### ISSUE TITLE
Deterministic manifest address

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1006]
#### Summary
When I upload a tar file using the `/dirs` endpoint twice I get different manifests. It would be nice if there was a way to upload the same file twice and getting back the same reference.

**Comment by zbiljic** [comment]
This is intentional behavior, random obfuscation key is generated for each manifest (to prevent some possible attacks, for example [Known-plaintext attack](https://en.wikipedia.org/wiki/Known-plaintext_attack)).

@zelig can provide much better explanation about this.

**Comment by zelig** [comment]
this is still annoying. we should be able to set the obfuscation key deterministically

**Comment by agazso** [comment]
I can imagine having a query parameter on the endpoint where you can pass in the obfuscation key.

**Comment by zbiljic** [comment]
@zelig Of course, I am not opposed to this. Support for that is in the manifest library. Only question is how do we want to implement this change.

**Comment by Eknir** [comment]
@zbiljic , what about the suggestion by @agazso ?

**Comment by zbiljic** [comment]
@Eknir I do not have any opposing arguments. There are numerous possibilities for solving this, some could be done without user involvement.

However, as I mentioned, I would want comment from @zelig about this, as discussion contradicts his previous comments.
One comment here is that we should create obfuscation key deterministically, which should be possible, and that can be done, I would just like some confirmation about this.

**Comment by Eknir** [comment]
Hi @agazso , I was trying to make a user story out of this, and it actually strikes me that I couldn't find a real reason why a user would want this, apart from "it would be nice to have this". I also believe this myself. Actually, I realized this is due to not understanding why similar content would have a different hash.
Would you agree that this "not understanding" is the real reason? Do you think that this issue can also be solved with a proper reasoning as to why the address of similar content uploaded via the `dirs` api is different?

**Comment by Eknir** [comment]
Note: I also don't know why this is the case myself. Maybe @zbiljic can enlighten us (I ready up about the known-plaintext attack, but still don't understand)?

**Comment by agazso** [comment]
> Hi @agazso , I was trying to make a user story out of this, and it actually strikes me that I couldn't find a real reason why a user would want this, apart from "it would be nice to have this". I also believe this myself. Actually, I realized this is due to not understanding why similar content would have a different hash.
> Would you agree that this "not understanding" is the real reason? Do you think that this issue can also be solved with a proper reasoning as to why the address of similar content uploaded via the `dirs` api is different?

By design static content stored on swarm is content addressed. That means if I upload a file I get back its content hash as its address. When I upload the same file twice I get back the same hash. Therefore at any time I can verify if the content integrity and has not been tampered with. This makes the system trustless. (With dynamic content (e.g. Single Owner Chunks) the integrity is provided by the signature).

When I upload a directory I would assume the same integrity requirements. I upload a directory twice, I get back the same hash. If I understand correctly the manifest changes each time because there is a random obfuscation key attached to it and the reason for that to protect against certain attacks when the content is encrypted by swarm, similar to a nonce. If this is correct then I think this is not necessary in the case the content is not encrypted by swarm (or it can be constant). In the case of encrypted content, this obfuscation key could be either provided by the user (for example by providing as a query parameter) or returned along with the content hash so that the user can verify the hash on the client side.

There are more practical user-stories I can come up with if you want, but I think this is a fundamental aspect of swarm so it would be good if we had a shared understanding and agreement about this.

**Comment by zelig** [comment]
the obfuscation should only be used whe the manifest is encrypted.
my earlier comment saying it should be custom configable is silly, sorry.

**Comment by Eknir** [comment]
Documentation:
@significance wants to add a little info box

**Comment by significance** [comment]
added a ticket to bee-docs https://github.com/ethersphere/bee-docs/issues/162

**Comment by significance** [comment]
@Eknir feel free to close when you get a moment
