### ISSUE TITLE
Batch chunk insert

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#1019]
# Task
When building data structures on top of Swarm, it becomes essential to add multiple chunks in single API for several reasons
1) To Batch all the insert, delete operations to make them atomic
2) When loading large amounts of data, the index chunks inserted one by one is very slow

So if the chunk API takes multiple chunks and inserts them  (like the file API which uses multipart to upload multiple files),
then it would definitely help the clients

## Acceptance criterea
Insert multiple chunks in one shot

**Comment by jmozah** [comment]
@Eknir what is your opinion on t is issue?

**Comment by Eknir** [comment]
I spoke about this with @agazso , he had some questions. @agazso , could you please ask them here? Also, I'm curious to hear the opinion of @acud .

I also have some questions:
Related to 1; why exactly do you need this atomic operation? Even though the operation might seem atomic, the internals of Bee can not guarantee that the request is processed as a whole. 
Related to 2; you could call the API with multiple go-routines, thus making the operation not sequential. This is how we would do it internally anyways.

**Comment by acud** [comment]
This changes the semantics of our API spec, and I am not sure how much it is needed. I am also not sure we have bandwidth to pursue this within the team.
@jmozah how many chunks are you trying to push through the chunk API? and why isn't the `bytes` api good for such amounts? if you need to upload large amounts of content addressed chunks, `/bytes` is what you need, correct me if I'm wrong.

**Comment by agazso** [comment]
@Eknir you basically covered my questions :)

It would be good to understand the use-case. The `/bytes` is appropriate when you are uploading amounts of bytes that belongs together (e.g. one 1GB blob). It also creates the intermediate branching node chunks containing the leaf chunk hashes. 

I can imagine that this kind of operation may be useful when trying to upload big number of chunks at once which may not belong together. For example you have lots of small (<4096 bytes) JSON documents that may reference each other. In that case you could try uploading them in parallel as a workaround. That would create an excess of HTTP connections but I think the bottleneck would be disk IO and chunk syncing anyhow.

**Comment by acud** [comment]
> the bottleneck would be disk IO and chunk syncing anyhow

Correct.

**Comment by jmozah** [comment]
@Eknir @agazso 

> 1; why exactly do you need this atomic operation? Even though the operation might seem atomic, the internals of Bee can not guarantee that the request is processed as a whole.

It is like a batch operation in leveldb. Atomic operations are from the client point of view. If i can send in a bunch of chunks and get an ack from Swarm (which means that the chunks are written to Swarms local DB), i can say it is atomic from my perspective. In my KV store you can create a bunch of operations and send them in batch and i need these chunks to reach bee in one shot and get an success/failure for the batch operation.

This is not new, for ex: RDBMS atomicity is also like this, they guarantee atomicity until they give it to kernel, then it is up to the driver and disk micro controller to decide when to write to the actual disk.. MySQL does a 10ms fsync, anything until that time is basically on the mercy of the kernel. (replace kernel with Swarm here). I hope you get my point.


>2; you could call the API with multiple go-routines, thus making the operation not sequential. This is how we would do it internally anyways.

Sending multiple chunks separately is a very un-optimized operation even if they are done parallely.. sending chunks multiple times is super slow compared to uploading  a large blob in one shot. I of course use multiple connection pools to reduce TCP overhead and multiple go-routines to send them parallelly. The issue is that the bee load will shoot up and  other side effects crop up like https://github.com/ethersphere/bee/issues/867, https://github.com/ethersphere/bee/issues/877

@acud  @agazso 

> how many chunks are you trying to push through the chunk API? 

Depends on the initial file upload. I used 50000 chunks (which is a very small load) and it takes more time, compared to uploading the entire content as one /bytes blob. So uploading the entire file as /bytes is of-course better. But unfortunately i cannot use .bytes for my usecase (see below).

> and why isn't the bytes api good for such amounts? 

Very good Question.  Imagine a Key Value store. when someone adds a Key and Value to the store, the key is added in the Index and the value is stores as a chunk or a /bytes if the value is bigger then 4K. The index stores only the reference of the value. Now imagine someone inserting several Key Values and for every Value a chunk is stored.

I cannot use a /bytes API because the **chunks are not related** and not in any order. They are independent and can grow. So they need to be stored and addressed as a chunk in the system. If we use a leveldb like immutable log files that store all the values together, then traditional problems like complexity in mutability of values, log merging, searching in multiple logs, kinda issues will arise. Hope you get the point.


@agazso
>I can imagine that this kind of operation may be useful when trying to upload big number of chunks at once which may not belong together. For example you have lots of small (<4096 bytes) JSON documents that may reference each other. In that case you could try uploading them in parallel as a workaround. That would create an excess of HTTP connections but I think the bottleneck would be disk IO and chunk syncing anyhow.

Rightly said. These chunks are not related to one another. Uploading them in parallel is slow compared to uploading the same amount of data in one TCP call. don't you agree? Also the disk IO is not an issue, disk IO is fast compared to network IO. Syncing will of-course be an issue, but that will be the same even if we upload through a ./bytes API. 

@acud 
> the bottleneck would be disk IO and chunk syncing anyhow

I am not worried about syncing for now,. i  trust that BEE team will improve sync time in future..
Disk IO will be the same even if use /chunks or /bytes. Infact it will be less if we use .chunks as network IO will dominate disk IO.
 But i am concerned about uploading time of those chunks as it affects the UX of the client.

**Comment by Eknir** [comment]
Hi @jmozah ,

Thanks for taking the time to answer the questions. I cannot judge on the technical validity of this, but perhaps @agazso, @zelig and @acud can take these points in the ongoing discussion on API (re)design.

As for the prioritization. Indeed, I do believe that right now, we have more important things to work on and don't have the capacity to tackle this. 

I will move this issue to the icebox and would expect that the people who work on the API redesign either close this issue if you are not convinced by the arguments of @jmozah or close the issue if the batch chunk insert is integrated in the plan for API re(design).

Thanks.

**Comment by acud** [comment]
This is addressed with the new chunk streaming API from @aloknerurkar
