### ISSUE TITLE
Alternative name resolution client support

### ISSUE THREAD

**Issue by paxthemax** [ethersphere/bee#1023]
# Description

In our original proposal for name resolution for Swarm, it was planned to support multiple name resolution clients, namely for:

1. ENS suite (deployed on any compatible chain)
2. RNS for RSK/RiF
3. File based (akin to loading a HOSTS file)

I would propose to revisit this topic. The resolver can be significantly simplified if there is no requirement to support clients other than ENS. Additionally, it would be good to clarify if a a file based client is necessary at this time.

## Outcome

I would say we either:
1. Implement a stub resolution client for file based resolution
2. Remove multi-client support and simplify the resolver

**Comment by Eknir** [comment]
You list them in order of priority. 

According to my understanding, we already support 1 and 2 (2 not officially supported as it is not tested). Supporting 3 is a nice to have, but definitely not something to spend attention on right now.

Given that the name resolution works and doesn't give us problems in the current implementation, I would personally just leave this as is.

**Comment by Eknir** [comment]
Moving to icebox
