### ISSUE TITLE
Cleanup TAR archive paths during collection upload

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1024]
# Task

When the TAR archive is create with questionable paths, creating collection may have some issues.

related issue: #999 

If we consider some simple TAR archive structure as:

```
index.html
js/app.js
css/app.css
```

we have structure which will be properly read, and collection created from it.
Reading some file from our `bzz` endpoint, for example `http://example.com/bzz/<reference>/js/app.js` should return expected file.

It is also quite possible that the user creates archive that looks like this:

```
./
./index.html
./js/app.js
./css/app.css
```

Note that this is also acceptable structure, and opening that archive should resolve properly (on *-nix systems), however accessing `http://example.com/bzz/<reference>/./js/app.js` will be resolved (by the router) to `http://example.com/bzz/<reference>/js/app.js`, which is not path that was stored in the collection (i.e. `./js/app.js`).
This specific issue can easy be solved by cleaning TAR paths during collection upload, as noted by @janos [here](https://github.com/ethersphere/bee/issues/999#issuecomment-733640369).

With that change, we should have following mapping:

```
./              -> "" (directory will not be added to collection)
./index.html    -> index.html
./js/app.js     -> js/app.js
./css/app.css   -> css/app.css
```

It is also quite possible that archive contains paths that are backward from the root:

```
index.html
../js/app.js
../css/app.css
```

In this case before-mentioned `Clean` function will no change paths (eve if it does clean some other possible path errors).

Those paths will be added in the collection as is, and while they are valid, accessing them is not possible through HTTP.
Trying to retrieve `http://example.com/bzz/<reference>/../js/app.js` will resolve to the `http://example.com/bzz/js/app.js`, at which point we lose the actual reference (URL encode does not work in this case).

Also note that there may be many variations to file structure, this is just one simple one.

Adding support for `Clean` function should be done, and with it we should resolve high percentage of issues that user may make.

As far as resolving this other issue we have several suggestions:

- do nothing in code and have documentation that notes that is is up to the user to make sure archive is "valid"
  - this may be best option
  - collection upload will still be accepted, it is just that user will not be able to access some files
- process archive first, and if any path starts with `..` reject whole request
  - we end up processing archive twice (although first pass should be much faster, second one will actually create files)
- skip all files that start with `..`
  - user may end up with some missing files, and may question what happened

In addition to this, there is also the point of having separate API for managing collections (manifest) structure.

## Acceptance criterea

We should successfully process (or rejects) different kinds of paths in TAR archive.

**Comment by agazso** [comment]
As a user of this my preference would be to reject those requests which result in manifests with missing or unreachable files. 

This approach is often called 'fail early' or 'fail fast'.

Imagine that you use an automated process for uploading files (backup for example), but the files you create are not acceptable for Swarm. Your upload process is successful, so you think it's working well. Months later you try to recover a backup and then you realize it was all broken and you lost all your data. 

I understand that this may not be the most important feature right now and documenting the behavior could mitigate the issue. But it won't help those who just lost their data :)

**Comment by Eknir** [comment]
Hi @zbiljic ,

Thank you for clearly outlining your points here.

I would suggest the following:

We create issues for the following tasks:
1. Implement clean
2. Document what type of directory structures are invalid
3. Fail on trying to upload invalid structures

I would assess that 1 and 2 are high priority, easy tasks and 3 somewhat lower priority, more difficult task. Having issues for all 3 of these allows us to plan this properly.

I would be happy to make these issues, let me know!

@agazso , while I see your point, I would personally not prioritize to make this feature 100% perfect as of now. The reason is that there are other reasons why a user might loose his file (or not use Swarm at all), which need to be fixed as well.

**Comment by zbiljic** [comment]
check comment: [1027#issuecomment-740502562](https://github.com/ethersphere/bee/pull/1027#issuecomment-740502562)

**Comment by Eknir** [comment]
I would personally say that a perfect implementation is not required for now. We should document, however, what works and what doesn't work with regards to paths and on the different os's. This documentation should be in docs.ethswarm.org (@sig). 

Perhaps, @zbiljic , you could write a hackmd where you explain what the user should know. We can put this markdown somewhere in the code (doc.go). Then @significance can translate that and put it in the required place in the docs.

Also, we should have an issue (but probably put it in the icebox) for implementing this perfectly on the code-side.

**Comment by zbiljic** [comment]
This is not so much of a `bug`, as issue for requesting comment on ideas how to ultimately have a solution that is acceptable.
