### ISSUE TITLE
Runtime multiresolver configuration

### ISSUE THREAD

**Issue by paxthemax** [ethersphere/bee#1025]
# Description

Currently the `multiresolver` package (part of the greater `resolver` package) interface supports runtime changes to the resolution chain for all domains. 

The perceived advantage would be adding more name resolution clients without restarting the bee client. This feature was a part of the resolver as a standalone service. On the other hand, name resolution configuration could be configured pretty stable (in the default case, ENS is used, while connected to an Ethereum node). Changing the name resolution config might warrant a restart.

## Proposal

I propose we discuss and decide weather this feature is required and make the appropriate changes:
- If we want this feature, then we should expose the multiresolver to the debugapi and add appropriate endpoints
- If we do not want this feature, multiresolver can be significantly simplified.

**Comment by Eknir** [comment]
Hi!

Great, thanks for pointing this out.

I would suggest to leave the multiresolver as-is and put the feature of runtime change of resolver endpoint to the icebox.

**Comment by Eknir** [comment]
Moved to icebox
