### ISSUE TITLE
Perform clean for TAR archive paths

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1026]
# Task

We should use `filepath.Clean` for paths fro TAR archive.

related issue: #999

**Comment by Eknir** [comment]
This needs documentation. @zbiljic , could you please provide an a list or some text, mentioning what kind of directory structures cannot be uploaded to Bee?

**Comment by zbiljic** [comment]
I think more in the way that we should support any "normal" directory structure (that is archived using TAR). Current state is that there might be some cases that are not covered (because we have not encountered them yet).

As noted in the #1024 (where further discussion should be continued), if someone (when creating TAR archive) adds some files/directories, that are in some parent directory, that is relative from the current working directory from which archive is being created, even though paths are valid strings, they will not be resolvable through Bee.
Issue can be read for some examples, as well as suggestions for possible changes.
