### ISSUE TITLE
uploaded a 50MB video file and it cannot be downloaded fully from another node

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/bee#1028]
#### Summary
after uploading i tried to play it from a different bee node, but it gets stuck.

then tried to wget it, but **wget loops with only a couple of seconds of delay**, as if my client was certain that it's not available in Swarm:
```
$ wget --verbose -c "http://localhost:1633/files/8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2"
--2020-11-30 14:36:04--  http://localhost:1633/files/8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:1633... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 54224667 (52M), 52651803 (50M) remaining [video/mp4]
Saving to: ‘8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2’

8d222325e69a2d3d7b0b4b73f984a4125497b51744edb6418507   2%[+++                                                                                                                   ]   1.50M  --.-KB/s    in 0s      

2020-11-30 14:36:07 (0.00 B/s) - Connection closed at byte 1572864. Retrying.

--2020-11-30 14:36:08--  (try: 2)  http://localhost:1633/files/8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2
Connecting to localhost (localhost)|::1|:1633... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 54224667 (52M), 52651803 (50M) remaining [video/mp4]
Saving to: ‘8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2’

8d222325e69a2d3d7b0b4b73f984a4125497b51744edb6418507   2%[+++                                                                                                                   ]   1.50M  --.-KB/s    in 0s      

2020-11-30 14:36:11 (0.00 B/s) - Connection closed at byte 1572864. Retrying.

...
```

the content is locally pinned on the uploading node (which is running and online), and wget works there as expected.

#### Steps to reproduce
```
$ bee version
0.4.0-625d64e
```

```
curl --verbose --data-binary @The\ Covid\ Cult\ _\ Thomas\ E.\ Woods\,\ Jr.-mcm8Sc8f66o.mp4 -H "Content-Type: video/mp4" "http://localhost:1633/files?name=The%20Covid%20Cult%20_%20Thomas%20E.%20Woods,%20Jr.-mcm8Sc8f66o.mp4"
```
the file itself is this one:
```
youtube-dl "https://www.bitchute.com/embed/mcm8Sc8f66o/"
```

[http://localhost:1633/files/8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2](http://localhost:1633/files/8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2)

#### Expected behavior
should play fully, even if only with some delays.

wget should be able to download the file.

#### Intention with this bug report

i'm a seasoned programmer and i'm willing to learn/debug. i don't care about this specific file itself, it was just a file censored on the day when i tried bee.

so, feel free to ignore/close this if there already are similar tests done and debugged. and also feel free to instruct me on how to proceed, what to read, etc.

i'm also wondering if there's a way to "force reupload" the file again? simply firing up the same upload request doesn't seem to do much besides locally splitting it and noticing that it's already uploaded into the wider swarm.

**Comment by acud** [comment]
@attila-lendvai nice to see you here :)

did you wait for the file to be synced before trying to retrieve from the other node? did you try later and get the same error?

**Comment by attila-lendvai** [comment]
> did you wait for the file to be synced before trying to retrieve from the other node?

yes, it was days prior.

the worst that **may** have happened is that the uploader machine got rebooted while still uploading, but i don't remember anything like that.

> did you try later and get the same error?

just tried it again on my laptop, whose bee node has been restarted since then, but it's still the same: `wget -c` loops rather fast.

**Comment by attila-lendvai** [comment]
let's assume that some chunks of this file is missing from the network.

is there a way to force the re-upload of that file? it seems to me that if i trigger the upload once again on my node, then it just finishes after splitting. maybe because this file was already "seen by the network" (as per the doc)?

```
$ curl http://localhost:1633/tags/2843703716 | jq
{
  "total": 13346,
  "split": 13346,
  "seen": 13346,
  "stored": 13346,
  "sent": 0,
  "synced": 0,
  "uid": 2843703716,
  "name": "unnamed_tag_1607201643",
  "address": "8d222325e69a2d3d7b0b4b73f984a4125497b51744edb64185073c79ddfbb9b2",
  "startedAt": "2020-12-05T21:54:03.558719803+01:00"
}
```

sidenote: it's rather confusing that the same concept has multiple names throughout the codebase ("uid", "Swarm-Tag-Uid", "tag"). it should be something specific enough that it could be the same everywhere. *upload-tag*, or *chunk-tag*, or *chunk-group*, or whatever fits better. i lack the perspective to give an informed suggestion.

**Comment by Eknir** [comment]
> is there a way to force the re-upload of that file? it seems to me that if i trigger the upload once again on my node, then it just finishes after splitting. maybe because this file was already "seen by the network" (as per the doc)?

There exists an issue for this: https://github.com/ethersphere/bee/issues/1051

> sidenote: it's rather confusing that the same concept has multiple names throughout the codebase ("uid", "Swarm-Tag-Uid", "tag"). it should be something specific enough that it could be the same everywhere. upload-tag, or chunk-tag, or chunk-group, or whatever fits better. i lack the perspective to give an informed suggestion.

I think this is something which @zbiljic is currently improving

**Comment by Eknir** [comment]
@attila-lendvai , the situation that you describe here is something we are constantly improving. There is no clear-cut solution here, as the issue could either be in push sync, retrieval, syncing or our node management. We are constantly working on improving these issues, as well as adding stuff so we have better observability on what happens on the cluster (so we can properly debug situations like this).
Could you please try retry the scenario? Perhaps one of the changes that we did last week improved the situation.

**Comment by attila-lendvai** [comment]
@Eknir i was just about to come here today and close this issue, because i have also understood that it's practically an issue saying that "swarm is not done"... well, sure captain obvious... :)

so, i'll close this and keep hacking.

and a very big +1 for improving observability!
