### ISSUE TITLE
Handshake timeout in CI

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#103]
There has been an error while receiving a handshake message on GitHub Actions on macOS which tends to be slow.

```
=== RUN   TestConnectDisconnect
--- PASS: TestConnectDisconnect (1.10s)
=== RUN   TestDoubleConnect
--- PASS: TestDoubleConnect (1.48s)
=== RUN   TestDoubleDisconnect
--- PASS: TestDoubleDisconnect (2.77s)
=== RUN   TestMultipleConnectDisconnect
--- PASS: TestMultipleConnectDisconnect (0.68s)
=== RUN   TestConnectDisconnectOnAllAddresses
##[error]    TestConnectDisconnectOnAllAddresses: connections_test.go:181: handshake: read synack message: timeout
--- FAIL: TestConnectDisconnectOnAllAddresses (6.03s)
```

I have pasted more test results than just the one that failed as a sign that the root cause may be indeed only the slower environment where the test is run. It may be just goo enough to raise the timeout which is currently 5 seconds. WDYT @pradovic @acud ?

**Comment by pradovic** [comment]
I already wanted to do it, but I switched it back as per PR comments, just left it in Hive as it was necessary, so I agree 👍 Especially, since the env is really slow.

**Comment by pradovic** [comment]
I think we should actually maybe increase all timeouts in read/write mesagges. Actaully, maybe put the same timeout for all of them, and use a special one only if needed by the actual protocol? Whad do you guys think?

**Comment by Eknir** [comment]
What is the status on this ticket @pradovic @janos ?

**Comment by janos** [comment]
We do not have this timeout anymore. Could we close this issue @pradovic?

**Comment by pradovic** [comment]
I think so, yes 😀
