### ISSUE TITLE
Uploading without specifying "Swarm-Index-Document" results in a redirect loop

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1030]
#### Summary
When you upload a tar file but you don't provide the `Swarm-Index-Document` header value then when trying to download access the reference without a filename, it returns a redirect answer to the reference without a filename.

#### Steps to reproduce
1. Create a tarfile
2. Upload it without `Swarm-Index-Document`
3. Access the reference without specifying a filename

#### Expected behavior
It should not return the same address, when there is no filename. Instead a 404 could be returned.

**Comment by zbiljic** [comment]
@agazso Not sure what problem you are encountering here. If `Swarm-*-Document` headers are not specified, "standard" flow will occur.

Only redirect that may account to your observation is the one to add the slash the the end of reference (which is not related to the process of serving files). This one is done on the HTTP router level; None of it is related to specifying those custom headers.

When accessing manifest reference (without ending slash):

```bash
http http://localhost:8081/bzz/<reference>
```

you should receive this response:

```bash
HTTP/1.1 308 Permanent Redirect
...
Location: /bzz/<reference>/
...

<a href="/bzz/<reference>/">Permanent Redirect</a>.
```

which is just used to redirect to same URL, just with slash.

And then when you try to access that path, i.e.:

```bash
http http://localhost:8081/bzz/<reference>/

OR

http http://localhost:8081/bzz/<reference>/non_existent_path
```

you should receive expected error:

```bash
HTTP/1.1 404 Not Found
...

{
    "code": 404,
    "message": "path address not found"
}
```

This change was added via in #690, exact change [here](https://github.com/ethersphere/bee/pull/690/files#diff-ce9544cf2f046068d8443822bbe9e602876c44adb5e55e68381ff1ce4e69283cR81).

**Comment by agazso** [comment]
Sorry, I think I mistakenly uploaded a wrong tarfile, like in #999

**Comment by Eknir** [comment]
Hi @agazso @zbiljic 

How does this issue related to #1026 and #1024 and #999 and the PR #1027 ?

Generally, it would be great if we could move the respective issues to the correct place in our boards, close duplicates and make conclusions / tangible issues under threats that were posed as a question.

Could the issue authors of above-mentioned issues do this?

Thanks
