### ISSUE TITLE
Inconsistent peer in addressbook

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1034]
#### Summary

The problem was first observed during testing for `0.4.0` release. While finding `ClosestPeer` so that `pushsync` can find peer to which to push chunks. If the closest peer happens to be the one that is 'inconsistent' pushing will fail, and note will try another peer. Since this is done for each chunk, we end up with a lot of errors, even though process eventually completes.

NOTE: For the mentioned release, special check was added, which removes problematic peer. This 'hotfix' should be replaced by some better solution.

What was observed in testing for this problem is that address book for 2 different peers contains underlay addresses which have same libp2p peer ID (underlay ID).
More specifically, on my node, for libp2p peer ID `16Uiu2HAmVXyQSNKVcrpVdNQu1BeSoxgS4Na4wjNxALUpLajUmDBT`, there are two addresses:

| overlay | underlay |
| --- | --- |
| `bfcdfe13d077b048981f616cec93502d72f3f119e69994d9d50a77b368bbe997` | `/ip4/3.91.233.180/tcp/31000/p2p/16Uiu2HAmVXyQSNKVcrpVdNQu1BeSoxgS4Na4wjNxALUpLajUmDBT` |
| `c8b062a111fefa8fa543ed0f69dc8dc778cdd41be1961739551c826b762fd1f6` | `/ip4/54.161.106.204/tcp/31000/p2p/16Uiu2HAmVXyQSNKVcrpVdNQu1BeSoxgS4Na4wjNxALUpLajUmDBT` |

(Note that there are additional peers in address book, these two are just relevant for this explanation.)

During node startup process, it starts building peer topology by using peers from address book (where these underlay addresses are found). When the first peer is processed, the connection to the peer is established using underlay address, and (if established) the peer connection is saved, and related to the the underlay address with that peer (i.e. `bfcdfe13d077b048981f616cec93502d72f3f119e69994d9d50a77b368bbe997` to `16Uiu2HAmVXyQSNKVcrpVdNQu1BeSoxgS4Na4wjNxALUpLajUmDBT`).

After that, when we eventually come to second peer, check is performed whether the peer (`c8b062a111fefa8fa543ed0f69dc8dc778cdd41be1961739551c826b762fd1f6`) is already connected, and since we are checking with underlay address peer ID (`16Uiu2HAmVXyQSNKVcrpVdNQu1BeSoxgS4Na4wjNxALUpLajUmDBT`), function completes, and we save that peer in our list as connected, and carry on (even though we are actually not connected).

At the point when attempt is made to send chunk to the peer, because there is no actual connection the call fails.

Latter on, the topology layer will just add that same peer again, and we have same loop again.

Now, what actually happens if we were to try connect to the second peer in this table is that we would not succeed, and (after some retrying, which takes some time), we would remote that peer from the address book.

The ID from `go-libp2p-core` that is causing issues in the description notes that `"Connection IDs may repeat across restarts"`.
Since both IP addresses seem to belong to Amazon AWS, what might have happened is that instance was migrated to different host, while keeping same internal peer ID, which caused this issue to become visible.

#### Steps to reproduce

There is no way to actually cause this issue simply. Maybe if one would actually "hack" address book of a node, and manually adding some host which will cause this problem.

#### Expected behavior

We should not be trying to send data to peers that are not connected. This means that we should have better check on whether the peer is actually connected.

#### Actual behavior

Application keeps trying to communicate with the peer which is not connected.

**Comment by zbiljic** [comment]
A way to reproduce this problem (found while testing the fix for this) is to have a node cluster, remove `swarm.key` from one node, after which that node should be restarted (until it receives different IP address).
After this is done, some other node can be restarted, and it should have "old" entry in address book, after which it will attempt to connect few times to that (no longer address), before in the end removing it from address book.

One remaining problem found during this testing is that if it happens that node that had its `swarm.key` removed (which changed `overlay` address) ends up on the same IP address (meaning it has same `underlay` address), it will successfully connected to peer. It would seem that upon connection, overlay address is not verified.

**Comment by Eknir** [comment]
Hi @zbiljic , First of all, thanks for the excellent explanation of the issue.

Would you say that this bug is completed with #1032 ? 

> One remaining problem found during this testing is that if it happens that node that had its swarm.key removed (which changed overlay address) ends up on the same IP address (meaning it has same underlay address), it will successfully connected to peer. It would seem that upon connection, overlay address is not verified.

Could you describe this to me in a bit more detail? Perhaps, it would be best to create a new issue out of this.

**Comment by zbiljic** [comment]
Hi @Eknir, my explanation in second comment was suppose to explain that it is different part of issue from the one resolved in #1032.

As far as more detailed explanation, I do not think something more can be said here. Main point about whole issue is that node might end up with "invalid" cluster topology. Main thing that can be done in that case is to find a way to "clean up" the state slowly. Fix done in the #1032 should have effect that eventually that state will be cleaned at some point.

They way how I reached "one remaining problem" is generally unlikely, and at worst node might have attempts to communicate with those invalid peers, after which it will revert to other(s). I am still exploring around this. Current "hotfix" around this does exists, however it may not be 'ideal' solution. We should be able to detect disconnected node more quickly, and recover. Once I have more details about this problem I will update here and create separate issue for it.
