### ISSUE TITLE
Timeout of retrieve / pushsync

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1044]
**Story**
As an upstream node, I want to give my downstream nodes sufficient time (depending on my distance to the content) to try and get my content, such that my content will be delivered to me if the content is retrievable.

**Background**
In bug report #843 , it was discovered that push sync continuously retried to re upload to peers that returned an error. Issue https://github.com/ethersphere/bee/pull/947 fixes this partly by retrying to a different peer after an error is returned. 
An outstanding problem is that we have a fixed timeout for each request.This is wrong, as the timeout should be more for content that is further away, to allow each peer on the hop to do several retries. Now, if my downstream peer retries 5 times and his downstream peer retries 5 times, I probably time out. I don't want this, because maybe the content is available.

Quoting [comment](https://github.com/ethersphere/bee/issues/843#issuecomment-723009053)

> When we don't get an answer from a peer in time, this is an error. The time allowance is increasing per maximum expected hop count (to allow downstream peers to find the content and retry themselves if needed) -- log(distance downstream peer, chunk).

@zelig requested to give a TTL with the request. Food for thought: what about privacy? If the initial TTL is x, then I know that my peer, who gives me a TTL of x is the final requester.

**Comment by Eknir** [comment]
@acud , could you briefly outline your proposal to this user story?

**Comment by Eknir** [comment]
A specific way to solve this issue was suggested in #1081

**Comment by acud** [comment]
will be addressed as part of #1441
