### ISSUE TITLE
api request logline should have traceid

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1054]
we are currently logging HTTP requests on bee, but the loglines do not include the trace information. this could be helpful to filter logs and correlate traces to errors that we see coming from a related request.

cc @janos WDYT?

**Comment by janos** [comment]
In order for log lines to have trace id, is must exist in the net/http handler. Currently tracing is on the lower p2p level, but adding traces to the http level can be added with opentracing HTTPHeadersCarrier extraction into the request context in one http middleware that could be set for every request. If the tracing span is not in request headers, a new one can be created there. The basic logic for the middleware function is in this example https://github.com/opentracing/opentracing-go#deserializing-from-the-wire.

Logging calls in http handlers have to be changed use a logger with the trace id field set, similarly as it is done on the p2p layer.

**Comment by Eknir** [comment]
Added label RFC. While I don't get the specifics of this issue, I'm all in for improving our instrumentation and debug possibilities. These are IMO always a priority, especially if you feel the real need to have them during a debug session.

**Comment by Eknir** [comment]
@acud , is this issue ready for implementation?

**Comment by acud** [comment]
yeah so I think that we can do this. The task is to add a middleware that will try to get a `Swarm-TraceId` header from the http request, if it is not found, the middleware should inject a new opentracing span into the context of the request.

I'm tagging https://github.com/ethersphere/bee/issues/724, since we could have this done in a way which could allow other tracing capabilities which are more granular than what we have today. So, perhaps have the tracer to inject onto different carriers, rather than just to a `p2p.Header` object. This is discussed in #724
