### ISSUE TITLE
Changing 'swarm' key causes invalid connections to be made

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1057]
#### Summary

Changing `swarm.key` of a peer (no real reason to do this) causes other peers to mark connections to same peer (with old file) to be marked as successful.

#### Steps to reproduce

To reproduce the issue (note that id does depend a bit on the timing, and may not happen every single time):

* create a cluster of nodes (3 should be enough)
* start all nodes, in order to create proper P2P topology
* stop one one of the nodes
* delete `swarm.key` of that stopped node
* start that node again

Kademlia process that manages connected peers occasionally goes through the list of known peers, and if the stopped node is started again (and is on the same `Multiaddr`), that previous peer will be marked as connected, even though main connection is actually made to that new Swarm peer.

#### Expected behavior

We should actually try to connect to same address, expecting "old" Swarm peer, which should return some internal error, which should eventually (after several attempts) remove that "old" peer from address book.

**Comment by Eknir** [comment]
Hi @zbiljic, you can move this issue from core: backlog to core: active sprint. Don't touch me pipeline in core: Active sprint should not be touched ;)

I do it for you now. Thx

**Comment by zbiljic** [comment]
Sorry @Eknir, I moved ticket within "core: Active sprint" board, not sure what happened.
