### ISSUE TITLE
Pin should fetch chunks from the network

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1062]
# Task

When pinning, we should try to fetch chunks from the network, if they cannot be found locally.

**Comment by Eknir** [comment]
This feature needs documentation:

- Pinning now fetches from the network if the content is not locally available
- User needs to be warned that, when the content cannot be fetched, the pincounters go into a corrupt state (which is also the case when we pin during upload and cancel stop the operation mid-way).
