### ISSUE TITLE
Bee service won't start due to config param

### ISSUE THREAD

**Issue by hlbcal** [ethersphere/bee#1072]
I have to remove "=" from config param in  "/lib/systemd/system/bee.service", otherwise Bee service won't start. Below is my workable copy:

[Unit]
Description=Bee - Ethereum Swarm node
Documentation=https://swarm-gateways.net/bzz:/docs.swarm.eth/
After=network.target

[Service]
EnvironmentFile=/etc/default/bee
NoNewPrivileges=true
User=root
Group=root
ExecStart=/usr/bin/bee start --config /etc/bee/bee.yaml
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target

My systemd version is:
systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

My OS is: 
ARMBIAN 5.67 user-built Debian GNU/Linux 9 (stretch) 3.10.108

On my hardware box, User=bee and Group=bee are also not working, I have to change it to root.

**Comment by vandot** [comment]
Hi @hlbcal thanks for the report.
As we discussed on telegram its due to old version of systemd.
Fix is ready and it will be merged and published with next release.
