### ISSUE TITLE
Bee.Service Documentation URL returns 404

### ISSUE THREAD

**Issue by him2him2** [ethersphere/bee#1075]
#### Summary
The URL provided by bee.service (https://swarm-gateways.net/bzz:/docs.swarm.eth/) returns 404(file not found).

#### Steps to reproduce
Followed URL provided by service description.

#### Expected behavior
Should probably point to https://swarm-gateways.net/bzz:/docs.swarm.eth/docs/

#### Actual behavior
URL point to https://swarm-gateways.net/bzz:/docs.swarm.eth/

**Comment by Eknir** [comment]
Hi @him2him2, I tried to reproduce your issue, but could not do this.You can always have a look at https://docs.ethswarm.org/docs/. @vandot , perhaps it is better to point the package documentation to our web2 docs, to prevent this from happening in the future?
