### ISSUE TITLE
Error: could not connect to backend at http://goerli-geth.dappnode:8545

### ISSUE THREAD

**Issue by john-a-m** [ethersphere/bee#1077]
#### Summary
I was following the tutorial (https://medium.com/ethereum-swarm/how-to-run-bee-on-a-dappnode-raspberry-pi-7b4993ff7583) to make a raspberrypi run Bee.

#### Steps to reproduce
I get an error saying

> time="2020-12-29T08:45:12Z" level=info msg="could not connect to backend at http://goerli-geth.dappnode:8545. In a swap-enabled network a working blockchain node (for goerli network in production) is required. Check your node or specify another node using --swap-endpoint."
> Error: could not get chain id from ethereum backend: Post "http://goerli-geth.dappnode:8545": dial tcp: lookup goerli-geth.dappnode on 127.0.0.11:53: no such host

I ran `docker ps` on the pi but didn't see anything related to goerli-geth.

**Comment by john-a-m** [comment]
I got past this error by installing goerli-geth from the DappStore. However I have a new error now.

>time="2020-12-29T15:13:32Z" level=info msg="using default factory address for chain id 5: a6b88705036f2a56807af157c116b7dfcdabf968"
>Error: not a valid factory contract

**Comment by ralph-pichler** [comment]
Does `goerli-geth` from DappStore install your own goerli node? My guess would be that the node was not fully synced yet (bee does not check for that currently) which is why the factory contract looked empty (and therefore invalid). Did this start  working later?

**Comment by Eknir** [comment]
Hi @ralph-pichler , I would suggest to close this issue, as the work is now captured in #1086. @john-a-m , thank you for reporting. Please retry installing your bee node once it is fully synced and give us a heads up after #1086 is released. 

All the best,

**Comment by john-a-m** [comment]
@ralph-pichler I suspect that goerli-geth not being fully synced is the issue. I have a slow internet connection so right now I'm at `Blocks synced: 2349703 / 4052377`. Once my node is all caught up (hopefully this week) I will do as @Eknir suggests and reinstall Bee. I'll let you all know how it goes.
