### ISSUE TITLE
Inconsistent naming convention in API JSON responses

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1078]
#### Summary
The naming convention in the API JSON responses are inconsistent. For example there are cases when it's lowerCamelCase

https://github.com/ethersphere/bee/blob/b44ed2eb3c60de775f063ed58d15891dccd8ce37/pkg/api/pin_chunks.go#L111

There are cases when it's lowercase

https://github.com/ethersphere/bee/blob/b44ed2eb3c60de775f063ed58d15891dccd8ce37/pkg/debugapi/chequebook.go#L40

There are cases when it's kebab-case

https://github.com/ethersphere/bee/blob/b44ed2eb3c60de775f063ed58d15891dccd8ce37/pkg/debugapi/p2p.go#L22

I think the best would be to stick to one naming convention and use that everywhere. Assuming these are all equal from the perspective of the Go code, I would suggest using lowerCamelCase because that's the easiest to use from Javascript.

**Comment by Eknir** [comment]
@paxthemax , this could be something

**Comment by AuHau** [comment]
Even after #1613 there are still some inconsistencies. For example https://github.com/ethersphere/bee/blob/master/openapi/SwarmCommon.yaml#L108
