### ISSUE TITLE
API Stability

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1084]
# User story

## Story

As a consumer of the Swarm APIs, I want to have a reasonable certainty that they won't change anymore or be prepared when they change, such that I can build products on top of Swarm and/or don't need to relearn again when the API endpoints changed

## Acceptance criteria

- All envisioned changes to the API endpoints which can be done without touching the architecture of Bee are done
- For all API endpoints, we explicitly mention the stability in the API docs (https://nodejs.org/dist/latest-v6.x/docs/api/all.html#documentation_stability_index)
- A blog is written, detailing all our API endpoints 

## Tasks

| Index | Task | reasoning |  Done (1), or 0 |
|-------- | ------ |------------| -----|
| 0 |  POST bzz: return 201 instead of 200 | fits better with [http response codes definitions](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) | 1 | 
| 1 |  POST bzz: swarm-encrypt to swarm-encryption | more proper | 1 | 
| 2 |  POST bzz: swarm-tag-uid to swarm-tag | shorter | 1 | 
| 3 |  POST bzz: Content-Type (by `multipart/form-data` request) should be defined as `multipart/form-data; boundary=...` . Other file attributes can be placed in Content-Disposition header | 0 |
| 4 | GET  bzz/{reference}: use 408 request timeout error when request times out | more in line with semantic error code definitions | 0 | 
| 6 |  GET  bzz/{reference}: use error code 416 when applicable | when possible, use semantic error codes | 0 | 
| 7 |  GET tags?offset={offset}&length={length}: this is not implemented yet, but should be implemented | mentioned in BOS. There might be usecases and easy to implement. Requested by #985 | 0 | 
| 8 |  issue #1078 | improve consistency | 1 | 
| 9 | add 404 to API response code for GET tags/{id} | verify code and API doc congruence | 1 |
| 10 | document the PATCH tags functionality in API docs and in the book | | 0 |
| 11 | add chunk estimation to tar reader when uploading directories and do final chunk accounting after each file in the tar has been split + manifests | | 0 |

**Comment by Eknir** [comment]
Proposed API changes: https://docs.google.com/spreadsheets/d/1JE4wY0i9ASt4oRiO7Q0D7qfb70ZF4Ds5MjWbbQ-8UtU/edit#gid=1710849048

**Comment by Eknir** [comment]
Related: #1113

**Comment by Eknir** [comment]
- eliminate collections data chunk
- equate file reference  and path-less manifest
- restful pin API
- all error responses are correct and documented
- feed epoch support
- feed update state persistence
- manifest manipulation API
- manifest listing
- bytes(??)
- files endpoint obsoleted
- dirs endpoint obsoleted
- announcement of API release candidate

**Comment by Eknir** [comment]
Partly outdated, but we will update this and tackle this sprint

**Comment by acud** [comment]
This is stale and not up to date, closing
