### ISSUE TITLE
check sync status of eth backend on startup

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#1086]
# Task

We should check the sync status of the bee node before proceeding with startup. Running bee against a still syncing node leads to  unclear errors such as `invalid factory` (probably what was observed in #1077. Even if the node is already past the factory deployment block, the bee node might see some valid chequebooks as invalid or illiquid (therefore refusing valid cheques). Backend may still go out of sync while bee is running, but we should check at least on startup.

## Acceptance criterea

Node waits for synced backend to boot. Doesn't fail with `not a valid factory`.

**Comment by Eknir** [comment]
QA task: connect Swarm to non-sync'ed backend and report what the behavior of the node is
