### ISSUE TITLE
add uncashed amount to some cheque or cashout endpoint

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#1087]
# Task

Currently computing which cheques are uncashed (and to which amount) requires using two different endpoints and some client side computation. Exposing the uncashed amount as part of one of the endpoints can significantly simplify cashout scripts.

**Comment by Eknir** [comment]
Thanks Ralph,
I think this makes sense.

**Comment by Eknir** [comment]
For reference: current cashout script that could be simplified: https://gist.githubusercontent.com/ralph-pichler/3b5ccd7a5c5cd0500e6428752b37e975/raw/7ba05095e0836735f4a648aefe52c584e18e065f/cashout.sh

**Comment by Eknir** [comment]
@paxthemax , this could be something
