### ISSUE TITLE
Pin listing options are missing from autogenerated API docs

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1089]
#### Summary
The [listing of pinned chunks](https://docs.ethswarm.org/api/#tag/Chunk-pinning/paths/~1pin~1chunks/get) endpoint API documentation is missing the `offset` and `limit` optional query parameters. However, without specifying the `limit` parameter the endpoint only returns 100 items whereas there may be more items than that.

**Comment by Eknir** [comment]
@agazso, this is supposedly done. Could you please validate that?

**Comment by agazso** [comment]
I see this was added in the source code, so hopefully soon it will be also on the website

https://github.com/ethersphere/bee/blob/b4b6245d7e7379bfe50d371cefa10dda7e110db9/openapi/Swarm.yaml#L641-L658

**Comment by Eknir** [comment]
@significance ^^
