### ISSUE TITLE
Cashout script for Windows users

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1092]
# User story

## Story

As a Windows users, I want to automate the management of my uncashed cheques, such that I don't need to interact with the Bee APIs for each uncashed cheque

## Acceptance criteria

- There exists a Windows script with similar functionality as https://gist.github.com/ralph-pichler/3b5ccd7a5c5cd0500e6428752b37e975#file-cashout-sh
- The [documentation](https://docs.ethswarm.org/docs/) (repo [here](https://github.com/ethersphere/docs.github.io)) contains a reference to this script and instructions for Windows users how to use

**Comment by liang55** [comment]
Can I submit a python script?
python bee_cashout.py
[bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)

**Comment by czb0907** [comment]
> Can I submit a python script?
> python bee_cashout.py
> [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)

thank you，but there's a little problem with your code. I've made some changes `# -*- coding: utf-8 -*-
import requests
import json
import time

DEBUG_API='http://localhost:1635'
MIN_AMOUNT=1000

def getPeers():
	cheque_url="%s/chequebook/cheque"%(DEBUG_API)
	rtn_content = requests.get(cheque_url).json()
	lastcheques=rtn_content.get('lastcheques')
	peers=[]
	for info in lastcheques:
		peers.append(info.get('peer'))
	print(peers)
	return peers

def getCumulativePayout(peer) :
	cheque_url="%s/chequebook/cheque/%s"%(DEBUG_API,peer)
	rtn_content = requests.get(cheque_url).json()
	if rtn_content.get('lastreceived') is None \
		or rtn_content.get('lastreceived').get('payout') is None:
		return 0
	return rtn_content.get('lastreceived').get('payout')


def getLastCashedPayout(peer):
	cashout_url="%s/chequebook/cashout/%s"%(DEBUG_API,peer)
	rtn_content = requests.get(cashout_url).json()		
	cashout=rtn_content.get('cumulativePayout')
	#print(rtn_content)
	if cashout:
		return cashout
	else:
		return 0	 

def getUncashedAmount(peer):
	cumulativePayout=getCumulativePayout(peer)
	if cumulativePayout == 0:
		return 0
	else:
		cashedPayout=getLastCashedPayout(peer)
		uncashedAmount=cumulativePayout-cashedPayout
		return uncashedAmount

def listAllUncashed():
	peers=getPeers()
	for peer in peers:
		uncashedAmount=getUncashedAmount(peer)
		if uncashedAmount > 0:
			print(peer,uncashedAmount)

def cashout(peer):
	cashout_url="%s/chequebook/cashout/%s"%(DEBUG_API,peer)
	rtn_content = requests.post(cashout_url).json()
	txHash=rtn_content.get('transactionHash')
	print('cashing out cheque for %s in transaction %s'%(peer,txHash))

	result= requests.get(cashout_url).json().get('result')
	while  1:
		if result:
			break
		time.sleep(5)
		result= requests.get(cashout_url).json().get('result')
		if result:
			break


def cashoutAll(minAmount):
	peers=getPeers()
	for peer in peers:
		uncashedAmount=getUncashedAmount(peer)
		if uncashedAmount > minAmount:
			print ("uncashed cheque for %s %s uncashed"%(peer,str(uncashedAmount)) )
			cashout(peer)

if __name__ == '__main__':
	#listAllUncashed()
	cashoutAll(MIN_AMOUNT)`

**Comment by czb0907** [comment]
# -*- coding: utf-8 -*-
import requests
import json
import time

DEBUG_API='http://localhost:1635'
MIN_AMOUNT=1000

def getPeers():
	cheque_url="%s/chequebook/cheque"%(DEBUG_API)
	rtn_content = requests.get(cheque_url).json()
	lastcheques=rtn_content.get('lastcheques')
	peers=[]
	for info in lastcheques:
		peers.append(info.get('peer'))
	print(peers)
	return peers

def getCumulativePayout(peer) :
	cheque_url="%s/chequebook/cheque/%s"%(DEBUG_API,peer)
	rtn_content = requests.get(cheque_url).json()
	if rtn_content.get('lastreceived') is None \
		or rtn_content.get('lastreceived').get('payout') is None:
		return 0
	return rtn_content.get('lastreceived').get('payout')


def getLastCashedPayout(peer):
	cashout_url="%s/chequebook/cashout/%s"%(DEBUG_API,peer)
	rtn_content = requests.get(cashout_url).json()		
	cashout=rtn_content.get('cumulativePayout')
	#print(rtn_content)
	if cashout:
		return cashout
	else:
		return 0	 

def getUncashedAmount(peer):
	cumulativePayout=getCumulativePayout(peer)
	if cumulativePayout == 0:
		return 0
	else:
		cashedPayout=getLastCashedPayout(peer)
		uncashedAmount=cumulativePayout-cashedPayout
		return uncashedAmount

def listAllUncashed():
	peers=getPeers()
	for peer in peers:
		uncashedAmount=getUncashedAmount(peer)
		if uncashedAmount > 0:
			print(peer,uncashedAmount)

def cashout(peer):
	cashout_url="%s/chequebook/cashout/%s"%(DEBUG_API,peer)
	rtn_content = requests.post(cashout_url).json()
	txHash=rtn_content.get('transactionHash')
	print('cashing out cheque for %s in transaction %s'%(peer,txHash))

	result= requests.get(cashout_url).json().get('result')
	while  1:
		if result:
			break
		time.sleep(5)
		result= requests.get(cashout_url).json().get('result')
		if result:
			break


def cashoutAll(minAmount):
	peers=getPeers()
	for peer in peers:
		uncashedAmount=getUncashedAmount(peer)
		if uncashedAmount > minAmount:
			print ("uncashed cheque for %s %s uncashed"%(peer,str(uncashedAmount)) )
			cashout(peer)

if __name__ == '__main__':
	#listAllUncashed()
	cashoutAll(MIN_AMOUNT)``

**Comment by czb0907** [comment]
[cashout.zip](https://github.com/ethersphere/bee/files/6142406/cashout.zip)


> Can I submit a python script?
> python bee_cashout.py
> [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)

Thank you, but there's a little problem with your code. I've made some changes

**Comment by gyaebay** [comment]
> [cashout.zip](https://github.com/ethersphere/bee/files/6142406/cashout.zip)
> 
> > 我可以提交python脚本吗？
> > python bee_cashout.py 
> > [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
> 
> 谢谢，但是您的代码有一点问题。我做了一些改变

D:\bee>cashout.py
Traceback (most recent call last):
  File "D:\bee\cashout.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by liang55** [comment]
> > [cashout.zip](https://github.com/ethersphere/bee/files/6142406/cashout.zip)
> > > 我可以提交python脚本吗？
> > > python bee_cashout.py
> > > [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
> > 
> > 
> > 谢谢，但是您的代码有一点问题。我做了一些改变
> 
> D:\bee>cashout.py
> Traceback (most recent call last):
> File "D:\bee\cashout.py", line 2, in
> import requests
> ModuleNotFoundError: No module named 'requests'

pip install requests

**Comment by gyaebay** [comment]
> > > [cashout.zip](https://github.com/ethersphere/bee/files/6142406/cashout.zip)
> > > > 我可以提交python脚本吗？
> > > > python bee_cashout.py
> > > > [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
> > > 
> > > 
> > > 谢谢，但是您的代码有一点问题。我做了一些改变
> > 
> > 
> > D:\bee>cashout.py
> > Traceback (most recent call last):
> > File "D:\bee\cashout.py", line 2, in
> > import requests
> > ModuleNotFoundError: No module named 'requests'
> 
> pip install requests

谢谢你，我成功了

**Comment by solostake** [comment]
https://github.com/solostaker/bee_cashout_windows
提供一份PHP在Cli模式下的Cashout脚本.
说明: http://solostake.com/?p=233
This a php scipt for cashout,please run it in cli mode.If have some problems,you can find me at discord(https://discord.gg/tKyTxWJZur),I can help u in english or chinese.
Doc:http://solostake.com/?p=233

**Comment by Richfuming** [comment]
> Can I submit a python script?
> python bee_cashout.py
> [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
![image](https://user-images.githubusercontent.com/14051742/116248979-ec88ed00-a79e-11eb-989c-450fe6d6013c.png)
好像现在不能cashout了？

**Comment by tydiamo** [comment]
> Can I submit a python script?
> python bee_cashout.py
> [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)

Traceback (most recent call last):
  File "D:\bee_cashout.py", line 80, in <module>
    cashoutAll(MIN_AMOUNT)
  File "D:\bee_cashout.py", line 73, in cashoutAll
    uncashedAmount=getUncashedAmount(peer)
  File "D:\bee_cashout.py", line 39, in getUncashedAmount
    cumulativePayout=getCumulativePayout(peer)
  File "D:\bee_cashout.py", line 22, in getCumulativePayout
    cumulativePayout=rtn_content.get('lastreceived').get('payout')
AttributeError: 'NoneType' object has no attribute 'get'


请问应该如何进行处理？

**Comment by liang55** [comment]
> > Can I submit a python script?
> > python bee_cashout.py
> > [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
> 
> Traceback (most recent call last):
> File "D:\bee_cashout.py", line 80, in
> cashoutAll(MIN_AMOUNT)
> File "D:\bee_cashout.py", line 73, in cashoutAll
> uncashedAmount=getUncashedAmount(peer)
> File "D:\bee_cashout.py", line 39, in getUncashedAmount
> cumulativePayout=getCumulativePayout(peer)
> File "D:\bee_cashout.py", line 22, in getCumulativePayout
> cumulativePayout=rtn_content.get('lastreceived').get('payout')
> AttributeError: 'NoneType' object has no attribute 'get'
> 
> 请问应该如何进行处理？

see https://github.com/liang55/bee-cli/blob/master/bee_cashout.py

**Comment by liang55** [comment]
> > Can I submit a python script?
> > python bee_cashout.py
> > [bee_cashout.zip](https://github.com/ethersphere/bee/files/6109127/bee_cashout.zip)
> > ![image](https://user-images.githubusercontent.com/14051742/116248979-ec88ed00-a79e-11eb-989c-450fe6d6013c.png)
> > 好像现在不能cashout了？
> > 一直卡在这位置

https://github.com/liang55/bee-cli/blob/master/bee_cashout.py

**Comment by runningsparrow** [comment]
I have a solution for this problem.
steps is blew:
1, Download jq-win64.exe and put it into the same folder as cashout.sh.
2, revise cashout.sh script , change all "jq" with "./jq-win64.exe".
3, run ./cashout.sh in git-bash.
That's all.

**Comment by filwu8** [comment]
$ ./cashout.sh
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")

**Comment by liuweisir** [comment]
> $ ./cashout.sh
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
> ./cashout.sh: line 40: ((: > 0 : syntax error: operand expected (error token is "> 0 ")

me too。

**Comment by agazso** [comment]
There is a tool called [Swarm-cli](https://github.com/ethersphere/swarm-cli) which is a command line tool that can be used to cash out on Windows. 

Usage:
```bash
# for all peers
swarm-cli cheque cashout -a

# only above a certain balance
swarm-cli cheque cashout -a -m <minimum-balance>

# for a certain peer
swarm-cli cheque cashout -p <peer-address>
```

There is also the [Bee Dashboard](https://github.com/ethersphere/bee-dashboard) which has a web UI if you prefer to use a graphical interface. It also works on Windows.

**Comment by acud** [comment]
closing this since it is handled in the swarm-cli as @agazso mentioned
