### ISSUE TITLE
bee nodes should use geth websocket api

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1100]
# Task
Due to upcoming changes needed by storage incentives, our bee nodes need to communicate with geth nodes only through either ipc or websocket APIs, since some of the APIs we're using are not available on the HTTP API. Our infrastructure configuration should therefore reflect this new requirement.

## Acceptance criteria
New clusters should automatically be deployed with websocket geth APIs

**Comment by vandot** [comment]
@acud for now infra tests are executed using ws geth endpoint, does this ticket reflects also on staging and production?
