### ISSUE TITLE
chunk api change

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1113]
# Task
Currently, the chunk API accepts any kind of chunk and verifies its validity before accepting it into the local node storage.
The `/chunks` endpoint should change to be a content addressed chunk API instead, not taking the chunk address as a parameter, but rather accepting only a content addressed chunk data (span+data) and return the BMT hash corresponding to the supplied inputs.

For SOC upload, a semantic API for SOC should be created. Right now, we do not want nodes to actually offer the actual signing of SOCs, but instead, in order to compensate for the lack of ability to upload SOCs to the chunk api after the aformentioned change, we should have an SOC upload endpoint which accepts the SOC data with a mandatory signature, then verifies it and accepts it to the local storage.

## Acceptance criteria
`/chunks` should not accept SOC, should reject requests that have the address as parameter, should return the BMT hash in the response.
`/soc` endpoint needs to be created (spec tbd)

**Comment by Eknir** [comment]
For congruence, can we consider `socs` (plural) and `cacs` (content addressed chunks) ?

**Comment by Eknir** [comment]
Related: #651

**Comment by acud** [comment]
done as part of #1143
