### ISSUE TITLE
Introduce deploy command to bee

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#1119]
# Task
Default timeout for service start on Windows is 30s (its hard to be increased, you should reboot the machine) and bee is failing during initial start due to wallet deployment. Idea is to deploy wallet during post-install so that services is started much faster even during initial start.
## Acceptance criterea

There is a deploy command `bee deploy` that will deploy wallet.

**Comment by ralph-pichler** [comment]
This is going to be tricky. The chequebook initialisation requires a ton of dependencies which are created in `node.go`. Seems we either need to duplicate a lot of stuff from `node.go` or refactor `NewBee` from `node.go`, quite a bit.

**Comment by Eknir** [comment]
@vandot , could you live without this issue fixed?

**Comment by Eknir** [comment]
@paxthemax , this could be something. Pending reply from @vandot (above)

**Comment by ralph-pichler** [comment]
it's quite important to have this I think for the windows service stuff. and a bit of refactoring won't hurt `node.go` either. one big issue though is that that init code has also changed on storage-incentives branch and rebasing would be a pain. anyway I do have some prior work here. @paxthemax ping me if you start working on this.

**Comment by Eknir** [comment]
@paxthemax , could you please assign your PR to this issue and assign the issue to the correct pipeline in the Active Sprint workspace?

**Comment by paxthemax** [comment]
Would it be good to separate the deployment command for the start command functionality?

Currently, when calling `bee start` the chequebook service is deployed, and with it the chequebook contract, amongst others. We could consider extracting this to a separate command - `deploy` that specifically does this, leaving `start` as a command that does not require on-chain deployments.

**Comment by Eknir** [comment]
`start` should `deploy` (if required) and then start. Separately, we should also be able to `deploy` only.

**Comment by ldeffenb** [comment]
I agree with @Eknir , there is runtime functionality that assumes we have Ethereum connectivity for the chequebook as we recently learned as slock.it is having issues right now.

**Comment by acud** [comment]
done in https://github.com/ethersphere/bee/pull/1314
