### ISSUE TITLE
Chunk endpoint returns 500 if chunk is not found

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1140]
#### Summary
When using the [`/chunk` endpoint with `GET` method](https://docs.ethswarm.org/api/#tag/Chunk/paths/~1chunks~1{reference}/get) and the requested chunk is not found then the response status is 500 (Internal Server Error).

#### Steps to reproduce
1. from the command line (fetch a random hash):
```
$ curl -v http://localhost:11633/chunks/8016d768c4f4a3f389848d26c5f3a57e0cbec5e8744d382ab0f0a608a4eefd4b
*   Trying ::1:11633...
* Connected to localhost (::1) port 11633 (#0)
> GET /chunks/8016d768c4f4a3f389848d26c5f3a57e0cbec5e8744d382ab0f0a608a4eefd4b HTTP/1.1
> Host: localhost:11633
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=utf-8
< Date: Wed, 20 Jan 2021 12:29:39 GMT
< Content-Length: 43
< 
{"message":"chunk read error","code":500}
```

#### Expected behavior
It would be better if the status were 404, 406 or 408 or something similar. 500 suggests that there was an error on the server side and it could not process the request.

**Comment by zbiljic** [comment]
I cannot reproduce this. Trying same steps return (expected) `404` error (i.e. `{"code": 404,"message": "chunk not found"}`).
This is the case when the chunk cannot be found.
From logs I see that my node is trying to retrieve chunk from other connected peers, but fails.

If the error was `chunk read error`, there must be something else wrong during read process. This does not include trying to fetch chunk from other peers. In the case where recovery from network fails one can also receive `202` response.

For this to be explored more, it would be helpful to have logs that happen during your request. The node must be started with option to log at least "debug" level logs (level >= `4`).

**Comment by agazso** [comment]
So I tried again with the current master (`0ead1204`) and it's indeed not reproducible. However with 0.4.2 (the currently released stable version) it is, so somewhere in between this behavior has changed. In case you are interested here are the logs with trace loglevel using all zeroes for the address:

```
TRAC[2021-01-27T12:16:01+01:00] name resolve: valid bzz address "0000000000000000000000000000000000000000000000000000000000000000" 
TRAC[2021-01-27T12:16:01+01:00] retrieval: requesting chunk 0000000000000000000000000000000000000000000000000000000000000000 from peer 1c352197b7fd89844d5edf62176b6035236106c340d74473cf0a458e975d2b73 
DEBU[2021-01-27T12:16:01+01:00] retrieval: failed to get chunk 0000000000000000000000000000000000000000000000000000000000000000 from peer 1c352197b7fd89844d5edf62176b6035236106c340d74473cf0a458e975d2b73: read delivery: stream reset peer 1c352197b7fd89844d5edf62176b6035236106c340d74473cf0a458e975d2b73 
TRAC[2021-01-27T12:16:01+01:00] retrieval: requesting chunk 0000000000000000000000000000000000000000000000000000000000000000 from peer 9c7c5cbf8f2720c8353d9159f92c55fb4cbcadcf9fa34de28e1d94717889a867 
DEBU[2021-01-27T12:16:01+01:00] retrieval: failed to get chunk 0000000000000000000000000000000000000000000000000000000000000000 from peer 9c7c5cbf8f2720c8353d9159f92c55fb4cbcadcf9fa34de28e1d94717889a867: read delivery: stream reset peer 9c7c5cbf8f2720c8353d9159f92c55fb4cbcadcf9fa34de28e1d94717889a867 
DEBU[2021-01-27T12:16:01+01:00] chunk: chunk read error: get closest for address 0000000000000000000000000000000000000000000000000000000000000000, allow upstream true: no peer found ,addr 0000000000000000000000000000000000000000000000000000000000000000 
ERRO[2021-01-27T12:16:01+01:00] chunk: chunk read error                      
INFO[2021-01-27T12:16:01+01:00] api access                                    duration=0.003628671 ip=127.0.0.1 method=GET proto=HTTP/1.1 size=43 status=500 uri=/chunks/0000000000000000000000000000000000000000000000000000000000000000 user-agent=axios/0.21.1
```

**Comment by zbiljic** [comment]
I can confirm that on `0.4.2` (commit `dd6aa73a99ee4ebf285701295eee626842248768`) it does return error `500`.
This happened if the case that there are too few peers connected to node that can be contacted for chunk.

One could argue that might be better to return `500` if the peers cannot be reached, in order to check if the chunks actually exists, because at some later time same request may return the chunk (because peers are reachable then).

This changed due to changes I made in regard to preemptive retry for chunk retrieval. In current code, due to the way retry is done internally, some complexities were required to have same behavior as before, which were removed during review. And in reality I think it is better to return `404` in the case where chunk cannot be fetched or confirmed to exist.

@acud, @Eknir would you care to comment in regards to this?
