### ISSUE TITLE
Simplify tags API

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1147]
# Task

Current `/tags/{id}` API returns response object which contains internal tag state, and was shown that it constantly confuses users. We should simplify this response to return only data that are relevant to the user. If possible we should make response usable to track actual "upload" process for the chunks (that can be used to track progress) to the network.

related: #918

## Acceptance criterea

Have update tags API which is more understandable to the users.

**Comment by Eknir** [comment]
Working on documenting this now in our bee docs
