### ISSUE TITLE
postage api semantics with predictable response times

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#1158]
# Task

Currently the create endpoint only returns once the batch creation has one confirmation on the blockchain. This is not optimal as this might take minutes or even hours on a real network.

- return directly batch ID
- make API endpoint that allows querying readiness of batch (is it mined?)

Tagging @acud , as this affects storage incentives API specs

**Comment by Eknir** [comment]
What would you suggest? Return a txHash instead?

**Comment by Eknir** [comment]
- generic issue with blockchain integration (blocking and in progress)
- then this issue
