### ISSUE TITLE
P2P address expects port

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1163]
#### Summary

When I run my node with `BEE_P2P_ADDR=1637`, I get the error `Error: p2p service: address: address 1637: missing port in address`
I can start my node if I put a colon (`:`) before `1637`, but this is not expected for neither `debug-api-addr` nor `api-addr`-
#### Steps to reproduce

Start the bee node with `--p2p-addr 1637`

#### Expected behavior

I expect my node to be able to start when I pass `--p2p-addr 1637` and have the same behavior as `debug-api-addr` and `api-addr` flags.

#### Actual behavior

The bee stops with error message: `Error: p2p service: address: address 1637: missing port in address`

**Comment by zbiljic** [comment]
@Eknir Please note that argument that needs to be provided is not for p2p port, but (as stated) address.
By putting just `1637`, that is being detected as just `host` part of an address, without the port. If you want to use default address with port `1637`, you need to write it like this: `:1637` (note colon before port). That should result in full address of `0.0.0.0:1637` and `::1:1637` for IPv6 (they are not the same, there is other issue for it).

**Comment by zbiljic** [comment]
@Eknir Please note that argument that needs to be provided is not for p2p port, but (as stated) address.

By putting just `1637`, that is being detected as just host part of an address, without the port. As you noted if you want to use default address with port `1637`, you need to write it like this: `:1637` (note colon before port). That should result in full address of `0.0.0.0:1637` and `::1:1637` for IPv6 (they are not the same, there is other issue for it).

As far as I can test, putting just values (ports without colon) for `--debug-api-addr` and `--api-addr` will fail with similar error - `missing port in address`. Only possibility where you can put just port number for `--debug-api-addr` is in the case where `--debug-api-enable` is false, which means debug API will not start, and therefore will not check the provided address.

For each `*-addr` flags, actual address is expected, which for Go can be written with just colon and port number (or of course with IP address or host and port).

**Comment by Eknir** [comment]
Hi Nemanja,
Thanks for having a look. And you are right.
