### ISSUE TITLE
Estimate network size

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1165]
# User story

## Story

- As a node operator who wants to earn qBZZ, I want to estimate the network size, such that I can estimate how much I will be earning
- As a Swarm comms team member, we want to have access to the estimated network size, such that we can estimate the effectiveness of our campaigns

## Acceptance criteria

- There exists a debugAPI endpoint which a peer can query to estimate the network size
- The documentation is updated, mentioning how to query the network size, mentioning the methodology to calculate it themselves and explain to the user that the estimation is merely an estimation based on local information (which could not be a reliable sample for the whole network)

## Background

How to get an estimation of the network size:

> you know that within your nearest neighbourhood  of depth d you are connected to  all peers that exist (R). Since the distribution of nodes is uniform, any neighbourhood of depth d has expected population of N/(2^d), so if R=N/(2^d), the maximum likelihood estimate for N=2^(d+log2(R))

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by wendydv1989** [comment]
Afaik @significance has some ideas about a network crawler / spider. The idea is to unimit the number of peers the node tries to connect to, thus crawling the entire network.

**Comment by Eknir** [comment]
I'm curious to hear about this idea. Nevertheless, I belief that the mentioned formula is already pretty accurate. It is like taking a sample of the density of nodes on one part of the address space and you extrapolate that to the network size. Obviously, there can be variance and outliers. Then, normal statistics kick in and a nodes estimate will be more and more accurate the more samples it takes (read: nodes it runs).

**Comment by Eknir** [comment]
This is completed with beenodes.live
