### ISSUE TITLE
Include offset and limit in OpenAPI specification

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#1181]
# Task

The `offset` and `limit` query parameters can be used in some places on the API. They are not currently specified in the OpenAPI specification documents.

## Acceptance criterea

The OpenAPI specification document should be updated to contain `offset` and `limit` query parameters on endpoints where it can be used.

related: #1084

**Comment by Eknir** [comment]
Thanks for making this issue @zbiljic
