### ISSUE TITLE
push sync integration testing

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#119]
Requirements for syncing integration testing:
- generate random chunk data
- upload the data to bee http api, register the content addressed hash returned by the api
- iterate over all node addresses with `DistanceCmp` function, and for each chunk that is being uploaded, check which node address is closest to a given chunk address, i.e. which node should store that chunk
- after a certain amount of time given to the nodes to sync, check for each chunk, that the closest node in the cluster has the chunk using the chunk debug api. if this fails the operation should be retried for resilience, until a certain timeout is reached
- tests should be done on a cluster of minimum 3 nodes
- should be tested ideally on larger clusters of 50 or 100 nodes
- test should not test that chunk exists _only_ on closer node, since intermediate node caching might occur, so for now, at least - this is not needed
- multiple chunks should be uploaded on each run, not one chunk per run
- seeds for random number generator that creates the data for the random chunk should be determined from `time.Now().UnixNano()` and should be logged in order to reproduce scenario in case of faliure

**Comment by Eknir** [comment]
> test should not test that chunk exists only on closer node, since intermediate node caching might occur, so for now, at least - this is not needed

Why is this the case? I never heard about caching on push-sync and also doesn't sound to me as something desired.

**Comment by svetomir** [comment]
This is done: https://github.com/ethersphere/bee/runs/666827823?check_suite_focus=true
