### ISSUE TITLE
Deposit after withdraw quickly fails

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1191]
#### Summary
I have a test where I withdraw some amount and then I try to deposit the same amount.

https://github.com/ethersphere/bee-js/blob/74af903cf8172578c4b6e6e576c91c8b706f65ad/test/modules/debug/chequebook.spec.ts#L31

Running Bee 0.4.2

If the time between the two is too short I get the following error:
```
INFO[2021-02-02T20:01:18+01:00] debug api access                              duration=0.271337999 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=90 status=200 uri="/chequebook/withdraw?amount=10" user-agent=axios/0.21.1
DEBU[2021-02-02T20:01:33+01:00] debug api: chequebook deposit: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce. 
ERRO[2021-02-02T20:01:33+01:00] debug api: cannot deposit from chequebook    
INFO[2021-02-02T20:01:33+01:00] debug api access                              duration=0.344153977 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=41 status=500 uri="/chequebook/deposit?amount=10" user-agent=axios/0.21.1
```

#### Steps to reproduce
```
% curl -v -X POST 'http://localhost:1635/chequebook/withdraw?amount=10' && curl -v -X POST 'http://localhost:1635/chequebook/deposit?amount=10'
*   Trying ::1:1635...
* connect to ::1 port 1635 failed: Connection refused
*   Trying 127.0.0.1:1635...
* Connected to localhost (127.0.0.1) port 1635 (#0)
> POST /chequebook/withdraw?amount=10 HTTP/1.1
> Host: localhost:1635
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Cache-Control: no-cache, no-store, must-revalidate
< Content-Type: application/json; charset=utf-8
< Expires: 0
< Pragma: no-cache
< Date: Tue, 02 Feb 2021 19:24:17 GMT
< Content-Length: 90
< 
{"transactionHash":"0x3309d846516822791cfae9c76773b6895fdf2d15df935f796ae1b30bbf215e97"}

* Connection #0 to host localhost left intact
*   Trying ::1:1635...
* connect to ::1 port 1635 failed: Connection refused
*   Trying 127.0.0.1:1635...
* Connected to localhost (127.0.0.1) port 1635 (#0)
> POST /chequebook/deposit?amount=10 HTTP/1.1
> Host: localhost:1635
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Cache-Control: no-cache, no-store, must-revalidate
< Content-Type: application/json; charset=utf-8
< Expires: 0
< Pragma: no-cache
< Date: Tue, 02 Feb 2021 19:24:17 GMT
< Content-Length: 41
< 
{"message":"cannot deposit","code":500}
```

#### Expected behavior
It would be good if there were no error or if it were actionable. In the Debug log it suggests to increase the gas price or increment the nonce but that's not available at the API. 

An alternative could be that the node is waiting a bit and try again the deposit and after a timeout return HTTP error 408 (Request timeout) to the client. Then the client could retry the request.

**Comment by Eknir** [comment]
Managing nonces is notoriously hard in Ethereum and the problem you ran into is well known. I suspect that the error message bubbled up from deeper in the stack. 
I personally have the impression that the log is actionable (at least I would know what to do), by just not running these two calls so shortly after each other. This does require some specific domain experience on Ethereum.

Your suggestion:

> An alternative could be that the node is waiting a bit and try again the deposit and after a timeout return HTTP error 408 (Request timeout) to the client. Then the client could retry the request.

Might be valid. Let's see what @rpicc thinks.

**Comment by Eknir** [comment]
@agazso, could you please validate if this works as expected?
