### ISSUE TITLE
storage incentives: integration testing

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1195]
# Epic

This epic is to concentrate all information about the necessary integration testing for storage incentives.
## Background

- change the current test suite to just even pass (postage stamps for each upload are necessary) - changes the infra to support this, and add postage api integration to buy the stamps before each upload
- specific tests about storage incentives - postage api tests, GC tests (can use existing gc tests as baseline)
- debugapi for batchstore (TODO), have a specific test case to create batches on different nodes and check that each node synchronized the blockchain correctly and has all the batches from the other nodes

**Comment by Eknir** [comment]
Related: #1318
