### ISSUE TITLE
duplicate chunk with different postage stamps

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1196]
Same chunks stamped with different postage stamps should result in storing nodes picking the stamp with the higher value and storing it with the chunk. When the chunk was already stored, the stamp should be overridden.

connect to #1051

**Comment by Eknir** [comment]
I believe this is answered in https://github.com/ethersphere/bee/issues/1440 . Could you validate this and confirm the answer here (and then perhaps close it?)
