### ISSUE TITLE
feeds: outstanding tasks

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#1206]
as a followup to  https://github.com/ethersphere/bee/pull/1193
- [ ] fix mantaray entry on empty path
- [ ] add support for index response headers for epoch based feeeds
- [ ] add support for internal signer and feed update endpoint (only localhost, no gateway)
- [ ] add support to persist last update index in statestore  (only localhost, no gateway)
- [ ] integration tests

**Comment by Eknir** [comment]
Integration tests in #1206
