### ISSUE TITLE
Validate bee authenticity

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1214]
# User story

## Story
As a node operator, I want to validate that the Bee software that I run came from an official source, such that I am assured that I did not run a malicious version

## Acceptance criteria

- For all of the bee version that we officially support (bee in package managers, binaries, docker, build from source), the user should be able to validate that it is a genuine version.

## Background

- We spoke about this in the backlog refinement of Januari 26.
- @vandot , please let me know which releases are currently not signed.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
This sprint: clarity on what should be implemented. Implementation upcoming sprint.

**Comment by Eknir** [comment]
Documentation task

**Comment by vandot** [comment]
Next bee release will have checksum file signed with GPG key.
Add to docs:

Releases are signed using the project GPG key with key-ID `65207E638F11F36B` and fingerprint `C07E 8D0F CC74 221F 2C24  1EEE 6520 7E63 8F11 F36B`. The key can be fetched from most keyservers.
```
gpg --recv-keys 65207E638F11F36B
```
Set trust for the key
```
$ gpg --edit-key 65207E638F11F36B
gpg> trust
pub  rsa4096/65207E638F11F36B
     created: 2021-04-19  expires: 2022-04-19  usage: C
     trust: ultimate      validity: ultimate
sub  rsa4096/60760BAEEDEFB3E6
     created: 2021-04-19  expires: 2022-04-19  usage: S
[ultimate] (1). ethersphere-bee (github.com/ethersphere/bee project key) <security@ethswarm.org>

Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu

Your decision? 5
Do you really want to set this key to ultimate trust? (y/N) y
gpg> quit
```
Download and verify the signature on the checksum file:
```
gpg --verify bee_v0.6.0_checksums.txt.sig bee_v0.6.0_checksums.txt
```
After verifying the checksum file signature use `shasum` to verify the checksums of the release artifacts:
```
shasum --check bee_v0.6.0_checksums.txt
```

**Comment by vandot** [comment]
@significance we added check bee's authenticity into docs? can I close this one?
