### ISSUE TITLE
Initial Checkbook Balance scale?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1215]
#### Summary
When upgrading to the new version, with the new gBZZ token, a new checkbook is created and funded and shows a balance of:

curl http://127.0.0.1:6061/chequebook/balance 2>nul | jq
{
  "totalBalance": 100000000,
  "availableBalance": 100000000
}

However, according to the debug trace output, the payment threshold amount is:

time="2021-02-08T17:02:05-05:00" level=trace msg="sending payment threshold announcement to peer ffb4bebe115e72fca4365cfce75e27d074db8f74085ca8c50a758c812fc08877 of 10000000000000"

I believe the new scale of the gBZZ token is not taken into account when the checkbook is initially funded.  It's off by a factor of 100,000, but likely a lot more than that to have enough in the checkbook for at least a few payments to be issued.

To back this up, after a few chunks have been exchanged with this node, the peer balances are:

curl http://127.0.0.1:6061/balances 2>nul | jq
{
  "balances": [
    {
      "peer": "4f70ad160d1e346d12cb1f8ec53fb813a44a66dd5dde4128e00d76014a24eb4b",
      "balance": 19000000000
    },
    {
      "peer": "5cc8055cc347e79f7074f7c957749f964ba91a4a5f929b805801fd78662a7840",
      "balance": -24000000000
    },
    {
      "peer": "63a1bb8688497606a5ae391148eb897f10ef89921490f0e5ebfb448d1a38584c",
      "balance": 10000000000
    },
    {
      "peer": "7c88699beec4ae4dccf5403bb4c93883037e9a0fa0c58579227475f2e9ac8e32",
      "balance": -10000000000
    },
    {
      "peer": "ffb4bebe115e72fca4365cfce75e27d074db8f74085ca8c50a758c812fc08877",
      "balance": 115000000000
    }
  ]
}

The initial checkbook balance isn't enough to even issue a single payment to any of these peers.

#### Steps to reproduce

Just fire up a new node and compare the initial balance to the payment threshold announcement.

#### Expected behavior
The initial checkbook should have enough to issue probably at least 100 or 1,000 payment thresholds checks.

#### Actual behavior
I have not seen a single settlement be issued, possibly because I haven't hit the threshold, but also possibly because my checkbook balance is too small.

Version: 0.4.3-67ff6fb0

**Comment by ldeffenb** [comment]
I just realized that I'm also running a pre-existing .bee.yaml file that contains:

payment-early: "1000000000000"
payment-threshold: "100000"
payment-tolerance: "10000"
swap-initial-deposit: "100000000"

Is it possible that the check-book creator used the initial deposit from this configuration file?

Should the new version possibly detect off-by-millions and warn the user that the scale of BZZ has changed?

**Comment by ralph-pichler** [comment]
for now we just added a remark about configuration options to the release notes

**Comment by ldeffenb** [comment]
Thank you.  I've now managed to update my nodes' configuration files and manually move enough gBZZ into the checkbook to keep them going.

**Comment by Eknir** [comment]
Thanks for taking the time to raise this issue @ldeffenb ! We did foresee this coming and warned for it in the [0.5.0 release notes](https://github.com/ethersphere/bee/releases/tag/v0.5.0). I am sorry that this didn't reach you. Your comment about detecting off-by-millions is valuable and now we have more and more users, we will consider implementing such measures to protect our users for mistakes.

I'm closing this issue as I don't see an actual task here anymore.
