### ISSUE TITLE
connectOut sometime fails because nodes are reachable before protocol setup

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#1221]
#### Summary

connectOut sometime fails because nodes are reachable before protocol setup. this is because nodes are already listening before all the protocols are added in `node.go`.

#### Expected behavior
Nodes should only accept connections after the protocols are set up

#### Actual behavior
Nodes should only accept connections before the protocols are set up and reject the initial swap message which leads to problems when they try to settle later. This affects payment thresholds (and in the future the initial pricing update).

**Comment by ralph-pichler** [comment]
will be fixed as part of #1207

**Comment by acud** [comment]
fixed in #1390
