### ISSUE TITLE
Expose bee version through API

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#1225]
It would be good if bee version is exposed through an API, like
- http://localhost:1633/version  

This will be helpful for the clients to determine which version of bee they are connecting. 
Useful when we have a breaking change and we want to support both version of bee.

**Comment by agazso** [comment]
I agree it would be nice. 

For the time being maybe you can try  `http://localhost:1635/health`
Please note it's the debug port.

**Comment by AleksandrKuporosov** [comment]
You can use `curl http://localhost:1635/readiness` handler
```
{"status":"ok","version":"0.5.1-65ec2d0"}
```

**Comment by acud** [comment]
@jmozah is this still an issue? since the information is already available through the readiness endpoint, I'm inclined to close this

**Comment by jmozah** [comment]
@acud yes yes. Please close it.
