### ISSUE TITLE
Error: statestore  - after updating bee node to version 0.5.0

### ISSUE THREAD

**Issue by eth-swarm** [ethersphere/bee#1232]
#### Summary

After updating bee node to version 0.5.0 (on Daapnode) I got  Error bellow:
Error: statestore: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000622]

Bee node keeps restarting

![image](https://user-images.githubusercontent.com/63300164/107497832-54ae3680-6b93-11eb-82b0-bb2cd2f5b540.png)

#### Steps to reproduce

1. install bee node v0.4.2 over dappnode
2. update bee node v0.4.2 to v0.5.0

**Comment by Eknir** [comment]
Thanks for making this bug report. We'll have a look into it!

**Comment by acud** [comment]
I have made a PR to possibly address this, but I also have a hunch that the dirty shutdown might be related to how DappNode shuts bee down. @Eknir can you get me in touch with them so we could have some pointers?

**Comment by petenickless** [comment]
@acud I've got the same issue on the Raspberry Pi 4 running without DappNode - just thought i'd flag.  I've subscribed and will follow updates.  

`Error: statestore: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000041]`
