### ISSUE TITLE
Generating password with openssl is broken on mac

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#1233]
If any non-system openssl variant is used parameter command is broken because of bug
```
openssl rand -base64 32 -out /usr/local/var/lib/swarm-bee/password
Extra arguments given.
rand: Use -help for summary.
```
Redirect generated random hash to file using `>`

**Comment by Eknir** [comment]
@vandot , a bug goes from core: backlog - new issues pipeline to the core:backlog - bugs pipeline. From there, you confirm and assign priority. Depending on the priority it lands in the current sprint or goes to the backlog. From the current sprint you manage it as you would manage any normal issue. I can see that you did not do that with this issue, which creates confusion. If you have questions, please let me know.
