### ISSUE TITLE
Tell user which backend (`--swap-endpoint`) is being used

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1237]
When waiting to be sync'ed
![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/bf8a0412-0a49-442c-9137-cd26a86befdf)

And perhaps also just as part of the boot-sequence

**Comment by acud** [comment]
closing this as this could leak sensitive information, such as infura api keys etc, since they are embedded in the URL
