### ISSUE TITLE
api pss test flaking

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1239]
```
== RUN   TestPssWebsocketSingleHandler
--- PASS: TestPssWebsocketSingleHandler (1.31s)
=== RUN   TestPssWebsocketSingleHandlerDeregister
    asm_amd64.s:1374: timed out waiting for message
--- FAIL: TestPssWebsocketSingleHandlerDeregister (23.34s)
=== RUN   TestPssWebsocketMultiHandler
```
@janos strange that it errors in `asm_amd64.go`. any idea?

**Comment by janos** [comment]
@acud I have no solution for this problem, but the timeout for waitMessage is 10 seconds and the whole test failed after 23.34s which suggests that there may have been some capacity problems while running the test, especially as the error was reported by the runtime's asm_amd64.s goexit function. I have no clear idea why would that happen in normal circumstances.

A other timeouts did not fire in this test and test did run significantly longer than waitMessage timeout, I would assume this one could be mitigated with a longer timeout.

**Comment by acud** [comment]
```
--- FAIL: TestPssWebsocketSingleHandler (10.02s)
    pss_test.go:79: timed out waiting for pss message
FAIL
coverage: 65.1% of statements
FAIL	github.com/ethersphere/bee/pkg/api	51.273s
```
