### ISSUE TITLE
Light nodes

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1242]
Light nodes are nodes which don't store data and are therefore not treated by other full nodes as part of their nearest-neighborhood. Light nodes can still upload and download data to the network.

The concept of light nodes might be ultimately useful for using Bee in low-resource environments, but we are currently looking at this task from a stability perspective; we want many nodes to "surf" the Swarm, but if too many nodes would just come and go that would harm the stability.

Therefore, nodes are by default a light node and only when the user explicitly intends, it becomes a full node.

A light node does not benefit from the plausible deniability on uploading/downloading, since a light node is always the originator of the request

**Comment by ldeffenb** [comment]
How does a "user explicitly intends" to mark their node as full when they intend to keep it running long-term?

**Comment by Eknir** [comment]
> How does a "user explicitly intends" to mark their node as full when they intend to keep it running long-term?

This should be done via a configuration parameter

**Comment by Eknir** [comment]
We could enforce the requirement to be available long-term by storing when a node is connected and only treat him/her as a full node when the connection is online for longer than x time. 
This way, there is no explicit need for a full-node flag, as nodes are treated by default as a light node, unless they proof to be a full node.

**Comment by Eknir** [comment]
@agazso

**Comment by veqtor** [comment]
I think having an explicit flag is nice, since a mobile or other light client might not want to be upgraded to a full node even if they're online for X amount of time

**Comment by acud** [comment]
#### Light node protocol/component behavior


- Hive:
    - Full nodes should not gossip light nodes (this can be toggled in kademlia#announce) to other nodes
    - Full nodes should gossip only about full nodes to light nodes
    - Light nodes should not gossip to full nodes at all (?? I would potentially just block this possibility altogether at the first phase)
- Addressbook:
	- should not persist light nodes at all
- Kademlia:
    - Should not initiate connections to light nodes 
    - potentially have as few as one connection
- Pricing, SWAP:
    - normal behavior
- Retrieval protocol:
    - Light node does not forward, therefore
    - Full node does not ask light node for chunks, light node should reset incoming requests, however disconnecting from the light node side due to this violation might be abused by full nodes that may take advantage of this in order to make the light node go away, they should just disconnect them instead
- Push sync (behavior is comparable to retrieval protocol):
    - Light node should be able to send chunks using the protocol
    - Light node should not receive (or forward) pushed chunks
- Pull sync:
    - Light node should be able to pull from other nodes, for the sake of receiving PSS messages or with the intention of becoming a full node.
    - Other nodes should not be pulling from the light nodes
	- Consider aspiring non-light nodes actually a storer node  only when historaical and live syncing is indicated to be full
- Ping pong:
    - Normal functionality should be maintained
- CLI:
	- cl flag to set light/storer  node type. light should be default but explicitly set a node storer node, though this is dangerous: if only a few nodes use the flag, no proper kademlia, so maybe light is not  default

cc @janos
