### ISSUE TITLE
Feed update lookup always return the same update

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1248]
#### Summary
Using the [Find feed update endpoint](https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1{owner}~1{topic}/get) always return the first or second update.

#### Steps to reproduce
1. Start from empty, standalone node.
2. Using the Find feed update endpoint with owner and topic returns 404 (this is good because it's empty).
3. Upload SOC containing value `0` with owner and topic using index `0`.
4. Using the Find feed update endpoint with owner and topic returns value `0`, index `0`, next index `1` (so far so good).
5. Upload SOC containing value `1` with owner and topic using index `1`.
4. Using the Find feed update endpoint with owner and topic returns value `0`, index `0`, next index `1` (same as step 4, this is an error).

#### Expected behavior
Find feed update returns the latest update.

It doesn't matter if you wait between the uploads or not. If you change `sequence.NewAsyncFinder` to `sequence.NewFinder` in `pkg/feeds/factory/factory.go` then it works correctly.

**Comment by zelig** [comment]
@agazso i dont see how this can happen. Knowing the exact test setup would be needed.
Note, that if step 5, the constructed chunk contains a timestamp in the future, then looking up latest returns the  latest at the current time.

**Comment by agazso** [comment]
I uploaded an app to help debugging this issue.

https://gateway.ethswarm.org/files/3ed0350080fd2fab4a9420e0b91571b777389bc87acfda3f21f7cd1712da1ddf

What it does is that it uses the Find feed update endpoint to get the next index and then it creates an SOC with that index and writes an update there. So in the Bee log you are supposed to see something like this:

```
INFO[2021-02-14T19:56:18+01:00] api access                                    duration=0.0170698 ip="::1" method=GET proto=HTTP/1.1 size=45 status=200 uri="/feeds/8d3766440f0d7b949a5e32995d09619a7f86e632/0000000000000000000000000000000000000000000000000000000000000000?type=sequence" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
INFO[2021-02-14T19:56:18+01:00] api access                                    duration=0.000322902 ip="::1" method=OPTIONS proto=HTTP/1.1 size=23 status=200 uri="/soc/8d3766440f0d7b949a5e32995d09619a7f86e632/1cf395c0cd58ef248dc39cbdb14948280ffdfcc9ac3aedbd8cb5d1d4bb9997be?sig=cd9478093049d7b50095913dd52dc88d82e4bc979d1fec0986dd4619ff474f2e4045a939ab6d07140f614b1672ab9595c79e285213603ebf0a8d52bdfb7e99c41b" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
INFO[2021-02-14T19:56:18+01:00] api access                                    duration=0.001621718 ip="::1" method=POST proto=HTTP/1.1 size=94 status=201 uri="/soc/8d3766440f0d7b949a5e32995d09619a7f86e632/1cf395c0cd58ef248dc39cbdb14948280ffdfcc9ac3aedbd8cb5d1d4bb9997be?sig=cd9478093049d7b50095913dd52dc88d82e4bc979d1fec0986dd4619ff474f2e4045a939ab6d07140f614b1672ab9595c79e285213603ebf0a8d52bdfb7e99c41b" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36"
```

The output of the page looks like this:

```
{
    "privateKey": "634fb5a872396d9693e5c9f9d7233cfa93f395c093371017ff44aa9ae6564cdd",
    "topic": "0000000000000000000000000000000000000000000000000000000000000000"
}
{
    "upload": {
        "reference": "3b8e67e9ab7c6ed2bfd320a425d41c920413c320f07b25f17ec4b4fcfd304a51",
        "cacAddress": "627f251b0514c92d6ce3999dc6e3de8aef746c5bc32cdadab3243f872411970a",
        "socData": "1cf395c0cd58ef248dc39cbdb14948280ffdfcc9ac3aedbd8cb5d1d4bb9997becd9478093049d7b50095913dd52dc88d82e4bc979d1fec0986dd4619ff474f2e4045a939ab6d07140f614b1672ab9595c79e285213603ebf0a8d52bdfb7e99c41b280000000000000000000000602972520000000000000000000000000000000000000000000000000000000000000000",
        "soc": {
            "identifier": "1cf395c0cd58ef248dc39cbdb14948280ffdfcc9ac3aedbd8cb5d1d4bb9997be",
            "signature": "cd9478093049d7b50095913dd52dc88d82e4bc979d1fec0986dd4619ff474f2e4045a939ab6d07140f614b1672ab9595c79e285213603ebf0a8d52bdfb7e99c41b",
            "span": "2800000000000000",
            "payload": {
                "timestamp": "0000000060297252",
                "reference": "0000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "index": "0000000000000001"
    }
}
```

It basically prints the `privateKey` and `topic` that's used, then it prints the result of the uploaded SOC:
- `reference`: is the address of the SOC
- `cacAddress`: is the bmt hash of the span and payload
- `socData`: is full SOC data
- `soc`: the SOC data broken down as
  - `identifier`: is the keccak hash of the `topic` and the `index`
  - `signature`: the signature of the SOC
  - `span`: length of payload in uint64 little endian
  - `payload`: broken down as
    - `timestamp`: uint64 big endian unix timestamp
    - `reference`: the reference written in the feed update
- `index`: the index where the update was written

You can change certain parameters by providing them as query parameters: `privateKey`, `topic`.
You can also connect to any Bee node by providing a `bee` query parameter like this `?bee=http://localhost:1633`. By default it will try to connect to the node where it is loaded from.

I suggest to download this file from the public network and upload it to a local, isolated Bee instance, preferably starting from an empty database. Then if you load the page for the first time you can see that the `index` is `0`. Refresh the page and you will see that the `index` is `1`. Then from this point after refreshing the page `index` will be always `1` but the SOC data is different (because the timestamp changes). However the since the SOC address is derived from the identifier (which is in turn derived from the topic and index) it will always stay the same. According to the book uploading different SOCs with the same address should result in an error, but it does not (it's a different issue, see #1247).

Then change the `sequence.NewAsyncFinder` to `sequence.NewFinder` in `pkg/feeds/factory/factory.go` and refresh the page a few times. You will see that the index increases with each page load as it is expected.

**Comment by Eknir** [comment]
@agazso, could you (or somebody from your team) please do QA on the feeds feature? Just to see if it is working as you would expect it to work and perhaps see if you can trigger some edge cases by behaving unexpected

**Comment by agazso** [comment]
In 0.5.1 the [Find feed update](https://docs.ethswarm.org/api/#tag/Feed/paths/~1feeds~1%7Bowner%7D~1%7Btopic%7D/get) endpoint returns the correct value.

However there are two new issues when using this feature:

1. After updating a feed and reading back the latest value immediately takes 10 seconds (the default chunk timeout) when running with multiple local nodes. This may not be a bug, just a lack of optimisation but it seems a bit weird from a user perspective. When running with a single, isolated node it returns almost instantly.

2. We have an [integration test](https://github.com/ethersphere/bee-js/blob/a5136590aa2de788ba1ab8f55f762f5e56f0f790/test/bee-class.spec.ts#L216) that does the operation described in point 1. twice. We run our tests on four different Node.js versions and out of 4 this test fails at least once randomly, by not finishing in 60 seconds. The 60 seconds were chosen with the timeout described in point 1. taken into consideration. This suggests that sometimes the lookups took even longer that 10 seconds or even they get stuck. This requires more investigation. Our [CI environment](https://github.com/ethersphere/bee-js/blob/fix/soc-upload-delete-chunk/.github/workflows/ci.yaml) is running a 5 node cluster with `bee-local` (which uses `beekeper` itself).

**Comment by agazso** [comment]
An update to the second point: after increasing the timeout from 60 seconds to 120 seconds the tests reliably run. This means that they don't get stuck, which is good news. However it would be good to investigate why they take so long.

**Comment by agazso** [comment]
Opened a new issue about feed lookup times: https://github.com/ethersphere/bee/issues/1382
