### ISSUE TITLE
Default Swap Endpoint on DappNode is wrong.

### ISSUE THREAD

**Issue by daresan** [ethersphere/bee#1249]
#### Summary
Installed Bee Package from DAppNode. Bee client starts following output comes:
clef is not enabled; portability and security of your keys is suboptimal
using existing swarm network address: aba... (it never showed the message that a new wallet is being created)
swarm public key 0281970...
Pss public key 024c23...
Using Ethereum address 9c11..
Could not connect to backend at http://goerli-geth.dappnode:8545
... check your node or specify another node using --swap-endpoint.
Error: could not get chain id from Ethereum backend: Post "http://goerli-geth.dappnode:8545": dial tcp: lookup goerli-geth.dappnode on 127.0.0.11:53: no such host ( I wonder why it's 127.0.0.11 and not 127.0.0.1?)

#### Steps to reproduce
Raspberry Pi 4 8GB and 64GB microSD & 250Gb USB SSD (not recognized yet, but not the problem now)
Installed Pi DappNodeImage and configured (light)
Installed Bee Package from DAppNode with approximately 40GB database size and Swap-Endpoint as default:
http://goerli-geth.dappnode:8545

#### Expected behavior
1st: show wallet generation in logs after start.
2nd: connect to swap-endpoint.

#### Actual behavior
Bee keeps restarting with above described message logs.

Screenshot:
![image](https://user-images.githubusercontent.com/22983361/107801429-5842e880-6d60-11eb-9f83-65d3498d25c8.jpeg)

**Comment by daresan** [comment]
Edited Default Swap Endpoint to rpc.slock.it/goerli:8545
-> success!

**Comment by Eknir** [comment]
This is a dappnode-specific issue. I forwarded your issue to the Dappnode maintainers and close the issue here. Hope you managed to get all working!

**Comment by daresan** [comment]
Yes, thanks! But keep getting DAppNode Errors in the Interface after a while the Pi is working. Unresponsive messages and such, but not related to this. Thanks anyways!
Have a good night!
Cheers,
Daniel

Von meinem iPhone gesendet
