### ISSUE TITLE
PATCH tags/{uid} response mis-match

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1250]
#### Summary
When executing the following PATCH:
curl --data "{\"address\": \"bd4eba9cf2de2167fbf9f842200d538aea835177379d65aa8c1af5be42425113\"}" -H "content-type: application/json" -X PATCH http://127.0.0.1:8080/tags/4186314294

The received response was:
{"message":"ok","code":200}

But the documentation at:
https://docs.ethswarm.org/api/#tag/Tag/paths/~1tags~1{uid}/delete

says it should be 
{
  "status": "string"
}

So, is the documentation or the implementation at fault?

#### Steps to reproduce
Create a new tag, use it for an upload, and patch the tag with the final CID.

#### Expected behavior
I expected to get status as the documentation described.

#### Actual behavior
Got a message and code instead of status.

**Comment by Eknir** [comment]
Closed in favor of #1371. Thanks for reporting!
