### ISSUE TITLE
Existing tags lose startedAt precision

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1251]
#### Summary
I have encountered a situation where querying a tag initially, the startedAt shows millisecond precision, but after some (previously unidentified) event, the same query on the same tag returns the startedAt timestamp without the milliseconds.

Upon looking at the source code, apparently tags are stored in two places, a memory-resident sync.Map (tags) and the persistent storage.StateStorer (stateStore).  The tag query API server first looks in tags and subsequently in the stateStore.  Apparently the former keeps the milliseconds, but the latter does not.

#### Steps to reproduce
Note: All of this is on the main, not debug, API
1) Create a tag with POST /tags
2) Query the tag with GET /tags/{uid}
3) Restart the node to force access from the stateStore
4) Query the tag again with GET /tags/{uid}

curl -X POST http://127.0.0.1:8080/tags 2>nul | jq
{
  "uid": 300444692,
  "startedAt": "2021-02-13T14:19:27.1729573-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}
curl http://127.0.0.1:8080/tags/300444692 2>nul | jq
{
  "uid": 300444692,
  "startedAt": "2021-02-13T14:19:27.1729573-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}

RESTART the node here

curl http://127.0.0.1:8080/tags/300444692 2>nul | jq
{
  "uid": 300444692,
  "startedAt": "2021-02-13T14:19:27-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}

The same thing happens if a PATCHed tag is DELETEd, causing it to be removed from the tags sync.Map but not the stateStore (issue #1252 ).

Note: All of this is on the main, not debug, API
1) Create a tag with POST /tags
2) Query the tag with GET /tags/{uid}
3) Persist the tag with PATCH /tags/{uid}
4) Query the tag with GET /tags/{uid} - Milliseconds is still here
5) Delete the tag with DELETE /tags/{uid} - This only removes from memory
6) Query the tag again with GET /tags/{uid} - Milliseconds is gone having been retrieved from stateStore

curl -X POST http://127.0.0.1:8080/tags 2>nul | jq
{
  "uid": 1411868748,
  "startedAt": "2021-02-13T14:32:07.136886-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}
curl http://127.0.0.1:8080/tags/1411868748 2>nul | jq
{
  "uid": 1411868748,
  "startedAt": "2021-02-13T14:32:07.136886-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}
curl -X PATCH http://127.0.0.1:8080/tags/1411868748 2>nul | jq
{
  "message": "ok",
  "code": 200
}
curl http://127.0.0.1:8080/tags/1411868748 2>nul | jq
{
  "uid": 1411868748,
  "startedAt": "2021-02-13T14:32:07.136886-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}
curl -X DELETE http://127.0.0.1:8080/tags/1411868748 2>nul | jq
(No output from DELETE)
curl http://127.0.0.1:8080/tags/1411868748 2>nul | jq
{
  "uid": 1411868748,
  "startedAt": "2021-02-13T14:32:07-05:00",
  "total": 0,
  "processed": 0,
  "synced": 0
}

#### Expected behavior
I would expect the startedAt to not lose precision when going through the stateStore.

#### Actual behavior
The startedAt element loses the millisecond precision.

The issue is likely in https://github.com/ethersphere/bee/blob/master/pkg/tags/tag.go and the methods MarshalBinary() and UnmarshalBinary().  They use the time.Unix() method(s) to convert StartedAt (a time.Time) to and from an integer representation in the stateStore.  This integer presumably doesn't carry the milliseconds value from the time.Time StartedAt.

**Comment by ldeffenb** [comment]
It appears that the tags that come back without the milliseconds component have actually been DELETEd!  My upload process only DELETEs tags that were fully processed and synced within 3 minutes of the upload completion response with the delivered CID which is used to PATCH the tag at that point.  The tag is then monitored for up to 3 minutes and is DELETEd if it completes sync, but is left intact if the sync takes longer than 3 minutes.

Interesting that you can still lookup a deleted tag, but it comes back without milliseconds on the startedAt element.  I wonder how long a deleted tag is actually still in the node somewhere?

**Comment by ldeffenb** [comment]
Confirmed, the milliseconds part of the startedAt timestamp disappear once a tag is deleted.  I'm surprised it can even be queried after deleting, but it can.  I even restarted the node after deleting a tag, and it can still be queried after the restart.

"before" is before the PATCH, "after" is after the PATCH, "DELETED" is after the DELETE

Matched: 12/0/0/233/116/8.meta CID:a45eb321fd01dc1c1aab8ceaab5cf7e9da6bba37ec81a1a1aab3677f4cd9fea1
Synced Update(2290911072) gave Table[2290911072] = code=200 message=ok
Table[before] = processed=23 startedAt=2021-02-13T13:50:20.9376468-05:00 synced=23 total=23 uid=2290911072
Table[after] = processed=23 startedAt=2021-02-13T13:50:20.9376468-05:00 synced=23 total=23 uid=2290911072
Table[DELETED] = processed=23 startedAt=2021-02-13T13:50:20-05:00 synced=23 total=23 uid=2290911072

Matched: 12/0/0/232/221/8.meta CID:388e2354002b017af289c472012165fb19bfb9ef149ac74405f4b0c3369c0c1b
Synced Update(3467778812) gave Table[3467778812] = code=200 message=ok
Table[before] = processed=5 startedAt=2021-02-13T13:50:31.6858242-05:00 synced=5 total=5 uid=3467778812
Table[after] = processed=5 startedAt=2021-02-13T13:50:31.6858242-05:00 synced=5 total=5 uid=3467778812
Table[DELETED] = processed=5 startedAt=2021-02-13T13:50:31-05:00 synced=5 total=5 uid=3467778812

Matched: 12/0/0/216/202/128.meta CID:63fd49f34d875d3d149d77a01d9cf897e84192a9dc2080fa9a9379974e8760a0
Synced Update(727876152) gave Table[727876152] = code=200 message=ok
Table[before] = processed=16 startedAt=2021-02-13T13:50:43.9485921-05:00 synced=16 total=16 uid=727876152
Table[after] = processed=16 startedAt=2021-02-13T13:50:43.9485921-05:00 synced=16 total=16 uid=727876152
Table[DELETED] = processed=16 startedAt=2021-02-13T13:50:43-05:00 synced=16 total=16 uid=727876152

Matched: 12/0/0/39/72/136.meta CID:43dcde41bf2c92e4adb6d4ff9fa90253e1b466b077bc9f41c3fcfbb0cdb380a4
Synced Update(2162870809) gave Table[2162870809] = code=200 message=ok
Table[before] = processed=5 startedAt=2021-02-13T13:50:49.5792017-05:00 synced=5 total=5 uid=2162870809
Table[after] = processed=5 startedAt=2021-02-13T13:50:49.5792017-05:00 synced=5 total=5 uid=2162870809
Table[DELETED] = processed=5 startedAt=2021-02-13T13:50:49-05:00 synced=5 total=5 uid=2162870809

**Comment by Eknir** [comment]
@ldeffenb , do you consider the milisecond precision useful? Would it be ok to just return startedAt with second precision? I agree with you that it should be uniform, but am not sure if we need milisecond.

**Comment by ldeffenb** [comment]
@Eknir Since tag IDs are randomly created, the millisecond precision allows reconstructing a time-sequence of those tags if they need to be queried after an outage for continued monitoring.  So yes, I think I would have to say that millisecond precision is useful.

Until I can actually delete persisted tags, I'm actually using this "inconsistency" to at least get some of the tags I should be monitoring if my client drops while my bee node stays alive.

**Comment by Eknir** [comment]
Closed in favor of #1371. Thanks for reporting!
