### ISSUE TITLE
Persisted tags are never deleted

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1252]
#### Summary
Tags are stored in two locations, a memory-resident sync.Map (tags) and the persistent storage.StateStorer (stateStore).  If a tag has been persisted, either through having been created and not deleted before a node shutdown, or by having been completed with PATCH, then that tag will continue to be queriable even after having been DELETEd.

#### Steps to reproduce

Note: All of this is on the main, not debug, API

1) Create a tag with POST /tags
2) Query the tag with GET /tags/{uid}
3) Restart the node to flush to the stateStore
4) Query the tag again with GET /tags/{uid}
5) Delete the tag with DELETE /tags/{uid}
6) Query the tag again with GET /tags/{uid} - It still exists!
7) Restart the node again, to be sure
8) Query the tag again with GET /tags/{uid} - It still exists!

Alternatively, with a PATCHed tag:

1) Create a tag with POST /tags
2) Query the tag with GET /tags/{uid}
3) Persist the tag with PATCH /tags/{uid}
4) Query the tag again with GET /tags/{uid}
5) Delete the tag with DELETE /tags/{uid}
6) Query the tag again with GET /tags/{uid} - It still exists!
7) Restart the node just to be sure
8) Query the tag again with GET /tags/{uid} - It still exists!

However, the following sequence actually works, because the tag was never persisted to the stateStore.

1) Create a tag with POST /tags
2) Query the tag with GET /tags/{uid}
3) Delete the tag with DELETE /tags/{uid}
4) Query the tag again with GET /tags/{uid} - It is gone
5) Restart the node just to be sure
6) Query the tag again with GET /tags/{uid} - It really is gone

#### Expected behavior
DELETE /tags/{uid} should make any tag disappear, including from the stateStore

#### Actual behavior
Persisted tags are never deleted.

This is really bad because there is a limited address space (Uint32) for tag {uid}s and if a random collision occurs, the tag create API will return errExists, something that would not really make sense to the user.  I suspect my own tag space is getting quite full which is why I was querying and deleting obsolete tags, only to discover that they don't really go away!

I suspect the problem is in the Delete method of https://github.com/ethersphere/bee/blob/master/pkg/tags/tags.go.  It only deletes the tag from the tags sync.Map and nothing that I can find ever deletes the key from the stateStore.

**Comment by acud** [comment]
Great catch @ldeffenb! A fix is underway!

**Comment by ldeffenb** [comment]
@acud Most excellent.   This'll give me a reason to move one of my nodes off of 0.5.0 release and back to the master build.
