### ISSUE TITLE
Cannot connect to clef signer: permission denied

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#1263]
#### Summary

Sometimes clef cannot be connected to from bee due to `permission denied`. This is most likely a timing issue in the custom startup logic similar to issue #1257. It seems that sometimes our custom `chmod` happens too early.

#### Expected behavior

Bee connects to clef.

#### Actual behavior

Bee does not connect to clef with a `permission denied` denied.

**Comment by jpritikin** [comment]
Maybe same problem here,

````
Feb 19 20:44:48 glow bee[2942]: time="2021-02-19T20:44:48-05:00" level=error msg="cannot connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
Feb 19 20:44:53 glow bee[2942]: time="2021-02-19T20:44:53-05:00" level=error msg="cannot connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"

````

**Comment by ldeffenb** [comment]
Also #1271

**Comment by centerorbit** [comment]
I too was having the same issue as @jpritikin this seemed to fix the issue (run as root):

```bash
cd /var/lib/bee-clef/
chmod g+rw clef.ipc
```

Right away the bee service (that was continually trying to connect) instantly started working.

**Comment by jpritikin** [comment]
Yeah, that fix worked for me too.

**Comment by centerorbit** [comment]
I did find that when the clef service was turned off it didn't always remove the `clef.ipc` either, which then (upon restarting bee-clef) did not allow bee to communicate with bee-clef. I don't know if these issues are related, but the work-around to this is:

```bash
sudo service bee-clef stop
sudo rm /var/lib/bee-clef/clef.ipc
sudo service bee-clef start
```

... at which point bee will be able to communicate with bee-clef again.

**Comment by positive-approach** [comment]
The fix of "chmod 660 /var/lib/bee-clef/clef.ipc" is only temporary.  In my case, the bug happens every few hours, and persists until the fix is re-applied.  I imagine it is the same for the fix above.

At the moment this bug drives people away from using bee-clef, when bee-clef is encouraged..

**Comment by hlbcal** [comment]
sudo nano /lib/systemd/system/bee.service

then change both User and Group to root.

This works for me, or else I have to run it in screen from cli.
