### ISSUE TITLE
Enable passing DNS name to `--nat-addr`

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#1276]
Allow passing DNS name as a `--nat-addr` parameter so that we enable users using internet without static IP and Dynamic DNS

**Comment by Eknir** [comment]
@vandot , this was opened quite a long time ago. Is this still relevant? Do you have an idea on how many users would actually benefit from this?

**Comment by vandot** [comment]
@Eknir [PR](https://github.com/ethersphere/bee/pull/1278) is merged long time ago, just this issue was not connected to it, I will close it now
