### ISSUE TITLE
Install with docker-compose get stuck

### ISSUE THREAD

**Issue by zapaz** [ethersphere/bee#1279]
#### Summary
Install Bee and Clef with docker-compose fails on Mac

#### Steps to reproduce
Just follow the instructions :
https://github.com/ethersphere/bee/tree/master/packaging/docker

#### Expected behavior
Bee an Clef working

#### Actual behavior
bee and clef not connecting together :

`bee-1_1   | time="2021-02-17T20:42:52Z" level=error msg="cannot connect to clef signer: Post \"http://clef:8550/\": dial tcp 192.168.224.2:8550: connect: connection refused"`

#### Solution
add     "container_name: clef"  to service clef-1 in docker-compose.yml

**Comment by Eknir** [comment]
@zapaz , thanks for taking the time to create this issue! @rpicc , I believe you are already working on this, right? Could you please have a look in this and manage this issue? Thanks!

**Comment by Eknir** [comment]
This is difficult for us to reproduce. Can you please confirm whether this issue is still there with the newest releases of `bee` and `bee-clef`?
Closing the issue for now, but please give us an update!
