### ISSUE TITLE
Allow CORS for debug API [enhancement]

### ISSUE THREAD

**Issue by alsakhaev** [ethersphere/bee#1280]
"cors-allowed-origins" config doesn't affect a debug :1635 API

Use-case: web interface (gui) for administration of bee node

**Comment by alsakhaev** [comment]
looks like this piece of code is responsible for CORS in the Main API
https://github.com/ethersphere/bee/blob/5e1a341dc125e6a7d6594cedae7ad494e664c8be/pkg/api/router.go#L199-L205

and something similar is missing here:
https://github.com/ethersphere/bee/blob/5e1a341dc125e6a7d6594cedae7ad494e664c8be/pkg/debugapi/router.go#L153-L157

**Comment by vojtechsimetka** [comment]
This looks resolved by https://github.com/ethersphere/bee/pull/1288

**Comment by Eknir** [comment]
Documentation: document this and document sane usage of cors and document potential security concerns

**Comment by Eknir** [comment]
QA task : @sig or @vojtechsimetka , can you please let me know if this works as expected?
