### ISSUE TITLE
systemd service file should specify nice level

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#1286]
I suggest,

```
[Service]
Nice=10
```

I like nice bees.

**Comment by Eknir** [comment]
@jpritikin , could you please provide more context?

**Comment by jpritikin** [comment]
If I'm going to run bee on my work laptop then I don't want bee to hurt performance of other stuff that I'm doing.

**Comment by jpritikin** [comment]
Actually ionice may be equally important, https://web.archive.org/web/20150423145758/http://b.zekjur.net/2012/09/23/systemd-ionice.html

**Comment by jpritikin** [comment]
I encourage adding [memory limits](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LimitCPU=) too. However, I'm not sure what to recommend as defaults.

**Comment by jpritikin** [comment]
I added,

```
ProtectHome=yes
```

It would be great if more sandboxing protections could be enabled.

**Comment by vandot** [comment]
Hi @jpritikin thank for submitting this bug report.
Bee's systemd service file is placed inside `/lib/systemd/system/` folder, you are free to customize it as much as you want and just place custom systemd service file inside `/etc/systemd/system/` and systemctl will use that one for managing your service.
In this way your changes will not be overwritten with bee updates.
I will close this ticket, you are free to comment on it or to create new one if needed.

**Comment by jpritikin** [comment]
I encourage you to at least add my suggested customizations as **comments** in the distributed service file. I'm not a systemd expert; it took me hours of research just to come up with the tweaks that I recorded here.
