### ISSUE TITLE
Bee cluster management with a single multi-user Clef instance 

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1287]
# User story
## Story

I'm an user running a cluster of Bee nodes. I want to use Clef for sign my transactions, but I've the issue that each Bee instance wants its running clef instance. This is an issue, because I want to be agile scaling my cluster. When I need a new bee node, I want to add a Bee node. If I don't need it, I want to be able to destroy one. I want to have minimal configurations.

Currently each node has to be in pair with a dedicated clef instance, otherwise bee nodes sharing the same clef instance will have the same address, and each new deployment have to configure specific network settings for link the bee node to its specific clef instance.

## Acceptance criteria

Any new Bee node have to get a different address connecting to a same clef instance the first time. Every time that a node connects again to the clef instance, it will be able to reuse the previously assigned address.

The cluster can assume that all nodes and the connecting network are trusted.

**Comment by ralph-pichler** [comment]
support for using the same clef for multiple bees has been added as of pr #1313 (which will be released with 0.5.3) but you will need to manually specify which address to use with `--clef-signer-ethereum-address` in a multi-node setup.

**Comment by Eknir** [comment]
@tmm360 , I believe this was added with `0.5.3`, although some convenience for the user is missing (see https://github.com/ethersphere/bee/issues/1481). Perhaps you could have a look at #1481 ? Let us know if you have questions with configuring. Closing the issue for now!

**Comment by tmm360** [comment]
Yes please, it's not clear to me how to configure bee nodes with a single clef instance.
Is already possible, or #1481 have to be implemented first? Thanks!

**Comment by attila-lendvai** [comment]
to my understanding, it's already possible. see e.g.: https://github.com/mfw78/apiarist

the general idea is to have one `clef` instance for each blockchain (goerli, xdai for testnet and mainnet), and multiple bee nodes with different `--clef-signer-ethereum-address` arguments.
