### ISSUE TITLE
PSS

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#129]
## Description
As a decentralized application developer, I want to send private messages to other nodes who might be offline or online, such that we can interact without being noticed and without risk of being censored.

## Background
- BOS (sec 4.4)

## Acceptance criteria
- A message can be send to any other node in the Swarm network without leaking the content of the message nor the fact that we are messaging
- The message should be received, even if not online at, or directly after, the moment of sending

**Comment by acud** [comment]
why do we need "PSS" per se? can't we just throw this on the push sync protocol and use trojan chunks?

**Comment by acud** [comment]
@zelig
