### ISSUE TITLE
Expose welcome messages in API

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1292]
# User story

## Story

As a observer of my own bee topology, I would like to know the welcome messages from all nodes, such that I can see if my friends are there or react on any message they may send me

## Acceptance criteria

- The welcome messages from all currently-connected nodes are stored in relationship to the overlay address of the node who sent the message
- When a node disconnects, his/her welcome message is purged from the list

## Background

- This feature exposes the welcome message feature (already implemented and logging to the terminal) in such a way that it becomes use able without looking at the logs only

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by acud** [comment]
@Eknir did you consider the XSS attack dimensions of this feature?

**Comment by Eknir** [comment]
This would expose a vulnerability (XSS)

**Comment by Eknir** [comment]
This would expose a vulnerability (XSS)

**Comment by Eknir** [comment]
This would expose a vulnerability (XSS)
