### ISSUE TITLE
incompletely uploaded file?

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#1293]
#### Summary
I tried to upload a 4 min video of a [mocha recipe](https://gateway.ethswarm.org/files/9f74d494b4e8f44569f5357673cf5c5b4db8183b21be88483942734c30bbb2c1)

It seems to have succeeded. I tried to upload it [again](https://gateway.ethswarm.org/files/0a8693c0ee66aa488e43fdf683397208111f6b5258071f7025797b5b2c461c12} and it succeeded immediately.

#### Steps to reproduce
I began a large upload and restarted the bee node a few times while it was sync'ing.

#### Expected behavior
The video should download correctly.

#### Actual behavior

It consistently fails to download from the main gateway,

```
joshua@salvia /o/n/mocha> wget 'https://gateway.ethswarm.org/files/0a8693c0ee66aa488e43fdf683397208111f6b5258071f7025797b5b2c461c12'
--2021-02-19 07:49:44--  https://gateway.ethswarm.org/files/0a8693c0ee66aa488e43fdf683397208111f6b5258071f7025797b5b2c461c12
Resolving gateway.ethswarm.org (gateway.ethswarm.org)... 3.223.43.33
Connecting to gateway.ethswarm.org (gateway.ethswarm.org)|3.223.43.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 137040833 (131M) [video/mp4]
Saving to: ‘0a8693c0ee66aa488e43fdf683397208111f6b5258071f7025797b5b2c461c12’

0a8693c0ee66aa488e43fd   1%[                          ]   2.00M  --.-KB/s    in 31s     

2021-02-19 07:50:38 (66.2 KB/s) - Connection closed at byte 2097152. Retrying.
```

Maybe the main gateway has a size restriction on serving files? Is there some other gateway that I can use to test whether the file is served properly?

**Comment by jpritikin** [comment]
Another gateway exhibits the same problem, http://193.70.46.225:1633/files/0a8693c0ee66aa488e43fdf683397208111f6b5258071f7025797b5b2c461c12

**Comment by jpritikin** [comment]
Uploaded the same video to [another gateway](http://193.70.46.225:1603/files/35e5648bb060b3dd6aee4bf7118f53a453e72269929fbaa3f08e89363a6ee5af). I get a 404 when I try to download it on my local node.

**Comment by Eknir** [comment]
We are continuously working on improving the reliability of Bee, are improving on our current testing framework and are setting up new testing frameworks to gauge the service level of the Swarm network.
Since this issue is not actionable, I will close it. Please rest assured however, that we are continuously looking on how to increase the reliability of Bee and the Swarm network.
