### ISSUE TITLE
Find out status of Ethereum connection and chequebook deployment

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1295]
# User story

## Story

As a user who is setting up his/her bee node, I want to view in a browser application whether I am connected to Ethereum; whether my chequebook is deployed; whether my node has sufficient eth/BZZ, such that I don't need to look in the logs on clues how to setup my bee node and I can get instructions on this browser page when something is not yet working

## Acceptance criteria

There exists an API endpoint for:
   - connection with Ethereum
   - gETH on overlay
   - gBZZ on overlay
And these endpoints are exposed before the chequebook is deployed

## Background

We want to put less emphasis on our logs and enable bee dashboards to give rich experience on the status of the Bee node. Above-mentioned statuses are important to help the user in starting the Bee node.
Related project: https://hackmd.io/SZ-YbMRDSUytRjhcxg6Xtg?both 
Currently, it is not possible to know all this, because the API router is only instantiated after the chequebook is deployed. That order should be the other way around in order to support his

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by vojtechsimetka** [comment]
Created repo where the development will take place https://github.com/ethersphere/bee-status

**Comment by Eknir** [comment]
To which Ethereum network am I connected?

**Comment by acud** [comment]
I'm not sure whether this is needed and what is the purpose here. It would be difficult to assert whether the node has a living eth backend and display the progress of the chequebook deployment. Some information is already being displayed in the terminal.

**Comment by acud** [comment]
@agazso @vojtechsimetka

**Comment by agazso** [comment]
I think this has been fixed and the debug API is initialized before the node is connected to the blockchain endpoint or other nodes. This may be problematic again in the future when the Bebug and Bee APIs are going to be merged.

This is going to be more important in Milestone 2 but I think we can close it for now.

**Comment by acud** [comment]
Thanks @agazso
