### ISSUE TITLE
bee heavily polls unsynced Ethereum backend

### ISSUE THREAD

**Issue by d10r** [ethersphere/bee#1296]
#### Summary
When starting a bee with the configured Ethereum node not synced, bee seems to flood that node with requests according to the node log.

bee output:
```
bee_1  | time="2021-02-19T19:54:39Z" level=info msg="waiting for ethereum backend to be synced."
```
Looks innocent.  
However the log of the Ethereum node says:
```
Feb 19 20:57:40 xx openethereum[6379]: 2021-02-19 20:57:40    0/25 peers     78 KiB chain  0 bytes queue  RPC:  0 conn, 3003 req/s,    6 µs
Feb 19 20:58:10 xx openethereum[6379]: 2021-02-19 20:58:10    0/25 peers     78 KiB chain  0 bytes queue  RPC:  0 conn, 2982 req/s,    5 µs
...
```
After stopping the waiting bee node, the value for _req/s_ of the Ethereum node drops to 0:
```
Feb 19 20:59:10 xx openethereum[6379]: 2021-02-19 20:59:10    0/25 peers     78 KiB chain  0 bytes queue  RPC:  0 conn,    0 req/s,    4 µs
```

Which suggests that the bee node does bruteforce polling of the syncing node.  
Also the bee process shows 100% CPU utilization in top in that situation.

**Comment by Eknir** [comment]
@d10r , thanks! This is valuable information. @rpicc, could you please have a look in this issue, confirm it and then fix?

**Comment by d10r** [comment]
btw. this may happen in general when the Ethereum RPC doesn't respond as expected.  
Today I had runaway load which I think was caused by the free Infura quota being exceeded:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/5479136/108605022-a5066f00-73b1-11eb-9a8a-ba985b72c880.png">
(the final drop is after stopping the bees)

**Comment by paxthemax** [comment]
This was fixed by @ralph-pichler on latest master :)

**Comment by Eknir** [comment]
@d10r , could you please do some basic QA around this issue and report the outcome here? The situation should have improved.

**Comment by d10r** [comment]
can confirm it's fixed
