### ISSUE TITLE
Density proofs in push sync receipt

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1301]
# Density proofs idea
**Challenge**: Given one address in the Swarm address space (target), give me the closest n chunk(s)/segment proofs of chunks closest to this target. The chunks close to the target need to have a valid postage stamp.

**Interpretation**: With the answer to this challenge, the challenger can obtain samples of maximum density of chunks in challengee’s storage. From the density sample, the challenger can infer the size of challengee’s storage using maximum likelihood estimation of the number of chunks.

# Why density proofs
- Prevent spoof-ability of signature (#1300)

# Appendix
## Formal specification of density proofs

Density proofs are based on the assumption, that 

Let. `S={s0,s1,.... s2n}` is a sample of size `2^n` from a uniform distribution, where `n` is not known

Let `O(S,a):= <s_f(0),s_f(1),....>` be an ordering of `S` based on distance from `a` (decreasing proximity order), i.e., the index function `f` is such that for any `i=[0,n)`, `XD(a,s_f(i)) < XD(a,s_f(i+1))`  

The task is to estimate `n` from ` d=PO(a, s_f(2^w))`

Using maximum likelihood estimation

` d=PO(a, s_f(2^w))) => n =~ d+w` and the variance is logarithmic  in `w`

## the mapping function

The sample should depend on stored chunks, but the storers should be prevented from mining new chunks so that they can manipulate their density proof.

In  order to do this, the chunk address is not an input param for the  sampling  function but the within-batch index is, which links  each chunk to a ticket. The sampling function `s` is defined as follows:

	s(t,c) := H(anchor(t)|index(PS(c))|id(PS(c)))

Applying this  function to all chunks within the neighbourhood defined by the consensus depth `D`, results in the sample `S(t,D)`

    S(t,D) := {s(t,c)| c \in Chunks(D)}

With the assumption that `n` is a storer node in the same neighbourhood as  `anchor(t)`, i.e, `PO(overlay(n), anchor(t))  >= D`
This sample is 

- known to all  nodes within the neighbourhood
- as a result of `H`, it is uniformly distributed (in the space of 256 bit integers)
- let `f` be the ordering function for `O(S,anchor(t))`

For a given order `w`, the density sample is  defined as:

	DS(T,D,W) := <s_f(0), s_f(1), ... s(f(2^w))>
	
where 
	
	s_i \in S(T,D)
	
## The density sample
	
The density sample is structured in a swarm merkle tree, the root of which is `HDS(T,D,W)`

The proof consists of showing an inclusion proof for a chunk within this sample and provide the corresponding segment proof and postage stamp.
The index of the element to show as well as the segment index for the segment proof is specific to a node so that it cannot be stolen and also depends on the DS Merkle hash so that the sample cannot be spoofed to be correct only on a select index.

     I(c,n,T,D,W) := HDS(T,D,W) XOR addr(c) XOR overlay(n) 

Let the sample index be 

	I_s(c,n,T,D,W) := I(c,n,T,D,W) % 2^W		
	
	c_f(I_s(c,n,T,D,W))
		
and `IP(c,n,T,D,W)` be the inclusion proof of `c_f(I_s(c,n,T,D,W))`

	
the segment proof for the corresponding chunk

	SP(c,n,T,D,W) :=    SP(c_f(I_s(c,n,T,D,W)), I(c,n,T,D,W) % 128)
	

Finally, the density proof 

     <PS(c), HDS(T,D,W), SP(c,n,T,D,W), IP(c,n,T,D,W), signature>
     
## Validity  check

when a node receives  the  density proof, it needs to validate  it by carrying out the following checks.
- validate postage stamp -> chunk addr `h=BMT(c)`
- get `T,D,W` from the blockchain
- recover pubkey from signature and calculate overlay `n`
- calculate `i=I(c,n,T,D,W)`, then 
- validate bmt segment proof -> `SP(c,n,T,D,W)`
- validate inclusion proof -> `IP(c,n,T,D,W)`
- calculate `d=PO(h,s)` and conclude storage size  `2^d`

**Comment by acud** [comment]
@eknir says we might not need this [link](https://hackmd.io/C4g-PJ2gTv6fm-96rj7zCA)
