### ISSUE TITLE
Get current pins

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1302]
# User story

## Story
As a local pinner, I want to retrieve all pinned roots of the content which I am currently pinning, such that I can manage these pins (remove, validate if still available, etc).

## Acceptance criteria
- The API exposed to the user should interact with pinned roots only

## Background
Pinned can come into the node either by uploads using the `Swarm-Pin` header, or, by downloads using the traversal service.

Right now, the implementation of the pinning API is a bit skewed and misinterpreted as it exposes localstore internals through the API package, by leaking individual chunk pin counters. This is not very user-friendly, complicates user onboarding, as well as leaks undesired internals that could hinder storage guarantees given by storage incentives that use pinning under-the-hood

## Tasks
- An additional abstraction should be defined to cater for the pinned root interaction. 
- Basic CRUD operations should be defined on the interface. 
- Pinned roots should be persisted in statestore
- API changes could be confined to just an extra middleware that would intercept incoming upload requests that have the pin header, then add the root once the request returns.
- Current API endpoints should be scratched and reimplemented (GET,DELETE,POST) using the aforementioned abstraction 
- PinCounter methods removed from the `swarm.Chunk` interface
- Beekeeper integration tests adjusted

Revised API definitions:
- `GET /pins` - gets all pinned roots
- `DELETE /pins/<root>` - unpins a root and all of its associated chunks (manifests and actual data chunks)
- `POST /pins/<unpinned root>` - tries to pin an unpinned root, fetching missing chunks from the network

**Comment by significance** [comment]
> Current API endpoints should be scratched and reimplemented (GET,DELETE,POST) using the aforementioned abstraction

i think it would be good to retain visibility of the individual chunks that are pinned at the api level. when we are ensuring data availability from a data stewards position (a la 1508) it is important to know that each and every chunk is alive and available from all sections of the network.
