### ISSUE TITLE
https://rpc.slock.it/goerli 503

### ISSUE THREAD

**Issue by zl-8888** [ethersphere/bee#1305]
____  _            _        _           _           _____                 _                                  _   _           _         
            |  _ \| |          | |      | |         (_)         |  __ \               | |                                | | | |         | |        
            | |_) | | ___   ___| | _____| |__   __ _ _ _ __  ___| |  | | _____   _____| | ___  _ __  _ __ ___   ___ _ __ | |_| |     __ _| |__  ___ 
            |  _ <| |/ _ \ / __| |/ / __| '_ \ / _` | | '_ \/ __| |  | |/ _ \ \ / / _ \ |/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __| |    / _` | '_ \/ __|
            | |_) | | (_) | (__|   < (__| | | | (_| | | | | \__ \ |__| |  __/\ V /  __/ | (_) | |_) | | | | | |  __/ | | | |_| |___| (_| | |_) \__ \
            |____/|_|\___/ \___|_|\_\___|_| |_|\__,_|_|_| |_|___/_____/ \___| \_/ \___|_|\___/| .__/|_| |_| |_|\___|_| |_|\__|______\__,_|_.__/|___/
                                                                                              | |                                                   
            ==================================================================================|_|===================================================

                                                                   ____          ____
                                                                  |oooo|        |oooo|
                                                                  |oooo| .----. |oooo|
                                                                  |Oooo|/\_||_/\|oooO|
                                                                  `----' / __ \ `----'
                                                                  ,/ |#|/\/__\/\|#| \,
                                                                 /  \|#|| |/\| ||#|/  \
                                                                / \_/|_|| |/\| ||_|\_/ \
                                                               |_\/    o\=----=/o    \/_|
                                                               <_>      |=\__/=|      <_>
                                                               <_>      |------|      <_>
                                                               | |   ___|======|___   | |
                                                              //\\  / |O|======|O| \  //\\
                                                              |  |  | |O+------+O| |  |  |
                                                              |\/|  \_+/        \+_/  |\/|
                                                              \__/  _|||        |||_  \__/
                                                                    | ||        || |
                                                                   [==|]        [|==]
                                                                   [===]        [===]
                                                                    >_<          >_<
                                                                   || ||        || ||
                                                                   || ||        || ||
                                                                   || ||        || ||     
                                                                 __|\_/|__    __|\_/|__
                                                                /___n_n___\  /___n_n___\

                                      ============================================================================
                                      503 <==> Service Unavailable
                                      ============================================================================

**Comment by jpritikin** [comment]
You can create an account at https://infura.io/ if you don't want to run your own ethereum node.

**Comment by him2him2** [comment]
I updated my nodes to run https://goerli.prylabs.net/

This works, but probably should run my own:
https://github.com/goerli/testnet
