### ISSUE TITLE
Chunk garbage collector issue

### ISSUE THREAD

**Issue by him2him2** [ethersphere/bee#1306]
#### Summary
Have several nodes that exceed available drive space. The node stops working. There are errors in the log about no drive space. I increased node's drive space and reduce the nodes db-capacity. The node starts working again and fills even more drive space. The chuck garbage collector does not seem to work correctly. 

#### Steps to reproduce

the db-capacity is set to:
db-capacity: 1167175

On bee start the debug shows:
INFO[2021-02-21T13:12:57Z] database capacity: 1167175 chunks (approximately 4.6GB) 

However after several hrs of running the hard drive shows:

linux:~# du -h /var/lib/bee/localstore/
27G	/var/lib/bee/localstore/
This number is not decreasing.

#### Expected behavior
The localstore chuck garbage collector should collect down to something close to 4.6GB

#### Actual behavior
The localstore is at 27G not 4.6GB
There are no error messages about this. If there is space on the drive the node runs again. The collector just does not collect.

Note: Once the hard drive is full. You get an error in the logs that says that the garbage collector failed because it could not write to the log. Seems strange that the process that should be clearing drive space failed because it can't write to the log to tell you it was cleaning up. It puts you in a spot that you can get out of. It can't clear drive space because it has no space to write a log about the fact it was freeing space.

#### Node information

linux:~# bee version
0.5.0-bd14a67

linux:~# lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

**Comment by jpritikin** [comment]
Duplicate #1258

**Comment by Eknir** [comment]
@jpritikin , I close this issue in favor of #1258. We will take the information int his issue into account, however. Thanks for reporting!
