### ISSUE TITLE
Can not start

### ISSUE THREAD

**Issue by zhangsj** [ethersphere/bee#1307]
- Logs begin at Tue 2020-09-01 06:32:47 UTC. --
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:    ____________(%%%%%%%)____________
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:   (     /   /  )%%%%%%%(  \   \     )
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:   (___/___/__/           \__\___\___)
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:      (     /  /(%%%%%%%)\  \     )
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:       (__/___/ (%%%%%%%) \___\__)
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:               /(       )\
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:             /   (%%%%%)   \
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:                  (%%%)
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]:                    !
Feb 22 08:05:40 ip-172-31-11-114 bee[6232]: time="2021-02-22T08:05:40Z" level=info msg="version: 0.5.0-bd14a67"

stop at here

**Comment by Eknir** [comment]
There is not enough information in this issue to help you. Please reach out to `bee-support` on our Discord server and we will help you there! https://discord.gg/KWREPyqn
