### ISSUE TITLE
Huge block I/O consumption in comparison to network I/O

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee#1312]
#### Summary

According to `docker stats`:

```
CONTAINER ID   NAME             CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
b6818110e6a1   swarm-2_bee_1    86.87%    5.457GiB / 62.82GiB   8.69%     1.14GB / 136MB    7.76GB / 59.2GB   33
1f0cd61ea368   swarm-1_bee_1    62.14%    4.779GiB / 62.82GiB   7.61%     917MB / 111MB     5.45GB / 61.5GB   30
a001af088548   swarm-0_bee_1    122.15%   7.407GiB / 62.82GiB   11.79%    1.17GB / 76.5MB   5.36GB / 83.2GB   27
```

The block I/O is huge in comparison to net I/O.

#### Steps to reproduce

Just running a standard node should do it, or at least on Docker.

#### Expected behavior

I expect `bee` to use way less disk I/O.

#### Actual behavior

For each of those `bee` nodes, there is a 50 to 70 times amplification from data ingested through network to disk writes. It looks like the node is constantly writing and deleting data, which causes an extremely high disk usage for a quite small amount of data.

**Comment by attila-lendvai** [comment]
i see this also, without docker, straight on nixos.

i'm running the bee and clef processes with nice and ionice, and they are still hogging my laptop, apparently due to disk io. filesystem journaling is at the top of `iotop`.

**Comment by attila-lendvai** [comment]
@filoozom do you have swap enabled? this could be due to clef using enormous amounts of memory, that overflows into swapping:

https://github.com/ethereum/go-ethereum/issues/22361

**Comment by filoozom** [comment]
> @filoozom is swapping involved? this could be due to clef using enormous amounts of memory, that overflows into swapping:
> 
> [ethereum/go-ethereum#22361](https://github.com/ethereum/go-ethereum/issues/22361)

I actually also opened an (albeit less insightful) issue on the `clef` RAM usage issue, so I'm fairly sure that's not my problem this time. I didn't show the `clef` container stats, but they were under control at around 700 MB per instance (which is still a lot, but not problematic in my case).

**Comment by filoozom** [comment]
This is what I currently have:

```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
0dcf51b25373   swarm-no-clef_bee_1   479.14%   10.52GiB / 62.82GiB   16.75%    54.4GB / 51GB     8.22GB / 1.92TB   31
6c520d04573f   swarm-2_bee_1         2.78%     5.13GiB / 62.82GiB    8.17%     3.05GB / 5.14GB   30.7GB / 805GB    25
92ebac7dad42   swarm-1_bee_1         74.73%    10.91GiB / 62.82GiB   17.36%    5.18GB / 3.03GB   36.1GB / 1.51TB   29
44892b7ee96b   swarm-0_bee_1         20.59%    5.598GiB / 62.82GiB   8.91%     2.94GB / 2.71GB   29.4GB / 611GB    28
fbaddc4e0127   swarm-2_clef_1        0.00%     661.2MiB / 62.82GiB   1.03%     1.2MB / 836kB     795kB / 0B        24
d4514547ab17   swarm-1_clef_1        0.02%     504.8MiB / 62.82GiB   0.78%     1.05MB / 728kB    20.8MB / 0B       24
1a14ad418256   swarm-0_clef_1        0.00%     664.3MiB / 62.82GiB   1.03%     2.42MB / 1.75MB   53.8MB / 61.4kB   24
```

I disabled the swap entirely to be sure that wasn't it (but even if it was, it wouldn't appear in Docker's block I/O stats). Mind you the `swarm-no-clef_bee_1` container was created shortly after I opened this issue, so a bit less than 7 hours ago, and it already wrote almost 2 TB of data, with only 55 GB network ingress...

**Comment by filoozom** [comment]
An update after running for around 24 hours (with nodes that already ran for 3 days previously, it was just a restart, except `swarm-no-clef_bee_1` which is new):
```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
0dcf51b25373   swarm-no-clef_bee_1   1.23%     10.91GiB / 62.82GiB   17.36%    113GB / 179GB     92GB / 5.6TB      31
6c520d04573f   swarm-2_bee_1         0.24%     9.579GiB / 62.82GiB   15.25%    13.4GB / 22.1GB   136GB / 3.86TB    25
92ebac7dad42   swarm-1_bee_1         0.18%     6.515GiB / 62.82GiB   10.37%    10.1GB / 9.34GB   106GB / 3.23TB    29
44892b7ee96b   swarm-0_bee_1         0.17%     5.034GiB / 62.82GiB   8.01%     9.93GB / 22.2GB   125GB / 2.13TB    28
fbaddc4e0127   swarm-2_clef_1        0.08%     879.6MiB / 62.82GiB   1.37%     3.18MB / 2.23MB   1.63MB / 0B       24
d4514547ab17   swarm-1_clef_1        0.07%     645.9MiB / 62.82GiB   1.00%     2.72MB / 1.93MB   21.4MB / 0B       24
1a14ad418256   swarm-0_clef_1        0.13%     539.8MiB / 62.82GiB   0.84%     4.4MB / 3.14MB    54.8MB / 61.4kB   24
```

We now have up to a 320x ratio between network ingress and disk writes. I'll have to replace my SSDs every few days at this rate! 😜

**Comment by veqtor** [comment]
I am also experiencing this problem, made me shutdown my bee nodes to save SSDs

**Comment by Eknir** [comment]
Hi all, this is supposedly fixed (or improved) with #1339 . I would be happy if somebody could validate that this is indeed fixing the issue.

**Comment by filoozom** [comment]
Hi,

It's definitely not fixed. Here is `docker stats` of recently rebooted nodes:

```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
888c67828243   swarm-9_bee_1         60.82%    1.751GiB / 62.82GiB   2.79%     6.11GB / 6.07GB   269GB / 445GB    40
8dfbccb8759f   swarm-8_bee_1         82.81%    1.854GiB / 62.82GiB   2.95%     6.52GB / 5.56GB   243GB / 355GB    39
12d221a5ec09   swarm-7_bee_1         302.01%   19.34GiB / 62.82GiB   30.79%    17.2GB / 6.45GB   148GB / 211GB    49
5734da6b14f6   swarm-6_bee_1         172.90%   1.914GiB / 62.82GiB   3.05%     4.24GB / 9.16GB   289GB / 282GB    43
fb6a704fa677   swarm-5_bee_1         251.29%   1.585GiB / 62.82GiB   2.52%     2.59GB / 3.66GB   175GB / 206GB    55
809808df1efb   swarm-4_bee_1         155.89%   1.57GiB / 62.82GiB    2.50%     5.13GB / 5.87GB   257GB / 323GB    45
397020acf853   swarm-3_bee_1         30.78%    1.228GiB / 62.82GiB   1.96%     4.09GB / 2.81GB   241GB / 326GB    45
48b974198760   swarm-2_bee_1         29.79%    1.708GiB / 62.82GiB   2.72%     5.64GB / 5.04GB   277GB / 424GB    68
7fa1da0d0e26   swarm-1_bee_1         158.67%   1.23GiB / 62.82GiB    1.96%     3.71GB / 684MB    184GB / 275GB    54
9f3bbec92581   swarm-0_bee_1         42.16%    1.718GiB / 62.82GiB   2.74%     5.47GB / 1.46GB   258GB / 385GB    37
c8f7966c141b   swarm-no-clef_bee_1   232.79%   3.234GiB / 62.82GiB   5.15%     325GB / 78.1GB    1.01TB / 658GB   102
129b55e00070   swarm-9_clef_1        0.00%     78.55MiB / 62.82GiB   0.12%     46.1MB / 24.9MB   901MB / 0B       24
8905530bd4c3   swarm-8_clef_1        0.00%     81.57MiB / 62.82GiB   0.13%     30.2MB / 18.5MB   810MB / 0B       24
1f68bd5f8efa   swarm-7_clef_1        0.00%     75.76MiB / 62.82GiB   0.12%     27.6MB / 18.1MB   564MB / 0B       24
a3b134b68c31   swarm-6_clef_1        0.02%     69.42MiB / 62.82GiB   0.11%     38.3MB / 24.9MB   1GB / 0B         24
086da1e24550   swarm-5_clef_1        0.01%     71.43MiB / 62.82GiB   0.11%     19.9MB / 13.2MB   531MB / 0B       23
ce76cd819837   swarm-4_clef_1        0.00%     75.79MiB / 62.82GiB   0.12%     21.1MB / 14MB     404MB / 0B       24
50ef9aa80d60   swarm-3_clef_1        0.00%     75MiB / 62.82GiB      0.12%     19MB / 11.7MB     339MB / 0B       24
febca8eb86ba   swarm-2_clef_1        0.00%     73.14MiB / 62.82GiB   0.11%     16MB / 10.8MB     656MB / 0B       24
9e767072c4c6   swarm-1_clef_1        0.00%     54.45MiB / 62.82GiB   0.08%     11.1MB / 7.78MB   643MB / 0B       24
8883a4ee24aa   swarm-0_clef_1        0.02%     72.36MiB / 62.82GiB   0.11%     38.7MB / 24.2MB   831MB / 0B       24
```

While nodes can now run at less than 100% IO, it still doesn't make any sense that they write so much data. Also, I don't think that the 32 MB buffer is enough. It really only starts to make a difference around 1 GB for me, and with a way higher `openFileLimit` to.

**Comment by veqtor** [comment]
Hmm, not sure it's better for everyone, but it's a bit better for me now, definetly an improvement, but I think this could be tweaked even more! But again, I would much rather have my node consume more memory than this much disk i/o if possible.
I could probably easiely run the entire DB in memory actually.

**Comment by Eknir** [comment]
@veqtor @filoozom , how is it looking now with 0.5.3?

**Comment by filoozom** [comment]
> @veqtor @filoozom , how is it looking now with 0.5.3?

Not a whole lot better I'd say:
```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
9a76863710cf   swarm-9_bee_1         110.67%   461.9MiB / 62.82GiB   0.72%     52.4GB / 78.3GB   2.54TB / 5.88TB   50
7c55e167f92c   swarm-8_bee_1         93.31%    1.622GiB / 62.82GiB   2.58%     46.3GB / 62.5GB   2.44TB / 6.15TB   63
14b6e171c607   swarm-7_bee_1         31.90%    745.1MiB / 62.82GiB   1.16%     63.4GB / 63.5GB   2.44TB / 5.01TB   54
1195fb73beab   swarm-6_bee_1         105.46%   3.034GiB / 62.82GiB   4.83%     63.4GB / 199GB    2.99TB / 8.13TB   48
070ed1e6999d   swarm-5_bee_1         86.80%    4.371GiB / 62.82GiB   6.96%     45.7GB / 37.5GB   2.34TB / 5.44TB   55
508c6d7834c6   swarm-4_bee_1         181.27%   8.664GiB / 62.82GiB   13.79%    115GB / 67.5GB    3.75TB / 13TB     61
702db78dd60c   swarm-3_bee_1         67.71%    1.195GiB / 62.82GiB   1.90%     58.1GB / 59.8GB   2.28TB / 4.75TB   70
54471834ed3f   swarm-2_bee_1         79.66%    2.825GiB / 62.82GiB   4.50%     43.9GB / 92.7GB   2.47TB / 6.16TB   43
c37721fedb49   swarm-1_bee_1         114.79%   2.122GiB / 62.82GiB   3.38%     89.6GB / 58.4GB   2.81TB / 8.04TB   42
c9dc17c0f06f   swarm-0_bee_1         7.65%     4.194GiB / 62.82GiB   6.68%     44.8GB / 57GB     2.46TB / 6.39TB   52
89cb3cd88fc2   swarm-no-clef_bee_1   512.33%   3.38GiB / 62.82GiB    5.38%     44.2GB / 138GB    1.82TB / 1.02TB   87
788b4160b5a0   swarm-9_clef_1        0.00%     86.37MiB / 62.82GiB   0.13%     285MB / 187MB     26.7GB / 0B       25
ca8e71c32f4d   swarm-8_clef_1        0.01%     78.56MiB / 62.82GiB   0.12%     219MB / 144MB     31.4GB / 0B       27
20d97b244686   swarm-7_clef_1        0.03%     78.59MiB / 62.82GiB   0.12%     175MB / 115MB     27.5GB / 0B       26
6355df868b08   swarm-6_clef_1        0.04%     85.41MiB / 62.82GiB   0.13%     304MB / 195MB     35.4GB / 0B       26
8df0b7d2a2f3   swarm-5_clef_1        0.00%     77.93MiB / 62.82GiB   0.12%     154MB / 103MB     18.4GB / 0B       29
a6283f8cbb19   swarm-4_clef_1        0.03%     78.54MiB / 62.82GiB   0.12%     430MB / 283MB     28.7GB / 0B       29
70a9a791d6b0   swarm-3_clef_1        0.00%     72.07MiB / 62.82GiB   0.11%     152MB / 101MB     19.2GB / 0B       26
e2d29a545de5   swarm-2_clef_1        0.00%     78.91MiB / 62.82GiB   0.12%     156MB / 102MB     20GB / 0B         29
50c39f8b7ebc   swarm-1_clef_1        0.00%     78.6MiB / 62.82GiB    0.12%     273MB / 178MB     32.2GB / 0B       25
72f0361c6a04   swarm-0_clef_1        0.01%     78.93MiB / 62.82GiB   0.12%     350MB / 229MB     38.6GB / 0B       27
```

**Comment by Eknir** [comment]
@filoozom, did you already try to play with the leveldb configuration parameters? see https://github.com/ethersphere/bee/releases/tag/v0.5.3

**Comment by filoozom** [comment]
> @filoozom, did you already try to play with the leveldb configuration parameters? see https://github.com/ethersphere/bee/releases/tag/v0.5.3

I have indeed. I've also been leading an effort to collect some of those metrics here and on Discord: https://docs.google.com/spreadsheets/d/1bi6LSYRTbdkdy8pPgy3npbqEkioPAi_NZVl_weE0VI8/edit#gid=0

My nodes are currently running with:
```
- BEE_DB_OPEN_FILES_LIMIT=65536
- BEE_DB_BLOCK_CACHE_CAPACITY=134217728
- BEE_DB_WRITE_BUFFER_SIZE=134217728
- BEE_DB_DISABLE_SEEKS_COMPACTION=false
```

This is where I felt I got the most performance out of it. Increasing the cache and buffer size further does not yield better results, and starts to use too much RAM. However, my tests weren't scientific, and mostly just watching `htop` and `iostat` after a reboot.

I'm still not exactly sure what disabling seeks compaction does, but I feel like it made the database grow in size really fast. Might have been related to something else though.

**Comment by Eknir** [comment]
Wow! This is great!

In terms of improvements with these configurations, what did you/other people notice?

We kept our default configuration, because we don't want to bump into system limits of any system, but, with your knowledge, would you recommend different default values for Bee?

**Comment by filoozom** [comment]
> We kept our default configuration, because we don't want to bump into system limits of any system, but, with your knowledge, would you recommend different default values for Bee?

I opened a separate issue for this: #1559. It looks like most systems have a quite high `ulimit -Hn`, the smallest recorded on the spreadsheet being 4096. The second smallest is 65536. My take is that the software should increase the limit automatically up to say `ulimit -n` minus a safe margin of maybe 200 - 300. A message should also be logged if that limit is too low. That's inspired of Redis' way of doing it.

Also, as `bee` is available in packages, you could simply increase the limit in the appropriate init configurations.

Example for `systemctl`:
```
[Service]
LimitNOFILE=65536
```

Example for `docker-compose.yaml`:
```
services:
  bee:
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
```

**Comment by Eknir** [comment]
Amazing. Thanks a lot. The task is scheduled.

**Comment by Eknir** [comment]
@filoozom , with the correct parametrization of `BEE_DB_OPEN_FILES_LIMIT` (https://github.com/ethersphere/bee/issues/1559), would you consider this issue fixed?

**Comment by Eknir** [comment]
@filoozom , with the correct parametrization of `BEE_DB_OPEN_FILES_LIMIT` (https://github.com/ethersphere/bee/issues/1559), would you consider this issue fixed?

**Comment by filoozom** [comment]
@eknir This one I'm not sure, I still think `bee` is reading and writing way too much. How can you write 170 MB/s with only 120 Mb/s (15 MB/s) in ingress? I still feal like it's shuffling data around for no apparent reason.

**Comment by jpritikin** [comment]
The change to systemd is mentioned in issue #1485. Maybe mark it as a duplicate.

**Comment by marvin9002** [comment]
Show your docker-compose file and .env for a look

**Comment by filoozom** [comment]
I'm not sure this should be closed yet. Looking at `docker stats`:
```
CONTAINER ID   NAME                  CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
24133e9b0f23   swarm-15_bee_1        112.60%   366.7MiB / 62.72GiB   0.57%     9.05MB / 11.8MB   721kB / 44.3GB    20
a36a31365e4d   swarm-14_bee_1        91.09%    426.3MiB / 62.72GiB   0.66%     14.2MB / 19MB     696kB / 37.9GB    19
17c41a451cd8   swarm-13_bee_1        83.60%    359.1MiB / 62.72GiB   0.56%     10.4MB / 10.6MB   995kB / 38GB      19
982db195ffd2   swarm-12_bee_1        97.23%    368.8MiB / 62.72GiB   0.57%     13.2MB / 13.2MB   639kB / 64GB      20
88afa636e7f6   swarm-11_bee_1        91.07%    345.7MiB / 62.72GiB   0.54%     10.3MB / 13.1MB   594kB / 49.3GB    19
fd603ecfd103   swarm-10_bee_1        90.63%    410MiB / 62.72GiB     0.64%     14.5MB / 16.4MB   713kB / 44.6GB    20
af1871471a58   swarm-9_bee_1         99.93%    429.2MiB / 62.72GiB   0.67%     16.8MB / 21.2MB   1.04MB / 63.4GB   19
d5108f2ca478   swarm-8_bee_1         82.23%    466.4MiB / 62.72GiB   0.73%     19.2MB / 22.9MB   1.06MB / 55.7GB   20
aa986ba5454c   swarm-7_bee_1         98.49%    387.4MiB / 62.72GiB   0.60%     14MB / 18.3MB     868kB / 63.6GB    20
aab4c92b88c4   swarm-6_bee_1         88.20%    336.8MiB / 62.72GiB   0.52%     4.34MB / 8.15MB   0B / 13.9GB       17
3a6067158a29   swarm-5_bee_1         98.00%    410.9MiB / 62.72GiB   0.64%     17.4MB / 18.5MB   881kB / 64.5GB    20
19e992a57f9e   swarm-4_bee_1         88.77%    374.7MiB / 62.72GiB   0.58%     12.2MB / 23.8MB   635kB / 60.4GB    19
c7d0c924a053   swarm-3_bee_1         93.65%    428.5MiB / 62.72GiB   0.67%     16.8MB / 22.1MB   868kB / 60.7GB    19
ee77e37a0828   swarm-2_bee_1         98.62%    359.4MiB / 62.72GiB   0.56%     14.5MB / 15.2MB   0B / 67.2GB       20
164168835d87   swarm-1_bee_1         86.28%    351.4MiB / 62.72GiB   0.55%     14.3MB / 17.5MB   885kB / 57.9GB    19
31f1320bc3d1   swarm-0_bee_1         88.13%    346.1MiB / 62.72GiB   0.54%     14.2MB / 11.8MB   0B / 55.2GB       20
```

And `iostat` reports 50 - 90 MB/s writes fairly constantly for 16 bees, despite the current total storage (for 0.6.1) only reaching 12 GB.

**Comment by marrrc** [comment]
for what its worth, I had my SSD failing on me just days before 0.6 release, was running 0.59 up until that point, and bee had been running for ~ 3 months before smart check reported imminent wear failure.
