### ISSUE TITLE
Too many logs. 

### ISSUE THREAD

**Issue by DigiDr** [ethersphere/bee#1326]
Please consider reducing the default log level. I'm accumulating hundreds of thousands (and hundreds of MBs) of log files at the moment - the vast majority of which are the context deadline exceeded variety.

**Comment by Eknir** [comment]
`context-deadline-exceeded` logs should be significantly reduced with `v0.5.3`. We would appreciate if you can confirm that this is indeed the case for your bee node. Closing the issue for now.
