### ISSUE TITLE
Could not load rules in bee-clef

### ISSUE THREAD

**Issue by iljooyoon** [ethersphere/bee#1330]
#### Summary
0.4.8 bee-clef has bug, it read rules.js file at / directory.

#### Steps to reproduce
upgrade bee-clef from 0.4.7 (maybe new install same..)
and systemctl restart bee-clef

#### Expected behavior
no error

#### Actual behavior
Could not load rules in bee-clef file=/rules.js err="open /rules.js: no such file or directory"

**Comment by iljooyoon** [comment]
![image](https://user-images.githubusercontent.com/34266807/109022903-9f858d80-76ff-11eb-9bf2-bc1715db8768.png)

**Comment by vandot** [comment]
This is already fixed and released `0.4.9` https://github.com/ethersphere/bee-clef/pull/22
