### ISSUE TITLE
/usr/local/bin/bee file doesn't upgrade

### ISSUE THREAD

**Issue by iljooyoon** [ethersphere/bee#1331]
#### Summary
i use wsl2, because wsl2 has no systemctl, i run by sudo bee start.

but /usr/local/bin/bee file doesn't upgrade so earlier version starts.

#### Steps to reproduce
just upgrade bee from  0.5.0 to 0.5.1 and sudo bee start

#### Expected behavior
version 0.5.1 should be displayed at the top of log.

#### Actual behavior
version 0.5.0 is displayed at the top of log.

**Comment by vandot** [comment]
@iljooyoon how you upgraded bee?

**Comment by iljooyoon** [comment]
> @iljooyoon how you upgraded bee?

i upgrade like below 

[bee-clef]
wget https://github.com/ethersphere/bee-clef/releases/download/v0.4.8/bee-clef_0.4.8_amd64.deb
sudo dpkg -i bee-clef_0.4.8_amd64.deb
[bee]
wget https://github.com/ethersphere/bee/releases/download/v0.5.1/bee_0.5.1_amd64.deb
sudo dpkg -i bee_0.5.1_amd64.deb

**Comment by iljooyoon** [comment]
bee 0.5.2 either.

wget https://github.com/ethersphere/bee/releases/download/v0.5.2/bee_0.5.2_amd64.deb
sudo dpkg -i bee_0.5.2_amd64.deb

**Comment by iljooyoon** [comment]
sudo apt-get remove bee
wget https://github.com/ethersphere/bee/releases/download/v0.5.2/bee_0.5.2_amd64.deb
sudo dpkg -i bee_0.5.2_amd64.deb

it works!!
