### ISSUE TITLE
Uploading empty file as part of a collection fails

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1332]
#### Summary
Uploading to the `/dirs` endpoint a tar collection which contains an empty file fails.

#### Steps to reproduce
Running Bee 0.5.1

```sh
$ touch x
$ tar cf ../test.tar ./x 
$ curl \                    
    -X POST \
    -H "Content-Type: application/x-tar" \
    --data-binary @../test.tar http://localhost:1633/dirs
{"message":"could not store dir","code":500}
```
#### Expected behavior
Empty files should work without problem. This used to work in 0.5.0 so this is a regression in 0.5.1.

**Comment by Eknir** [comment]
Why do you want to upload an empty file?

**Comment by acud** [comment]
This is caused because of my changes to the splitter, which no longer accepts empty data. I'l rectify this somehow tomorrow. 

@agazso what is the desired behavior on retrieval? HTTP 204?

**Comment by agazso** [comment]
> @agazso what is the desired behavior on retrieval? HTTP 204?

I would say 200 with `content-length: 0`
