### ISSUE TITLE
cannot cashout after upgrade. 

### ISSUE THREAD

**Issue by iljooyoon** [ethersphere/bee#1333]
#### Summary
root@Bee3:~# . cashout.sh cashout-all 5
uncashed cheque for b9f11433246b6250d9759b811ea47cb827f38fa484a05478967c189b3ca52f32 (8986000000000 uncashed)
cashing out cheque for b9f11433246b6250d9759b811ea47cb827f38fa484a05478967c189b3ca52f32 in transaction null

i can see bee log below

DEBU[2021-02-25T00:36:38+09:00] debug api: cashout status peer: f74c71b0c5c09aae0bb4e478f249ccf52cbdb3777dcd14748b0ed11c2610d070%!(EXTRA *errors.errorString=no prior cashout)

#### Steps to reproduce
upgrade bee to 0.5.1 and  bee-clef to 0.4.8

if i downgrade bee to 0.5.0 and bee-clef to 0.4.7, cashout succeeds

**Comment by iljooyoon** [comment]
This bug was fixed in bee-clef 0.4.9.

**Comment by ThkerLee** [comment]
bee v0.5.3,bee-clef v0.4.9;
![Uploading image.png…]()
