### ISSUE TITLE
Variable prices

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#134]
## Story
- As a forwarding node, I want that my node chooses economical prices, such that I am making a profit on forwarding and my node is not too expensive, causing it to be avoided by peers.
- As a final consumer of bandwidth, I want that my node chooses decently priced peers to forward my requests to, such that I don't overpay on bandwidth incentives.

## Background
The prices for bandwidth in Swarm is currently hardcoded as an array of constants, that price the chunks which are further away as more expensive. Having hardcoded prices won't work, given expected volatility of the BZZ price. Furthermore, with hardcoded prices, Swarm developers will decide what the price of using Swarm should be and whenever this needs to change, we need to update the sourcecode which then should be simultaneously applied by all nodes. This is obviously not a working solution.
Variable pricing solves both issues, by introducing the possibility for nodes to signal what price they charge for delivering/requesting a chunk that proximity orders away. When we combine this with economical behavior of nodes (send requests to the cheapest nodes, initiate new connections if your current connections are overpriced), then we can create a market, where nodes compete with each other on price.
Economically, the market for bandwidth is close to perfect competition. Hence, we expect that introducing variable pricing will cause a strong downward pressure on prices, eventually benefiting the consumers of bandwidth on Swarm. 

- [Outdated proposal on how to do variable pricing (still contains some relevant stuff)](https://hackmd.io/lM3AWa4kRg-XCFc5aDp9Cg)

## Status
🔨 [communicate price table upon connection](https://github.com/ethersphere/bee/pull/1047)
🔨 [continuously update price table based on information from retrieval and push sync protocols](https://github.com/ethersphere/bee/pull/1134)
✍️ [price-based routing](https://github.com/ethersphere/bee/issues/1272)
✍️ [guarantee profit for each request](https://app.zenhub.com/workspace/o/ethersphere/bee/issues/1273)

**Comment by Eknir** [comment]
@juli, please keep an eye on this

**Comment by acud** [comment]
In its current form this issue is deprioritised from the current working backlog due to increased complexity.
@metacertain is working on a simplified version of this with differential pricing as per proximity order hops, but user customisable pricing remains a moving target.
