### ISSUE TITLE
time.Since() gives bogus units

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1343]
#### Summary
I was monitoring the --verbosity 5 logs for the kademlia iterator and noticed some that have a non-printable (on Windows at least) time unit.  I understand ms and s, but "242.9┬╡s" is mighty strange.

time="2021-02-25T00:26:56-05:00" level=trace msg="kademlia iterator took 1.0014ms to finish"
time="2021-02-25T00:26:57-05:00" level=trace msg="kademlia iterator took 7.0847ms to finish"
time="2021-02-25T00:26:57-05:00" level=trace msg="kademlia iterator took 242.9┬╡s to finish"
time="2021-02-25T00:26:57-05:00" level=trace msg="kademlia iterator took 736.6┬╡s to finish"
time="2021-02-25T00:26:58-05:00" level=trace msg="kademlia iterator took 0s to finish"
time="2021-02-25T00:26:58-05:00" level=trace msg="kademlia iterator took 1.945ms to finish"
time="2021-02-25T00:26:58-05:00" level=trace msg="kademlia iterator took 1.002ms to finish"
time="2021-02-25T00:26:59-05:00" level=trace msg="kademlia iterator took 998.8┬╡s to finish"
time="2021-02-25T00:26:59-05:00" level=trace msg="kademlia iterator took 913┬╡s to finish"
time="2021-02-25T00:27:00-05:00" level=trace msg="kademlia iterator took 1.0011ms to finish"
time="2021-02-25T00:27:00-05:00" level=trace msg="kademlia iterator took 997.3┬╡s to finish"
time="2021-02-25T00:27:03-05:00" level=trace msg="kademlia iterator took 2.351029s to finish"
time="2021-02-25T00:27:03-05:00" level=trace msg="kademlia iterator took 3.1108ms to finish"
time="2021-02-25T00:27:03-05:00" level=trace msg="kademlia iterator took 3.9974ms to finish"

I tracked the source of this log down to pkt/kademlia/kademlia.go which is how I know it must be coming out of time.Since().  I was unable to locate the source to time.Since() however.

k.logger.Tracef("kademlia iterator took %s to finish", time.Since(start))

I wonder if time actually jumped backwards a bit (it does that on Windows in my experience) resulting in a negative delta to be displayed?  But I would have hoped that a utility routine like Since() would handle such a thing gracefully, hopefully by just displaying a negative number?

#### Steps to reproduce
Just watch and wait and filter the --verbosity 5 output logs for this particular message.

#### Expected behavior
I would expect interval time values to have readable units.

#### Actual behavior
"736.6┬╡s" isn't a readable numeric value.

**Comment by acud** [comment]
This looks like a problem with your terminal font. `time.Since()` gives results in `m`, `s`, `ms`, `ns`, and `μs`

**Comment by Eknir** [comment]
Closing this issue, as it is most likely not a problem of Bee. Thanks for reporting anyways!

**Comment by ldeffenb** [comment]
I finally found the source to time.Since() and confirmed that it does indeed put a unicode character for micro-seconds:
		case u < uint64(Millisecond):
			// print microseconds
			prec = 3
			// U+00B5 'µ' micro sign == 0xC2 0xB5
			w-- // Need room for two bytes.
			copy(buf[w:], "µ")
