### ISSUE TITLE
kademlia connect loop executes too frequently

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1344]
#### Summary
I was watching my node's --verbosity 5 logs and noticed that sometimes a burst of "kademlia iterator" logs would fly by.  Capturing those logs and examining the source code for those logs resulted in the following observations.

Note: Possible cause of and solution to the issue are at the end.

#### Steps to reproduce
My node was just starting up and taking a (relatively) long time to get connected to peers.  This resulted in the following logs from kademlia:

time="2021-02-25T00:18:30-05:00" level=trace msg="kademlia iterator took 6m36.3270304s to finish"
time="2021-02-25T00:25:06-05:00" level=trace msg="kademlia iterator took 6m35.6968729s to finish"
time="2021-02-25T00:26:52-05:00" level=trace msg="kademlia iterator took 1m45.687002s to finish"
time="2021-02-25T00:26:52-05:00" level=trace msg="kademlia iterator took 11.9986ms to finish"
time="2021-02-25T00:26:52-05:00" level=trace msg="kademlia iterator took 1.0009ms to finish"
time="2021-02-25T00:26:53-05:00" level=trace msg="kademlia iterator took 920.8┬╡s to finish"
time="2021-02-25T00:26:53-05:00" level=trace msg="kademlia iterator took 1.0011ms to finish"
time="2021-02-25T00:26:53-05:00" level=trace msg="kademlia iterator took 0s to finish"
time="2021-02-25T00:26:54-05:00" level=trace msg="kademlia iterator took 0s to finish"
time="2021-02-25T00:26:54-05:00" level=trace msg="kademlia iterator took 0s to finish"
time="2021-02-25T00:26:54-05:00" level=trace msg="kademlia iterator took 0s to finish"

Note the timestamps at the end, it was running the loop multiple times within the same second.  I checked the source code, and it appears that it should have waited 30 seconds between loop executions.

#### Expected behavior
I certainly wouldn't expect multiple quick executions of code in a short span of time.

#### Actual behavior
9 logs in the space of 3 seconds seems a bit extreme to me.

In pkg/kademlia/kademlia.go, the manage() method is the source of this particular log.  Examining the control flow of this method reveals the possible cause of this discrepancy.

func (k *Kad) manage() {
<snip>
	for {
		select {
		case <-k.quit:
			return
		case <-time.After(30 * time.Second):
			// periodically try to connect to new peers
			select {
			case k.manageC <- struct{}{}:
			default:
			}
		case <-k.manageC:
			start = time.Now()
<snip>
			k.logger.Tracef("kademlia iterator took %s to finish", time.Since(start))
<snip>
		}
	}
}

My novice-go reading of this code appears that the timer should be triggering the manageC every 30 seconds.  But what happens if the manageC takes longer than 30 seconds to execute as in the first 3 logs above (6m36.3270304s 6m35.6968729s 1m45.687002s)?  Does the timer actually queue up a bunch of manageC notifications that subsequently get worked off as fast as possible?

Would a possible fix be to keep track of whether or not manageC is executing and modify the time.After() case to only pass the empty struct to manageC if it is not already running when the timer fires?

I'm not a good enough go programmer to actually implement this reliably, but it seems like a good first PR for someone that is actually conversant in go-lang.

**Comment by acud** [comment]
The channel could be triggered also due to peer connect and disconnects (see `Connected()` and `Disconnected()` on the same file)

**Comment by Eknir** [comment]
Ha :) great to see that you are inspecting our source code ;). I close this issue, as I don't see a problem here. Thanks for reporting and I hope you learned something!
