### ISSUE TITLE
return ErrWantSelf in pushsync

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1349]
I would be glad if this could be analyzed and judged on severity. If it is a likely explainer of some problems which we are seeing, then it would be good to dive deeper into this and fix.

if we cannot find a node closer, then we were actually the closest, so we return 
https://github.com/ethersphere/bee/blob/master/pkg/kademlia/kademlia.go#L583
with ErrWantSelf = meaning we are the closest node.

Now, when nemanja  introduced retries in pushsync, we go as follows, we find the closest peer
if sending or receiving produces an error, we ask for another peer. in order to skip the one we tried
we introduce a peers to skip map. 
imagine we are experiencing problems pushing downstream, all pees  closer errored, then we return with 
ErrWantSelf,
https://github.com/ethersphere/bee/blob/master/pkg/pushsync/pushsync.go#L200
which means we are the closest peer, or are we?
https://github.com/ethersphere/bee/blob/master/pkg/pushsync/pushsync.go#L204

we are  the  closest peer that has not errored, but as a result we behave as if a  closest peer
and store the chunk in localstore
https://github.com/ethersphere/bee/blob/master/pkg/pushsync/pushsync.go#L127
and  even respond with a receipt to thee originator
This means the chunk may not  be retrievable until pullsyncing eventually synchronises it.
the overall consequence is if push chunks is not possible to peers closer than our node, our node will  start to absorb the chunks    although the chunks might not even be  within  our depth.

Currently our low watermark is 1  which means that some nodes may have a single connection in a bin  outside their  neighbourhood.
Knowing this one can easily force a node to behave as a storer node with all those chunks that are not in their neighbourhood. all you need is to push all those chunks to them with push-sync.

If there is db write delay causing the push-sync errors, then  this will be even worse.
If the node is a gateway node, then continuous upload to them makes the issue much easier to achieve.

Mitigation: 

- correct the bug and return peer not found error from kademlia
- push sync spread, symmetric neighbourhoods, and raising low watermark as well as balanced kademlia all help
- maybe monitor the uniformity of chunk traffic arriving from nodes. Those with skewed requests can become throttled or disconnected.

**Comment by acud** [comment]
> Currently our low watermark is 1 

this is incorrect

**Comment by Eknir** [comment]
> > Currently our low watermark is 1
> 
> this is incorrect

I copied this from a note from @zelig .
