### ISSUE TITLE
Storage incentivization

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#135]
## Description
Providing nodes a way to earn money on storing chunks, even when they are not accessed.

## Resources
- Postage lottery (see BOS)
- [RACE](https://swarmresear.ch/t/race-positive-incentivization-of-chunk-storage/48/2)
- REAR (not yet published)

**Comment by acud** [comment]
link to write-up by viktor https://hackmd.io/2XLZhMUfTbuhWU5pTHR6gg?view

**Comment by acud** [comment]
we can probably get rid of this issue. too general @Eknir

**Comment by Eknir** [comment]
Agreed.
