### ISSUE TITLE
Database lock 

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1350]
I would be glad if this could be analyzed and judged on severity. If it is a likely explainer of some problems which we are seeing, then it would be good to dive deeper into this and fix.

If for whatever reason the db writes get delayed and pile up, the  garbage collection has less and  less  chance to run. 
Since db writes due to upload  or push sync or pullsync compete for the db write lock.
If  the GC process  is unlucky not  getting  the  mutex in the beginning, after thousands and thousands of writes pile up, as a  single go routine  it has virtually  no chance  leading to a non-GC-ed localstore, leading to full hard disk.

mitigation:

- (instead of regular sync.Mutex-es) use priority locking for GC or
- continuous GC by spawning GC removals of chunks in separate go routines
- each write also deletes a few chunks if capacity is reached 
- rate limiting concurrent db write routines 
- backward pressure of parent calling db writes
- write queue and workers

**Comment by ldeffenb** [comment]
I don't know if this is related, but I had a bee node going crazy with CPU consumption this morning and when I terminated it with ^C, it generated a dump with lots of goroutines waiting in sync.runtime_SemacquireMutex and most of those coming from ithub.com/ethersphere/bee/pkg/localstore.(*DB).put.  My disk was not 100% at the time nor anytime  recently so I'm not sure how so many goroutines got to be waiting on this mutex.

https://gateway.ethswarm.org/files/d1d1680b5807f735f832293fdd9a1f8c744337ac0513c69d5f00a16286ffa55d

That capture is all that was available in my ssh scrollback buffer after the dump.

**Comment by zelig** [comment]
thank  you @ldeffenb very useful

**Comment by acud** [comment]
should be improved with #1435

**Comment by Eknir** [comment]
@acud , shall we connect this issue with your PR? Even if it is not completely what asked, I think it makes sense to do
