### ISSUE TITLE
Take less resources while historical syncing

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1353]
# User story

## Story

As a user of Swarm, I want that my node does not take all the resources (bandwidth and processing power) while my node is doing historical sync'ing, such that my other nodes (eth2 validaters) continue running correctly and I can use my PC for something else

## Background

- Running Swarm right now makes your PC unusable for some time.
- There have been actual user complaints, that Swarm is taking so much resources that the eth2 validators miss attestations

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by ldeffenb** [comment]
I noticed that in puller.go's syncPeerBin, two go routines are spawned in parallel, one for histSyncWorker and the other for liveSyncWorker.  That's bad, but what's worse is that syncPeerBin is just for a single bin.  It is invoked in a loop causing LOTS of go routines to immediately starting working on the local client, and further, to be pushing bunches of stuff into the remote peer that is being synced with.

Is there any particular reason a single peer's syncing can't be done sequentially across bins and between history and live syncing?

**Comment by Eknir** [comment]
This relates to #1243 and #1504

**Comment by acud** [comment]
relates to #2686
