### ISSUE TITLE
Ensure that tags work on the gateway

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1369]
# User story

## Story

As a user of a Swarm gateway, I want to know the status of my upload, such that I know whether my upload succeeded

## Acceptance criteria

- Tags enabled in gateway mode
- Old tags are intelligently flushed

## Background

Tags are disabled in the gateway mode since old tags are not flushed and hence there might eventually be too many tags, rendering the gateway unusable. The completion of this issue is to solve this underlying issue, such that tags can be exposed in the gateway mode.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
Related: #1530

**Comment by acud** [comment]
if we enable tags on gateway mode, they might conflict and someone would have to periodically flush and clean them. also, with postage stamps in place i'm not sure how relevant is this anymore

**Comment by AuHau** [comment]
I just now discovered that with every upload you automatically creates a tag and return it in the response header. Is this behaviour also present in Gateway mode? (I did not manage to test it) If so, maybe we don't need to have the ability to create tags, but only to query their status in the Gateway mode...

**Comment by acud** [comment]
The bug that @AuHau mentioned is already fixed. The tags could be accessed through the gateway with the restricted APIs. Closing :+1:
