### ISSUE TITLE
Accounting

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#137]
## Story
As a node operator, I want to keep track of the relative value of bandwidth consumed and provided with every peer I such that I know when to issue a payment or disconnect when I don't receive a payment.

## Background
[conclusions from SWAP](https://hackmd.io/afN3oTZsTjqT3niGwB8GlQ)

**Comment by Eknir** [comment]
@juli, please keep an eye on this

**Comment by acud** [comment]
this is done
