### ISSUE TITLE
Kademlia's AddPeers unnecessarily wakes manageC

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1380]
While researching how connections are managed in bee and the excessive CPU consumption in 0.5.2, I uncovered an inefficiency in kademlia's AddPeers:

https://github.com/ethersphere/bee/blob/9a88523453bf33aab3a8741fce6fe778dcf5c098/pkg/kademlia/kademlia.go#L436

This routine loops through a range of peer addresses and adds any that were not previously know to the appropriate knownPeers bin.  The inefficiency is that it ALWAYS wakes k.manageC even if all of the added peers were already known.  There is no need to attempt new connections unless at least one of the peers was actually new.

**Comment by ldeffenb** [comment]
Unfortunately, my CPU consumption has not reduced by the conditional removal of the unnecessary wake events, but every drop of saved CPU counts.

**Comment by acud** [comment]
This is an optimization and I in all honesty I think that it would be beneficial on optimize only if we are iterating over millions of peers every time. Right now this is an non-issue
