### ISSUE TITLE
Debug api is executed for too long

### ISSUE THREAD

**Issue by littlekfc** [ethersphere/bee#1387]
#### Summary

I have operated and maintained dozens of bee nodes at the same time. Their machine configuration and environment are all the same. When my batch script executes cashout, I found that some nodes take a lot of time to call the debug api or even get stuck. At the same time, some nodes have serious memory leaks. I don't know if this is related.

Environment: ubuntu 20.04;
Bee version: 0.5.2;
Bee config: as default;

What can I do to help you locate the issue?

**Comment by ralph-pichler** [comment]
Do you know which call specifically got stuck? The cashout script calls multiple endpoints.

**Comment by Eknir** [comment]
`Bee v0.5.2` had problems with resource consumption. While there are still existing problems, `bee v0.5.3` is already running much smoother. It would be useful if you could update your nodes to the newest version and let us know if your problem still persists.

If the problem still persists, please report here. Analyzing your problem will then most likely help us to locate issues in our code.

You can reach me on the [Swarm Discord](https://discord.gg/KC8MbQhEeh)

**Comment by Eknir** [comment]
Stale issue, closing.
