### ISSUE TITLE
Node cannot start if blockchain is "stuck"

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1395]
#### Summary
The goerli blockchain is having deadlocks caused by an internal tie in their validation logic.  When the blockchain is not moving, a bee node cannot start, even though its swap-endpoint IS actually sync'd to the fully validated chain.  The bee node sits with the following as the last log message (--verbosity 5):

time="2021-03-06T06:55:30-05:00" level=info msg="waiting to sync with the Ethereum backend"

#### Steps to reproduce
Try to start a bee node when the goerli network is stalled.

#### Expected behavior
The swap-endpoint goerli provider IS synchronized with the blockchain it's just that bee doesn't see the block number moving.  Bee node should be allowed to start, especially if a checkbook contract is already fully deployed on the blockchain.

Besides, nodes that were already running when the chain stalls can continue to operate normally except that cashout transactions go into the queue and stay there until the chain starts moving again.  Why shouldn't a funded and previously running node be allowed to start if existing nodes can continue to run?

#### Actual behavior
The bee node sits on the following message until the blockchain starts moving again.

time="2021-03-06T06:55:30-05:00" level=info msg="waiting to sync with the Ethereum backend"

**Comment by Eknir** [comment]
@rpicc , can you provide some details here?

**Comment by acud** [comment]
I agree. This is a non-issue from my perspective. Trying to detect whether the blockchain is broken is out of scope for this project

**Comment by jmozah** [comment]
I think the issue of global state is present in this case too. How can we
know of the chain is stalled for the running node only or for the entire
network. We should either stop the running node and not allow starting any
new nodes OR allow both to run. Not allow in one case and not allow in
another.

**Comment by Eknir** [comment]
Closing this issue, as it is not a high priority. A smoothly running Ethereum is required to run `bee`. It is expected behavior that the `bee` node doesn't run as expected, when Ethereum doesn't function.
