### ISSUE TITLE
https://goerli-faucet.slock.it/?An error is reported after the address is entered, and 0.05 go eth cannot be collected

### ISSUE THREAD

**Issue by adonis1128** [ethersphere/bee#1396]
#### Actual behavior

An error is reported after the address is entered, and 0.05 go eth cannot be collected。why？

**Comment by Eknir** [comment]
This bug report does not contain the needed information to resolve. Please join our Discord; you will probably find an answer to your question there. https://discord.gg/vmZsKx9n
