### ISSUE TITLE
https://goerli-faucet.slock.it/?An error is reported after the address is entered, and 0.05 go eth cannot be collected

### ISSUE THREAD

**Issue by adonis1128** [ethersphere/bee#1397]
![eefe5710f71b82d39c83dcad3e294c2](https://user-images.githubusercontent.com/80170497/110228060-10674980-7f39-11eb-9a95-f45ec870d9dd.png)

**Comment by Eknir** [comment]
This faucet is not maintained by the Swarm team. Please join our discord for questions  https://discord.gg/vmZsKx9n . The Goerli network experienced problems over the weekend. I suspect that this is the problem.
