### ISSUE TITLE
localstore's mode_set.go uses wrong metrics

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1409]
#### Summary
While learning how to use the metrics and browsing the source code, I noticed that localstore's mode_set.go references the Put metrics even though Set metrics are decleared.

#### Steps to reproduce
Just compare the mode_put.go and mode_set.go and you'll see the error.

#### Expected behavior
mode_set should be using the set metrics, not the put metrics.

#### Actual behavior
mode_set actually increments the put metrics.

I'll be tying this to (my first) PR with the correction to the single source file.

**Comment by Eknir** [comment]
Thanks for reporting (and fixing!)
