### ISSUE TITLE
localstore's gc_size metric is wrong

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1411]
#### Summary
Learning more about and looking at the various metrics, I discovered that the gc_size metric matches the gc_count metric.  Checking the source code revealed that they are both incrementing at the same time.  I believe that gc_size should be SET to the current gcSize and not incremented.

#### Steps to reproduce
Just look at the /metrics page and see that bee_localstore_gc_size has the same value as bee_localstore_gc_count which makes no sense.

#### Expected behavior
The two metrics should at least have different values, and gc_count is described as "Number of times the GC operation is done." whereas gc_size is "Number of elements in Garbage collection index."

#### Actual behavior
The two values are the same.

I have fixed localstore's gc.go to set the gc_size metric when it is looked up in the garbage collector, after the garbage collector runs and when it is updated later in that file.

**Comment by acud** [comment]
fixed in https://github.com/ethersphere/bee/pull/1417
