### ISSUE TITLE
No cashout is created.

### ISSUE THREAD

**Issue by iljooyoon** [ethersphere/bee#1413]
#### Summary
Cashout has not been generated since last week when the network had a problem.

![image](https://user-images.githubusercontent.com/34266807/110619356-0f554700-81db-11eb-8ab0-f95f52d088cb.png)

6 March, cashout has failed with null error. from then on i cannot cashout any more.

there are only 2 peers always, but i can see the log 'successfully connected to peer <peer-id>'. 
(but when i call /peers, the peer-id what i saw in the log is not exist.)

i can see the log 'could not send payment threshold announcement to peer <peer-id>'. 

![image](https://user-images.githubusercontent.com/34266807/110619216-e03ed580-81da-11eb-8d99-05690861ac0c.png)

should i backup the wallet and create new node? or Is there any way to solve the problem?

**Comment by Eknir** [comment]
Please have a look at our trouble shoot guide for cashout problems: https://hackmd.io/95rvXRswSh-xm9Td_Xl2cg?view

If the issue persists, my advice would be to make a backup of your private key and start a new node.
