### ISSUE TITLE
can't cashout because of EIP-155

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#1415]
#### Summary
TXNs never get mined. [Somebody diagnosed this](https://discord.com/channels/799027393297514537/810905662375854123/818986298345652255) as a lack of [eip-155](https://eips.ethereum.org/EIPS/eip-155) support.

#### Steps to reproduce
Run bee until you have some cheques to cash. Try to cash them against geth 1.10

#### Expected behavior
TXN should be mined

#### Actual behavior
Nothing happens.

**Comment by playaz** [comment]
Same issues here.

**Comment by Eknir** [comment]
@rpicc - can you comment here please?

**Comment by ralph-pichler** [comment]
this was fixed a while ago and will be in the upcoming release

**Comment by ralph-pichler** [comment]
actually this was already in the last release. are you sure this happened on bee 0.5.2?

**Comment by jpritikin** [comment]
Not sure. Maybe the txns are failing for a different reason.

**Comment by Eknir** [comment]
We have a trouble shoot guide: https://hackmd.io/95rvXRswSh-xm9Td_Xl2cg?view

Closing this issue, please reopen if the issue persists and it cannot solved with the trouble-shoot guide.
