### ISSUE TITLE
The Link to the Book of Swarm is Broken

### ISSUE THREAD

**Issue by elif42** [ethersphere/bee#1419]
One receives a 404 error when you click on the [link](https://swarm-gateways.net/bzz:/latest.bookofswarm.eth/the-book-of-swarm.pdf)

**Comment by ldeffenb** [comment]
Try this one: https://gateway.ethswarm.org/bzz/latest.bookofswarm.eth/

**Comment by Eknir** [comment]
This is the old gateway. Where did you get that url? We will replace it.

**Comment by elif42** [comment]
@Eknir [Here]( https://link.medium.com/6MrLm3mOyeb)
