### ISSUE TITLE
Original uploader pusher sync improvement

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1423]
#### Summary
I've been working to understand how uploads get distributed into the swarm and make their way to their "close" neighborhood.  This has had me watching the --verbosity 5 logs from pusher and pushsync and all of their "context deadline exceeded" and, from casual observation, redundancy in pushing the same chunk over and over again causing my upload tags to take a long time to be completed.

And then diving into the source code to understand the flow and seeing the (short at 3 seconds) timeToWaitForReceipt being applied to both my original pusher invocations of pushToClosest (via PushChunkToClosest) and the pushsync handler's invocation of pushToClosest.

This short timeout seems to be the cause of the many many "context deadline exceeded" (and maybe "stream reset") messages while attempting to read (or send, in the case of the handler) receipts.

What I see happening is that my uploading client pusher invokes PushChunkToClosest which invokes pushToClosest which goes into a loop to try 5 peers.  When it sends to the first closest peer, it uses a 3 second timeout on receiving the receipt.  Remember, 3 seconds.

That push request arrives in the pushsync handler of that first-closest peer.  That handler directly invokes pushToClosest which selects the closest peer and sends the push on to that peer, again using the same 3 second timeout.  Let's say that peer is a bit slow to respond and it times out.  So the handler's invocation goes on to the next closest peer and starts a new 3 second timeout.  But for the purposes of my original pusher, that doesn't matter, because it has already timed out!

And my original pusher chooses the next closest peer and starts the whole chain running again.  If the second closest peer has a slow closest peer, boom, I time out again.  And yes, I've seen it happen all 5 times at which point the pusher gets an error back, skips that attempt and will try it again after running through the whole list.  If the swarm's connectivity and response hasn't changed, I'll keep shoveling that chunk into 5 of my peers, and each of those 5 will push to 5 more and down the chain, multiplying and multiplying with each of my retries.

And it appears that this is all because I didn't give my original "closest" peer (or even my second or third or fourth or fifth) enough time to get a receipt back to me on their second closest peer attempt.

So, what I'm proposing is to have pusher-initiated PushChunkToClosest pass a longer timeout into pushToClosest and have the handler use the current 3 second timeout on pass-through invocations.

In my experiments here, simply using a 16 second timeout will give each of my 5 closest peers a chance to get a good reply from at least one of their three closest peers.  Yes, my pusher may slow down a bit, but it will only have to attempt to push each chunk ONCE given that it will try 5 closest peers and give each of those peers enough time to try three each.

I did initially try 30 seconds, but most receipts were received in <15 seconds and most that took longer than that exceeded the 30.  And the pusher runs up to 20 of these chunks in parallel, so slowing down one or two that are trying to get into a slow neighborhood should not significantly stall the whole pusher queue.

With this setup (16 seconds), I've only seen ONE pushed chunk make it through all 5 of my closest peers without getting a successful receipt.  And that was shortly after my node started and long before it had fully connected into the swarm.

#### Steps to reproduce
Upload a file and watch the pusher and pushsync trace logs.  Way too many to go into here.

#### Expected behavior
I expected the pusher trying 5 different peers to at least successfully deliver the chunk to one of them on the first pass.

#### Actual behavior
Instead, due to the re-used timeout, it was not getting a receipt back, even if one of those peers succeeded to a second or third closest peer.

I can put together a clean PR of pushsync.go if this is desired.  Right now I can't push mine because it's full of my logging cruft.

Basically it adds a new timeout constant at the top:

var (
	timeToWaitForReceipt = 3 * time.Second // time to wait to get a receipt for a chunk I'm handling
	timeToWaitForFirstReceipt = 16 * time.Second // time to wait to get a receipt for a chunk I'm initiating
)

The handler uses the first constant in it's invocation of pushToClosest:
		receipt, err := ps.pushToClosest(ctx, chunk, timeToWaitForReceipt)

PushChunkToClosest uses the new constant:
	r, err := ps.pushToClosest(ctx, ch, timeToWaitForFirstReceipt)

pushToClosest expects a new time.Duration for the timeout (tmo):
func (ps *PushSync) pushToClosest(ctx context.Context, ch swarm.Chunk, tmo time.Duration) (rr *pb.Receipt, reterr error) {

And the two original references to timeToWaitForReceipt are changed to tmo:
		ctx, cancel := context.WithTimeout(ctx, tmo)
		cctx, cancel := context.WithTimeout(ctx, tmo)

**Comment by ldeffenb** [comment]
I do believe that this simple change to the pusher behavior (even though it is in pushsync and not pusher), when rolled into the original data source nodes of the swarm, will dramatically reduce the redundant traffic and "context deadline exceeded" messages that everyone is seeing from all the redundant retries.

I really wish I could figure out a way to have a reducing retry as an original push goes through multiple handlers, but that would be a pushsync protocol change which I'm not about to suggest!  (yet)

**Comment by Eknir** [comment]
Thank you for the thorough analysis! We will look into your suggestions when debugging push sync behavior.

**Comment by Eknir** [comment]
If you are up for some coding to resolve this situation, I would be glad to pair you with somebody from our team to assist you here.

One thing which I would like to suggest is not to define two timeouts (initiator + forwarder), but to actually define the timeout depending on the distance between you and the chunk (proxy for expected hops), irrespective of whether you were an originator or not. This was spoken about before: https://github.com/ethersphere/bee/issues/1044

**Comment by ldeffenb** [comment]
@Eknir Let me give some thought on a timeout calculation based on distance (possibly leading bit match/bin distance rather than actual distance) and maybe play with it a bit in my modified node.

**Comment by acud** [comment]
Closing this as this is going stale. We refactored the protocol at least twice since. Some improvements should already be visible but this is a moving target. We are also looking into various further approaches to improve the protocol design as the problem space is quite large
