### ISSUE TITLE
zero gBZZ cashouts

### ISSUE THREAD

**Issue by JRCry** [ethersphere/bee#1429]
zero gBZZ cashouts

Im having this issue with many of my cashoits, BTW I can only do manually.

Device  Mac OS 10.15.7
16GB ram , Dual intel core I7 2,9 Ghz

INFO[2021-03-12T13:15:35+01:00] version: 0.5.2-4a598b6    

{"chequebookaddress":"0xCF5347cFe1670Dab190a32598d08c141d4FF871E"}

swarm network address: 5b60d1e20ec83afdf3152d9499382d1a097ba9e992c970c48647548941f3bc80 
ethereum address 7238145e23f7820f5815955435f61f55fc9edc20 

mbp@MBP-de-MBP ~ % curl -XPOST http://localhost:1635/chequebook/cashout/5f9b46da8d52daa618b992f9056dde330343db910e24e9bb0a9a9d5a3e0d65bf
{"transactionHash":"0x172e4c7de06150a636482d8382a3ab8bb4c6acb03336fe8f186cca92f27e40d1"}

mbp@MBP-de-MBP ~ % curl -XPOST http://localhost:1635/chequebook/cashout/3030f4aabccbfe38319e0716608f07ba2a19ab736c0f728fc71b649972f9cd4d
{"transactionHash":"0x360ac496300a13b414328985f0b60b88cea2c8eac255aec31b31784e7da02260"}

mbp@MBP-de-MBP ~ % curl -XPOST http://localhost:1635/chequebook/cashout/5b62179d812534adf83be23474e86291f24668dc4a98ed171579314c116ca126
{"transactionHash":"0xb5c9bf712b354943056bd1272b76c523b9ee57e89ca2387286b3e47541108e43"}

{"peer":"5b62179d812534adf83be23474e86291f24668dc4a98ed171579314c116ca126","received":8633000000000,"sent":0},{"peer":"5b6e26385ed33f59459a7f961b184706c399ad4698dbefed94a359ae2df88356","received":0,"sent":2192000000000},{"peer":"5b67f7412ec86915d340d2ce1cb14c2cb9797943327b2fca4cc6bc7b02b3367e","received":0,"sent":3737000000000},{"peer":"5f9b46da8d52daa618b992f9056dde330343db910e24e9bb0a9a9d5a3e0d65bf","received":763000000000,"sent":0},{"peer":"5b5e6aa422a1ffb9ca09e7d0bcdcf88aac80f1061e0dc08ff1884e684ef69cad","received":0,"sent":1442000000000},{"peer":"5aa76873a55633f6ce39af19e68e3d0fece57b11a94033f1e92a1c87593b45af","received":0,"sent":8949000000000},{"peer":"3030f4aabccbfe38319e0716608f07ba2a19ab736c0f728fc71b649972f9cd4d","received":17938000000000,"sent":0}]}

{"chequebookaddress":"0xCF5347cFe1670Dab190a32598d08c141d4FF871E"}

￼
![Captura de pantalla 2021-03-13 a las 20 17 09](https://user-images.githubusercontent.com/80598897/111051461-7c731180-8453-11eb-83c0-0d86909892bd.png)

thx 

J

**Comment by ralph-pichler** [comment]
see https://github.com/ethersphere/bee/issues/1436#issuecomment-802669617

**Comment by Eknir** [comment]
Fixed per https://github.com/ethersphere/bee/pull/1402 (see https://github.com/ethersphere/bee/issues/1436#issuecomment-802669617)
