### ISSUE TITLE
Immutable references

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1433]
**Rationale**

By default the data stored on Swarm is immutable, however when using the `/bzz` endpoint it's not possible to tell in advance what data is going to be returned (even if you use the same reference twice), because that endpoint also does name resolution and feed lookup and may return different data based on updates.

It would be good to have an immutable endpoint that would simply return the content based on the address. With that it would be possible to utilize the immutability of Swarm in application for integrity checking, auditing authenticity, creating DAGs etc. Another advantage then that the data coming from this endpoint could be potentially cached for an unlimited time, because of its immutable nature.

For example IPFS has two different schemas for downloading data, `ipfs` for immutable references and `ipns` for mutable ones. Bee also has `/files` endpoint that does no name resolution and feed lookup so that could be a possible alternative for immutable data. 

However we imagine using these as URL schemas in the future. So for exmaple instead of `http://localhost:1633/bzz/<hash>/` it would be possible to use `bzz://<hash>/` in the future. Similarly the `/files` endpoint would yield `files://<hash>/` but that's too close to the existing `file://` schema, so it would be better to find a name that better differentiates (maybe `bzzi://` ?)

**Comment by Eknir** [comment]
@zelig , I think this is an important point. Could you please shed your light on it and define what we should do here?

**Comment by agazso** [comment]
Also related: https://github.com/ethersphere/bee/issues/1444

**Comment by Eknir** [comment]
Thinking about this. Don't you think it would be better to pass a header-param where the user explicitly tells to resolve the content. With that, it would be possible for the user to just browse the `bzz` (immutable), and for the front-end to tell the user something along the lines of: "This address references a mutable resource, for which the authenticity is provided by <address here>, do you want to continue?"

**Comment by agazso** [comment]
I am not sure I understand how that would work. For example one use case of Swarm is to be able to host websites and applications. The way of sharing them is through links. How do you imagine using headers would look like in that use-case?
