### ISSUE TITLE
Too many calls to blockchain

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#1434]
#### Summary
it looks like bee is doing too many calls to blockchain.
My 25 Million api calls is over within a week.
And infura's daily limit of 100K is becoming peanut for my cluster.
![image](https://user-images.githubusercontent.com/940575/111154246-05578d80-85b9-11eb-9d9f-03d9ed37e170.png)

#### Steps to reproduce
let it run for few days. Then do a cashout once every day.

**Comment by Eknir** [comment]
What version are you running?

**Comment by jmozah** [comment]
@Eknir bee 0.5.2 on Ubuntu 20.04. Roughly 20 of my nodes use this particular infura endpoint.

**Comment by jmozah** [comment]
Below is the usage of compute units of two alchemy accounts that i use. Both have 50M compute units capacity (roughly 2M eth_calls). They got exhausted in few days, just like that.

<img width="485" alt="Screenshot 2021-03-16 at 3 04 28 PM" src="https://user-images.githubusercontent.com/940575/111287982-c33a5480-8669-11eb-836c-b81d7dd8abca.png">
<img width="762" alt="Screenshot 2021-03-16 at 3 08 44 PM" src="https://user-images.githubusercontent.com/940575/111288002-c9c8cc00-8669-11eb-9916-47062068b8d3.png">

**Comment by ralph-pichler** [comment]
Hm, I think the traffic might just be the result of a lot of cheque traffic. The node needs to verify balances every time it sends or receives cheque. For now I will add some metrics so we can actually track how many cheques a node sends or receives so we can confirm if this is the reason.

**Comment by ralph-pichler** [comment]
how many nodes are in your cluster?
