### ISSUE TITLE
Internal network configuration leaking

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee#1439]
# Leaking Network Configuration

When `bee` establishes connections, it leaks internal networking configuration (IP address, port) that some cases, may not be needed. It's been observed on `bee` node logs that other bee nodes are advertising private IP addresses that are non-routable, causing network overhead, as well as leaking potentially private information / network configuration.

# Suggested Fix

It's suggested that logic be applied to the underlay addresses _exported_ such that:

1. Blacklist all [private CIDRs](https://en.wikipedia.org/wiki/IPv4#Special-use_addresses) by default.
2. Send private CIDRs only to whitelisted nodes (such as bootstrap nodes?). This would assist in the event of running multiple nodes on a Kubernetes cluster, allowing them to communicate amongst one another without the need for NAT reflection firewall rules.

**Comment by Eknir** [comment]
cc @vandot

**Comment by DigiDr** [comment]
+1 for this. I've had a cloud provider disconnect a box for persistent attempts to connect to private ip ranges. In my case, docker makes this challenging to resolve with iptables.

**Comment by janos** [comment]
I would suggest to have a configuration option to enable advertisement of private CIDRs (current behaviour) and by default not to advertise them. There are cases where a private swarm network is created and they operate only in the private CIDRs, such are testing environments and organisations' private networks.

**Comment by Skjold** [comment]
+1 more for this.
I've temporarily solved the issue by applying the settings from https://github.com/chaifeng/ufw-docker and then doing:
`curl --retry 20 --retry-delay 1 -o bogons https://www.team-cymru.org/Services/Bogons/bogon-bn-agg.txt
while read -r bogon; do
    ufw route deny from any to "$bogon";
done < bogons
rm bogons`
It does work to cut all Docker traffic to bogon addresses, you just need to insert your own `ufw route allow` rules before these ones to explicitly allow outgoing connections to any RFC1918 networks you actually use.
It would be nice to also log a warning for users to set the nat-address in bee.yaml or as an environment variable if Bee is advertising a bogon IP.

**Comment by mrekucci** [comment]
Fixed in #2538

**Comment by mrekucci** [comment]
Fixed in #2538
