### ISSUE TITLE
Postage stamps

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1440]
# Epic

## Story

- As a node operator, I want to be able to distinguish chunks which are of high-value to uploaders from those which are of low-value to uploaders, such that I can decide what content to throw away if my storage space if full and benefit the Swarm network optimally with my storage space. 
- As an uploader of data, I want to signal to node operators that the data which I upload is valuable to me, such that they will preserve my content over less-valued content and my content will stay available longer

## Background

Swarm can be compared to a public harddrive, to which everybody can read and everybody can write. Looking at the Swarm network this way, there arises an obvious question: what information will be stored in this network and what information not? 
In order to increase the utility of the network, node operators want to persist information that is most valuable for the uploaders. Uploaders can signal how much the chunk is worth to them by attaching a _postage stamp_ to the chunk.

A postage stamp is created by burning BZZ on the main-chain (see [smart-contracts](https://github.com/ethersphere/storage-incentives/blob/master/src/PostageStamp.sol)). By burning tokens, we align the incentives of BZZ token holders with node operators. It is envisioned that later, postage stamp inpayments are not burned, but distributed to node operators.

[Meeting notes, explaining technical architecture behind how postage stamps are implemented](https://hackmd.io/ZuTshAH7RbuaQ0YvBYz3Uw?view)
[Youtube video, explaining Swarm incentives (among them postage stamps)](https://www.youtube.com/watch?v=oarfbLFdae4&t=3902s)
[Live demo at the Liberate Data week](https://youtu.be/s2xNgLw_ZbI?t=957)

## Status
✅ [Postage stamps contracts](https://github.com/ethersphere/storage-incentives/) implemented
✅ [API-endpoints ready on the `storage-incentives` branch](https://github.com/ethersphere/bee/tree/storage-incentives)
✅  [Use postage stamps in the Bee node](https://github.com/ethersphere/bee/pull/1562)
✅  Integration tests of postage stamps [(#129)](https://github.com/ethersphere/beekeeper/pull/129), [(#133)](https://github.com/ethersphere/beekeeper/pull/133)
🔨 [bee-js team will work on making it easy to upload with postage-stamps](https://github.com/ethersphere/bee-js/issues/212)

**Comment by Eknir** [comment]
[Research notes on short-term, outstanding tasks](https://hackmd.io/gpI2Ku9HTgiugqEiEkZH6w)

**Comment by zelig** [comment]
architecture proposals:


## Postage stamp - architecture proposals:

-  Postage Stamp contracts - https://hackmd.io/tvacCgfBSWmeConc3rFOtw
-  contract events, blockchain syncronisation - https://hackmd.io/3ZZOx25JRuiDfPrvJdeCKg
- Postage API - https://hackmd.io/XE6CATOkTki3AM9QcHXjvg
- sending and validating postage stamps - https://hackmd.io/t1uOx-URTyyVhqnGxBv5xA
- postage stamps in the localstore - https://hackmd.io/2NgPR2CeQICKzWBAH7Mk0Q
-  stamping chunks during upload - https://hackmd.io/k42tvB44RWGXtpbpmdcv2g
-  batch store - https://hackmd.io/o8RGsNwZSN6IE0lkBAZCPw
-  garbage collection and postage value - https://hackmd.io/3ZZOx25JRuiDfPrvJdeCKg

**Comment by agazso** [comment]
- Postage stamp support in bee-js - https://github.com/ethersphere/bee-js/pull/290
- Postage stamp support in swarm-cli - https://github.com/ethersphere/swarm-cli/pull/98
