### ISSUE TITLE
Pusher repeatedly pushing single chunk

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1441]
#### Summary
I've been watching the chunks coming through my node on the pushsync handler and see a lot of duplicate push requests coming through for a single packet.  Not just in a burst, but continuously over a long period of time.

Investigating how this works on the pusher side, it gets a subscription notification from the pushIndex, pushes the chunk, and if a receipt is successfully received, it invokes a Put with setSync which removes the chunk from the pushIndex after looking up the StoredTimestamp from the retrievalIndex.

Well, I'm suspecting that the source of these pushsync requests has an issue that causes either the chunk not to be found in the retrievalIndex or the timestamp doesn't actually match the entry in the pushIndex, either of which can cause a successful return from Put(setSync) even though the chunk is actually still in the pushIndex.  This is especially true if the timestamp in the pushIndex doesn't match the timestamp retrieved from the retrievalIndex, a situation that I have directly observed in my own localstore after numerous times of crashing and restarting my node while actively uploading files.  But this issue isn't about how the problem happens, but the behavior of a node with such a condition.

#### Steps to reproduce
Reproducing this outside of a contrived test is nearly impossible, but at the time of this writing, chunk 039945dd184fe6e6b1c1cab5d3aaa774e9c57a1bc08c4b4d8194290d282a5510 has been coming through my node for the past 2.5 hours.

#### Expected behavior
I would expect a given pusher to push a chunk only until it receives a successful receipt, not over and over and over again.

#### Actual behavior
A single chunk is being pushed into my node repeatedly over a span of 2.5 hours and still going!  039945dd184fe6e6b1c1cab5d3aaa774e9c57a1bc08c4b4d8194290d282a5510

I suspect the original pusher node may be logging a debug event from line 158 in function setSync in mode_put.go, specifically:

db.logger.Debugf("localstore: chunk with address %s not found in push index", addr)

This will happen if the timestamp pulled out of the retrievalDataIndex doesn't match the timestamp that is the key to the pushIndex record.

Or if the chunk isn't found in the retrievalDataIndex to start with, then a zero timestamp is attempted to be removed from the pushIndex at line 141 with no logger record to indicate any issues, but at least the DeleteInBatch error (if any) is returned in this case.

There are lots of relational integrity assumptions made in the localstore between the original chunk in the retrievalDataIndex and key components in various other *Index tables that do not seem to be consistency checked anywhere.

And worse, since the StoredTimestamp is not returned to the pusher from the pushIndex, it is assumed by setSync that the correct record can be removed from the pushIndex using the StoredTimestamp from the retrievalDataIndex record for the chunk.  If these two timestamps don't match, a debug message will be logged, but the record will remain in the pushIndex and be pushed forever, well, at least on every push trigger.

I have studied the migration of chunks through the various indices and realize that this can only happen in the event of a database corruption, but this particular corruption has ongoing ramifications for the swarm itself as it causes redundant and repeated pushsync activity.

**Comment by Eknir** [comment]
@ldeffenb , would be amazing if you can validate if this is fixed per v0.6.0
