### ISSUE TITLE
Docs: incorrect documentation for `ChequebookAddress`

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#1443]
In your OpenAPI specification, you have a [`ChequebookAddress`](https://github.com/ethersphere/bee/blob/master/openapi/SwarmCommon.yaml#L135) defined as `EthereumAddress` which is according to your definition non-prefixed hex string, yet your API returns actually prefixed hex string with `0x`. Which is inconsistent with your general approach to hex strings but more importantly wrong in the API documentation.

**Comment by Eknir** [comment]
Thanks @auHau !

**Comment by acud** [comment]
Speaking with @ralph-pichler we reached the following conclusions:
- ethereum addresses by convention are `0x` prefixed
- we should change the API spec to specify that all ethereum addresses that are being returned have the `0x` prefix
- sweep through the API to make sure all endpoints return the correct format
- other swarm references dont need to follow the same convention and can be used as a non 0x prefixed addresses
