### ISSUE TITLE
Cashout API ends up at "500" error code

### ISSUE THREAD

**Issue by hlbcal** [ethersphere/bee#1445]
#### Summary
It returns {"message": "cannot cash cheque", "code": 500} by calling cashout API. 

#### Steps to reproduce
![bee_cashout_issue](https://user-images.githubusercontent.com/34809039/111490904-59f43780-8776-11eb-8eba-cebe98b2d688.png)

#### Expected behavior
Should be able to see a cashout tx.

#### Actual behavior
null tx

I'm using bee-clef now but I didn't in the very beginning.

**Comment by ralph-pichler** [comment]
do you have the corresponding log output from bee?

**Comment by pk27734** [comment]
Would this relate to https://github.com/ethersphere/bee/issues/1436?

**Comment by hlbcal** [comment]
> do you have the corresponding log output from bee?

Here comes the log.

[cashout_log.txt](https://github.com/ethersphere/bee/files/6163724/cashout_log.txt)

**Comment by hlbcal** [comment]
> Would this relate to #1436?

No, is a different case.

**Comment by pk27734** [comment]
This however seem like it, right?

```
ubuntu@nuc:~/docker$ curl http://localhost:1635/chequebook/cheque/787a31f37863002babeba0f8f4e868010e43f9518e39d0829c61255f4a02511d | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   387  100   387    0     0   377k      0 --:--:-- --:--:-- --:--:--  377k
{
  "peer": "787a31f37863002babeba0f8f4e868010e43f9518e39d0829c61255f4a02511d",
  "lastreceived": {
    "beneficiary": "0xdF8A7f178C4D06cDC50261f46F7393b2bf1a7931",
    "chequebook": "0x5C720259491632E52C0e3e5F553aAB4f092e0F54",
    "payout": 3650000000000
  },
  "lastsent": {
    "beneficiary": "0x2D9735f193Cf7D1E39cB44a648f4FB550A253518",
    "chequebook": "0xdB54E1DC984828A4a0709058fe57419c5B170e96",
    "payout": 8992000000000
  }
}
ubuntu@nuc:~/docker$ curl http://localhost:1635/chequebook/cashout/787a31f37863002babeba0f8f4e868010e43f9518e39d0829c61255f4a02511d | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    52  100    52    0     0    541      0 --:--:-- --:--:-- --:--:--   541
{
  "message": "cannot get cashout status",
  "code": 500
}

```

**Comment by ralph-pichler** [comment]
Hm, given the log I think you might have a chequebook for the wrong address and received cheques for the wrong address also. You said you are using bee-clef now but not in the beginning? Did you reset your bee data directory when doing the switch?

**Comment by cobordism** [comment]
I am experiencing the same issue.

I have downgraded to 0.5.2 and variably enabled and disabled clef and then run:
```
curl localhost:1635/balances | jq '.' > addresses.txt
for addr in `cat addresses.txt | grep -v '-' | grep "balance" -B 1 | grep peer | cut -c 16-79`; do curl -XPOST http://localhost:1635/chequebook/cashout/$addr; done
```

Basically just hit every cashout address possible. Some fail, some work. I don't have any further insight into what's going on. Apparently my bee node deployed the chequebook using the wrong key and never deployed one with the clef managed key.

**Comment by ldeffenb** [comment]
This is a good way to spend gETH and log 0 gBZZ valued cashouts.  If a peer has not issued a cheque in excess of the total already cashed out, the POST to /cashout will do a transaction, but no gBZZ will move.

**Comment by AlexyTime** [comment]
The same problem. Could you pls share the code of "have downgraded to 0.5.2 and variably enabled and disabled clef"?  My system is Debian and I don't know much about code..

> I am experiencing the same issue.
> 
> I have downgraded to 0.5.2 and variably enabled and disabled clef and then run:
> 
> ```
> curl localhost:1635/balances | jq '.' > addresses.txt
> for addr in `cat addresses.txt | grep -v '-' | grep "balance" -B 1 | grep peer | cut -c 16-79`; do curl -XPOST http://localhost:1635/chequebook/cashout/$addr; done
> ```
> 
> Basically just hit every cashout address possible. Some fail, some work. I don't have any further insight into what's going on. Apparently my bee node deployed the chequebook using the wrong key and never deployed one with the clef managed key.

**Comment by acud** [comment]
closing this as the UX has significantly improved since. If the problem still persists please open a new issue
