### ISSUE TITLE
Users of own geth node experiencing error wrt transactions without replay protection.

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#1473]
#### Summary
Users using own geth node are unable to cashout.

#### Steps to reproduce
Start Bee without Clef and using own geth node. Transactions cannot be processed without the option `--rpc.allow-unprotected-txs`

#### Expected behavior
Tx's should be processed

#### Actual behavior
Tx's are not processed

More info:

https://discord.com/channels/799027393297514537/810905662375854123/823553650625609789

Relevant:

![52ob1b](https://user-images.githubusercontent.com/130104/112116849-9da1d380-8bb2-11eb-8202-8efdc06d2508.png)

**Comment by ralph-pichler** [comment]
Should have been fixed in 0.5.2. Some users were still using 0.5.1.

**Comment by significance** [comment]
ah thanks @ralph-pichler, spotted your message too. have asked users to confirm.

**Comment by significance** [comment]
confirmed
