### ISSUE TITLE
improve shutdown sequence

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1479]
# Task

Out shutdown sequence is a bit dirty, sometimes localstore still shuts down with open goroutines. We should revisit the sequence and optimize it, making sure that some things happen before others and that the shutdown time is within limits for the k8s graceful shutdown period which is 30 seconds AFAIK.
## Acceptance criterea

Shutdown should be clean

**Comment by mfw78** [comment]
Spot on, grace period for K8S by default is 30s. Given K8S, I have the use case where the `StorageClass` is quite slow, which was impeding the performance of bee considerable (iSCSI-backed `PersistentVolume`s running over only 1Gbe, with not a particularly fast SAN). As such, I hacked together an init container and pod lifecycle handler to `rsync` the bee data to/from the SAN so it may run locally on the K8S node's NVME ephemeral storage.

This works great....except when something crashes. Having the ability to send a signal, or alternatively via the debug API endpoint to write a checkpoint to the localstore db, for subsequent `rsync` seems like a reasonable idea to bridge that problem.

I think in most K8S cases the problem occurs when designing the `StatefulSet` to roam between nodes, which is critical for failover protection. If this is done, remote storage will be used, running into IOPS/performance issues, necessitating a similar solution that I've come up with. Any feedback / suggestions are much appreciated.

**Comment by mfw78** [comment]
Additionally, with the setup that I've been running, I encountered a problem recently whereby `geth` decided to randomly toast itself, taking down the entire `StatefulSet`. It seems that the resulting termination was handled correctly by the pod's lifecycle handlers, and the data directory was `rsync`'d to the SAN.

When the pods start up, they failed with:

```
Error: localstore: database entry point either missing or corrupted
```

**Comment by Eknir** [comment]
@acud , there is a PR out on the shutdown sequence. Is this one covering this issue? If so, could you please connect it, or close the issue if merged?
