### ISSUE TITLE
Weird Log Messages in Bee Node Logs. 

### ISSUE THREAD

**Issue by Sally-Balls** [ethersphere/bee#1498]
#### Summary
Have Bee Node up and Running.  Receiving Weird messages in my logs.  Quite Often (every 5th line).

 time="2021-03-26T00:35:03Z" level=warning msg="skipping peer in response Underlay:"\004\306\020>\302\006\303\326\245\003'\000%\010\002\022!\003q/5>'\303\343\336\276\235\322u\357\re\t\310\020\\\371\022\262\243\200\346X\303\332?\271\235K" Signature:"NZ~\343Ac\262/\366\313P!\227\r{o\365%i\204\254\027\">\234\265\177\301\000b>\3662|\373A\022\356\206\242\363M\276\001F\314\257\377\303\3329!\265c\013N!\254\037Cf\365\235\323\033" Overlay:"\027\240\210c.l\037\365.\270\265\211\016\\\257r\005\350\2315p\206e=_\241JM\352\350" : leveldb/table: corruption on data-block (pos=431540): checksum mismatch, want=0x62376365 got=0xb0bf1a07 [file=000926.ldb]"

#### Steps to reproduce
No Steps to reproduce.  I just have my bee node running and the following message's pop up.

 time="2021-03-26T00:35:03Z" level=warning msg="skipping peer in response Underlay:"\004\306\020>\302\006\303\326\245\003'\000%\010\002\022!\003q/5>'\303\343\336\276\235\322u\357\re\t\310\020\\\371\022\262\243\200\346X\303\332?\271\235K" Signature:"NZ~\343Ac\262/\366\313P!\227\r{o\365%i\204\254\027\">\234\265\177\301\000b>\3662|\373A\022\356\206\242\363M\276\001F\314\257\377\303\3329!\265c\013N!\254\037Cf\365\235\323\033" Overlay:"\027\240\210c.l\037\365.\270\265\211\016\\\257r\005\350\2315p\206e=_\241JM\352\350" : leveldb/table: corruption on data-block (pos=431540): checksum mismatch, want=0x62376365 got=0xb0bf1a07 [file=000926.ldb]"

[logs-dappnode-package-DAppNodePackage-bee.dnp.dappnode.eth (2).txt](https://github.com/ethersphere/bee/files/6208690/logs-dappnode-package-DAppNodePackage-bee.dnp.dappnode.eth.2.txt)

I have included my log in the issue

#### Actual behavior

[logs-dappnode-package-DAppNodePackage-bee.dnp.dappnode.eth (2).txt](https://github.com/ethersphere/bee/files/6208699/logs-dappnode-package-DAppNodePackage-bee.dnp.dappnode.eth.2.txt)

**Comment by Eknir** [comment]
Thank you for reporting! How did you use your node before this happened? Did you restart, update, fresh install? 
Also, is the situation already resolved (if so: how?).

With more information available, we can have a look at this.
