### ISSUE TITLE
Failover for swap endpoints

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee#1499]
# User story

## Story

As a node operator I want the feature such that `bee` will automatically fail-over to another endpoint in the event that an endpoint fails.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
Thank you for this suggestion, but we prefer to keep this logic out of Bee. This is logic that is generally applicable and useful for many projects. I am reasonably sure that there is a way how many Ethereum endpoints can be combined in one, with the mentioned fallback functionality. 
It would help if you mingle in Ethereum communities to see if something like this already exists (open-source). 

If it exists, and also if it does not exist, I would appreciate to hear your outcome here. If it exists, we can reference it on our documentation and use it ourselves as well. If it does not exist, Swarm may consider funding an open-source project that would make this with a bounty.
