### ISSUE TITLE
Insufficient payment threshold (10000)

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1503]
#### Summary
I noticed that a few of my nodes were failing to push chunks to closer peers due to "attempted overdraft" while reserving the balance for a peer.  Further checking the --verbosity 5 logs revealed that the peer announced a completely insufficient payment threshold to even push the smallest chunk.  If this node remains the closest possible node for a given chunk, that chunk will retry forever in the pusher since the Reserve call in pushToClosest is considered fatal and no additional peers will even be attempted.

#### Steps to reproduce
Get connected to a peer that announces a small payment threshold and try to push a chunk to that peer.

#### Expected behavior
My node should either a) disconnect and/or blocklist the peer that cannot even handle a reasonable chunk or b) try the next closest peer so that my push chunk can be delivered instead of infinitely retrying.

#### Actual behavior
Pusher keeps trying, and failing, to deliver the chunk to that closest peer.

From 3 different nodes (Note: my node's payment threshold is the default of 10000000000000)

time="2021-03-26T08:55:46-04:00" level=trace msg="received payment threshold announcement from peer 9726928d3d3830821e3415acac9ebf8d16cd7a1c7f862558b3cc136e53ad98b1 of 10000"
Causes the following over and over again:
time="2021-03-26T09:09:10-04:00" level=debug msg="pusher chunk 97027bb709c0345b2f5374b4b2d05ad6dc1ecec098710ad80298d56ca647d644 err reserve balance for peer 9726928d3d3830821e3415acac9ebf8d16cd7a1c7f862558b3cc136e53ad98b1: attempted overdraft"

time="2021-03-26T12:59:24Z" level=trace msg="received payment threshold announcement from peer 48156cf9e6af152f526a13458ec9e19b14e7b4d4d63d1501c507f458afa8d51b of 10000"
and
time="2021-03-26T13:03:53Z" level=debug msg="pusher chunk 48b9e7d4bc0f40cf093ef3ca23ce4b4b3094407771e1906808d45c683dac6e83 err reserve balance for peer 48156cf9e6af152f526a13458ec9e19b14e7b4d4d63d1501c507f458afa8d51b: attempted overdraft"
time="2021-03-26T13:05:22Z" level=debug msg="pusher chunk 48c39a2b10ecbb74ebc4f523ab04ce8fa21f20c57f80d546ae5cbeb200096e0c err reserve balance for peer 48156cf9e6af152f526a13458ec9e19b14e7b4d4d63d1501c507f458afa8d51b: attempted overdraft"

time="2021-03-26T13:10:08Z" level=trace msg="received payment threshold announcement from peer 11d38665f15e13bb59a0fb478585c2185ce8d930d99517a9550d3bedebaa01ea of 10000"
Results in:
time="2021-03-26T13:12:34Z" level=debug msg="pusher chunk 11133f08f6f1570e879aebd6625f132cd31b06106912fdd58e054fc4cebf816e err reserve balance for peer 11d38665f15e13bb59a0fb478585c2185ce8d930d99517a9550d3bedebaa01ea:
attempted overdraft"

**Comment by ldeffenb** [comment]
Some peer IDs in this state are:
114e950f34bc125d59487044baab02a87fe5a2351e47fc4a5e12c2a2c3843898
470784f0323d73f1f1cfd1defa339c1ab1f1ac8a0d1d0c6fcab668a1b429ef37
8760fe3104b64f28832fca175c6b9869047500756bf763611700c1349b4daa7a

**Comment by ldeffenb** [comment]
It appears that this too-low threshold also affects the retrieval:
time="2021-03-26T18:01:22-04:00" level=debug msg="retrieval: failed to get chunk 968ad69fb4af10daf3e12dbec8bdcff1185028c5a24cec1da65ed65a8e82bea5 from peer 9651106ac19d9b7d9309206eac67072d1a9f25fbca610e673202bbf3f55f67bd: attempted overdraft"

**Comment by ldeffenb** [comment]
I just downloaded the DAppNode bee installation .tar file from ipfs and it has the following values in the default config.yml file:
# amount in BZZ below the peers payment threshold when we initiate settlement (default 10000)
payment-early: 10000
# threshold in BZZ where you expect to get paid from your peers (default 100000)
payment-threshold: 100000
# excess debt above payment threshold in BZZ where you disconnect from your peer (default 10000)
payment-tolerance: 10000

**Comment by ldeffenb** [comment]
Opened the following issue up at DAppNode:
https://github.com/dappnode/DAppNode/issues/288

**Comment by Eknir** [comment]
Thanks @ldeffenb ! We are scheduling this task.

**Comment by ldeffenb** [comment]
Here's my fix for this issue: https://github.com/ldeffenb/bee/commit/f5149c3a4c6a146de29975476df2d75532f816ea#diff-e0ce1a7f3f76d7bfda0ffdae6e0226aa63b3009c4c4a770c321876aecad0a6c1
