### ISSUE TITLE
Unable to start bee

### ISSUE THREAD

**Issue by my-Gem** [ethersphere/bee#1505]
> 
![搭建swarm获取bzz遇到的问题](https://user-images.githubusercontent.com/26290087/112716621-5ef97980-8f22-11eb-9ed7-3e5e5313175b.png)

**Comment by Eknir** [comment]
Sorry, but we don't have enough information here to help you. Please reach out to your local bee community or our [Discord](https://discord.gg/tGaWb5bT7a)
