### ISSUE TITLE
Unable to install bee on Ubuntu running on WSL

### ISSUE THREAD

**Issue by avalyn2** [ethersphere/bee#1506]
#### Summary
bee installation failed with error
`Error: dial unix /var/lib/bee-clef/clef.ipc: connect: no such file or directory`

#### Steps to reproduce
1) Followed the steps to install Bee Clef https://docs.ethswarm.org/docs/installation/bee-clef
2) Followed the steps to get Bee wget https://github.com/ethersphere/bee/releases/download/v0.5.3/bee_0.5.3_amd64.deb
sudo dpkg -i bee_0.5.3_amd64.deb
3) Execution failed after running `sudo dpkg -i bee_0.5.3_amd64.deb`

#### Expected behavior
Bee installation succesful

#### Actual behavior
`user@DESKTOP-S00B9E3:~$ sudo dpkg -i bee_0.5.3_amd64.deb
(Reading database ... 32170 files and directories currently installed.)
Preparing to unpack bee_0.5.3_amd64.deb ...
Unpacking bee (0.5.3) over (0.5.3) ...
Setting up bee (0.5.3) ...
Error: dial unix /var/lib/bee-clef/clef.ipc: connect: no such file or directory
dpkg: error processing package bee (--install):
 installed bee package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 bee
`

Using Ubuntu 20.04.2 LTS running on Windows Subsystem for Linux (WSL).

**Comment by Eknir** [comment]
It seems to me that `bee-clef` was not correctly installed. Can you confirm that `bee-clef` was running?
This to me does not seem as a problem with bee, or bee-clef , but rather a user error. We would be very happy to help you in our [Discord](https://discord.gg/tGaWb5bT7a)!
