### ISSUE TITLE
gas price too low for chequebook deployment

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#1528]
#### Summary
gas prices seems set to 1 gwei which is too low for goerli at the moment, as a result the chequebook did not deploy

#### Steps to reproduce

create and fund new node

#### Expected behavior

chequebook should deploy

#### Actual behavior

chequebook could not deploy

**Comment by cppfuns** [comment]
It is recommended to add Gas Price to the parameter configuration instead of hard-coded 1

**Comment by pefish** [comment]
> It is recommended to add Gas Price to the parameter configuration instead of hard-coded 1

It is not hard-coded 1, but hard-coded nil.

nil allows the transaction layer to ask the blockchain for the going gas price and it will use that.

However, I think that we still should have ability to customize gas price.

**Comment by cppfuns** [comment]
> > It is recommended to add Gas Price to the parameter configuration instead of hard-coded 1
> 
> It is not hard-coded 1, but hard-coded nil.
> 
> nil allows the transaction layer to ask the blockchain for the going gas price and it will use that.
> 
> However, I think that we still should have ability to customize gas price.

Is there a version of bee's existing code that supports custom configuration?

**Comment by cppfuns** [comment]
https://github.com/ethersphere/bee/commit/b22fda83d7bf470fd766486bdf82c67f7ea526c5
