### ISSUE TITLE
Add all /tags routes to the debug API

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee#1530]
# Task
Currently, only the `GET /tags/{uid}` route is available on the debug API. This is problematic, because when `bee` is ran in gateway mode, all `/tags` endpoints are disabled on the external API.

As far as I can tell, this leaves us with no way of getting tag information if all created tags aren't recorded when files are created.

Alternatively, maybe some `/tags` routes should still be accessible publicly in gateway mode. Having `GET /tags` and `GET /tags/{uid}` could prove very useful to create statistics for example.

## Acceptance criterea
Be able to list tags and fetch information about them when running in gateway mode.

**Comment by Eknir** [comment]
This is highly related to #1369

**Comment by Eknir** [comment]
Closing this, but we keep track of the information here and the connected PR (#1532). Thanks!
