### ISSUE TITLE
Resolvers

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#154]
## Story
- As a dapp developer, I want to serve my content under a human-readable address such that my users can memorize the address and share it with friends and I can update the content.

## Background
- Using ENS/RNS

## Acceptance criteria

**Comment by Eknir** [comment]
This task might be completed by writing a separate programme:

The progframme (say `ens.go`) is a wrapper around the library [ens](https://godoc.org/github.com/puffscoin/go-puffscoin/contracts/ens) or another comparable library. The component takes 3 arguments: a blockchain backend url (`IPC`or http api, such as Infura), an `ENS_contractAddress` and a `name`. It returns a hash or an error. If we have the first two components as en environment variable, we only need to pass in the `name`. Additionally, other variables might be needed (out of my scope, it's up to the implementer).

If we have this component, it will allow us to pipe the outcome of this programme into Bee. In Swarm, we would do `swarm down | ens swarm.eth`. 

From my understanding, matters are slightly more complicated in `Bee`, as we only expose the download function via an HTTP API and I'm not sure if it is possible to "pipe" into an HTTP query.

However, developing this functionality as a separate component (first) probably still makes sense.

WDYT @janos @nolash @paxthemax @ralph-pichler @vojtechsimetka @santicomp2014 ?

**Comment by nolash** [comment]
I think that can be useful in any case.

`bee-name foo.eth | bee-join` would be a good target for bee.

Please look at  `bee-split` and `bee-join` vs `pkg/file` to see how the two related tools are organized.

I guess a `pkg/ens` library would be the interface to the underlying whatever generic blockchain glue already present.

**Comment by nolash** [comment]
perhaps also not called `ens` since the term would double as interface and implementation.

**Comment by ralph-pichler** [comment]
I would try to avoid a dependency on `puffscoin/go-puffscoin` (which seems to be an abandoned geth clone). 99% of the code there is autogenerated anyway, we can just abigen that ourselves if needed or use `go-ens` which seems to be actively maintained at least (and also includes the full resolution logic).  
You may also want to look at the `ethers-ens` tool (https://github.com/ethers-io/ethers.js/tree/ethers-v5-beta/packages/cli) which might already provide the needed functionality (for ens at least). Never tried it myself though.

**Comment by janos** [comment]
I have just tried https://github.com/wealdtech/go-ens as per their example (with minor adjustments) and it works without cgo, can cross-compile even if it depends on go-ethereum/ethclient. It is unfortunate that go-ethereum v1.9.14 broke the ABI package, so v1.9.13 must be used for go-ens.

If resolving is such a simple task with go-ens, I do not know if we need our own library, just to use it in the tool that we want it to be in, bee, "bee-cli", or something else.

**Comment by nolash** [comment]
> If resolving is such a simple task with go-ens, I do not know if we need our own library, just to use it in the tool that we want it to be in, bee, "bee-cli", or something else.

I agree.

**Comment by vojtechsimetka** [comment]
> perhaps also not called `ens` since the term would double as interface and implementation.

Yes I would suggest just calling it `ns` or `NamingService`. There is now more than one relevant and used name services like ENS, Unstopable Domains, RNS etc.

> If resolving is such a simple task with go-ens, I do not know if we need our own library, just to use it in the tool that we want it to be in, bee, "bee-cli", or something else.

++

**Comment by Eknir** [comment]
@paxthemax , can you please link your work here in the comments?
