### ISSUE TITLE
Pre-defined Bee client keys

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1557]
# User story

## Story
There is a need for managing/generating keys outside from the Bee that Bee uses.
If keys are generated even before Bee starts first, it could be possible to orchestrate arbitrary numbered Bee clients with those keys and the keys could be still handled via the outside application (export/manage easily) and it could be really great for creating test environment (with passing pre-defined keys for startup).

## Acceptance criteria

Possibility to provide `swarm.key` in V3 format (best scenario) or get know how to generate this unique key format.

## Background
As I noticed the key recognition is implemented in Bee and I can provide `libp2p.key, pss.key, swarm.key`  in its config folder before Bee starts.

One use case that would be nice to achieve:
`swarm-cli` can generate V3 compatible keys already with the `identity` command, which could be also useful to generate Bee client keys as well, with which it could start arbitrary numbered Bee clients [in Docker](https://github.com/ethersphere/swarm-cli/issues/17#issuecomment-781998784). Thereby the users easily could manage their keys and it wouldn't be neccessary to export from `clef` directly (that they will do anyway to import Metamask or to some wallet app. By this they can export to a not protected folder).
But moreover we would like to create a determenistic test environment for JS tests, and it could be easier to do by the following workflow:
- pass X, how many nodes I would like to orchestrate
- `swarm-cli` generates X*3 keys by the `identity` command
- creates datadirs for Bee client(s) within the CLI's config folder with chmod 700
- export the keys to these datadirs
- give right of the folder(s) to the _bee docker user_
- start bee nodes with these datadirs

Unfortunately `swarm.key` is not in V3 format, but there is a [tool](https://github.com/ethersphere/exportSwarmKey) to export it into that. Nevertheless this use-case needs the opposite side, it wants to generate this key (which should be in V3 format).
Also as I heard it won't be supported in the future, which makes this use-case impossible to do.

I know Bee uses `clef` for signing, because it may provide some memory safe environment (not sure how exactly, if someone can link a great article about that I would appretiate), but if it is not the case then someone could tell me the consideration behind using `clef`? What are those security features that it gives? The before mentioned `swarm-cli` workflow would be less secure?

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
Hi,
Looking forward to discuss this today.

Preliminary thoughts:
- We should not encourage the usage of the in-memory signer to a user. The in-memory signer is for testing purposes.
- Clef is improving the security of the Bee node, by not exposing the key material in plain form to the bee process. This makes the possible attack surfaces to confiscate this key much smaller and easier to reason about. Furthermore, the security properties of clef can be extended if the need arises, which is not the case with the in-memory signer (please see https://github.com/ethereum/go-ethereum/tree/master/cmd/clef).
- If you need the reverse operation of exportSwarmKey, @jmozah can probably help you with that.

> Also as I heard it won't be supported in the future, which makes this use-case impossible to do.

What do you mean here?

**Comment by Eknir** [comment]
Hi,
Looking forward to discuss this today.

Preliminary thoughts:
- We should not encourage the usage of the in-memory signer to a user. The in-memory signer is for testing purposes.
- Clef is improving the security of the Bee node, by not exposing the key material in plain form to the bee process. This makes the possible attack surfaces to confiscate this key much smaller and easier to reason about. Furthermore, the security properties of clef can be extended if the need arises, which is not the case with the in-memory signer (please see https://github.com/ethereum/go-ethereum/tree/master/cmd/clef).
- If you need the reverse operation of exportSwarmKey, @jmozah can probably help you with that.

> Also as I heard it won't be supported in the future, which makes this use-case impossible to do.

What do you mean here?
