### ISSUE TITLE
JS Number overflow for balances, settlements and generally "money"

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#1561]
JavaScript's `number` type is able to maximally safely represent `2^53 - 1` (see [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)) above that floating errors steps in and we can't assume accurate representations and calculations. This is especially problematic when money comes in, which is the exact case as we are running into this limitation with all the balance, settlement, and generally money APIs. With the number of decimals that BZZ uses we are able to safely represent inside JavaScript only values lower than `0.9 BZZ`, which I believe you agree is not sufficient.

**The main problem is that the fields containing these data (balances, settlements etc.) are currently typed and returned as `number`.** Which then if somebody uses thing like `JSON.parse()` to convert the response into JS native objects hits this problem.

The common approach to solve this is usually to pass the numeric value as a string in all the response/requests and on the JS-side use libraries or natives like [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) that are able to correctly work with these values.

We (Bee Gees) are working on correctly handling this inside bee-js, but we believe that this should be actually tackled on the Bee level. Possibly by changing the return types of these properties to string as that would correctly communicate this expectation to other API users.

**Comment by AuHau** [comment]
For some more info see our issue: https://github.com/ethersphere/bee-js/issues/254

**Comment by Eknir** [comment]
Thanks for noting this!

**Comment by ralph-pichler** [comment]
this is related to #756
