### ISSUE TITLE
Get last cashout action for peer has wrong return type in docs

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee#1570]
#### Summary
The API docs for `GET /chequebook/cashout/{peer-id}` has different 200 response object than what bee really returns. https://docs.ethswarm.org/debug-api/#tag/Chequebook/paths/~1chequebook~1cashout~1%7Bpeer-id%7D/get

#### Steps to reproduce
Run latest released bee node with any peer from which a cheque was received, navigate to `http://localhost:1635/chequebook/cashout/{peer-id}` and look at the response.

The response has extra undocumented value `uncashedAmount` and the `chequebook`, `beneficiary` and `cumulativePayout` values are nested in `lastCashedCheque`.

#### Expected behavior
The API response in the DOCS should look like:
```JSON
{
  "peer": "dc830656350927d57be37dea90834f79d40cf4d4574746be0129496089d49bfc",
  "lastCashedCheque": {
    "beneficiary": "0xD2fCA1F348b35E869490435e6C2eFf3996624D64",
    "chequebook": "0x2689Cc943FEC13655869B716A8F2cAd8C32AdD0B",
    "payout": 178765000000000
  },
  "transactionHash": "0x7a25acca4d248de3f87594f52e78d7f325ddd8428d4abee4468e458b5b8ff94f",
  "result": {
    "recipient": "0x05f26c4838be44528ec6fd4a4a31bb7f39296dfb",
    "lastPayout": 0,
    "bounced": false
  },
  "uncashedAmount": 0
}
```

#### Actual behavior

The API docs currently shows the respons is:
```JSON
{
  "peer": "36b7efd913ca4cf880b8eeac5093fa27b0825906c600685b6abdd6566e6cfe8f",
  "chequebook": "36b7efd913ca4cf880b8eeac5093fa27b0825906",
  "cumulativePayout": 0,
  "beneficiary": "36b7efd913ca4cf880b8eeac5093fa27b0825906",
  "transactionHash": "e28a34ffe7b1710c1baf97ca6d71d81b7f159a9920910876856c8d94dd7be4ae",
  "result": {
    "recipient": "36b7efd913ca4cf880b8eeac5093fa27b0825906",
    "lastPayout": 0,
    "bounced": true
  }
}
```

**Comment by ralph-pichler** [comment]
docs.ethswarm.org always shows the documentation for the last release. this change has not been released yet. when the docs are regenerated from the openapi yamls this should be up to date again.

**Comment by vojtechsimetka** [comment]
Apologies you are right, I was running two different versions of `bee`
