### ISSUE TITLE
Hardcoded 16 bins in pkg\pullsync\pullstorage\pullstorage.go Cursors()

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1577]
#### Summary
While perusing the source code around PullSync, I noticed the following function in pkg\pullsync\pullstorage\pullstorage.go:

https://github.com/ethersphere/bee/blob/d447839345b388954d236bcbbed18f964e1c4a1c/pkg/pullsync/pullstorage/pullstorage.go#L122

	// Cursors gets the last BinID for every bin in the local storage
	func (s *ps) Cursors(ctx context.Context) (curs []uint64, err error) {
		curs = make([]uint64, 16)
		for i := uint8(0); i < 16; i++ {
			binID, err := s.Storer.LastPullSubscriptionBinID(i)
			if err != nil {
				return nil, err
			}
			curs[i] = binID
		}
		return curs, nil
	}

Seems to me that 16 should be a constant of some sort, especially since swarm.go defines:

	MaxPO             uint8 = 15
	ExtendedPO        uint8 = MaxPO + 5
	MaxBins                 = MaxPO + 1

and puller uses:

		bins            uint8 = swarm.MaxBins

But yet relies on p.syncer.GetCursors to give back a properly sized array of cursors.

#### Steps to reproduce
Just read the source.  If either 16 or swarm.MaxBins changes, things will break.

#### Expected behavior
I'd expect a single source of this constant to be used consistently.

#### Actual behavior
pkg\pullsync\pullstorage\pullstorage.go has a hard-coded 16.

**Comment by ldeffenb** [comment]
It appears that #1593 will be fixing this.

**Comment by acud** [comment]
Yes! I was just about to mention this here. Thanks for this ticket :pray:
