### ISSUE TITLE
Unpinning directory uploaded with an index document fails

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1589]
#### Summary

Unpinning directory uploaded with an index document fails.

#### Steps to reproduce

- create a tarball with a single file
- upload with curl, use `swarm-pin` header and upload as a collection, set the file to be the index document using `Swarm-Index-Document` header
- try to unpin

#### Expected behavior

Collection should be entirely unpinned.

#### Actual behavior

error occurs while traversing the collection. this appears to be some serialization problem in `mantaray`

**Comment by agazso** [comment]
Also pinning in retrospect is broken for manifests with index documents
