### ISSUE TITLE
Simple Swap Factory bytecode checking

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1591]
#### Summary

I'm [initialising our test environment Bee Factory](https://github.com/ethersphere/bee-factory/pull/1) for JS tests, which operates with its own blockchain network, so I wanted to migrate the [SimpleSwapFactory](https://github.com/ethersphere/swap-swear-and-swindle/blob/master/contracts/SimpleSwapFactory.sol) smart contract to it.
Though the transaction was successful on blockchain side, the Bee responded `Error: factory fail: not a valid factory contract`.
@ralph-pichler helped me with the info it's because the Bee has bytecode verification, where the bytecode has to be exactly identical as excepted, but the last couple of bytes are ignored (the last 64 surely because of the token address parameter of the contract).
Nevertheless to build this exact bytecode from source code is almost impossible, or you need to use all of your luck that you got for your remaining lifetime. During the compilation some particular metadata also will be attached to the bytecode, which does not effect the resulting usability of the contract but it is not considered under this check. Anyhow I tried to compile with the same [source code that has been uploaded to etherscan](https://goerli.etherscan.io/address/0xf0277caffea72734853b834afc9892461ea18474#code%20openzeppelin%20ERC20PresetMinterPauser%C5%B1) and with the same `solc` version v0.6.12+commit.27d51765 with the same parameters (optimizer enable, runs 200) but still I get different bytecode result.

#### Steps to reproduce

1. deploy [ETH20 minter token](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/presets/ERC20PresetMinterPauser.sol)
2. deploy SimpleSwapFactory from [source code that has been uploaded to etherscan](https://goerli.etherscan.io/address/0xf0277caffea72734853b834afc9892461ea18474#code%20openzeppelin%20ERC20PresetMinterPauser%C5%B1) with the prev generated ERC20 token address 
3. start a Bee node with flag `--swap-factory-address=$DEPLOYED_SIMPLE_SWAP_ADDRESS`

#### Expected behavior

Accepts the smart contract since I passed explicitly the contract address.

#### Actual behavior

The Bee process stops, because of invalid smart contract bytecode.

**Comment by Eknir** [comment]
@ralph-pichler , isn't it documented/automated how we compile and deploy our contract?

**Comment by acud** [comment]
@nugaon it works as long as you use the bytecode that was generated by the github ci in https://github.com/ethersphere/go-sw3-abi/tree/master/sw3abi
