### ISSUE TITLE
Remove VOLUME declaration in Dockerfile

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1620]
#### Summary
Into the `Dockerfile` is declared a volume with `VOLUME /home/bee/.bee`, but it should be avoided.

Declaration of volumes with the Dockerfile generate only anonymous volumes, and it is an outdated pattern, how is well clarified here https://stackoverflow.com/questions/52570093/what-is-the-practical-purpose-of-volume-in-dockerfile. Aside of this, it also generate some unwanted behaviors.

When an user choose to generate a named volume with the same mount point of the one declared in Dockerfile, everything works well. But if user choose to separate directories `keys`, `localstore` and `statestore` with different named volumes (for example for backup purposes), a new pointless anonymous volume is always created for each execution, and there is no way for avoid it.

This configuration has not advantages, because anonymous volume lifetime is binded to the container that creates it. Each new container will create a new volume, so user has anyway to declare a named one for persist data between containers. It also has little meaning for documentation purpose, because real documentation already specify how to create docker volumes.

#### Steps to reproduce
Try to run the docker image without declaring the default volume binded to `/home/bee/.bee`, or declaring only different volumes.

#### Expected behavior
Decision on how to create volumes has to be leaved only to user, and anonymous volumes should not be created.

#### Actual behavior
A new anonymous volume will be created, even if unwanted. Each different container execution will create a different one.

**Comment by Eknir** [comment]
Hey! We welcome a PR for this against our Dockerfiles.

**Comment by tmm360** [comment]
All right, I will!

**Comment by tmm360** [comment]
@vandot If I want to backup only `statestore` or `keys` daily, and `localstore` that is much bigger weekly I don't see why not.
For what I've understood `localstore` e `statestore` should be decoupable.

About VOLUME in Dockerfile, I don't understand WHY it should be a best practice. It looks to me a totally outdated advice.

> As you said anonymous volume follows container lifecycle so I don't see any problem with it, it will be removed when container is removed.

No it doesn't. Like any volume, it persist on the host. Please reconsider.

**Comment by vandot** [comment]
@tmm360 they are tightly coupled, if that is changed we will change on our side to ease backup for us as well
if container is started with `--rm` as it should anonymous volumes are cleaned automatically

**Comment by tmm360** [comment]
Umh ok, you are right with `--rm`. Using docker-compose it doesn't disappear.
Ok, my fault, I thought they were decoupled.

**Comment by vandot** [comment]
Not sure how is this applied in your current situation https://docs.docker.com/compose/#preserve-volume-data-when-containers-are-created or you mean when your execute `docker-compose down`?
All volumes will be removed if you specify `-v` flag (`docker-compose down -v`)
``` 
    -v, --volumes           Remove named volumes declared in the `volumes`
                            section of the Compose file and anonymous volumes
                            attached to containers.
```

**Comment by tmm360** [comment]
I'm using simply `docker-compose down`, but also Docker Swarm. But problem doesn't consist if two folders are coupled and I have to backup them together. I will reduce frequency of backups, and use the default mounted volume.
