### ISSUE TITLE
puller persists `math.MaxUint64` interval on live syncing

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1623]
#### Summary

While inspecting interval store persisted values from production, I found that the `math.MaxUint64` is persisted for some reason on certain intervals. This is a clear indication that we have an edge case in `IntervalChunks` that is not handled correctly, since this interval should never be persisted.

#### Steps to reproduce

No clue, yet.
But I assume that it should be visible if we look for the exact value when returning from the iterator.

#### Expected behavior

Interval should never be persisted.

#### Actual behavior

Interval persisted.

**Comment by aloknerurkar** [comment]
#2566 is related to this
