### ISSUE TITLE
Chequebook deployment runs into "Out of gas" exception

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#1624]
#### Summary
I was trying to start a new node, funded the address with ether and BZZ, trying to deploy the chequebook contract, but tx generate an "Out of gas" exception. Here the logs:

```
time="2021-04-29T20:31:46Z" level=info msg="version: 0.5.3-acbd0e2"
time="2021-04-29T20:31:46Z" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
time="2021-04-29T20:31:46Z" level=info msg="using existing swarm network address: 24a4df3584fc88b17e61532448416a6d66173807cb1665c057c3729bb4c876e2"
time="2021-04-29T20:31:46Z" level=info msg="swarm public key 021d82138a69070df06d37a413e9276bbd489b7e66f9fa1c86448c47d9b54ed900"
time="2021-04-29T20:31:47Z" level=info msg="pss public key 03b166f2426f41faa122d86756cc662e047e03560e5b97305a9f3a0b1afe956925"
time="2021-04-29T20:31:47Z" level=info msg="using ethereum address c50670ef56f984e91cd52d767eab47bc41fe2ace"
time="2021-04-29T20:31:47Z" level=info msg="using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474"
time="2021-04-29T20:31:47Z" level=info msg="waiting for chequebook deployment in transaction 91656cf0b92d6540b78b317c66efb668a96a59f426e120cf06352fe51738ec83"
Error: chequebook init: contract deployment failed: transaction reverted
```
Here you can see the exception: https://goerli.etherscan.io/tx/0x91656cf0b92d6540b78b317c66efb668a96a59f426e120cf06352fe51738ec83

#### Steps to reproduce
Don't know

#### Expected behavior
Tx should be accepted

#### Actual behavior
Tx fails with "Out of gas" exception

**Comment by Eknir** [comment]
Hmm. Did you observe this more often since then? Given that this happened on a v0.5.* node, I close the issue now. If it happens again on a v0.6.* node, please report!

**Comment by tmm360** [comment]
I saw that gas limit should be general increased with 0.6, I will report if this will happen again.
