### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by yangkinger** [ethersphere/bee#1629]
#### Summary

The system crashed suddenly

#### Actual behavior

![image](https://user-images.githubusercontent.com/14162431/116807497-0a22d180-ab66-11eb-917f-0ff0431e0bff.png)

**Comment by acud** [comment]
@yangkinger which version are you running?

**Comment by Eknir** [comment]
Closing this issue, as it is stale. @yankinger , please try again with v0.6.0 and report if this still exists there.
