### ISSUE TITLE
Error: overlay address changed

### ISSUE THREAD

**Issue by moonfunjohn** [ethersphere/bee#1630]
I followed the install instruction but failed to start the bee client. It shows error message in log file, please help.

OS: Ubuntu 20.04

May 03 07:30:17 swarm systemd[1]: bee.service: Scheduled restart job, restart counter is at 6144.
May 03 07:30:17 swarm systemd[1]: Stopped Bee - Ethereum Swarm node.
May 03 07:30:17 swarm systemd[1]: Started Bee - Ethereum Swarm node.
May 03 07:30:17 swarm bee[169480]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
May 03 07:30:17 swarm bee[169480]:                 \     /
May 03 07:30:17 swarm bee[169480]:             \    o ^ o    /
May 03 07:30:17 swarm bee[169480]:               \ (     ) /
May 03 07:30:17 swarm bee[169480]:    ____________(%%%%%%%)____________
May 03 07:30:17 swarm bee[169480]:   (     /   /  )%%%%%%%(  \   \     )
May 03 07:30:17 swarm bee[169480]:   (___/___/__/           \__\___\___)
May 03 07:30:17 swarm bee[169480]:      (     /  /(%%%%%%%)\  \     )
May 03 07:30:17 swarm bee[169480]:       (__/___/ (%%%%%%%) \___\__)
May 03 07:30:17 swarm bee[169480]:               /(       )\
May 03 07:30:17 swarm bee[169480]:             /   (%%%%%)   \
May 03 07:30:17 swarm bee[169480]:                  (%%%)
May 03 07:30:17 swarm bee[169480]:                    !
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="version: 0.5.3-acbd0e2"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="using swarm network address through clef: 261c85f1bfc2522ecb0d650ddba1207bc04fe5347673a56aa099251ec47e7ad1"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="swarm public key 037d08070506bf61e9c207e008c8e4ff14569c767be085a3ac9b687a2ccf30fae6"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=debug msg="using existing libp2p key"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=debug msg="using existing pss key"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="pss public key 0331c8ca4586df7fa83327fbbaf74a07bebb5416df81dbda160bfb6315adc13419"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="using ethereum address 97aec29e61919d3a31b9793373df5010234d17ea"
May 03 07:30:17 swarm bee[169480]: time="2021-05-03T07:30:17+08:00" level=info msg="debug api address: 127.0.0.1:1635"
May 03 07:30:17 swarm bee[169480]: Error: overlay address changed. was d8b25348fdd27dcd1b01daee56930f799e6277486dfcde8c4077fb02d29fa233 before but now is 261c85f1bfc2522ecb0d650ddba1207bc04fe5347673a56aa099251ec47e7ad1
May 03 07:30:17 swarm systemd[1]: bee.service: Main process exited, code=exited, status=1/FAILURE
May 03 07:30:17 swarm systemd[1]: bee.service: Failed with result 'exit-code'.
[bee.yaml.txt](https://github.com/ethersphere/bee/files/6412445/bee.yaml.txt)

**Comment by ldeffenb** [comment]
You probably changed the clef-signer-enabled value after the node was initialized.  Change it back and all should be fine.

**Comment by moonfunjohn** [comment]
Change clef-signer-enabled value does not help.

After I installed bee client 0.5.3. I just changed

nat-addr: "47.243.52.72" 
network-id: 5 

in bee.yaml

**Comment by acud** [comment]
when you start the node once an overlay address gets generated using the network ID (there's a default fallback value). Once you change the value and start the node again the network ID change will cause the overlay address to change too. 

Due to accounting restrictions we don't allow different overlays with the same underlying accounting database at this point. 

To get around this you'll have to either change the network ID or delete the `statestore` directory of your node.

**Comment by rairyx** [comment]
Can the node delete the statestore or generate a new one automatically in this case?

**Comment by Eknir** [comment]
> Can the node delete the statestore or generate a new one automatically in this case?

In your case that might be preferred, but in others, deleting the statestore may be not a great idea (e.g. when you have already accumulated a lot of income on one address).

For now, you will just have to delete the statestore manually.
