### ISSUE TITLE
Single Owner Chunks

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#164]
## Story
As a Swarm user, I want to upload chunks which address is based on my address and an identifier, such that a partition of the Swarm address space is uniquely identified as mine and I can create the illusion of mutable content.

## Background
- See BOS (2.2.3)
- Single-owner-chunks are an abstraction over feeds.

**Comment by acud** [comment]
done

**Comment by acud** [comment]
pending documentation cc @Eknir

**Comment by acud** [comment]
@eknir i'm closing this
