### ISSUE TITLE
pushsync: preemptive retry

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1640]
`pushsync` should do a preemptive retry in the same way that we retry in retrieval protocol.
Today, a sequencial retry would is done in the following manner:
```
t0                  t1                   t2
|--------------------|--------------------|
send(A)        send(b)           send(c)
```
The node will attempt to send to peer `A` at `t0`, then would time out at `t1` and immediately try another peer `B`, expire again and try another peer `C` immediately.

Instead, individual sends should not time out, and different in-flight requests should be raced, with preemptive sends being done at intervals:
```
t0         t0'        t1                  t2
|----------|---------|--------------------|
send(A)   
           send(B)
                   senc(C)
```
Ideally, we should allow a node a reasonable time to reply to a request. If a node or a trace might appear to be slow, we should try a different trace, while still allowing the old request to still return a response (race the requests). Even when the chunk is successfully synced, the streams must remain open so that correct accounting be done for the services rendered over the network.

**Comment by ldeffenb** [comment]
And who pays the proverbial piper when multiple raced requests actually succeed?  It would seem that the node that did the parallel requests would end up paying multiple times but only being paid himself once for the incoming request.  This was already observed in 0.6.0 and documented in #1650

**Comment by aloknerurkar** [comment]
We have decided to go in a different direction here. Preemptive retries will make accounting too complicated. So we will not be implementing it.

Instead, we plan to implement #1653 to improve selection criteria for peers and mitigate failures.

Closing this for now.
