### ISSUE TITLE
pushsync: perform accounting whenever services are rendered

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1641]
Accounting in pushsync should always occur whenever a service can be rendered. A node may choose to send a chunk and go away so that accounting may not happen, however the downstream peer should always perform accounting whenever the service has been supplied. Whether the node can consume the service is at the discretion of the upstream node operator but should not matter to the downstream peer.

**Comment by Eknir** [comment]
This has the intended side-effect that a node who frequently does not pay for services will be disconnected.

**Comment by aloknerurkar** [comment]
This will be addressed by #1695

We can close this. Changes can be tracked using the above issue.
