### ISSUE TITLE
kademlia: connect to multiple peers simultaneously while building up topology

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1642]
currently, kademlia dials to a single peer every time separately and moves between bins and peers every time such a connection attempt has been concluded.

This makes the process of building a topology very slow, especially if the address book has stale entries or entries of many nodes which are unreachable.

In order to speed up building a topology, we should collect multiple node addresses within the manage loop and connect to them simultaneously.

**Comment by ldeffenb** [comment]
That is actually the next thing I was going to experiment with in my 0.5.3 hacked version!  I looked at the "inflight" approach in pusher.go, but was still working out how to manage the concurrency of updating knownPeers and connectedPeers from the parallel connection attempts in kademlia.go's manageC (IIRC) outbound connection loop...
