### ISSUE TITLE
kademlia: bootnodes should accept new nodes and kick away old ones

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1646]
right now kademlia accepts all incoming connections as a bootnode. this makes the bootnodes hyper-connected but it is not a reasonable model going forward.

we should accept a node's connection and send it peers, then kick away the node and allow it to connect to other peers in the network. the peer can always come back to the bootnode for more peers and will even do so with the current implementation.

The solution is that we keep a max count of peers per bin for the bootnodes, and when a new connection comes in for a bin that's full, we disconnect from a random peer from that bin.

**Comment by ldeffenb** [comment]
But if we kick them all away, who's going to gossip new peers to us?  But then again, I guess every new peer will have to reach out to the boot node at least once, so we would have that one chance to know about it?  I'd have to do more thinking on this one having never actually run a boot node...

**Comment by acud** [comment]
the idea is to keep connectivity to a certain degree which does not favor one type of peer over another so that the bootnode cannot be hijacked. it will keep connections but once it reaches a limit it will start disconnecting random peers until it is within a certain threshold once more. since we don't gossip about peers we are not connected to, we muse maintain connectivity to a certain degree but it should be bounded.

**Comment by ldeffenb** [comment]
I didn't infer the "keep them up to a limit" when I read "accept..., send..., kick away the node".

**Comment by Eknir** [comment]
A bootnode is just an entrypoint to the network. Peer gossiping is done by all nodes. A bootnode is more a type of configuration which allows to run bootnodes effectively (and we do so, for the default-provided bootnodes). In theory, you would not even need such nodes, as long as a new entrant to the network can make at least one connection (can be a friend) he/she should be fine. 
If the bootnodes were essential, that would be a problem for the censorship resistance of Swarm.
