### ISSUE TITLE
0.6.0 Credits 3 peers for every 1 peer Debited?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1650]
#### Summary
I noticed that my new 0.6.0 peer was running 3* outbound balance for every 1* inbound balance.  And no files were uploaded nor download via this new node.  Every pushsync-received chunk has this pattern, regardless of whether or not a return receipt was successfully read from the downstream peers.

time="2021-05-03T17:53:33Z" level=error msg="pushsync: chunk 17843c7eef1b400b3047d93ab142bba687912fff170d9f08113583920b2fcc32 receive receipt from peer 1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066: stream reset"
time="2021-05-03T17:53:33Z" level=error msg="pushsync: chunk 17843c7eef1b400b3047d93ab142bba687912fff170d9f08113583920b2fcc32 receive receipt from peer 18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341: stream reset"
time="2021-05-03T17:53:33Z" level=error msg="pushsync: chunk 17843c7eef1b400b3047d93ab142bba687912fff170d9f08113583920b2fcc32 receive receipt from peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6: stream reset"
time="2021-05-03T17:53:33Z" level=trace msg="debiting peer a1940b1df17c5a22396fd92b2658872addab1cfcd182a4e6f292b20019c0ba62 with price 29000000000, new balance is 29000000000"
time="2021-05-03T17:53:33Z" level=trace msg="crediting peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6 with price 29000000000, new balance is -1369000000000"
time="2021-05-03T17:53:33Z" level=trace msg="crediting peer 18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341 with price 28000000000, new balance is -2188000000000"
time="2021-05-03T17:53:33Z" level=trace msg="crediting peer 1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066 with price 28000000000, new balance is -2228000000000"

time="2021-05-03T18:29:40Z" level=error msg="pushsync: chunk 1885f8b0531ea51dca617679bfd4acd71777937e8a128517665df953f2f8bd68 receive receipt from peer 18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341: stream reset"
time="2021-05-03T18:29:40Z" level=error msg="pushsync: chunk 1885f8b0531ea51dca617679bfd4acd71777937e8a128517665df953f2f8bd68 receive receipt from peer 1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066: stream reset"
time="2021-05-03T18:29:40Z" level=error msg="pushsync: chunk 1885f8b0531ea51dca617679bfd4acd71777937e8a128517665df953f2f8bd68 receive receipt from peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6: stream reset"
time="2021-05-03T18:29:40Z" level=trace msg="debiting peer a1940b1df17c5a22396fd92b2658872addab1cfcd182a4e6f292b20019c0ba62 with price 29000000000, new balance is 58000000000"
time="2021-05-03T18:29:40Z" level=trace msg="crediting peer 1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066 with price 27000000000, new balance is -2255000000000"
time="2021-05-03T18:29:40Z" level=trace msg="crediting peer 18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341 with price 23000000000, new balance is -2211000000000"
time="2021-05-03T18:29:40Z" level=trace msg="crediting peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6 with price 29000000000, new balance is -1398000000000"

time="2021-05-03T18:29:49Z" level=error msg="pushsync: chunk 0e143738c0d818603b4b038c2215ceeef01ccaa641faa336cf14b6668a915310 receive receipt from peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6: stream reset"
time="2021-05-03T18:29:49Z" level=trace msg="debiting peer a1940b1df17c5a22396fd92b2658872addab1cfcd182a4e6f292b20019c0ba62 with price 28000000000, new balance is 86000000000"
time="2021-05-03T18:29:49Z" level=trace msg="crediting peer 1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066 with price 29000000000, new balance is -2284000000000"
time="2021-05-03T18:29:49Z" level=trace msg="crediting peer 18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341 with price 29000000000, new balance is -2240000000000"
time="2021-05-03T18:29:49Z" level=trace msg="crediting peer 069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6 with price 28000000000, new balance is -1426000000000"

#### Steps to reproduce
Fire up a new clean node and wait for a chunk to arrive via pushsync.  Then look at your /balances and your --verbosity 5 (trace) logs.

#### Expected behavior
At most I would expect at most a single credit for one downstream peer for each debit of an upstream peer.  At this rate, it would guarantee every node operator to lose BZZ tokens into the swarm!

#### Actual behavior
See logs above.

The full log is available at:

https://ipfs.io/ipfs/QmUUtrDXjRinPamWeR65taq9DPAoL15deCuAf3yo92EKEc?filename=bee6-0.out

/balances output:
{
  "balances": [
    {
      "peer": "069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6",
      "balance": -2786000000000
    },
    {
      "peer": "18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341",
      "balance": -3563000000000
    },
    {
      "peer": "1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066",
      "balance": -3599000000000
    },
    {
      "peer": "8ec163755407cbae8a6fa56b48cf645009c86a6299d94a202d0e43b48fcb64fc",
      "balance": 1447000000000
    },
    {
      "peer": "a1940b1df17c5a22396fd92b2658872addab1cfcd182a4e6f292b20019c0ba62",
      "balance": 1446000000000
    }
  ]
}

/settlements output (definitely losing gBZZ on this node.  3.034/1.000 sent vs received!)
{
  "totalreceived": 8871000000000,
  "totalsent":      26920000000000,
  "settlements": [
    {
      "peer": "1f8812c5af5bd4442ae6a407da2af4b1144c6a0a3f93cdb82d850c34365e7066",
      "received": 0,
      "sent": 8982000000000
    },
    {
      "peer": "18dc8ed96c0dd6bd70bb5994a804eb12c7e8c124e44232a44b34bfcd5264f341",
      "received": 0,
      "sent": 8960000000000
    },
    {
      "peer": "069f988f229a426cb1169bc8c1589d9668789246fa95216e64ae6323f78571b6",
      "received": 0,
      "sent": 8978000000000
    },
    {
      "peer": "8ec163755407cbae8a6fa56b48cf645009c86a6299d94a202d0e43b48fcb64fc",
      "received": 8871000000000,
      "sent": 0
    }
  ]
}

**Comment by Eknir** [comment]
This is explained by #1640 . In the newest Bee, Bee nodes still pay for forwarding requests. This will be updated, such that only originating nodes pay, such that a forwarder won't make a loss on such preemptive retries.
