### ISSUE TITLE
0.6.0 Retries pushsync w/Stream Reset

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1651]
#### Summary
0.6.0 seems to still have issues with getting lots of errors on pushsync causing a lot of retries on certain chunks.  The original pusher must still have this chunk in its push index.

Look for chunk 35de02646baa77e6385ef6d0c6997c33d9425987659d8b6bc778b05bab614323 in my node's --verbosity 5 logs at:

https://ipfs.io/ipfs/QmUUtrDXjRinPamWeR65taq9DPAoL15deCuAf3yo92EKEc?filename=bee6-0.out

between 18:29:54Z and 21:1417Z

#### Steps to reproduce
Just fire up a node and capture the --verbosity 5 logs until some unfortunate chunk comes along looking for a neighborhood to land in.

#### Expected behavior
Some node "close" to the neighborhood should just adopt and keep the chunk so that the pushes quit clogging up the network.

#### Actual behavior
EverReady bunny effect:  It keeps pushing and pushing and pushing...

**Comment by Eknir** [comment]
This is supposed to be fixed,, as part of #1680 . It would be great if you could validate that once v0.6.1 is out! 

As always, I'll be happy to hear your findings in this issue.

Thanks!

**Comment by bumbleshrimp** [comment]
@Eknir I, too am having problems with this on the latest master, though I had the same problems on 0.6.0 and 0.6.1 as well. I've tried uploading a file 5 times across 3 nodes and have never gotten it to succeed.  Not sure if you want to reopen this or have me create a new issue.

Current version is `0.6.2-4d918bf3`

Logs/metrics:
node 2 metrics: https://ipfs.io/ipfs/QmNUvdpT2uNyViqd9ZyivAFMTk8skA2NosivRvJtLru9co?filename=bee-2-metrics.txt
node 2 logs: https://ipfs.io/ipfs/QmTNrBJSynRM9uNJjgJ7dj362TbVA3AUp391UmY4ayaTVb?filename=bee-2-upload-log.txt

node 3 metrics: https://ipfs.io/ipfs/QmQkrCWynucdwX7nDnRQ6dDajahtHkFcqCX8NBejzEiCA9?filename=bee-3-metrics.txt
node 3 logs: https://ipfs.io/ipfs/QmVrxZLPN94p7DTJp3azGFRF4uBcXeyaKLxCF4g67ryTmu?filename=bee-3-upload-log.txt

**Comment by esadakar** [comment]
@bumbleshrimp Can you share the postage amount and batch depth you used to create your postage batch for your uploads?

**Comment by grivasjon** [comment]
> @bumbleshrimp @ldeffenb Can you share the postage amount and batch depth you used to create your postage batch for your uploads?

I used the recommended /100/20 - the files I upload are all in the 4-8MB range.

**Comment by bumbleshrimp** [comment]
@esadakar I used a depth of 20 and postage amount of 100.  I thought maybe it was a stamp problem so I tried re-uploading the exact same file (with same resulting manifest reference) from other nodes and, while none of the uploads ever finished syncing all chunks, the file did eventually get completed between the 5 separate attempts.

**Comment by bumbleshrimp** [comment]
It should also be noted I had this exact same problem in 0.5.3 for weeks as well, I never managed to get larger files to succeed in uploading. I was able to upload a 20GB video though by converting it to HLS with a few thousand very small segments.
