### ISSUE TITLE
kademlia: prune oversaturated bins when depth increases

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1652]
Kademlia will always try to connect to known peers within depth.
This creates a problem when depth increases, since some bins which would now be outside of depth will be oversaturated more than they should be.

Once depth changes, we should therefore sweep through all bins which are outside of depth and clean up random nodes in order to shrink the bins into the acceptable upper bound

**Comment by Eknir** [comment]
This has the 'in progress' label. Is this being actively worked on, already completed?
