### ISSUE TITLE
pushsync: remember failed traces

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#1653]
This is a suggestion for improvement of pushsync using a small LRU cache of chunk addresses associated with peer addresses which have failed to deliver a receipt. 

This can be used to improve our retry logic by not retrying (or at least keeping to a minimum) the amount of times we retry the same peer with the same chunk.

We can use an off-the-shelf LRU cache (like the one from [hashicorp](https://github.com/hashicorp/golang-lru)) and just blindly insert into it when a chunk address errors on a peer address, then, when forwarding to a peer, we check if that chunk address produced an error from this peer in the past (LRU size should be small enough so that the set just expunges old entries relatively quickly), and if so, we try the next peer in the list which is not sanctioned.

Let's have some feedback on this @metacertain @zelig. I'm not sure how this will behave inside the neighborhood. We need a way to still answer a request once it lands in the NN and not repeatedly block on the same peer (which might be malicious behavior to create denial of service over the network). This can be expanded into remembering number of attempts done per peer, and once a maximum amount of attempts have been made per peer, we try another.

**Comment by ldeffenb** [comment]
I actually have this implemented in the myhacks branch of my fork of bee 0.5.3.  Works quite well, in actual fact.  In my case, if I fail all 5 peers repeatedly over 5 minutes, I just decide to keep the chunk myself.
