### ISSUE TITLE
cannot receive faucet balance

### ISSUE THREAD

**Issue by zq112288** [ethersphere/bee#1664]
the instruction "curl -s localhost:1635/addresses | jq .ethereum" output:
"0x7f866b29035349c147980a961ccf918042514282"

but when i enter the address "0x7f866b29035349c147980a961ccf918042514282" in this web https://faucet.ethswarm.org/.  nothing happens.  the address "0x7f866b29035349c147980a961ccf918042514282" receives no G-eth. there is no transaction shown in the web https://goerli.etherscan.io/address/0x7f866b29035349c147980a961ccf918042514282.

**Comment by honeway** [comment]
@zq112288 How did you resolve the issue? I found some transactions in your given link.

**Comment by honeway** [comment]
I got same issue. When I enter "0xf0ea5815b0e82fae1aa5d8dc002987bdb456ee94" in https://faucet.ethswarm.org/, nothing happened.

**Comment by opezss** [comment]
I had the same problem , trouble helping out

**Comment by Eknir** [comment]
Best to join our Discord server (https://discord.gg/QpVwzJ3JKj) and requests funds in the #faucet channel!
