### ISSUE TITLE
pushsync: receive receipt deadline filed

### ISSUE THREAD

**Issue by zeoio** [ethersphere/bee#1669]
bee version: 0.5.3-acbd0e2

error info:

```
error msg="pushsync: chunk f726d53d6388fb23fc7ae83b99120a9dbb1acd4cef87346792ddcfaa80d14351 receive receipt from peer f72082d038e9d7c1935c1be4e6debaaa42f66234e201604afd4a2ea64f40011a: context deadline exceeded"
```

**Comment by honeway** [comment]
Same issue

**Comment by aloknerurkar** [comment]
#1662 Will try to address this in a way. We have increased the timeout duration for the pushsync protocol to allow more time for replication. Also, we have improved the retry logic in pushsync service to select more reliable peers during the retries.

**Comment by cppfuns** [comment]
How to solve this problem?

**Comment by Eknir** [comment]
Hi all,
Thanks for reporting the issue. Bee v0.6.0 is supposed to improve this. We are preparing a hotfix (bee v0.6.1). Once this is released, please try it out and report if it works!
