### ISSUE TITLE
pushsync: chunk  context deadline exceeded

### ISSUE THREAD

**Issue by prz23** [ethersphere/bee#1674]
#### Summary

bee_0.5.3_amd64

msg="pushsync: chunk 9c92ec957daece6fb92c5dffc30b8abc56f11803b80368ee0d25ba0606d34485 receive receipt from peer 9c930f5e59d190c46377e269568371e4c15147a5a70585668dd735e2d62b122b: context deadline exceeded"

**Comment by xizhouchen** [comment]
I have the same problerm. and the quantity of connected node never more than 53

**Comment by ldeffenb** [comment]
"Context deadline exceeded" means "timeout" and is normal.

**Comment by ldeffenb** [comment]
> I have the same problerm. and the quantity of connected node never more than 53

Receiving a receipt from a peer has nothing to do with your connected peer count.  Look at your topology.  If you have 4 or more peers connected in most of the lower-numbered (say <10) bins, your node is operating normally:

curl http://localhost:1635/topology | jq >output.txt

The output redirection is necessary as the output is quite large.

**Comment by xizhouchen** [comment]
> > I have the same problerm. and the quantity of connected node never more than 53
> 
> Receiving a receipt from a peer has nothing to do with your connected peer count. Look at your topology. If you have 4 or more peers connected in most of the lower-numbered (say <10) bins, your node is operating normally:
> 
> curl http://localhost:1635/topology | jq >output.txt
> 
> The output redirection is necessary as the output is quite large.

thanks for your answer. 

my node run two days ,but do not receive a cheque.
I have two question
1.  which factors can effect the cheque receiving.
2.  I get a lot of  "could not handle protocol pushsync/1.0.0 " error message in console. does it effect my node operation?

**Comment by regentropfenbinacs** [comment]
mark
