### ISSUE TITLE
Can multiple nodes share a private key

### ISSUE THREAD

**Issue by cqcwasd** [ethersphere/bee#1675]

**Comment by ldeffenb** [comment]
No.  The nonces will get all mixed up when the different nodes check out without synchronization.

**Comment by ldeffenb** [comment]
No, this is not possible.  The swarm key is the Ethereum account key and this is what needs to be unique for each node.  Otherwise the nodes will mess up their nonces and will not be able to interact with the blockchain.

**Comment by BinacsLee** [comment]
> No, this is not possible. The swarm key is the Ethereum account key and this is what needs to be unique for each node. Otherwise the nodes will mess up their nonces and will not be able to interact with the blockchain.

Got it, thanks a lot ^-^

**Comment by BinacsLee** [comment]
> Actually, I believe that if Bob attempts to join with a node with the same private key as Alice's node, then Alice will be eventually introduced to Bob as being in the same neighborhood at which point Bob's node should shut down with an error.

Considering that some good nodes may be attacked, is there a security risk?

**Comment by Eknir** [comment]
> Considering that some good nodes may be attacked, is there a security risk?

It is not possible to forge the same overlay address as another node, unless you know that nodes' private key.
