### ISSUE TITLE
bee started but check status was dead,how to handle ? SOS

### ISSUE THREAD

**Issue by maketigers** [ethersphere/bee#1676]
#### Summary
#systemctl status bee
● bee.service - Bee - Ethereum Swarm node
   Loaded: loaded (/usr/lib/systemd/system/bee.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.ethswarm.org

bee start with command line:
#bee start --verbosity 5 --swap-endpoint https://rpc.slock.it/goerli --debug-api-enable --clef-signer-enable --clef-signer-endpoint /var/lib/bee-clef/clef.ipc
after running command:#sudo systemctl start bee.service
and check bee status again
# systemctl status bee
● bee.service - Bee - Ethereum Swarm node
   Loaded: loaded (/usr/lib/systemd/system/bee.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2021-05-09 10:04:07 CST; 3s ago
     Docs: https://docs.ethswarm.org
  Process: 16109 ExecStart=/usr/bin/bee start --config /etc/bee/bee.yaml (code=exited, status=1/FAILURE)
 Main PID: 16109 (code=exited, status=1/FAILURE)

May 09 10:04:07 hecs-x-large-2-linux-20210506105547 systemd[1]: Unit bee.service entered failed state.
May 09 10:04:07 hecs-x-large-2-linux-20210506105547 systemd[1]: bee.service failed.
help ,please,thanks!!

# systemctl status bee-clef -l
● bee-clef.service - Bee Clef
   Loaded: loaded (/usr/lib/systemd/system/bee-clef.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2021-05-09 01:38:48 CST; 8h ago
     Docs: https://docs.ethswarm.org
 Main PID: 8558 (bash)
   CGroup: /system.slice/bee-clef.service
           ├─8558 bash /usr/bin/bee-clef-service start
           ├─8566 clef --stdio-ui --keystore /var/lib/bee-clef/keystore --configdir /var/lib/bee-clef --chainid 5 --rules /etc/bee-clef/rules.js --nousb --lightkdf --4bytedb-custom /etc/bee-clef/4byte.json --pcscdpath  --auditlog  --loglevel 3 --ipcpath /var/lib/bee-clef
           └─8567 tee /var/lib/bee-clef/stdout

May 09 01:38:49 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:38:49.299] Loaded 4byte database                    embeds=146841 locals=4 local=/etc/bee-clef/4byte.json
May 09 01:38:49 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: {"jsonrpc":"2.0","id":1,"method":"ui_onInputRequired","params":[{"title":"Master Password","prompt":"Please enter the password to decrypt the master seed","isPassword":true}]}
May 09 01:38:49 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: Waiting for the clef.ipc file to show up at /var/lib/bee-clef/clef.ipc
May 09 01:38:50 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:38:50.624] Rule engine configured                   file=/etc/bee-clef/rules.js
May 09 01:38:50 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:38:50.624] Starting signer                          chainid=5 keystore=/var/lib/bee-clef/keystore light-kdf=true advanced=false
May 09 01:38:50 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:38:50.624] IPC endpoint opened                      url=/var/lib/bee-clef/clef.ipc
May 09 01:38:50 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: {"jsonrpc":"2.0","method":"ui_onSignerStartup","params":[{"info":{"extapi_http":"n/a","extapi_ipc":"/var/lib/bee-clef/clef.ipc","extapi_version":"6.1.0","intapi_version":"7.0.1"}}]}
May 09 01:38:50 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: tee: /var/lib/bee-clef/stdout: Broken pipe
May 09 01:39:11 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:39:11.753] Op approved
May 09 01:39:11 hecs-x-large-2-linux-20210506105547 bee-clef-service[8558]: INFO [05-09|01:39:11.762] Op approved

======ENV==============
# bee version 0.5.3-acbd0e2
#clef version bee-clef_0.4.10_amd64.rpm
#centos LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core) 
Release:        7.6.1810
Codename:       Core

**Comment by ldeffenb** [comment]
So what does your bee log say:
journalctl -u bee -n 1000 -f

**Comment by maketigers** [comment]
> So what does your bee log say:
> journalctl -u bee -n 1000 -f

FYI
May 09 11:45:57 hecs-x-large-2-linux-20210506105547 systemd[1]: bee.service: main process exited, code=exited, status=1/FAILURE
May 09 11:45:57 hecs-x-large-2-linux-20210506105547 systemd[1]: Unit bee.service entered failed state.
May 09 11:45:57 hecs-x-large-2-linux-20210506105547 systemd[1]: bee.service failed.
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 systemd[1]: bee.service holdoff time over, scheduling restart.
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 systemd[1]: Stopped Bee - Ethereum Swarm node.
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 systemd[1]: Started Bee - Ethereum Swarm node.
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: \     /
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: \    o ^ o    /
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: \ (     ) /
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: ____________(%%%%%%%)____________
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: (     /   /  )%%%%%%%(  \   \     )
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: (___/___/__/           \__\___\___)
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: (     /  /(%%%%%%%)\  \     )
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: (__/___/ (%%%%%%%) \___\__)
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: /(       )\
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: /   (%%%%%)   \
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: (%%%)
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: !
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:02+08:00" level=info msg="version: 0.5.3-acbd0e2"
May 09 11:46:02 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:02+08:00" level=warning msg="failing to connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
May 09 11:46:07 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:07+08:00" level=warning msg="failing to connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
May 09 11:46:12 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:12+08:00" level=warning msg="failing to connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
May 09 11:46:17 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:17+08:00" level=warning msg="failing to connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
May 09 11:46:22 hecs-x-large-2-linux-20210506105547 bee[30247]: time="2021-05-09T11:46:22+08:00" level=warning msg="failing to connect to clef signer: dial unix /var/lib/bee-clef/clef.ipc: connect: permission denied"
