### ISSUE TITLE
bee-docker-compose

### ISSUE THREAD

**Issue by hesen2006cn** [ethersphere/bee#1677]
level=warning msg="failing to connect to clef signer: Post \"http://clef-1:8550\": dial tcp 172.18.0.2:8550: connect: connection refused"

**Comment by kernelogic** [comment]
Same for me

**Comment by mfw78** [comment]
This is a general support question. I strongly suspect incorrect copy / pasting when configuring `docker-compose`. If you have any questions surrounding this, please kindly direct them to Discord.
