### ISSUE TITLE
docker   connect new stream: incompatible stream: protocol not

### ISSUE THREAD

**Issue by hackren** [ethersphere/bee#1678]
[2021-05-09T18:49:37Z] connect to bootnode /ip4/54.167.196.243/tcp/31305/p2p
/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd                          
DEBU[2021-05-09T18:49:37Z] discover fail /dnsaddr/bootnode.ethswarm.org: discove
r /dnsaddr/swarm-2.bootnode.ethswarm.org: discover /dnsaddr/bee-5.bootnode.ethsw
arm.org: discover /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuA
aJ3ZSw5hovsepXjF859wDZ6bd: connect new stream: incompatible stream: protocol not
 supported

**Comment by acud** [comment]
latest master is not compatible with the existing testnet. please use either `beta` tag or `0.5.3`
