### ISSUE TITLE
Error: chequebook init: insufficient BZZ for initial deposit

### ISSUE THREAD

**Issue by GoGOGORS** [ethersphere/bee#1681]
I can't get Geth and GBZZ from Swarm Goerli Faucet. I in this website https://faucet.ethswarm.org/ click no reaction after fill in the address.
This is my address 0xb08c098300671d3a2793edd0462e00a8af35b42c.
Can you tell me what I should do?
please.
![image](https://user-images.githubusercontent.com/41220758/117649314-f4df2000-b1c1-11eb-8f6d-b7307e8b7f93.png)

**Comment by Eknir** [comment]
We are happy to help you in our [Discord](https://discord.gg/A6SBuEaK)

It looks as if the faucet was down. The official faucet is also in our Discord
