### ISSUE TITLE
0.6.0 - POST /stamps/{amount}/{depth} checking wrong account?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1687]
#### Summary
I tried to do a simple, very cheap, stamp and got:
curl -X POST http://192.168.10.18:1633/stamps/1/17
{"message":"out of funds","code":400}

But curl http://192.168.10.18:1635/chequebook/balance
{"totalBalance":100000000000000000,"availableBalance":99973080000000000}

So I added a logger to pkg/postage\postagecontract/contract.go's CreateBatch and found:
CreateBatch:initial=1 depth=17 total=131072 balance=100000000000000000 owner=0xC39492264bF8e44a85F4017Ec7Ae8C6161C95d0c

But wait, 0xC394....5d0c is my Ethereum address!  Shouldn't it be looking for the token balance in my checkbook address?

Or do postage stamps require gBZZ tokens on the Ethereum address to be purchased?

#### Steps to reproduce
Have a node whose Ethereum address has zero gBZZ balance, as most of our nodes are running.  And try to buy the minimum (and probably useless) postage stamp with:

curl -X POST http://192.168.10.18:1633/stamps/1/17

#### Expected behavior
I expected the tokens to come from my checkbook contract which is where, up until now, we have held all gBZZ.

#### Actual behavior
It required gBZZ to be on my Ethereum address.

Once I sprinkled new gBZZ onto my Ethereum address, the purchase was successful, albeit with a probably uselessly cheap batch.

curl -X POST http://192.168.10.18:1633/stamps/1/17
{"batchID":"42229d2c66ba3310bff655ea1b384bbd26a1b9913777ac252f524d2cf08a501d"}

**Comment by AuHau** [comment]
Funding creation of stamps to my understanding indeed comes from the Ethereum account associated with the node. 

With the addition of the Stamps system there are two incentive systems in Bee which operate independently and with a different purpose. Chequebook is meant to incentivize the usage of bandwidth, while the stamps are currently mainly spam protection, but in the future might fund long-term storage incentivization.

So yes, this is not a bug but a feature ;-) When you are creating a new stamp it actually creates a new transaction using an independent Stamp Factory contract and hence the funds are coming for the Ethereum account.

But I agree that the communication around this is still not the most polished. For example configuration parameters are mainly pointing to the "swap" (for example `--swap-endpoint`) while now these things are more generic.

**Comment by ldeffenb** [comment]
> But I agree that the communication around this is still not the most polished.

Can you provide ANY links that describe the stamp functionality?  I'm still trying to determine appropriate values for /stamps/{amount}/{depth}.  I know the depth has to be greater than 16.  And the cost of the stamp is amount*2^(depth-16), but I have no idea yet how much stamp to purchase for any given file size and anticipated retention period.

**Comment by AuHau** [comment]
> I'm still trying to determine appropriate values for /stamps/{amount}/{depth}.

Well, this is also one of my questions for the Bee devs. Honestly, I was mainly digging in code to get a better understanding of the functionality. One piece of code that I found relevant to this is from `beekeeper`:

https://github.com/ethersphere/beekeeper/blob/789db0569c51459210e8ffb18f01332e1fda39ce/pkg/bee/postage.go#L11

>  I have no idea yet how much stamp to purchase for any given file size and anticipated retention period.

Be aware! Stamps currently do not give you the guarantee of a "retention period". It mainly works as signaling to the nodes "how much you value the data" and based on that they select what to GC. To my understanding, currently, the BZZ put into the stamps is actually burned and does not go to the storrer node, but only prevents bad actors from spamming the network.

**Comment by Eknir** [comment]
@ldeffenb , this is expected behavior. We provide an update documentation with the v0.6.0. release that will hopefully address all your questions.

Thanks for inspecting v0.6.0!
