### ISSUE TITLE
0.6.0 Buy stamp batch documentation wrong

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#1688]
#### Summary
https://deploy-preview-174--vibrant-sinoussi-1c9314.netlify.app/api/#tag/Buy-stamp-batch says that "Buy stamp batch" is a GET.  It should be a POST.

#### Steps to reproduce
Just look at the page.

#### Expected behavior
Since it spends money and changes state, it should be a POST, and in fact, is implemented as a POST.

#### Actual behavior
GET on /stamps/n/m fails.

**Comment by AuHau** [comment]
Yeah, also run into this. There are unfortunately more problems with the docs.

For example the header that is now required for all uploads of everything `swarm-postage-batch-id` is not present in the OpenAPI at all. Also a note. PSS sending messages also require Stamp assigned (I did not think of it first).

Also I believe that the stamp endpoints should be grouped under one "section" in the OpenAPI. Something like "Stamps".

If nobody will take it upon himself to fix these, I will do it once I have 0.6.0 support in `bee-js` ready.

**Comment by AuHau** [comment]
Resolved with #1738
