### ISSUE TITLE
TX polling times and confirmations should be configurable

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee#1700]
### Issue statement
When working with the postage stamps locally (and in CI), some of the values intended for testnet/mainnet do not make sense and slow down the development. Currently in our setup we have a blockchain with 1 second block time but still it takes 30 seconds to create postage stamps.

### Proposed resolution
Make the constants that are in the code configurable. In this case that would be:
- postage stamps block confirmations (hardcoded to 4 blocks) https://github.com/ethersphere/bee/blob/84f54d73e165d5c16246a95802e59e51b7a523a7/pkg/postage/listener/listener.go#L29
- chain update interval (hardcoded to 5 seconds) https://github.com/ethersphere/bee/blob/84f54d73e165d5c16246a95802e59e51b7a523a7/pkg/postage/listener/listener.go#L33
- polling interval (hardcoded to 30 seconds) https://github.com/ethersphere/bee/blob/84f54d73e165d5c16246a95802e59e51b7a523a7/pkg/node/chain.go#L28

**Comment by Eknir** [comment]
Thanks. A while ago, but we'll dust away the dust on this issue ;). This is still relevant, right?

**Comment by acud** [comment]
they are hardcoded for a reason (we don't want users to mess around with the values). 30 seconds is also not eternity in CI terms. How many stamps are you creating? can't you reuse stamps between tests?

**Comment by acud** [comment]
@vojtechsimetka this is now made possible with https://github.com/ethersphere/bee/pull/2641.
