### ISSUE TITLE
peer not reachable when attempting to connect

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#1703]
INFO[2021-05-13T19:16:28+08:00] attempting to connect to peer 7d660d4c6d6bb28ac51cd7027087aec939307a3014f78645b8c4bdeacbadc22f 
WARN[2021-05-13T19:16:28+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:28+08:00] attempting to connect to peer 7d6515324547316f97b75771a518beec1d027ed0fbc52dae843279b6f23968df 
WARN[2021-05-13T19:16:33+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:33+08:00] attempting to connect to peer 7d5db0ff842bcf58cbd31886af7bede6f84e77991d447d2655ca4158e76653b7 
WARN[2021-05-13T19:16:38+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:38+08:00] attempting to connect to peer 7d45da1a04e573b96be9496a014f943d40696a23feff8891782faac26f9d368c 
WARN[2021-05-13T19:16:40+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:40+08:00] attempting to connect to peer 7d44c0272ad0c101dbdf7eac31df511bd3c0970fae8f2d5dea2eaaf8438a8699 
WARN[2021-05-13T19:16:45+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:45+08:00] attempting to connect to peer 7d393fa10997664861206948f8ad66a1c3e2ab24254f95a9a92369686c348aad 
WARN[2021-05-13T19:16:50+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:50+08:00] attempting to connect to peer 7d2f3f3554e732c64bf11306097ebf395d2998be43807171f3bf412c3c3506e2 
WARN[2021-05-13T19:16:55+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:55+08:00] attempting to connect to peer 7d2c5009a910fd6c24b546a6c72d559c3dc8fff98222672d440d47b1f972bb38 
WARN[2021-05-13T19:16:55+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:16:55+08:00] attempting to connect to peer 7d27383ad7486005e4d7614c4faae276ddbed681079396efc2940570b91636ba 
WARN[2021-05-13T19:17:00+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:00+08:00] attempting to connect to peer 7d2436240b0f2266fff7fbf66b8368d11eceb3e75d8fc21c18e00e3c565f34d8 
WARN[2021-05-13T19:17:03+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:03+08:00] attempting to connect to peer 7d240ccb05e218c1675f95e38d23e7100751ff3c9774be58a021781d8a15d33e 
WARN[2021-05-13T19:17:08+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:08+08:00] attempting to connect to peer 7d151d9a7d9be981c96f198bc6355c011ecaf6eaa3a362763e425cd74e78fa2d 
WARN[2021-05-13T19:17:08+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:08+08:00] attempting to connect to peer 7d0cc43b266975449fa358441bd57612a435bdb6a412284272d8b8506a28b284 
WARN[2021-05-13T19:17:08+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:08+08:00] attempting to connect to peer 7cf5e6150574e5b94ffcd6de7acb9ba7cb01111efbb11e419ec1cdfa96f92e59 
WARN[2021-05-13T19:17:13+08:00] peer not reachable when attempting to connect 
INFO[2021-05-13T19:17:13+08:00] attempting to connect to peer 7cf403fb1ba7347cccb39bcdecdd3e5ebdf82503f715b900d8d6aa74feb22bf1

**Comment by a20131549** [comment]
我也遇到这个问题

**Comment by a20131549** [comment]
怎么处理

**Comment by sk911911** [comment]
time="2021-06-10T09:12:49+08:00" level=debug msg="kademlia: disconnected peer 1495a24d80abdf53ea3eabde0bdd5cd2b0b4228bc9d280cd9b1ccfe37817a6c8"
time="2021-06-10T09:12:49+08:00" level=debug msg="kademlia: disconnected peer 15f4e5d7e6290772af563f6a7ec943c334ec056a3dc77812f40086b71605d806"
time="2021-06-10T09:12:50+08:00" level=debug msg="kademlia pruned peer from address book \"714131b92f642c81cb7909c6d9b014a913304cb7bdd4572f902fcd6e3d98e001\""
time="2021-06-10T09:12:50+08:00" level=info msg="kademlia shutting down"
time="2021-06-10T09:12:50+08:00" level=debug msg="kademlia: peer not reachable from kademlia \"[Underlay: /ip4/111.0.38.161/tcp/27061/p2p/16Uiu2HAmVFWzPazoQhrGmJn7jybpaM6K7x49MHLdYkrFaBmA5kEw, Overlay 714131b92f642c81cb7909c6d9b014a913304cb7bdd4572f902fcd6e3d98e001, Signature 8b4713c712ae3ad560b107a800c4d16c2f577ae5adeeab5063f02efc5ee571fd207e5b569359a58c4ca77fe4759a4304d9260b0cd1faaa7884cc2f4a64835a6e1c]\": handshake: read synack message: stream reset"
time="2021-06-10T09:12:50+08:00" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-10T09:12:50+08:00" level=trace msg="kademlia: connector took 4.4585905s to finish: old depth 14; new depth 0"
time="2021-06-10T09:12:50+08:00" level=debug msg="kademlia manage loop exited"
time="2021-06-10T09:12:50+08:00" level=info msg="kademlia persisting peer metrics"



then  the cmd closed automaticly.......... why?

**Comment by ldeffenb** [comment]
Get a more stable connection to your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.

This is not a bug and please ask for support in the #bee-support channel of the Discord server.
