### ISSUE TITLE
Migration of pinned content to v0.6.0

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1707]
# User story

## Story

As a pinner of content, I don't want that my pinned content is automatically wiped when updating to v0.6.0, such that I don't accidentally delete my pinned content without the possibility to recover

## Acceptance criteria

- When updating from v0.5.3 to v0.6.0 pinned content should not be deleted without explicit user consent
## Background

Database schemes between v0.5.3 and v0.6.0 are not compatible due to the introduction of postage stamps. A migration of all non-pinned content would only be possible if everybody would manually stamp all chunks in their storage. We cannot reasonably expect this to happen. A node operator who pins content should at least be ensured that that content is safe.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by acud** [comment]
already done
