### ISSUE TITLE
429 Too Many Requests    

### ISSUE THREAD

**Issue by liuweisir** [ethersphere/bee#1718]
`time="2021-05-15T10:30:40+08:00" level=info msg="version: 0.5.3-acbd0e2"
Password:
time="2021-05-15T10:30:52+08:00" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
time="2021-05-15T10:30:53+08:00" level=info msg="using existing swarm network address: 1be8e49c4bec1076cbb2f79d657b04e6a8f24d253ac96f73aa7b42623e7d6acc"
time="2021-05-15T10:30:53+08:00" level=info msg="swarm public key 0378353bdd92ad39bbfb4cf64abb8f470b8a45bdffa3fe30e10e59cbfd71acfbe8"
time="2021-05-15T10:30:53+08:00" level=debug msg="using existing libp2p key"
time="2021-05-15T10:30:53+08:00" level=debug msg="using existing pss key"
time="2021-05-15T10:30:53+08:00" level=info msg="pss public key 02296ec071f4bb2a3c0a381c18cad69e715582d535969d397c08ec73e5848e9fcc"
time="2021-05-15T10:30:53+08:00" level=info msg="using ethereum address 1e0388b51aa9bcd7c0cd5b49e845a529ffb81513"
time="2021-05-15T10:30:53+08:00" level=info msg="debug api address: [::]:1635"
time="2021-05-15T10:30:55+08:00" level=info msg="using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474"
time="2021-05-15T10:30:57+08:00" level=info msg="no chequebook found, deploying new one."
time="2021-05-15T10:30:58+08:00" level=warning msg="cannot continue until there is at least 10 BZZ available on 1e0388b51aa9bcd7c0cd5b49e845a529ffb81513"
time="2021-05-15T10:30:58+08:00" level=warning msg="get your Goerli ETH and Goerli BZZ now via the bzzaar at https://bzz.ethswarm.org/?transaction=buy&amount=10&slippage=30&receiver=0x1e0388b51aa9bcd7c0cd5b49e845a529ffb81513"
Error: chequebook init: 429 Too Many Requests: <html><body><h1>429 Too Many Requests</h1>
You have sent too many requests in a given amount of time.
</body></html>`

**Comment by flybobdog** [comment]
I get the same problem.Can anybody help me?

**Comment by ldeffenb** [comment]
It sounds like you're using a free account from infura.io as your swap-endpoint.  Those accounts are limited in the number of API calls you can make per day.  Log on to your account and look at your dashboard to see if that is your issue.

If you are running multiple nodes, or are using cashout.sh on very frequently, even just to query, you would be better off running your own local goerli node.  Even a light node will support your bee nodes as a swap-endpoint.

**Comment by Eknir** [comment]
Thanks for trying out bee! @ldeffenb gives you correct advice. Please join our Discord for support! https://discord.gg/sU8NEtaR8y
