### ISSUE TITLE
Does the program have a malicious backdoor?

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#1719]
The contract address of my account [0x8C048c1c4e2F2675fe194b4b730871e0A360e38c](0x8C048c1c4e2F2675fe194b4b730871e0A360e38c) created by SimpleSwapDeployed should be [0x6f57d2fd4593a19c58f281d4cd9997b1984ef229](https://goerli.etherscan.io/tx/0xa30634a5f66c682324c00c1130dd3df13794f62d96449b078d5ba45242203ba6)
, But why becomes 0xA07e2aa6B1fe65C38446885b5692CEfbaE5BB9D2? Check that this contract address was created by [0xd573e8f36925ad11c35c127daea934b085c6ca68](https://goerli.etherscan.io/tx/0x8f14b5f7054e8bb4b7686cf7146f2d67793bd1f16902ded11f210dd3a544ba2a)

https://goerli.etherscan.io/address/0x8C048c1c4e2F2675fe194b4b730871e0A360e38c
https://goerli.etherscan.io/tx/0xa30634a5f66c682324c00c1130dd3df13794f62d96449b078d5ba45242203ba6#eventlog

https://goerli.etherscan.io/tx/0x8f14b5f7054e8bb4b7686cf7146f2d67793bd1f16902ded11f210dd3a544ba2a

**Comment by cppfuns** [comment]
`curl localhost:1635/chequebook/balance | jq`
```
{
  "totalBalance": 1284000000000,
  "availableBalance": 1284000000000
}
```

**Comment by cppfuns** [comment]
View 0xd573e8f36925ad11c35c127daea934b085c6ca68 is just an ordinary account, why is there permission to create a contract for me?

https://goerli.etherscan.io/txs?a=0xd573e8f36925ad11c35c127daea934b085c6ca68
https://goerli.etherscan.io/tx/0x8f14b5f7054e8bb4b7686cf7146f2d67793bd1f16902ded11f210dd3a544ba2a#eventlog

**Comment by ralph-pichler** [comment]
this is bug in the current version of bee, where a node sometimes locks in on the wrong chequebook if there is blockchain reorganisation. this is fixed in the upcoming release.

**Comment by cppfuns** [comment]
> 这是蜜蜂当前版本中的错误，如果存在区块链重组，则节点有时会锁定错误的支票簿。在即将发布的版本中已修复此问题。
