### ISSUE TITLE
No balance

### ISSUE THREAD

**Issue by cjsliuj** [ethersphere/bee#1720]
My wallet had test eth:
![IMG_2298](https://user-images.githubusercontent.com/4098790/118365481-876f2d00-b5cf-11eb-8243-6e6b5dde0112.PNG)
But the bzz.ethswarm.org shows the wallet balance is zero. (I had clean browser cahce and re-scan the qrcode).
![image](https://user-images.githubusercontent.com/4098790/118365543-c604e780-b5cf-11eb-82b9-f990a144b16e.png)
There are other questions.After I click Get G-ETH.The address (minting to receiver) has no transaction information  at https://goerli.etherscan.io/

**Comment by Eknir** [comment]
This issue is stale, as the bzzaar is not anymore open on Goerli.
