### ISSUE TITLE
Could not connect to backend at https://rpc.slock.it/goerli. In a swap-enabled network a working blockchain node (for goerli network in production) is required. Check your node or specify another node using --swap-endpoint

### ISSUE THREAD

**Issue by zhuyunxiang** [ethersphere/bee#1721]
Is there any other public swap-endpoint?

**Comment by maketigers** [comment]
The big team pretend to see nothing #swarm!!!

**Comment by ldeffenb** [comment]
Read the history in the bee-support channel on Discord.  We are constantly telling people to:

Create a free account at infura.io
Make an Ethereum project there
Take the Goerli URL from that project as your swap-endpoint.
It will include your personal API key.
