### ISSUE TITLE
bee-clef 0.4.10 failed to start

### ISSUE THREAD

**Issue by caesarchad** [ethersphere/bee#1722]
#### Summary
Bee Clef failed to read credentials files for bee-clef 0.4.10, 

#### Steps to reproduce
root@VM-0-3-ubuntu:~# history
    1  2021-05-16 01:00:52
    2  2021-05-16 00:38:31 apt-get remove --purge bee-clef
    3  2021-05-16 00:38:39 apt-get remove --purge bee
    4  2021-05-16 00:38:48 sudo groupdel bee-clef
    5  2021-05-16 00:39:39 wget https://github.com/ethersphere/bee/releases/download/v0.5.3/bee_0.5.3_arm64.deb
    6  2021-05-16 00:41:40 wget https://github.com/ethersphere/bee/releases/download/v0.5.3/bee_0.5.3_amd64.deb
    7  2021-05-16 00:42:51  wget https://github.com/ethersphere/bee-clef/releases/download/v0.4.10/bee-clef_0.4.10_amd64.deb
    8  2021-05-16 00:45:39 sudo dpkg -i bee-clef_0.4.10_amd64.deb
    9  2021-05-16 00:45:58 sudo systemctl start bee-clef.service
   10  2021-05-16 00:47:44 sudo systemctl status bee-clef.service
   11  2021-05-16 00:49:34 sudo dpkg -i bee_0.5.3_amd64.deb
   12  2021-05-16 00:50:21 sudo bee-get-addr
   13  2021-05-16 01:00:55 sudo bee-clef-keys
   14  2021-05-16 01:01:03 vi /root/bee-clef-key-1621098055.json
   15  2021-05-16 01:01:41 vi /root/bee-clef-password-1621098055.txt
   16  2021-05-16 01:06:44 sudo systemctl start bee.service
   17  2021-05-16 01:06:53 sudo systemctl status bee-clef.service
   18  2021-05-16 01:07:08 curl http://localhost:1635
   20  2021-05-16 01:08:09 sudo systemctl stop bee.service
   21  2021-05-16 01:08:13 journalctl -u bee -f
   22  2021-05-16 01:09:35 sudo vi /etc/bee/bee.yaml
   23  2021-05-16 01:11:09 sudo systemctl restart bee
   25  2021-05-16 01:14:41 chown bee:bee /var/lib/ -R
   29  2021-05-16 01:16:02 sudo systemctl status  bee
   30  2021-05-16 01:16:40 systemctl status bee
   31  2021-05-16 01:17:03 sudo systemctl restart bee
   32  2021-05-16 01:17:07 systemctl status bee
   33  2021-05-16 01:17:54 curl http://localhost:1635
   34  2021-05-16 01:18:20 systemctl status beesudo systemctl status bee-clef.service
   35  2021-05-16 01:18:26 sudo systemctl status bee-clef.service
   36  2021-05-16 01:20:33 :q
   37  2021-05-16 01:20:35 sudo systemctl status bee-clef.service

#### Expected behavior
Bee Clef should start and able to read the signed file

#### Actual behavior
Bee Clef cannot read the signed file.
![image](https://user-images.githubusercontent.com/17776934/118372712-8a751800-b5e5-11eb-9c24-ef1a019c93f3.png)

May 16 01:14:43 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:14:43.806] Failed to read encrypted storage         err="open /var/lib/bee-clef/2001958183fb2e1db28e/credentials.json: permission denied" file=/var/lib/bee-clef/20019>
May 16 01:14:43 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:14:43.806] Failed to unmarshal encrypted storage    err="unexpected end of JSON input" file=/var/lib/bee-clef/2001958183fb2e1db28e/credentials.json
May 16 01:14:43 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:14:43.806] Failed to read encrypted storage         err="unexpected end of JSON input" file=/var/lib/bee-clef/2001958183fb2e1db28e/credentials.json
May 16 01:14:43 VM-0-3-ubuntu bee-clef-service[25819]: {"jsonrpc":"2.0","id":3,"method":"ui_onInputRequired","params":[{"title":"Password for signing","prompt":"Please enter password for signing data with account 0x589F5F9a48426930299c8>
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25818]: INFO [05-16|01:17:04.037] Op approved
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25818]: INFO [05-16|01:17:04.043] Op approved
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:17:04.043] Failed to read encrypted storage         err="open /var/lib/bee-clef/2001958183fb2e1db28e/credentials.json: permission denied" file=/var/lib/bee-clef/20019>
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:17:04.043] Failed to unmarshal encrypted storage    err="unexpected end of JSON input" file=/var/lib/bee-clef/2001958183fb2e1db28e/credentials.json
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25818]: WARN [05-16|01:17:04.043] Failed to read encrypted storage         err="unexpected end of JSON input" file=/var/lib/bee-clef/2001958183fb2e1db28e/credentials.json
May 16 01:17:04 VM-0-3-ubuntu bee-clef-service[25819]: {"jsonrpc":"2.0","id":4,"method":"ui_onInputRequired","params":[{"title":"Password for signing","prompt":"Please enter password for signing data with account 0x589F5F9a48426930299c8

**Comment by Eknir** [comment]
The newest `bee-clef` is v0.4.12. Please try this version. We can help you on our Discord https://discord.gg/sU8NEtaR8y
