### ISSUE TITLE
waiting for transaction 24c5a1935df760efc1d76398d52bd5f94c8779dd56962292f541e16376c6c6e5 to be mined: not found

### ISSUE THREAD

**Issue by hackren** [ethersphere/bee#1725]
TRAC[2021-05-16T23:34:51+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:53+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:54+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:55+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:56+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:57+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:34:58+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:00+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:01+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:02+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:03+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:04+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:06+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:07+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:08+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 
TRAC[2021-05-16T23:35:09+08:00] waiting for transaction 678f23ff07d3bf261a512527ce0f219f4f0bd8f5e2f3c050437170991c06844c to be mined: not found 

Help me

**Comment by flotox** [comment]
same problem

**Comment by flotox** [comment]
INFO[2021-05-17T08:50:50Z] pss public key 0349e35f38d671564184a58fd0c8c59ed5006342fdbfa22a96b2831dc04a1007c7
INFO[2021-05-17T08:50:50Z] using ethereum address 8b482bf261ffcab4aecd5454d79958413977a701
INFO[2021-05-17T08:50:50Z] debug api address: [::]:1635
INFO[2021-05-17T08:50:51Z] using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474
INFO[2021-05-17T08:50:52Z] waiting for chequebook deployment in transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28
TRAC[2021-05-17T08:50:52Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found
TRAC[2021-05-17T08:50:53Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found
TRAC[2021-05-17T08:50:54Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found
0x8b482bf261ffcab4aecd5454d79958413977a701TRAC[2021-05-17T08:50:56Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found
TRAC[2021-05-17T08:50:57Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found
TRAC[2021-05-17T08:50:58Z] waiting for transaction a2aa26d9f5592818261c0e56fbc269a919914d41ad21f4e3faadc980414e8b28 to be mined: not found

**Comment by Eknir** [comment]
Thank you for trying out Bee!

Please join our Discord for support: https://discord.gg/sU8NEtaR8y
