### ISSUE TITLE
How to solve the error "no prior cashout"?

### ISSUE THREAD

**Issue by moonfunjohn** [ethersphere/bee#1728]
Hi, I ran cash out api on my swarm node, 

curl http://localhost:1635/chequebook/cashout/fd8f10cd34ba9c99ea7a53efd2afac169ee706272d600c1f5c8d3076c091e4dd

and got {"message":"no prior cashout","code":404} response. 

Can anyone help to tell me what is the response mean? I searched the swarm API documents and got nothing about it.

**Comment by wanyvic** [comment]
same too.
`root@bee-4:/home/wany/bee# curl http://127.0.0.1:1635/chequebook/cheque | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   268  100   268    0     0   2504      0 --:--:-- --:--:-- --:--:--  2528
{
  "lastcheques": [
    {
      "peer": "d44d8d5c87aa9990f331c5bf8e5b9c2f6ea105b2652368e0a2e6b457bc026412",
      "lastreceived": {
        "beneficiary": "0xAff7904eb3b5AA295605FDA2Aa665D65774aC16a",
        "chequebook": "0x062C545d95069dA82084bd4C78D27BFa1B0d083d",
        "payout": 1635000000000
      },
      "lastsent": null
    }
  ]
}
root@bee-4:/home/wany/bee# curl http://127.0.0.1:1635/chequebook/cashout/d44d8d5c87aa9990f331c5bf8e5b9c2f6ea105b2652368e0a2e6b457bc026412
{"message":"no prior cashout","code":404}`

**Comment by Eknir** [comment]
Hi there, thanks for trying out Bee!

It would be best if you join our Discord: https://discord.gg/sU8NEtaR8y

**Comment by moonfunjohn** [comment]
upgrade bee node to 0.6.1 solve the problem.
