### ISSUE TITLE
Replace leveldb not found errors in package localstore 

### ISSUE THREAD

**Issue by mrsimicsak** [ethersphere/bee#1742]
I am working on a version of bee that uses BadgerDB instead of LevelDB for localstore to reduce the disk io requirements (https://github.com/mrsimicsak/bee/tree/badgerfrompr75). While working on changing over I discovered that localstore checks for returned leveldb.ErrNotFound errors, making it dependent on LevelDB where it otherwise wouldn't be.

Creating a shed.ErrNotFound and using it in place of the LevelDB.ErrNotFound would make it easier to swap database backends and eliminate localstore's dependency on LevelDB.

**Comment by Eknir** [comment]
Thanks. Dust settled a bit after the launch now. We'll look into this.

**Comment by acud** [comment]
@mrsimicsak I'm closing this since the PR went stale and this is not time well spent considering we are looking into doing significant changes in our storage abstractions.
