### ISSUE TITLE
POST /stamps/{amount}/{depth} returns HTTP 500 for high but valid depth -- insufficient balance?

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#1766]
#### Summary

For high but valid (< 256) `depth` values I see `{"message":"cannot create batch","code":500}`. My assumption is that I don't have the balance to create the stamp with that `depth`.

#### Steps to reproduce

Example where it gives `HTTP 500`

```
> curl -X POST http://localhost:1633/stamps/1000/100 -i
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Tue, 18 May 2021 13:51:56 GMT
Content-Length: 46

{"message":"cannot create batch","code":500}
```

Example with lower `depth` that works

```
> curl -X POST http://localhost:1633/stamps/1000/50 -i
HTTP/1.1 201 Created
Content-Type: application/json; charset=utf-8
Date: Tue, 18 May 2021 13:51:36 GMT
Content-Length: 80

{"batchID":"..."}
```

#### Expected behavior

Instead of `HTTP 500`, the status code should be `HTTP 400` with a descriptive message. 

#### Actual behavior

`HTTP 500` with an assumption of insufficient balance.

**Comment by Eknir** [comment]
We introduced an error-code that specifies invalid balance. If that was indeed the case, then this issue can be considered fixed. We would appreciate if you could confirm this!
