### ISSUE TITLE
Bootnode discovery using public DNS

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#177]
Implement connectivity based on @vandot specifications https://hackmd.io/@ethswarm/SJJ2WE_FI.

Ideally, a special form o multiaddresses which would include domain name and protocol name for srv based lookup should be implemented that can be defined as --bootnode option value. Something like, if it is possible:

```
bee start --bootnode /dnsaddr/bootnodes.ethswarm.org/discovery/srv
```

**Comment by vandot** [comment]
Multiaddr already has DNS discovery process set. We implemented their process (use existing libs with little custom code) described [here](https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md)
