### ISSUE TITLE
Estimate batch lifetime

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1774]
# User story

## Story

- As a user who previously bought postage batches, I want to know the balances for each batch I bought, as well as the current price, such that I can estimate the expected lifetime of my batches
- As a user who is about to purchase a new batch, I want to know the current price, such that I can estimate what balance I should put in my batch for a certain expected lifetime.

## Acceptance criteria

- Properly designed API endpoints on `1633` that allows said user-stories.

## Background

- The current price is returned from [the priceOracle contract](https://github.com/ethersphere/storage-incentives/blob/8e29b8020edc7dffcb40008c61f42f7182b26489/src/PriceOracle.sol#L22)
- The remaining batch balance should be computed by calling [the remainingBalance](https://github.com/ethersphere/storage-incentives/blob/8e29b8020edc7dffcb40008c61f42f7182b26489/src/PostageStamp.sol#L138) function on the batch.
   - @ralph-pichler , the remainingBalance is only in-sync when the priceOracle has just updated it's price. Do I see this correctly? How do we correct for the time when the priceOracle has not recently updated it's price (this to me also seems to be a problem in the smart-contract itself. E.g. on the `topUp` function).

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by miaoyanbao132** [comment]
公共链接还有没有

**Comment by IxaBrjnko** [comment]
Thank you, thank you, thank you!!

**Comment by Eknir** [comment]
This is currently being worked on. @mrekucci , can you close this issue with a reference to the PR when done?

**Comment by mrekucci** [comment]
> This is currently being worked on. @mrekucci , can you close this issue with a reference to the PR when done?

Thanks, will do!

**Comment by mrekucci** [comment]
This issue was addressed in #2336
