### ISSUE TITLE
node forever stuck attempting to sync chunks with expired batch ids

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#1777]
#### Summary
When a batch with a low amount is created, or for whatever reason, peers do not have the batch id my node uses to send out chunks, my node will forever be stuck attempting to sync chunks to peers who send back invalid chunk error due to invalid batch id.

#### Expected behavior
My node should stop attempting to sync chunks after some number of failed attempts.

#### Actual behavior
My node is constantly attempting to sync the chunks with expired/invalid batch ids.

seen error from pushsync:
```
chunk %s receive receipt from peer
```

**Comment by Eknir** [comment]
Thank you for reporting. 

Fixed per: https://github.com/ethersphere/bee/pull/1856

We would appreciate if you could validate the fix and report here.
