### ISSUE TITLE
error getting migrations for current schema (clean-interval): could not find current db schema

### ISSUE THREAD

**Issue by totodata** [ethersphere/bee#1779]
bee start error:
error getting migrations for current schema (clean-interval): could not find current db schema

how to fix it?

**Comment by ldeffenb** [comment]
It sounds like you are trying to run the latest master.  0.6.0 is still under development and not ready for the world to try to run yet...

**Comment by totodata** [comment]
how to down to 0.53 ?

**Comment by Eknir** [comment]
`git checkout tags/v0.5.3`

**Comment by Eknir** [comment]
Thanks for trying out Bee! I would advice you to wait maximally a few days once v0.6.0 is out
