### ISSUE TITLE
Error: read private key: open /root/.bee/keys/libp2p.key: permission denied

### ISSUE THREAD

**Issue by AnalogKnight** [ethersphere/bee#1785]
When I use command:

journalctl --lines=100 --follow --unit bee

The output is:

5月 20 13:15:24 pop-os systemd[1]: bee.service: Scheduled restart job, restart counter is at 2441.
5月 20 13:15:24 pop-os systemd[1]: Stopped Bee - Ethereum Swarm node.
5月 20 13:15:24 pop-os systemd[1]: Started Bee - Ethereum Swarm node.
5月 20 13:15:24 pop-os bee[132876]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
5月 20 13:15:24 pop-os bee[132876]:                 \     /
5月 20 13:15:24 pop-os bee[132876]:             \    o ^ o    /
5月 20 13:15:24 pop-os bee[132876]:               \ (     ) /
5月 20 13:15:24 pop-os bee[132876]:    ____________(%%%%%%%)____________
5月 20 13:15:24 pop-os bee[132876]:   (     /   /  )%%%%%%%(  \   \     )
5月 20 13:15:24 pop-os bee[132876]:   (___/___/__/           \__\___\___)
5月 20 13:15:24 pop-os bee[132876]:      (     /  /(%%%%%%%)\  \     )
5月 20 13:15:24 pop-os bee[132876]:       (__/___/ (%%%%%%%) \___\__)
5月 20 13:15:24 pop-os bee[132876]:               /(       )\
5月 20 13:15:24 pop-os bee[132876]:             /   (%%%%%)   \
5月 20 13:15:24 pop-os bee[132876]:                  (%%%)
5月 20 13:15:24 pop-os bee[132876]:                    !
5月 20 13:15:24 pop-os bee[132876]: time="2021-05-20T13:15:24+08:00" level=info msg="version: 0.5.3-acbd0e2"
5月 20 13:15:24 pop-os bee[132876]: Error: read private key: open /root/.bee/keys/libp2p.key: permission denied
5月 20 13:15:24 pop-os systemd[1]: bee.service: Main process exited, code=exited, status=1/FAILURE
5月 20 13:15:24 pop-os systemd[1]: bee.service: Failed with result 'exit-code'.

What should I do?

I tried "sudo chmod 777 /root/.bee/keys/libp2p.key" but still not work.

**Comment by AnalogKnight** [comment]
My OS is base on Ubuntu 20.04 so I think this won't bring any problem.

**Comment by 15ho** [comment]
sudo chown -R bee:bee /root/.bee

**Comment by Eknir** [comment]
Hi there, it would be best if you reach out to our support channel in Discord to resolve your problem. https://discord.gg/qG8Kb8TsvQ

**Comment by Eknir** [comment]
Thanks for trying out Bee! And welcome to Swarm :) . I hope you have success soon ;)

**Comment by Eknir** [comment]
:bee:
