### ISSUE TITLE
failed: could not cash out cheque

### ISSUE THREAD

**Issue by zeoio** [ethersphere/bee#1787]
run `./cashout.sh cashout-all` failed:

```log
could not cash out cheque for 0080b163f28265c8a061f00ec10e9daa9c95fd41d010bd09c8511005ea9ae2d9: 500 cannot cash cheque
```

**Comment by leepood** [comment]
Some problem here, I have checked the logs which all http response status code is 500. Oops!

**Comment by Eknir** [comment]
Bee v0.6.0 contains many improvements to cashing out cheques. I would appreciate if you could update to that version, once it is out and report here whether the experience improved!

**Comment by leepood** [comment]
> Bee v0.6.0 contains many improvements to cashing out cheques. I would appreciate if you could update to that version, once it is out and report here whether the experience improved!

Thanks for your reply, btw when will the v0.6.0 be release?

**Comment by cppfuns** [comment]
> Bee v0.6.0 contains many improvements to cashing out cheques. I would appreciate if you could update to that version, once it is out and report here whether the experience improved!

Can v0.6.0 participate in the existing goerli test network of v0.5.3 and participate in 100W activities? I have tried it is because the version of chequebook is different, which causes it to not run normally.

**Comment by Penguin-Killer** [comment]
> Bee v0.6.0 contains many improvements to cashing out cheques. I would appreciate if you could update to that version, once it is out and report here whether the experience improved!

I have upgraded to Bee V0.6.0 and still can't cash the check.

**Comment by cppfuns** [comment]
> > Bee v0.6.0包含许多兑现支票的改进。如果您可以将其更新到该版本，并在此报告体验是否有所改善，将不胜感激！
> 
> 我已经升级到Bee V0.6.0，但仍然无法兑现支票。

0.6.0 bug, wait for the 0.6.1 version to fix it

**Comment by Penguin-Killer** [comment]
> > > Bee v0.6.0包含许多兑现现支票的改进。如果您可以将其更新到该版本，并在此报告中体验是否有所改善，将不胜感激！
> > 
> > 
> > 我已经升级到Bee V0.6.0，但仍然无法兑现现支票。
> 
> 0.6.0错误，请等待0.6.1版本修复

I upgraded 0.6.1 and still have this problem

**Comment by cppfuns** [comment]
> > > > Bee v0.6.0包含许多兑现现支票的改进。如果您可以将其更新到该版本，并在此报告中体验是否有所改善，将不胜感激！
> > > 
> > > 
> > > 我已经升级到Bee V0.6.0，但仍然无法兑现现支票。
> > 
> > 
> > 0.6.0错误，请等待0.6.1版本修复
> 
> I upgraded 0.6.1 and still have this problem

Unfortunate result, Keep waiting for the new fix version

**Comment by Eknir** [comment]
> Bee v0.6.0 contains many improvements to cashing out cheques. I would appreciate if you could update to that version, once it is out and report here whether the experience improved!

Same question for 1.0. How is the experience now?

**Comment by acud** [comment]
Closing this as the issue is going stale. Without more debugging information this would be difficult to debug. If the problem still persists please open a new issue with: logs from the node and exact steps to reproduce the problem. Thanks!
