### ISSUE TITLE
Chunk => file

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#179]
As a user of Swarm, I want to easily upload and download a file to/from Swarm, such that I don't spend my valuable time on being concerned with low-level structures such as chunks.

**Comment by Eknir** [comment]
@nolash, you are working on this, right? Could you give an update here on the status of this issue?

**Comment by nolash** [comment]
it's _sooooo_ close: https://github.com/ethersphere/bee/pull/168

**Comment by Eknir** [comment]
Closing this issue, I think it's done
