### ISSUE TITLE
Join Swarm without a chequebook

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1791]
# User story

## Story

As a downloader/uploader of Swarm content, I want to be able to join the Swarm without having a chequebook, such that onboarding to Swarm is faster and easier.

## Acceptance criteria

- A user can upload/download content from Swarm without deploying a chequebook

## Background

- [time-based settlements](https://github.com/ethersphere/bee/pull/1711) ensured that a Bee node (and a Swarm network) can function properly without a chequebook
- Our boot-up sequence still automatically deploys a chequebook if the chequebook is non-existing. This should change.
- If the user has not deployed a chequebook, it needs to pass an Ethereum transaction (https://github.com/ethersphere/bee/pull/1655) done in the past by it's Ethereum account connected to Swarm. 
    - Ideally, we should scan the blockchain on start-up to see if such a transaction exists. 
    - If it doesn't exist the Bee node should make an empty transaction to the blockchain.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by acud** [comment]
related to https://github.com/ethersphere/bee/issues/2394

**Comment by mrekucci** [comment]
@Eknir is this still relevant since we're working on the ultra-light mode?

**Comment by acud** [comment]
@mrekucci this can be closed since we've merged the ultra-light node PR
