### ISSUE TITLE
Bee 0.6 !!!!!the ABI signature could not be found

### ISSUE THREAD

**Issue by seedlive** [ethersphere/bee#1799]
in bee 6 use this cmd : 
 bee start   --verbosity 5   --data-dir  /mnt/bee1/gbzzdate2635   --api-addr :2633 --p2p-addr :2634 --debug-api-addr :2635  --swap-endpoint https://goerli.infura.io/v3/fba6b82dd89d47d7b0613fcbf00aa27c --debug-api-enable --clef-signer-enable --clef-signer-endpoint /var/lib/bee-clef/clef.ipc

Welcome to the Swarm.... Bzzz Bzzzz Bzzzz

               .-.         .--''-.
             .'   '.     /'       '
             '.     '. ,'          |
   _        o    '.o   ,'        _.-'
 .\ /.       \.--./'. /.:. :._:.'
< ~O~ >    .'    '._-': ': ': ': ':
 '/_\'     :(.) (.) :  ': ': ': ': ':>-
 \ | /      ' ____ .'_.:' :' :' :' :'
  \|/        '\<>/'/ | | :' :' :'
   |               \  \ \
   |                '  ' '
        
                   
INFO[2021-05-21T03:01:18+08:00] version: 0.6.0-67cc8f24                      
INFO[2021-05-21T03:01:18+08:00] using swarm network address through clef: 8cf3780f08986c117ca65a1a4fda2b078972717d374e896214197c8c92c05d5a 
INFO[2021-05-21T03:01:18+08:00] swarm public key 020bb09c0a8c1bf91aed900a6551fd16ab3902f0f567fb3a1654108b387951de54 
DEBU[2021-05-21T03:01:18+08:00] using existing libp2p key                    
DEBU[2021-05-21T03:01:18+08:00] using existing pss key                       
INFO[2021-05-21T03:01:18+08:00] pss public key 0289c16c4faa6e4f9adfbd341747c435ad2e837b84a3277bdd3ce45b661b736809 
INFO[2021-05-21T03:01:18+08:00] using ethereum address 16798e455b9d9ec4699d73f989454bf7c11e4e1b 
INFO[2021-05-21T03:01:18+08:00] debug api address: [::]:2635                 
INFO[2021-05-21T03:01:19+08:00] using default factory address for chain id 5: 73c412512e1ca0be3b89b77ab3466da6a1b9d273 
INFO[2021-05-21T03:01:21+08:00] no chequebook found, deploying new one.      
**Error: chequebook init: validation failed: Transaction contains data, but the ABI signature could not be found: signature 15efd8a7 not found**
****

**Comment by wenju-chen** [comment]
这个问题会不会是因为官方所说的指定时间前更新才会出现的问题？

**Comment by ldeffenb** [comment]
According to #1798 you might need to upgrade your bee-clef.
