### ISSUE TITLE
post /chequebook/cashout/peer-id  error

### ISSUE THREAD

**Issue by hackren** [ethersphere/bee#1802]
get http://localhost:1635/chequebook/cheque
`{
  "lastcheques": [
    {
      "peer": "84e2e02a067f0044fcd894618df2af0826e871492cc94ec9218d8d74de56415c",
      "lastreceived": {
        "beneficiary": "0x48c760020e4725452f1Fd799fB5C502fd9b7F7e5",
        "chequebook": "0xE9ee65847c9e13D8dCF4fA4F4a733Df7D3Bd0eEf",
        "payout": 198000000000
      },
      "lastsent": null
    },
    {
      "peer": "8de1077869816f5f0f5ed96b967db15c9f3d8b8e0da9b1cef6643d823af73ff1",
      "lastreceived": {
        "beneficiary": "0x48c760020e4725452f1Fd799fB5C502fd9b7F7e5",
        "chequebook": "0xEdCb942044C917D14bBe271f0792Ac6f39caf855",
        "payout": 78000000000
      },
      "lastsent": null
    },
    {
      "peer": "8de2f8f9562b9d4b638367dba0c985e8c97653691092a541308cdf68f7d1acd7",
      "lastreceived": {
        "beneficiary": "0x48c760020e4725452f1Fd799fB5C502fd9b7F7e5",
        "chequebook": "0xfD236395cA2d976014a12435cf3a1FD500a87231",
        "payout": 21000000000
      },
      "lastsent": null
    },
    {
      "peer": "8dfa101e7f483034f3c0a9c2b400a05411ea4b78c194ca90b8150ee0fff48620",
      "lastreceived": {
        "beneficiary": "0x48c760020e4725452f1Fd799fB5C502fd9b7F7e5",
        "chequebook": "0xE34A76f33D05D2D14219a08EC353Ec8BDeaD8CC2",
        "payout": 88000000000
      },
      "lastsent": null
    }
  ]
}`

post http://localhost:1635/chequebook/cashout/8dfa101e7f483034f3c0a9c2b400a05411ea4b78c194ca90b8150ee0fff48620
`{"transactionHash":"0x4375c8c720431c2101422effb98ad5dfe6cbdf00c0ce1c43b59667b252b1babd"}`

open https://goerli.etherscan.io/tx/0x4375c8c720431c2101422effb98ad5dfe6cbdf00c0ce1c43b59667b252b1babd
Sorry, We are unable to locate this TxnHash

get http://localhost:1635/chequebook/cashout/8dfa101e7f483034f3c0a9c2b400a05411ea4b78c194ca90b8150ee0fff48620
`{
  "peer": "8dfa101e7f483034f3c0a9c2b400a05411ea4b78c194ca90b8150ee0fff48620",
  "chequebook": "0xe34a76f33d05d2d14219a08ec353ec8bdead8cc2",
  "cumulativePayout": 88000000000,
  "beneficiary": "0x48c760020e4725452f1fd799fb5c502fd9b7f7e5",
  "transactionHash": "0x4375c8c720431c2101422effb98ad5dfe6cbdf00c0ce1c43b59667b252b1babd",
  "result": null
}`

open https://goerli.etherscan.io/address/0xe313bC02a22D730670a61C14682ecE764107C941#tokentxns
No record

please help me

**Comment by Penguin-Killer** [comment]
I also encountered this bug.
 I was unable to extract GBZZ from the checkbook contract back into my node's own wallet, and I was unable to deposit additional GBZZ into the checkbook contract.
I use cashout.sh reply to me that there is no check available，But I see some checks in my checkbook that haven't been cashed yet.
I can't find the hash value after cashing the check

**Comment by kevin486** [comment]
I also experienced the same issue.   What's worse,  bee node considersthe cheque as cashedout, which actually not.

**Comment by checkblue** [comment]
I also experienced the same issue.

**Comment by potato1992** [comment]
same

**Comment by acud** [comment]
We've created an endpoint at `POST /transactions/<txnHash>` which should address the problem, if a transaction gets purged out of the mem-pool for whatever reason, you can use the endpoint to resubmit the transaction using the hash of the already-purged transaction. If you still experience problems please open a new issue and try to provide with as much information as possible
