### ISSUE TITLE
Improve input validation for BZZ Reupload

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#1803]
When I try to input all sort of invalid or valid-ish data, I pretty much always get `500` which seems to me a bit extreme as for most of these I would either expect `400` or `404`. About `404` I did not manage to actually get that one at all, not sure when I should receive it?

Example inputs:

```bash
$ curl -X PATCH -s localhost:1633/bzz/111/

// Non existing reference
$ curl -X PATCH -s localhost:1633/bzz/1e477b015af480e387fbf5edd90f1685a30c0e3ba88eeb3871b326b816a542da/
```

**Comment by nugaon** [comment]
I'd rather propose using 422 http error, as the syntax and the request are in great format and understandable by the Bee, but the business-logic does not let reupload an unpinned content.

**Comment by acud** [comment]
related to #2026
