### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by chinapeace** [ethersphere/bee#1809]
###  I deploy new node use bee v0.6.0 and bee-clef v0.4.12, When start bee show this error:

`         
May 21 10:39:35 vultr.guest bee[5688]: time="2021-05-21T10:39:35Z" level=info msg="version: 0.6.0-67cc8f24"
May 21 10:39:35 vultr.guest bee[5688]: time="2021-05-21T10:39:35Z" level=info msg="using swarm network address through clef: 1c731fbce203fe5d8f87cfb0e2a*******"
May 21 10:39:35 vultr.guest bee[5688]: time="2021-05-21T10:39:35Z" level=info msg="swarm public key 0314ca3a9b092b1f4d7b3ca1af1*****"
May 21 10:39:35 vultr.guest bee[5688]: time="2021-05-21T10:39:35Z" level=info msg="pss public key 038f06780066d2536d70199a69d1*******"
May 21 10:39:35 vultr.guest bee[5688]: time="2021-05-21T10:39:35Z" level=info msg="using ethereum address b49b7bb82e***"
May 21 10:39:35 vultr.guest bee[5688]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 10:39:35 vultr.guest bee[5688]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11141cb]
May 21 10:39:35 vultr.guest bee[5688]: goroutine 1 [running]:
May 21 10:39:35 vultr.guest bee[5688]: github.com/ethersphere/bee/pkg/node.NewBee(0x1417c43, 0x5, 0xc000554060, 0x20, 0x20, 0x1733780, 0x1fadd20, 0xc00033c660, 0xc00033c680, 0x17300f8, ...)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/ethersphere/bee/pkg/node/node.go:205 +0x750b
May 21 10:39:35 vultr.guest bee[5688]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).initStartCmd.func1(0xc0000eb340, 0xc0000cffe0, 0x0, 0x2, 0x0, 0x0)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:119 +0x1178
May 21 10:39:35 vultr.guest bee[5688]: github.com/spf13/cobra.(*Command).execute(0xc0000eb340, 0xc0000cffc0, 0x2, 0x2, 0xc0000eb340, 0xc0000cffc0)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
May 21 10:39:35 vultr.guest bee[5688]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eb080, 0x0, 0x0, 0xc00037cac0)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
May 21 10:39:35 vultr.guest bee[5688]: github.com/spf13/cobra.(*Command).Execute(...)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/spf13/cobra@v1.0.0/command.go:887
May 21 10:39:35 vultr.guest bee[5688]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).Execute(...)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:132
May 21 10:39:35 vultr.guest bee[5688]: github.com/ethersphere/bee/cmd/bee/cmd.Execute(0xc000056748, 0x1fafd00)
May 21 10:39:35 vultr.guest bee[5688]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:141 +0x69
May 21 10:39:35 vultr.guest bee[5688]: main.main()
May 21 10:39:35 vultr.guest bee[5688]:         github.com/ethersphere/bee/cmd/bee/main.go:15 +0x26
May 21 10:39:35 vultr.guest systemd[1]: bee.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 10:39:35 vultr.guest systemd[1]: bee.service: Failed with result 'exit-code'.

### `
Vultr VPS Server
OS: Ubuntu 20.04 x64
CPU:Intel Xeon Processor (Skylake, IBRS)

Package: 
bee_0.6.0_amd64.deb  
bee-clef_0.4.12_amd64.deb

**Comment by Eknir** [comment]
What steps did you follow to update your node?

**Comment by mrekucci** [comment]
This is partially fixed in #1807 Once merged, I recommend building and running bee with the fix included and report the error which is currently hidden because of the `nil` panic.

**Comment by chinapeace** [comment]
> 您按照什么步骤来更新您的节点？
I am install new node 
1.wget bee and bee-clef package
2.dpkg -i bee-clef then dkpg -i bee
3.fucet my address
4.modify bee.yaml
5.start bee

**Comment by Eknir** [comment]
@chinapeace , could you please validate if #1807 indeed solves your problem?

**Comment by chinapeace** [comment]
> @chinapeace , could you please validate if #1807 indeed solves your problem?

Ok I will

**Comment by esadakar** [comment]
We'd appreciate if you can also increate the logging level to "trace".

**Comment by chinapeace** [comment]
> We'd appreciate if you can also increase the logging level to "trace".
show this ：
`May 21 14:03:40 vultr.guest systemd[1]: Started Bee - Ethereum Swarm node.
May 21 14:03:40 vultr.guest bee[62084]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
May 21 14:03:40 vultr.guest bee[62084]:                .-.         .--''-.
May 21 14:03:40 vultr.guest bee[62084]:              .'   '.     /'       '
May 21 14:03:40 vultr.guest bee[62084]:              '.     '. ,'          |
May 21 14:03:40 vultr.guest bee[62084]:    _        o    '.o   ,'        _.-'
May 21 14:03:40 vultr.guest bee[62084]:  .\ /.       \.--./'. /.:. :._:.'
May 21 14:03:40 vultr.guest bee[62084]: < ~O~ >    .'    '._-': ': ': ': ':
May 21 14:03:40 vultr.guest bee[62084]:  '/_\'     :(.) (.) :  ': ': ': ': ':>-
May 21 14:03:40 vultr.guest bee[62084]:  \ | /      ' ____ .'_.:' :' :' :' :'
May 21 14:03:40 vultr.guest bee[62084]:   \|/        '\<>/'/ | | :' :' :'
May 21 14:03:40 vultr.guest bee[62084]:    |               \  \ \
May 21 14:03:40 vultr.guest bee[62084]:    |                '  ' '
May 21 14:03:40 vultr.guest bee[62084]:         
May 21 14:03:40 vultr.guest bee[62084]:                    
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="version: 0.6.0-67cc8f24"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="using swarm network address through clef: 1c731fbce203fe5d8f87cfb0e2a156d5bfc5dd85a1459f3e2e2b6ba02416ff87"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="swarm public key 0314ca3a9b092b1f4d7b3ca1af1dfe16aac098cbfd43318ab9dc8b169af4dce5f2"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=debug msg="using existing libp2p key"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=debug msg="using existing pss key"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="pss public key 038f06780066d2536d70199a69d1ecaee3abdf6f37e39727d11a426b506ae18a0a"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="using ethereum address b49b7bb82e5438751557f7f92e93bf274d48c522"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="debug api address: [::]:1635"
May 21 14:03:40 vultr.guest bee[62084]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 14:03:40 vultr.guest bee[62084]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11141cb]
May 21 14:03:40 vultr.guest bee[62084]: goroutine 1 [running]:
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/pkg/node.NewBee(0x1417c43, 0x5, 0xc00051a1c0, 0x20, 0x20, 0x1733780, 0x1fadd20, 0xc000076140, 0xc000076160, 0x17300f8, ...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/pkg/node/node.go:205 +0x750b
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).initStartCmd.func1(0xc0000eb8c0, 0xc000169180, 0x0, 0x2, 0x0, 0x0)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:119 +0x1178
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).execute(0xc0000eb8c0, 0xc000169160, 0x2, 0x2, 0xc0000eb8c0, 0xc000169160)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eb600, 0x0, 0x0, 0xc000166dc0)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).Execute(...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:887
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).Execute(...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:132
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.Execute(0xc000056748, 0x1fafd00)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:141 +0x69
May 21 14:03:40 vultr.guest bee[62084]: main.main()
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/main.go:15 +0x26
May 21 14:03:40 vultr.guest systemd[1]: bee.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 14:03:40 vultr.guest systemd[1]: bee.service: Failed with result 'exit-code'.
May 21 14:03:46 vultr.guest systemd[1]: bee.service: Scheduled restart job, restart counter is at 2044.
May 21 14:03:46 vultr.guest systemd[1]: Stopped Bee - Ethereum Swarm node.
`

**Comment by chinapeace** [comment]
> We'd appreciate if you can also increase the logging level to "trace".

**When  logging level to "trace"：**
May 21 14:03:40 vultr.guest systemd[1]: Started Bee - Ethereum Swarm node.
May 21 14:03:40 vultr.guest bee[62084]: Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
May 21 14:03:40 vultr.guest bee[62084]:                .-.         .--''-.
May 21 14:03:40 vultr.guest bee[62084]:              .'   '.     /'       '
May 21 14:03:40 vultr.guest bee[62084]:              '.     '. ,'          |
May 21 14:03:40 vultr.guest bee[62084]:    _        o    '.o   ,'        _.-'
May 21 14:03:40 vultr.guest bee[62084]:  .\ /.       \.--./'. /.:. :._:.'
May 21 14:03:40 vultr.guest bee[62084]: < ~O~ >    .'    '._-': ': ': ': ':
May 21 14:03:40 vultr.guest bee[62084]:  '/_\'     :(.) (.) :  ': ': ': ': ':>-
May 21 14:03:40 vultr.guest bee[62084]:  \ | /      ' ____ .'_.:' :' :' :' :'
May 21 14:03:40 vultr.guest bee[62084]:   \|/        '\<>/'/ | | :' :' :'
May 21 14:03:40 vultr.guest bee[62084]:    |               \  \ \
May 21 14:03:40 vultr.guest bee[62084]:    |                '  ' '
May 21 14:03:40 vultr.guest bee[62084]:         
May 21 14:03:40 vultr.guest bee[62084]:                    
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="version: 0.6.0-67cc8f24"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="using swarm network address through clef: 1c731fbce203fe5d8f87cfb0e2a156d5bfc5dd85a1459f3e2e2b6ba02416ff87"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="swarm public key 0314ca3a9b092b1f4d7b3ca1af1dfe16aac098cbfd43318ab9dc8b169af4dce5f2"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=debug msg="using existing libp2p key"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=debug msg="using existing pss key"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="pss public key 038f06780066d2536d70199a69d1ecaee3abdf6f37e39727d11a426b506ae18a0a"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="using ethereum address b49b7bb82e5438751557f7f92e93bf274d48c522"
May 21 14:03:40 vultr.guest bee[62084]: time="2021-05-21T14:03:40Z" level=info msg="debug api address: [::]:1635"
May 21 14:03:40 vultr.guest bee[62084]: panic: runtime error: invalid memory address or nil pointer dereference
May 21 14:03:40 vultr.guest bee[62084]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11141cb]
May 21 14:03:40 vultr.guest bee[62084]: goroutine 1 [running]:
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/pkg/node.NewBee(0x1417c43, 0x5, 0xc00051a1c0, 0x20, 0x20, 0x1733780, 0x1fadd20, 0xc000076140, 0xc000076160, 0x17300f8, ...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/pkg/node/node.go:205 +0x750b
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).initStartCmd.func1(0xc0000eb8c0, 0xc000169180, 0x0, 0x2, 0x0, 0x0)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/start.go:119 +0x1178
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).execute(0xc0000eb8c0, 0xc000169160, 0x2, 0x2, 0xc0000eb8c0, 0xc000169160)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000eb600, 0x0, 0x0, 0xc000166dc0)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
May 21 14:03:40 vultr.guest bee[62084]: github.com/spf13/cobra.(*Command).Execute(...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/spf13/cobra@v1.0.0/command.go:887
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.(*command).Execute(...)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:132
May 21 14:03:40 vultr.guest bee[62084]: github.com/ethersphere/bee/cmd/bee/cmd.Execute(0xc000056748, 0x1fafd00)
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/cmd/cmd.go:141 +0x69
May 21 14:03:40 vultr.guest bee[62084]: main.main()
May 21 14:03:40 vultr.guest bee[62084]:         github.com/ethersphere/bee/cmd/bee/main.go:15 +0x26
May 21 14:03:40 vultr.guest systemd[1]: bee.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 14:03:40 vultr.guest systemd[1]: bee.service: Failed with result 'exit-code'.
May 21 14:03:46 vultr.guest systemd[1]: bee.service: Scheduled restart job, restart counter is at 2044.
May 21 14:03:46 vultr.guest systemd[1]: Stopped Bee - Ethereum Swarm node.

**Comment by acud** [comment]
Closing this issue since this version is very outdated and we haven't seen this recently. Please open a new issue if the problem persists
