### ISSUE TITLE
Bee gets suck at "Waiting for chequebook deployment in transaction xxxxx"

### ISSUE THREAD

**Issue by iecies** [ethersphere/bee#1815]
#### Summary
Bee node gets suck at "Waiting for chequebook deployment in transaction xxxxx"

#### Steps to reproduce
1. ETH network got congested.
2. Start bee node. 
3. Sprinkle it.
4.  Bee node gets suck at "Waiting for chequebook deployment in transaction xxxxxx".
5. After 3 hours, restart bee node.
6. Bee node still gets suck at "Waiting for chequebook deployment in transaction xxxxxx". 

#### Expected behavior
Bee node starts successfully.

#### Actual behavior
Bee node gets suck at "Waiting for chequebook deployment in transaction xxxxxx".
By checking the tx hash at etherscan,  the transaction has been dropped because of timeout (more than 3 hours).

#### Condition
This will only happen when ETH network got congested.

#### Root cause
The state store holds the tx hash and bee node uses it without checking the transaction state from blockchain,  which leads node gets suck even restart. 

#### Suggest fix
Add the checking of state of tx hash before using it from store in bee node client.

**Comment by acud** [comment]
This should be improved as we moved to xDai network. In addition, other improvements got implemented so that chequebook deployment gas limits could be adjusted on node startup
