### ISSUE TITLE
Bee cheque problems

### ISSUE THREAD

**Issue by nugaon** [ethersphere/bee#1816]
#### Summary

I tried to push random data continuously to a Bee node (A) in a 5 node network, meanwhile I was polling the cheques from an other connected Bee node (B).
Until the interruption of the data generation script, the Bee node (B) hadn't got any cheques and when Bee Node (A) was not on load anymore because the generation script stopped, immediately 2 cheques appeared at Bee node (B).

It seems like Bee node cannot issue cheques on high load - in this case when tries to process and push the updated chunks.  

Other problem is on this little network every node connected with each other, but still I got more than 1 cheque at Bee node (B).
My exceptation would be only Bee node (A) is in debt to Bee node (B) because that is the only point where the data is uploaded and populated from, so
- the nodes have the full list of the others on the network, so basically with one hop it would be possible to send any message.
- eventually other node accumulated more debt than Bee node (A), when the actual data upload had happened only at Bee node (A).

Lastly, but not least after stopping the uploads, the Bee node (A) floods with log message repeating the following:
```
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer fbfe295a5e5bd716d8c540c49beec532d87f39e3d298290f5679985601b2276d: reserve balance for peer fbfe295a5e5bd716d8c540c49beec532d87f39e3d298290f5679985601b2276d: attempted overdraft"
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: reserve balance for peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: attempted overdraft"
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: reserve balance for peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: attempted overdraft"
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer fbfe295a5e5bd716d8c540c49beec532d87f39e3d298290f5679985601b2276d: reserve balance for peer fbfe295a5e5bd716d8c540c49beec532d87f39e3d298290f5679985601b2276d: attempted overdraft"
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: reserve balance for peer 3b1b2aff113e77b78ee96a29046a07a2408424d75fa7371bf4f49607587e68d5: attempted overdraft"
time="2021-05-21T13:08:56Z" level=debug msg="could not push to peer 61b5e550df598d68e35741680bea2af6961679167846b81e33b6b7ae7bdf303c: reserve balance for peer 61b5e550df598d68e35741680bea2af6961679167846b81e33b6b7ae7bdf303c: attempted overdraft"
```

#### Steps to reproduce

I [have a branch for this problem in Bee-factory](https://github.com/ethersphere/bee-factory/pull/36) to reconstruct this state
```sh
git clone --branch refactor/traffic-gen-promise-all https://github.com/ethersphere/bee-factory.git
cd bee-factory
npm i
npm run run:env -- start --ephemeral
# the following script is generating traffic, normally it would stop at 3 cheques, 
# but it won't because the before mention problem,
# so you have to interrupt with Ctrl^C after a time  
npm run gen:traffic -- 3
```

During the traffic generation you can request for cheques by `swarm-cli` or by `curl` independently from this process, it won't show any, until you stop the traffic generation command. _If you execute that again it will successfully exit from the loop because the node could issue the cheque(s) meanwhile_.

#### Expected behavior

- Only one incoming cheque (from Bee node (A)) of Bee node (B)
- The cheques can be issued on load.
- resolve push peer problem - maybe related to the cheque issuance.

**Comment by Eknir** [comment]
Thank you for identifying this! What is the approximate rate of upload from which you start to see problems?

**Comment by nugaon** [comment]
The quoted logs appeared immediately after the first upload attempt - though the traffic generation script tries to upload random data for 400 chunks in every cycle.

**Comment by Eknir** [comment]
@metacertain @ralph-pichler , you applied fixes for this, right? If so, @nugaon should perhaps try it out again in his setup, see if there are improvements.

**Comment by acud** [comment]
@nugaon is this still relevant?
