### ISSUE TITLE
Price oracle for bandwidth and initial costs

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1819]
# Intro
There is a need for having a price oracle that quotes the exchange rate between honey (accounting credits) and BZZ. Nodes query this value before sending/receiving a cheque and hence value the BZZ cheque at a certain honey-worth. 

The price oracle is a smart-contract on the blockchain that may internally gets its price from the bonding curve or another source. The maintenance of the price oracle is done by an Ethereum smart-contract, which initially is controlled by a set of trusted keys, but may later transition to being controlled by BZZ token holders.

Initially, a price oracle was not great to have, as services that were rendered in the past might have a radically different value at the moment of settlement. With time based settlement, it is much more likely that a settlement comes at the time when the services are delivered.

# Architecture
## Smart-contract
Exposes:
- Exchange rate
        - How many accounting units does 1 PLUR give me?
 - Initial cost
        - Deducted from first payment from a peer *ever*. Reject payment if less.

## Reading price in bee
There is a service that polls the contract each X minutes sharp. All nodes poll at the same time. If there are minor time differences and the block with the price update is mined at the time that nodes poll, it may happen that part of the network accounts with a different price for X minutes.

## Using price information
The price information is used when sending a cheque:

1. Settler sends message header to receiver, signalling it wants to monetary-settle
2. Receiver returns current exchange rate and deduction if applicable
3. Settler validates exchange rate and deduction with it's own version of the truth
    - If corresponding
        - Settler issue cheque to Abel and updates accounting if write succeeds
        - Receiver receives cheque and updates accounting
    - If not corresponding
        - Settler reset stream

- consider timeout of streams
    - We may want to prevent a node to indefinitely keep a stream open and engage in option-buying behavior (may also be as an update at a later time)
        - timeout
        - If the receiving party, based on their version of time, receives the cheque too long after the exchange rate was issues => apply current exchange rate

**Comment by acud** [comment]
this is already done and live on xdai
