### ISSUE TITLE
Error: init chain: dial eth client: dial tcp [::1]:8546: connect: connection refused

### ISSUE THREAD

**Issue by 15280012543** [ethersphere/bee#1820]
WARN[2021-05-21T15:11:38+08:00] clef is not enabled; portability and security of your keys is sub optimal 
INFO[2021-05-21T15:11:38+08:00] new swarm network address created: c7467c074ecd39a28f9cbd7f6ef6b37b8f8ed614c9e68a40f9c15e72a6980c87 
INFO[2021-05-21T15:11:38+08:00] swarm public key 0355a3a1e2722b9daf49e9c4e909c55079537b672b34ba64ad7324b6e7a541b434 
INFO[2021-05-21T15:11:38+08:00] pss public key 03c56d1498d4d2fee38c4301784c75abec2b5541e9301c47e5a77d2868412098f6 
INFO[2021-05-21T15:11:38+08:00] using ethereum address 823a444318ef8f498a8760bb9f2363028d9ad8d4 
Error: init chain: dial eth client: dial tcp [::1]:8546: connect: connection refused
[root@iZp0wgi0uj2bxtsemdwopeZ ~]#

**Comment by potato1992** [comment]
same for me. Ubuntu20.04

**Comment by HawxGT** [comment]
Same here. Ubuntu20.04

**Comment by yihao1997** [comment]
same for me. Windows

**Comment by HCMY** [comment]
> same for me. Ubuntu20.04
you need setup your Blockchain Endpoints, see this:
https://docs.ethswarm.org/docs/installation/install

**Comment by HCMY** [comment]
you need setup your Blockchain Endpoints, and set up parameters in yout bee.yaml file or via command line, 
see this intructions:
https://docs.ethswarm.org/docs/installation/install

**Comment by adrianzhang** [comment]
> you need setup your Blockchain Endpoints, and set up parameters in yout bee.yaml file or via command line,
> see this intructions:
> https://docs.ethswarm.org/docs/installation/install

Hi HCMY,

Problem is that the error still exist while configure endpoint address and restart bee service on Ubuntu 20.04. I followed the guide which in your link, it says the endpoint address would be swap-endpoint: wss://goerli.infura.io/ws/v3/your-api-key , I get my api key and pasted. 

Any further advice? Thanks in advance!

**Comment by adrianzhang** [comment]
> > you need setup your Blockchain Endpoints, and set up parameters in yout bee.yaml file or via command line,
> > see this intructions:
> > https://docs.ethswarm.org/docs/installation/install
> 
> Hi HCMY,
> 
> Problem is that the error still exist while configure endpoint address and restart bee service on Ubuntu 20.04. I followed the guide which in your link, it says the endpoint address would be swap-endpoint: wss://goerli.infura.io/ws/v3/your-api-key , I get my api key and pasted.
> 
> Any further advice? Thanks in advance!

More info:

The error from systemd log is:
Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused

when I use netstat to check but there is no process listening on this port.
Would it be a bee-clef problem?

**Comment by adrianzhang** [comment]
> > > you need setup your Blockchain Endpoints, and set up parameters in yout bee.yaml file or via command line,
> > > see this intructions:
> > > https://docs.ethswarm.org/docs/installation/install
> > 
> > 
> > Hi HCMY,
> > Problem is that the error still exist while configure endpoint address and restart bee service on Ubuntu 20.04. I followed the guide which in your link, it says the endpoint address would be swap-endpoint: wss://goerli.infura.io/ws/v3/your-api-key , I get my api key and pasted.
> > Any further advice? Thanks in advance!
> 
> More info:
> 
> The error from systemd log is:
> Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused
> 
> when I use netstat to check but there is no process listening on this port.
> Would it be a bee-clef problem?

Solved

ws endpoint in configuration should be set as public url, default one which is localhost 8546 doesn't work.

**Comment by cacacai** [comment]
if user the command start like that 
`bee.exe start --config bee.yaml` 
May reproduce the problem, you need to use the following command
The configuration file needs to use an absolute path
`bee.exe start --config ./bee.yaml`

**Comment by ColinWang1203** [comment]
My docker-compose failed using the ws://localhost:8546, but my xdai node is fully synced and connectable.

Is there any solution yet?

bee-1_1  | time="2021-07-10T06:26:38Z" level=info msg="version: 1.0.0-2572fa48"
bee-1_1  | time="2021-07-10T06:26:38Z" level=info msg="debug api address: [::]:1635"
bee-1_1  | Error: init chain: dial eth client: dial tcp 127.0.0.1:8546: connect: connection refused

**Comment by mfw78** [comment]
This is a general configuration problem whereby you have started `bee` in a docker container, and therefore the loopback address refers to that docker container itself. If using the official `bee` docker containers, there is no RPC endpoint included, and therefore you will get this error as you're trying to connect to a service that doesn't exist.

You can either choose to add in a container into your `docker-compose` setup, using either geth (for goerli), or nethermind / openethereum (for xdai). Then you would use the docker container name to connect to it from the `bee` node. 

Further support for this is outside the context of Github, and you're recommended to contact support on Discord at the [#bee-mainnet-support](https://discord.gg/ndtEp368) channel, or the #bee-testnet-support channel respectively.
