### ISSUE TITLE
flag provided but not defined: -L/usr/local/opt/ruby/lib

### ISSUE THREAD

**Issue by winkee01** [ethersphere/bee#1821]
I am trying to build from source on macOS, but executing `make binary` gives me this error

```
flag provided but not defined: -L/usr/local/opt/ruby/lib
```

Go version: go1.15 & go1.16
macOS: Big Sur 11.3.1
Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin18]

**Comment by winkee01** [comment]
When I remove the flag and manually execute: `go build -trimpath -o dist/bee ./cmd/bee`, the build will be successful.

**Comment by acud** [comment]
not sure what this is about but I've never seen this before. Probably something related to your local setup (we have nothing even remotely related to ruby).
