### ISSUE TITLE
The same problem exists, but I configured “- BEE_DATA_DIR=/home/C23_SD01/node1” in docker-compose.yml config, boot found error "Error: libp2p key: mkdir /home/C23_SD01: permission denied", the file directory "/home/C23_SD01" has been set to 777, user is root.   In ".env" has same problem.

### ISSUE THREAD

**Issue by linht8** [ethersphere/bee#1822]
The same problem exists, but I configured “- BEE_DATA_DIR=/home/C23_SD01/node1” in docker-compose.yml config, boot found error "Error: libp2p key: mkdir /home/C23_SD01: permission denied", the file directory "/home/C23_SD01" has been set to 777, user is root.   In ".env" has same problem.

services:
  clef-1:
    image: ethersphere/clef:0.4.9
    restart: unless-stopped
    environment:
      - CLEF_CHAINID
    privileged: true
    volumes:
      - clef-1:/app/data
    command: full
  bee-1:
    image: ethersphere/bee:0.5.3
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-1:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      **- BEE_DATA_DIR=/home/C23_SD01/node1**
      - BEE_DB_CAPACITY
      
bee-1_1   | Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
bee-1_1   |                 \     /
bee-1_1   |             \    o ^ o    /
bee-1_1   |               \ (     ) /
bee-1_1   |    ____________(%%%%%%%)____________
bee-1_1   |   (     /   /  )%%%%%%%(  \   \     )
bee-1_1   |   (___/___/__/           \__\___\___)
bee-1_1   |      (     /  /(%%%%%%%)\  \     )
bee-1_1   |       (__/___/ (%%%%%%%) \___\__)
bee-1_1   |               /(       )\
bee-1_1   |             /   (%%%%%)   \
bee-1_1   |                  (%%%)
bee-1_1   |                    !
bee-1_1   | time="2021-05-21T17:07:49Z" level=info msg="version: 0.5.3-acbd0e2"
bee-1_1   | time="2021-05-21T17:07:49Z" level=info msg="using swarm network address through clef: 7b7db6df84dc6ff07180cba83421dd6f40294f45c1d81a3b3241906aa199c0ad"
bee-1_1   | time="2021-05-21T17:07:49Z" level=info msg="swarm public key 03a1cc0bd90f80519dfc00cddef6c706a9cc797e58210cfdda1a5f3dcc781c05c0"
**bee-1_1   | Error: libp2p key: mkdir /home/C23_SD01: permission denied**

_Originally posted by @linht8 in https://github.com/ethersphere/bee/issues/1649#issuecomment-846113628_

**Comment by Eknir** [comment]
Hey, thanks. I re-opened #1649 and will track this issue there
