### ISSUE TITLE
node started but didn't spend bzz

### ISSUE THREAD

**Issue by chx8223** [ethersphere/bee#1830]
#### Summary
My node started and it did not spend the  bzz, and it still can cashout the tickets. Why?https://goerli.etherscan.io/address/0x9621e1f1d62074998c3b9c951b07638c7626db00#tokentxns

#### Expected behavior
Even if you don't stake bzz, you can still start a node to get rewards

**Comment by acud** [comment]
you need bzz for operations that cost bzz, like retrieving or uploading content. if you just serve content you earn bzz.
