### ISSUE TITLE
connect to bootnode failed.

### ISSUE THREAD

**Issue by totodata** [ethersphere/bee#1831]
how to get a new bootnode in config yaml file?

INFO[2021-05-22T10:00:20+08:00] api address: [::]:1633                       
TRAC[2021-05-22T10:00:20+08:00] kademlia balanced connector took 4.446µs to finish 
TRAC[2021-05-22T10:00:20+08:00] kademlia iterator took 25.22µs to finish     
DEBU[2021-05-22T10:00:20+08:00] kademlia has no connected peers, trying bootnodes 
TRAC[2021-05-22T10:00:20+08:00] connecting to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW 
DEBU[2021-05-22T10:00:21+08:00] connect fail /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW: connect new stream: incompatible stream: protocol not supported 
WARN[2021-05-22T10:00:21+08:00] connect to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW 
DEBU[2021-05-22T10:00:21+08:00] discover fail /dnsaddr/bootnode.ethswarm.org: discover /dnsaddr/swarm-3.bootnode.ethswarm.org: discover /dnsaddr/bee-9.bootnode.ethswarm.org: discover /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLoebk5rUbHsiYKvMpBHW: connect new stream: incompatible stream: protocol not supported 
WARN[2021-05-22T10:00:21+08:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org 
TRAC[2021-05-22T10:00:51+08:00] kademlia balanced connector took 3.066µs to finish 
TRAC[2021-05-22T10:00:51+08:00] kademlia iterator took 38.754µs to finish    
DEBU[2021-05-22T10:00:51+08:00] kademlia has no connected peers, trying bootnodes 
TRAC[2021-05-22T10:00:51+08:00] connecting to bootnode /ip4/52.3.228.231/tcp/31307/p2p/16Uiu2HAmGPGL4hhxj2KQK7i3ZjaqYXP2tUreJskHQdqNVHLHvVfq 
DEBU[2021-05-22T10:00:53+08:00] connect fail /ip4/52.3.228.231/tcp/31307/p2p/16Uiu2HAmGPGL4hhxj2KQK7i3ZjaqYXP2tUreJskHQdqNVHLHvVfq: connect new stream: incompatible stream: protocol not supported 
WARN[2021-05-22T10:00:53+08:00] connect to bootnode /ip4/52.3.228.231/tcp/31307/p2p/16Uiu2HAmGPGL4hhxj2KQK7i3ZjaqYXP2tUreJskHQdqNVHLHvVfq 
DEBU[2021-05-22T10:00:53+08:00] discover fail /dnsaddr/bootnode.ethswarm.org: discover /dnsaddr/swarm-2.bootnode.ethswarm.org: discover /dnsaddr/bee-7.bootnode.ethswarm.org: discover /ip4/52.3.228.231/tcp/31307/p2p/16Uiu2HAmGPGL4hhxj2KQK7i3ZjaqYXP2tUreJskHQdqNVHLHvVfq: connect new stream: incompatible stream: protocol not supported 
WARN[2021-05-22T10:00:53+08:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org

**Comment by liruishan** [comment]
@totodata ,I ran into the same problem, and I haven't found a solution yet. Has your problem been solved?

**Comment by eazlong** [comment]
I have gotten this problem too.

**Comment by zhangrui231** [comment]
I have gotten this problem too.

**Comment by myscl123** [comment]
I have gotten this problem too.

**Comment by liruishan** [comment]
I update  bee to version 0.6.0 and  solve this problem

发自我的iPhone

**Comment by IMJacky** [comment]
i have the same error 
`"discover fail /dnsaddr/bootnode.ethswarm.org: dns resolve address /dnsaddr/bootnode.ethswarm.org: lookup _dnsaddr.bootnode.ethswarm.org: dnsquery: This operation returned because the timeout period expired`

version：0.6.1

**Comment by liruishan** [comment]
> i have the same error
> `"discover fail /dnsaddr/bootnode.ethswarm.org: dns resolve address /dnsaddr/bootnode.ethswarm.org: lookup _dnsaddr.bootnode.ethswarm.org: dnsquery: This operation returned because the timeout period expired`
> 
> version：0.6.1

This may be caused by your network problems, if you are in China, you need to use vpn

**Comment by corey-wu** [comment]
> I update bee to version 0.6.0 and solve this problem 发自我的iPhone
> […](#)
> 在 2021年5月22日，14:28，eazlong ***@***.***> 写道： ﻿ I have gotten this problem too. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes ,I update  bee to version 0.6.0 and  solve this problem too.  Thanks

**Comment by 992185100** [comment]
but v6.0 can't get any cheque .    and have more bugs . 
I've occur this problem long time 
who can tell me why

**Comment by acud** [comment]
this is caused by a bumping of the handshake protocol version. if you're seeing this message you're probably running an outdated version of bee
