### ISSUE TITLE
Can multiple nodes share a wallet address ？多节点可以共享一个钱包地址吗？

### ISSUE THREAD

**Issue by baysmall1** [ethersphere/bee#1836]
当我部署了多个节点之后， 每个节点启动后都会生成自己的钱包地址， 这样不方便管理，  有好的建议？
When I deploy multiple nodes, each node will generate its own wallet address after startup, which is not convenient for management. Do you have any good suggestions?

**Comment by cppfuns** [comment]
Unfortunately, there must be one-to-one, software design architecture issues
https://www.bcskill.com/index.php/archives/1098.html

**Comment by EricCode1983** [comment]
https://bzz.ethswarm.org/ this website not work, cant change the gETH to gBZZ

**Comment by baysmall1** [comment]
> Unfortunately, there must be one-to-one, software design architecture issues
> https://www.bcskill.com/index.php/archives/1098.html

我尝试把/var/lib/bee/下的所有文件复制到新节点并启动bee， 在启动过程中有看到 钱包地址与老节点一致 ，请问这样会有问题吗？

**Comment by y19818** [comment]
> Unfortunately, there must be one-to-one, software design architecture issues
> https://www.bcskill.com/index.php/archives/1098.html

I think the article you shared was very helpful to me Thanks

**Comment by ldeffenb** [comment]
> > Unfortunately, there must be one-to-one, software design architecture issues
> > https://www.bcskill.com/index.php/archives/1098.html
> 
> 我尝试把/var/lib/bee/下的所有文件复制到新节点并启动bee， 在启动过程中有看到 钱包地址与老节点一致 ，请问这样会有问题吗？

YES, that will be a problem.  You may not see anything immediately, but peers will get confused about seeing the same Overlay address on two different connections, the transaction nonce will get messed up when cashouts occur asynchronously between the nodes, and all manner of chaos will follow due to this sharing of Ethereum addresses.
