### ISSUE TITLE
update to 0.6.1,there is ERROR

### ISSUE THREAD

**Issue by jixiang-jlwolf** [ethersphere/bee#1841]
E:\swarm>bee start --config bee-default.yaml

Welcome to the Swarm.... Bzzz Bzzzz Bzzzz

               .-.         .--''-.
             .'   '.     /'       '
             '.     '. ,'          |
   _        o    '.o   ,'        _.-'
 .\ /.       \.--./'. /.:. :._:.'
< ~O~ >    .'    '._-': ': ': ': ':
 '/_\'     :(.) (.) :  ': ': ': ': ':>-
 \ | /      ' ____ .'_.:' :' :' :' :'
  \|/        '\<>/'/ | | :' :' :'
   |               \  \ \
   |                '  ' '

time="2021-05-22T21:01:27+08:00" level=info msg="version: 0.6.1-79ad7f08"
Password:
time="2021-05-22T21:01:30+08:00" level=warning msg="clef is not enabled; portability and security of your keys is sub optimal"
time="2021-05-22T21:01:31+08:00" level=info msg="using existing swarm network address: 4f179a401fcd248434ec5fdd38d53ceaac40d7fb809ca5b7b3481bc3d3c523a3"
time="2021-05-22T21:01:31+08:00" level=info msg="swarm public key 020f2da0a86735b1956cfbe5614763ec35b21d870097803f384e17662b9ec52900"
time="2021-05-22T21:01:31+08:00" level=debug msg="using existing libp2p key"
time="2021-05-22T21:01:31+08:00" level=debug msg="using existing pss key"
time="2021-05-22T21:01:31+08:00" level=info msg="pss public key 0227e8185ccc9102bfcee0e3360e8e4a75c5eb53189ae675d55726545bcf21496e"
time="2021-05-22T21:01:31+08:00" level=info msg="using ethereum address 86f2a336973b28746e759900f01f8ec5d4cf5d20"
time="2021-05-22T21:01:31+08:00" level=info msg="debug api address: 127.0.0.1:1635"
time="2021-05-22T21:01:33+08:00" level=info msg="using default factory address for chain id 5: 73c412512e1ca0be3b89b77ab3466da6a1b9d273"
time="2021-05-22T21:01:34+08:00" level=info msg="using existing chequebook 394346c49d2644fd447befe3900f746a27a0fad5"
time="2021-05-22T21:01:34+08:00" level=info msg="using the chequebook transaction hash 528e2a14d069444991a19744927b8fa069e33ab312ee72ee74cb1cac7a4a8c54"
time="2021-05-22T21:01:35+08:00" level=info msg="using datadir in: 'e:/.bee'"
time="2021-05-22T21:01:35+08:00" level=info msg="database capacity: 1000000 chunks (approximately 20.3GB)"
time="2021-05-22T21:01:35+08:00" level=info msg="localstore migration: found current localstore schema code, migrate to yuj, total migrations 2"
time="2021-05-22T21:01:35+08:00" level=info msg="localstore migration: need to run 1 data migrations on localstore to schema code"
time="2021-05-22T21:01:35+08:00" level=debug msg="truncating indexes"
time="2021-05-22T21:01:35+08:00" level=debug msg="truncating pullsync index"
time="2021-05-22T21:01:58+08:00" level=debug msg="truncate writing batch. processed 10000"
Error: localstore: truncate pullsync index: index iterator function: leveldb/table: corruption on data-block (pos=1533258): checksum mismatch, want=0x595ccc2d got=0xc9d75c8a [file=1109624.ld
b]

E:\swarm>

**Comment by dudebing99** [comment]
encountered the same problem as the following log:
```
May 22 23:24:31  bee[21418]: time="2021-05-22T23:24:31+08:00" level=info msg="localstore migration: found current localstore schema code, migrate to yuj, total migrations 2"
May 22 23:24:31  bee[21418]: time="2021-05-22T23:24:31+08:00" level=info msg="localstore migration: need to run 1 data migrations on localstore to schema code"
[23:27]
```

from v0.5.3 to 0.6.1

**Comment by chijiao** [comment]
just rm -rf localstore , restart again. working now

**Comment by acud** [comment]
stale - closing
