### ISSUE TITLE
the current version of "docker-compose.yml" is missing environment variable "BEE_FULL_NODE"

### ISSUE THREAD

**Issue by saronic** [ethersphere/bee#1842]
#### Summary
docker-compose.yml in "https://raw.githubusercontent.com/ethersphere/bee/master/packaging/docker/docker-compose.yml" is missing a environment variable "BEE_FULL_NODE"

**Comment by mfw78** [comment]
Fixed in https://github.com/ethersphere/bee/commit/ebae0f1c9746f7d40bfab02ee637c851499c3436
