### ISSUE TITLE
peers is empty 

### ISSUE THREAD

**Issue by efgod** [ethersphere/bee#1843]
#### Summary
 curl -s localhost:1635/peers
{"peers":[]}

#### Steps to reproduce

start bee, there is the log:

INFO[2021-05-22T11:10:29-04:00] version: 0.5.3-acbd0e2
INFO[2021-05-22T11:10:29-04:00] using swarm network address through clef: 5b6cee814d8a10980ade1739c1717453a2a188f9d2cef8
4c99326d69abf1c5b0
INFO[2021-05-22T11:10:29-04:00] swarm public key 0319e3fadf0359d753e3a125273aa20d47621da170c53e138b470dbe14accfaaac
INFO[2021-05-22T11:10:30-04:00] pss public key 03cafca58c4346b0199b067f9c08190526967bff627ba75e2352e13767a297f37d
INFO[2021-05-22T11:10:30-04:00] using ethereum address c90d1ae202add9bcc6f79dd4d03bbe11cdfe8d21
INFO[2021-05-22T11:10:30-04:00] debug api address: 127.0.0.1:1635
INFO[2021-05-22T11:10:30-04:00] using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474
INFO[2021-05-22T11:10:31-04:00] using existing chequebook f5823fc7d4625603221b8880baf60762648b7348
INFO[2021-05-22T11:10:39-04:00] database capacity: 5000000 chunks (approximately 19.5GB)
INFO[2021-05-22T11:10:39-04:00] name resolver: no name resolution service provided
INFO[2021-05-22T11:10:39-04:00] api address: [::]:1633
WARN[2021-05-22T11:10:45-04:00] connect to bootnode /ip4/54.167.196.243/tcp/31303/p2p/16Uiu2HAm4frXQ2vDhuuZhzrQqX69f4t4h
adbDyUvz97Dmwkz9GrT
WARN[2021-05-22T11:10:45-04:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org
WARN[2021-05-22T11:11:15-04:00] connect to bootnode /ip4/54.210.29.30/tcp/31300/p2p/16Uiu2HAmUC3GsAfnZhVyYz5suYYCkKE9TCv
JnLWT75EeoqpDarCM
WARN[2021-05-22T11:11:15-04:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org
WARN[2021-05-22T11:11:46-04:00] connect to bootnode /ip4/52.90.206.204/tcp/31309/p2p/16Uiu2HAmLe8hu7N9cnkY4BjwjtdfsPzYLo
ebk5rUbHsiYKvMpBHW
WARN[2021-05-22T11:11:46-04:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org

**Comment by grivasjon** [comment]
@efgod  This is not a bug, you can't use 0.5.3 anymore. The boot nodes were shut down and you must migrate to 0.6.x
