### ISSUE TITLE
No data in localstore folder version 0.6.1

### ISSUE THREAD

**Issue by FX336494** [ethersphere/bee#1844]
No data in localstore folder version 0.6.1

**Comment by a734718092** [comment]
我也是同样的问题

**Comment by cppfuns** [comment]
Waiting for the 0.6.2 version, currently 0.6.1 is also unable to produce tickets normally

Welcome to join the Swarm Chinese technical community www.bcskill.com

**Comment by acud** [comment]
Closing this ticket as there's not enough information  here. Please use our issue template when opening new issues
