### ISSUE TITLE
When running for 2 hours, the number of connections reaches 85, but there is no load on CPU and network. Is this normal?

### ISSUE THREAD

**Issue by z724133545** [ethersphere/bee#1846]
When running for 2 hours, the number of connections reaches 85, but there is no load on CPU and network. Is this normal?
When I was running on version 0.5.3, the CPU was 80-90%, and the network was 1-2m to upload and download！
Is this a bug or update optimization？

**Comment by acud** [comment]
The load depends on the amount of traffic which is caused by syncing and retrieve requests. This is indeed possible. Bee is built to be environmentally friendly :)
