### ISSUE TITLE
cash out error

### ISSUE THREAD

**Issue by lemonlml** [ethersphere/bee#1847]
[root@ecs-d88c-0003 ~]# ./cashout.sh 
2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d 123000000000
1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c 125000000000
[root@ecs-d88c-0003 ~]# ./cashout.sh cashout-all
uncashed cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c (125000000000 uncashed)
could not cash out cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c: 500 cannot cash cheque
uncashed cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d (123000000000 uncashed)
could not cash out cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d: 500 cannot cash cheque
[root@ecs-d88c-0003 ~]# ./cashout.sh cashout-all
uncashed cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c (125000000000 uncashed)
could not cash out cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c: 500 cannot cash cheque
uncashed cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d (123000000000 uncashed)
could not cash out cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d: 500 cannot cash cheque
[root@ecs-d88c-0003 ~]# ./cashout.sh cashout-all
uncashed cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c (125000000000 uncashed)
could not cash out cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c: 500 cannot cash cheque
uncashed cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d (123000000000 uncashed)
could not cash out cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d: 500 cannot cash cheque
[root@ecs-d88c-0003 ~]# ./cashout.sh cashout-all
uncashed cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c (125000000000 uncashed)
could not cash out cheque for 1facf5ef01551d313e41ce4d74a4ab10c2edd77fa9502a6f2a2b4023c329949c: 500 cannot cash cheque
uncashed cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d (123000000000 uncashed)
could not cash out cheque for 2d3a8252830a18e4da12b58c4f2fb232decb4297d907608761d8cfb76d51540d: 500 cannot cash cheque

**Comment by wyh136** [comment]
I think your goerli rpc backend was  limited.

**Comment by lemonlml** [comment]
Jam? But the frequency is too high

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question, and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
