### ISSUE TITLE
Error: chequebook init: storage: not found

### ISSUE THREAD

**Issue by Skjold** [ethersphere/bee#1848]
#### Summary
I've changed the Docker tag from 0.5.3 to 0.6.0 before reading the upgrade guide, and started getting these errors:
```
Error: chequebook init: storage: not found
```
The main log reads this:
```
time="2021-05-22T22:45:28Z" level=info msg="version: 0.6.0-67cc8f24"
time="2021-05-22T22:45:28Z" level=info msg="using swarm network address through clef: %redacted%"
time="2021-05-22T22:45:28Z" level=info msg="swarm public key %redacted%"
time="2021-05-22T22:45:29Z" level=info msg="pss public key %redacted%"
time="2021-05-22T22:45:29Z" level=info msg="using ethereum address %redacted%"
time="2021-05-22T22:45:29Z" level=info msg="debug api address: [::]:1635"
time="2021-05-22T22:45:29Z" level=info msg="using default factory address for chain id 5: 73c412512e1ca0be3b89b77ab3466da6a1b9d273"
time="2021-05-22T22:45:29Z" level=info msg="waiting for chequebook deployment in transaction %redacted%"
```

I've followed the guide and restarted containers after following the steps (removed the localstore folder's contents,, added full-node: true to bee.yaml), but the error persists.

What do you recommend?

**Comment by Porco-Rosso** [comment]
I'm having the same error. Same situation, just updated, since apparently when I had installed 0.6 was not the version in the docs last week. Been trying to join the network for a week now :(

**Comment by Porco-Rosso** [comment]
Here is some additional information of mine:
Debian 10, installed via the .deb package
; v0.5.3 upgraded to 0.6.0 after I kept failing to create chequebook after a few days of waiting for transaction. Did not manually delete any folders.

Been getting a loop between these errors:

'Error: init chain: is synced: no trusted canonical hash trie'
'Error: chequebook init: storage: not found'
'Error: factory fail: getDeleteStateObject (73c412512e1ca0be3b89b77ab3466da6a1b9d273) error: no suitable peers available'

Here is my config:
<details><summary>/etc/bee/bee.yaml</summary>
<p>
```
## Bee configuration - https://gateway.ethswarm.org/bzz/docs.swarm.eth/docs/installation/configuration/

## HTTP API listen address (default ":1633")
# api-addr: :1633
## initial nodes to connect to (default [/dnsaddr/bootnode.ethswarm.org])
# bootnode: [/dnsaddr/bootnode.ethswarm.org]
## cause the node to always accept incoming connections
# bootnode-mode: false
## enable clef signer
clef-signer-enable: true
## clef signer endpoint
clef-signer-endpoint: /var/lib/bee-clef/clef.ipc
## config file (default is /home/<user>/.bee.yaml)
config: /etc/bee/bee.yaml
## origins with CORS headers enabled
# cors-allowed-origins: []
## data directory (default "/home/<user>/.bee")
data-dir: /mnt/bee-data
## db capacity in chunks, multiply by 4096 to get approximate capacity in bytes
db-capacity: 10000000
## number of open files allowed by database
db-open-files-limit: 1000
## size of block cache of the database in bytes
# db-block-cache-capacity: 33554432
## size of the database write buffer in bytes
# db-write-buffer-size: 33554432
## disables db compactions triggered by seeks
# db-disable-seeks-compaction: false
## debug HTTP API listen address (default ":1635")
debug-api-addr: 127.0.0.1:1635
## enable debug HTTP API
debug-api-enable: true
full-node: true
## disable a set of sensitive features in the api
# gateway-mode: false
## enable global pinning
# global-pinning-enable: false
## NAT exposed address
# nat-addr: ""
## ID of the Swarm network (default 1)
# network-id: 1
## P2P listen address (default ":1634")
# p2p-addr: :1634
## enable P2P QUIC protocol
# p2p-quic-enable: false
## enable P2P WebSocket transport
# p2p-ws-enable: false
## password for decrypting keys
# password: ""
## path to a file that contains password for decrypting keys
password-file: /var/lib/bee/password
## amount in BZZ below the peers payment threshold when we initiate settlement (default 1000000000000)
# payment-early: 1000000000000
## threshold in BZZ where you expect to get paid from your peers (default 10000000000000)
# payment-threshold: 10000000000000
## excess debt above payment threshold in BZZ where you disconnect from your peer (default 50000000000000)
# payment-tolerance: 50000000000000
## ENS compatible API endpoint for a TLD and with contract address, can be repeated, format [tld:][contract-addr@]url
# resolver-options: []
## whether we want the node to start with no listen addresses for p2p
# standalone: false
## enable swap (default true)
# swap-enable: true
## swap ethereum blockchain endpoint (default "http://localhost:8545")
#swap-endpoint: https://rpc.slock.it/goerli
swap-endpoint: https://goerli-light.eth.linkpool.io
## swap factory address
# swap-factory-address: ""
## initial deposit if deploying a new chequebook (default 100000000000000000)
swap-initial-deposit: 10000000000000000
## enable tracing
# tracing-enable: false
## endpoint to send tracing data (default "127.0.0.1:6831")
# tracing-endpoint: 127.0.0.1:6831
## service name identifier for tracing (default "bee")
# tracing-service-name: bee
## log verbosity level 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=trace (default "info")
# verbosity: info
## send a welcome message string during handshakes
# welcome-message: 
```
</p>
</details>

**Comment by bumbleshrimp** [comment]
@Porco-Rosso Something tells me this won't solve your problem, but when you upgrade from 0.5.3 to 0.6.x, you need to delete your `/localstore` folder, you can't keep it.

**Comment by mdongsheng** [comment]
> @Porco-Rosso Something tells me this won't solve your problem, but when you upgrade from 0.5.3 to 0.6.x, you need to delete your `/localstore` folder, you can't keep it.

In fact, the localstore is no longer there when this error is reported, you can delete the $DATA_DIR (or ~/.bee) directory and it will work fine, but I don't know what the consequences will be (mine is a new node so it doesn't matter)

**Comment by Skjold** [comment]
Can confirm that deleting localstore didn't help, but deleting statestore did. The consequence of that was losing current progress towards cheques, but eh, at least the nodes work now.

**Comment by Porco-Rosso** [comment]
I didn't delete anything because it does not say to do so in the [automatic update procedures](https://docs.ethswarm.org/docs/working-with-bee/upgrading-bee#automatic-migration-procedure)

> Can confirm that deleting localstore didn't help, but deleting statestore did. The consequence of that was losing current progress towards cheques, but eh, at least the nodes work now.
> Also I've noticed that despite my migration script removing localstore/*, the problematic nodes had the localstore folder completely missing for some reason, though re-creating it didn't help. I'm not sure if its Bee that deleted it or if I messed up; the nodes where this occurred are randomly scattered across the cluster while my scripts are iterative. Could there be a failure condition during migration using Docker that could end up removing the localstore folder if the container was shut down or something?
> Is it possible to somehow manually modify statestore files to resolve this problem in the future without removing them completely, perhaps?

Thanks, I've deleted it and now a new chequebook is being deployed. Unfortunately that probably means I am back to the end of the gETH tx queue... was worried I wouldn't have enough gbzz to deploy but that doesn't seem to have been the case. Now will go back to waiting.
Still getting `error while checking pending transactions: no trusted canonical hash trie` but that might be due to the goerli node I am using. Will give it some time and see what happens. Meanwhile missed out on some potential mining.

**Comment by Porco-Rosso** [comment]
after switching to Infura, which seemed to have helped with the node connection, I am now getting: 
`error while checking pending transactions: header not found`
Guess I'll try to wait this one out as well

**Comment by Porco-Rosso** [comment]
Ended up wiping my statestore and keys and trying again. This time it succeeded...
