### ISSUE TITLE
help

### ISSUE THREAD

**Issue by EverCurse** [ethersphere/bee#1849]
now i have a host.  i want to deploy many nodes with one wallet? is there have solusions? thankx

**Comment by ldeffenb** [comment]
You cannot share Ethereum accounts nor checkbooks with multiple nodes.

One node, one Ethereum account, one checkbook, one configuration, one data-dir, one set of 3 unique ports.

**Comment by EverCurse** [comment]
> You cannot share Ethereum accounts nor checkbooks with multiple nodes. It will not work. Each node must be unique and that uniqueness is based on the Ethereum address.
> 
> One node, one Ethereum account, one checkbook, one configuration, one data-dir, one set of 3 unique ports.



yeah i get. thx.  and another question: many node on one host., and how to use one clef, thx

**Comment by ldeffenb** [comment]
You have to manually create the accounts in bee-clef and then tell each of your nodes which account to use with the following command-line argument:

--clef-signer-ethereum-address string     ethereum address to use from clef signer

I do not know how the password is managed in this usage as I don't use clef (yet).  You may find some hints on this in https://github.com/mfw78/apiarist

**Comment by Eknir** [comment]
Hi there!

Thank you for trying out bee :bee: !
We can better help you with your question in our Discord forum. Hope to see you there, and... Welcome to Swarm.

[Link to Discord](https://discord.gg/QpVwzJ3JKj)
