### ISSUE TITLE
Error migrate

### ISSUE THREAD

**Issue by woyouwole2012** [ethersphere/bee#1850]
#### Summary

Error: migrate: error getting migrations for current schema (clean-interval): could not find current db schema

#### Steps to reproduce

**Comment by ldeffenb** [comment]
Did you try to revert to 0.5.3 from 0.6.0?  If you did, you also need to restore your backed-up copy of statestore and probably delete localstore again.  The database schema in statestore (at least) was migrated in the upgrade, but it cannot automatically migrate in a downgrade.

**Comment by woyouwole2012** [comment]
I have tried ,but it still need 10 gbzz,Is it ok?first time I used > Did you try to revert to 0.5.3 from 0.6.0?  If you did, you also need to restore your backed-up copy of statestore and probably delete localstore again.  The database schema in statestore (at least) was migrated in the upgrade, but it cannot automatically migrate in a downgrade.

**Comment by woyouwole2012** [comment]
新版本的不出票，退回到老版本又要10个gbzz> 我也遇到了，只要再升级回最新版就能正常运行

**Comment by Eknir** [comment]
Hi there,
Welcome to Swarm! I see you are already helped. Please join our Discord for support: https://discord.gg/QpVwzJ3JKj
