### ISSUE TITLE
API：Get all available stamps for this node    404

### ISSUE THREAD

**Issue by zhupengxiang** [ethersphere/bee#1852]
![image](https://user-images.githubusercontent.com/17894209/119309734-434fec80-bca1-11eb-81f2-fc0087e8dc38.png)

bee version:0.5.3

**Comment by aloknerurkar** [comment]
Are you still facing this after the upgrade? What version are you running?

**Comment by zhupengxiang** [comment]
I did not upgrade，the current version is 0.5.3

**Comment by aloknerurkar** [comment]
This API endpoint is only available on v0.6.*
