### ISSUE TITLE
Immutable stamps

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1853]
# User story

## Story

- As a consumer of open data, I want to have the certainty that the attached stamp will be used for the content for the full expected lifetime of the stamp, such that I can use this data in my media.
- As a publisher of data, I want to signal that I don't ever mean to remove this data, such that I can not be coerced to remove it and my consumer can trust that the data will stay in the network for the expected validity of the stamp.

## Background

- Stamps can be diluted (batch increase) or overwritten (once indexed postage stamps are out). Both options would allow the owner of a batch to make the stamps be invalid for certain content it was previously valid for. This is against one of the core primitives of Swarm that access to specific content cannot be blocked or changed once it is online.
- The idea is to introduce a boolean on the postage stamp contract that would prevent dilution on the contract. Furthermore, nodes look at this boolean flag when they see new content from a similar batch to decide whether existing content may be overwritten.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by acud** [comment]
already done
