### ISSUE TITLE
Error: overlay address changed. 

### ISSUE THREAD

**Issue by totodata** [ethersphere/bee#1854]
Error: overlay address changed. was 8dcdfb4cd3e6167ffe475ebaa4f37e8945bd3ba754b55d7fca1436a6eef4e1d5 before but now is 2a2b2f2b97e387996c6f78fcea6813b544264d0b2dd5f756fe1e26be44369399

how to fix it

**Comment by rchlz** [comment]
是不是分别运行了bee-clef和没运行bee-clef时执行了bee start？

**Comment by baysmall1** [comment]
rm -rf /root/.bee

**Comment by matmertz25** [comment]
See #1630 . If your on Ubuntu `rm -r /var/lib/bee/statestore` to clear out the statestore after switching networks
