### ISSUE TITLE
Push to neighborhood, not to closest peer

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1858]
# Problem
- Our push sync protocol is currently only giving back a receipt if you are the closest peer to a chunk. This causes a problem if the closest peer for whatever reason is not reachable. Our retry logic ensures that this closest peer is eventually skipped (making the 2nd closest peer the closest), but this can take a while. Push sync does not need to deliver to the closest peer; as long as it is delivered to some peer in the neighborhood and that peer redundantly spreads it in the neighborhood, push sync can be completed and any peer in the neighborhood may create a receipt.

# Task
- Push sync completes whenever a peer is hit that is within the neighborhood. That peer redundantly pushes in the neigbhorhood and hands out the receipt. This solves: https://github.com/ethersphere/bee/issues/1651

**Comment by ldeffenb** [comment]
AMEN!   I'll be watching for this implementation because I 100% believe this will solve a lot of the upload and retrieval issues that have been plaguing the swarm even in the 0.5.* versions.

**Comment by bumbleshrimp** [comment]
>  Our retry logic ensures that this closest peer is eventually skipped (making the 2nd closest peer the closest), but this can take a while. 

> This solves: #1651

My uploads fail seemingly permanently, they don't eventually correct themselves.  I let one of them try for 2 days and the # of chunks synced did not change after the first 20 minutes and the upload never became available.

**Comment by Eknir** [comment]
A conversation with @esadakar revealed that the implementation of this is not too difficult, but the unit tests of the push sync protocol will need to be adapted (which will cost the most time). 
I believe that this change can be made in such a way that will imply minimal changes to the unit tests, by always attempting to push to the closest peer and only hand out a receipt if a closer peer fails and you are within the neighborhood.

**Comment by Eknir** [comment]
This issue can be validated by requesting chunks individually that were retried by the pusher. If the chunks are retrievable, we know that the chunk was delivered to the neighborhood (service performed), while it is not accepted by the node because there is no receipt.

If only a small percentage of chunks are found, while the pusher is still retrying, this issue is already validated. The bigger the percentage of sucesfull retrieves, the higher the impact will be of fixing this.

**Comment by Eknir** [comment]
Pushing to the neighborhood is a notoriously difficult concept, because the notion of neighborhood might be wildly off for some peers. For this reason, we concluded it is not desirable to push to the neighborhood. Nevertheless, there is a problem if the closest peer to a chunk is not responding for whatever reason, because then the whole neighborhood is attempted, and each peer in the neighborhood will attempt to push to the same, closest, unresponsive peer.

To remedy this, the following PR was introduced: https://github.com/ethersphere/bee/pull/2066.
