### ISSUE TITLE
How to upload a single file

### ISSUE THREAD

**Issue by zhupengxiang** [ethersphere/bee#1865]
I want to upload a picture
![image](https://user-images.githubusercontent.com/17894209/119451350-ba4fb880-bd67-11eb-88d6-616a2a1409d7.png)
![image](https://user-images.githubusercontent.com/17894209/119451372-c176c680-bd67-11eb-84d6-afebdcaeb206.png)

**Comment by zhupengxiang** [comment]
bee version:0.6.0
I have successfully uploaded a picture，"reference": "b22ec35503e569ab5822c6ee8b74c8fdf9e6f09a41666ce403ea28376ad53b9e"
but when I call get file api, the picture does not display

**Comment by acud** [comment]
Hi, please follow the docs at `docs.ethswarm.org`. It is thoroughly documented how to use the API there. If there's any other questions, please use our Discord support channel
