### ISSUE TITLE
clef is not enabled.When is was started bee with docker, a warning was displayed

### ISSUE THREAD

**Issue by Fury76** [ethersphere/bee#1867]
#### Summary
Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
                \     /
            \    o ^ o    /
              \ (     ) /
   ____________(%%%%%%%)____________
  (     /   /  )%%%%%%%(  \   \     )
  (___/___/__/           \__\___\___)
     (     /  /(%%%%%%%)\  \     )
      (__/___/ (%%%%%%%) \___\__)
              /(       )\
            /   (%%%%%)   \
                 (%%%)
                   !
INFO[2021-05-25T08:20:27Z] version: 0.5.3-acbd0e2
WARN[2021-05-25T08:20:27Z] clef is not enabled; portability and security of your keys is sub optimal

#### Steps to reproduce
docker pull ethersphere/bee:0.6.0 

docker run -v /path:/home/bee/.bee  .......

#### Expected behavior
expect no warning

#### Actual behavior
WARN[2021-05-25T08:20:27Z] clef is not enabled; portability and security of your keys is sub optimal

**Comment by Eknir** [comment]
Hi there!
Thank you for trying out Bee!
This is an expected warning message, because clef is not enabled. Please have a look at our docs (docs.ethswarm.org) to learn how to enable clef. 
For further assistance, please join our Discord server for support: https://discord.gg/QpVwzJ3JKj

**Comment by hhenrry501** [comment]
> Hi there!
> Thank you for trying out Bee!
> This is an expected warning message, because clef is not enabled. Please have a look at our docs (docs.ethswarm.org) to learn how to enable clef.
> For further assistance, please join our Discord server for support: https://discord.gg/QpVwzJ3JKj

Is there a window version of how to enable clef?
