### ISSUE TITLE
General problem description

### ISSUE THREAD

**Issue by dockerServices** [ethersphere/bee#1871]
#### Summary

time="2021-05-26T00:35:17+08:00" level=trace msg="waiting for transaction xxxxxxxxxxxxxxxxxx to be mined: not found"
time="2021-05-26T00:35:18+08:00" level=trace msg="waiting for transaction xxxxxxxxxxxxxxxxxx to be mined: not found"
#### Steps to reproduce

cd /mnt/bee/ && nohup bee start   --verbosity 5   --swap-endpoint https://XXXXXXX  --debug-api-enable --clef-signer-enable --clef-signer-endpoint /var/lib/bee-clef/clef.ipc --password xxxxxx >> ./logs/bee.out 2>&1 &

when I curl 'http://localhost:1633' return curl: (7) Failed connect to localhost:1633

#### Expected behavior

when I curl 'http://localhost:1633' return success

**Comment by Eknir** [comment]
You will have to wait until your transaction is included in the Ethereum Goerli blockchain. Use the parameter `--swap-initial-deposit` to speed up your transaction!

**Comment by Eknir** [comment]
For further support, please join our Discord: https://discord.gg/QpVwzJ3JKj
