### ISSUE TITLE
can't start bee with exe

### ISSUE THREAD

**Issue by brant9527** [ethersphere/bee#1872]
Error: init chain: get chain id: Post "https://rpc.goerli.mudit.blog": dial tcp 144.76.236.199:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by ldeffenb** [comment]
That would be a problem with your swap-endpoint specification and/or the server there (...mudit.blog), not a problem with bee.  Please read the following links:

https://docs.ethswarm.org/docs/installation/install#blockchain-endpoints

https://docs.ethswarm.org/docs/FAQ#how-to-set-infuraio-endpoint
