### ISSUE TITLE
bee start error

### ISSUE THREAD

**Issue by Raven2105** [ethersphere/bee#1875]
When I run bee start, it appears：

Error: init chain: dial eth client: websocket: bad handshake (HTTP status 401 Unauthorized)

**Comment by ldeffenb** [comment]
This is likely an error in your swap-endpoint.  Are you sure you have the proper URL there for a goerli network provider and that you have authorized access to that provider via that URL?

**Comment by Eknir** [comment]
Please join our Discord for support: https://discord.gg/QpVwzJ3JKj
