### ISSUE TITLE
bee 0.5.3 run wrong

### ISSUE THREAD

**Issue by freejiu123** [ethersphere/bee#1879]
show:incompatible Stream :protocol not supported。

DEBU[2021-05-27T04:00:41Z] discover fail /dnsaddr/bootnode.ethswarm.org: discover /dnsaddr/swarm-3.bootnode.ethswarm.org: discover /dnsaddr/bee-8.bootnode.ethswarm.org: discover /ip4/54.210.29.30/tcp/31308/p2p/16Uiu2HAmRHY7h1cdpmB6S48MGfwecG3kfhLT9cXpE8SokS9o1Cck: connect new stream: incompatible stream: protocol not  #1649

**Comment by freejiu123** [comment]
![Uploading Screenshot_20210527_084824_com.sonelli.juicessh.jpg…]()

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/1100.html  Look at the end of the article, the startup process for 0.5.3

**Comment by freejiu123** [comment]
> https://www.bcskill.com/index.php/archives/1100.html Look at the end of the article, the startup process for 0.5.3

thanks you very much

**Comment by sonygod** [comment]
still not working ..

**Comment by Eknir** [comment]
Hi there,
Thank you for trying out Bee!
I cannot help you with the given information. Please join our Discord for support: https://discord.gg/QpVwzJ3JKj
