### ISSUE TITLE
Internal response error. event listener sync: websocket: close 1011

### ISSUE THREAD

**Issue by Fury76** [ethersphere/bee#1881]
#### Summary
ERRO[2021-05-26T06:48:14Z] event listener sync: websocket: close 1011 (internal server error): Internal response error

#### Steps to reproduce
started with docker

#### Expected behavior
run narmal

#### Actual behavior
Internal error
<img width="1509" alt="report" src="https://user-images.githubusercontent.com/7465355/119765333-a7fb8900-bee5-11eb-86c8-de8e116e8131.png">

**Comment by ldeffenb** [comment]
The only websocket that I know that bee uses is the swap-endpoint.  So, this error probably means that your swap-endpoint went down while your bee was running.

**Comment by lwmacct** [comment]
@ldeffenb 这个问题怎么处理呢,我也全是这个问题

**Comment by lwmacct** [comment]
@ldeffenb How do I deal with this problem, which I have a lot of nodes with

**Comment by acud** [comment]
This is usually caused by API call limit being exceeded. Please review your infrastructure setup to allow enough API calls per bee node
