### ISSUE TITLE
Multipart form upload

### ISSUE THREAD

**Issue by zhupengxiang** [ethersphere/bee#1882]
Multiple file upload error,How to solve it

![image](https://user-images.githubusercontent.com/17894209/119774148-51e21200-bef4-11eb-8c01-dd9725813610.png)
![image](https://user-images.githubusercontent.com/17894209/119774240-750cc180-bef4-11eb-88f4-4df097eba8f2.png)
![image](https://user-images.githubusercontent.com/17894209/119774274-805fed00-bef4-11eb-95fa-890d56e1d8ff.png)

**Comment by acud** [comment]
Hi, please follow our documentation at `docs.ethswarm.org` and everything should be clear on how to upload directories or files. If the problem still persists please open a new issue and follow the issue template. it would be useful to have the log output from the node
