### ISSUE TITLE
I can't generate my sprinke receiver IP

### ISSUE THREAD

**Issue by LemonYF** [ethersphere/bee#1884]
#### Summary
When I type 'bee-windows-amd64.exe start --config bee.yaml' and enter. It needs me type password, but after I type my password, only show
 ' level=warning msg="learn how to fund your node by visiting our docs at https://docs.ethswarm.org/docs/installation/fund-your-node"
time="2021-05-27T17:13:50+08:00" level=warning msg="cannot continue until there is sufficient ETH (for Gas) and at least 1 BZZ available on d6583XXXXXXXXXXXXXXXX"'

What should I do?
![image](https://user-images.githubusercontent.com/12078353/119806446-ca58cb00-bf14-11eb-9c88-3d66a7115732.png)

**Comment by Eknir** [comment]
Hi there,
Thank you for trying out Bee!
As is written, go to our documentation (docs.ethswarm.org) to see what is next. Pro-tip: join our Discord for support https://discord.gg/QpVwzJ3JKj

Good luck!
