### ISSUE TITLE
bee service can not be run

### ISSUE THREAD

**Issue by viponedream** [ethersphere/bee#1889]
systemctl restrt bee   has wrong message

but   /usr/bin/bee start --config /etc/bee/bee.yaml  runs well. 

`root@swamp:~# systemctl restart bee
root@swamp:~# systemctl  status   bee
● bee.service - Bee - Ethereum Swarm node
     Loaded: loaded (/lib/systemd/system/bee.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2021-05-27 16:17:31 UTC; 4s ago
       Docs: https://docs.ethswarm.org
    Process: 3414 ExecStart=/usr/bin/bee start --config /etc/bee/bee.yaml (code=exited, status=1/FAILURE)
   Main PID: 3414 (code=exited, status=1/FAILURE)

May 27 16:17:31 swamp systemd[1]: bee.service: Main process exited, code=exited, status=1/FAILURE
May 27 16:17:31 swamp systemd[1]: bee.service: Failed with result 'exit-code'.
`

**Comment by Eknir** [comment]
H there, 
Please join our Discord for support: https://discord.gg/QpVwzJ3JKj
