### ISSUE TITLE
PATCH /bzz fails with Internal Server Error: push error during reupload: closest peer: node wants self"

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#1897]
#### Summary

While testing the reupload feature for `swarm-cli` in a test environment (3 nodes), I experience flaky behaviour. `PATCH /bzz` responds with `HTTP 200` the first few times, after that it is always `HTTP 500`, and the message appears in the log:

```
push error during reupload: closest peer: node wants self"
```

**Comment by Eknir** [comment]
I'll assign this one to you, @acud . No need to get this in immediately, but somewhere next week would be good.

**Comment by AuHau** [comment]
I think this issue can be closed as it was resolved with #1980.
