### ISSUE TITLE
docker-compose up --build error?

### ISSUE THREAD

**Issue by yangmiok** [ethersphere/bee#1902]
`| INFO [05-28|09:49:55.919] HTTP endpoint opened                     url=http://[::]:8550/
clef-1_1  | {"jsonrpc":"2.0","method":"ui_onSignerStartup","params":[{"info":{"extapi_http":"http://[::]:8550/","extapi_ipc":"n/a","extapi_version":"6.1.0","intapi_version":"7.0.1"}}]}
bee-1_1   | Bee node is booting up for the first time. Please provide a new password.
bee-1_1   | Password: 
bee-1_1   | Error: inappropriate ioctl for device
bee-1_1   | 
bee-1_1   | Welcome to the Swarm.... Bzzz Bzzzz Bzzzz
bee-1_1   | 
bee-1_1   |                .-.         .--''-.
bee-1_1   |              .'   '.     /'       '
bee-1_1   |              '.     '. ,'          |
bee-1_1   |    _        o    '.o   ,'        _.-'
bee-1_1   |  .\ /.       \.--./'. /.:. :._:.'
bee-1_1   | < ~O~ >    .'    '._-': ': ': ': ':
bee-1_1   |  '/_\'     :(.) (.) :  ': ': ': ': ':>-
bee-1_1   |  \ | /      ' ____ .'_.:' :' :' :' :'
bee-1_1   |   \|/        '\<>/'/ | | :' :' :'
bee-1_1   |    |               \  \ \
bee-1_1   |    |                '  ' '
bee-1_1   | 	
bee-1_1   | 		   
bee-1_1   | time="2021-05-28T09:49:57Z" level=info msg="version: 0.6.0-67cc8f24"
docker_bee-1_1 exited with code 1
docker_bee-1_1 exited with code 1`

**Comment by Eknir** [comment]
Hi there,
We often see this error message if the password is not properly passed. Please join our Discord for further support: https://discord.gg/QpVwzJ3JKj
