### ISSUE TITLE
DNS operation refused

### ISSUE THREAD

**Issue by wingaimo** [ethersphere/bee#1903]
#### Summary
this problem occured:

time="2021-05-28T18:18:23+08:00" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
time="2021-05-28T18:18:53+08:00" level=trace msg="kademlia balanced connector took 0s to finish"
time="2021-05-28T18:18:53+08:00" level=trace msg="kademlia iterator took 0s to finish"
time="2021-05-28T18:18:53+08:00" level=debug msg="kademlia has no connected peers, trying bootnodes"
time="2021-05-28T18:19:01+08:00" level=debug msg="discover fail /dnsaddr/bootnode.ethswarm.org: dns resolve address /dnsaddr/bootnode.ethswarm.org: lookup _dnsaddr.bootnode.ethswarm.org: dnsquery: DNS operation refused."
#### Steps to reproduce

when I use  https://goerli.infura.io/v3/53b4e5cf35db4cf2a3c511ff07916ef6 
as swap-endpoint

whatever it is 0.5.3 or 0.6.1

**Comment by Eknir** [comment]
Hi there,

Thank you for running Bee! :bee: 

I suspect that you run v0.5.3. Please wait a few days until v0.6.2 is out and then try again!
Sorry for the wait.

**Comment by Eknir** [comment]
Join our Discord for support: https://discord.gg/QpVwzJ3JKj
