### ISSUE TITLE
 mapping values are not allowed in this context

### ISSUE THREAD

**Issue by meaverick** [ethersphere/bee#1904]
window 10 pro 20H2 
bee version 0.60
Please take a look.
yaml file: 

clef-signer-enable:false
data-dir: c:/swarm
swap-enable: true
swap-endpoint: https://goerli.infura.io/v3/aca4da5cd42b450cb826a4cb1512619c
verbosity: trace
welcome-message: “Welcome bee”
debug-api-enable: true

C:\swarm>bee.exe start --config bee-default.yaml
**Error: While parsing config: yaml: line 2: mapping values are not allowed in this context**

**Comment by meaverick** [comment]
when i try to change data-dir to other dir have same issue.

**Comment by Eknir** [comment]
This looks like a wrong-formatted path. Try to see the value under `data-dir` if you run `bee printconfig`, and base your custom-path on that.

**Comment by Eknir** [comment]
Please join our Discord for further support! https://discord.gg/QpVwzJ3JKj
