### ISSUE TITLE
  How do I map this directory to the host

### ISSUE THREAD

**Issue by sedasdas** [ethersphere/bee#1905]
ports:
      - "${API_ADDR:-1633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:1635}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - bee-1:/home/bee/.bee
      How do I map this directory to the host，The default directory will soon run out of space and I want to map it to a larger directory，what should i do

**Comment by Eknir** [comment]
Hi there!
Thank you for trying out Bee. It would be best to join our Discord: https://discord.gg/QpVwzJ3JKj
