### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1909]
ERRO[2021-05-28T16:29:59+02:00] failed syncing event listener, shutting down node err: client is closed 
INFO[2021-05-28T16:29:59+02:00] api shutting down                            
panic: close of closed channel

goroutine 126 [running]:
github.com/ethersphere/bee/pkg/api.(*server).Close(0xc0009d2160, 0x7f21231fae98, 0xc00cb07a40)
	github.com/ethersphere/bee/pkg/api/api.go:150 +0xa5
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown.func1(0x7f20fbee9490, 0xc0009d2160, 0x1561940, 0x3)
	github.com/ethersphere/bee/pkg/node/node.go:707 +0x62
github.com/ethersphere/bee/pkg/node.(*Bee).Shutdown(0xc000440120, 0x188f3c0, 0xc00003e0e0, 0xc005e61a60, 0x1)
	github.com/ethersphere/bee/pkg/node/node.go:712 +0x7b
github.com/ethersphere/bee/pkg/node.(*pidKiller).Shutdown(0xc0005483c0, 0x188f3c0, 0xc00003e0e0, 0xc005e61a60, 0x1)
	github.com/ethersphere/bee/pkg/node/node.go:809 +0x46
github.com/ethersphere/bee/pkg/postage/listener.(*listener).Listen.func3(0xc000f87b00, 0xc0020338c0)
	github.com/ethersphere/bee/pkg/postage/listener/listener.go:257 +0x10f
created by github.com/ethersphere/bee/pkg/postage/listener.(*listener).Listen
	github.com/ethersphere/bee/pkg/postage/listener/listener.go:252 +0x21d

**Comment by aloknerurkar** [comment]
Currently, there is a possibility where we might try shutdown twice. If a shutdown is already in progress and we hit an error in the postage listener, we might try to shut down again. This can cause panic.

**Comment by acud** [comment]
this should be done AFAIK
