### ISSUE TITLE
Bee binary asset name does not contain version number

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#1910]
#### Summary
The bee binary asset name does not contain the version number for certain assets: `darwin`, `linux`, `windows`.
It contains the version number in the case of Deb or Rpm packages. It would be good to include the version number for all binary assets.

On some OSes (e.g. WIndows, Mac) this will yield ordered filenames (see screenshot) and if there are multiple versions downloaded it can be confusing. 

<img width="880" alt="Screenshot 2021-05-28 at 17 09 57" src="https://user-images.githubusercontent.com/230163/120005356-06a12f80-bfd8-11eb-888d-fc2b0c5efd6b.png">

**Comment by Eknir** [comment]
Thanks for creating this issue. Tagging @vandot

**Comment by agazso** [comment]
I agree that this is not necessary, it just makes people's life easier and less confusing on Mac and Windows when you have to manually download and install new versions.

I don't understand what this has to do with the project being written in golang. For example [Geth](https://geth.ethereum.org/downloads/) includes the version number (and also the beginning of the commit hash) in their packaged filenames.

**Comment by vandot** [comment]
@agazso geth is one of the projects and if you ask me not the shiniest example how you should do things, we already have to many repos and scripts that use this filename structure to work
If filename is really important to you you can always rename it after you download it, simple as that
I will close this issue
