### ISSUE TITLE
Is there a tutorial for windows?

### ISSUE THREAD

**Issue by qingsong666** [ethersphere/bee#1915]
Is there a tutorial for windows?

Many users don't know Linux, it seems too complicated, if there is a Windows tutorial, it will be icing on the cake.

**Comment by ldeffenb** [comment]
I don't know of one, but feel free to write something up.  I'd be glad to review it!

**Comment by Eknir** [comment]
Great idea and supporter of this as well. If you, or somebody else wants to write this, we can offer you the support you need.

Closing this issue, as it is not something which the Bee team will work on currently.
