### ISSUE TITLE
Cant connect to peers after being online for more than 24hours..0.6.1version on Windows.

### ISSUE THREAD

**Issue by hhenrry501** [ethersphere/bee#1918]
Here's my configuration..please help

## HTTP API listen address (default ":1633")
api-addr: :1633
## initial nodes to connect to (default [/dnsaddr/bootnode.ethswarm.org])
bootnode: [/dnsaddr/bootnode.ethswarm.org]
## enable clef signer
clef-signer-enable: false
## clef signer endpoint
clef-signer-endpoint: /usr/local/var/lib/swarm-clef/clef.ipc
## config file (default is /home/<user>/.bee.yaml)
config: D:\swarm\bee.yaml
## origins with CORS headers enabled
cors-allowed-origins: applicable
## data directory (default "/home/<user>/.bee")
data-dir: D:\swarm
## db capacity in chunks, multiply by 4096 to get approximate capacity in bytes
db-capacity: 5000000
## debug HTTP API listen address (default阿 ":1635")
debug-api-addr: 127.0.0.1:1635
## enable debug HTTP API
debug-api-enable: true
full-node: true
## disable a set of sensitive features in the api
gateway-mode: false
## enable global pinning
global-pinning-enable: false
## NAT exposed address
nat-addr: "222.129.49.63:1634"
## ID of the Swarm network (default 1)
network-id: 1
## P2P listen address (default ":1634")
p2p-addr: :1634
## enable P2P QUIC protocol
p2p-quic-enable: false
## enable P2P WebSocket transport
p2p-ws-enable: false
## password for decrypting keys
password: "admin"
## path to a file that contains password for decrypting keys
password-file: D:\Swarm\password
## amount in BZZ below the peers payment threshold when we initiate settlement (default 10000)
payment-early: 10000
## threshold in BZZ where you expect to get paid from your peers (default 100000)
payment-threshold: 100000
## excess debt above payment threshold in BZZ where you disconnect from your peer (default 10000)
payment-tolerance: 10000
## ENS compatible API endpoint for a TLD and with contract address, can be repeated, format [tld:][contract-addr@]url
resolver-options: []
## whether we want the node to start with no listen addresses for p2p
standalone: false
## enable swap (default true)
swap-enable: true
## swap ethereum blockchain endpoint (default "http://localhost:8545")
swap-endpoint: wss://goerli.infura.io/ws/v3/4384ff31fc184b00b71461efcd41718c
## swap factory address
swap-factory-address: ""
## initial deposit if deploying a new chequebook (default 100000000)
swap-initial-deposit: 100000000
## enable tracing
tracing-enable: false
## endpoint to send tracing data (default "127.0.0.1:6831")
tracing-endpoint: 127.0.0.1:6831
## service name identifier for tracing (default "bee")
tracing-service-name: bee
## log verbosity level 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=trace (default "info")
verbosity: info
## send a welcome message string during handshakes
welcome-message: "gogogo"

**Comment by Eknir** [comment]
Hi there, 

Thanks for trying out Bee!

We can best help in in the support channel of our Discord: https://discord.gg/FUZ9BZb3zJ

From a first glimpse, it looks as if you did not set your `swap-endpoint` correctly.
