### ISSUE TITLE
Bee service bug

### ISSUE THREAD

**Issue by adrianzhang** [ethersphere/bee#1921]
#### Summary
Installed and configured Bee on Ubuntu 20.04 GamePack (a 3rd party Ubuntu edition), system service not working as expected.

#### Steps to reproduce
install bee-clef and bee by following instructions in https://docs.ethswarm.org/docs/installation/install, package install, version of bee-clef is 0.4.12, bee 0.6.0
Problem: 
sudo systemctl start bee
curl localhost:1635/peers
curl: (7) Failed to connect to localhost port 1635: Connection refused
sudo systemctl stop bee
sudo bee start --config /etc/bee/bee.yaml
curl localhost:1635/peers
{"peers":[{"address":"77027f042a4f9631366e95966e7112b8987d86aff4188c61c52d638a2ef717f4","fullNode":true},{"address":"770ff5c9b9709984fdfeb7b22b7e3e2995327dcf9da6d5324eab2410932b37f4","fullNode":true},{"address":"7725ce925db080551db7f2fcd01559414d092b6f2bc195143dfb30cf2bcb5aaf","fullNode":true}]}

#### Expected behavior
Hope I can use system service to run Bee.

#### Actual behavior
Only can run Bee by hand command.

**Comment by luozhanxin** [comment]
you can execute `journalctl --lines=100 --follow --unit bee` look system log.

**Comment by adrianzhang** [comment]
> journalctl --lines=100 --follow --unit bee

bee.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

**Comment by adrianzhang** [comment]
Please fix the bug, notice that the line I comment.
```
$ cat vi /lib/systemd/system/bee.service
cat: vi: No such file or directory
[Unit]
Description=Bee - Ethereum Swarm node
Documentation=https://docs.ethswarm.org
After=network.target

[Service]
#EnvironmentFile=-/etc/default/bee
NoNewPrivileges=true
User=bee
Group=bee
ExecStart=/usr/bin/bee start --config /etc/bee/bee.yaml
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
```
