### ISSUE TITLE
Recommended specifications

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1927]
To run Bee, what are the recommended specifications of hardware, software and connectivity?

**Comment by ldeffenb** [comment]
There are official recommendations for hardware, software, or connectivity because the bee node software is not yet complete.  Until the software is complete, reliable performance analysis cannot be done.  Until the performance is analyzed, not recommendations can be made.

**Comment by Zhangxh1011** [comment]
Now that bee is pre-launched, do we have a detailed hardware configuration?

**Comment by ldeffenb** [comment]
> Now that bee is pre-launched, do we have a detailed hardware configuration?

Do you see any answers here?  Or is this issue closed?  That should give you a good answer to your question...

**Comment by AVANT951** [comment]
I have run Linux hosts of different specifications and come to some limited conclusions.
The recommended configuration for a single bee node is as follows:
**0.5.3**
cpu: 1 Core
ram: 2GB+1GB swap
Storage: 50GB ssd m.2 pci-e slc/mlc 4K IOPS(The higher the better)
Network: 10mbps-25mbps bandwidth
**0.6.2**
cpu: 2 Core
ram: 4GB
Storage: 50GB ssd m.2 pci-e slc/mlc 4K IOPS(The higher the better)
Network: 10mbps-25mbps bandwidth
**The foreseeable future**
When swarm is formally deployed and enters the practical stage, the performance requirements of storage and network will be greatly improved.
It is suggested that a higher standard be adopted for these two items.
