### ISSUE TITLE
from one linux to other linux,warning: no chequebook found, deploying new one!

### ISSUE THREAD

**Issue by adnely** [ethersphere/bee#1930]
from one linux to other linux,warning: no chequebook found, deploying new one!

**Comment by adnely** [comment]
the same node ,from one linux to other linux,warning: no chequebook found, deploying new one?

**Comment by mitboy1983** [comment]
when i update the version 0.6.2 , i run the code :  curl -s http://localhost:1635/chequebook/address | jq .chequebookaddress

the result is  null ???

why my chequebook address is missing ？

**Comment by ldeffenb** [comment]
You need to look at your node's logs and see what it is telling you.  I suspect it hasn't even fully started running yet.

**Comment by attila-lendvai** [comment]
@adnely what does this mean:

> from one linux to other linux

did you copy the data directories to another machine? what did you copy? how did you copy it? are file permissions right? did you look at the logs? can you paste the relevant parts?

please edit the description of the original issue to add more information. or if it's really a support question, then close this issue, and ask for help on discord: https://docs.ethswarm.org/docs/community/community

**Comment by Eknir** [comment]
Closing this issue, as no further information is supplied
