### ISSUE TITLE
the checkque address is missing

### ISSUE THREAD

**Issue by mitboy1983** [ethersphere/bee#1933]
when i update the version to 0.6.2,  i run the code : `curl -s http://localhost:1635/chequebook/address | jq .chequebookaddress`

the result is null ???

why my checkque address is missing ?   

long ago , i update 0.5.3 to 0.6.0 run the same code , the result is all right , that show my chequebook address !

**Comment by chrisvander** [comment]
Should be `curl -s http://localhost:1635/chequebook/address | jq .chequebookAddress`. Capitalization matters!

**Comment by ldeffenb** [comment]
Or just do:
curl -s http://localhost:1635/chequebook/address

It's a simple enough response to not need the | jq.

**Comment by mitboy1983** [comment]
> Or just do:
> curl -s http://localhost:1635/chequebook/address
> 
> It's a simple enough response to not need the | jq.

thanks ! your code is right !

**Comment by mitboy1983** [comment]
> Should be `curl -s http://localhost:1635/chequebook/address | jq .chequebookAddress`. Capitalization matters!

thanks for reply !
