### ISSUE TITLE
failed syncing event listener, shutting down node err: client reconnected

### ISSUE THREAD

**Issue by jilongcui** [ethersphere/bee#1935]
#### Summary
Bee client (version 0.6.2 docker) shutdown after running 30 minutes. the logs show:
failed syncing event listener, shutting down node err: client reconnected
#### Steps to reproduce
docker-compose.yaml:
      - BEE_CACHE_CAPACITY=50000000
      - BEE_DB_OPEN_FILES_LIMIT=2000
      - BEE_PAYMENT_EARLY=1000000000000
      - BEE_PAYMENT_THRESHOLD=2000000000000
      - BEE_PAYMENT_TOLERANCE=5000000000000

#### Expected behavior
bee runs no shutdown.

#### Actual behavior

time="2021-06-01T05:23:52Z" level=info msg="greeting \"hello world!\" from peer: bf81b526a85b4c3e336202a3c16a5075f0874005092abe968e0f02f0c60050be"
time="2021-06-01T05:23:52Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAmSiUaMLnCTx3VqcrSH3TV7S9fESmxMT55T5Fjf1oq9TDA"
time="2021-06-01T05:23:53Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAmQAEzCVUsPPqTKziHPbRTxnDrjDtD7jBD25WwiESxRN1p"
time="2021-06-01T05:23:54Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:54Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:54Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:54Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAmE1iDi6FV1w7btHfpQRzaX3WuimG8E4TBoDHZeREXNZSh"
time="2021-06-01T05:23:55Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"314caeb763661e718bbc0eaa7f44e7f35fe3d85ffaa559330e49f9f62491dc5a\""
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"e881a885a59a24a4476000e7710b2dad1c7eceb663c063aac12959fc9e98410a\""
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"88a85cfa58aebb80102409817a88421fbdfec867320d143f7be33d95965ef1de\""
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"a30d5a268596fd2d698b09230b23f95732df266f39e438ea5d962c91db91cada\""
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"b2058e4a40df74ee2eecd651d60b54fed40592413456d373b3a6db27afc327c0\""
time="2021-06-01T05:23:55Z" level=info msg="attempting to connect to peer \"bcb3fb073024c7e619fd27fa8fa1699fb73157255518e15c5e8ef8e82db23abd\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"bffaa772a6b469dd4396e031b49ccb181148b138efe002c19e7ebb3473a9ac34\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"be6fd995e374087f097479faa96c88ade29e5c0c1e198fa5be22d4cb735c6cb9\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"bf797165ed8ca2eea6b963b790242b3294664daa470d44ec33dae3bef124f898\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"bc569fb9fb90c60d45f8c223764fb519ca08f3596acb0cec67ee1eaf71085cf7\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"bbf83b1b413077a13f670fbfe4e41023082bf3ba8d7dc9f1d5b3aa275876a67f\""
time="2021-06-01T05:23:56Z" level=info msg="attempting to connect to peer \"b3cc8d5407239671f1b16f22ff6289e50fed71e46b2b2fa1319a7e59a8342f94\""
time="2021-06-01T05:23:58Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm56RGTdevmt95Y1MvaS7WbR9dtfEHTzLCWt7i7VExHQmM"
time="2021-06-01T05:23:58Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAmLNWiKQ2hEdmDX8ncFTc76nzPvaLsiGmPDMWxh4Kebnvt"
time="2021-06-01T05:23:59Z" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm3C2DK2Hb5CeT5aCLV1QaZCeNuVv4Z5AK8BUwD7uAnHuP"
time="2021-06-01T05:23:59Z" level=error msg="failed syncing event listener, shutting down node err: client reconnected"
time="2021-06-01T05:23:59Z" level=info msg="api shutting down"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer bf69133b037ad08168d9661c55f39ea2e71899ae05f8e1d36cce41530cc3d140"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer b8af3f2a8237855b01434df4a2aee602f283bb72768c4d30bfff946f03d81438"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer bf81b526a85b4c3e336202a3c16a5075f0874005092abe968e0f02f0c60050be"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer fbcf9593281a471ca8374020c1c5fd0fe2418de4a94091a0011fa33d78fb79a3"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer bf40684ed621c3222185dfc745c6570fabff78d9af211ebc8efda1e867bfcae3"
time="2021-06-01T05:23:59Z" level=warning msg="could not send payment threshold announcement to peer db8d480d029f20ab305aa63cecf76925e0235461110aa5698f095359a52c3f8b"
time="2021-06-01T05:23:59Z" level=info msg="stream handler: successfully connected to peer b5c01209f352c9453f4fb16e0af7a8c8d98870b8a5288a23462af20320b77f60 (inbound)"
time="2021-06-01T05:23:59Z" level=info msg="stream handler: successfully connected to peer bf84069837592d90b7afac6171d08f7a0371738cd22106daef389051b8265e90 (inbound)"
time="2021-06-01T05:23:59Z" level=info msg="pusher shutting down"
time="2021-06-01T05:23:59Z" level=info msg="puller shutting down"
time="2021-06-01T05:23:59Z" level=info msg="pull syncer shutting down"
time="2021-06-01T05:23:59Z" level=info msg="kademlia shutting down"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T05:23:59Z" level=info msg="kademlia persisting peer metrics"

**Comment by tmm360** [comment]
My logs says:

```
time="2021-06-01T18:02:03Z" level=error msg="failed syncing event listener, shutting down node err: Post \"http://******:8545\": dial tcp ********:8545: connect: connection refused"
time="2021-06-01T18:02:03Z" level=info msg="api shutting down"
time="2021-06-01T18:02:03Z" level=info msg="pusher shutting down"
time="2021-06-01T18:02:03Z" level=info msg="puller shutting down"
time="2021-06-01T18:02:03Z" level=info msg="pull syncer shutting down"
time="2021-06-01T18:02:04Z" level=info msg="kademlia shutting down"
time="2021-06-01T18:02:04Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T18:02:04Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T18:02:04Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T18:02:04Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T18:02:04Z" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-01T18:02:04Z" level=info msg="kademlia persisting peer metrics"
```

Node should NEVER shout down, specially if process isn't terminated. In my case, for some reason, the swap point was unaccessible, but it was down only temporarily. Because of this, all nodes on my machine have stopped to work, and even when geth returned available, nodes didn't come back. Moreover, because nodes processes didn't terminate with an error, docker also didn't know that containers have to be restartes, and my full server was totally offline. Very important to reconsider this design decision.

**Comment by firesWu** [comment]
same issue

**Comment by qinxiaoqing** [comment]
same issue

**Comment by hjfdb** [comment]
v1.0.0 same issue

**Comment by acud** [comment]
This is a known design decision we've made. The rational behind it is that if your nodes don't have a functional blockchain backend, they become more of a burden over the network than of use. The fact that syncing relies on on-chain events (postage stamps) in order to persist chunks, means that if your node cannot process on-chain events properly, chunks will be actively rejected. This node behavior is very difficult to circumvent and this creates cascades of problems over the network. It is then favorable that the node will actually go offline than misbehave in a way which is semi correct. 

We're trying to always improve on this, but this matter is extremely difficult to optimize on. Since we rely on the on-chain data so much, we cannot afford the node to have a flaky backend connection. You are therefore required to have a solid setup for your nodes. Hopefully in the future we would have a mechanism (sort of slashing) to make sure node operators adhere to a certain service level agreement. The network reliability depends on that!
