### ISSUE TITLE
Version 0.6.2 has been unable to connect peer nodes

### ISSUE THREAD

**Issue by z724133545** [ethersphere/bee#1936]
bee-1_1   | time="2021-06-01T06:20:52Z" level=warning msg="discover to bootnode /dnsaddr/bootnode.ethswarm.org"
bee-1_1   | time="2021-06-01T06:20:52Z" level=info msg="attempting to connect to peer \"9da363d7a47f6bdb831fc70b7b094e2f3d8b15d3a267b3fe59bbbdf6bb88c8c1\""
bee-1_1   | time="2021-06-01T06:20:52Z" level=info msg="attempting to connect to peer \"7bdbb2b197e96040c714e4b814fe3b510b86a9f7884770aeb6c66b977c60a7b7\""
bee-1_1   | time="2021-06-01T06:20:52Z" level=info msg="attempting to connect to peer \"fdf53bb6dfc06daea4b8dbd9aa348533f6fbc5038f7f50a1ffdb950d133ac968\""
bee-1_1   | time="2021-06-01T06:20:52Z" level=info msg="attempting to connect to peer \"be15b6bba12e0b4141c6b2d330105547406688af41a0b03d9af7b0f85c6a57ce\""
bee-1_1   | time="2021-06-01T06:20:52Z" level=info msg="attempting to connect to peer \"85f779949381a25028ae825a55d9fcae858e80420dc64838f4632a6784ff4844\""
bee-1_1   | time="2021-06-01T06:20:52Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1   | time="2021-06-01T06:20:53Z" level=info msg="greeting \"Welcome to the Swarm, you are Bee-ing connected!\" from peer: fdf53bb6dfc06daea4b8dbd9aa348533f6fbc5038f7f50a1ffdb950d133ac968"
bee-1_1   | time="2021-06-01T06:20:54Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1   | time="2021-06-01T06:20:57Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1   | time="2021-06-01T06:20:57Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1   | time="2021-06-01T06:20:57Z" level=warning msg="peer not reachable when attempting to connect"

**Comment by acud** [comment]
This is normal and not a bug. The experience should be improved in the latest version
