### ISSUE TITLE
Very important bug, please investigate carefully by the bee team

### ISSUE THREAD

**Issue by ndcc5** [ethersphere/bee#1937]
Needless to say too much, please see the following link:
https://goerli.etherscan.io/address/0x138B15eB3743A4f3CF0a27eEe777237549a15225#tokentxns
https://goerli.etherscan.io/address/0x2622329742B27E6E12C7E27898d8e72c7e477E96#tokentxns
https://goerli.etherscan.io/address/0xD3E1e7dBf8E8a6F8321647f26118966Dee8556fe#tokentxns
https://goerli.etherscan.io/address/0xD73d6a8c14F729d517ce46762A51ab74B3000D9D#tokentxns

These four contract addresses have all the ticketing data up to 0529.：
![1](https://user-images.githubusercontent.com/6286019/120290473-f3060980-c2f4-11eb-963e-a9911702e356.png)
![2](https://user-images.githubusercontent.com/6286019/120290499-f7322700-c2f4-11eb-8a1f-c020cd23a654.png)
![3](https://user-images.githubusercontent.com/6286019/120290509-f9948100-c2f4-11eb-8b0b-defb0d9fd54d.png)
![4](https://user-images.githubusercontent.com/6286019/120290517-fb5e4480-c2f4-11eb-8491-62832396cee0.png)

his income is very different from ordinary users, if it can be optimized to that, it is tantamount to a BUG，And it is difficult to guarantee that only four check contract addresses have such a high return, and it is estimated that there are many more addresses.

**Comment by Eknir** [comment]
Cheques can be sent outside of the bee process. This is not a bug, but a natural consequence of the Blockchain, being permission-less and open for anybody. 

There are no adverse affects of this on the Swarm network.

Thank you for investigating and keeping an eye on the network nevertheless
