### ISSUE TITLE
0.5.3 bug,please check it .

### ISSUE THREAD

**Issue by Limore0129** [ethersphere/bee#1939]
#### Summary
INFO[2021-06-01T20:09:44+08:00] version: 0.5.3-acbd0e2
WARN[2021-06-01T20:09:44+08:00] clef is not enabled; portability and security of your keys is sub optimal
INFO[2021-06-01T20:09:45+08:00] using existing swarm network address: 6f8d1d4693a9a7dfb29f8f0ff3487fe139c120f2e639523d8262b5d34ab6a454
INFO[2021-06-01T20:09:45+08:00] swarm public key 024e4852c220c363a7b6c640b4af09e9df007530ff81b1a5e660a8469fc61d3a5c
INFO[2021-06-01T20:09:45+08:00] pss public key 035e2c62437aedb0b36e239cbec1272ad3cdcbe032934e932aaca595c83d9d1ced
INFO[2021-06-01T20:09:45+08:00] using ethereum address 51230bec78cca17ebd3d51a91aba8eb3a2ce31a6
INFO[2021-06-01T20:09:45+08:00] debug api address: [::]:1640
INFO[2021-06-01T20:09:46+08:00] using default factory address for chain id 5: f0277caffea72734853b834afc9892461ea18474
INFO[2021-06-01T20:09:47+08:00] waiting for chequebook deployment in transaction 95f823ceb811cab540f81efba9d8fca47126c2d771f6763d4963308df11e77cb
INFO[2021-06-01T20:10:11+08:00] debug api access                              duration=0.000151744 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:11:10+08:00] debug api access                              duration=4.3254e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:12:10+08:00] debug api access                              duration=5.9251e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:12:26+08:00] debug api access                              duration=0.000143369 ip="::1" method=POST proto=HTTP/1.1 size=36 status=404 uri=/connect/ip4/62.171.188.64/tcp/1634/p2p/16Uiu2HAmEq76upEBNofPJiaU91zuSWxhfytU7NfsvUjqLfBM1QGs user-agent=curl/7.68.0
INFO[2021-06-01T20:13:12+08:00] debug api access                              duration=6.6053e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:14:09+08:00] debug api access                              duration=6.1094e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:15:10+08:00] debug api access                              duration=5.7172e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:16:11+08:00] debug api access                              duration=5.9347e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:17:10+08:00] debug api access                              duration=6.7865e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:18:09+08:00] debug api access                              duration=6.772e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:19:10+08:00] debug api access                              duration=5.507e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:20:10+08:00] debug api access                              duration=6.0623e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:21:09+08:00] debug api access                              duration=6.7825e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:22:15+08:00] debug api access                              duration=7.0649e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:23:09+08:00] debug api access                              duration=5.7105e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:24:10+08:00] debug api access                              duration=6.7216e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:25:09+08:00] debug api access                              duration=5.402e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:26:10+08:00] debug api access                              duration=6.0658e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:27:10+08:00] debug api access                              duration=6.0466e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:28:09+08:00] debug api access                              duration=5.3139e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers
INFO[2021-06-01T20:29:09+08:00] debug api access                              duration=6.3683e-05 ip=117.147.16.252 method=GET proto=HTTP/1.1 size=36 status=404 uri=/peers

#### Steps to reproduce
I got the bug when I deploy 0.5.3,how does I fix it?

**Comment by Eknir** [comment]
Bee 0.5.3 is not anymore supported. Please update to v0.6
