### ISSUE TITLE
error while checking pending transactions: header not found

### ISSUE THREAD

**Issue by wonliang** [ethersphere/bee#1940]
0.6.2 error while checking pending transactions: header not found why?

**Comment by wonliang** [comment]
0.6.2-984dca0a

**Comment by haruhituki** [comment]
I have this error too

**Comment by cdm14cn** [comment]
I have this error too

**Comment by bhswallow** [comment]
I have this error too

**Comment by githubForlinli** [comment]
me too

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question (goerli backlog / overload), and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
