### ISSUE TITLE
chequebook init: validation failed

### ISSUE THREAD

**Issue by zzzhangjian** [ethersphere/bee#1944]
#### Summary

time="2021-06-02T08:41:54+08:00" level=info msg="version: 0.6.2-984dca0a"
time="2021-06-02T08:41:54+08:00" level=info msg="using swarm network address through clef: 21f63811f9d463238ece821c9332cacc2f5297c748be36d6cc1a343d3234def4"
time="2021-06-02T08:41:54+08:00" level=info msg="swarm public key 033318105630a1dc791c04c89937ace6c78c05fa343a2e71945158a5aee63a3a7e"
time="2021-06-02T08:41:55+08:00" level=info msg="pss public key 032a10a29c72fdc2aea9f7fb7cc92a51aef1d4d8a4521bcd88bc7b3a6a11a7745d"
time="2021-06-02T08:41:55+08:00" level=info msg="using ethereum address 00bd435efcc2f4bacd591c2ada64ac47b265b8e8"
time="2021-06-02T08:41:55+08:00" level=info msg="debug api address: 127.0.0.1:16358"
time="2021-06-02T08:41:57+08:00" level=info msg="using default factory address for chain id 5: 73c412512e1ca0be3b89b77ab3466da6a1b9d273"
time="2021-06-02T08:41:58+08:00" level=info msg="no chequebook found, deploying new one."
Error: chequebook init: validation failed: Transaction contains data, but the ABI signature could not be found: signature 15efd8a7 not found

**Comment by ldeffenb** [comment]
You need the latest bee-clef version to fix the ABI signature issue.
