### ISSUE TITLE
could not cash out cheque for xxx 500 cannot cash cheque

### ISSUE THREAD

**Issue by LXuao** [ethersphere/bee#1945]
I try to run bash cashout-0.5.3.sh but faied:

[root@VM-0-2-centos ~]# bash cashout-0.5.3.sh                                   343f7f0a49e2c5dc035554592e3919697d191b09e245e9d0ea474b1c99de638d 371000000000
[root@VM-0-2-centos ~]# bash cashout-0.5.3.sh cashout-all                       
uncashed cheque for 343f7f0a49e2c5dc035554592e3919697d191b09e245e9d0ea474b1c99de638d (374000000000 uncashed)
could not cash out cheque for 343f7f0a49e2c5dc035554592e3919697d191b09e245e9d0ea474b1c99de638d: 500 cannot cash cheque

**Comment by leapp** [comment]
I also encountered the same problem...

**Comment by JxiaoC** [comment]
I also encountered the same problem...

**Comment by Somiar** [comment]
i also have the same problem..

**Comment by fdxmslx** [comment]
I also encountered the same problem...

**Comment by Penguin-Killer** [comment]
same

**Comment by yosefl20** [comment]
same

**Comment by Eknir** [comment]
0.5.3 is not anymore supported. Please update to v0.6
