### ISSUE TITLE
error: read requestPeers message: stream reset or rate limit exceeded

### ISSUE THREAD

**Issue by byteworlds** [ethersphere/bee#1946]
这两个错误一直在抛，不知为啥？请赐教下，感谢！
could not handle protocol hive/1.0.0: stream peers: peer f276e6812698e69b5d8ed1f430686f02bfa9cda6ec3bf2a6a6453c7fc85fe69c: error: read requestPeers message: stream reset

could not handle protocol hive/1.0.0: stream peers: peer f276e6812698e69b5d8ed1f430686f02bfa9cda6ec3bf2a6a6453c7fc85fe69c: error: rate limit exceeded

**Comment by coverboy007** [comment]
me too. seems router stopped it, but can't be sure.

**Comment by leapp** [comment]
same proble....

**Comment by Eknir** [comment]
It is expected in a decentralized network that you can not always communicate with all your peers. Swarm is resilient against this.
