### ISSUE TITLE
0.6.2 error while checking pending transactions: header not found

### ISSUE THREAD

**Issue by yatengLG** [ethersphere/bee#1949]
#### Summary

im a new farmer, but it did not work.

Welcome to the Swarm.... Bzzz Bzzzz Bzzzz

               .-.         .--''-.
             .'   '.     /'       '
             '.     '. ,'          |
   _        o    '.o   ,'        _.-'
 .\ /.       \.--./'. /.:. :._:.'
< ~O~ >    .'    '._-': ': ': ': ':
 '/_\'     :(.) (.) :  ': ': ': ': ':>-
 \ | /      ' ____ .'_.:' :' :' :' :'
  \|/        '\<>/'/ | | :' :' :'
   |               \  \ \
   |                '  ' '
	
		   
INFO[2021-06-02T12:35:15+08:00] version: 0.6.2-984dca0a                      
Password: 
WARN[2021-06-02T12:35:18+08:00] clef is not enabled; portability and security of your keys is sub optimal 
INFO[2021-06-02T12:35:18+08:00] using existing swarm network address: XXX 
INFO[2021-06-02T12:35:18+08:00] swarm public key XXX 
DEBU[2021-06-02T12:35:18+08:00] using existing libp2p key                    
DEBU[2021-06-02T12:35:18+08:00] using existing pss key                       
INFO[2021-06-02T12:35:18+08:00] pss public key XXX 
INFO[2021-06-02T12:35:18+08:00] using ethereum address XXX 
INFO[2021-06-02T12:35:18+08:00] debug api address: [::]:1635                 
INFO[2021-06-02T12:35:20+08:00] using default factory address for chain id 5: XXX 
INFO[2021-06-02T12:35:22+08:00] waiting for chequebook deployment in transaction XXX 
TRAC[2021-06-02T12:35:22+08:00] starting to watch transaction XXX with nonce 0 
ERRO[2021-06-02T13:16:30+08:00] error while checking pending transactions: header not found 

AND 

 ~$ curl localhost:1633
curl: (7) Failed to connect to localhost port 1633: 拒绝连接
 ~$ curl localhost:1634
curl: (7) Failed to connect to localhost port 1634: 拒绝连接
~$ curl localhost:1635
{"message":"Not Found","code":404}

#### Steps to reproduce

ubuntu 18.04
version: 0.6.2-984dca0a

config:
--verbosity 5
--debug-api-enable
--swap-endpoint wss://goerli.infura.io/ws/v3/my_code

**Comment by woshidama323** [comment]
Same issue

**Comment by cdm14cn** [comment]
Same issue

**Comment by zhangqingwen** [comment]
Same issue

**Comment by CaoShusai** [comment]
Same issue

**Comment by ChainFans** [comment]
Same issue

**Comment by bhswallow** [comment]
Same issue

**Comment by zjphone** [comment]
Same issue

**Comment by zkingnode** [comment]
Same issue,me too

**Comment by a252937166** [comment]
有人解决了吗

**Comment by ldeffenb** [comment]
Get a more stable connection to your swap-endpoint.  0.6 monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local goerli node.

Or it's just an issue due to the backlog on goerli.  If you hadn't redacted your transaction IDs, we could do additional diagnostics.

**Comment by shumintao** [comment]
same issue,how to solve it  ?

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question (goerli backlog / overload), and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
