### ISSUE TITLE
could not send payment threshold announcement to peer

### ISSUE THREAD

**Issue by 4his2** [ethersphere/bee#1958]
#### Summary
Is this normal behavior? `could not send payment threshold announcement to peer`. What are the reasons for this?

#### Steps to reproduce
bee version: https://github.com/ethersphere/bee/releases/download/v0.6.2/bee_0.6.2_amd64.rpm

![image](https://user-images.githubusercontent.com/24546717/120507319-48c3da00-c3f9-11eb-8323-24a7ef7c8afd.png)

![image](https://user-images.githubusercontent.com/24546717/120507518-7577f180-c3f9-11eb-86f6-ea855cb210c5.png)

```bash
curl -s http://localhost:1635/peers | jq '.peers | length'
103
```

**Comment by acud** [comment]
This does not look like a bug but more like a connectivity issue. Could you say if this is still an issue?
