### ISSUE TITLE
What is the specific meaning of db-capacity/cache-capacity?

### ISSUE THREAD

**Issue by fenglindubu** [ethersphere/bee#1959]
db-capacity 0.5.3
cache-capacity 0.6.x

Please tell me the specific meaning of db-capacity/cache-capacity. Why do I limit the size, the localstore still grows without limit. Is it possible to delete unused files in the operating environment? If it is deleted, whether it will affect the ticket issuance.

**Comment by ldeffenb** [comment]
If you read the upgrade instructions, you were supposed to delete the localstore.

**Comment by fenglindubu** [comment]
> If you read the upgrade instructions, you were supposed to delete the localstore.
I understand that the upgrade requires deleting the folder. Is it possible to limit the maximum hard disk usage during the operation? Or, when the program is running, deleting a part of the localstore files will affect the new receipts obtained?

**Comment by fenglindubu** [comment]
> If you read the upgrade instructions, you were supposed to delete the localstore.
