### ISSUE TITLE
Sudden disconnect in operation

### ISSUE THREAD

**Issue by chenCoB** [ethersphere/bee#1967]
version: v.0.6.2
environment: MacOs
error:
INFO[2021-06-03T13:15:28+08:00] api shutting down                            
INFO[2021-06-03T13:15:29+08:00] pusher shutting down                         
INFO[2021-06-03T13:15:29+08:00] pull syncer shutting down                    
INFO[2021-06-03T13:15:29+08:00] kademlia shutting down                       
WARN[2021-06-03T13:15:29+08:00] peer not reachable when attempting to connect 
WARN[2021-06-03T13:15:29+08:00] peer not reachable when attempting to connect 
INFO[2021-06-03T13:15:29+08:00] kademlia persisting peer metrics             
Killed: 9

**Comment by acud** [comment]
Hi, please follow our issue template when opening an issue. We need more information with bug reports so we have a chance to figure what's wrong
