### ISSUE TITLE
Running here, the process is killed

### ISSUE THREAD

**Issue by FX336494** [ethersphere/bee#1969]
DEBU[2021-06-03T16:50:46+08:00] kademlia pruned peer from address book "5ff37907e4eace8f1e89d17819a5093bef99406b2276536e5c0d399200520d8c"
DEBU[2021-06-03T16:50:46+08:00] kademlia: peer not reachable from kademlia "[Underlay: /ip4/47.241.182.160/tcp/1634/p2p/16Uiu2HAmRvFC2vKsnVHWLDZJzhMP19W4eRnwimsmq7qyjq65KXFo, Overlay 5ff37907e4eace8f1e89d17819a5093bef99406b2276536e5c0d399200520d8c, Signature 35cf2ccd8aa442d293455db7b93760d909f38d7190089353d5f0f180332deb8f1acd095802c73f4dc5cdc0c59c71c93ac0e84852c8c82591e87c151f4c49bc421c]": context deadline exceeded
WARN[2021-06-03T16:50:46+08:00] peer not reachable when attempting to connect
TRAC[2021-06-03T16:50:46+08:00] kademlia: connector took 5.489756778s to finish: old depth 0; new depth 0
DEBU[2021-06-03T16:50:46+08:00] kademlia manage loop exited
WARN[2021-06-03T16:50:51+08:00] puller shutting down with running goroutines
INFO[2021-06-03T16:50:51+08:00] kademlia shutting down
INFO[2021-06-03T16:50:51+08:00] kademlia persisting peer metrics

Running here, the process is killed

**Comment by aloknerurkar** [comment]
same as #1947

**Comment by acud** [comment]
there's not enough information here. If the problem persists please open a new issue and kindly follow our issue template
