### ISSUE TITLE
The program will exit automatically

### ISSUE THREAD

**Issue by boensu452** [ethersphere/bee#1970]
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=error msg="kademlia: could not broadcast to peer 8443a5a980a5f8e49291a6881ae0a87df997a161f1b1bd83803ee0dfb2e84e8b"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=debug msg="libp2p disconnect: disconnecting peer 8443a5a980a5f8e49291a6881ae0a87df997a161f1b1bd83803ee0dfb2e84e8b"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=debug msg="kademlia: disconnected peer 8443a5a980a5f8e49291a6881ae0a87df997a161f1b1bd83803ee0dfb2e84e8b"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=debug msg="libp2p disconnect: peer 8443a5a980a5f8e49291a6881ae0a87df997a161f1b1bd83803ee0dfb2e84e8b not found"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=debug msg="kademlia: peer not reachable from kademlia \"[Underlay: /ip4/140.246.112.63/tcp/60976/p2p/16Uiu2HAmNqEuUL9X7GjMb8cmGnkJtQifDvKjpnYm2gpJv4tAjaq3, Ove>
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=warning msg="peer not reachable when attempting to connect"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=trace msg="kademlia: connector took 9.093420065s to finish: old depth 1; new depth 0"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=debug msg="kademlia manage loop exited"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=info msg="kademlia shutting down"
Jun 03 16:30:55 VM-0-7-centos bee[41117]: time="2021-06-03T16:30:55+08:00" level=info msg="kademlia persisting peer metrics"

**Comment by honeway** [comment]
Same issue happened.

ENV:
- Win10 64
- bee 0.6.2-984dca0a


```
time="2021-06-03T16:48:18+08:00" level=info msg="attempting to connect to peer \"41ba4cb75c28865f29d354024b146981c78c5a971525004e39d7c93b25adee38\""
time="2021-06-03T16:48:18+08:00" level=info msg="greeting \"CryptoHunter&Swarm GO GO GO\" from peer: caa9aeb98b7d2b07ccfe997a95a8b14a3f838ab37941c3ee18ca511f2b21d8c0"
time="2021-06-03T16:48:19+08:00" level=info msg="successfully connected to peer 41ba4cb75c28865f29d354024b146981c78c5a971525004e39d7c93b25adee38 (outbound)"
time="2021-06-03T16:48:20+08:00" level=info msg="attempting to connect to peer \"403c648c68696eaf6e6e2ee6d0b611c36ef9cda188940f018cbebab530a4d391\""
time="2021-06-03T16:48:21+08:00" level=info msg="greeting \"qbzz.io\" from peer: cbff8ef2df20dcff4bb775719eb69ab46c23bd1d6d014fd28aabdeba0281e584"
time="2021-06-03T16:48:22+08:00" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-03T16:48:22+08:00" level=info msg="attempting to connect to peer \"40c828473b9735baefb39e7ec45e979b52e42af0610c5fdd4e8e38c7bde089f8\""
time="2021-06-03T16:48:24+08:00" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm6A8aWdXsG4T7vXopFcaeHEBUuebSJjHNDhbwUf3nDCo9"
time="2021-06-03T16:48:24+08:00" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAmPrufqWNmsvybr3GoTaHsvNDNUVqP2bDnwEKbH8A9fKmj"
time="2021-06-03T16:48:24+08:00" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm655UqaAyAuspRfWcSA6S7Zd5gT3hXtPvgX9GF8VfBN8i"
time="2021-06-03T16:48:24+08:00" level=error msg="failed syncing event listener, shutting down node err: websocket: close 1011 (internal server error): Internal response error"
time="2021-06-03T16:48:24+08:00" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm7NxHPgCG55xJnKmBuXYFExXjFjuzxxdDxGVvuizYoKZS"
time="2021-06-03T16:48:24+08:00" level=error msg="stream handler: handshake: unable to handshake with peer id 16Uiu2HAm88BUMo7vT1yVGWuHDYKNNaqp3pjtZoKQtc7MZKt4awzp"
time="2021-06-03T16:48:24+08:00" level=info msg="api shutting down"
time="2021-06-03T16:48:24+08:00" level=info msg="pusher shutting down"
time="2021-06-03T16:48:24+08:00" level=info msg="puller shutting down"
time="2021-06-03T16:48:24+08:00" level=info msg="pull syncer shutting down"
time="2021-06-03T16:48:24+08:00" level=error msg="kademlia: could not broadcast to peer a0dd2c299dff38b55ca5d4a771b20dc73e76dee5272738619c2cb5c47d9568d7"
time="2021-06-03T16:48:24+08:00" level=info msg="kademlia shutting down"
time="2021-06-03T16:48:24+08:00" level=warning msg="peer not reachable when attempting to connect"
time="2021-06-03T16:48:24+08:00" level=info msg="kademlia persisting peer metrics"
```

**Comment by boensu452** [comment]
I don't know if it will be fixed. Some people think it's a swap endpoint problem, but I don't think it's... This should be a dead cycle

**Comment by honeway** [comment]
One node of 0.6.2 consumes several times more requests than 0.5.3. The number is more than 32,944/day. I think this is abnormal. 
![image](https://user-images.githubusercontent.com/6339134/120646077-bc262400-c4ab-11eb-9aa2-e30ca7c82d00.png)

**Comment by aloknerurkar** [comment]
same as #1947

**Comment by acud** [comment]
this is because the node cannot query the backend infrastructure, most likely due to request limits. please review your setup to allow enough queries
