### ISSUE TITLE
Add additional informations to GET /stamps

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#1971]
# Task
currently `GET /stamps` returns just `batchID` and `utilization`. These two values alone are not enough to show useful information to the user like probable worst case scenario `health` of the  uploaded data or how much can still be uploaded. 
It would be great if the endpoint also return the stamp `amount`, `depth`, `label` and `timestamp` of the purchase.

**Comment by Eknir** [comment]
More suggestions on postage API: https://roamresearch.com/#/app/swarm-org/page/xjP58GgAm

**Comment by acud** [comment]
this is already implemented and extra debugging information has already been added
