### ISSUE TITLE
Error: init chain: dial eth client: dial tcp [::1]:8546: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by jlfsccm** [ethersphere/bee#1972]
Error: init chain: dial eth client: dial tcp [::1]:8546: connectex: No connection could be made because the target machine actively refused it.

**Comment by ldeffenb** [comment]
Your configuration is looking for a local goerli swap-endpoint that you are not running.  Read: https://docs.ethswarm.org/docs/installation/install#blockchain-endpoints and https://docs.ethswarm.org/docs/FAQ#how-to-set-infuraio-endpoint
