### ISSUE TITLE
没有生成swarm.key文件

### ISSUE THREAD

**Issue by idoup** [ethersphere/bee#1974]
centos8系统
bee版本0.6.2
运行第一次运行bee没有生成swarm.key文件，请问这是什么问题

**Comment by dfhuf504** [comment]
我也遇见同样的问题，采用docker方式部署的

**Comment by cppfuns** [comment]
你肯定是用了clef，去找下clef 导出 私钥json

**Comment by piqihaha** [comment]
> 你肯定是用了clef，去找下clef 导出 私钥json

我在Linux是使用了CLEF，我导出私钥了，我现在换成了WIN系统，要怎么才能导入呢 ？

**Comment by idoup** [comment]
> 你肯定是用了谱号，去看下谱号 导出引json

谢谢，已经捣鼓出来了。。。。又遇到了新的问题，如何用一个clef运行多个bee呢？
