### ISSUE TITLE
Bee 0.6.2-984dca0 running with Error and cannot provide server

### ISSUE THREAD

**Issue by heaven2358** [ethersphere/bee#1984]
#### Summary
when bee 0.6.2 running on centos7, the logs always said
` ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: netlinkrib: too many open files"}`
and several hours later, it can not provide server with error

#### Steps to reproduce
systemclt start bee
journalctl -f -u bee

#### Expected behavior
no error

#### Actual behavior
error and the bee service was shut down after several hours with errors :

```
level=error msg="failed syncing event listener, shutting down node err: put chain state: open /data/bee/statestore/201672.ldb: too many open files"
 level=info msg="api shutting down"
 level=info msg="pusher shutting down"
level=info msg="puller shutting down"
 level=info msg="pull syncer shutting down"
 level=info msg="kademlia shutting down"
level=warning msg="kademlia shutting down with announce goroutines"
 level=warning msg="kademlia manage loop did not shut down properly"
level=info msg="kademlia persisting peer metrics"
level=error msg="failed shutting down node: 2 errors occurred:\n\t* statestore: open /data/bee/statestore/201670.ldb: too many open files\n\t* localstore: open /data/bee/localstore/043211.ldb: too many open files\n\n"
```

but I has modified the ulimit :

```
# ulimit -n
655350
```

```
# cat /etc/security/limits.conf

#<domain>      <type>  <item>         <value>
#
*		soft	nofile		655350
*               hard    nofile         	655350
*               soft    nproc           655350
*               hard    nproc           655350
```

**Comment by ldeffenb** [comment]
ulimit -n only shows the current shell limit.  Since your bee is running under systemctl, you need to add something like the following to the applicable bee.service file (using your appropriate number):
LimitNOFILE=20000
Search for "LimitNOFILE" on the Internet to know exactly where to place it within bee.service.

The following command should show you the location of the bee.service file that needs the addition:
sudo systemctl status bee

**Comment by jhfnetboy** [comment]
Ideffenb,You are so great, solve every difficult questions~!
