### ISSUE TITLE
Download file prompt "Permanent Redirect"

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#1985]
### Purchasing MyBatch of Stamps
```
curl -s -XPOST http://localhost:6333/stamps/10000000/20
{"batchID":"2156f818591d36f8bc457f9f83697d793afacfcf81d824ad0a8ed51a7d0dd2ed"}
```

### Waiting for the transaction to be irreversible
Approve： https://goerli.etherscan.io/tx/0xbbba7723ad03430848724dd8ffe5760386fa696cd9bed1d1b81f63ce2e97c1dc
Create Batch： https://goerli.etherscan.io/tx/0x01868c16b19b24a93c8f49e4c932bf459481a519bd3fd8cd820c15b76e8220dd

### View the operating directory file
```
ls
bee  export-swarm-key-linux-amd64
```

### Upload
```
curl --data-binary @bee  -H "Swarm-Postage-Batch-Id: 2156f818591d36f8bc457f9f83697d793afacfcf81d824ad0a8ed51a7d0dd2ed" "http://localhost:6333/bzz?name=bee"
{"reference":"44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6"}
```

### Download
```
curl -OJ http://localhost:6333/bzz/44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6
ls
44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6  bee  export-swarm-key-linux-amd64
```

### View file content
```
cat 44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6 
<a href="/bzz/44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6/">Permanent Redirect</a>.
```
### result
Download file content error

### Reference documents
https://docs.ethswarm.org/docs/access-the-swarm/upload-and-download/
https://docs.ethswarm.org/docs/access-the-swarm/keep-your-data-alive/

**Comment by filoozom** [comment]
I'm guessing following redirections (with `-L`) should fix this? Or adding a slash after your url:

```
curl -OJ http://localhost:6333/bzz/44002171b486e68853c48bb242dc8a61530b11cc7da802fbca308400e894a2c6/
```
