### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by oneusdt** [ethersphere/bee#1987]
go build -trimpath -ldflags "-s -w -X github.com/ethersphere/bee.commit=""984dca0""" ./...
go: github.com/btcsuite/btcd@v0.21.0-beta requires
        golang.org/x/crypto@v0.0.0-20200510223506-06a226fb4e37: invalid version: git fetch --unshallow -f origin in /root/go/pkg/mod/cache/vcs/f72f7a6f267d2fe79b1e174efab21a591b07c84ef53364f65b8281fda7000b49: exit status 128:
        fatal: git fetch-pack: expected shallow list
make: *** [build] 错误 1

**Comment by acud** [comment]
this is not related to `bee`
