### ISSUE TITLE
Postage batch buy stamps transaction succeeded after many hours but not shown.

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#1991]
An attempt to buy a postage batch buy stamps api call failed after some time, then the transaction succeeded, gBZZ was spent but the batch not shown from the list stamps endpoint.

The transaction took 10 hours.

https://goerli.etherscan.io/tx/0x5d3ed64a4325bfc5be5320065b1213d06460e158ca4eaf858f8bddeaf6d4ef53

**Comment by Eknir** [comment]
Relates to #1559

**Comment by Eknir** [comment]
This is fixed by: https://github.com/ethersphere/bee/pull/2080 . @significance , would be good if you can validate the fix.

**Comment by acud** [comment]
should be fixed since the node will now add batches that appear on chain, even if the http call failed or was cancelled
