### ISSUE TITLE
Can't deploy/init new chequebook , v0.6.2

### ISSUE THREAD

**Issue by stevensu1977** [ethersphere/bee#1993]
#### Summary
I start bee v0.6.2 and already fund 1 gETH/1gBZZ to 0x96865f39f9817cf2f3ad04597f9bb119b71d8bee, bee can't deploy new chequbook , I wait long time but  nothing is happened. 

log:

time="2021-06-04T14:31:23Z" level=trace msg="sending transaction df6395510b82dff81829f4e8f19b5a17eb6ad7d7473af15de567607a238ce519 with nonce 0"
time="2021-06-04T14:31:23Z" level=info msg="deploying new chequebook in transaction df6395510b82dff81829f4e8f19b5a17eb6ad7d7473af15de567607a238ce519"
time="2021-06-04T14:31:23Z" level=trace msg="starting to watch transaction df6395510b82dff81829f4e8f19b5a17eb6ad7d7473af15de567607a238ce519 with nonce 0"

etherscan transaction:
https://goerli.etherscan.io/tx/0xdf6395510b82dff81829f4e8f19b5a17eb6ad7d7473af15de567607a238ce519

**Comment by jacoobwang** [comment]
same issue

**Comment by 51dudu** [comment]
same issue

**Comment by cppfuns** [comment]
https://www.bcskill.com/index.php/archives/1108.html  look step 7

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question (related to Goerli blockage / backlog), and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
