### ISSUE TITLE
How do I migrate from Linux to Windows/怎么从Linux迁移到Windows

### ISSUE THREAD

**Issue by piqihaha** [ethersphere/bee#1994]
My program was deployed on Linux system before, and I have obtained the key and file. Now I want to migrate to Windows system, but I find that the key file format is different, what should I do? Help me.

Linux ：bee-clef-key-1621695536.json   bee-clef-password-1621695536.txt

windows：libp2p.key pss.key swarm.key
---------------------------------------------------------------------------------------
我的程序之前是部署再Linux系统，我已经获取了密钥还有文件，我现在想迁移到Windows系统，发现密钥文件格式不一样，我要怎么做？帮帮我。
Linux ：bee-clef-key-1621695536.json   bee-clef-password-1621695536.txt
windows：libp2p.key pss.key swarm.key

**Comment by xami** [comment]
试下用linux上bee-clef的密码来重建windows的账号，密码路径：
cat /var/lib/bee-clef/password

删除windows的keys目录，在用上面的密码来初始化一个新账号
bee init --config /path/bee.yalm

windows账号重建好后，再用linux上 /var/lib/bee-clef/keystore/UTC--2021-06-03T02-12-56.138211119Z--xxxxxx （每台机器的名字不一样，自己查找） 这个认证文件内容替换windows的的swarm.key，删除localstore，statestore

重新启动节点
bee start --config /path/bee.yalm

这样就能以服务器的账号新启动起来了，但因为v0.6.2一直没法出票，我也不知道这种操作是不是没问题。我测试了反正能正常启动起来，这种方式在本地重新启动会重新生成票据来验证账号，就是你账户余额有最低要求，要有足够的geth和gbzz才能启动成功。

**Comment by piqihaha** [comment]
> 试下用linux上bee-clef的密码来重建windows的账号，密码路径：
> cat /var/lib/bee-clef/password
> 
> 删除windows的keys目录，在用上面的密码来初始化一个新账号
> bee init --config /path/bee.yalm
> 
> windows账号重建好后，再用linux上 /var/lib/bee-clef/keystore/UTC--2021-06-03T02-12-56.138211119Z--xxxxxx （每台机器的名字不一样，自己查找） 这个认证文件内容替换windows的的swarm.key，删除localstore，statestore
> 
> 重新启动节点
> bee start --config /path/bee.yalm
> 
> 这样就能以服务器的账号新启动起来了，但因为v0.6.2一直没法出票，我也不知道这种操作是不是没问题。我测试了反正能正常启动起来，这种方式在本地重新启动会重新生成票据来验证账号，就是你账户余额有最低要求，要有足够的geth和gbzz才能启动成功。

老哥 你好，问题是，我已经把Linux删了，租的VPS 到期了，我就备份了bee-clef-key-1621695536.json bee-clef-password-1621695536.txt 这两个文件下来

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question, and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
