### ISSUE TITLE
run bee 0.6.2 validation failed: Transaction contains data, but the ABI signature could not be found: signature 15efd8a7 not found

### ISSUE THREAD

**Issue by dtuncle** [ethersphere/bee#1996]
INFO[2021-06-04T18:39:58Z] no chequebook found, deploying new one.
Error: chequebook init: validation failed: Transaction contains data, but the ABI signature could not be found: signature 15efd8a7 not found

**Comment by ldeffenb** [comment]
You need the latest version of bee-clef to solve the ABI signature issue.

**Comment by picone** [comment]
I install latest version of bee-clef from brew, and start clef with arguments ```--4bytedb-custom /usr/local/etc/swarm-clef/4byte.json --rules /usr/local/etc/swarm-clef/rules.js```. Solved.
