### ISSUE TITLE
no cheque

### ISSUE THREAD

**Issue by cxlater** [ethersphere/bee#1998]
I heard that the main network is going to go online recently. Do so many bug officials still have the confidence to go online.
Since upgrading to version 0.6,I didn't get any cheque

**Comment by chrisvander** [comment]
This is not a bug with bee, this is just the nature of the 0.6.* network in the testnet phase.

**Comment by xami** [comment]
那我们是该退回之前的0.5.3版本还是关机？一直让大量参与者的机器开着又没收益，这是想干嘛？
Should we go back to version 0.5.3 or should we shut it down?

**Comment by ldeffenb** [comment]
> Should we go back to version 0.5.3 or should we shut it down?

What you do with your nodes is completely your decision.  But realize that if you go back to 0.5.3, no new checks received after the official 0.6.2 upgrade announcement will qualify for the airdrop.

**Comment by lazy1523** [comment]
This is a mistake, but you didn't realize it.
