### ISSUE TITLE
💭 5.3 bee cashing out cheque failure.

### ISSUE THREAD

**Issue by freejiu123** [ethersphere/bee#1999]
#### Actual behavior

![mmexport1622777396402](https://user-images.githubusercontent.com/48649939/120879900-4b0a6d80-c58c-11eb-961d-153a87cc4ee2.jpg)

**Comment by sonygod** [comment]
+1

**Comment by ldeffenb** [comment]
0.5.3 is no longer supported, but the "transaction null" recovery is documented in the cashout troubleshooting guide at https://hackmd.io/95rvXRswSh-xm9Td_Xl2cg?view
