### ISSUE TITLE
 ERROR[06-05|07:50:13.463] ########## BAD BLOCK #########

### ISSUE THREAD

**Issue by KIMQI001** [ethersphere/bee#2001]
#### Summary
INFO [06-05|07:50:13.463] Skip duplicated bad block                number=4,915,190 hash=b3343e..4dbc30
ERROR[06-05|07:50:13.463]
########## BAD BLOCK #########
Chain config: {ChainID: 5 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 1561651, Muir Glacier: <nil>, Berlin: 4460644, YOLO v3: <nil>,Engine: clique}

Number: 4915190
Hash: 0xb3343e69ee0b86793f8de46f54a1e40d601971d2cffe4336798a6d35924dbc30

Error: could not apply tx 51 [0x89d6ba34eeeced5842f8a17545a893d77ef5e35d92def26a6a3ff2b05b4679da]: gas limit reached
##############################

#### Steps to reproduce
when I depoly a new node,the geth log jump this

#### Expected behavior
no bad block and the deploy go well

**Comment by ldeffenb** [comment]
This is an issue with geth and not bee and I believe it occurred while the validators were attempting to increase the gas limit per block.
