### ISSUE TITLE
Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"

### ISSUE THREAD

**Issue by jameslei518** [ethersphere/bee#2006]
Jun 05 19:57:30 bee1 bee[26160]: time="2021-06-05T19:57:30Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"
Jun 05 19:57:31 bee1 bee[26160]: time="2021-06-05T19:57:31Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"
Jun 05 19:57:31 bee1 bee[26160]: 2021-06-05T19:57:31.795Z        ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: netlinkrib: too many open files"}
Jun 05 19:57:31 bee1 bee[26160]: 2021-06-05T19:57:31.912Z        ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: netlinkrib: too many open files"}
Jun 05 19:57:32 bee1 bee[26160]: time="2021-06-05T19:57:32Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"
Jun 05 19:57:33 bee1 bee[26160]: time="2021-06-05T19:57:33Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"
Jun 05 19:57:34 bee1 bee[26160]: time="2021-06-05T19:57:34Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"
Jun 05 19:57:35 bee1 bee[26160]: time="2021-06-05T19:57:35Z" level=error msg="http: Accept error: accept tcp 127.0.0.1:1635: accept4: too many open files; retrying in 1s"

**Comment by ldeffenb** [comment]
You have apparently increased the db-open-files limit but you didn't tell your host operating system to allow more.  You need to search the Internet for "ulimit -n" and/or limitNOFILE if you are using systemctl.
