### ISSUE TITLE
docs: setting gas price and gas limit on withdraw

### ISSUE THREAD

**Issue by paralin** [ethersphere/bee#2007]
The current `withdraw?amount=N` endpoint supports setting gas price via header `Gas-Price` and limit via `Gas-Limit`, docs should probably mention these, as the current withdraw default limits & price are too low for the testnet at the moment.

**Comment by ldeffenb** [comment]
https://docs.ethswarm.org/debug-api/#tag/Chequebook/paths/~1chequebook~1withdraw/post
Does not mention these optional headers, but /chequebook/cashout does:
https://docs.ethswarm.org/debug-api/#tag/Chequebook/paths/~1chequebook~1cashout~1{peer-id}/post

**Comment by liyu3519** [comment]
> The current `withdraw?amount=N` endpoint supports setting gas price via header `Gas-Price` and limit via `Gas-Limit`, docs should probably mention these, as the current withdraw default limits & price are too low for the testnet at the moment.

https://github.com/ethersphere/bee/issues/2007#issue-912554114

**Comment by Eknir** [comment]
We welcome PRs against our documentation repo: https://github.com/ethersphere/bee-docs

**Comment by Eknir** [comment]
Closing this issue for now, as it was created in the Bee repo. But please open it in our docs and/or create the PR. Thanks
