### ISSUE TITLE
type error of buy stamps

### ISSUE THREAD

**Issue by soforth** [ethersphere/bee#2008]
#### Summary
Fund your node's wallet returns 404

#### Steps to reproduce
following the document which says:
curl -XPOST "http://localhost:1635/chequebook/withdraw/?amount=1000"

#### Expected behavior
{"transactionHash":"0xxxxxxxxxxxxxxxxxxxx"}

#### Actual behavior
{"message":"Not Found","code":404}

PS: there is a typing error, just remove the trailing slash before the ?amount can fix it, fg.
curl -XPOST "http://localhost:1635/chequebook/withdraw?amount=1000"

**Comment by soforth** [comment]
document: https://docs.ethswarm.org/docs/access-the-swarm/keep-your-data-alive/

**Comment by Eknir** [comment]
@significance error in the docs
