### ISSUE TITLE
bee 0.6.2 amd64 CentOS 7x64 --> error while checking pending transactions: header not found

### ISSUE THREAD

**Issue by ctusky** [ethersphere/bee#2009]
When I run bee0.6.2 on centos7 x64, I get the following prompt:

INFO[2021-06-06T08:39:17Z] using ethereum address 3af9bee4b041488ba4****************** 
INFO[2021-06-06T08:39:17Z] debug api address: [::]:1635
INFO[2021-06-06T08:39:17Z] using default factory address for chain id 5: 73c412512e1ca0be3b89b7*********** 
INFO[2021-06-06T08:39:18Z] no chequebook found, deploying new one.      
TRAC[2021-06-06T08:39:19Z] sending transaction 4d2abe0f06aca97731fddb96dfeb3df905135e978868f42d7bafaecc8f4322b1 with nonce 8 
INFO[2021-06-06T08:39:20Z] deploying new chequebook in transaction 4d2abe0f06aca97731fddb96dfeb3df905135e978868f42d7bafaecc8f4322b1 
TRAC[2021-06-06T08:39:20Z] starting to watch transaction 4d2abe0f06aca97731fddb96dfeb3df905135e978868f42d7bafaecc8f4322b1 with nonce 8 
ERRO[2021-06-06T08:59:02Z] error while checking pending transactions: header not found 
ERRO[2021-06-06T08:59:48Z] error while checking pending transactions: header not found 
ERRO[2021-06-06T09:08:54Z] error while checking pending transactions: header not found 

Is this a bug? I tried to replace bootnode but it didn't work. What should I do?

**Comment by ldeffenb** [comment]
> ERRO[2021-06-06T09:08:54Z] error while checking pending transactions: header not found

This error is caused by your swap-endpoint.  Make sure your configured swap-endpoint is working.
