### ISSUE TITLE
k8s start bee

### ISSUE THREAD

**Issue by Sseve** [ethersphere/bee#2014]
when i use k8s to start bee, it report an errror that is bee command error 
![image](https://user-images.githubusercontent.com/41677305/120996968-63ab9b00-c7b9-11eb-8f01-0c987b7a9cd3.png)
how can i handle this error

**Comment by anatollupacescu** [comment]
It's not an error, it is printing the "usage".

You have the wrong command to start the bee, more details here: https://docs.ethswarm.org/docs/bee-developers/starting-a-test-network#starting-your-nodes

**Comment by Sseve** [comment]
thanks, i have solevd it.
