### ISSUE TITLE
why can not listening port 1634 when start bee

### ISSUE THREAD

**Issue by abaity** [ethersphere/bee#2021]
[root@mongodb147 /]# netstat -tpln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2833/master         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2608/sshd           
tcp6       0      0 ::1:25                  :::*                    LISTEN      2833/master         
tcp6       0      0 :::1635                 :::*                    LISTEN      15856/bee           
tcp6       0      0 :::22                   :::*                    LISTEN      2608/sshd

**Comment by cppfuns** [comment]
Operation of normal nodes

```
bcskill_com@web0_190:~$ netstat -tpln
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:44251           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:1634            0.0.0.0:*               LISTEN      29824/./bin/bee     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp6       0      0 :::30303                :::*                    LISTEN      28066/./geth        
tcp6       0      0 :::1633                 :::*                    LISTEN      29824/./bin/bee     
tcp6       0      0 :::1634                 :::*                    LISTEN      29824/./bin/bee     
tcp6       0      0 :::1635                 :::*                    LISTEN      29824/./bin/bee
```

**Comment by abaity** [comment]
Using Docker!
