### ISSUE TITLE
Don't initialize push sync and pull sync when building up Kademlia

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#2024]
# User story

## Story
As a storer node, I don't want to initialize the push sync and pull sync protocols when building up a Kademlia such that I don't waste resources and damage the stability of the network

## Acceptance criteria

- It is less likely that a node initializes push sync and pull sync protocols when building up a healthy Kademlia

## Background

- Easiest (and sufficient) solution is to wait 10 minutes. This wait time should be configurable not to mess with our integration tests.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
When we pick peers for forwarding, don't pick peers that are connected to us less than 10 minutes

**Comment by acud** [comment]
This is already done by the warmup time feature
