### ISSUE TITLE
Error: migrate: error getting migrations for current schema (clean-interval): could not find current db schema

### ISSUE THREAD

**Issue by totodata** [ethersphere/bee#2031]
Bee boot error: migrate: error getting migrations for current schema (clean-interval): could not find current db schema

What does it mean? How to fix it.

**Comment by ldeffenb** [comment]
Did this error come from bee or nonce-reset?  If the former, it happens when you try to downgrade from 0.6 back to 0.5.3 which is unsupported.  If the latter, and you are trying to do a nonce-reset on a 0.6 node, there is already an issue logged at https://github.com/ethersphere/nonce-reset/issues

**Comment by acud** [comment]
Closing this as the issue is stale
