### ISSUE TITLE
connect new stream: incompatible stream: protocol not supported

### ISSUE THREAD

**Issue by joliny** [ethersphere/bee#2032]
TRAC[2021-06-09T13:03:21+08:00] kademlia balanced connector took 2.75µs to finish 
TRAC[2021-06-09T13:03:21+08:00] kademlia iterator took 45.763µs to finish    
DEBU[2021-06-09T13:03:21+08:00] kademlia has no connected peers, trying bootnodes 
TRAC[2021-06-09T13:03:21+08:00] connecting to bootnode /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd 
DEBU[2021-06-09T13:03:23+08:00] connect fail /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd: connect new stream: incompatible stream: protocol not supported 
WARN[2021-06-09T13:03:23+08:00] connect to bootnode /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd 
DEBU[2021-06-09T13:03:23+08:00] discover fail /dnsaddr/bootnode.ethswarm.org: discover /dnsaddr/swarm-2.bootnode.ethswarm.org: discover /dnsaddr/bee-5.bootnode.ethswarm.org: discover /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd: connect new stream: incompatible stream: protocol not supported 
WARN[2021-06-09T13:03:23+08:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org 
TRAC[2021-06-09T13:03:53+08:00] kademlia balanced connector took 3.486µs to finish 
TRAC[2021-06-09T13:03:53+08:00] kademlia iterator took 56.707µs to finish    
DEBU[2021-06-09T13:03:53+08:00] kademlia has no connected peers, trying bootnodes 
TRAC[2021-06-09T13:03:53+08:00] connecting to bootnode /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd 
DEBU[2021-06-09T13:03:54+08:00] connect fail /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd: connect new stream: incompatible stream: protocol not supported 
WARN[2021-06-09T13:03:54+08:00] connect to bootnode /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd 
DEBU[2021-06-09T13:03:54+08:00] discover fail /dnsaddr/bootnode.ethswarm.org: discover /dnsaddr/swarm-2.bootnode.ethswarm.org: discover /dnsaddr/bee-5.bootnode.ethswarm.org: discover /ip4/54.167.196.243/tcp/31305/p2p/16Uiu2HAmEYYKJZzCE9PuBBzncuAaJ3ZSw5hovsepXjF859wDZ6bd: connect new stream: incompatible stream: protocol not supported 
WARN[2021-06-09T13:03:54+08:00] discover to bootnode /dnsaddr/bootnode.ethswarm.org

**Comment by joliny** [comment]
bee version is  0.5.3

**Comment by ldeffenb** [comment]
Bee version 0.5.3 is no longer supported and the bootnodes have been upgraded to 0.6.  You need to be running 0.6.2 as of the official announcement on June 1st.
