### ISSUE TITLE
error: read requestPeers message: context canceled"

### ISSUE THREAD

**Issue by joliny** [ethersphere/bee#2033]
#### Summary
logs:
time="2021-06-09T13:24:00+08:00" level=error msg="kademlia: could not broadcast to peer 0df988bdb0c2fa14c58d32cbe5a0c12e56eec40e637fc182d59dbd99bc22f902"
time="2021-06-09T13:24:20+08:00" level=debug msg="could not handle protocol hive/1.0.0: stream peers: peer 0e85fe3c190304f080af8c52bb9e1803cf08dac7fb5703b8485a7e56b521274c: error: read requestPeers message: context canceled"
time="2021-06-09T13:25:02+08:00" level=debug msg="could not handle protocol hive/1.0.0: stream peers: peer 109866ce0dfb76e7c16961f2c73da9c796f55316b8adf7306b59bc728e211955: error: read requestPeers message: context canceled"
time="2021-06-09T13:25:18+08:00" level=error msg="kademlia: could not broadcast to peer 0a7bce88ef3d100d235af275e8001ee2d95f81e42895d0de7d08f914b5e157e2"
time="2021-06-09T13:26:11+08:00" level=debug msg="could not handle protocol pricing/1.0.0: stream pricing: peer 0112316f2b4285a18cabf4e0ad08a374937e62ebe3cd3f0836075392f072a9a0: error: read request from peer 0112316f2b4285a18cabf4e0ad08a374937e62ebe3cd3f0836075392f072a9a0: context canceled"
time="2021-06-09T13:26:59+08:00" level=error msg="kademlia: could not broadcast to peer 2c64d93afb12ad570f85be8b62cf6791b774d8357b84cf139e3f16add4bfe6db"
time="2021-06-09T13:27:04+08:00" level=error msg="kademlia: could not broadcast to peer 0837d4bf07cc9376af64da63e03b922e04cefdac4b2872c7addb5871d912f6b0"
time="2021-06-09T13:27:19+08:00" level=debug msg="could not handle protocol hive/1.0.0: stream peers: peer 012a6b6baceab169e0c0d0f93362d3f172ffe1a6fdf815e3097b7349ec1d83fb: error: read requestPeers message: context canceled"
time="2021-06-09T13:28:39+08:00" level=error msg="kademlia: could not broadcast to peer a1202df8c3b5d660248513c9efbcde24a6c2d6152034395abb3e6d9ebd299fed"
time="2021-06-09T13:28:52+08:00" level=debug msg="could not handle protocol pricing/1.0.0: stream pricing: peer 41279fa23e8b69c05a4c792bcd3791478dd259e42fced928bf2b171b5db52435: error: read request from peer 41279fa23e8b69c05a4c792bcd3791478dd259e42fced928bf2b171b5db52435: context canceled"
time="2021-06-09T13:29:48+08:00" level=debug msg="could not handle protocol pricing/1.0.0: stream pricing: peer 0ed85ef02ac74fe3dfb673cfd8e26a4470a2d7552e60991113254f75301b201b: error: read request from peer 0ed85ef02ac74fe3dfb673cfd8e26a4470a2d7552e60991113254f75301b201b: context canceled"
time="2021-06-09T13:31:37+08:00" level=debug msg="could not handle protocol pricing/1.0.0: stream pricing: peer 0d08eb920bb249eea161d989ecec28ee07377f6921606e359d030255fab065f4: error: read request from peer 0d08eb920bb249eea161d989ecec28ee07377f6921606e359d030255fab065f4: context canceled"

os:ubuntu20.04
bee:0.6.2

**Comment by ldeffenb** [comment]
Is there a question in there?  I didn't see one.  Those logs appear normal.  If your node has connected peers, then all of those can be safely ignored.  

Questions like this are better handled in #bee-support in our Discord server.  Issues are to report actual problems, not to ask if something is normal or not.
