### ISSUE TITLE
no cheque in bee 0.6.2。

### ISSUE THREAD

**Issue by SunYoung91** [ethersphere/bee#2035]
i was  upgrade bee from 0.5.3 to 0.6.2 few days ago . and it with full localstorage size .  before upgrade  i can got 5-15 cheque one day 。 after upgrade my node upload datasize  totaly 100 gigabytes at least .but i can't got any cheque。

**Comment by ldeffenb** [comment]
This is not a problem report, but a complaint.  This sort of thing is better handled in the #bee-support channel of our Discord server.  If you read the conversations there, you'd know that checks are very rare in the 0.6 swarm at this time and that the developers are aware of it and looking into it.
