### ISSUE TITLE
critical bug

### ISSUE THREAD

**Issue by liu454639377** [ethersphere/bee#2039]
using m2 card to store database , it's happened 100% of cpu and the card is not working 
![image](https://user-images.githubusercontent.com/47815423/121374812-cbf1ac80-c972-11eb-9da0-1923d8b18526.png)

all of the bee process become zoombies , and few later, server has dead.
![image](https://user-images.githubusercontent.com/47815423/121378296-a74b0400-c975-11eb-9092-63d510f1b275.png)

**Comment by liu454639377** [comment]
![image](https://user-images.githubusercontent.com/47815423/121378664-fabd5200-c975-11eb-8eff-ddfd9c535335.png)
this is last Screenshots before dead server,help me deal with this bug

**Comment by acud** [comment]
Please follow our github issue template when opening an issue and provide as much debugging information as possible. Closing this for now since there's not enough information here. If the problem persists please open a new issue
