### ISSUE TITLE
v0.6.2版本压根不出票，几个节点都跑了3天以上了，一张票没看到！这么严重的问题，官方就不管吗，或者给个解释啊！

### ISSUE THREAD

**Issue by xami** [ethersphere/bee#2042]

**Comment by luke188** [comment]
我也是，不知道官方在干什么

**Comment by xami** [comment]
搞笑的项目，打着V神的旗号来招摇撞骗，V神怕一行代码都没参与写过吧

**Comment by dfhuf504** [comment]
0.6.0-0.6.3 我所有版本都试过了，就是没有票！

**Comment by joliny** [comment]
#1998 
This is not a bug with bee, this is just the nature of the 0.6.* network in the testnet phase.

**Comment by joliny** [comment]
What a powerful answer

**Comment by koalaylj** [comment]
不要用中文交流。
keep uses English, please!

**Comment by Eknir** [comment]
Thank you for reporting, but we close all issues that are not English.
