### ISSUE TITLE
reason for 0.6.2 cannot produce checks?

### ISSUE THREAD

**Issue by wxw1198** [ethersphere/bee#2043]
#### Summary
0.6.2 

#### Steps to reproduce

I find some thing at  "pkg/accounting/accounting.go"
```golang
func (a *Accounting) NotifyRefreshmentReceived(peer swarm.Address, amount *big.Int) error {
	accountingPeer := a.getAccountingPeer(peer)

	accountingPeer.lock.Lock()
	defer accountingPeer.lock.Unlock()

	currentBalance, err := a.Balance(peer)
	if err != nil {
		if !errors.Is(err, ErrPeerNoBalance) {
			return err
		}
	}

	// Get nextBalance by increasing current balance with amount
	nextBalance := new(big.Int).Sub(currentBalance, amount)

	// We allow a refreshment to potentially put us into debt as it was previously negotiated and be limited to the peer's outstanding debt plus shadow reserve
	a.logger.Tracef("crediting peer %v with amount %d due to payment, new balance is %d", peer, amount, nextBalance)

	err = a.store.Put(peerBalanceKey(peer), nextBalance) 
	if err != nil {
		return fmt.Errorf("failed to persist balance: %w", err)
	}

	return nil
}

```
_**err = a.store.Put(peerBalanceKey(peer), nextBalance)**_ 

 at this line , will set balance to 0, Is a BUG for v0.6.2?

amount value should bigger than 310000000000,but get log :
level=trace msg="pseudosettle accepting payment message from peer 3bc153667f592de55fec5dfd84068e2039400e32a18c887b4d6fee666fc67956 of 16000000000"

**Comment by y-ang2010** [comment]
You mean there are some logical problems in this place.
Wait and see the official reply.

v0.6.2 is a common problem that there is no check. I hope the official can give some answers as soon as possible.

**Comment by wxw1198** [comment]
may be the code ```if paymentAmount.Cmp(big.NewInt(0)) > 0 && timeElapsed > 0 {``` is error? shoud change to 

	if paymentAmount.Cmp(big.NewInt(0)) < 0 && timeElapsed > 0 {

**Comment by wxw1198** [comment]
i do not understand "time-based settlements"
