### ISSUE TITLE
bee client setup error

### ISSUE THREAD

**Issue by smsaravanakumar** [ethersphere/bee#2045]
![bee error-1](https://user-images.githubusercontent.com/19745532/121467104-2708bb00-c9d6-11eb-8b3b-24ae94f8f78c.jpg)

Can anyone help to fix this issue.

Advanced thanks

**Comment by wxw1198** [comment]
can not connect to geth node

**Comment by ldeffenb** [comment]
Your actual problem is that your swap-endpoint is not pointing to a goerli network provider.  This is why you got the message "no known factory address for this network".  Fix your swap-endpoint.

This is not a bug in bee, but a configuration issue with the node.

**Comment by smsaravanakumar** [comment]
Issue solved

Thanks for your support & guidance

**Comment by smsaravanakumar** [comment]
> Your actual problem is that your swap-endpoint is not pointing to a goerli network provider. This is why you got the message "no known factory address for this network". Fix your swap-endpoint.
> 
> This is not a bug in bee, but a configuration issue with the node.
-------------
Issue solved

Thanks for your support & guidance
