### ISSUE TITLE
Bee uses up all RAM and crashes after switching from light mode to full mode

### ISSUE THREAD

**Issue by wuyazero** [ethersphere/bee#2053]
#### Summary
After running in light mode for several days, switching the node to full mode causes it to use up all available RAM and get killed by the Linux system.

#### Steps to reproduce
1. Run the v0.6.2 bee node in light mode for some time (not sure how long is required, or if the length of time running as light node is relevant here, mine was running in light mode for around a week)
2. Stop bee node
3. Change the `bee.yaml` configuration file to set `full-node: true`
4. Start bee node with the modified configuration file
5. Wait for the bee node to start connecting to peers

#### Expected behavior
The bee node should run normally after switching from light mode to full mode, just like any other bee node started with the `full-node` configuration property set to `true` right from the start

#### Actual behavior
Bee node starts, and after a while start to connect to peers, with the RAM usage continuously climbing up, until it uses up all available RAM and force-killed by the Linux system.

Memory usage right before bee node is force-killed by system
![image](https://user-images.githubusercontent.com/34883700/121589392-94b1f700-ca69-11eb-9e5f-8aa7ff4ff714.png)

Out of memory error
![image](https://user-images.githubusercontent.com/34883700/121589541-c1660e80-ca69-11eb-8c2c-fd24de8eb151.png)

Memory usage of another bee node that has always been running (on a much lower spec system) as full node 
![image](https://user-images.githubusercontent.com/34883700/121591116-b1e7c500-ca6b-11eb-8191-eead58b8dd13.png)

**Comment by Eknir** [comment]
Thank you for reporting this. We will inspect the issue!

**Comment by 1105120802** [comment]
I also encountered that the number of connections reached 5W + and took up 140g of memory. When the number of connections fluctuates, the memory does not decrease. Then the memory is full and is killed

**Comment by 1105120802** [comment]
I also encountered that peers reached 50K + and occupied 140g of memory. When the number of connections fluctuates, the memory does not decrease. Then the memory is full and is killed

**Comment by istae** [comment]
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
19788 esad      20   0  877064 196272  27856 S   0.3   1.5   0:11.41
20367 esad      20   0 1082468 403020  27916 S  45.7   3.1   8:47.27
```

As of v1.1.0-rc2, after testing it against the test-net, the CPU and mem usage is higher when `full-node: true`, but there are major differences between the two because some protocols behavior differently, for example, puller is enabled for full node, but not for light nodes, so the extra usage is not unexpected. Also, since 0.6.2, there have been improvements made to optimize full node resource usage.

So, I am closing this issue.
