### ISSUE TITLE
Unable to withdraw the check. Stuck in the process of withdrawal

### ISSUE THREAD

**Issue by Gump-II** [ethersphere/bee#2054]
Unable to withdraw the check. Stuck in the process of withdrawal.....
![image](https://user-images.githubusercontent.com/16313834/121619757-a7452400-ca9b-11eb-9f48-6426db42e6fb.png)

**Comment by ldeffenb** [comment]
This is due to the backlog in the goerli blockchain and resulting slowness in validating transactions.  It is NOT a bug in bee.
