### ISSUE TITLE
I  got  some tickets at 0.6.2,but  it cashout itself,,,as  we know bee will not cash checks on its own.  That is a user-triggered event,so what is the problem?

### ISSUE THREAD

**Issue by damen-lzw** [ethersphere/bee#2055]
I  got  some tickets at 0.6.2,but  it cashout itself,,,as  we know bee will not cash checks on its own.  That is a user-triggered event,so what is the problem?

**Comment by lulei0215** [comment]
out 還是in  被其他人 兌現了嗎

**Comment by damen-lzw** [comment]
> out 還是in 被其他人 兌現了嗎

就是正常的获得的票

**Comment by Eknir** [comment]
I don't understand the question. Sorry. For support, please reach out to our Discord: https://discord.gg/QpVwzJ3JKj
