### ISSUE TITLE
Questions about the version

### ISSUE THREAD

**Issue by Zhangxh1011** [ethersphere/bee#2058]
one：Why use last in the docker image tag every test version ，Instead of using beta
two：Why the bee image in docker-compose.yaml uses the beta version

**Comment by Zhangxh1011** [comment]
@ldeffenb

**Comment by ldeffenb** [comment]
> @ldeffenb

I don't do Docker, and it's bad enough to tag me in the Discord, but really now?  Tagging me in an Issue?  Please DON'T!

**Comment by Zhangxh1011** [comment]
I'm so sorry。I saw that most people did not point out this problem, so I thought it was my problem. That's why I came to ask questions. I'm really sorry to disturb you!
