### ISSUE TITLE
General problem description

### ISSUE THREAD

**Issue by occurxu** [ethersphere/bee#2064]
#### Actual behavior

Error: no known factory address for this network

**Comment by occurxu** [comment]
Error: no known factory address for this network

**Comment by ldeffenb** [comment]
Your configured swap-endpoint is likely not pointing to a goerli node.  Doublecheck your swap-endpoint.  If using infura.io, make sure you selected Goerli from the drop-down before copying the URL.

**Comment by ldeffenb** [comment]
Oh, and these sorts of things are best asked first in the #bee-support channel of the Discord server.
