### ISSUE TITLE
v1.0.0-rc2 panic

### ISSUE THREAD

**Issue by mark2021blue** [ethersphere/bee#2076]
panic: runtime error: index out of range [93] with length 93

goroutine 8 [running]:
github.com/mark2021blue/bee/pkg/postage.(*Batch).UnmarshalBinary(0xc000246500, 0xc0007360c0, 0x5d, 0x60, 0xc000246500, 0xc000736001)
        github.com/mark2021blue/bee/pkg/postage/batch.go:50 +0x205
github.com/mark2021blue/bee/pkg/statestore/leveldb.(*store).Get(0xc000117f68, 0xc001910880, 0x31, 0x1291c80, 0xc000246500, 0xc001910880, 0x31)
        github.com/mark2021blue/bee/pkg/statestore/leveldb/leveldb.go:83 +0x1ca
github.com/mark2021blue/bee/pkg/postage/batchstore.(*store).Get(0xc0002ca400, 0xc000736091, 0x20, 0x2f, 0x1, 0x51, 0x80)
        github.com/mark2021blue/bee/pkg/postage/batchstore/store.go:89 +0xc8
github.com/mark2021blue/bee/pkg/postage/batchstore.(*store).evictExpired.func1(0xc000736060, 0x51, 0x60, 0xc000728850, 0x4, 0x8, 0x1, 0x1, 0x0)
        github.com/mark2021blue/bee/pkg/postage/batchstore/reserve.go:86 +0xab
github.com/mark2021blue/bee/pkg/statestore/leveldb.(*store).Iterate(0xc000117f68, 0x144bf95, 0x11, 0xc001943e90, 0x0, 0x0)
        github.com/mark2021blue/bee/pkg/statestore/leveldb/leveldb.go:115 +0x286
github.com/mark2021blue/bee/pkg/postage/batchstore.(*store).evictExpired(0xc0002ca400, 0x1, 0x6)
        github.com/mark2021blue/bee/pkg/postage/batchstore/reserve.go:85 +0x202
github.com/mark2021blue/bee/pkg/postage/batchstore.(*store).PutChainState(0xc0002ca400, 0xc0018fdf08, 0xc000421bf8, 0xc001924240)
        github.com/mark2021blue/bee/pkg/postage/batchstore/store.go:146 +0x47
github.com/mark2021blue/bee/pkg/postage/batchservice.(*batchService).UpdateBlockNumber(0xc0004a1c40, 0x4bc368, 0x0, 0x0)
        github.com/mark2021blue/bee/pkg/postage/batchservice/batchservice.go:113 +0x16e
github.com/mark2021blue/bee/pkg/postage/listener.(*listener).Listen.func2(0x0, 0x0)
        github.com/mark2021blue/bee/pkg/postage/listener/listener.go:239 +0x7f0
github.com/mark2021blue/bee/pkg/postage/listener.(*listener).Listen.func3(0xc0016e8ea0, 0xc00018c240)
        github.com/mark2021blue/bee/pkg/postage/listener/listener.go:255 +0x2b
created by github.com/mark2021blue/bee/pkg/postage/listener.(*listener).Listen
        github.com/mark2021blue/bee/pkg/postage/listener/listener.go:254 +0x21d

**Comment by Eknir** [comment]
Your configuration is not compatible with v1.0, as mentioned in the release notes.
