### ISSUE TITLE
Swarm source code management needs to be strengthened

### ISSUE THREAD

**Issue by cppfuns** [ethersphere/bee#2086]
https://github.com/ethersphere/bee/releases

Additional increments since v0.6.2
Protect against overissuance of postage stamps and allow the transfer of part of the stamps under a postage batch (#1625)
Allow the price for bandwidth to fluctuate and deduct an initial amount from the first-received cheque from a peer (#1925)
Increase the resilience against churn by:
Speed up the build-up of a healthy Kademlia (#2028)
Delay the start-up of push sync and pull sync protocols (#2050)
Ensure the profitability and security of forwarder nodes by only letting originator nodes pay with cheques (#1870)

Several bug fixes and cleanups
Do not consider issuing another 0.6.3? According to the regular project testing process, the code of the testnet should be prioritized than the code of the official line, but currently some of the repair codes of Swarm are only in the 1.0RC branch
And the 1.0RC branch cannot run on the testnet, what is the role of the testnet?

**Comment by cppfuns** [comment]
@Eknir no problem?

**Comment by Eknir** [comment]
Hi there,

I might have accidentally closed this issue, while weeding through all issues. Sorry for that. 
Thank you for opening the issue and you are right. We want to release the 1.0-rc branch as soon as we can to the test network. 

All the best
