### ISSUE TITLE
How bee saves the data generated by the smart contract?

### ISSUE THREAD

**Issue by jackma-cloud** [ethersphere/bee#2087]
I was deeply attracted by swarm's ability to save smart contract data, and I also read the developer [documentation of bee](https://docs.ethswarm.org/docs/dapps-on-swarm/develop-on-bee). I found some storage principles, such as chunk, reference, manifest, etc., and also saw that bee.js can be used to implement [upload and download functions](https://bee-js.ethswarm.org/docs/upload-download). 

But what I want to know is how bee saves the data in the smart contract. For example, I uploaded a smart contract. Over time, this smart contract has been called many times by many people, resulting in some data write in blockchain. I What I want to know is how bee saves this data, and is there any related business flowcharts or mature solutions?  

I saw the chapter [Storing Your Dapps Data #](https://docs.ethswarm.org/docs/dapps-on-swarm/develop-on-bee)，but I did not capture more information。Looking forward to your answers~

**Comment by Eknir** [comment]
Hi there,

We use issues to comment about stuff that you would like to have implemented in Bee or for bugs. This is clearly a support question. Please join our Discord (referenced on our website) and ask your question in a channel where people talk about Dapp development.

Best,

**Comment by jackma-cloud** [comment]
> Hi there,
> 
> We use issues to comment about stuff that you would like to have implemented in Bee or for bugs. This is clearly a support question. Please join our Discord (referenced on our website) and ask your question in a channel where people talk about Dapp development.
> 
> Best,

Oh, I see, thank you!
