### ISSUE TITLE
gBZZ transfer from 0.5.3 node cheque book to 0.6.x node cheque book

### ISSUE THREAD

**Issue by Nil-lang** [ethersphere/bee#2089]
we found a tx that one 0.5.3 node transfer gBZZ to one 0.6.x node.

this is the cheque transfer tx
https://goerli.etherscan.io/tx/0x9f304a2bdfcdbf9a7b060d4cdd2afcdf56bc1b80b8c2f7ac22524ceecb5b047f

this is the sender cheque book
https://goerli.etherscan.io/token/0x2ac3c1d3e24b45c6c310534bc2dd84b5ed576335?a=0xac419be76edf25ff046ff6661151c99d471b0228
deployed in 0.5.3 contract https://goerli.etherscan.io/tx/0x243853bdb01d65a564d3d0e352a6e765626789fcc27f96a0e2e5258663c861d0

this is the receiver cheque book
https://goerli.etherscan.io/token/0x2ac3c1d3e24b45c6c310534bc2dd84b5ed576335?a=0xcd1605b580384659acf1e2911f0db1df46addc69
deployed in 0.6.x contract https://goerli.etherscan.io/tx/0xd5649c629c8d9d0e9b07f5eaa633e22453f1d83c13e7c32c7806ba68ca518a77

but the sender is a 0.5.3 node
and the receiver is a 0.6.x node

why will the transfer happened?

**Comment by Eknir** [comment]
Hi there,
Thanks for trying out Bee. Support questions please to our Discord (referenced on our website).

Best,

**Comment by Nil-lang** [comment]
this is a bug that some node can hijack to get illegal 0.6.x cheque
