### ISSUE TITLE
The error message "failed to resolve local interface addresses" in the log of the Bee service 

### ISSUE THREAD

**Issue by huangxunet** [ethersphere/bee#2092]
My bee node looks normal. But I use "journalctl -f -u bee.service" to view the bee service log information.

Get the error message as shown in the figure, 

> Jun 15 15:38:47 yax-cs-cmcc-001 bee[33148]: 2021-06-15T15:38:47.114+0800        ERROR        basichost        failed to resolve local interface addresses        {"error": "route ip+net: netlinkrib: too many open files"}

I want to know what went wrong with "bee.yaml".

Thank you

**Comment by Eknir** [comment]
Hi there, thank you for trying out Bee! It is best to ask for support in our Discord (please find the url referenced on our website)

**Comment by ldeffenb** [comment]
Yes, please use the #bee-support Discord channel where you could have searched for this message and received numerous hits of the solution:

Either set your db-open-files-limit back to the default of 200 or search the Internet for "ulimit -n" or limitNOFILES if you are using systemctl.
