### ISSUE TITLE
runtime error: index out of range [1] with length 0 

### ISSUE THREAD

**Issue by yinyangyu** [ethersphere/bee#2118]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

**Comment by yinyangyu** [comment]
runtime error: index out of range [1] with length 0

**Comment by Eknir** [comment]
Thank you for reporting this. However, there is too little information for us to inspect this issue. Next time, please run your node with `--verbosity 5` and copy the logs here.
