### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by yinyangyu** [ethersphere/bee#2119]
panic: runtime error: index out of range [1] with length 0

goroutine 225 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).recalcPeer(0xc002ecae10, 0x1761a78, 0xc0031db4c0, 0xc014d13d00, 0x20, 0x20, 0x3)
        github.com/ethersphere/bee/pkg/puller/puller.go:220 +0x698
github.com/ethersphere/bee/pkg/puller.(*Puller).manage(0xc002ecae10)
        github.com/ethersphere/bee/pkg/puller/puller.go:170 +0x448
created by github.com/ethersphere/bee/pkg/puller.New
        github.com/ethersphere/bee/pkg/puller/puller.go:82 +0x2aa

**Comment by yinyangyu** [comment]
panic: runtime error: index out of range [1] with length 0

goroutine 225 [running]:
github.com/ethersphere/bee/pkg/puller.(*Puller).recalcPeer(0xc002ecae10, 0x1761a78, 0xc0031db4c0, 0xc014d13d00, 0x20, 0x20, 0x3)
        github.com/ethersphere/bee/pkg/puller/puller.go:220 +0x698
github.com/ethersphere/bee/pkg/puller.(*Puller).manage(0xc002ecae10)
        github.com/ethersphere/bee/pkg/puller/puller.go:170 +0x448
created by github.com/ethersphere/bee/pkg/puller.New
        github.com/ethersphere/bee/pkg/puller/puller.go:82 +0x2aa

**Comment by mrekucci** [comment]
Thanks for reporting this. Since you didn't use the template for bug reporting would you mind adjusting the description according to [this template](https://github.com/ethersphere/bee/blob/master/.github/ISSUE_TEMPLATE/bug-report.md). Also, the version of your running node would be great to have.

**Comment by yinyangyu** [comment]
"version: 0.6.1-79ad7f08"

**Comment by ldeffenb** [comment]
0.6.1 has known bugs in this area that are fixed in 0.6.2

**Comment by yinyangyu** [comment]
Thanks
