### ISSUE TITLE
level=error msg="error while checking pending transactions: header not found"

### ISSUE THREAD

**Issue by ShilohMy** [ethersphere/bee#2122]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

# Epic

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question, and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) discord channel.
