### ISSUE TITLE
0.62 bee run errro,help kids

### ISSUE THREAD

**Issue by Gods-good** [ethersphere/bee#2129]
![image](https://user-images.githubusercontent.com/39650584/122509285-17bce980-d036-11eb-9121-6d01473b54f3.png)

my bee node version is 0.62  ，my machine configuration is 27CPU  251G RAM。 I run 20 nodes at the same time, but  cpu  is  only  17%  ?,  my  friends   64CPU  ,he   run  50 bee nodes,   CPU  100%.  please  help  me!!! 

and  whole nodes  hava error log

![image](https://user-images.githubusercontent.com/39650584/122509712-d0832880-d036-11eb-8040-ac551baeadbe.png)

**Comment by attila-lendvai** [comment]
it's normal to have some errors in the log when nodes or the network misbehave, or when nodes disappear.

**Comment by acud** [comment]
Also, running bee should not be computationally intensive.
