### ISSUE TITLE
HTTP headers get mixed into the beginning of file contents

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/bee#2149]
#### Summary
i was trying to upload a ~700MB file on `0.6.2`, and there were issues. finally i managed to get through chunking (syncing is stuck, but that's probably a different story):

```
$ curl http://localhost:1600/tags/925145647 | jq
{
  "uid": 925145647,
  "startedAt": "2021-06-15T08:49:16+02:00",
  "total": 170097,
  "processed": 170097,
  "synced": 141242
}
```

then i tried to download the file from the same node to see if all is well at least locally, but HTTP headers get mixed into the first bytes of the file?!

#### Steps to reproduce

from my notes (not all output is recorded):
```
curl -s -XPOST http://localhost:1600/stamps/10000000/20
{"batchID":"745172fa64ea89aec27f12926beeca18cecfbb0d7591c0e16668b745e9cf35e8"}

curl -X POST http://localhost:1600/tags

curl --verbose --header "swarm-pin: true" --header "Swarm-Tag: 925145647" --header "Content-Type: video/mp4" --header "Swarm-Postage-Batch-Id: 745172fa64ea89aec27f12926beeca18cecfbb0d7591c0e16668b745e9cf35e8" --form file=@COVID19-Ivermectin-and-the-Crime-of-the-Century-Podcast-with-Pierre-Kory-Bret-Weinstein.mp4 http://localhost:1600/bzz

curl http://localhost:1600/tags/925145647 | jq

http://localhost:1600/bzz/aea486f3ab83c559b3394dbdabf7c0b7f25301a5a6f1ebe3f54bcd26f33747c1
```

#### Actual behavior
```
$ wget -c http://localhost:1600/bzz/aea486f3ab83c559b3394dbdabf7c0b7f25301a5a6f1ebe3f54bcd26f33747c1/
--2021-06-20 01:15:10--  http://localhost:11600/bzz/aea486f3ab83c559b3394dbdabf7c0b7f25301a5a6f1ebe3f54bcd26f33747c1/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:11600... connected.
HTTP request sent, awaiting response... 200 OK
Length: 691242236 (659M) [video/mp4]
Saving to: ‘index.html’

index.html                                  1%[>                                                                                     ]  11.50M  --.-KB/s    eta 80m 38s^C
$ head -n 5 index.html 
--------------------------29556a0b2efa9671
Content-Disposition: attachment; name="file"; filename="COVID19-Ivermectin-and-the-Crime-of-the-Century-Podcast-with-Pierre-Kory-Bret-Weinstein.mp4"
Content-Type: application/octet-stream

 ftypisomisomiso2avc1mp4free(���mdat��%�@_����*�69��| �p^/8�4�,��n9�+���=8a{��͛���u�׵l�;K���/�����$3�=k��XY��G|z��������|ID��	~��`a�6Pd&"�bN	����_ho���3.�l�lܻ&�,T�QӲ��Zr�P�j�'�$�x�/�eŇ�*ۖ�(�������N��
```

**Comment by ralph-pichler** [comment]
not sure if form upload works. usually I upload video with
`curl -v -H "Content-Type: video/mp4" -H "Swarm-Postage-Batch-Id: $BATCH_ID" --data-binary @$FILENAME "http://localhost:1633/bzz?name=$1"`

**Comment by attila-lendvai** [comment]
thanks @ralph-pichler!

then we need to make a choice here:

1. disable forms in the bee code to fail with an explicit error. then grep `curl.*-F` in the docs and change them to use `--binary-data`.
2. fix form upload in bee.

**Comment by acud** [comment]
@attila-lendvai form upload works in bee. you're using it the wrong way. since form data changes the content type header to `application/x-www-form-urlencoded` or `multipart/form-data`, your request isn't going the way you expected. the header can only be specified once for the request. when doing multipart requests, every _part_ (i.e. everything that goes within the _boundary_ tag) can have its own content type, since different parts can have different types. bee supports this perfectly well, however pulling this off in `curl` might be a bit tricky. i would tend to `wont-fix` in this case

**Comment by acud** [comment]
also, i'm not entirely sure how curl handles multiple settings of the same header in one request. on the client side i know that this is not considered legal and the request parser should return only one value

**Comment by attila-lendvai** [comment]
@acud so, basically it's `curl` that should have warned me, which is outside of the scope of `bee`, right?

if there is a way to detect this situation on the server side, then it would be nice to warn/error about it. otherwise just close the issue, and i'll update the docs keeping this in mind, and maybe even add a warning about it. but certainly get rid of every mention of `curl --form`.

**Comment by acud** [comment]
if we could mend the docs to reflect this information would be awesome. tagging @significance too
