### ISSUE TITLE
Error:connection reset by peer    

### ISSUE THREAD

**Issue by lulei0215** [ethersphere/bee#2167]
.-.         .--''-.
             .'   '.     /'       '
             '.     '. ,'          |
   _        o    '.o   ,'        _.-'
 .\ /.       \.--./'. /.:. :._:.'
< ~O~ >    .'    '._-': ': ': ': ':
 '/_\'     :(.) (.) :  ': ': ': ': ':>-
 \ | /      ' ____ .'_.:' :' :' :' :'
  \|/        '\<>/'/ | | :' :' :'
   |               \  \ \
   |                '  ' '

                   
INFO[2021-06-21T09:36:24Z] version: 1.0.0-rc4-02dd4346                  
Password: 
WARN[2021-06-21T09:36:26Z] clef is not enabled; portability and security of your keys is sub optimal 
INFO[2021-06-21T09:36:26Z] swarm public key 02003d52ea26da2236eff29f6fa169a8ec3f70fcb5e2dccac7d79c49d285b627df 
DEBU[2021-06-21T09:36:27Z] using existing libp2p key                    
DEBU[2021-06-21T09:36:27Z] using existing pss key                       
INFO[2021-06-21T09:36:27Z] pss public key 02c4481b9ff561eb33b2672da9303ccacdce831996f0e727a14cd0df9cfeee90db 
INFO[2021-06-21T09:36:27Z] using ethereum address 9e31640724b5375ed87decf312f9d1cf038f4eb5 
INFO[2021-06-21T09:36:27Z] debug api address: 127.0.0.1:1635            
Error: init chain: dial eth client: read tcp 127.0.0.1:50462->127.0.0.1:8546: read: connection reset by peer

**Comment by BradChan** [comment]
I have the same error.

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question, and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
