### ISSUE TITLE
invalid chain id , xdai chainid change

### ISSUE THREAD

**Issue by code-scan** [ethersphere/bee#2176]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Actual behavior

# 修复方法 how to fix
change file /usr/bin/bee-clef-service

```
CHAINID=5
```
to
```
CHAINID=100
```

# run
```
service bee-clef restart
```

enjoy your bee client !
官方招go开发吗？

一站式bee全自动部署加监控解决方案
https://www.pocpool.io/

**Comment by ldeffenb** [comment]
You probably need to open this issue on the bee-clef repository, not bee.
