### ISSUE TITLE
mainnet chain id error !

### ISSUE THREAD

**Issue by toneewang** [ethersphere/bee#2177]
version: 1.0.0-2572fa48

`bee.exe start --config bee.yaml --mainnet --network-id 1`

bee.yaml：
`mainnet: true
nat-addr: ""
network-id: "1"`

time="2021-06-22T02:29:38+08:00" level=info msg="using default factory address for chain id 5: 73c412512e1ca0be3b89b77ab3466da6a1b9d273

**Comment by ralph-pichler** [comment]
chainid is determined by the swap endpoint you are using (and different from network id). If you want to use mainnet you need to use an xdai swap endpoint (chain id 100).

**Comment by mfw78** [comment]
Thanks for your issue. This falls more in the realm of a support question, and not a problem specifically with Bee itself. For support, please contact us on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) channel.
