### ISSUE TITLE
is version 1.0.0-2572fa48 but your node is outdated, please check for the latest version  error

### ISSUE THREAD

**Issue by yjgfn** [ethersphere/bee#2180]
your node is outdated, please check for the latest version  error

1.0.0-2572fa48 version run logs：
ersion: 1.0.0-2572fa48 - planned to be supported until 1 April 1970, please follow http://ethswarm.org/

WARN[2021-06-22T08:52:38+08:00] your node is outdated, please check for the latest version 
INFO[2021-06-22T08:52:38+08:00] swarm public key 0219e801d44ed93686de1bbe719f276ca97032f7e7025fc997b63e1c6fbc9462c5 
DEBU[2021-06-22T08:52:38+08:00] using existing libp2p key                    
DEBU[2021-06-22T08:52:38+08:00] using existing pss key                       
INFO[2021-06-22T08:52:38+08:00] pss public key 02bdfa341eb92306bd570e31890c478934f67622a518b6af5334207586364867a1 
INFO[2021-06-22T08:52:38+08:00] using ethereum address 1fcf50876e96a12f4beb59073d9ba5f5b9e9869d 
INFO[2021-06-22T08:52:38+08:00] version: 1.0.0-2572fa48                      
INFO[2021-06-22T08:52:38+08:00] debug api address: 127.0.0.1:1635            
INFO[2021-06-22T08:52:41+08:00] using default factory address for chain id 100: c2d5a532cf69aa9a1378737d8ccdef884b6e7420 
INFO[2021-06-22T08:52:44+08:00] using existing chequebook d11ab9c623cce12e31103fba2bfd34b9c29d7d0a 
Error: chequebook init: chequebook not deployed by factory

**Comment by mrekucci** [comment]
@yjgfn I'm guessing you ran your node directly from the source code without compiling it using `make binary`. If that's the case then this is fixed in #2191

**Comment by xuanyuan219** [comment]
> @yjgfn I'm guessing you ran your node directly from the source code without compiling it using `make binary`. If that's the case then this is fixed in #2191

How to make binary?

**Comment by mrekucci** [comment]
> > @yjgfn I'm guessing you ran your node directly from the source code without compiling it using `make binary`. If that's the case then this is fixed in #2191
> 
> How to make binary?

Download the [source code](https://github.com/ethersphere/bee/archive/refs/heads/master.zip) or clone the GitHub repository. In the downloaded `bee` directory run `make binary` from your command line. After the successfull build, you can find the binary under the `./dist` subdirectory.

**Comment by mfw78** [comment]
This is fixed in #2191 and is available in tag 1.0.1-rc1.
