### ISSUE TITLE
how to found My Node?

### ISSUE THREAD

**Issue by gouchaoer** [ethersphere/bee#2181]
there's nothing on the official doc on found node
```
https://docs.ethswarm.org/docs/installation/fund-your-node/
```

please keep it simple and stupid. swarm bzz is so difficult to deploy. please provide a usable deploy tutorial.
thank you !

**Comment by whatarey** [comment]
curl -s http://localhost:1635/addresses | jq 

bee_1
{
  "overlay": null,
  "underlay": [],
  "ethereum": "0x9a943adeexxxxxxx",
  "publicKey": "xxxxx",
  "pssPublicKey": "xxx"
}
ethereum   is   node

**Comment by mfw78** [comment]
Thanks for your query. For more comprehensive support, you would be best served in the [#bee-support-mainnet](https://discord.gg/agpsxHvV) discord channel. Please kindly ask your question there.
