### ISSUE TITLE
I run ver 1.0.0 but warning msg="your node is outdated, please check for the latest version"

### ISSUE THREAD

**Issue by camille3344520** [ethersphere/bee#2182]
I run ver 1.0.0 but warning msg="your node is outdated, please check for the latest version"

**Comment by ahauswk** [comment]
me too

**Comment by wangshibing3318** [comment]
me too

**Comment by devjunj** [comment]
time="2021-06-22T08:58:43Z" level=warning msg="your node is outdated, please check for the latest version"

**Comment by whatarey** [comment]
time="2021-06-22T01:05:17Z" level=warning msg="your node is outdated, please check for the latest version"
bee-3_1    | time="2021-06-22T01:05:17Z" level=debug msg="using existing libp2p key"
bee-3_1    | time="2021-06-22T01:05:17Z" level=debug msg="using existing pss key"
bee-3_1    | time="2021-06-22T01:05:17Z" level=info msg="using ethereum address eeeee"
bee-3_1    | time="2021-06-22T01:05:17Z" level=info msg="version: 1.0.0-2572fa48"
bee-3_1    | Error: provided network ID does not match mainnet

**Comment by mrekucci** [comment]
@camille3344520 @ahauswk @devjunj @whatarey would you mind sharing the way (source) from which you've downloaded the nodes you have this problem?

**Comment by pennchester** [comment]
> @camille3344520 @ahauswk @devjunj @whatarey would you mind sharing the way (source) from which you've downloaded the nodes you have this problem?

I use this 
![1](https://user-images.githubusercontent.com/46217533/122912058-837eb980-d38a-11eb-810b-87f7d943778b.PNG)
![image](https://user-images.githubusercontent.com/46217533/122912223-ac9f4a00-d38a-11eb-904b-9d9b801042c8.png)

**Comment by ChainFans** [comment]
> @camille3344520 @ahauswk @devjunj @whatarey你介意分享你下载节点的方式（来源）吗？

https://github.com/ethersphere/bee/releases/download/v1.0.0/bee_1.0.0_amd64.rpm

**Comment by qqbbcr** [comment]
mee too.

**Comment by whatarey** [comment]
> @camille3344520 @ahauswk @devjunj @whatarey你介意分享你下载节点的方式（来源）吗？
wget -q https://raw.githubusercontent.com/ethersphere/bee/v1.0.0/packaging/docker/docker-compose.yml
image: ethersphere/bee:beta

**Comment by mutianqi** [comment]
me too. I use  this 
'https://github.com/ethersphere/bee/releases/download/v1.0.0/bee_1.0.0_amd64.deb'

 time="2021-06-23T01:05:24+08:00" level=info msg="version: 1.0.0-2572fa48"
 time="2021-06-23T01:05:24+08:00" level=info msg="waiting to sync with the Ethereum backend"
 time="2021-06-23T01:35:24+08:00" level=warning msg="your node is outdated, please check for the latest version"
time="2021-06-23T02:05:24+08:00" level=warning msg="your node is outdated, please check for the latest version"

**Comment by yaohuijie** [comment]
![image](https://user-images.githubusercontent.com/29352344/123027121-e23a4680-d40f-11eb-8f15-b51d9b173d2f.png)
This is the latest version

**Comment by xiaomugu** [comment]
yes me too

**Comment by anatollupacescu** [comment]
fix pending: #2196

**Comment by luoweidd** [comment]
time="2021-06-23T20:41:52+08:00" level=info msg="version: 1.0.0-2572fa48"
time="2021-06-23T20:41:52+08:00" level=info msg="debug api address: [::]:1625"
time="2021-06-23T20:41:52+08:00" level=info msg="waiting to sync with the Ethereum backend"
time="2021-06-23T21:11:50+08:00" level=warning msg="your node is outdated, please check for the latest version"
time="2021-06-23T21:41:50+08:00" level=warning msg="your node is outdated, please check for the latest version"
time="2021-06-23T22:11:50+08:00" level=warning msg="your node is outdated, please check for the latest version"

一样的节奏

**Comment by whatarey** [comment]
bee-1_1    | time="2021-06-23T06:36:33Z" level=debug msg="kademlia: disconnected peer ee21ace67f3e72d022d687505658c1ef9133b03a285fe99f7215ea950a6087e4"
bee-1_1    | time="2021-06-23T06:36:33Z" level=debug msg="libp2p disconnect: peer ee21ace67f3e72d022d687505658c1ef9133b03a285fe99f7215ea950a6087e4 not found"
bee-1_1    | time="2021-06-23T07:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T07:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T08:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T08:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T09:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T09:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T10:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T10:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T11:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T11:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T12:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T12:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T13:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T13:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T14:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T14:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T15:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T15:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T16:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T16:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T17:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T17:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T18:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T18:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T19:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T19:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T20:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T20:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T21:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T21:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T22:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T22:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T23:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-23T23:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-24T00:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-24T00:36:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-24T01:06:02Z" level=warning msg="your node is outdated, please check for the latest version"
bee-1_1    | time="2021-06-24T01:36:02Z" level=warning msg="your node is outdated, please check for the latest version"

**Comment by luoweidd** [comment]
me too

**Comment by addicted0010** [comment]
same issue here.

**Comment by lihdodo** [comment]
INFO[2021-06-24T01:17:53-04:00] debug api address: 127.0.0.1:1635
INFO[2021-06-24T01:17:55-04:00] waiting to sync with the Ethereum backend
WARN[2021-06-24T01:47:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T02:17:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T02:47:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T03:17:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T03:47:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T04:17:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T04:47:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T05:17:53-04:00] your node is outdated, please check for the latest version
WARN[2021-06-24T05:47:53-04:00] your node is outdated, please check for the latest version

![image](https://user-images.githubusercontent.com/23337312/123242193-5bbb5d00-d514-11eb-91e2-45fbae854dbd.png)

**Comment by mrekucci** [comment]
@luoweidd @whatarey @addicted0010 @lihdodo can you guys [download](https://github.com/ethersphere/bee/archive/refs/heads/master.zip), build (by `make binary`), and try to run (from `dist` directory) the latest binary?

**Comment by maketigers** [comment]
this version like a dog shit

**Comment by Eknir** [comment]
Hi all,

Thank you for reporting this. Your versions are not outdated, but due to a varying build process on different systems bee thinks it is outdated. This is a bug, but does not have any effect on the operation of your bee node. It is fixed per https://github.com/ethersphere/bee/issues/2196 and will released with the upcoming release. Thanks
