### ISSUE TITLE
Error: chequebook init: chequebook not deployed by factory

### ISSUE THREAD

**Issue by timmy2048** [ethersphere/bee#2185]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Actual behavior

time="2021-06-22T12:12:25+09:00" level=info msg="using ethereum address 819c5a5f0ac21aab48018dac50ccb38afeff81a9"
time="2021-06-22T12:12:25+09:00" level=info msg="version: 1.0.0-2572fa48"
time="2021-06-22T12:12:25+09:00" level=info msg="debug api address: [::]:1615"
time="2021-06-22T12:12:27+09:00" level=info msg="using default factory address for chain id 100: c2d5a532cf69aa9a1378737d8ccdef884b6e7420"
time="2021-06-22T12:12:29+09:00" level=info msg="using existing chequebook 10b7faa5c8cb9870face25b1ad6faf65a88eb1c1"
Error: chequebook init: chequebook not deployed by factory
I have 0.01xdai in my account

The following is my yaml configuration：
clef-signer-enable: false
data-dir: D:/.bee
swap-enable: true
swap-endpoint:  https://stake.getblock.io/mainnet/?api_key=ca6780d3-f5e3-4722-a472-fa9cdf677060
verbosity: info
welcome-message: "BOOM"
debug-api-enable: true
swap-initial-deposit: 0
bootnode-mode: true
mainnet: true
full-node: true
block-time: 5
gateway-mode: false
network-id: 1
api-addr: :1613
debug-api-addr: :1615
p2p-addr: :1614

**Comment by filwu8** [comment]
add：
swap-initial-deposit: 0

**Comment by WillanLan** [comment]
same issue how to fix?

**Comment by timmy2048** [comment]
Keep the keys file and delete the rest of the old data

在 周二, 6月 22, 2021 在 22:38, William ***@***.***> 来信：

**Comment by webdage** [comment]
same issue how to fix?

**Comment by ralph-pichler** [comment]
the chequebook in the log is from goerli test network. please make sure to start your mainnet node with a new data directory (copy over the `keystore` directory if not using clef).

**Comment by lystrosaurus** [comment]
Error: chequebook init: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 3500000000000000 and got: 0
