### ISSUE TITLE
error: rate limit exceeded 

### ISSUE THREAD

**Issue by dislikediss** [ethersphere/bee#2189]
In the process of running a node
Will attempt to link with a peer
If the request doesn't go through or if there is some other problem it will always be prompted
: error: rate limit exceeded
![1](https://user-images.githubusercontent.com/36874994/122874254-608dde80-d365-11eb-9069-ec36093f3f9f.png)

**Comment by Eknir** [comment]
This behavior is intentional, and in place in order to reduce the gossiping of addresses in the network
