### ISSUE TITLE
Peers disconnected at proximity order >= depth

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#219]
Kademlia topology for multiple nodes (in a 50 node cluster) has peers disconnected at proximity order >= depth.
Branch: https://github.com/ethersphere/bee/tree/debugapi-topology-content-type

Example for node 1 (bin 3) can be seen on link https://bee-1-debug.svetomir.core.internal/topology

`{
baseAddr: "e2faaaa6984d4919b1b4f9bd914da563aa3cf2de4d8cb2dece5c22bc999f1938",
population: 49,
connected: 15,
timestamp: "2020-05-26T15:22:25.16825826Z",
nnLowWatermark: 2,
depth: 3,
bins: {
bin_0: {
population: 26,
connected: 5,
disconnectedPeers: [
"791c7131de09fa01ff8478ed1e219501842a1c5211f9521783754b113f7ff34e",
"716cd3cb58f4ffd238f6f49a6201f9c2ef1d242042312677643ffdde8cd149f2",
"76642beda4b98b367f3d95db6be587345c8029f9cdac335aa0281d99f067fbe1",
"4a8e6665ecdbbfcccea195bc8c6bb35aadcebcc609d69141faf8e4145e8667a4",
"4e9012f52056c5162f54658214e0bb940eaaa3bc11553b1ee4585da355a11a8a",
"0c38fec0aabd3c5fcc184274f736457cb008ed15b8b522d68cc54e15e1b05157",
"4c969c9ccc5e866abbddda4cb71ecdac783d98f7c4b87f83753ab6efad8442f6",
"3876c4146f00bd6d8fcc304cfe1fb558ae6f8d0dd47b4d508177afeff0a9a1b4",
"6332a8d7ba900969a3914dfcbd8cbe4ee50f730936d51e74993fa11938bfd75c",
"6c11a823120257219614e2f589a1af1fc99a20359f75568261e8e6e81555762c",
"53a5b6c065f016530d2f467889790b7a91e866d532ecebcfac80abe781189624",
"2067461a682ad84758c1b2743fdc9854f0668ad40932dcaa990c941228fdbd5d",
"15b74e76fccb3be5318b5bd3d440420cabfec96013029a0a66d40d385fd5b585",
"41254bac986b19fdd88fcf9d2f2456d1af8d89a038e1a89e54bd885c95b64a5d",
"00c2867ec8073bcd6cb1ddeb206ace54b8f338bc39d2c3fd1872a7f3090f6407",
"6c0b3929f5faec0b228a1b48ed67b204f7efbf25b623d1d7a7abe65b9894b138",
"18dbb139e7e15d5a911643450a52119034d7ff6a82d9eb651fd276f0ebbd88b0",
"1735b4a281bd4645f4fbd5457bf2c7d59cc36909c7de7fb34414ae94c7102ac4",
"10bae4ed636322e61bbde05ab3650d4214379f0677c25bc91a1dbfb2c17a1799",
"3f12cf04485c10048fe593ba59f48f6cfb71551931fc65502612eb438f71c115",
"76397868fb77c49ad78059164a794c574de990aa73b9ba3d33523beacabdb848"
],
connectedPeers: [
"46ba6d6f36613f2ef6fefee2a7da7a1f30cac276e7be1f3a4e55b31cc253dd9b",
"4cde4679b4a18df016cab8aa83893f4f2753ab6872f850fb250e3812c96214d5",
"5a9564128c1dcac5c147b246116f2501d53e002d39503e927dce47861c861769",
"120f58bb00520fe155e1e677946e7d96993b788fdc3ea71c7aa7ebb266291ee8",
"2021e16344eab03646edd161fbc7ddcfdad8070c2a6f5233b5178d0affc9ab2d"
]
},
bin_1: {
population: 10,
connected: 2,
disconnectedPeers: [
"abde2b5ad434dfdbcce2bf0d29cc86a2adaaaf08f9aa3905b57370e74afc4c6f",
"b321dd23a8e9982d88e14ba52a79c2e7f1195777ceb4aa568fdc4454d2bbc0e9",
"bad1b2ab6bdbe4a799dfc482ec0bea3d954038954d7d00ec093240aedf2ef06f",
"8b008aac0395048381513ef67201e009c1339a1443e9ca4dd3de97ff9fa45711",
"830b066a9a38837a00fb1ef7f69aa3e2838482efec2f4dec3cc384cafce248a4",
"95168ce06e6c61b4e15221a0f73146d9fcfd4f045a1627198dff8eb2e00bee0e",
"86e2311817f63722a6df74a211448463370878850aa0f68701058b15d659b126",
"b26e2e61be78cc1e3e1adfbf5d14e1466678b0e2d8df304c5c911eb1798c1449"
],
connectedPeers: [
"81501514d76848d19edb16a3ad740d31b883a721260775bac553c06363c4095c",
"8192e3641ed045f10891151462b5809fd0bf47e4f9f1b75cd63e8e7a77af01ef"
]
},
bin_2: {
population: 6,
connected: 2,
disconnectedPeers: [
"c95e0bcf4d27b0f1004a95d1cbf246d8e780aff3e5c106ac2f7650b682bf817b",
"d8a569a9e9fe37bf394fd45f4bdbd024bdaa5966880faa87d8e2e14552fb7cf3",
"cea4b8a60304073e42650fb4d6ed237599dedbac86630f9bd90a5c5921ccbced",
"da8a42846a0af4f2f469a37060720e126546439f975a2a227036ac01b3ccd335"
],
connectedPeers: [
"ce557ad5ac43065a24dc00111d9e983aae9652bacef3351cbc9321f4b8942019",
"c38f807718be6f2eea930aebfcabc058b5ef59777bedeba0c08db2dcc5d4d1e0"
]
},
bin_3: {
population: 6,
connected: 5,
disconnectedPeers: [
"fb5904b853457734d5a0f08bce6e45ecbbf6d6aff3a62ef0e95dc0690522b4b1"
],
connectedPeers: [
"fa4343f457efea327cd63dfb1fdeda9aae683d6e3dab4cdbfee6e619a127bc51",
"f0a89d6bda3f86bd099e4e9abe52fde9bf6aba491d1b0a5a38347868f284022a",
"f0f04b613ae02bdaf48094863476f0882c1c81894a0652fee12a38fe1bf85e2e",
"f6068d55ef05597fb5f0c01c31699bf7501c5fe00d1d0353332e7eb0003db2bc",
"fd4dbcf76025afa442b02d35190c87c3d92f6b32a84b8eacfc6ebc3e822463dd"
]
},
bin_4: {
population: 1,
connected: 1,
disconnectedPeers: null,
connectedPeers: [
"e91bcca7d761768232b8acab319ae9b86bd3d42c67f04e791d6c85be5b3bed5f"
]
},
bin_5: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_6: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_7: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_8: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_9: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_10: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_11: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_12: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_13: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_14: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
},
bin_15: {
population: 0,
connected: 0,
disconnectedPeers: null,
connectedPeers: null
}
}
}`

NOTE: I left cluster up and running in case you need more detailed inspection.

**Comment by acud** [comment]
so.. this is a bit strange and I can think of a couple of things:
- peer was sanctioned for some reason (not sure why since there shouldn't be any errors or disconnections). now if the peer is disconnected, and the manageC channel was not triggered since no peer was added, then the check for the sanctioned peer was never triggered, and so we never end up connecting to the peer.
- possible solution - if we encounter a sanctioned peer that we'd like to connect to, spawn a goroutine that will after some time trigger `manageC` so we get to that peer eventually and connect to it. this can be verified by the following: add a non-reachable peer to this node (node 1) via debug api, this will trigger manageC and because we can already connect to the peer, then it should finally connect to it

**Comment by janos** [comment]
According to log messages, all of these disconnects happened because of p2p.ErrAlreadyConnected in Kad.connect method when the peer was received by the hive protocol and that peer is already connected. I will test some solutions and make a PR afterwards.

**Comment by janos** [comment]
This issue could be closed as the remaining issue can be defined separately as of https://github.com/ethersphere/bee/pull/232 is merged, as the consequence is different.

The remaining issue is the false tracking in kademlia that a peer is disconnected and it actually is not.

**Comment by janos** [comment]
Closing this issue as followup one is made.
