### ISSUE TITLE
I use docker-compose to arrange nodes,How to export private keys from the node with bee-clef installed?

### ISSUE THREAD

**Issue by alingb** [ethersphere/bee#2190]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Steps to reproduce

How to export private keys from the node with bee-clef installed?I use docker-compose to arrange nodes

**Comment by Eknir** [comment]
Thanks for trying out Bee. This is a request-for-support and not a bug. Please join our Discord for support, and we gladly answer your question there: https://discord.gg/sU8NEtaR8y
