### ISSUE TITLE
chequebook init: Invalid chain id --> When use docker

### ISSUE THREAD

**Issue by cielu** [ethersphere/bee#2192]
bee-1_1   | time="2021-06-22T12:05:06Z" level=info msg="no chequebook found, deploying new one."
bee-1_1   | time="2021-06-22T12:05:06Z" level=trace msg="sending transaction 8d3c8ff96384d66945ff4d22a11a17440e6b0530fdafdsafdsafdsaa44ed3 with nonce 0"
bee-1_1   | Error: chequebook init: Invalid chain id.

**Comment by devjunj** [comment]
me too

**Comment by Eknir** [comment]
Thanks for trying out Bee. This points to an issue in your configuration. Please join our Discord for support: https://discord.gg/sU8NEtaR8y

**Comment by tqtcloud** [comment]
Me too, is there any solution

**Comment by mutianqi** [comment]
me too
