### ISSUE TITLE
there are an error that trigger bee to exit on windows is  "failed syncing event listener, shutting down node err: 503 Service Unavailable: upstream connect error or disconnect/reset before headers. reset reason: connection failure"

### ISSUE THREAD

**Issue by lwf163** [ethersphere/bee#2197]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary
bee.exe is running, but no other error happenned. when that error log is printted, bee will exit. I'd Know what happened.
How can bee won't exit by that error？

**Comment by lwf163** [comment]
bee version is 1.0.0

**Comment by devjunj** [comment]
i have the same issue

**Comment by rmokerone** [comment]
i have the same issue too

```
bee-1_1       | time="2021-06-22T15:15:32Z" level=error msg="failed syncing event listener, shutting down node err: 503 Service Unavai
lable: upstream connect error or disconnect/reset before headers. reset reason: overflow"
bee-1_1       | time="2021-06-22T15:15:32Z" level=info msg="api shutting down"
bee-1_1       | time="2021-06-22T15:15:32Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1       | time="2021-06-22T15:15:34Z" level=info msg="debug api access" duration=2.707478873 ip=172.20.0.1 method=GET proto=HTTP
/1.1 size=45 status=200 uri=/chequebook/balance user-agent=curl/7.68.0
bee-1_1       | time="2021-06-22T15:15:34Z" level=warning msg="peer not reachable when attempting to connect"
bee-1_1       | time="2021-06-22T15:15:34Z" level=info msg="pusher shutting down"
bee-1_1       | time="2021-06-22T15:15:34Z" level=info msg="puller shutting down"
bee-1_1       | time="2021-06-22T15:15:34Z" level=info msg="pull syncer shutting down"
bee-1_1       | time="2021-06-22T15:15:34Z" level=info msg="kademlia shutting down"
```

**Comment by dislikediss** [comment]
i have the same issue too

**Comment by ldeffenb** [comment]
These are all issues caused by a failed connection to your configured swap-endpoint.  Get a more stable connection to your swap-endpoint.  bee monitors the swap-endpoint and will shut down your node if errors are detected.  The postage stamps require this in order to keep track of the currently valid stamps.  The most reliable swap-endpoint you can have is running your own local blockchain node.

This is NOT an issue with bee but with your configuration and your chosen swap-endpoint.
