### ISSUE TITLE
Issue: no bootnodes defined for network ID1

### ISSUE THREAD

**Issue by ahauswk** [ethersphere/bee#2201]
.
time="2021-06-23T12:31:40+08:00" level=warning msg="no bootnodes defined for network ID1"
Error: init chain: dial eth client: dial tcp [::1]:8546: connectex: No connection could be made because the target machine actively refused it.

**Comment by microfisher** [comment]
how did you fix it?

**Comment by ldeffenb** [comment]
You need to configure a swap-endpoint.  See https://docs.ethswarm.org/docs/installation/install#blockchain-endpoints
