### ISSUE TITLE
Error: init chain: dial eth client: dial tcp [::1]:8546: connectex: No connection could be made because the target machine actively refused it. description

### ISSUE THREAD

**Issue by ahauswk** [ethersphere/bee#2202]
Error: init chain: dial eth client: dial tcp [::1]:8546: connectex: No connection could be made because the target machine actively refused it.

**Comment by mfw78** [comment]
Thanks for your query. This is a support related question which is best served in the [#bee-support-mainnet](https://discord.gg/agpsxHvV) discord channel. Please kindly ask your question there.
