### ISSUE TITLE
Bee start error, unlimited restart

### ISSUE THREAD

**Issue by xuanyuan219** [ethersphere/bee#2204]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary
I have recharged 1 BZZ for the node address and 1 xdai for xdai network, but the system reported an error when creating the checkbook

#### Steps to reproduce
sudo systemctl start bee
Error: init chain: is synced: 503 Service Unavailable: upstream connect error or disconnect/reset before headers. reset reason: overflow
16:34:51 10-7-73-40 bee[29510]: time="2021-06-23T16:34:51+08:00" level=info msg="using default factory address for chain id 100: c2d5a532cf69aa9a1378737d8ccdef884b6e7420"
16:34:51 10-7-73-40 systemd[1]: bee.service: main process exited, code=exited, status=1/FAILURE
16:34:51 10-7-73-40 systemd[1]: Unit bee.service entered failed state.
![image](https://user-images.githubusercontent.com/9054488/123066268-7a512380-d442-11eb-9237-88131cd40929.png)
![image](https://user-images.githubusercontent.com/9054488/123066351-8fc64d80-d442-11eb-8540-d5c9044dbe95.png)
![image](https://user-images.githubusercontent.com/9054488/123066527-b8e6de00-d442-11eb-9aa2-c1ee869711bd.png)
![image](https://user-images.githubusercontent.com/9054488/123066432-a7053b00-d442-11eb-8bd4-c86f60fa1527.png)
![image](https://user-images.githubusercontent.com/9054488/123066466-ad93b280-d442-11eb-95ac-894a9e093c5a.png)

**Comment by ldeffenb** [comment]
Your swap-endpoint is not working properly.  Get a better swap-endpoint.
