### ISSUE TITLE
General problem deError: init chain: is synced: 503 Service Unavailable: upstream connect error or disconnect/reset before headers. reset reason: connection failurescription

### ISSUE THREAD

**Issue by zhangzengli** [ethersphere/bee#2206]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

**Comment by mfw78** [comment]
Thanks for your query. This is a support related question which is best served in the [#bee-support-mainnet](https://discord.gg/agpsxHvV) discord channel. Please kindly ask your question there.
