### ISSUE TITLE
event listener exit when got any error from swap endpoint

### ISSUE THREAD

**Issue by mntya** [ethersphere/bee#2208]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary
When running Bee node in mainnet, the event listener exit when any error got from swap endpoint.

#### Steps to reproduce
Running Bee node in mainnet,  swap endpoint response timeout or connection broken.

#### Expected behavior
Bee node not shutting down, and retry to interact with swap endpoint.
Maybe configrable retry and retry times will be best.

#### Actual behavior
Bee node exit immediately when error from swap endpoint.

**Comment by mfw78** [comment]
Hi @mntya, thanks for your query. This is normal functioning of Bee. If you wish to suggest an alternative method of monitoring postage stamps, please open another issue. If you wish to discuss this support related question, you are best served in the [#bee-support-mainnet](https://discord.gg/agpsxHvV) discord channel.
