### ISSUE TITLE
provided network ID does not match mainnet && your node is outdated, please check for the latest version  What should I do?

### ISSUE THREAD

**Issue by luoweidd** [ethersphere/bee#2209]
bug 1 ：provided network ID does not match mainnet
config：
debug-api-enable: true
swap-initial-deposit: "10000000000000000"
full-node: true
# db-open-files-limit: 2000000
api-addr: :1623
p2p-addr: :1624
debug-api-addr: :1625
networkID: 1
mainnet: true

bug2:
time="2021-06-23T20:41:52+08:00" level=info msg="debug api address: [::]:1625"
time="2021-06-23T20:41:52+08:00" level=info msg="waiting to sync with the Ethereum backend"
time="2021-06-23T21:11:50+08:00" level=warning msg="your node is outdated, please check for the latest version"
time="2021-06-23T21:41:50+08:00" level=warning msg="your node is outdated, please check for the latest version"
time="2021-06-23T22:11:50+08:00" level=warning msg="your node is outdated, please check for the latest version"
config2：
debug-api-enable: true
swap-initial-deposit: "10000000000000000"
full-node: true
# db-open-files-limit: 2000000
api-addr: :1623
p2p-addr: :1624
debug-api-addr: :1625
networkID: 1
# mainnet: true

What should I do?

**Comment by taleStone** [comment]
set CLEF CHAINID = 100

**Comment by luoweidd** [comment]
It didn't work

**Comment by Uly41** [comment]
same problem here

**Comment by mfw78** [comment]
Thanks for your issue. For support on these kinds of issues, please contact the support team on the [#bee-mainnet-support](https://discord.gg/agpsxHvV) discord channel.
