### ISSUE TITLE
process at  "waiting to sync with the Ethereum backend"

### ISSUE THREAD

**Issue by lylllou** [ethersphere/bee#2213]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary

![image](https://user-images.githubusercontent.com/57655073/123243780-ebadd680-d515-11eb-85f5-2d99d273577d.png)

**Comment by mfw78** [comment]
Thanks for your query. This is a support related question which is best served in the [#bee-support-mainnet](https://discord.gg/agpsxHvV) discord channel. Please kindly ask your question there.
