### ISSUE TITLE
Check the validity of a postage stamp batch

### ISSUE THREAD

**Issue by nagydani** [ethersphere/bee#2220]
# User story

## Story

As an uploader or content curator, I would like to be able to easily check whether a certain batch is still valid. If it is, additional information such as its balance and the estimated validity time based on current rent would also be helpful. It should be a public API endpoint, not a debug one, as this information is entirely public and accessing the endpoint does not modify any state. 

## Acceptance criteria

Given a running bee node, a GET request to its corresponding endpoint with reference to `batchID` should return whether or not the given `batchID` is valid.

**Comment by acud** [comment]
This is covered by the newly added functionalities in bee `v1.1.0` under the debug api `/stamps` endpoint. `Exists` field will be `false` in case the batch has not yet propagated to the node from the chain data, or if the batch has already expired. The batch ttl field will indicate in how long (secs) the batch will expire
