### ISSUE TITLE
compose.parallel.feed_queue: Pending: set()

### ISSUE THREAD

**Issue by hesen2006cn** [ethersphere/bee#2224]
compose.parallel.feed_queue: Pending: {<Service: bee-80>, <Service: bee-59>, <Service: bee-1>, <Service: bee-30>, <Service: bee-44>, <Service: bee-27>, <Service: bee-2>, <Service: bee-41>, <Service: bee-118>, <Service: bee-55>, <Service: bee-71>, <Service: bee-19>, <Service: bee-48>, <Service: bee-4>, <Service: bee-88>, <Service: bee-28>, <Service: bee-68>, <Service: bee-52>, <Service: bee-39>, <Service: bee-70>, <Service: bee-115>, <Service: bee-117>, <Service: bee-66>, <Service: bee-18>, <Service: bee-79>, <Service: bee-85>, <Service: bee-13>, <Service: bee-98>, <Service: bee-78>, <Service: bee-7>, <Service: bee-114>, <Service: bee-89>, <Service: bee-95>, <Service: bee-22>, <Service: bee-91>, <Service: bee-116>, <Service: bee-15>, <Service: bee-53>, <Service: bee-76>, <Service: bee-17>, <Service: bee-54>, <Service: bee-60>, <Service: bee-107>, <Service: bee-29>, <Service: bee-67>, <Service: bee-100>, <Service: bee-16>, <Service: bee-40>, <Service: bee-51>, <Service: bee-42>, <Service: bee-101>, <Service: bee-6>, <Service: bee-26>, <Service: bee-64>, <Service: bee-43>, <Service: bee-31>, <Service: bee-12>, <Service: bee-47>, <Service: bee-3>, <Service: bee-14>, <Service: bee-49>, <Service: bee-5>, <Service: bee-38>, <Service: bee-74>, <Service: bee-25>, <Service: bee-90>, <Service: bee-81>, <Service: bee-65>, <Service: bee-72>, <Service: bee-119>, <Service: bee-23>, <Service: bee-105>, <Service: bee-99>, <Service: bee-33>, <Service: bee-94>, <Service: bee-45>, <Service: bee-75>, <Service: bee-97>, <Service: bee-92>, <Service: bee-69>, <Service: bee-87>, <Service: bee-104>, <Service: bee-111>, <Service: bee-113>, <Service: bee-77>}
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()

**Comment by acud** [comment]
Hello! Please use the issue template when opening a new bug report
