### ISSUE TITLE
Can't buy a  new postage batch, signature 5239af71 not found

### ISSUE THREAD

**Issue by fanyongpeng** [ethersphere/bee#2254]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary

I want buy a postage batch in mainnet bee. But it return {"message":"cannot create batch","code":500}

#### Steps to reproduce

My bee is deployed by docker.
1.  curl localhost:1633/stamps/10000000/20?label=t2     -X POST
2. It return
   `{"message":"cannot create batch","code":500}`
3. I check the logs 
    `time="2021-06-30T07:05:28Z" level=debug msg="create batch: failed to create: send: depth 20 bucketDepth 16 immutable false: validation failed: Transaction contains data, but the ABI signature could not be found: signature 5239af71 not found"`
4. Upgrade my clef version from 0.4.12 to 0.5.0. Same problem 
5.  Check the clef's 4byte.json
    `{
  "0d5f2659": "cashChequeBeneficiary(address,uint256,bytes)",
  "576d7271": "deploySimpleSwap(address,uint256)",
  "15efd8a7": "deploySimpleSwap(address,uint256,bytes32)",
  "2e1a7d4d": "withdraw(uint256)",
  "e9563f05": "createBatch(address,uint256,uint8,bytes32)"
}`

There is no abi named with 5239af71. Is that the docker clef not catch up the code of  bee 1.0.0? 

I compare the file 4byte.json in bee-clef and docker-clef. bee-clef is right, but  docker-clef missing this abi:
` "5239af71": "createBatch(address,uint256,uint8,uint8,bytes32,bool)"`

#### Expected behavior

It shoud return hash
#### Actual behavior

   `{"message":"cannot create batch","code":500}`

**Comment by Eknir** [comment]
Hi there, thank you for reporting. This is on our radar and we will report here.

**Comment by acud** [comment]
you need to update the 4byte.json file:
https://github.com/ethersphere/bee-clef/blob/master/packaging/4byte.json
