### ISSUE TITLE
Unpinning encrypted chunk fails

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2284]
#### Summary
I was trying to unpin an encrypted chunk. Bee returns 500 Internal Server Error.

#### Steps to reproduce
1. Upload encrypted, pinned data. I used swarm-cli for that
2. Then I queried the list of pinned chunks with the `/pins` endpoint, it returned
```json
{"references":["0118ec07f4d9791292aad45e5698643a458a5769ea09c96e6423b0ac92e091af6010995fec936a5577e6155ebe963788966914a9ade93237a5cf85b78a7134e3","549b38d94e08349d9218933907313a971e3b22bd9d716f04ab8a70ad1712a52d3ef23e2a69af1d39b124f46ed66ec5fdc7855cdbaaf181a48890a3804c64a21c","e030c463f75b032458d8c80a1a49cb56bce4d49b2fb9c9084d7f69f874d4702f179c8763ccf23acebf77b68f7be84ffb2a05b5e5b87619cdaf4de978c4a22b6d"]}
```
3. Then I took one from the list (`e030c463f75b032458d8c80a1a49cb56bce4d49b2fb9c9084d7f69f874d4702f179c8763ccf23acebf77b68f7be84ffb2a05b5e5b87619cdaf4de978c4a22b6d`) and tried to unpin it with swarm-cli
4. I got Internal Server Error
#### Expected behavior
I expected that I can unpin a pinned chunk with its reference.

#### Actual behavior
I got Internal Server Error

See the logs from the Bee node:
```
time="2021-07-02T12:34:12Z" level=debug msg="unpin root hash: deletion of pin for \"e030c463f75b032458d8c80a1a49cb56bce4d49b2fb9c9084d7f69f874d4702f179c8763ccf23acebf77b68f7be84ffb2a05b5e5b87619cdaf4de978c4a22b6d\" failed: 3 errors occurred:\n\t* traversal iteration failed\n\t* get value: leveldb: not found\n\t* unable to unpin the chunk for leaf \"5bcf3dd76a18b305f4e74aa9a81bd3f9633d07f455bee35a45087bdee6332773724842005cdd364a7bcba317a907897685fc8da01f43354831d1a634d5bd85ac\" of root \"e030c463f75b032458d8c80a1a49cb56bce4d49b2fb9c9084d7f69f874d4702f179c8763ccf23acebf77b68f7be84ffb2a05b5e5b87619cdaf4de978c4a22b6d\": get value: leveldb: not found\n\n"
time="2021-07-02T12:34:12Z" level=info msg="api access" duration=0.0186536 ip=172.18.0.1 method=DELETE proto=HTTP/1.1 size=48 status=500 uri=/pins/e030c463f75b032458d8c80a1a49cb56bce4d49b2fb9c9084d7f69f874d4702f179c8763ccf23acebf77b68f7be84ffb2a05b5e5b87619cdaf4de978c4a22b6d user-agent=axios/0.21.1
```

**Comment by istae** [comment]
As of v1.1.0-rc2, I could not replicate this issue. PR 2411 adds better unit testing that covers this as well.

**Comment by istae** [comment]
![image](https://user-images.githubusercontent.com/14264581/129937843-8400854a-2ffa-4690-aa90-8c00250d4fc0.png)

**Comment by agazso** [comment]
Can confirm, with 1.1.0-rc2 it works correctly.

**Comment by acud** [comment]
@agazso can you try to reproduce this with an earlier version? i'm not sure if we've changed anything in any of the related packages tbh...

**Comment by istae** [comment]
@acud I tried with v1.0.0, it works correctly as well.
