### ISSUE TITLE
0 utilization postage batch - Payment Required: batch is overissued

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#2312]
# Environment

Using `bee-factory` with `bee` `1.0.0-2572fa48` and using local `ganache` as blockchain (provided by `bee-factory`)

# Creating the File to Upload

I created 1MB of random data

`dd if=/dev/urandom count=1000 bs=1000 > 1mb.bin`

---

# Checking the Postage Batch

I have a postage batch as follows:

```
Stamp ID: 533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481
Usage: 0%
Depth: 50
Bucket Depth: 16
Amount: 1000
Usable: true
Utilization: 0
Block Number: 20098
Immutable Flag: false
```

or via `curl`:

```
curl http://localhost:1633/stamps/533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481

{"batchID":"533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481","utilization":0,"usable":true,"label":"recovered","depth":50,"amount":"1000","bucketDepth":16,"blockNumber":20098,"immutableFlag":false}
```

---

# Uploading 

```
swarm-cli upload 1mb.bin --stamp 533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481

Payment Required: batch is overissued
```

or via `curl`:

```
curl http://localhost:1633/bzz -X POST -H "swarm-postage-batch-id:533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481" --data @1mb.bin

{"message":"batch is overissued","code":402}
```

or 1 byte:

```
curl http://localhost:1633/bzz -X POST -H "swarm-postage-batch-id:533b6a52082a0bb9499a8233cf5c885ff6eb14c3b8aa41fa29df55328ed63481" --data 'a'
{"message":"batch is overissued","code":402}
```

---

# Bee logs

```
time="2021-07-07T10:16:10Z" level=debug msg="bzz upload file: file store, file \"\": bucket full"
time="2021-07-07T10:16:10Z" level=error msg="bzz upload file: file store, file \"\""
time="2021-07-07T10:16:10Z" level=info msg="api access" duration=0.0004573 ip=172.21.0.1 method=POST proto=HTTP/1.1 size=46 status=402 uri=/bzz user-agent=curl/7.64.1
```

**Comment by Cafe137** [comment]
Bee log:

```
time="2021-07-07T10:16:10Z" level=debug msg="bzz upload file: file store, file \"\": bucket full"
time="2021-07-07T10:16:10Z" level=error msg="bzz upload file: file store, file \"\""
time="2021-07-07T10:16:10Z" level=info msg="api access" duration=0.0004573 ip=172.21.0.1 method=POST proto=HTTP/1.1 size=46 status=402 uri=/bzz user-agent=curl/7.64.1
```

**Comment by acud** [comment]
Hi @Cafe137. While it is not clear whether you've stamped any uploads prior to the upload that you've mentioned, one thing looks suspicious, and that is that the batch depth is 50. That means that it should accommodate 2^50 (1125899906842624) chunks or in other words `4611686.018427387904 petabytes` which is quite a bit. It could be that there's some overflow issue. We'll look into it, thanks!

**Comment by ldeffenb** [comment]
While you're looking at stamp strangeness, I have the following stamp on mainnet that SHOULD have ended up less than 70% full after a complete upload.  The uploading node did crash several times during the upload and after one of those crashes the stamp jumped from nowhere near 100% to 100% in one jump.  I only bring it up here because it was also a larger depth (30) than people typically purchase.

```
  "stamps": [
    {
      "batchID": "d7dcb4544a164e71333a9096be22f81a848c569fa77f74b0131940f30c61bdc7",
      "utilization": 16384,
      "usable": true,
      "label": "",
      "depth": 30,
      "amount": "10000000",
      "bucketDepth": 16,
      "blockNumber": 17404168,
      "immutableFlag": false
    },
```

I ended up purchasing another (smaller) stamp to restart and complete the upload, so now my data is covered by one or the other stamp, and I'm not sure how to tell which one is which.  The former has a really long duration while the new one (below) is only 10% of that duration.

```
    {
      "batchID": "7a2aa4b3760235c8d7243d68847739078ee9d9e21b4e131a13e216a97356e51a",
      "utilization": 123,
      "usable": true,
      "label": "",
      "depth": 25,
      "amount": "1000000",
      "bucketDepth": 16,
      "blockNumber": 17425802,
      "immutableFlag": false
    }
```
