### ISSUE TITLE
Tag not updated when uploaded files using stream

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#2317]
#### Summary

When I upload a file to `/bzz` with stream (eq. with Transfer Encoding: chunked) and attached tag, the tag has always reported `total` of 3 chunks, even when the upload is finished.

If I specify the `content-length` with expected length then the tag has correctly reported the number of `total` chunks.

If after the upload is finished I call `PATH /tags/{uid}` with the returned reference the `total` is updated with correct number of chunks.

#### Expected behavior

Upon upload using stream, the tag has expected `total` chunks count.

#### Actual behavior

It always returns `total: 3`.

**Comment by Eknir** [comment]
Thanks for finding this!

**Comment by AuHau** [comment]
Since the idea is to get rid of the tag system in long run I would say it is alright to close this.
