### ISSUE TITLE
Failed to open master, rules disabled

### ISSUE THREAD

**Issue by EysaDun** [ethersphere/bee#2346]
clef container shows this log:
Failed to open master, rules disabled err="failed stat on /app/data/masterseed.json: stat /app/data/masterseed.json: no such file or directory

I installed bee and clef by docker-compose:
`version: "3"

services:
  clef-01:
    image: ethersphere/clef:0.5.0
    restart: unless-stopped
    environment:
      - CLEF_CHAINID=1
    volumes:
      - ./volumes/clef-01:/app/data
    command: full
  bee-01:
    image: ethersphere/bee:1.0.0
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CLEF_SIGNER_ENABLE
      - BEE_CLEF_SIGNER_ENDPOINT=http://clef-01:8550
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_DEBUG_API_ADDR
      - BEE_DEBUG_API_ENABLE
      - BEE_GATEWAY_MODE
      - BEE_GLOBAL_PINNING_ENABLE
      - BEE_FULL_NODE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_SWAP_ENABLE
      - BEE_SWAP_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
      - BEE_MAINNET
    ports:
      - "${API_ADDR:-10133}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-10134}${BEE_P2P_ADDR:-:1634}"
      - "${DEBUG_API_ADDR:-127.0.0.1:10135}${BEE_DEBUG_API_ADDR:-:1635}"
    volumes:
      - ./volumes/bee-01:/home/bee/.bee
    command: start
    depends_on:
      - clef-01

`

see the clef-01 volumes:
volumes:
  - ./volumes/clef-01:/app/data
maybe container can not create the masterseed.json file.
And i see other guys found the same err.
How to fix it?

**Comment by mfw78** [comment]
I strongly suspect that this is a permissions error on `./volumes/clef-01` that is causing this issue. As such, I'm going to close this for now. If there are any issues pertaining to this, this is more of a general support question, and I'd advise you to contact us on Discord.
