### ISSUE TITLE
Raspberry Pi run bee warning msg="your node is outdated, please check for the latest version"

### ISSUE THREAD

**Issue by xuanyuan219** [ethersphere/bee#2360]
Jul 23 07:12:39 ubuntu systemd[1]: Started Bee - Ethereum Swarm node.
Jul 23 07:12:39 ubuntu bee[77336]: Welcome to Swarm.... Bzzz Bzzzz Bzzzz
Jul 23 07:12:39 ubuntu bee[77336]:                 \     /
Jul 23 07:12:39 ubuntu bee[77336]:             \    o ^ o    /
Jul 23 07:12:39 ubuntu bee[77336]:               \ (     ) /
Jul 23 07:12:39 ubuntu bee[77336]:    ____________(%%%%%%%)____________
Jul 23 07:12:39 ubuntu bee[77336]:   (     /   /  )%%%%%%%(  \   \     )
Jul 23 07:12:39 ubuntu bee[77336]:   (___/___/__/           \__\___\___)
Jul 23 07:12:39 ubuntu bee[77336]:      (     /  /(%%%%%%%)\  \     )
Jul 23 07:12:39 ubuntu bee[77336]:       (__/___/ (%%%%%%%) \___\__)
Jul 23 07:12:39 ubuntu bee[77336]:               /(       )\
Jul 23 07:12:39 ubuntu bee[77336]:             /   (%%%%%)   \
Jul 23 07:12:39 ubuntu bee[77336]:                  (%%%)
Jul 23 07:12:39 ubuntu bee[77336]:                    !
Jul 23 07:12:39 ubuntu bee[77336]: DISCLAIMER:
Jul 23 07:12:39 ubuntu bee[77336]: This software is provided to you "as is", use at your own risk and without warranties of any kind.
Jul 23 07:12:39 ubuntu bee[77336]: It is your responsibility to read and understand how Swarm works and the implications of running this software.
Jul 23 07:12:39 ubuntu bee[77336]: The usage of Bee involves various risks, including, but not limited to:
Jul 23 07:12:39 ubuntu bee[77336]: damage to hardware or loss of funds associated with the Ethereum account connected to your node.
Jul 23 07:12:39 ubuntu bee[77336]: No developers or entity involved will be liable for any claims and damages associated with your use,
Jul 23 07:12:39 ubuntu bee[77336]: inability to use, or your interaction with other nodes or the software.
Jul 23 07:12:39 ubuntu bee[77336]: version: 1.0.0-2572fa48 - planned to be supported until 1 April 1970, please follow http://ethswarm.org/
Jul 23 07:12:39 ubuntu bee[77336]: time="2021-07-23T07:12:39Z" level=warning msg="your node is outdated, please check for the latest version"

**Comment by mfw78** [comment]
Duplicate #2182
