### ISSUE TITLE
Error: rename data/node31/statestore/CURRENT.559529 data/node31/statestore/CURRENT: structure needs cleaning

### ISSUE THREAD

**Issue by wanming851** [ethersphere/bee#2362]
Error: rename data/node31/statestore/CURRENT.559529 data/node31/statestore/CURRENT: structure needs cleaning

**Comment by acud** [comment]
Hi,
Please follow our github template when opening a new issue. Without adequate debugging information we cannot help you.
Thank you for the understanding
