### ISSUE TITLE
Where is the contract code for factoryaddress? thank you

### ISSUE THREAD

**Issue by oneusdt** [ethersphere/bee#2363]
https://blockscout.com/xdai/mainnet/address/0xC2d5A532cf69AA9A1378737D8ccDEF884B6E7420/contracts
Factoryaddress I can't find the contract code for factory. Can you tell me where to find it?

**Comment by ldeffenb** [comment]
Maybe somewhere in https://github.com/ethersphere/swap-swear-and-swindle

**Comment by mfw78** [comment]
You can find the factory address in https://github.com/ethersphere/bee/blob/master/pkg/config/chain.go.

**Comment by mfw78** [comment]
Duplicate #2381
