### ISSUE TITLE
centralize peer connection logic

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#237]
we currently have a few places where peers are added to the system:
- persisted address book
- bootnodes flag
- incoming p2p connections
- debug api
- kademlia (initiated connections)

there are duplicate sequences of code that do p2p connections, addressbook puts, then notify kademlia (sometimes). this is too verbose and error prone, as recent integration tests have revealed.
there should be one intermediate component (or dedicated endpoints within an existing component) that handles:
- add peer to backlog (but not connect)
- add peer immediately (for use by debug api)
- add incoming peer (dial-in)

and does the relevant address book operation, p2p operation and kademlia notifications

**Comment by pradovic** [comment]
Maybe this can help: https://github.com/ethersphere/bee/pull/247.
`topology.Connected`-  means that we have a new connected code,
`topology.AddPeer` -  means that we want to add new node to topology, regardless of connection status.

**Comment by pradovic** [comment]
One more idea:
My original idea for this was to broadcast new peers added in the addressbook, and actually listen to this event in toploguy, and not have `topology.AddPeer` call at all.
