### ISSUE TITLE
allow transaction from another sender for identity tx

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#2394]
Currently we require a transaction sent from the public key that the overlay derivation is based on. This makes running a bee node with swap disabled difficult as sending a tx from the internal or the clef key in that case is quite difficult.

Instead of requiring the tx to be signed from that account we could also accept an additional type where the tx data matches the eth address for which the proof is for. Then the identity tx can also be created using any wallet which supports tx data.

As the required data for every address is different this still should enforce the same security as the current approach. It is good to support both types as nodes with chequebook will already have a tx satisfying the current type.

**Comment by acud** [comment]
done
