### ISSUE TITLE
The program is always displayed:"clef is not enabled"

### ISSUE THREAD

**Issue by Hdj666-up** [ethersphere/bee#2397]
1.There was an error running the program with the “bee start” command，appear：“warn clef is not enabled; portability and security of your keys is sub optimal “，But my bee.yaml configuration is set to:  clef-signer-enable: true，clef-signer-endpoint: /var/lib/bee-clef/clef.ipc。
2.There is another problem：”Error: connected to wrong ethereum network: got chainID 100, want 5“
My bee-clef setting ：bee_clef_chain_id:100

**Comment by ldeffenb** [comment]
I suspect you need to read the follow FAQ and choose the appropriate command to start your node vs the bee.yaml file that you are customizing:

https://docs.ethswarm.org/docs/FAQ#what-is-the-difference-between-systemctl-and-bee-start

**Comment by Hdj666-up** [comment]
Okay, thanks, that's really a problem with the way I started it

**Comment by Hdj666-up** [comment]
Hello.... I'm having another problem now。INFO:still waiting for Ethereum to sync. Block time is 1970-01-01 08:00:00 +0800 CST.  It seems that its time is wrong，Am I missing any configuration?

**Comment by acud** [comment]
Please make sure your system time settings are correct and that your node is synced. We also saw this sort of messages coming from some nethermind xdai clients. Not sure what's the workaround there

**Comment by Hdj666-up** [comment]
> Please make sure your system time settings are correct and that your node is synced. We also saw this sort of messages coming from some nethermind xdai clients. Not sure what's the workaround there

Well, that's no way, thank you

**Comment by acud** [comment]
We've seen this before and this is due to an unsynced blockchain backend. Closing this issue. If there's a concrete problem with bee please open a new issue
