### ISSUE TITLE
Concurrent pushsync test fails

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#241]
Uploading chunks to Bee node in series works fine, but concurrent upload of chunks fails.
Also, after attempting to upload chunks concurrently and switching back to uploading in series, that one fails, too. It becomes impossibile to upload a chunk.

Logs do not help much:
`level=debug msg="bzz: write error: storage: invalid chunk, addr 13c8e84581163ea4ce505277f6ed4cc32b94f71a61e6d8e72eb3f3f147f647b7"`
`level=error msg="bzz: write error"`
`level=debug msg="bzz: write error: storage: invalid chunk, addr ad7556a3b378f23637e876f8b7d44d9d488ecd93fefa6e71c959e2348548e20d"`
`level=error msg="bzz: write error"`

But goroutine dump shows that there is probably a goroutine leak.
It looks like a deadlock in the [bmt](https://github.com/ethersphere/bmt/blob/master/legacy/bmt.go), lines 129 and 133.
[dump.txt](https://github.com/ethersphere/bee/files/4711289/dump.txt)

Following Beekeeper v0.2.3 command can be used for concurrent upload:
`beekeeper check pushsync --namespace svetomir --node-count 5 --insecure-tls -u 5 -p 5 --concurrent`

**Comment by janos** [comment]
It looks like that TreePool.c is waiting on read at line 133 and holding the lock for other goroutines.

What is confusing is that `storage: invalid chunk` error is returned by the validator on Put for the address that is hashed by bmt itself in the same handler api.uploadHandler.
