### ISSUE TITLE
EIP-1559 not supported

### ISSUE THREAD

**Issue by filoozom** [ethersphere/bee#2413]
#### Summary
Nodes don't create EIP-1559 transactions and can't verify other nodes whose transaction is an EIP-1559 one.

#### Steps to reproduce
1. Create a wallet with some gETH for a new node
2. Create an EIP-1559 transaction from said wallet
3. Try to launch a light node with said transaction as proof for the overlay address

#### Expected behavior
Nodes should create type 2 transactions and verification should just work with EIP-1559 transactions.

Related: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1559.md#backwards-compatibility

#### Actual behavior
The verification fails with the following debug log:

```
DEBU[2021-08-16T13:20:19Z] stream handler: handshake: handle 16Uiu2HAmJccsCKu98Wq4PD3peuEJSUxYC1qRXziF4cGv1qqRDqtG: overlay 17c696c1ec633efba090b5434958afd11a7ccb39f53db807fbfef9da0a69a8d7 verification failed: transaction type not supported: transaction not found
```

**Comment by ralph-pichler** [comment]
xdai does not support 1559 at this time so we cannot use them yet. latest master already accepts presented 1559-style transactions.

**Comment by filoozom** [comment]
I tried on Goerli while running the `:latest` tag yesterday, and `bee version` returned `1.1.1-db09d74-dirty` at that point, which is #2408's commit I believe?

**Comment by ralph-pichler** [comment]
hm, the odd thing is that the error is `transaction not found` so it actually seems to be the receipt lookup that fails. what ethereum backend are you using?

**Comment by filoozom** [comment]
> hm, the odd thing is that the error is `transaction not found` so it actually seems to be the receipt lookup that fails. what ethereum backend are you using?

I'm using an OpenEthereum node, latest version.

By the way, I think this might indirectly impact the testnet. Right now, Goerli is post-London and the block hash has changed: https://eips.ethereum.org/EIPS/eip-1559#block-hash-changing

This results in `bee` returning invalid hashes for blocks, and thus breaking overlay addresses.

Simple check:
```go
package main

import (
	"context"
	"fmt"	
	"math/big"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	ctx := context.Background()
	client, _ := ethclient.Dial("GOERLI_RPC_HERE")
	block, _ := client.BlockByNumber(ctx, big.NewInt(5220820))

	fmt.Printf("%x\n", block.Hash())
}
```
returns `76ed8d98818bb8a57cd4f1b880510b5564d2c1633ee01cb2d986d5c10af97337` in older `bees` and should return `c876a6267d76ebae87043a5c9ee0f93006bcd35646e0d7bd3824357053ddae28` with the latest master (I'm assuming). This block is used for the overlay address generation, and thus different versions of `bee` might not be able to handshake.

At least it displays the right hash when using the following `go.mod`:
```
module test/verify

go 1.16

require github.com/ethersphere/bee v1.1.0-rc2.0.20210816203416-5a6ddbdfd10a
```

**Comment by ralph-pichler** [comment]
indeed. probably because bee 1.0.0 uses a version of go-ethereum before they added london-support. which means we cannot maintain 1.0.0 compatibility on london-enabled networks.

**Comment by filoozom** [comment]
Looks like I might have been running an outdated version when this happened.

However, let's keep in mind that right now the testnet is in a quite unstable state, and this might also happen whenever xDai hardforks. Maybe some backwards compatibility would be nice during the transition phase?

**Comment by acud** [comment]
closing this as it seems this is no longer relevant :+1:
