### ISSUE TITLE
Inefficient, redundant, schema saving

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2419]
#### Summary
While investigating the slowness of node shutdown and discovering that it was mainly due to how long the kademlia takes to flush peer metrics, I noticed that the metrics were actually updating the statestore schema for each field of each peer that was being saved.  In this process, the current schema is first loaded from the database and unmarshalled into RAM.  The new field is then added to this which is then marshalled and written to the DB.

Given that 100s or 1,000s of keys are added in a single kademlia metrics flush, this results in a lot of unnecessary overhead showing up as copious CPU consumption during metrics flushing.

#### Steps to reproduce
Run a new (or even existing) node for a while to accumulated new peer metrics.  When you shut down the node, you will see a large CPU consumption for a long time (read: seconds, to minutes, to hours).  Inspecting the active goroutines and their stacks, you will see that the kademlia metrics flusher is active and bounding around in the shed doing these schema modifications.

Note: I didn't detect the issue using the stacks, but with iterative additions of logging down through the various layers.

#### Expected behavior
Given that locks are already in place to ensure a single schema modification is active at any point in time, why re-read the schema?  According to my testing logs, the schema size is not large enough to impact memory utilization, so simply cache the current version between updates.

#### Actual behavior
Bee wastes lots of CPU resources loading and unmarshalling the schema during kademlia peer metrics flushing.  By caching the current schema version, this time is easily reduced by 50%.

**Comment by mrekucci** [comment]
Fixed in #2452
