### ISSUE TITLE
New GET /stewardship/{reference} is redundant

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2426]
#### Summary
I tried the new GET /stewardship/{reference} API on 1.1.0-rc2 with verbosity 5 logging and find that it is redundantly retrieving chunks from the swarm.  Consider the following log snippet
```
time="2021-08-17T16:32:45-04:00" level=trace msg="retrieval: requesting chunk 9015edfe9a060078585b8be5a772a2012cc6f3d0a5398a1635600486dafa0232 from peer 91dd5b99ebac7e3ec5e3a420f6b010bc7b1f573480bb86e7b92e5fd9e0281282"
time="2021-08-17T16:32:45-04:00" level=trace msg="retrieval: requesting chunk 9015edfe9a060078585b8be5a772a2012cc6f3d0a5398a1635600486dafa0232 from peer 91dd5b99ebac7e3ec5e3a420f6b010bc7b1f573480bb86e7b92e5fd9e0281282"
time="2021-08-17T16:32:45-04:00" level=trace msg="retrieval: requesting chunk ebdcd51ffe05df73d8dc8555a81f4f2e9a4105bf7ad85b8f5368285e489ea21a from peer e03d1d763cac5a2c74b5fed77adf256e62d7ecf6849a60b25dc1b2e9583e3dd5"
time="2021-08-17T16:32:46-04:00" level=trace msg="retrieval: requesting chunk ebdcd51ffe05df73d8dc8555a81f4f2e9a4105bf7ad85b8f5368285e489ea21a from peer e03d1d763cac5a2c74b5fed77adf256e62d7ecf6849a60b25dc1b2e9583e3dd5"
time="2021-08-17T16:32:46-04:00" level=trace msg="retrieval: requesting chunk d27803264142a3ab1e005a74c96edf0162799e2d5b2b01cf57cfafd8b12596e2 from peer d167955bf135ca77e24627c64e95ee0bd7831239590cb06aefc140217f4a88a2"
time="2021-08-17T16:32:47-04:00" level=trace msg="retrieval: requesting chunk f56fbea515876ceeb192a425b3d78745f32205f43ad0b56bf5465dd2205d71c4 from peer f0390f6c51da964358f73368f09ca686350b118b4e2d65fe3372a450a95f5bd1"
time="2021-08-17T16:32:47-04:00" level=trace msg="retrieval: requesting chunk f56fbea515876ceeb192a425b3d78745f32205f43ad0b56bf5465dd2205d71c4 from peer f0390f6c51da964358f73368f09ca686350b118b4e2d65fe3372a450a95f5bd1"
time="2021-08-17T16:32:47-04:00" level=trace msg="retrieval: requesting chunk ff09675287e219f2bd4549c21d1429714f7c65e0928ec3ef1a646df46c3eb7ef from peer f0390f6c51da964358f73368f09ca686350b118b4e2d65fe3372a450a95f5bd1"
time="2021-08-17T16:32:48-04:00" level=trace msg="retrieval: requesting chunk 94ab9c7ed0f9a6e8069907459998103550634c97abd2804d2b9f5de9ffad7a5a from peer 91dd5b99ebac7e3ec5e3a420f6b010bc7b1f573480bb86e7b92e5fd9e0281282"
time="2021-08-17T16:32:48-04:00" level=trace msg="retrieval: requesting chunk 94ab9c7ed0f9a6e8069907459998103550634c97abd2804d2b9f5de9ffad7a5a from peer 91dd5b99ebac7e3ec5e3a420f6b010bc7b1f573480bb86e7b92e5fd9e0281282"
time="2021-08-17T16:32:48-04:00" level=trace msg="retrieval: requesting chunk 34a92135e2864049e53a9cc38e7b3da686f2094d5d5575d2a17e445d40899411 from peer 345e089c1caa86690b8bffdd63dd534ec600d6db56d9ac5ed02e77021f4bb641"
time="2021-08-17T16:32:49-04:00" level=trace msg="retrieval: requesting chunk 538d36ff1ee31d2c0be217989d5205c4fb872846bd12303feac79fde3da4ab20 from peer 50b40d00877c7e396fb8f18d7bb12fa369c8d5a4764cdb231ade73cc7325ebe9"
time="2021-08-17T16:32:49-04:00" level=trace msg="retrieval: requesting chunk 538d36ff1ee31d2c0be217989d5205c4fb872846bd12303feac79fde3da4ab20 from peer 50b40d00877c7e396fb8f18d7bb12fa369c8d5a4764cdb231ade73cc7325ebe9"
time="2021-08-17T16:32:50-04:00" level=trace msg="retrieval: requesting chunk c34d3b2b09f1b38cc0d5628fd6951bb2e135549421502bc9c2b5ca03a3e54493 from peer c65e3e78625120476fbe2797482b925d592e23356ffd9368cae429e766767dc8"
time="2021-08-17T16:32:50-04:00" level=trace msg="retrieval: requesting chunk d2f87d80301e695e2f5a3ed258ad6f867a256ac3f7fb1e8077fb1f44eb4ac759 from peer d167955bf135ca77e24627c64e95ee0bd7831239590cb06aefc140217f4a88a2"
time="2021-08-17T16:32:51-04:00" level=trace msg="retrieval: requesting chunk d2f87d80301e695e2f5a3ed258ad6f867a256ac3f7fb1e8077fb1f44eb4ac759 from peer d167955bf135ca77e24627c64e95ee0bd7831239590cb06aefc140217f4a88a2"
time="2021-08-17T16:32:52-04:00" level=trace msg="retrieval: requesting chunk 8857a5222d92f72aee48a3127c8b2cb1034226428fe0a7ab6fd31041ce922f93 from peer 808bd08bdb8c2854160be3d58bf37d8462085a7150212d69a62ddfa384e81a32"
time="2021-08-17T16:32:52-04:00" level=trace msg="retrieval: requesting chunk ebdcd51ffe05df73d8dc8555a81f4f2e9a4105bf7ad85b8f5368285e489ea21a from peer e03d1d763cac5a2c74b5fed77adf256e62d7ecf6849a60b25dc1b2e9583e3dd5"
time="2021-08-17T16:32:52-04:00" level=trace msg="retrieval: requesting chunk ebdcd51ffe05df73d8dc8555a81f4f2e9a4105bf7ad85b8f5368285e489ea21a from peer e03d1d763cac5a2c74b5fed77adf256e62d7ecf6849a60b25dc1b2e9583e3dd5"
time="2021-08-17T16:32:52-04:00" level=trace msg="retrieval: requesting chunk d27803264142a3ab1e005a74c96edf0162799e2d5b2b01cf57cfafd8b12596e2 from peer d167955bf135ca77e24627c64e95ee0bd7831239590cb06aefc140217f4a88a2"
```
You will notice there are a LOT of redundant retrievals of a single chunk from the SAME peer.  I could understand a possible retry of a missing chunk via a different peer, but to fetch the same chunk from the same peer is just a waste of SWAP bandwidth (and possible BZZ if it moved faster).

#### Steps to reproduce
curl http://localhost:1633/stewardship/a6ab79baf718f5ad76249e5b1cb1c3eee7d1c6d8e079d36566098493e148e361
is the collection that I was testing with on the xdai mainnet swarm.

#### Expected behavior
I would expect each chunk to be fetched only once per stewardship check of a given reference.

#### Actual behavior
As you can see from the log snippet above, it is redundantly fetching the same chunk from the same peer repeatedly.  And that's just a fraction of the log.  If necessary, I can provide the full log (which is still running) if you ask for 20's xdai5-L.out.

Actually, the full capture of retrieval logs from the /stewardship check is at:
https://gateway.ethswarm.org/access/74ac26c6002caf3bdd6e42139b4aad272ea54d436eb2abd0c25aee591b625ac8

**Comment by acud** [comment]
So... this is a naive implementation. Keeping track of chunks that belong to a certain root hash is very costly once the set grows and this can send the node to an OOM kill. We intended the API to behave this way because optimizing this is not very trivial and can have quite a complexity with our current architecture. We will improve on  this in the future, but I don't think this is a significant issue and certainly not on prio.

**Comment by ldeffenb** [comment]
Then I will continue by "collect-bee" implementation in TrueScript using mantaray-js and bee-js.

Any chance of getting a header flag on the stewardship to have it do just the single specified object and not the entire manifest on both GET and PUT?  Or do a stewardship/bytes with GET/PUT that only do what /bytes would do?

Right now if I detect a hole in the manifest at, for instance, the node that is 0/, if I do a stewardship on that reference, it ends up processing the entire manifest from that point on down, which is WAY more than is necessary, especially on the PUT.

**Comment by acud** [comment]
> Any chance of getting a header flag on the stewardship to have it do just the single specified object and not the entire manifest on both GET and PUT? Or do a stewardship/bytes with GET/PUT that only do what /bytes would do?

Not sure what you mean by "single specified object". The root hash which you give to traverse can be a variety of things and we need to go guesswork on traversals (both for GETs and PUTs). I agree that there is an inefficiency but this has been built with relatively small data sets in mind. For larger data sets we would need to be able to serialize a pointer to where exactly in the graph traversal we were and resume from that pointer both for PUTs and GETs (preventing the incurred cost of traversal or upload of the parts which do not need to be uploaded), however, having toyed with implementing this, it would require quite some changes on our abstractions to support such complex operations

**Comment by ldeffenb** [comment]
I'm doing some outside work with mantaray-js and bee-js and might be able to work around this request.   But if you don't mind keeping it open just in case I see an easy way in the go code to manage it.
