### ISSUE TITLE
Add a Darwin ARM64 Build Target

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee#2432]
# Task
Add a Darwin ARM64 build target.

## Acceptance criterea
Darwin ARM64 packages are available in the regular distribution cycle.

**Comment by mennoterlaak** [comment]
I can build and run it with go 1.17 when bumping `go-libp2p-quic-transport` to `v0.12.0`. This is on an intel mac though.

**Comment by acud** [comment]
@vandot we can add the target, we've upgraded to 1.16 and updating to 1.17 is already in progress

**Comment by vandot** [comment]
Resolved with #2740 2740
