### ISSUE TITLE
A is accidentally missed in the Bee package output

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2446]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary
A was accidentally in the Bee package output that is printed after install. 

#### Steps to reproduce
Install Bee using package, look for what is not there.

#### Expected behavior
What was not there may should have been there.

#### Actual behavior
It was not.

![Screenshot 2021-08-25 at 08 39 56](https://user-images.githubusercontent.com/130104/130748363-55ed0d36-1315-41c8-8d49-1a4c4f6b48bf.png)

**Comment by acud** [comment]
> A was accidentally in the Bee package output that is printed after install.

sentence missing the direct object?

**Comment by acud** [comment]
we should probably change the message, as it can be an ethereum backend but also an xdai backend

**Comment by ldeffenb** [comment]
> we should probably change the message, as it can be an ethereum backend but also an xdai backend

"Blockchain"

**Comment by significance** [comment]
i believe the mighty @vandot may already have

**Comment by acud** [comment]
so can we close?

**Comment by vandot** [comment]
@ldeffenb @significance no I didnt tihs is the [text](https://github.com/ethersphere/bee/blob/master/packaging/deb/postinst#L15)
It has infura in it

**Comment by acud** [comment]
seems like this is sorted. please reopen if needed
