### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#246]
# Story
As a user of BEE, I want to set the welcome message for my node, such that I can greet any node who connects to my

# Background
This feature will probably be used as part of the Swarm Alpha release; we'll put a welcome message in our bootnode, which contains instructions on how to register for the Swarm alpha release. Suggested to do this via the handshake protocol.

# Acceptance criterea
- When I connect to a new node, the welcome message of this node is printed to my terminal
- A default welcome message is defined for each node. A user can adjust this message to be any fixed string via our default config parameters. A design is proposed on how to do make a dynamic message such that the bootnode can send out personal invites.

**Comment by janos** [comment]
I would set to default that the message is empty, not to have default one.

What would be the acceptable max length?

I have no clear idea how to implement dynamic messages. We should see what parameters the dynamics would need. But for now, a static message should be good enough, I think.

**Comment by Eknir** [comment]
@paxthemax
