### ISSUE TITLE
bitvector error calling string function

### ISSUE THREAD

**Issue by AboutaBoy** [ethersphere/bee#2470]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

#### Summary
Error calling function String

#### Steps to reproduce
If I use bitvector.New and try to call String to get the message inside, I get a panic: runtime error: index out of range [1] with length 1

#### Expected behavior
Print out the true bit vector result

#### Actual behavior
panic: runtime error: index out of range [1] with length 1

#### The solution
 [error code](https://github.com/ethersphere/bee/blob/47397c8515a115d1ab639d7ad51cc169ce797827/pkg/bitvector/bitvector.go#L113)

```go
func (bv *BitVector) String() (s string) {
	for i := 0; i < len(bv.b)*8; i++ {
		if bv.Get(i) {
			s += "1"
		} else {
			s += "0"
		}
	}
	return s
}
```

**Comment by AboutaBoy** [comment]
The fundamental question is why the bitvector created with the New function is compared with len in all functions? Instead of len(b)

**Comment by mrekucci** [comment]
The `String` method no longer exists: #2601
