### ISSUE TITLE
Handshake stream resets

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#2477]
# Task
Investigate stream resets on handshakes. This is clearly visible on the bootnode behavior in production:
```
time="2021-09-07T10:44:40Z" level=error msg="stream handler: handshake: unable to handshake with peer id <peer>"
time="2021-09-07T10:44:40Z" level=debug msg="stream handler: handshake: handle <peer>: read ack message: stream reset"
```

**Comment by mrekucci** [comment]
Additional log messages and metrics for building bigger picture about what is going on: #2490
