### ISSUE TITLE
Ensure persistent connections between peers

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#2478]
# Task
Make other bootnodes immune to kicking-out behavior of current bootnode implementation.

## Problem
Currently, bootnodes are getting restarted from time to time. We are still investigating this, but in order to mitigate the problem, we need a way in which we can ensure the bootnodes are connected to other bootnodes/gateway nodes/storer nodes all the time. This is required so that the nodes connect to each other everytime on restart and hence get better information about the topology faster.

As the bootnodes don't dial out, we always prefer newer connections to older ones. This is a problem when one of these older connections is to the other bootnodes. So we need to protect certain nodes from this kicking-out behavior.

## Solution
The solution envisioned is to have a configurable list of nodes that would be used to dial out and protect certain peers. This is similar to what IPFS does with [peering](https://docs.ipfs.io/how-to/peering-with-content-providers/#content-provider-list)

Steps:
1. Configure the list of peers using option/config file
2. Dial to the list on start and mark the peers protected
3. Hook into kademlia logic to prevent kicking out of these protected peers
4. On restart, go to step 2

This can be useful going ahead to other node operators as well. Users who operate multiple nodes can ensure they are always connected to each other. Also, users can configure list of already-known and trusted nodes to access data etc faster.

**Comment by acud** [comment]
solved by #2512

**Comment by ldeffenb** [comment]
> solved by #2512

@acud I might have missed it, but I don't see anywhere in the changed files of #2512 where it implements step 2 to "Dial to the list on start"?

**Comment by acud** [comment]
@ldeffenb we eventually decided to go with a smaller subset and additional external tooling that ensures that the nodes get the connection initiation between them, since doing it by providing the actual underlays through cli flags is a bit more clunky and also error prone. Having the overlays only provides us with minimal functionality we need right now on production. Eventually this stuff should be possible to toggle manually through the debug api.
