### ISSUE TITLE
Current master (1d5c07c4) doesn't make with golang 1.15.2

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2515]
#### Summary
Did a git pull to get the current master (1d5c07c4), followed by make and got the following error:

```
ldeffenb@osm:~/master/bee$ make
go build -trimpath -ldflags "-s -w -X github.com/ethersphere/bee.commitHash=""1d5c07c4"" -X github.com/ethersphere/bee.commitTime=""1631792277""" ./...
go: downloading github.com/syndtr/goleveldb v1.0.1-0.20210819022825-2ae1ddf74ef7
go: downloading github.com/ethereum/go-ethereum v1.10.8
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/libp2p/go-libp2p v0.14.4
go: downloading golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d
go: downloading golang.org/x/sys v0.0.0-20210816183151-1e6c022a8912
go: downloading github.com/libp2p/go-tcp-transport v0.2.4
go: downloading github.com/golang/snappy v0.0.4
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
cmd/bee/cmd/start.go:11:2: package embed is not in GOROOT (/usr/local/go/src/embed)
Makefile:92: recipe for target 'build' failed
make: *** [build] Error 1
```
This is with `go version go1.15.2 linux/amd64`

#### Steps to reproduce
Pull the current master and try to build it with go 1.15.2

#### Expected behavior
Obviously expected it to build in the absence of any direct dependency checks.

#### Actual behavior
Didn't build.  See above

#### Recovery
Conveniently, I've been tracking the PRs and saw that the golang was updated to finally fix the ARM build, so I updated my golang version and tried the make again.  It builds with `go version go1.17.1 linux/amd64`, but it doesn't work.  I'll open a new Issue for that error.

It would probably be good if the makefile could verify that golang is a sufficient version and issue a more clear error message than "...package embed is not in GOROOT...".

**Comment by mrekucci** [comment]
Thanks for reporting this. It panics because we're using the [embed feature from Go 1.16](https://golang.org/doc/go1.16#library-embed). So the current minimum required version is 1.16. See: https://github.com/ethersphere/bee/commit/2c867beef210771d5ec18b3d67d916f52dbde00e

**Comment by ldeffenb** [comment]
Ok, so you're using a feature from golang 1.16.  How does that explain a panic when built with a *LATER* golang version?  Does embed lock you into a specific golang version?

And I see where your build tools updated the golang version, but if a specific version is required for the build artifact to work, then I should think that `make binary` would detect the mismatch and terminate the build rather than generating a non-working artifcat.

**Comment by mrekucci** [comment]
> ... How does that explain a panic when built with a LATER golang version (eg 1.17)?...

The issue was already reported here: #2516

> Does embed lock you into a specific golang version?

Yes, the currently required version is 1.16+ as we're using a feature introduced in this version that wasn't available in the previous one.

> And I see where your build tools updated the golang version, but if a specific version is required for the build artifact to work, then I should think that make binary would detect the mismatch and terminate the build rather than generating a non-working artifact.

Thanks for this suggestion, it will be taken into a consideration, though it is not a valid reason for having this issue open. The main point was the fact that the current master doesn't compile with the go1.15+ which was already explained.
