### ISSUE TITLE
Current master (1d5c07c4) panics when built with golang 1.17.1

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2516]
#### Summary
Cloned a fresh copy of the current master (1d5c07c4) and built it with `go version go1.17.1 linux/amd64` successfully.  But the resulting executable panics when simply asking for the version.

```
ldeffenb@osm:~$ mkdir master2
ldeffenb@osm:~$ cd master2
ldeffenb@osm:~/master2$ git clone https://github.com/ethersphere/bee.git
Cloning into 'bee'...
remote: Enumerating objects: 20253, done.
remote: Counting objects: 100% (1604/1604), done.
remote: Compressing objects: 100% (837/837), done.
remote: Total 20253 (delta 975), reused 1205 (delta 729), pack-reused 18649
Receiving objects: 100% (20253/20253), 6.34 MiB | 6.34 MiB/s, done.
Resolving deltas: 100% (13455/13455), done.
ldeffenb@osm:~/master2$ cd bee
ldeffenb@osm:~/master2/bee$ make binary
mkdir dist
go version
go version go1.17.1 linux/amd64
go build -trimpath -ldflags "-s -w -X github.com/ethersphere/bee.commitHash=""1d5c07c4"" -X github.com/ethersphere/bee.commitTime=""1631792277""" -o dist/bee ./cmd/bee
ldeffenb@osm:~/master2/bee$ dist/bee version
panic: qtls.ClientHelloInfo doesn't match

goroutine 1 [running]:
github.com/marten-seemann/qtls-go1-15.init.0()
        github.com/marten-seemann/qtls-go1-15@v0.1.1/unsafe.go:20 +0x132
```

#### Steps to reproduce
Clone a new copy, build it with golang 1.17.1 and try to run `dist/bee version`

#### Expected behavior
If it built, I expected it to run.

#### Actual behavior
Panics when simply asking for version.

**Comment by ldeffenb** [comment]
Note:  I rolled back my golang to `go version go1.16.1 linux/amd64` and it builds and runs successfully.  As I mentioned in #2515, it would be good if the makefile could validate the required golang version to avoid very confusing error messages.  Especially when 1.15 and 1.17 both fail in different ways, but 1.16 works!

**Comment by acud** [comment]
there's an open PR to upgrade to go 1.17. it doesn't work out of the box. it will be handled soon.
