### ISSUE TITLE
Lastest master (1d5c07c4) fails on /settlements

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2518]
#### Summary
I have a mainnet node that has actually issued true /settlements.  I upgraded this node to the latest master (1d5c07c4), but now I cannot query the /settlements API.

```
curl http://192.168.10.20:11650/settlements
{"message":"can not get settlements","code":500}
```

The --verbosity 5 logs have these messages when the /settlements API is queried:
```
time="2021-09-16T09:53:38-04:00" level=debug msg="debug api: sent settlements: encoding/hex: invalid byte: U+0078 'x'"
time="2021-09-16T09:53:38-04:00" level=error msg="debug api: can not get sent settlements"
time="2021-09-16T09:53:38-04:00" level=info msg="debug api access" duration=0.000447906 ip=192.168.10.20 method=GET proto=HTTP/1.1 size=50 status=500 uri=/settlements user-agent=curl/7.68.0
```

#### Steps to reproduce
Run the latest master on a node that has executed settlements.

#### Expected behavior
Settlements should be queriable.

#### Actual behavior
See description above.

Note: Worse is the fact that there are database migrations between 1.1.0 and the current master, so I cannot even go back!  Yes, I KNOW I should have saved state/localstore, but...

**Comment by ldeffenb** [comment]
Interesting that /timesettlements still works.?

**Comment by acud** [comment]
@ralph-pichler @mrekucci could it be related to the statestore migration?

**Comment by ldeffenb** [comment]
I patched around the problem with the following logging and code in swap.go.  I have not tracked down why `s.addressbook.BeneficiaryPeer(beneficiary)` is returning the encoding error.

```
func (s *Service) SettlementsSent() (map[string]*big.Int, error) {
        result := make(map[string]*big.Int)
        cheques, err := s.chequebook.LastCheques()
        if err != nil {
                s.logger.Debugf("SettlementsSent:LstCheques gave %v", err)
                return nil, err
        }

        for beneficiary, cheque := range cheques {
                peer, known, err := s.addressbook.BeneficiaryPeer(beneficiary)
                if err != nil {
                        s.logger.Debugf("SettlementsSent:BeneficiaryPeer(%s) gave %v", beneficiary, err)
                        result[beneficiary.String()] = cheque.CumulativePayout
                        continue
                        //return nil, err
                }
                if !known {
                        s.logger.Debugf("SettlementsSent:Beneficiary %s not known in addressbook", beneficiary)
                        result[beneficiary.String()] = cheque.CumulativePayout
                        continue
                }
                s.logger.Debugf("SettlementsSent:Payout to beneficiary %s peer %s", beneficiary, peer.String())
                result[peer.String()] = cheque.CumulativePayout
        }

        return result, nil
}

```
which outputs the following logs when /settlements is queried:
```
ime="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x6D8677a52b6c499e56bc90b0BfbAe3597306A2B7 not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x72bDaa8ecDa52B9B23de1c2B900038F91B43fC1e not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x8f5fe4065dF0bcCFFCb1E3AEb60d472405e93b50 not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0xd3535fe612E1F4D451594e27Ab7c1dabe9c7B14b not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x10346df6318b3593255d2e4Df2725f8180Fc7468 not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x261fEecDB11bABEa1fc7d2c06C74a178c1ddEe0e not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:BeneficiaryPeer(0x3509df3DcCb8beeca933bEd850634fD5206269d0) gave encoding/hex: invalid byte: U+0078 'x'"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x6E6C28f6A34625a58cc42CF94C3A8FEc6576629E not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0x75345311936A5Fc8f3ccdf5A9c41a6806b3Bc17a not known in addressbook"
time="2021-09-16T11:06:13-04:00" level=debug msg="SettlementsSent:Beneficiary 0xEEbe7Fdaf8230D557bD497B73f2c7912D6062f24 not known in addressbook"
```

And yes, I realize that I'm now getting the beneficiary address back in the peer field, but at least the query isn't failing.

And it appears that this code makes settlements issued to (and possibly received from) peers that are no longer in the address books simply disappear from the /settlements query.

**Comment by ralph-pichler** [comment]
I will look into this. Some migration that was supposed to run in the last release did not but new entries already used the new format. So when the migration runs now it is "updating" some entries that are already updated. at least that is my theory so far.

**Comment by ldeffenb** [comment]
@ralph-pichler If there is anything that I can dump out of my statestore to help diagnose this, I'd be glad to help.  At least, if you can provide the instructions and/or tools to do such a dump!

**Comment by ralph-pichler** [comment]
was this node first started with 1.0.0 or 1.1.0?

**Comment by ldeffenb** [comment]
> was this node first started with 1.0.0 or 1.1.0?

1.0.0

**Comment by acud** [comment]
@ralph-pichler this issue should be resolved with https://github.com/ethersphere/bee/pull/2537 right? can we close?

**Comment by ralph-pichler** [comment]
fixed in master. already broken nodes (which are only nodes that ran broken master at some point) can be fixed by starting with the `restore_swap_migration` branch once.
