### ISSUE TITLE
how do i update my node from v1.0.0 to v1.1.0

### ISSUE THREAD

**Issue by DaC1989** [ethersphere/bee#2540]

**Comment by szz1233** [comment]
你这种人要是只有废话可以说，那大可不必张嘴。笑死

**Comment by DaC1989** [comment]
> 你这种人要是只有废话可以说，那大可不必张嘴。笑死

死了吗？

**Comment by DaC1989** [comment]
死了吗？

szz1233 ***@***.***> 于2021年9月25日周六 下午2:54写道：

**Comment by DaC1989** [comment]
还没笑死吗

Liuwei Fire ***@***.***> 于2021年12月5日周日 21:37写道：

**Comment by fireliuwei** [comment]
> 你这种人要是只有废话可以说，那大可不必张嘴。笑死

还没死吗？

**Comment by cnm2024** [comment]
> 你这种人要是只有废话可以说，那大可不必张嘴。笑死

今年应该要死了吧

**Comment by szz1233** [comment]
我寻思今年还收益了 没什么问题啊0.0

**Comment by szz1233** [comment]
各位踏空了 突出一个急

**Comment by DaC1989** [comment]
> 各位踏空了 突出一个急



> 你这种人要是只有废话可以说，那大可不必张嘴。笑死

陌生的朋友，我觉得你骂的很对。那时我是作为研发人员，只是拿份工资，完全没必要一时冲动来这里暗损这个垃圾项目方。只是生气这个垃圾项目浪费了自己几天的时间。你的批评，时常让我在币圈感到警惕。正是这种警惕，帮助我积累了之前打工无法积累的资金。衷心的谢谢你。虽然我始终不认可任何帮助这个垃圾项目方说话的任何行为，但还是捍卫你说话的权力
