### ISSUE TITLE
POST /bzz - Very long directory name yields `store dir err: read tar stream: archive/tar: invalid tar header`

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#2542]
Related: https://github.com/ethersphere/swarm-cli/issues/250

It seems that when trying to upload a tar with a lengthy directory (`specification-for-fairdrive-and-everything-else-you-need-to-know-about-your-digital-safe-zone`), Bee fails with:

```
time="2021-09-27T10:00:31Z" level=debug msg="bzz upload dir: store dir err: read tar stream: archive/tar: invalid tar header"
time="2021-09-27T10:00:31Z" level=error msg="bzz upload dir: store dir"
```

and 

```
Internal Server Error: could not store directory
```

Uploading the **content** of the directory above succeeds, so it seems the problem is not with the content of it, but the directory itself.

**Comment by ldeffenb** [comment]
The answer may be in the TAR format itself.  It seems to depend on which actual TAR version is used within bee.

https://www.gnu.org/software/tar/manual/html_section/Formats.html

**Comment by agazso** [comment]
A simple fix for this could be to simply return 400 in this case instead of 500 with an error message that actually tells what is the problem (e.g. `invalid filename in tar archive` or something like that).
