### ISSUE TITLE
Be more resilient on blockchain error

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#2567]
# Task

Currently we shutdown on the first error coming from the postage event listener. We should retry to get the blockchain connection before shutting down. We also get false negatives on some of the overlay verifications as well (and this can cause connectivity issues).

## Acceptance criterea

Retry multiple times before shutting down.

**Comment by acud** [comment]
As you can see the shutdown sequence was indeed initiated but it seems we still might have a problem with the kademlia metrics flushing on shutdown. @jpritikin which version are you running? cc @mrekucci on this.

**Comment by jpritikin** [comment]
> was it because you ended the process?

No. I suspect bee is shutting down because a request to the blockchain endpoint timed out. I generally want bee to run 24/7 without the need for user intervention.

**Comment by jpritikin** [comment]
Nope, still haven't seen any problem. Bee is humming away just fine.

**Comment by acud** [comment]
done in #2626
