### ISSUE TITLE
Invalid formula error - MacOS 12.0

### ISSUE THREAD

**Issue by jasecoulls** [ethersphere/bee#2681]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context 
OS: MacOS 12.0.1 
Hardware: MacBook Pro (M1 Pro)
Brew version:  Homebrew 3.3.5
Homebrew/homebrew-core (git revision 47e6dc9e7fe; last commit 2021-11-23)

### Summary
1. Started following instructions at : https://docs.ethswarm.org/docs/installation/install/
2. It begins with "brew tap ethersphere/tap", so I ran that command.
3. It ultimately fails with "Error: Cannot tap ethersphere/tap: invalid syntax in tap!"

### Expected behavior
I was hoping to be able to move to the next instruction of actually installing swarm-clef. 

### Actual behavior
This is the actual output when I ran "brew tap ethersphere/tap"....

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
rizin
==> Updated Formulae
Updated 54 formulae.
Updating Homebrew...

==> Tapping ethersphere/tap
Cloning into '/opt/homebrew/Library/Taps/ethersphere/homebrew-tap'...
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 150 (delta 63), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (150/150), 20.84 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (63/63), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/ethersphere/homebrew-tap/swarm-bee.rb
formulae require at least a URL
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the ethersphere/tap tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/ethersphere/homebrew-tap/swarm-clef.rb:9

Error: Invalid formula: /opt/homebrew/Library/Taps/ethersphere/homebrew-tap/swarm-clef.rb
formulae require at least a URL
Error: Cannot tap ethersphere/tap: invalid syntax in tap!

### Steps to reproduce
1. Run "brew tap ethersphere/tap" in a terminal window. 

### Possible solution
None known.

**Comment by vandot** [comment]
Problem was because there was no arm64 candidate for `swarm-clef` fixed it now https://github.com/ethersphere/bee-clef/pull/58
