### ISSUE TITLE
incorrect funding logline on node startup

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2689]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context 
incorrect currency requested during startup

### Expected behavior
should read eg. '...sufficient xDAI (for Gas) and at least 1 BZZ bridged on the xDAI network...'

### Actual behavior
this was displayed

```
Nov 27 13:49:26 ip-172-31-18-31 bee[17534]: time="2021-11-27T13:49:26Z" level=warning msg="cannot continue until there is sufficient ETH (for Gas) and at least 1 BZZ available on 50078a907a97fda390f8a0733005731eefa7244f"
```

### Steps to reproduce

start a node on mainnet with no currency in wallet

**Comment by acud** [comment]
IMO the message should be either specific about both gbzz and xdai, or should be chain agnostic
