### ISSUE TITLE
v1.4.1-RC1 doesn't connect peers until after warmup.

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2702]
### Context 
Running v1.4.1-RC1

### Summary
When a node starts, it is supposed to connect to the peers to establish the depth before the pusher and puller kick off after the warmup period.  Starting with v1.4.1-RC1, peers are no longer connected until after the warmup.

### Expected behavior
Peers should begin being connected to establish a depth during the warmup period.

### Actual behavior
Kademlia doesn't try to connect to any peers until after the warmup period.

### Steps to reproduce
I added a bunch of logs to node.to to track this down and you can see the results at:
https://pastebee.com/?4a6d72f1e4a9c4f80cc92091e32cc0797c94c874ffd1f1efa9205d918eac8a18

### Possible solution
It appears that the invocation of pusherService.AddFeed from node.go is the problem.  That routine tries to write to a channel which is not being read until after the warmup period has cleared in the pusher.

https://github.com/ethersphere/bee/blob/9a1162ff3f44297ac69421dfd7e6ba04d8c992dc/pkg/node/node.go#L772
https://github.com/ethersphere/bee/blob/9a1162ff3f44297ac69421dfd7e6ba04d8c992dc/pkg/pusher/pusher.go#L312

Somehow the write to s.smugler in AddFeed needs to be deferred to allow node.go's startup to complete without waiting for the warmup period.

**Comment by acud** [comment]
thanks @ldeffenb, fix is already inbound!
