### ISSUE TITLE
File sizes in a manifest?

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2709]
#### Summary
It would be good to have an easy way for accessing the file sizes in a manifest.

#### Motivation
In the tooling projects (Dashboard, Gateway, CLI) there is a need to display the contents of the manifests with size information. For example before you download something you usually want to know how big the file is.

#### Implementation
Currently this is possible with going through the manifest references, fetch them on the [chunk endpoint](https://docs.ethswarm.org/api/#tag/Chunk/paths/~1chunks~1{reference}/get) and treat the first 8 bytes of that as a little endian encoded `uint64` for the file size.

This is a bit cumbersome and also it is somewhat wasteful because even though only the first 8 bytes usually it will download the whole chunk data which (is for files that are bigger than 4KB) can be 4KB.

I was thinking of some alternative ways of doing this and I wanted to write them down to start a discussion around this topic:

1. Allow HTTP HEAD requests on the `/bytes` endpoint

This would only return the headers, including the `content-length` that is the file size.

2. Have a separate endpoint for the size

One way to do this is to have an endpoint for returning the size of the data stored under a reference. An alternative could be to have a similar endpoint for manifests that returns a JSON object with the list of files accompanied by their respective file sizes.

3. Allow range queries on the `/chunk` endpoint.

For example `/chunk/<hash>?offset=<offset>&length=<length>` would be allowed. With that it would be possible to pass `offset=0` and `length=8` and it would only return the first 8 bytes.

**Comment by acud** [comment]
@agazso we can probably close this due to the fact that HEAD requests are now allowed on `bytes` endpoint
