### ISSUE TITLE
Connect to bootnode skipped when should not be

### ISSUE THREAD

**Issue by pradovic** [ethersphere/bee#271]
This problem is happening when there are peers in the addressbook but they all have wrong addresses, for example.
Currently, when the node is started, node will add all nodes from addressbook to topology, and if any `AddPeer` call pass without error, it will not try to connect to bootnodes. This seems OK, however, kademlia is connecting to bootnodes in async matter, and although the connect call might fail, the `AddPeer` will not return error. This result in bootnode not being connected if there were nodes in addressbook, but they all had wrong addresses, for example. What will happen in this case is that all `AddPeer` calls will be valid, thus bootnode will not be used, but connect call will fail and the node will just be running without trying to connect to it and get more known nodes.

**Comment by Eknir** [comment]
@pradovic , what is the status of this issue?

**Comment by pradovic** [comment]
@Eknir Still did not work on this, so it's for the backlog. I think we talked and considered it en endge-case, and we don't actually have a nice easy fix I think. @janos Can you confirm as well?

**Comment by janos** [comment]
@pradovic correct. This can remain in the backlog, for now.
