### ISSUE TITLE
/bytes pinning doesn't pin any chunks

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#2712]
### Context 
Source examination and experience with missing subsequent chunks from pinned /bytes uploads.

### Summary
I upload my OSM tiles with /bytes and assemble the returned references into a manifest using mantaray-js with pinning specified on every invocation.  I've noticed that many tiles larger than 4KB seem to be missing subsequent chunks after some time has gone by.  These chunks are even missing from the node through which the /bytes were originally uploaded and pinned.

### Expected behavior
Any /bytes upload of any length should always be retrievable from the original uploading node if they were initially pinned.

### Actual behavior
The uploading node fails to retrieve some /bytes pinned uploads after a long-ish period of time has elapsed.  I suspect it is due to the subsequent chunks being not actually pinned and therefore subject to the garbage collector when things fill up.  Reminder: this is an upload node through which 150+GB have been pushed over time.

### Steps to reproduce
Not sure, but I suspect if you set up a node with limited garbage-collected space and upload two or three very large and unique /bytes uploads to it with pinning, then by the time you are done, the first upload may not be retrievable from the local node.  But you'd also have to disconnect said pinning node from the swarm or monitor for it to be sending out retrieval requests to the swarm for content that SHOULD be locally pinned.

### Possible solution
If you look at how pinning is handled by the /bytes API, you see a single call to s.pinning.CreatePin with the root address of the /bytes upload and false for the traversal flag.  https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/bytes.go#L92

Looking at CreatePin, we see that if traversal is false, it simply stores a single key for the specified chunk in the rhStorage (statestore), seemingly ignoring all of the subsequent chunks it takes to make the entire /bytes upload.   https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/pinning/pinning.go#L91

However, if traversal is true (which it is not from pinned /bytes), then traverser.traverse is invoked with a callback function that updates pinStorage for every address received.  And the traverser iterates through all manifest nodes (if it is a manifest) as well as all chunks within each value node, including the originally specified reference at the end.
https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/pinning/pinning.go#L68
https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/traversal/traversal.go#L66
https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/traversal/traversal.go#L79

So on final reflect, it seems that /bytes with pinning specified doesn't actually do ANYTHING to the pinStorage (localstore) which is used to keep chunks out of the garbage collector, but simply puts the /bytes reference as a key into the rhStorage (statestore) which doesn't actually accomplish pinning at all for any of the chunks in the /bytes upload!

Now, if the /bytes reference was subsequently specified in an explicit POST to /pins/{reference}, then it WILL actually get all of the chunks pinned into pinStorage via CreatePin with traversal = true to request a traverser that enumerates all of the chunks for the specified reference.  This will work ONLY if you did NOT specify pinning on the original /bytes because if you did that, then the root reference will already be a key in rhStorage which will turn the explicit POST to /pins/{reference} into a NoOp.
https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/pin.go#L40
https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/pin.go#L28

So the bottom line is that /bytes doesn't actually pin anything into pinStorage when Swarm-Pin is set to true, but does add the reference as a key in statestore effectively preventing future explicit pinning requests.  Ug.

I guess I'll modify my /bytes uploader to NOT specify the Swarm-Pin and follow it up immediately with a POST /pins/{reference} to actually get my file data and manifest nodes to be actually pinned.

**Comment by ldeffenb** [comment]
It seems like CreatePin, at least when invoked from /bytes with a Swarm-Pin header, should invoke something like the processBytes which creates a joiner to iterate through all of the chunks involved in the specified reference.  This iteration should increment or store entries in pinStorage (localstore) that will actually prevent all of the /bytes-involved chunks from being garbage collected.

**Comment by ldeffenb** [comment]
But you definitely do NOT want to simply specify traverse of true to CreatePin in /bytes or entire sub-manifests will be repeatedly invoked as new manifests are stored via /bytes with a possible Swarm-Pin header!  /bytes should be manifest-agnostic, but should certainly pin all of the chunks for the reference it created if it is requested to do so.

**Comment by ldeffenb** [comment]
Is it even worse for the new direct-pushing /bytes uploads?  I just quickly skimmed that code and it appears that chunks are split and directly pushed into the swarm and don't even get stored in localstore, so they won't even be there for pinning by the time the /bytes are done splitting?  Or am I completely missing something in pushStamperPutter.Put? https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/api.go#L525

A direct-push /bytes upload not being able to honor the Swarm-Pin header should probably be opened in another Issue though...

**Comment by ldeffenb** [comment]
Now, to write a script to delete the 3249506 pins in my uploading node so that my next full upload will ACTUALLY pin the /bytes uploads with a follow-on POST /pins/{reference} and not short-circuit any tiles that haven't actually changed content.  Double ug.

**Comment by ldeffenb** [comment]
> Now, to write a script to delete the 3,249,506 pins in my uploading node so that my next full upload will ACTUALLY pin the /bytes uploads with a follow-on POST /pins/{reference} and not short-circuit any tiles that haven't actually changed content. Double ug.

Well, I can't even delete the pins!  DELETE /pins/{reference} automatically traverses the manifest if it is one, and always creates a joiner that tries to enumerate all of the involved chunks of the reference.  But because these pins didn't actually pin what they were supposed to, they cannot be deleted because the traverser fails.  Triple ug at this point!

**Comment by acud** [comment]
@ldeffenb thanks for opening the issue. I am not sure why you are under the assumption that using the `/bytes` endpoint does not pin any chunks. There's a bit of indirection, which makes this a bit less clear, but pinning does take place. If you look at `bytes.go`, specifically here:
```go
	// Add the tag to the context
	ctx := sctx.SetTag(r.Context(), tag)
	p := requestPipelineFn(putter, r) <--- makes sure that pinning takes place, this is also reused across other places in the api
	address, err := p(ctx, r.Body)
```
The entries stored in the statestore are pinned _roots_, and thus referred to as such, so that we do not need to track all of the subtrees of chunks. Uploading with the new deferred uploads indeed is not compatible with pinning at the moment, and should be documented. Uploading with the normal deferred uploads should pin as usual.

**Comment by ldeffenb** [comment]
@acud I haven't chased the whole way through requestPipelineFn to see what it does with the request (r), but a simple search of the source code only shows the obvious references to SwarmPinHeader which doesn't appear to be anywhere except in the actual api upload service functions.  And they call pinning.CreatePin() if this header is set to true.  Can you quickly point me to where an actual pin gets created in the requestPipeline chain?

From https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/bytes.go#L91

```
	if strings.ToLower(r.Header.Get(SwarmPinHeader)) == "true" {
		if err := s.pinning.CreatePin(ctx, address, false); err != nil {
			logger.Debugf("bytes upload: creation of pin for %q failed: %v", address, err)
			logger.Error("bytes upload: creation of pin failed")
			jsonhttp.InternalServerError(w, nil)
			return
		}
	}
```

If this is so explicit, why would other pinning actions be done in the pipeline?

**Comment by ldeffenb** [comment]
@acud  Never mind.  I found a promising bit of code at https://github.com/ethersphere/bee/blob/fc63f016b0feba260a131d05b3c1686be178e450/pkg/api/api.go#L240

But I'm still trying to explain why my uploading node with 100% pinning on the /bytes uploads still managed to lose large numbers of chunks, some of which it would retrieve from the swarm when asked, and some that were just plain gone.  I've added explicit logging code to CreatePin, but I do still need to add logging to the chunks being garbage collected or otherwise deleted from the localstore to attempt to find a smoking gun when any of my new chunks become non-retrievable from the uploading and pinning node.

**Comment by acud** [comment]
My bet would be that this might be somehow related to the storage incentives logic in the localstore. There's a lot going on there, and without a clear way to reproduce the problem it might very quickly evolve into a wild-goose chase.

**Comment by acud** [comment]
@ldeffenb just an idea about reproducing or at least homing in on the problem: could you try turning off the reserve eviction worker in `localstore/gc.go` and say whether the problem persists?

**Comment by ldeffenb** [comment]
So far, I only have the anecdotal evidence that entire files became non-retrievable from the uploading node that supposedly had them pinned.  I say supposedly because even though /pins/{reference} showed a pin, having looked at the code, that's not actually what the garbage checker honors.  And I haven't found a way yet to query the actual pin status (in the localstore) of the individual chunks required by the reference.

So I'm planning a two step approach.  I'm reloading an updated set of map tiles with added logging of the individual chunks being actually pinned.  Then I'll be monitoring their retrieval status directly from the uploading/pinned node, not via stewardship (wish there was a call that was local-only instead of the swarm-only of /stewardship).  Once I get a failure, I'll know that there is definitely a problem.  Hopefully before that I'll also have logging in the actual chunk deletion code to prove that it was deleted.

Step two will then be determining under what condition the confirmed-pinned chunks are able to be deleted which will then provide exactly how to fix this.  It will definitely take some time.

Oh, and once I put the deletion logging code in, I was going to shrink the cache-capacity: "1000000" to a much smaller number because this particular node has plenty to keep in the pins (like the entire OSM tile sets over time) and doesn't really need/want to keep a cache of "other" chunks for the swarm for this test.  In my theory, and your's it seems, it is the maintenance of this chunk cache that may be violating the pinning status of locally pinned chunks.

**Comment by acud** [comment]
> wish there was a call that was local-only instead of the swarm-only of /stewardship

you can change:
`pkg/steward/steward.go#CTOR`: `getter storage.Getter` -> `getter storage.Storer`
`pkg/steward/steward.go#L48` Add:
`		localTraverser: traversal.New(storer),`

Then just add another field in the IsRetrievable method to take a `local bool` and just switch over to the localTraverser from the API with a given header.

**Comment by ldeffenb** [comment]
Thank you SO much!  I had the thought of trying something like that but would have had to search around for how to make a local-only getter.  I think I can handle the rest of it and then use /stewardship with my new header to check for local-only or remote-only as it is now without the header.
