### ISSUE TITLE
`/health` reports `0.0.0` for api versions

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#2725]
Using Bee-factory images that uses Bee docker images I am getting:

```
$ curl http://localhost:1635/health
{"status":"ok","version":"1.4.1-238867f1","apiVersion":"0.0.0","debugApiVersion":"0.0.0"}
```

**Comment by ldeffenb** [comment]
I get the same on a direct download of the 1.4.1 release for Linux AMD64.
```
{
  "status": "ok",
  "version": "1.4.1-238867f1",
  "apiVersion": "0.0.0",
  "debugApiVersion": "0.0.0"
}
```

**Comment by mrekucci** [comment]
The versions are set in the [build process](https://github.com/ethersphere/bee/blob/master/pkg/api/version.go#L7) so I'm guessing that the binary you're running wasn't built by `make binary`.

**Comment by ldeffenb** [comment]
My Linux AMD64 version was directly downloaded from github's releases, so how it was built is up there somewhere.
