### ISSUE TITLE
Refer to xDai instead of ETH if in mainnet

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#2754]
### Summary
Currently printed text on logs refers always to ETH, even if mainnet where the coin is xDai instead. Update printed texts.

Example:
`time="2022-01-09T18:40:10Z" level=warning msg="cannot continue until there is sufficient ETH (for Gas) and at least 1 BZZ available on xxxxxxxxxxxx"`

### Expected behavior
Each net should call its main coin properly.

### Actual behavior
It's always cited ETH.

### Possible solution
A dictionary with `Net->CoinName` should be kept as a coin name source by text printers.

**Comment by acud** [comment]
thanks @tmm360. I believe that xDai is officially called `Gnosis chain` now, and I'm not sure what the native token will be, I guess GNO. Let's follow up on this once their transition is done, and we can sweep through the codebase and do the appropriate cleanups

**Comment by tmm360** [comment]
@acud Correct, it's Gnosis Chain, but main coin is still xDai. It is a bridge on stablecoin Dai, so no clue that is will go to change name. Anyway, the dictionary is easy to update at any moment the coin should change name in future, if it will.

**Comment by tmm360** [comment]
.

**Comment by tmm360** [comment]
I don't agree. To explicit quote the token name remove any ambiguity. Important when some one is using bee for the first time. It's a very very simple implementation.

**Comment by agazso** [comment]
> Instead of naming token variables by it's symbol names, `bee` client can use network agnostic term in order to be flexible.

There is clearly a usability issue here and the solution is not necessary more flexibility, but rather some added clarity. I think it makes sense to internally keep track of the context if it is about native token or swarm token, however when communicating with the user it would be better to resolve it to the actual token name.
