### ISSUE TITLE
Sanitize logging in API package

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#278]
# Task

A separate pass at all files in the api package to ensure that all logging is being performed in the method immediately called by the router.

## Acceptance criterea

Peer review

**Comment by Eknir** [comment]
@nolash , in your opinion: is this something that we need to have in our next release?

**Comment by nolash** [comment]
Don't know the current state of this. @janos may know. It was in direct relation to one of my PRs.

**Comment by janos** [comment]
This was addressed in PRs indirectly. Logging has been improved along the way.

**Comment by Eknir** [comment]
Closing, as per @janos comment
