### ISSUE TITLE
request: bee dev - realistic TTL values 

### ISSUE THREAD

**Issue by vojtechsimetka** [ethersphere/bee#2816]
#### Summary
In `bee dev` mode, I would like to see realistic TTL values for postage stamps. Right now it always returns `-1`. Instead TTL could just be a difference between `time bought` and `request time` + `amount` to `/stamps` endpoint. The time bought could be stored in `blockNumber`.

#### Motivation
In the current form `bee dev` makes code that works with stamps a bit challenging. E.g. in `gateway-proxy` we want to purchase new postage stamps when stamps become full or expire. I can imagine other applications (like `bee-dashboard` or apps uploading to your own node) wanting this functionality (to test code that checks if stamp is usable before uploading).

#### Implementation
`blockNum` should return timestamp when the stamp was bought (in seconds) and 
`batchTTL` should return either positive difference between `blockNum - currentTimestamp + amount` or `-1` (also in seconds) .

#### Drawbacks
Adds complexity to `dev` mode code.

**Comment by tmm360** [comment]
.

**Comment by agazso** [comment]
Would it make sense to assume block time to be one second and calculate the TTL based on that? @acud

**Comment by acud** [comment]
would it be ok if we just adjust the API to return _some_ answer which is `>0`? there's some hardcoded values there that probably make the ttl calculation break. it would make our life easier to just somehow make sure that some reasonable output is guaranteed, rather than having configurable values

**Comment by vojtechsimetka** [comment]
would work for me
