### ISSUE TITLE
One-to-many relationship between chunks and postage stamps

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#2850]
#### Summary
Right now, pullsync and pushsync presumes one-to-one relationship between content and supporting postage stamps,
however multiple uploaders can upload partly or fully matching content, which can result in inadvertent loss of data.

#### Motivation
Correctness

#### Implementation
To be designed

#### Drawbacks
-

**Comment by ldeffenb** [comment]
I believe this really needs to be addressed, particularly for content that may be shared between multiple sites.
