### ISSUE TITLE
Reuploading content without increasing bucket collision counters, used stamp collision refinement 

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#2851]
#### Summary
Using direct uploads and potentially other use-cases (stewardship?), the exact chunks already uploaded included in the bucket collision counter are not remembered, so if a batch is used for reuploading the same data, the collision count can potentially be incremented multiple times for the same chunk

#### Motivation
Correctness

#### Implementation
To be verified, redesigned

#### Drawbacks
Introduces some overhead

**Comment by ldeffenb** [comment]
Would this happen if the content was pinned or otherwise still present in the uploading node?
