### ISSUE TITLE
error when installing package without clef

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2858]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
--image ubuntu-18-04-x64 --size s-1vcpu-1gb

### Summary

error when installing package without clef

```
root@sig-bee-main-04:~# sudo dpkg -i bee_1.5.0_amd64.deb
Selecting previously unselected package bee.
(Reading database ... 60462 files and directories currently installed.)
Preparing to unpack bee_1.5.0_amd64.deb ...
Unpacking bee (1.5.0) ...
Setting up bee (1.5.0) ...
Error: dial unix /var/lib/bee-clef/clef.ipc: connect: no such file or directory
dpkg: error processing package bee (--install):
 installed bee package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 bee
 ```

### Steps to reproduce
try to install on new droplet

**Comment by nikipapadatou** [comment]
Closing this as not relevant anymore - clef has been removed from the package.
