### ISSUE TITLE
Node doesn't start, even though there is sufficient xDAI

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#2860]
commit: `0703c82c02cd21e19e0f8248bdec40977564acdb`
@agazso attempted to deploy a light client bee node, but was not able to deploy even though the Ethereum address of the node holds 0.01xDAI.

I suspect that this error is related to a wrong gas-estimation on the xDAI network.

You *should* be able to validate this by overriding the gas estimation via passing the `--swap-deployment-gas-price string` flag upon node startup. **However**, upon inspection of the code, it seems that this flag is not correctly used.  The flag is read at `InitCheckBookService, settlement/swap/chequebook/init.go` (ln 177), but in the function `checkBalance, settlement/swap/chequebook/init.go`, we estimate the gas price even though the user passed in the gas price (ln 51 and 56). This should be reconciled by validating if the gas price was already set and if this is the case, don't read the gas price anymore.

Another way to validate if the gas price is indeed wrongly estimated is by looking up the used gas price from the deployment transaction. Is this much more than the recommended gas price (see: https://www.xdaichain.com/for-developers/developer-resources/gas-price-oracle)? Is the gas price in line with the recommendations, but significantly less used than 0.01xDAI? If any of these is yes, then indeed the gas estimation is incorrect. I mean to remember that the gas price estimation on the xDAI network does not work the same as on the Ethereum main network, so the function `estimateGas` should then not be used if the user is connection to xDAI. Additionally, in line 56 from `checkBalance, settlement/swap/chequebook/init.go`, we multiply the gas price with `250000`, this was probably done once as a quick fix for a too-low gas price or to get around the very busy Goerli network (during Rise of Bee), but it is probably not anymore needed now (you should validate this).

**Comment by agazso** [comment]
Related fix: https://github.com/ethersphere/bee/pull/2861

**Comment by agazso** [comment]
Closing this, because the description of the issue describes two issues and the issue mentioned in the title is fixed by #2861.

Opened another issue for the incorrect calculation when overriding gas estimation here: #2991
