### ISSUE TITLE
feat: track postage batch sync level using api call

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2872]
#### Summary
allow Bee to start apis but wait to connect to the network
then implement endpoint to allow users to track the progress of postage batch sync without having to resort to excessively verbose logs
this endpoint should also indicate whether the batches are currently synced

#### Motivation
to track the postage batch sync using api endpoints and allow reporting of this information in bee-desktop / swarm-cli

**Comment by agazso** [comment]
The idea is that we can expose the tip of the syncing in the `/chainstate` endpoint and using that and the already exposed `block` property, the client application can show the progress.
