### ISSUE TITLE
cacophony of bugs

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2879]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context

osx lightnode

### Summary
apologies for suboptimal bug reporting

![Screenshot 2022-04-09 at 15 03 30](https://user-images.githubusercontent.com/130104/162577620-9ca84659-9539-4bfa-bdcf-0c1513e70812.png)
![Screenshot 2022-04-09 at 15 03 24](https://user-images.githubusercontent.com/130104/162577624-19f41d6f-ba15-448f-bfe7-b833555f70c3.png)

no idea what is happening but this doesn't seem right

funded the chequebook and no change...

restarted node...

![Screenshot 2022-04-09 at 15 05 22](https://user-images.githubusercontent.com/130104/162577681-03bdc047-3697-4251-b5a8-666f02316feb.png)

```
sig32 :: Code/swarm/bee-desktop 130 » swarm-cli status
Bee Status
------------------------------------------------------------------------------------------------------------------------
Bee API URL: http://localhost:1633
Bee Debug API URL: http://localhost:1635
------------------------------------------------------------------------------------------------------------------------
[OK] Bee API Connection
[OK] Bee Debug API Connection
[FAILED] Bee Version Compatibility
Bee Version: 1.5.1-38705d4e-dirty
Supported Version: 1.4.1 (1.4.1-238867f1)
------------------------------------------------------------------------------------------------------------------------
Gateway Mode: false
Bee Mode: light
========================================================================================================================
Topology
------------------------------------------------------------------------------------------------------------------------
Connected Peers: 104
Population: 2844
Depth: 9
````
seems connected but no use

![Screenshot 2022-04-09 at 15 06 56](https://user-images.githubusercontent.com/130104/162577737-f6c41513-a0b1-4caa-8dd6-4ca6bc7ae086.png)

chequebook has balance but still reporting out of balance

i guess chunks are not pushed but no way to find out

**Comment by acud** [comment]
without an understanding of which actions were made prior to the aforementioned supposed problems (which you are also unsure of), it is not very clear to me what is the expected actionable outcome of this ticket. for future tickets, please consult the issue template
