### ISSUE TITLE
Add API for receive already signed chunks by client

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#2905]
#### Summary
We need a way for upload to a node chunks that was already signed by the client with postage stamps.
This primarily permits to publish contents signed with the user's address instead of the node's one.

#### Motivation
This is useful in all cases where a node is used by more than one user. Currently every published content is signed by node, and so the node owner is the first responsible of uploaded contents, where instead the final user should be.

Moreover, this permits to discharge node from computing load of sign every chunk, distributing it to clients.

#### Implementation
New API and a chunk validity check have to be implemented.
Old APIs can be kept untouched, eventually node's chunk signature can be disabled by options.

#### Drawbacks
Don't see any.

**Comment by agazso** [comment]
This is a good idea and definitely something like this would be good to have as a feature. The difficulty of this is that if the postage stamps are distributed then it is no longer trivial to know how much data was uploaded with it.

Currently the stamp is managed by a single node therefore the node is trivially able to account for all data that was attached to it and not overcommit. If you detach the stamp from the node and possibly make it distributable between different parties then it would require some kind of extra protocol to be able to track the data in a distributed manner as well. This protocol is missing and although there were some thinking in this space but as far as I know there is no consensus on how to do this at the moment.

**Comment by nugaon** [comment]
Picking up this issue since it was the closest to the pre-signed chunk support.

The `POST /chunk` endpoint could receive a `Swarm-Postage-Stamp` header where postage stamp signature could be set as a hex encoded string. [@mfw78 already hacked all this](https://github.com/ethersphere/bee/compare/master...rndlabs:bee:hack/stamped-chunk-api) but we need to have it on `POST /soc` endpoint as well.

This feature is also required for Addressed Envelope feature #4713 .

**Comment by agazso** [comment]
Maybe allow only mutable postage stamps, because it is not a problem to overcommit them. Otherwise the node may be penalized if it uploads with an overcommited postage stamp.

**Comment by nugaon** [comment]
there is no punishment system in Bee for uploading two chunks with the same postage stamp, it will just store the one with higher timestamp.

**Comment by ldeffenb** [comment]
> it will just store the one with higher timestamp.
Well, there are issues with the stamp timestamps in the reserve, but hopefully they'll get resolved before externally-stamped (and possibly re-used bucket indices) gets reduced to actual code.

**Comment by istae** [comment]
> > it will just store the one with higher timestamp.
> 
> Well, there are issues with the stamp timestamps in the reserve, but hopefully they'll get resolved before externally-stamped (and possibly re-used bucket indices) gets reduced to actual code.

yep, the fix is in the pipeline.

**Comment by istae** [comment]
fantastic feature idea btw
