### ISSUE TITLE
Bee API stops to return data on GET requests without evident reason

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#2909]
### Context
Using Bee 1.5.1 with Docker.

### Summary
I've a node that at some point started to timeout get requests, even if content should be cached.

This is an extract of logs:
```
time="2022-04-27T15:59:58Z" level=info msg="api access" duration=0.013540011 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=96387 status=200 uri=/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.145, 10.0.0.74"
time="2022-04-27T16:00:08Z" level=info msg="api access" duration=1.003372393 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=93 status=200 uri="/feeds/F60Fbc6A72dde156f24A08C414197AE3CF5399E0/40daa16a08bb37fc91dcfb3402af8193e327e741209d6f86a8127cbd4b1befaa?type=sequence" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.35.201, 10.0.0.74"
time="2022-04-27T16:00:09Z" level=info msg="api access" duration=0.01309673 ip=10.0.8.11 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=96387 status=200 uri=/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.145, 10.0.0.73"
time="2022-04-27T16:00:22Z" level=info msg="api access" duration=2.008228539 ip=10.0.8.11 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=93 status=200 uri="/feeds/3270fF5B8a32e1E39b12311ea5a9Eab325425137/40daa16a08bb37fc91dcfb3402af8193e327e741209d6f86a8127cbd4b1befaa?type=sequence" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.98, 10.0.0.74"
time="2022-04-27T16:00:26Z" level=info msg="api access" duration=60.005563862 ip=10.0.8.11 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=23 status=200 uri=/bzz/5d2a835a77269dc7bb1fb6be7b12407326cf6dcde4bd14f41b92be9d82414421/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.142, 10.0.0.73"
time="2022-04-27T16:00:26Z" level=info msg="api access" duration=60.00241233 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=0 status=206 uri=/bzz/d88f68aa5b157ce6bda355d8bd54179df264a899c03bf5bdf0d4569f20a6933b/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.148, 10.0.0.74"
time="2022-04-27T16:00:41Z" level=error msg="bzz download: invalid path"
time="2022-04-27T16:00:41Z" level=info msg="api access" duration=60.003016437 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=60 status=404 uri=/bzz/7eb77f7d0c2d17d9e05036f154b4d26091ba3e7d0ccfe8ebda49cda2bb94cd9b/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.101, 10.0.0.74"
time="2022-04-27T16:00:47Z" level=info msg="api access" duration=60.003261465 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=0 status=206 uri=/bzz/cf492b4f50da74f9789d02ad32d741d8642b77e76194a925f8ee0dd1450d3990/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.95, 10.0.0.74"
time="2022-04-27T16:01:20Z" level=error msg="feed get: lookup error"
time="2022-04-27T16:01:20Z" level=info msg="api access" duration=60.005268886 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=64 status=404 uri="/feeds/73963b959078051daB5535029FCB7AAcfc87Cf9E/40daa16a08bb37fc91dcfb3402af8193e327e741209d6f86a8127cbd4b1befaa?type=sequence" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.134, 10.0.0.74"
time="2022-04-27T16:01:26Z" level=info msg="api access" duration=60.002606399 ip=10.0.8.11 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=23 status=200 uri=/bzz/5d2a835a77269dc7bb1fb6be7b12407326cf6dcde4bd14f41b92be9d82414421/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.142, 10.0.0.73"
time="2022-04-27T16:01:26Z" level=info msg="api access" duration=60.001224132 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=0 status=206 uri=/bzz/d88f68aa5b157ce6bda355d8bd54179df264a899c03bf5bdf0d4569f20a6933b/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.148, 10.0.0.73"
time="2022-04-27T16:01:26Z" level=info msg="api access" duration=60.001309699 ip=10.0.8.247 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=23 status=200 uri=/bzz/5d2a835a77269dc7bb1fb6be7b12407326cf6dcde4bd14f41b92be9d82414421/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.142, 10.0.0.74"
time="2022-04-27T16:01:26Z" level=info msg="api access" duration=59.996773946 ip=10.0.8.11 method=GET proto=HTTP/1.0 referrer="https://app.etherna.io/" size=0 status=206 uri=/bzz/d88f68aa5b157ce6bda355d8bd54179df264a899c03bf5bdf0d4569f20a6933b/ user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36" x-forwarded-for="185.159.157.9, 151.139.95.148, 10.0.0.73"
```
You can see that logs reports `duration` that started from low values, and without any evident reason pass to ~60 seconds, where the network components rise a timeout. It's not a network fault, because a simple bee restart solved the issue.

What is strange is that the status is anyway often a 2xx code, but data is not returned, and connection is closed with the timeout.

### Expected behavior
API should properly return data, specially with a success result code.

### Actual behavior
API stops to return data, even if it should be available, and connections are closed by the timeout exception that drops it.

### Steps to reproduce
Don't know, it's random.

### Possible solution
Don't know.

**Comment by tmm360** [comment]
It happened again now, and it happened again also a moment very after a restart. I'm going to enable debug logs

**Comment by tmm360** [comment]
With debug logging I see that my node keeps to print A LOT of this errors, continuously:

```
time="2022-05-03T00:35:51Z" level=debug msg="could not handle protocol retrieval/1.1.0: stream retrieval: peer 7072445eae4008aacdb875b55cf4a60595b38d7a5a9ea196dee9b29eeef4c87c: error: retrieve chunk: storage: not found"
time="2022-05-03T00:35:51Z" level=debug msg="could not handle protocol retrieval/1.1.0: stream retrieval: peer 58ba5f7080e68220c8a713753890020b263ad407b18f2e85bca1e5d899a8eb4f: error: retrieve chunk: storage: not found"
time="2022-05-03T00:35:51Z" level=debug msg="could not handle protocol retrieval/1.1.0: stream retrieval: peer 7b04a8151df9852b1272becd4717468b1d24b8855f2e73eb019f212e572ec5ee: error: retrieve chunk: storage: not found"
time="2022-05-03T00:35:51Z" level=debug msg="could not handle protocol retrieval/1.1.0: stream retrieval: peer 6fd64f8ccfa081f23d5c4c5d085d796bbdc3104f36a0845d344225318e710026: error: retrieve chunk: storage: not found"
time="2022-05-03T00:35:51Z" level=debug msg="could not handle protocol retrieval/1.1.0: stream retrieval: peer 72f5e2b4e2441383e88e9451d9c0ee4659010525f2300f396a66bae822266b35: error: retrieve chunk: storage: not found"
```

My current think is that for some reason chunks could be garbage collected from the node (content is not pinned), and when it tries to retrieve chunks from the net, it fails. Problem is that it is not able to recover from this state.

**Comment by mrekucci** [comment]
@tmm360 thanks for reporting this. We're currently working on something that might be maybe related to this #2843 (not sure yet). But despite that the number of inbound and outbound connections in Kadeblia is limited (among other things) by blocking peers that are [non-responsive](https://github.com/ethersphere/bee/blob/master/pkg/topology/kademlia/kademlia.go#L608) and vice versa. The node you run blocklist peers that are unresponsive for a certain amount of time (currently 5 min.) for a period of one hour, and your node is blocked by other nodes when it is unresponsive (which means that the ping ends with some error) for that mentioned time. You can check the peers that your node has put on the blocklist by accessing the `http://localhost:1635/blocklist` endpoint.

**Comment by tmm360** [comment]
@mrekucci At this point I don't think that this issue is related to external connections. The node is recovering:

![Immagine 2022-05-04 204321](https://user-images.githubusercontent.com/7620704/166804171-86ea4f05-ad67-44b6-948b-9f07c3566dac.png)
and also `/blocklist` endpoint looks near empty:
```
{"peers":[{"address":"7d0011f20aeadd788e9b55e6ba5bca57da59c631ad768781129c4edba4a9f16e","fullNode":false},{"address":"7db670e433ee2347755d1837e392f569ed89cddb312598fdf760cfb3fe8ede35","fullNode":false},{"address":"7dfb32ee8f24836baf592e716e1c3f5a31e7c456e126706c91f6b508df8ba06b","fullNode":false}]}
```
Anyway, it keeps to not reply.

I've tried a wget of a simple image from local network on nodes. Bee1 reply without issues:
```
root@f54f9b825bac:/app# wget bee1:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
--2022-05-04 18:39:58--  http://bee1:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
Resolving bee1 (bee1)... 10.0.8.133
Connecting to bee1 (bee1)|10.0.8.133|:1633... connected.
HTTP request sent, awaiting response... 200 OK
Length: 97463 (95K) [image/jpeg]
Saving to: 'index.html.1'

index.html.1                                    100%[====================================================================================================>]  95.18K  --.-KB/s    in 0.008s

2022-05-04 18:39:58 (11.2 MB/s) - 'index.html.1' saved [97463/97463]
```

where Bee0 instead hangs on replying. Bypassing external network infrastructure, that impose the timeout, the call never terminate:
```
root@f54f9b825bac:/app# wget bee0:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
--2022-05-04 18:40:13--  http://bee0:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
Resolving bee0 (bee0)... 10.0.8.19
Connecting to bee0 (bee0)|10.0.8.19|:1633... connected.
HTTP request sent, awaiting response...
```

I've tried to keep it open for 10 minutes, and this is the output log:
```
time="2022-05-04T18:50:51Z" level=info msg="api access" duration=637.60826538 ip=10.0.8.7 method=GET proto=HTTP/1.1 size=0 status=200 uri=/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/ user-agent="Wget/1.20.1 (linux-gnu)"
```

Relevant are `status=200` and `duration=637.60826538`. At this point something internally is blocking response, and is something that keeps to ripropose with a random time after restart of the same node.

**Comment by mrekucci** [comment]
> @mrekucci At this point I don't think that this issue is related to external connections. The node is recovering:
> 
> ![Immagine 2022-05-04 204321](https://user-images.githubusercontent.com/7620704/166804171-86ea4f05-ad67-44b6-948b-9f07c3566dac.png) and also `/blocklist` endpoint looks near empty:
> 
> ```
> {"peers":[{"address":"7d0011f20aeadd788e9b55e6ba5bca57da59c631ad768781129c4edba4a9f16e","fullNode":false},{"address":"7db670e433ee2347755d1837e392f569ed89cddb312598fdf760cfb3fe8ede35","fullNode":false},{"address":"7dfb32ee8f24836baf592e716e1c3f5a31e7c456e126706c91f6b508df8ba06b","fullNode":false}]}
> ```
> 
> Anyway, it keeps to not reply.
> 
> I've tried a wget of a simple image from local network on nodes. Bee1 reply without issues:
> 
> ```
> root@f54f9b825bac:/app# wget bee1:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
> --2022-05-04 18:39:58--  http://bee1:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
> Resolving bee1 (bee1)... 10.0.8.133
> Connecting to bee1 (bee1)|10.0.8.133|:1633... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 97463 (95K) [image/jpeg]
> Saving to: 'index.html.1'
> 
> index.html.1                                    100%[====================================================================================================>]  95.18K  --.-KB/s    in 0.008s
> 
> 2022-05-04 18:39:58 (11.2 MB/s) - 'index.html.1' saved [97463/97463]
> ```
> 
> where Bee0 instead hangs on replying. Bypassing external network infrastructure, that impose the timeout, the call never terminate:
> 
> ```
> root@f54f9b825bac:/app# wget bee0:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
> --2022-05-04 18:40:13--  http://bee0:1633/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/
> Resolving bee0 (bee0)... 10.0.8.19
> Connecting to bee0 (bee0)|10.0.8.19|:1633... connected.
> HTTP request sent, awaiting response...
> ```
> 
> I've tried to keep it open for 10 minutes, and this is the output log:
> 
> ```
> time="2022-05-04T18:50:51Z" level=info msg="api access" duration=637.60826538 ip=10.0.8.7 method=GET proto=HTTP/1.1 size=0 status=200 uri=/bzz/a1384bd71fcecf3a706d777075b56e3d6063dd876bba5617c985ba4eff3311e3/ user-agent="Wget/1.20.1 (linux-gnu)"
> ```
> 
> Relevant are `status=200` and `duration=637.60826538`. At this point something internally is blocking response, and is something that keeps to ripropose with a random time after restart of the same node.

So if it is hanging can you terminate the node with `ABRT` signal and paste the output here.

**Comment by tmm360** [comment]
@mrekucci tried `docker kill --signal=ABRT <containerName>` but there is empty output.

**Comment by tmm360** [comment]
@mrekucci attaching logs:
[killLogs.txt](https://github.com/ethersphere/bee/files/8627299/killLogs.txt)

**Comment by mrekucci** [comment]
> @mrekucci attaching logs: [killLogs.txt](https://github.com/ethersphere/bee/files/8627299/killLogs.txt)

Could you cherry-pick the following commit #2932 onto the version you're running and run it with this fix?

**Comment by acud** [comment]
@tmm360 if you can't find the tag on git with `git checkout v1.5.1` please use `git fetch --tags`

**Comment by tmm360** [comment]
@mrekucci @acud yes I will try to implement it today or tomorrow, and return with updates

**Comment by tmm360** [comment]
Ok, I compiled and deployed with fix, let's see if issue appear again.

**Comment by tmm360** [comment]
@mrekucci @acud after 48h it still works, that is like a record, so... I think that issue is solved 👍 Will ask to reopen in the case

**Comment by acud** [comment]
Sweet. The fix is already on master and will be in the upcoming release in a few days. Thanks for helping us debug this @tmm360!

**Comment by tmm360** [comment]
Great! Thanks to you!
