### ISSUE TITLE
bug: it does not provide postage stamp batch update info even in debug mode

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#2916]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
1.6 master tip

### Summary
no postage batch update info? 

### Expected behavior
postage batch info to print it

### Actual behavior
it did not print it
![Screenshot 2022-04-30 at 10 38 53](https://user-images.githubusercontent.com/130104/166098559-31ec01c4-5deb-4b50-af14-55d279eea082.png)

### Steps to reproduce
try to view the information in debug mode

### Possible solution
print the information when debug mode is selected

**Comment by acud** [comment]
the information about batches which are processed is indeed printed when logging in debug level. not sure what else should be done here. if there's a problem kindly reopen the ticket
