### ISSUE TITLE
Store block and transaction hashes to disk during "ultra" light mode boot

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#2918]
#### Summary
We want to store the provided hashes to disk so they would be available on subsequent runs in `ultra` light mode.

**Comment by agazso** [comment]
Is this issue still relevant? There are config variables to store the hashes if I understand correctly.

**Comment by notanatol** [comment]
> Is this issue still relevant? There are config variables to store the hashes if I understand correctly.

This is an UX improvement suggestion IIRC. If we start in chain-less mode and the values are not found in the config file we check if they are stored on the disk instead of failing to boot.

**Comment by agazso** [comment]
And how would the node find about these values?

**Comment by notanatol** [comment]
> And how would the node find about these values?

Initially the user provides them, but upon successful start-up the value can be stored to disk for future use, in case these values are later removed from the config file. 

This allows for more seamless transition between modes.
