### ISSUE TITLE
Debug flag with restricted endpoints is confusing

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#2940]
Historically the `debug` config variable turned the Debug API on or off. Now that the endpoints from the Debug API moved to the Bee API the behavior of this variable has changed:
- `true` means that the Debug API is turned on (as it was before). The endpoints of the Debug API are not available on the Bee API.
- `false` means that the Debug API is turned off. The endpoints of the Debug API are available as restricted endpoints on the Bee API.

I would argue that this is confusing, especially considering that the Debug API will be deprecated and removed in the future. It would be good to come up with a solution for this problem in a way that is also future-proof.
So far three alternatives were considered:
1. We acknowledge that this is the case and we don't do anything.
2. We use another flag to control this behavior or find a better way to do this
3. We deprecate the `debug` flag over time

Please note that the solutions has a certain overlap. I think it would be good to find a better way (alternative nr. 2) because it will be confusing for people who used the product before or during the deprecation period (which can be undeterministically long potentially).

**Comment by agazso** [comment]
Maybe I would not introduce a new configuration option but rather use the `restricted` configuration parameter (that is `false` by default) for this purpose.

Then the `debug` would simply just turn the API on `:1635` on and off (as it does currently) and the `restricted` parameter would turn on and off the restricted endpoints on `:1633`. The two options are orthogonal, therefore could be turned on and off independently and would be backwards compatible, and at some point we could choose to make the `restricted` `true` by default.

Wdyt? also @elad?

**Comment by acud** [comment]
so @agazso just to continue the discussion, the infra team needs to be able to bootstrap the API in the new merged scheme, but without authentication. So we need to support the following configuration permutations:
- Backward-compatible mode - endpoints split between two ports, auth possible on endpoints
- New mode (merged APIs)
- - No auth - all endpoints available
- - Yes auth - apply same rules like in the backwards compatible mode

**Comment by notanatol** [comment]
> so @agazso just to continue the discussion, the infra team needs to be able to bootstrap the API in the new merged scheme, but without authentication. So we need to support the following configuration permutations:
> 
>     * Backward-compatible mode - endpoints split between two ports, auth possible on endpoints
> 
>     * New mode (merged APIs)
> 
>     * * No auth - all endpoints available
> 
>     * * Yes auth - apply same rules like in the backwards compatible mode

so from your description it seems that these three modes are orthogonal:
```sh
debug-api-enable: bool
restricted: bool
single-port-api-layout: bool (potential new configuration param)
```
@agazso what are the concerns with introducing a new configuration parameter for this specific purpose? I agree it's ugly to have a "throw away" config flag, but it gets the job done...

**Comment by notanatol** [comment]
We will re-purpose the `restricted` flag so that when it is enabled it will attach the new (debug) set of http endpoints on the API port `:1633`.
This has a few repercussions:
- the user will no longer be able to restrict the endpoints currently residing on `:1633`, they will be always unrestricted.
- it will be impossible to have unrestricted access to subset of endpoints that will be moved from the `debug API`
- if the user enables both flags then we will see a duplicate set of endpoints on both ports.

there will be NO changes in the behavior of the `debug-api-enable` flag.
