### ISSUE TITLE
Expose "health" and "readiness" values on metrics

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#2956]
#### Summary
Expose current value of health and readiness on `/metrics` endpoint.

#### Motivation
This is useful for implement automatic alarms on node availability using tools based on metrics like Prometheus.

#### Implementation
Needs only to include these values on metrics.

#### Drawbacks
Nothing.

**Comment by notanatol** [comment]
This can be done as part of the current effort to [refactor the APIs](https://github.com/ethersphere/bee/pull/2846)
