### ISSUE TITLE
--bootnodes /dnsaddr/bootnode.ethswarm.org doesn't work

### ISSUE THREAD

**Issue by vporton** [ethersphere/bee#2993]
### Context
1.6.0-6ceadd35-dirty
Ubuntu

### Summary
The default value for `--bootnodes` does not work.

### Expected behavior
`--bootnodes /dnsaddr/bootnode.ethswarm.org` should initialize boot nodes.

### Actual behavior
`/dnsaddr/bootnode.ethswarm.org` does not work, because there are no `TXT` records at `_dnsaddr.bootnode.ethswarm.org`:

```
$ dig TXT _dnsaddr.bootnode.ethswarm.org

; <<>> DiG 9.18.1-1ubuntu1.1-Ubuntu <<>> TXT _dnsaddr.bootnode.ethswarm.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 51535
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_dnsaddr.bootnode.ethswarm.org.	IN	TXT

;; AUTHORITY SECTION:
ethswarm.org.		365	IN	SOA	ns-889.awsdns-47.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 19 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon May 30 17:46:30 IDT 2022
;; MSG SIZE  rcvd: 143
```

### Possible solution
Either:
- Make `_dnsaddr.bootnode.ethswarm.org` with suitable `TXT` record
- Install another boot node, change the default option value, and rewrite help.

**Comment by agazso** [comment]
> Then
> 
> ```
> handshake: incompatible network ID
> ```
> 
> It still does not work for Gnosis Network (`network-id: "100"`), the default network for which the documentation should speak about.

The `network-id` specifies the swarm network identifier and not the blockchain identifier. If you want your node to be connected to the swarm mainnet then you are supposed to use the value `1` as `network-id` (and which is the default).

As for connecting to the blockchain, you are supposed to set the `swap-endpoint` to an Ethereum RPC provider. Therefore here you need to set an RPC endpoint that is connected to the Gnosis Network.
