### ISSUE TITLE
Bee processes `Range:` HTTP header wrongly.

### ISSUE THREAD

**Issue by vporton** [ethersphere/bee#2994]
### Context
Bee 1.6.1-5d6ad4b1 / Ubuntu

### Summary
Bee wrongly processes `Range:` HTTP header.

### Expected behavior
Symbols of indexes interval 1-3 (starting from zero) should be printed.

### Actual behavior
Symbols of indexes interval 2-3 (starting from zero) are printed.

### Steps to reproduce
```bash
$ cat ~/t/x.txt ;echo
abcdefg
$ curl --data-binary @$HOME/t/x.txt  -H "Swarm-Postage-Batch-Id: XXX" "http://localhost:1633/bzz"
$ curl --http1.1 -H 'range: bytes=1-3' http://localhost:1633/bzz/31714c5dacfac786f14911c2bbc947e4216fcd7b061e34b458b01182a4c70222/ ;echo
cd
```

### Notes
It is apparently not a bug of `net/http` or `langos` modules.

**Comment by agazso** [comment]
I am closing this, because there was an experiment running the [static.wiki](http://static.wiki) on Swarm and it showed that the range queries are working correctly, assuming there is `HEAD` and `OPTIONS` method are supported on the `/bytes` endpoint.
