### ISSUE TITLE
It seems that getting current price of storage in BZZ is missing in the API

### ISSUE THREAD

**Issue by vporton** [ethersphere/bee#3000]
### Summary
It seems that getting current price of storage in BZZ is missing in the API.

### Expected behavior
https://docs.ethswarm.org/api/ should contain an endpoint to obtain current storage price.

The documentation should explain whether it is per-byte-second, per-chunk-second, or whatever.

**Comment by vporton** [comment]
It is in undocumented `/chainstate`. I am closing this bug and opening a bug in `bee-docs`.

**Comment by ldeffenb** [comment]
> It is in undocumented `/chainstate`. I am closing this bug and opening a bug in `bee-docs`.

But apparently this issue is still open?  @vporton If the bee-docs issue has been opened, please close this one.

**Comment by vporton** [comment]
It should be in main API rather than in Debug API.

**Comment by swarmHaseeb** [comment]
@agazso this issue has been closed with https://app.zenhub.com/workspace/o/ethersphere/bee/issues/3112
