### ISSUE TITLE
Shutdown hangs on blockchain backend failure

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#3015]
logs here:
https://pastebin.com/LTa4D27R

shutdown happened apparently due to too many calls to blockchain backend while uploading a huge data set. the goroutine dump is at the bottom

**Comment by aloknerurkar** [comment]
@notanatol Does your shutdown change fixes this?

**Comment by notanatol** [comment]
> @notanatol Does your shutdown change fixes this?

it depends, my fixes were for the shutdown process hanging and never exiting.

this issue appears to be that a certain situation causes the shutdown, is this right @acud ?
