### ISSUE TITLE
Expose geospatial data about other bees in your swarm.

### ISSUE THREAD

**Issue by chrishobcroft** [ethersphere/bee#3026]
#### Summary

Expose information about the geographical location of other bees in the swarm.

This would enable `bee-desktop` to provide users with views such as this:

![image](https://user-images.githubusercontent.com/2212651/174057341-30130a31-e8e7-4940-aed8-c674a3f8ed0d.png)

#### Motivation

Users of IPFS and IPFS-Desktop (like me), are regularly delighted with the cartographical representation of peers in the user's network.

As a user of bee-desktop, I would also like to feel this delight.

#### Implementation

I am not personally willing to implement this feature, as I simply don't have the capability right now.

But if it ended up being something simple enough to expose on an interface, for `bee-desktop` to retrieve data from, then it ought to be relatively trivial to then e.g. plot those on an OpenStreetMap, to see where all the other bees are, and show their ENS names etc.

#### Drawbacks

I guess there is always the security risk of showing people's precise locations.

**Comment by agazso** [comment]
The good news is that there is a map in the current design. That is not yet implemented in the current version. The idea is to use the IP addresses of the peers and use a Geo IP database to map them to city level, therefore providing reasonable privacy. 

Also check out https://swarmscan.resenje.org in the meanwhile.

<img width="1054" alt="Screenshot 2022-06-16 at 13 45 50" src="https://user-images.githubusercontent.com/230163/174063072-b32f8266-6679-43b5-8e8c-ee9c72dde747.png">

**Comment by chrishobcroft** [comment]
Why not use little bee icons to represent peers.

It would be cute.

**Comment by istae** [comment]
see https://swarmscan.io/
