### ISSUE TITLE
`1.6.2-rc1` debug endpoint miss `/tags` endpoint

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#3029]
With the merge of endpoints one endpoint got lost the: [`/tags/{uid}`](https://docs.ethswarm.org/debug-api/#tag/Tag).

**Comment by mrekucci** [comment]
Thanks for the issue. To my knowledge, there never was a `/tag` endpoint. I also checked this in git history:
```
git log --follow -p -- pkg/api/router.go
git log --follow -p -- openapi/Swarm.yaml
git log --follow -p -- openapi/SwarmDebug.yaml
```
There are `/tags` and `tags/{uid}` endpoints in the Swarm.yaml. However, the mistake is probably that in both files we have defined `/tags/{uid}:
https://github.com/ethersphere/bee/blob/master/openapi/Swarm.yaml#L424
https://github.com/ethersphere/bee/blob/master/openapi/SwarmDebug.yaml#L661

@anatollupacescu ⬆️

**Comment by AuHau** [comment]
There was and is `/tag` endpoint in the current version ;-) https://github.com/ethersphere/bee/blob/v1.6.1/pkg/debugapi/tag.go

**Comment by AuHau** [comment]
https://github.com/ethersphere/bee/blob/v1.6.1/pkg/debugapi/router.go#L214

**Comment by AuHau** [comment]
Sorry, typo on my end. It was meant to be `/tags` (plural) and not `/tag`

**Comment by mrekucci** [comment]
> https://github.com/ethersphere/bee/blob/v1.6.1/pkg/debugapi/router.go#L214



> Sorry, typo on my end. It was meant to be `/tags` (plural) and not `/tag`

Ah, ok, that changes everything @notanatol

**Comment by notanatol** [comment]
I can't reproduce it, need help @AuHau
```
anatol:bee/ (master*) $ git rev-parse HEAD                                          [19:26:20]
46c2b59bb6e65d2ebf0bcaec07a520bde37239fa
anatol:bee/ (master*) $ curl --request GET --url http://localhost:1633/tags | json_pp
{
   "tags" : [
      {
         "processed" : 0,
         "startedAt" : "2022-04-12T19:56:26+03:00",
         "synced" : 0,
         "total" : 0,
         "uid" : 1197711019
      },
      {
         ...
       }
}
anatol:bee/ (master*) $ curl --request GET --url http://localhost:1633/tags/1197711019 | json_pp
{
   "processed" : 0,
   "startedAt" : "2022-04-12T19:56:26+03:00",
   "synced" : 0,
   "total" : 0,
   "uid" : 1197711019
}
anatol:bee/ (master*) $

**Comment by notanatol** [comment]
sorry I missed the `debug` part, just created a PR to add it back.
