### ISSUE TITLE
Unexpected duplicate handshake

### ISSUE THREAD

**Issue by pradovic** [ethersphere/bee#304]
Sometimes debug logs look a bit bad when lots of nodes are trying to connect to each other, and it seems that there can be a couple of unexpected duplicate handshake-s, which is bad. We can not reproduce it now but it should be investigated regardless. The example of logs:
```
time="2020-06-12T12:16:26Z" level=debug msg="kademlia dialing to peer 64bc98e62f825c652084807f786e0a6f5d8844f1f87fe93c19cf1b9c72232957"
time="2020-06-12T12:16:26Z" level=debug msg="handshake: handle 16Uiu2HAmRomfcrxKwXQ4WyAyKckoVwSun9urEXiz1yryi46NVngm: duplicate handshake"
time="2020-06-12T12:16:26Z" level=error msg="unable to handshake with peer 16Uiu2HAmRomfcrxKwXQ4WyAyKckoVwSun9urEXiz1yryi46NVngm"
time="2020-06-12T12:16:26Z" level=debug msg="handshake: handle 16Uiu2HAmRomfcrxKwXQ4WyAyKckoVwSun9urEXiz1yryi46NVngm: read ack message: stream reset"
time="2020-06-12T12:16:26Z" level=error msg="unable to handshake with peer 16Uiu2HAmRomfcrxKwXQ4WyAyKckoVwSun9urEXiz1yryi46NVngm"
time="2020-06-12T12:16:26Z" level=debug msg="error connecting to peer 64bc98e62f825c652084807f786e0a6f5d8844f1f87fe93c19cf1b9c72232957: handshake: write ack message: stream reset"
time="2020-06-12T12:16:26Z" level=debug msg="error connecting to peer from kademlia 64bc98e62f825c652084807f786e0a6f5d8844f1f87fe93c19cf1b9c72232957 {Underlay:/ip4/10.42.0.24/tcp/7070/p2p/16Uiu2HAmRomfcrxKwXQ4WyAyKckoVwSun9urEXiz1yryi46NVngm Overlay:64bc98e62f825c652084807f786e0a6f5d8844f1f87fe93c19cf1b9c72232957 Signature:[31 216 84 131 247 240 229 236 31 232 148 144 169 168 232 167 215 76 32 101 211 226 93 99 14 225 6 210 38 94 192 40 150 126 43 223 207 120 201 95 106 55
29 169 242 152 213 65 0 137 179 80 197 31 158 106 128 125 108 197 53 150 222 218 97]}: handshake: write ack message: stream reset"
```

**Comment by pradovic** [comment]
@vandot Did you manage to reproduce this? I did not? If not, maybe we could close the issue and open again if we stumble upon it?

**Comment by vandot** [comment]
I can always reproduce it using [bee-local](https://github.com/ethersphere/bee-local)
`./beeinfra.sh install --dns-disco --local --test -r 3 --bootnode /dnsaddr/localhost`
In the end all nodes are interconnected but there are some duplicate handshake errors along the way.

**Comment by pradovic** [comment]
Oh ok, I understood you cannot reproduce it. Ok, will work on it then after we are finished with todays deubugging :) Could you copy paste the logs that you reproduce here? or attach them?

**Comment by vandot** [comment]
[bee-0.log](https://github.com/ethersphere/bee/files/4793709/bee-0.log)
[bee-1.log](https://github.com/ethersphere/bee/files/4793710/bee-1.log)
[bee-2.log](https://github.com/ethersphere/bee/files/4793712/bee-2.log)
here you can find duplicate handshake issue. latest bee master `./beeinfra.sh install --dns-disco --local --test -r 3 --bootnode /dnsaddr/localhost`

**Comment by Eknir** [comment]
Hi guys, what is the status of this issue? Will it be fixed before the release?

**Comment by pradovic** [comment]
Hey @Eknir, I still did not have a change to work on it. I put it as low priority compared to the bug we were solving this week, as it does not look like corrupted state. I will tackle it later today or Monday probably. Is that ok?

**Comment by Eknir** [comment]
@pradovic , sure! Please close this issue when done

**Comment by pradovic** [comment]
Could not reproduce this since then, so I will close this one. We did not notice problems with this in production  and staging evn since.
