### ISSUE TITLE
Debug Tag endpoint is not what it was before

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#3043]
#3030 added back tag handler, but it is not the one that was there before the change, see bellow:

```
    - ObjectContaining {
    -   "address": Any<String>,
    -   "seen": Any<Number>,
    -   "sent": Any<Number>,
    -   "split": Any<Number>,
    -   "startedAt": Any<String>,
    -   "stored": Any<Number>,
    -   "synced": Any<Number>,
    -   "total": Any<Number>,
    -   "uid": Any<Number>,
    + Object {
    +   "processed": 0,
    +   "startedAt": "2022-06-20T10:55:04.51559552Z",
    +   "synced": 0,
    +   "total": 0,
    +   "uid": 99520315,
      }
```

@notanatol

**Comment by ldeffenb** [comment]
IMNSHO, both versions should still be available.  The simplified is easier to see at a glance what is going on, while the original Debug API was invaluable for digging into the details of deferred uploads, especially revisions of large datasets which would show the difference between "seen" and "sent" which is completely hidden in the main API response.
