### ISSUE TITLE
Reserve Commitment Sampler

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#3069]
This component is intended to be triggered by the storage incentive agent with an input of the current redistribution anchor.

Upon being triggered, for each chunk that is PO(chunk, overlay) >= storage depth, a transformed hash is computed using the redistribution anchor and the chunk content as arguments. 
From the transformed addresses the alphabetically ordered first 128 hashes are kept as the sample.
After the iteration is done the component returns the regular swarm hash of the file that contains the first 128 transformed hashes. 

The transformed hash can be defined as a keyed hash function, taking the redistribution anchor as the key, or, alternatively, 
as a random deterministic data segment XOR-d with the redistribution anchor, where the selected segment is calculated as redistribution anchor (mod chunk segments length).

**Comment by agazso** [comment]
Specs: https://hackmd.io/@NivJ0VAwTB2QRu3weL9S2g/BJR1t_Ulj/https%3A%2F%2Fhackmd.io%2Fc%2FBJR1t_Ulj%2Fedit%3Fedit
