### ISSUE TITLE
Deletion of peer in addressbook

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#307]
When I start up my Bee node and somehow populate the addressbook with a peer with whom I can't make a connection (I am connecting to an external bootnode with two nodes on my machine), both nodes that I control will always show an `ERROR connecting to peer`. 

I believe it would be sensible to delete the peers with whom no connection can be made from the addressbook, such that we won't clutter the ERROR log and spend resources on trying to connect to peers from whom we know we can't connect. @janos , can you provide more details here if you think I don't describe it well?

**Comment by pradovic** [comment]
@Eknir, @janos Currently, there is a bit of a specific logic for topology driver on how it handles failed connect calls. For example, kademlia is not using connection breaker at all, and it keeps track of it's connected peers and it's peers waiting for a next retry if the failed connect is attempted. There is a todo comment there about forgetting the peers that failed connections. On the other hand, the addressbook should be populated for it to work.
Also, we need to think a bit about on when do we know that peer should be considered non connectable. For example, it might be down at the moment, but could be up and running after some time. I think we could benefit from some component unifying connection logic that would also encapsulate connection breaker as well so it would be used across the system.
Did I maybe miss the point of the issue, do you guys have any additional information about the scope or some concrete situation?

**Comment by janos** [comment]
@pradovic the issue is to remove the peer if it can be considered as non connectable. This can be done after some number of failed connection attempts, maybe with backoff right away. This issue is not a specification, it specifies the general idea. It looks to me that you already have ideas how to implement the solution, feel free to try them out and make pr.

**Comment by pradovic** [comment]
@janos Sounds good, thanks! What I wanted to say is that it would probably also include some refactor of connecting logic, and we already have one PR on hold about that. Should we go for this before alpha release or do it after? I don't mind working on it right away, just asking about when should we aim to merge it to master, and what the scope should/would be. If I should go for a quick fix or a better solution.

**Comment by janos** [comment]
I think that we should have aim to have this for alpha as failed connections are logged periodically which should be avoided. Given that, it would be good not to spend time on refactoring, rather on implementing the functionality with the current concepts. Of course, new service is completely fine.

**Comment by Eknir** [comment]
@pradovic , is https://github.com/ethersphere/bee/pull/309 solving this?

**Comment by pradovic** [comment]
@Eknir Sorry, did not see your meesage 🙈 Yup, it should solve it and it was linked to this PR. Could you verify please as well :)
