### ISSUE TITLE
Storage Incentive Agent

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#3070]
This component implements participating in the redistribution process.

The component only listens to on-chain redistribution round related information, if the following conditions are both true:
- If the node has staking enabled and currently owns stake registered with the overlay address  as part of #3071 
- If the storage depth is signaled as stable, meaning we are not in an intensive pull-syncing / adaptation period at the moment 

The component listens to on-chain data for RandomAura as source of Redistribution anchors (defined as either every odd or every even RandomAura round)

When PO(redistribution anchor, overlay) >= storage depth, 
- it triggers the reserve commitment sampler, waits for reserve commitment 
- submits a transaction to use the commit function of the redistribution contract to commence application with the hash of the reserve commitment hash, the depth, and some secret nonce
- after commit period is over submits a transaction to use the reveal function of the redistribution contract to announce actual reserve commitment hash and depth by revealing all three components of commit
- after reveal period is over uses the claim accessor of the redistribution contract to determine winning, 
- if redistribution contract shows winning outcome for the node, the claim function is called by a subsequent transaction

Expected smart contract functions:

**Commit(bytes32 obfuscatedHash, bytes32 transaction)**
"transaction" needed for overlay verification, to see it exists in stake registry which matches the overlay of the committing ethereum address

**Reveal(nonce bytes32, depth uint8, hash bytes32)**

**Claim()**

**Comment by agazso** [comment]
Would be nice to add links to the smart contracts itself once the code is available, at least on the interface level.
