### ISSUE TITLE
Staking Agent

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#3071]
This component's aim is to provide a convenient user experience for staking as a participant in the storage incentives redistribution process.

The most simple form would take some user defined value from an API providing amount to stake, which is then consequentially deposited in the staking contract along with the node's overlay using the 'register'-like method of the contract.

expected smart contract interface for interactions:
**Deposit(bytes32 overlay, uint256 value)**

**Comment by ct-ctrl** [comment]
additional specs and notes: > https://hackmd.io/@NivJ0VAwTB2QRu3weL9S2g/Bk5f2Zk-i

**Comment by agazso** [comment]
Would be nice to add links to the smart contracts itself once the code is available, at least on the interface level.
