### ISSUE TITLE
This doc link does not exist - update needed

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#3083]
https://github.com/ethersphere/bee/blob/08674d0c562ede8b3c248814fd553032a77384fd/packaging/bee.yaml#L1

**Comment by swarmHaseeb** [comment]
@vladopajic Hi, so umm are you actively working on this issue or do you need someone to fix this?

**Comment by vladopajic** [comment]
@swarmHaseeb Yes I am. I have fixed this in PR #3225 and now it needs to be reviewed.
