### ISSUE TITLE
Feature request: light node without postage syncing

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3094]
#### Summary
It would be good to have a light node without postage syncing, because it is what takes the most time during Desktop setup and also it is error prone. 

Also when using the Desktop app the postage syncing is not needed, because it does not store chunks and it does not have initial postage stamps either.

**Comment by notanatol** [comment]
The most intuitive way to achieve this is to have boolean flag that we can toggle to enable/disable postage syncing.

We just need to decide on the default behavior, what do you tihink?

**Comment by notanatol** [comment]
> If there are no downsides we can try this. As far as I know there is already a config variable that enables the postage snapshot syncing (`use-postage-snapshot`). Then this logic would disable that altogether, right?

that is correct, this new flag would disable syncing altogether, but if enabled - the `use-postage-snapshot` would be responsible for fetching the snapshot from the network or syncing from scratch.

Question - let's say
```
postage-syncing-enable: false
use-postage-snapshot: true
```
should we error because of conflicting flags or override the latter and log a message "ignoring postage snapshot flag because syncing is disabled"?

also @acud wdyt?

**Comment by agazso** [comment]
Ultra light node by definition cannot have the syncing enabled, because that would require `chain-enabled` to be `true`.

Regarding the config values logic: I would ignore postage snapshot if `postage-syncing-enable` is `true` and log a message, just how you suggested.

Btw I would prefer to have consistent naming in the config variables. I have seen variations of `*-enable` and I think it is not necessary at all, e.g. `postage-syncing: <true|false>` conveys the same meaning and that would be my preference. However that is also not consistent with the existing `use-postage-snapshot`, so for the sake of consistency we can consider `use-postage-syncing`.
