### ISSUE TITLE
Documentation on "/soc" doesn't mention use of swarm-postage-batch-id

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#3100]
### Location
https://docs.ethswarm.org/api/#tag/Single-owner-chunk/paths/~1soc~1%7Bowner%7D~1%7Bid%7D/post and OpenAPI documentation.

### Description
Documentation doesn't mention requirement of `swarm-postage-batch-id` parameter for this API. Anyway, trying to pass an invalid one I receive
```
{"message":"batch not found","code":400}
```
that make no sense, if it shouldn't be required. Anyway I didn't try to pass no one at all.

**Comment by agazso** [comment]
This is clearly an issue with the documentation, thanks for reporting!

As a general rule any time Bee writes to the network, a valid postage stamp is required and it is expected to be provided with the `swarm-postage-batch-id` header.
