### ISSUE TITLE
after upgrade to 1.6.3, stuck at depth 0

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#3107]
### Context
1.6.3 on Ubuntu 22.04 amd64

### Summary
The node has been struggling for 4-5 hours now.

**Comment by tmm360** [comment]
I've uploaded trace logs from my node, manifesting the issue:
https://www.swisstransfer.com/d/bd1bc878-df18-4086-9611-93c29ff9b344 (~6.5GB decompressed).

Link will expire on 22/8/2022

**Comment by tmm360** [comment]
1.7.0 solves for me

**Comment by acud** [comment]
closing this as it appears that the latest version fixes this. please reopen if the problem persists :+1:
