### ISSUE TITLE
RAM not cleared after uploading files

### ISSUE THREAD

**Issue by IgorShadurin** [ethersphere/bee#3113]
I upload a lot of files through a node. With each file, the amount of RAM consumed grows and hours after unloading, the RAM is not freed. So I have to reboot the node regularly.

Bee 1.6.3 via Docker.
All uploaded files are saved into feed (type sequence) and pinned locally.

<img width="670" alt="Screenshot 2022-07-23 at 14 09 54" src="https://user-images.githubusercontent.com/1595061/180602601-4b8b4d0b-9a28-4f4e-9876-7f52524f8979.png">

**Comment by acud** [comment]
hi @IgorShadurin, how large are the files? through which API endpoint are you uploading? something to keep in mind is that the go runtime does not immediately reclaim the unused RAM back to the OS, however the behavior you're showing is a bit bizarre. More info would be helpful in determining the cause. Thanks!

**Comment by IgorShadurin** [comment]
> hi @IgorShadurin, how large are the files? through which API endpoint are you uploading? something to keep in mind is that the go runtime does not immediately reclaim the unused RAM back to the OS, however the behavior you're showing is a bit bizarre. More info would be helpful in determining the cause. Thanks!

Files from few bytes to few megabytes. I am uploading data via /bytes endpoint with enabled pinning. Then I write feed with received reference. I'm using bee-js library for that.

```
const bee = new Bee('http://localhost:1633')
const topic = bee.makeFeedTopic(key)
const feedWriter = bee.makeFeedWriter('sequence', topic, privateKey)
const info = await bee.uploadData(batchId, data, {
 pin: true
})

await feedWriter.upload('MY_BATCH_HERE', info.reference, {
 pin: true
})
```

The data is uploaded in several parallel threads.
