### ISSUE TITLE
Can not pin a chunk

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#3119]
If I upload a chunk and want to pin it with the `POST /pins` endpoint it fails with `Not Found`. If pinning a chunk with the API is not supported then it should be at least documented.

**Comment by ldeffenb** [comment]
Which API are you using to upload the "chunk"?   POST /chunks, /bytes, or /bzz?  I can attest that POST /pins/{reference} works fine with references returned from POST /bytes.

**Comment by AuHau** [comment]
It was the `POST /chunks` endpoint.

**Comment by istae** [comment]
it is not allowed to pin single chunks,
you can only pin root addresses
