### ISSUE TITLE
Postage stamps do not report accurate utilization

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3122]
### Context
Bee 1.7 and lower versions

### Summary
Postage stamps with depth < 20 do not report accurate utilization. The suggested workaround is to use minimum 20 for depth, but this may make low capacity postage stamps 8x more expensive than it is required (where depth is 17).

This also makes it confusing for people who just try out the postage stamps and choose the minimum possible value and then they don't understand why their postage stamp utilization is reportedly high.

If there is a theoretic difficulty behind this then maybe it would make sense to say that the minimum is 20 and enforce that in the API.

**Comment by agazso** [comment]
In general postage stamps do not report accurate utilization. The easiest way to reproduce is the following:

1. Buy a postage stamp with `depth` 22. That should be enough for 17GB
2. Upload a 10MB file filled with zeroes (`dd if=/dev/zero of=test-10M-zero.data bs=1M count=10`)

The reported utilization value will be `12`, which is about 19% or 3.22GB, whereas it should be less than 1%, because all the leave chunks are the same, so only the intermediate chunks and the root chunk is different.

**Comment by agazso** [comment]
Related issue: #2851

**Comment by istae** [comment]
this problem starts to go away as the batch depth gets larger than the bucket depth.
The const 16 bucket depth may be too large.

What about setting the bucket depth as the current storage radius plus some buffer eg: 8 + 4
