### ISSUE TITLE
localstore leak

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3126]
The localstore is limited to 2^22 chunks (roughly 4M chunks, ~16G capacity), but due a potential leak in sharky, we have seen the localstore reach full capacity of a 70G disk.

![Image Pasted at 2022-7-26 11-17](https://user-images.githubusercontent.com/14264581/181226475-11e79254-9919-4b6b-a76a-3ff3229bc04b.png)

**Comment by agazso** [comment]
Duplicate of #2992 
Also related #1258
