### ISSUE TITLE
upload and download data mismatch/corruption

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3128]
As can be observed using the [grafana dashboard](https://monitoring.mainnet.ethswarm.org/d/R6nXBFH7k/milestone-smoke-test?orgId=1&refresh=30s&var-job=bee-gateway), 
there has been an increased rate of data mismatches, pointing to a possible localstore/netstore data corruption

smoketest logs

```
time="2022-07-27T13:14:43Z" level=info msg="uploaded data does not match downloaded data"                   

time="2022-07-27T13:14:43Z" level=info msg="length mismatch: download length 262144; upload length 5000000" 
```

**Comment by agazso** [comment]
There is another, related issue #3140

**Comment by agazso** [comment]
Closing this, keeping https://github.com/ethersphere/bee/issues/3140
