### ISSUE TITLE
Replace `resolver/multiresolver/multierror` with `hashicorp/go-multierror`

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/bee#3151]
Check if the `hashicorp/go-multierror` package provides the same functionality as our `resolver/multiresolver/multierror` package and replace our package with `hashicorp/go-multierror` if that's the case.

**Comment by aloknerurkar** [comment]
The description says replace hashicorp/go-multierror with our multierror, but the heading says the other way 😕

**Comment by mrekucci** [comment]
> The description says replace hashicorp/go-multierror with our multierror, but the heading says the other way 😕

Good catch, a copy-paste mistake 😇 fixed.
