### ISSUE TITLE
Simplyfy logging of `fmt.Sprintf("%x", value)` values

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/bee#3157]
Currently, most `[]byte` values are logged using the `fmt.Sprintf("%x", value)` call, review these records and try to remove the formatting of these values. At the same time, check that the output remains the same, if not, then implement the `log.Marshaler` interface for these types, which will produce the same output as in the case of `fmt.Sprintf`.

**Comment by swarmHaseeb** [comment]
@vladopajic Hi, can you confirm if you are actively working on this issue?

**Comment by vladopajic** [comment]
@swarmHaseeb Yes I am. I have fixed this in PR #3220 and now it needs to be reviewed.
