### ISSUE TITLE
API should listen also on IPv6 `::1` 

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#3167]
Node 18 changed the default behavior of translating DNS names into IPv6 instead of IPv4. That means that `localhost:1633` gets translated into `::1:1633`. I think this is a quite strong signal for push to IPv6 support and also it creates a lot of problems for us as suddenly a lot of our projects do not work on Node 18 as we use `localhost` in almost all our default settings.

Would it be possible for the Bee's API to listen also on the IPv6's localhost `::1`?

**Comment by ldeffenb** [comment]
You could just use 127.0.0.1 instead of localhost?

**Comment by AuHau** [comment]
As workaround yes (and one that we already use), but it is not a long-term fix ;-)

**Comment by ldeffenb** [comment]
But any change should work with all of http://localhost:1633 and http://127.0.0.1:1633 and http://::1:1633 and not leave any particular use case in the dust.

**Comment by AuHau** [comment]
Yup agree.
