### ISSUE TITLE
Migration functionality for the new data abstraction layer

### ISSUE THREAD

**Issue by aloknerurkar** [ethersphere/bee#3185]
Once we migrate everything to the new store, we would need a way to migrate the keys that we have in the store in the future. With the Store abstractions, Users can configure ways to provide information for the key and the byte representation. The migration functionality would need the following:

- Configuring a version for the store which would be a constant.
- Maintaining the current version on disk.
- Figuring out on start which migrations we need to run.
- Provide an easy mechanism for users to register migrations for their Items.

This task involves researching some of the existing migration functionalities and then coming up with a solution to handle the above requirements.

**Comment by vladopajic** [comment]
Doc with proposal could be found [here](https://hackmd.io/@ethswarm/H1_sxXOMs).

**Comment by vladopajic** [comment]
Closing this issue after proposal was reviewed (by @aloknerurkar, @mrekucci and @umerm-work).
