### ISSUE TITLE
Research what causes leaking in sharky

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3194]
It would be good to identify under what circumstances sharky is leaking. There is a previous thread about similar issues: https://github.com/ethersphere/bee/issues/1258

However that started long time ago and a lot of those problems may have been since fixed. 

One datapoint is that this may definitely be triggered without pinning, because this issue was experienced on the gateway nodes where pinning is not exposed to the API. But it definitely has data uploaded through it.

Maybe it would be good to check if the storage nodes also have this problem. Or to set up a storage node and another one that is used to upload data to, and see if there is any difference in the behavior.

**Comment by istae** [comment]
Leak was discovered in the localstore garbage collection at some point.
this has been fixed already.
