### ISSUE TITLE
Checking retrievability of a single chunk takes almost 30 minutes

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3205]
### Context
Bee 1.7.0, multiple OSes

### Summary
I uploaded the [Book of Swarm](https://www.ethswarm.org/The-Book-of-Swarm.pdf) that I previously downloaded from the https://ethswarm.org website and uploaded it to swarm with a [tool](https://github.com/agazso/swarm-random-chunk-upload) I created. This tool stores the individual chunks in a folder so that later their availability can be checked.

The uploaded BoS resulted in this hash: `ea681fc1595a978a52379deab002e319fb845e5836bd910e597f15c0f6520980`
It generated 3864 chunks, I attached a CSV file for the generated chunks, where they are listed as `chunk_hash,retrievability_time` columns.

From that the median time to check a chunk's retrievability (with the [stewardship endpoint](https://docs.ethswarm.org/api/#tag/Stewardship/paths/~1stewardship~1%7Breference%7D/get)) is ~3 seconds and the average is ~6 seconds. However there are some outliers and the longest one (chunk hash `b8d17f296190ccc09a2c36b7a59d0f23c4479a3958c3bb02dc669466ec919c5d`) takes about 28 minutes to return a positive answer!

Now there must be some anomaly with this particular chunk because I tested it from several different Bee nodes and the times are always in the 10 minutes range.

### Steps to reproduce
```curl -v http://localhost:1633/stewardship/b8d17f296190ccc09a2c36b7a59d0f23c4479a3958c3bb02dc669466ec919c5d
*   Trying 127.0.0.1:1633...
* Connected to localhost (127.0.0.1) port 1633 (#0)
> GET /stewardship/b8d17f296190ccc09a2c36b7a59d0f23c4479a3958c3bb02dc669466ec919c5d HTTP/1.1
> Host: localhost:1633
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Wed, 17 Aug 2022 15:41:16 GMT
< Content-Length: 24
< 
{"isRetrievable":true}

* Connection #0 to host localhost left intact
Start time 17:13:57, end time 17:41:17, elapsed 27:20 (1640s)
```

Attaching a file with the times for all the chunks:
[report.csv](https://github.com/ethersphere/bee/files/9364611/report.csv)

**Comment by agazso** [comment]
Upon further investigation I found a possible clue: out of all chunks there are only two that has a size different than 4096 bytes and the `b8d17f...` is one of them. The other is `38857ef7a417f3eec789c0cea5342fb2094e7900920cc813b0b87b695e8a2b98`, size 2090 bytes, but there is no anomaly with that one.

**Comment by ldeffenb** [comment]
You need to understand how bee breaks a file into chunks and stores it into the swarm, namely the BMT (https://github.com/fairDataSociety/bmt-js).

Also, you need to understand that the /stewardship endpoint does NOT work on individual chunks.  But if /stewardship recognizes the chunk as being part of a BMT, it will automatically check the retrievability of EVERY chunk that the BMT references.

This is also true for mantaray manifests (https://github.com/ethersphere/mantaray-js).  The /stewardship API will check the ENTIRE manifest, all nodes, and EVERY chunk of EVERY file that the manifest collection references.  Obviously, for a large collection, the root chunk will take a long time.  And every sub-node in the manifest will check it's sub-tree if that node is explicitly passed to /stewardship.

All of the above is actually done by the traverser defined in https://github.com/ethersphere/bee/blob/master/pkg/traversal/traversal.go.  Line 76 is where a mantaray manifest is recognized and fully, recursively traversed with each referenced file being passed to processBytes.  Line 89 handles a direct BMT (or generic chunk) reference passing it directly to processBytes.  It's the iterateChunkAddresses on line 53 that traverses all of the chunks of a BMT graph.

**Comment by agazso** [comment]
> You need to understand how bee breaks a file into chunks and stores it into the swarm, namely the BMT (https://github.com/fairDataSociety/bmt-js).

I understand how chunking works and the tool I used uses the `bmt-js` library to break the file into chunks.

> Also, you need to understand that the /stewardship endpoint does NOT work on individual chunks. But if /stewardship recognizes the chunk as being part of a BMT, it will automatically check the retrievability of EVERY chunk that the BMT references.

I don't think this is the case. The tool I wrote checks for individual chunk addresses with the `/stewardship` endpoint and it works. Athough I don't completely understand the code, there are distinct `if`s in the `Traverse` function to handle SOCs and at the end there is a code path with the comment `// Non-manifest processing.` which suggests to me that it handles individual chunks as well.

**Comment by ldeffenb** [comment]
I should have included an "only" in my statement.   /stewardship will work on an individual chunk, but if it recognizes the specified reference as a manifest or the root of a BMT, it will traverse the entire data structure.  This may be why you are seeing different times on some of your chunks.  They may be recognized and process more than just the single specified reference chunk.

**Comment by agazso** [comment]
Ah, okay I see what you mean and indeed it may cause this, the outliers may be the intermediate chunks or the root chunk itself.

And this actually highlighted a bug with my tool, that although it creates and uploads the manifest chunk, so that it generates the correct hash for the file, it does not save the manifest chunk to disk, so it is not checked.

Then I am closing this since this may be the intended behavior, although this API makes it impossible to check the availability of individual chunks in case of intermediate chunks.

**Comment by ldeffenb** [comment]
> Then I am closing this since this may be the intended behavior, although this API makes it impossible to check the availability of individual chunks in case of intermediate chunks.

I would agree with that statement 100%.  The /stewardship API leaves a LOT to be desired, including the ability to check just a single node of a manifest without it processing the entire data structure just because it smells like a manifest node.

**Comment by agazso** [comment]
As a workaround maybe a flag to disable the traverse behavior could help?

Otherwise the issue has deeper roots, namely that in swarm based only on the hash itself it is impossible to tell in advance what is the content (leaf chunk, intermediate chunk, root chunk, manifest, feed chunk), because all references are just 64 bytes. With a prefix it would be possible for universal endpoints to differentiate between them, therefore decide on the behavior without fetching the actual data.

**Comment by ldeffenb** [comment]
IMHO, there needs to be 4 modes of operation:

1) Check just the specified chunk ignoring BMT and manifest
2) Check the BMT of the specified chunk using a joiner
3) Check just the specified manifest sub-tree, ignoring all references
4) Check the specified manifest including all subtrees and all references

Right now, it only does 2 and 4 depending if a manifest node is recognized.

The -X PUT /stewardship would need the same 4 capabilities.

I personally run a dirty node that does 2 and doesn't even try to recognize a manifest node.  Option 2 can check any single reference returned by a /bytes upload, which happens to be how individual manifest nodes are actually stored.
