### ISSUE TITLE
Optimize logger alocations

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/bee#3211]
Write benchmark for logger and optimize memory allocations to a minimum. Consider a lock-free linked list as a data structure.

Resources:
https://github.com/golang/glog/blob/master/glog.go#L488-L502
http://hackemist.com/logbench/
https://github.com/imkira/go-loggers-bench
https://gist.github.com/Avinash-Bhat/48c4f06b0cc840d9fd6c
https://github.com/uber-go/zap/tree/master/benchmarks

**Comment by istae** [comment]
have we seen any instances where the logging is a bottleneck?

**Comment by mrekucci** [comment]
> have we seen any instances where the logging is a bottleneck?

Not really, it's just to avoid unnecessary memory allocations and put less strain on the GC.
