### ISSUE TITLE
Utilize swarm.BatchID

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3219]
This issue tracks effort to update all occurrences of batch identifier to  `swarm.BatchID` type.

PR #3216 has introduce new type `swarm.BatchID` for unique batch identifier instead of `[]byte`. That PR refactored occurrences only in the scope of the issue, but potentially there are more occurrences where this type could be used.

**Comment by aloknerurkar** [comment]
Firstly this PR is not merged yet. I dont understand why we are opening issues on this?

I am not sure if we even need this BatchID type.

**Comment by vladopajic** [comment]
Issue could be closed if it becomes irrelevant.

**Comment by vladopajic** [comment]
Closing this one as per #3216, #3221
