### ISSUE TITLE
Proposal: add swarm.BatchID type

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3221]
#### Summary
Introduce new type `swarm.BatchID` for representing unique batch identifiers instead of `[]byte`.

#### Motivation
By observing current code usage for handling batch id values it appears that `swarm.BatchID` would come handy as additional type in Swarm's zero layer. 

There are quite few reasons why zero layer (and layers build on top of it) would benefit form this type. In the enumerated list below I will list all benefits and how it can solve some of current issues in the codebase.

1) **type safety** 
 1.1) Having `swarm.BatchID` type in zero layer gives this layer opportunity to precisely specify it's API which removes it's perplexity for other layers building on top of it. This behavior does not only apply to zero layer. All other layers benefit in same manner as they would also be able to precisely specify their APIs. 
 NOTE: Please take a second to ponder that all (good and bad) decision in zero layer will scale up. All benefits of this change in zero layer will be translated in above. Consider this for issues mentioned later in this proposal. 
 1.2) It's not just about perplexity of APIs which define layer interface, but also perplexity can occur in same layer across different components. 
1.3) Generally, type safety gives us protection from various errors at compile time.

 _Principle_: All (good and bad) design decision in zero layer will scale up. 
 
2) **semantics**
Generally `swarm.BatchID` would clear out all possabilities for mixing frogs and apples in all layer. 
Current Swarm's code base (all layers) have a lot of different `[]byte` variables. It is not always clear what those variables actually contain. It could be some raw binary data from stream, string value or hexadecimal string value, etc. Looking only at hexadecimal string values - they could actually represent different things. They could represent `swarm.Address` (luckily Swarm has type for this), key, hash, signature, batch id, and so on... In order to understand what is held in these variables we need to know where those values came from, unless those variables have vary verbose names. 
Lets look at this vivid example, in which line of code was taken from current code base:
```var b []byte```
can we guess what's happening here? Everyone who is looking at this will understand that new variable `b` is defined. But what will be contained in this variable? We can literally put anything and everything in bytes slice of unspecified length. 
If we compare that line to the vary same line of another Swarm's code base, which uses `swarm.BatchID` types, we could actually see this:
```var b swarm.BatchID```
now not only developer how defined this variable, but everyone reading this code will have same level of understanding what will be contained in this variable. In the boundaries of this example (and provided code) we can see that later practice brings more meaning to the code. 

_Principle_:  The more information, code has, the better.
  (in practice): The more types, code has, the better.
 
3) **added functionality** 
 `swarm.BatchID` type can provide us with additional functionality:
 3.1) We would be able to implement `fmt.Stringer` interface which can be beneficial to developers (in all layers) because it can reduce boilerplate code when conversion to human readable string is needed. 
 In current code base there is boilerplate code when we need to convert batch ID values to human friendly values. This processes requires developers to manually convert value before writing to the log. This conversion could be achieved using at least two approaches, where preferred way is to use `hex.EncodeToString` while unpreferred `fmt.Sprintf("%x",...)`. It was already observed, by issue [#3157](https://github.com/ethersphere/bee/issues/3157), that unprefferd way ends up committed to the codebase and time is allocated for cleanup.
Suggested functionality would remove any possability for developers to make this kind of mess furthermore reducing boilerplate code.
3.2) `swarm.BatchID` type complemented with additional creator method would impose additional safety and validation for batch ID values. If we force this type declaration to be `[32]byte` we can be sure that whenever we use this type we will have specifed length so no validation for this would be needed. Creator method could be defined to create values of this type from hex strings which can preform sanity check for input. 
This would lead to more comfortable usage, because those who create `swarm.BatchID` would need to handle potential errors, while giving sanity guarantees to rest of system.
3.3) We can enrich this type by adding more functionality should we need it.
 
#### Implementation
Implementation should include: 

1) type definition in `swarm` package

```
type BatchID [32]byte
```

2) additional type specific methods:
2.1) creator method to create `BatchID` from hex string e.g. `func HexToBatchID(string) (BatchID, error)`
2.2) receiver method which implements `fmt.Stringer` interface

Implementation is quite small; example code could be seen in [this commit](https://github.com/ethersphere/bee/pull/3216/commits/5ccad116bee19831d3adfbf1f57ee4ea884cc3e8).

Adding this type will not require us to refactor every occurrence of batch id at once. We can granularly make refactoring.    

#### Drawbacks

No drawback as far as I can see.

**Comment by notanatol** [comment]
really solid argumentation, thanks!

**Comment by aloknerurkar** [comment]
@zelig @acud Thoughts on this?

In my opinion, BatchID is not a new type. I think BatchID is the same hash as the swarm.Address. As such defining a new type might lead to confusion.

I feel the only advantage of this type is for printing in logs using the `fmt.Stringer` interface. The rest of the operations on this type would be duplicated.

For eg:
Decoding the type would be the same as hex.Decode and this doesnt save us any code as with the new function proposed, it will be exactly the same no. of lines. Checking if they are equal is also a one-liner using the bytes package.

Instead, adding this new type might lead to some type casting in some places and also a lot of churn of code in the repo as this field is used in multiple packages. Changing this just for the advantage of printing in logs when `hec.EncodeToString` is a one-line call without error, seems to be too many changes without gaining anything in return.

I feel a lot of external projects using bee also rely on this swarm package and changing this here would require them also to update their code if they are using the `stamp` field in the chunk.

I am not necessarily against anything proposed, I just feel there is not enough return on time invested here.

**Comment by mrekucci** [comment]
@vladopajic Although, as you mentioned, it may have some advantages, I am not entirely convinced that we need this change (now). Alok's comments also have some merit. Golang's programming model is not about types and type taxonomies; most of the time, you make do with basic types. I would refer to the [following quote](https://github.com/golang/go/issues/29649#issuecomment-454820179):
> This is a restriction expressed in the type system. **Go intentionally has a weak type system, and there are many restrictions that can be expressed in other languages but cannot be expressed in Go. Go in general encourages programming by writing code rather than programming by writing types.** Why does this restriction in particular carry enough benefit that it is worth adding to the language? What does it permit us to do that we cannot already do?

If arguments change in the future, I would suggest not implementing it as a transparent type, but rather wrapping a slice in structure and using methods to enforce size (and other) invariants. This not only saves copying the array every time it is passed to a function/method but also helps us avoid some of the potential problems mentioned in this article: https://tailscale.com/blog/netaddr-new-ip-type-for-go/

**Comment by vladopajic** [comment]
>  Golang's programming model is not about types and type taxonomies; most of the time, you make do with basic types. I would refer to the https://github.com/golang/go/issues/29649#issuecomment-454820179:
This is a restriction expressed in the type system. Go intentionally has a weak type system, and there are many restrictions that can be expressed in other languages but cannot be expressed in Go. Go in general encourages programming by writing code rather than programming by writing types. Why does this restriction in particular carry enough benefit that it is worth adding to the language? What does it permit us to do that we cannot already do?

Please correct me if I am wrong, but this comment addresses proposal for adding mechanism where one would be able to specify type along with set of valid values. What author of this comment wanted to say is that Go intentionally didn't want to implement such mechanism in the language. With idea that if you would want to have any restrictions you would do it in the code. 

For example, we can look at how Go enums are specified. Well, to be precis and to take a cue from comment author, in Go there is no built in language mechanism to do so, because enums are exactly for what being proposed - definition of type with set of possible values.
Usual developers practice for defining enum like constructs is to specify *new type* (say `int` alias) and to specify const values for each possible enum value. Developers would have to have set of utilities which would ensure that only valid const values are used.

Go actually encourages specifying custom alias types by having support for in the language. As we can see things that are not encouraged by Go will not end up in the language in the first place.

----

> Instead, adding this new type might lead to some type casting in some places and also a lot of churn of code in the repo as this field is used in multiple packages.

If we specify `BatchID` type to be alias for `[]byte` no casting will be need.

----

>  Changing this just for the advantage of printing in logs when hec.EncodeToString is a one-line call without error, seems to be too many changes without gaining anything in return.

This is not only advantage. Type safety and semantics are much more important factors here.

---

> Decoding the type would be the same as hex.Decode and this doesnt save us any code as with the new function proposed, it will be exactly the same no. of lines. Checking if they are equal is also a one-liner using the bytes package.
  
In addition to decoding value from string, we can also have sanity check to ensure that decoded value has expected size. As we can see here, this step can be overlooked in decoding process.

**Comment by mrekucci** [comment]
@vladopajic
> Please correct me if I am wrong, but this comment addresses proposal for adding mechanism where one would be able to specify type along with set of valid values.

This proposal is not relevant to our discussion. The comment that I pointed out from this proposal, particularly its highlighted sentences, is/are. It relates to the Golang program model in **general**. Not every idiom or way of doing things from other languages is idiomatic or more appropriate/applicable to Golang.

**Comment by vladopajic** [comment]
Closing this issue since proposal was not approved in voting process.

Voting results: for: 1, against: 3, abstain:1
