### ISSUE TITLE
Improve Ergonomics of unavailable APIs during boot

### ISSUE THREAD

**Issue by swarmHaseeb** [ethersphere/bee#3242]
Some endpoints on the debug API take around 10 seconds to start up. Bee already reports healthy and ready statuses, but some endpoints return {"message":"Not Found","code":404} (e.g. /chequebook/balance) during that initial period, before the response switches to normal.
It would be good to understand how the API boots up and improve this by making it either “on” or “off”
Identify all endpoints that have this issue.

**Comment by vladopajic** [comment]
It looks like this is not issue after anymore. PR #3248 seams to have fixed this because healthy and live statues are being set more precisely.
