### ISSUE TITLE
Make the initial deposit 0 for full nodes

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3243]
#### Summary
It would be good to change the initial deposit (`swap-initital-deposit` config variable) to `0` as a default for full nodes. Currently it is set to 1 BZZ and the node won't start until there is enough money in the node's wallet so that the deposit can be transferred to the chequebook.

#### Motivation
The reasoning behind the change is that full nodes are meant to be run for earning BZZ and not for using their API for accessing data, especially uploading files. This means that people who wants to run their nodes only for earning BZZ have to first also buy BZZ and deploy it to a chequebook which they won't use. By changing the default to 0 would simplify the setup process.

It is possible to deposit money in the chequebook any time later when the node is already up and running.

#### Implementation
There are two possible ways to do this:
1. Changing the default in the code (and update the comments in the default `bee.yaml` config that is shipped with the packages).
2. Changing the default in the bee.yaml config

I think it would be better to change it in the code (solution 1.) because 0 makes sense for all use cases (desktop, full node, etc.) and it is still possible to change if someone needs a different value.

#### Drawbacks
Maybe there are some historical reasons why this has been chosen this way, but I can't see any problems with this proposal.

**Comment by ldeffenb** [comment]
Maybe I'm just lucky, but I've been running two mainnet nodes for months now and both were started with a zero initial deposit.  Knock-on-wood, I have not observed any ill effects on these nodes' operation as compared to my nodes that actually have a checkbook balance.

Of course, I do not upload data through these nodes that may cause them to need to issue a cheque for pushing data.  And all retrievals via these nodes are carefully controlled to keep them within the pseudo-settlement "free" bandwidth utilization.
