### ISSUE TITLE
pull sync outstanding tasks

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#329]
this issue enumerates the outstanding issues that arise out of the pull sync initial PR.

- [ ] falling edge kademlia channel wrapper
- [x] metrics
- [x] extract number of bins from pullstorage, pullsync protocol and puller to be injected from constructors
- [x] construct the tests in pullsync and pullstorage around the limit in a way which the limit can be adjusted through the const and that the test adjusts automatically
- [x] puller.go - handle error on next interval L313
- [x] puller.go L390 - eliminate return on top==0 (shouldnt happen, probably related to the mocks) (#810)
- [ ] subscribe pull in localstore - db shutdown might be removable altogether 
- [ ] sync only in NN
- [x] abstract syncCtx to a separate object (#810)
- [ ] get rid of mode set sync pull? just have mode set sync?

related to:
#193 #302 #144 #136 #254

**Comment by Eknir** [comment]
@acud , is this in progress?

**Comment by acud** [comment]
not yet. after the release.

**Comment by Eknir** [comment]
@acud , is this in progress? If so, could you connect the PRs to this issue?

**Comment by Eknir** [comment]
Status update?
