### ISSUE TITLE
`GET /stamps/<id>` throws `cannot get batch` after purchase

### ISSUE THREAD

**Issue by AuHau** [ethersphere/bee#3300]
If you query for `GET /stamps/<id>` endpoint with `id` of freshly created stamp it returns `Bad Request: cannot get batch` error.

**Comment by AuHau** [comment]
We had to do hotfix like this: https://github.com/ethersphere/bee-dashboard/commit/c0456a3bf6d541457b706670b1a757d2b1d70f10

**Comment by Cafe137** [comment]
Expected:

- first the batch reports `exists: false`
- then `exists: true` and `usable: false`
- finally `usable: true`

Actual:

errors out

**Comment by umerm-work** [comment]
Here is output of PR :
First Time
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": false,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": false,
    "batchTTL": -1,
    "expired": false
}

Second Time
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": false,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": true,
    "batchTTL": -1,
    "expired": false
}

Third Time
{
    "batchID": "52a2733df435ce6c7f1b3891b7afeba630b7deec6000b4aee09daee3b96f7f01",
    "utilization": 0,
    "usable": true,
    "label": "",
    "depth": 20,
    "amount": "600",
    "bucketDepth": 16,
    "blockNumber": 7709035,
    "immutableFlag": false,
    "exists": true,
    "batchTTL": -1,
    "expired": false
}
