### ISSUE TITLE
DELETE `/pins/{ref}` throws `unpin root hash: deletion of pin failed`

### ISSUE THREAD

**Issue by asabya** [ethersphere/bee#3302]
### Context
Tested on v1.8.0 and v1.8.1. Mac arm

### Summary
unpinning fails for content uploaded with encrypt header from `/bytes` endpoint.

### Expected behavior
Return 200

1. upload to bee directly `/bytes` post request with pin and encrypt header 
2. try to unpin the reference (from step 1) `/pinning/{ref}` delete request
3. See error
```
{
    "message": "unpin root hash: deletion of pin failed",
    "code": 500
}
```

**Comment by ldeffenb** [comment]
You might want to turn on debug level logging and do the delete again.  IIRC, the unpinning action has additional details that log showing more about what the issue might be.

**Comment by Cafe137** [comment]
Same issue here.

```
"time"="2022-09-30 11:52:41.061787" "level"="debug" "logger"="node/api" "msg"="unpin root hash: delete pin failed" "chunk_address"="703d3400e5cc9a6ba3f620a729315fe768dbe4347b4ace29aa8a986ccbe87878" "error"="3 errors occurred:\n\t* traversal iteration failed\n\t* get pin index: get value: leveldb: not found\n\t* unable to unpin the chunk for leaf \"fa514a85dda0b609b7cd14bae8d4276bddd9c7bed7011f56b1d8fd0a2fa4491d\" of root \"703d3400e5cc9a6ba3f620a729315fe768dbe4347b4ace29aa8a986ccbe87878\": get pin index: get value: leveldb: not found\n\n"
"time"="2022-09-30 11:52:41.061868" "level"="error" "logger"="node/api" "msg"="unpin root hash: delete pin failed"
```

**Comment by aloknerurkar** [comment]
Can you verify if this issue persists post 1.17.2. We can reopen this if it does. Closing it for now.
