### ISSUE TITLE
rpc endpoint free plans could reach block limit while update 1.8.0 / 1.8.1 

### ISSUE THREAD

**Issue by tamas6** [ethersphere/bee#3312]
### Location
https://docs.ethswarm.org/docs/installation/install

### Description
this may be getblock.io specific, but no previous update caused this before, but now even to 1.8.1. 
it took me a while to figure out why swarm-extension thinks I'm out of funds.
logs indirectly indicated rpc endpoint issue, but needed many professional support on discord 👌

switching to https://www.quicknode.com/ solved cause it mesures limit monthly, not daily as getblock.

I'm not sure if I can state this but it seems these newer bee versions are more blockchain data heavy, and to run smoothly we can indicate in the docs what price plans should the user try (sometimes needs more than free 40k block / day e.g.) 
or link documentation to make their own blockchain node

**Comment by ldeffenb** [comment]
The 1.8 upgrades completely reload the existing stamps from the blockchain.  This would account for a large blockchain API hit during these upgrades.   This is NOT the norm for upgrades, but was necessary for this one to prepare for storage incentives.
