### ISSUE TITLE
Flaky test `TestDepthChange`

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3325]
Unit test `TestDepthChange` seams to be flaky. CI job [has failed](https://github.com/ethersphere/bee/actions/runs/3104521168/jobs/5029090731) although change from PR couldn't affect it (since it had no change on source code), also other subsequent jobs have completed successfully.

Logs output from CI:
```
     puller_test.go:412: error getting interval for bin 4: storage: not found
--- FAIL: TestDepthChange (3.34s)
    --- PASS: TestDepthChange/move_peer_around (2.06s)
    --- FAIL: TestDepthChange/peer_moves_out_of_depth_then_back_in (1.28s)
```

**Comment by acha-bill** [comment]
Closing as this test no longer exists
