### ISSUE TITLE
1.8.1 db nuke clears nonce?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3331]
### Context
bee 1.8.1 on Linux on mainnet swarm

### Summary
This is an original node that was upgraded to 1.8.0 and then to 1.8.1.   In the 1.8.0 upgrade, the node mined a new nonce to get back into the original neighborhood for the changed overlay calculations.   Today I had occasion to "db nuke" the node and when started up after the nuke it is mining the overlay again?

### Expected behavior
Once a nonce is mined, I would expect it to be retained across a db nuke.

### Actual behavior
The node is re-mining the overlay after the db nuke.   Waiting for startup begins again...

### Steps to reproduce
Upgrade a pre-1.8.0 node to 1.8+ and wait for the node nonce/overlay to be established.  "db nuke" the node and restart it and watch what happens.

### Possible solution
Please preserve the nonce across the db nuke!    This is positively painful!

Maybe this is as easy as adding "overlayV2_nonce" to https://github.com/ethersphere/bee/blob/cc95d37277472ffbfb72acedf3d51011abb7428b/pkg/statestore/leveldb/migration.go#L337

**Comment by ldeffenb** [comment]
Confirmed.   I db nuke'd the node again and it's back to "finding new overlay...".

**Comment by ldeffenb** [comment]
Just did my 4 already-migrated-and-mined testnet nodes only to be reminded of this issue.  Burning some additional CPU while waiting for them to come back up!   Maybe it's as easy as adding "overlayV2_nonce" to https://github.com/ethersphere/bee/blob/cc95d37277472ffbfb72acedf3d51011abb7428b/pkg/statestore/leveldb/migration.go#L337

**Comment by agazso** [comment]
Fixed by #3384
