### ISSUE TITLE
"Reserve Size" discrepancy

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3337]
### Context
bee version 1.8.2 on mainnet swarm - 2 different nodes

### Summary
I have been interested in, and monitoring my two nodes reserve size and just discovered the depthmonitor debug log which is now reporting the results of the new ComputeReserveSize counting routine.  My two mainnet nodes have vastly different numbers showing between bee_localstore_reserve_size (metric from db.reserveSize value) and the ComputeReserveSize result (from depthmonitor's current size log).

```
Node            ComputeReserveSize  bee_localstore_reserve_size
1.3 TB node     radius 9   626,769       43,385,014
db nuked node   radius 7 2,534,368        3,424,913

```
I have 2 other mainnet nodes that have not yet upgraded to 1.8.2, so I'll try to remember to report their results once I update them.

### Expected behavior
I would expect there to be one definitive value for the current "reserve size".  Especially since I believe the evictBatch logic is using the db.reserveSize to evict and the depthmonitor is using the ComputeReserveSize to attempt to fill it up more.

### Actual behavior
As you can see in the Summary section, there are two definitely different values showing up.

### Steps to reproduce
Just look at the metric and the debug log in any node and I suspect they'll be different.

### Possible solution
Possibly have the ComputeReserveSize result automatically update the db.reserveSize value to keep them in sync at least every time the reserve is explicitly counted?   Or determine why db.reserveSize is deviating from the index iterator (supposedly definitive) count?

**Comment by istae** [comment]
Fixed by https://github.com/ethersphere/bee/pull/3579
