### ISSUE TITLE
Bee-clef is still in the default configuration 

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3356]
### Context
Bee 1.8.1

### Summary
During the milestone 2 (make it easy to run a bee node) the decision was made to not make bee-clef a default. It is removed from the documentation as default already. Still it is in the default configuration as of today. It would be good to remove it by default and let advanced users to enable it.

Here it is in the default config:
https://github.com/ethersphere/bee/blob/621c62c5cbc705998303597078e3bdc51bcee8b0/packaging/bee.yaml#L14

Also it would be good remove as a dependency for the bee package (if it is a dependency).

**Comment by istae** [comment]
Related #4100

**Comment by nikipapadatou** [comment]
closing this as duplicate - handled at https://github.com/ethersphere/bee/pull/4252
