### ISSUE TITLE
testnet stamps have batchTTL = -1

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3389]
### Context
1.8.2 and 1.9.0 rc3

### Summary
Stamps located in the testnet are reporting a batchTTL of -1.

### Expected behavior
I would expect the stamp to have a positive TTL.

### Actual behavior
```  "stamps": [
    {
      "batchID": "84529f9ac63b0030a60519dc74eca9ef23096f28110f3c8e836dcd7a8381789b",
      "utilization": 10,
      "usable": true,
      "label": "OSM-0-8",
      "depth": 25,
      "amount": "100000000",
      "bucketDepth": 16,
      "blockNumber": 7712510,
      "immutableFlag": false,
      "exists": true,
      "batchTTL": -1,
      "expired": false
    }
```

### Steps to reproduce
Create a stamp, wait for it to exist and become usable, and the batchTTL will be -1.

### Possible solution
I have tracked this down in the source code to a zero currentPrice coming from the blockchain.  When will a storage price be set on the testnet?  It is important that this be published so that stamp owners can top-up as necessary to keep their data alive as we enter the storage compensation testing phase.
```curl http://localhost:6071/chainstate | jq
{
  "chainTip": 7718030,
  "block": 7718025,
  "totalAmount": "0",
  "currentPrice": "0"
}
```

**Comment by istae** [comment]
Setting a non-zero price on the price oracle resolves this, thanks.
