### ISSUE TITLE
Unexplained intensity and number of disconnections and reconnections

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#3414]
We have been observing an unexplained intensity and number of disconnections and reconnections

**Comment by ldeffenb** [comment]
I'll ditto this observation.  Here's a graph of bee_kademlia_currently_connected_peers for the past 12 hours on 3 of my mainnet nodes.   Interesting that only 2 of them have the square-wave appearance.
![20201010-Peers](https://user-images.githubusercontent.com/5175026/194991830-2ab33142-5f96-4810-b210-a748c55d1f43.png)
