### ISSUE TITLE
neighborhood reserve discrepancy

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3445]
After releasing the storage incentives to the testnet, it was realized that nodes of a neighborhood were reporting different reserve commitment samples, which is a direct result of chunk differences across the reserves of neighborhoods.

**Comment by istae** [comment]
## reserve content discrepancy
- storage radius may be the same but batch evictions are sometimes  different across the neighborhood 
- it seems that if live sync or historical sync returns with error, no new sync process is established
- many make offer context cancellations in the logs, which terminates syncing
-  "msg"="unverified stamp" "error"="batchstore get: get batch 7efb6d7be447cccafd3139407abd4a430e153f17d36084401c623d934532fdcf: storage: not found, not found", which is a sign that when batches expire and are evicted, chunks get leftover.
-  bugs are getting reported in branch `reserve-bugs` with `BUG:` comments
- if SyncInterval has a chunk with an invalid/expired batch or if a write to storage fails, both historical and live syncs terminate. cause it returns an error. these should be "soft" errors, and not terminate syncing

## cleanup
- we can remove the falling edge detector, it was originally put in place because of high cpu usage during bootup as kademlia was establishing new connections, but the puller now waits for node warm up.

**Comment by ldeffenb** [comment]
Not only are the sample hashes different, but in some neighborhoods, committed samples are even different depths.

**Comment by agazso** [comment]
Related fix for pullsync: https://github.com/ethersphere/bee/pull/3444

**Comment by agazso** [comment]
Related fix for removing pullIndex for caching: https://github.com/ethersphere/bee/pull/3447

**Comment by agazso** [comment]
Related fix for puller rewrite: https://github.com/ethersphere/bee/pull/3437

**Comment by agazso** [comment]
This seems to be addressed and seems working well in the [1.10.0](https://github.com/ethersphere/bee/releases/tag/v1.10.0) release.
