### ISSUE TITLE
claim tx fails with high gas price

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3465]
### Context
v1.9.0-1b9ccf48 running in testnet on goerli blockchain

### Summary
I had a node that commited, revealed, and was selected the winner, but failed to submit the claim transaction with the following log:

```
"time"="2022-10-26 08:54:59.191404" "level"="debug" "logger"="node/transaction" "v"=1 "msg"="sending transaction" "tx"="0x19380324c47c5780d50f3ea2907a43832bb7703e264ef0d98b392155d658cb75" "nonce"=2271

"time"="2022-10-26 08:54:59.193656" "level"="error" "logger"="node/storageincentives" "msg"="claim" "error"="error claiming win: claim: tx fee (1.02 ether) exceeds the configured cap (1.00 ether)"
```

### Expected behavior
I expected the claim transaction to be processed.

### Actual behavior
The claim transaction was never submitted.

### Steps to reproduce
Get the storage incentives agent to play a round with very high gas prices.  Goerli at the time was >150gwei gas price and is now just short of 250gwei when my node did exactly the same thing; commited, revealed, won, but failed to claim.

### Possible solution
I see that PR #3452 is reducing the GasLimit on both commit and reveal from 3,000,000 to 1,000,000.   I suspect that the combination of high gas price on goerli (150+gwei at the time) coupled with the commit GasLimit of 9,000,000 caused the geth/goerli RPC provider to calculate that the transaction fee would exceed the default limit of 1 ETH.

Does the commit really need a GasLimit of 9,000,000 or should it be using something like eth_estimateGas?   Maybe even a debug log in the transaction layer Send() that does the eth_estimateGas and logs that value against what the transaction originator specified to assist in tuning the hard-coded values?

Or better yet, implement a "max gas price" configuration parameter that would cause the storage incentives to not even start playing a round if the gas prices exceed that limit before even triggering the commit?

**Comment by ldeffenb** [comment]
BTW, geth, which is what I use for my goerli RPC provider, has the following command line argument which is apparently the source of the error:
```
--rpc.txfeecap value                Sets a cap on transaction fee (in ether) that can be sent via the RPC APIs (0 = no cap) (default: 1)
```

**Comment by istae** [comment]
Fixed by recent changes to gas price and gas limit changes.
