### ISSUE TITLE
Passing bootnode flag

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#348]
Today, I tried to specify another node as a bootnode. As per the instructions `bee start -h`, I passed an address in between brackets []. However, I get an error:

```
DEBU[2020-06-22T12:42:51+02:00] multiaddress fail [/ip4/77.161.16.115/tcp/7070/p2p/16Uiu2HAmFFHqxqwp4RRXktdBTU9WZ37uA1SAv2mHshmgyuGLnR4N]: failed to parse multiaddr "[/ip4/77.161.16.115/tcp/7070/p2p/16Uiu2HAmFFHqxqwp4RRXktdBTU9WZ37uA1SAv2mHshmgyuGLnR4N]": must begin with / 
```
If I pass the address without brackets, it works fine. Fixing this issue is done by either updating the help text, or allowing multiple bootnodes to be passed in an array.

**Comment by vandot** [comment]
@Eknir you can also specify ` ["/ip4/77.161.16.115/tcp/7070/p2p/16Uiu2HAmFFHqxqwp4RRXktdBTU9WZ37uA1SAv2mHshmgyuGLnR4N"]`

**Comment by Eknir** [comment]
@vandot, it works now. I don't know if this was fixed or I do something differently. Thanks for the answer anyways. Closing the issue!

**Comment by vandot** [comment]
@Eknir I added `"` but you are right there is no `"` in help text, not sure if its possible to add them

**Comment by Eknir** [comment]
@vandot , it work as `"[multiaddress]"`, `["multiaddress"]`, `"multiaddress"`, `[multiaddress]`. Not sure what I bumped into yesterday.

**Comment by janos** [comment]
Also `--bootnode` flag can be specified multiple times.
