### ISSUE TITLE
Postage stamp utilisation went to zero

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3492]
### Context
Bee 1.8.1 light node with Swarm Desktop 0.16.0 on Linux

### Summary
I bought a stamp with `depth` 27 (about 500GB) four days ago. Then I uploaded some data and the utilisation was around 20%. Now I checked again and the utilisation is 0%. 

I was thinking that maybe the internal bookkeeping of the postage stamps got reset somehow, but I still have one postage stamp which has utilisation at 50% so that is not the case.

The postage stamp id is `ec4417164928fabb98a9097bacb575caf7093671864c5c26cf996260e37c6c1a`.

**Comment by istae** [comment]
Related [#3577](https://github.com/ethersphere/bee/pull/3577)
