### ISSUE TITLE
Uploading /bytes with swarm-pin: true doesn't pin all chunks

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3514]
### Context
All versions up to and including 1.10rc3

### Summary
I've been trying to explain why some of the chunks of a large dataset become inaccessible over time in the originally uploading node when swarm-pin: true is set on the uploads.  In a recent unpinning test, I believe I have finally tracked down the cause.   Consider:

Two file contents A and B.  A hashes to reference RA which includes chunks RA, 1, 2, and 3.   B hashes to reference RB which includes chunks RB, 4, 5, and 3.  Yes, both file contents include the same final chunk in their BMT.

Bee is "smart" when storing chunks and doesn't actually redundantly store chunks that are already present in the localstore.   I suspect that when B is uploaded, and chunk 3 is generated in the BMT, that the internal pin-counter for this chunks is NOT incremented.  Then, if reference RA is unpinned, chunk 3 is decremented from 1 to 0 and put into the gc index.   If this gc index is actually processed before reference RB is unpinned (because a lot of unpinning is going on), then RB will fail to traverse it's BMT because chunk 3 is no longer in the node, and indeed, possibly no longer available in the swarm.

I have anecdotal evidence of this, but will be working to provide exact content for A and B examples for future testing.  Note however, that for this bug to manifest itself, the shared chunk must be completely removed from the node's gc before the second reference using that chunk is unpinned.

### Expected behavior
If a chunk is involved in multiple pinned references, then that chunk's pin-counter should reflect the total count of references using the chunk to avoid early removal from the localstore.

### Actual behavior
When a reference is unpinned that includes a shared chunk, and sufficient activity elapses to flush the shared chunks from the gc index, then subsequent references sharing that chunk will fail to unpin with a traversal error.

### Steps to reproduce
Read the description above.

### Possible solution
Ensure that shared chunks being newly stored do indeed get their pin-count incremented even though the chunk is already in the localstore.

Note that the rewrite of the pinning storage support to split it away from the reserve will still likely be subject to this issue.

**Comment by aloknerurkar** [comment]
So this will be fixed with the upcoming localstore changes. I guess you have already seen the new pinning store which has this functionality of collection based referencing of chunks. So it wont store duplicate chunks and also maintain separate references for chunks across collections.

**Comment by ldeffenb** [comment]
I haven't actually looked at the new implementation, but when I finally realized this the wee hours of the morning, I wanted to document it somewhere just in case the new implementation was still counter-based and possibly relying on new BMT leaf chunks being uniquely stored.   I'm going to try to get examples of A and B to possibly use in a test case to ensure that this issue doesn't exist when the new pinning implementation is released, if we can keep this issue open until then to remind me?

**Comment by aloknerurkar** [comment]
@ldeffenb So I am closing this for now as this should be fixed ideally. If this issue persists maybe we can create a new issue or reopen this.
