### ISSUE TITLE
Unpinning doesn't remove from reserve

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3519]
### Context
I had a node (overlay e1dc994c4...) with lots of pinned data which was unpinned before the stamp expired.  I was refreshing this data by reuploading all of it, most of which was marked "seen" in the associated tag, when the stamp finally expired terminating my re-upload attempt.  In the end, I still have 196,000 references pinned, but IsFullySynced is still showing a load of 4,124,862 chunks authorizing this node to still participate in the storage initiatives.

```
"logger"="node/depthmonitor" "msg"="depthmonitor: IsFullySynced" "rate"=0 "load"=4124862 "ReserveCapacity/2"=2097152
```
Note: I believe this is one of my -dirty logs and won't be found in the standard bee source of any version.

### Summary
Somehow, even though the data was unpinned, IsFullySynced is still counting the chunks as being in Reserve.  Is it possible that the unpinning left the chunks in the pullsync index and they were not evicted because of the pin?

### Expected behavior
I would expect the chunks to be completely gone after unpinning given that they are now part of an expired stamp.

### Actual behavior
The node continues to participate in the storage incentives by virtue of the "load" chunk counting in IsFullySynced.    However, given that the entire testnet has no valid stamps, there is nothing to collect on the claim.  This has happened in rounds 52126 through 52128 and is currently happening again in round 52129, although in this round there is one other node (overlay b7563e747...) that has also committed.

Even though IsFullySynced is indicating a large "load", the depth of the node is zero so it will participate in every Schelling game round.

### Steps to reproduce
Pin a bunch (millions of references) of data into a node.   Unpin that data and wait for the stamp to expire is how this one happened.

### Possible solution
Not sure how IsFullySynced is still seeing the data.   I'm actively unpinning the remaining 196,000 references, but I don't expect the situation to change.

**Comment by ldeffenb** [comment]
Apparently these 4+million chunks are still in the node based on the following sampler log:
```
"time"="2022-11-09 14:57:18.293811" "level"="info" "logger"="node/localstore/sampler" "msg"="sampler done" "stats"="Total: 4124862 NotFound: 0 New Ignored: 0 Iteration Duration: 361 secs GetDuration: 1775 secs HmacrDuration: 77" "sample"={"Items":[],"Hash":"b34ca8c22b9e982354f9c7f50b470d66db428d880c8a904d5fe4ec9713171526"}
```
And for some reason, they're not being called "New Ignored" even though their stamp is expired!

**Comment by aloknerurkar** [comment]
@ldeffenb There are some localstore fixes in the latest RC. Can you try those and give us some feedback?
