### ISSUE TITLE
Investigate and fix failing beekeeper gc test

### ISSUE THREAD

**Issue by mrekucci** [ethersphere/bee#3527]
The gc beekeeper test [was disabled](https://github.com/ethersphere/bee/pull/3525) due to changes in [PostageStamp smart contract](https://github.com/ethersphere/storage-incentives/commit/4d911417e355392b9945dd66a6046fa85f5c938f). Investigate the possibility of fixing the tests.

**Comment by agazso** [comment]
There is a function on the contract that can set the minimum batch depth, and that is what is compared to the `bucketDepth` when creating the batch. With that it is possible to fix the GC test without changing the contract.

Related issue: https://github.com/ethersphere/storage-incentives/issues/56

**Comment by nikipapadatou** [comment]
This is relevant was part of the old localstore. Not relevant anymore.
