### ISSUE TITLE
rc4 Contract issues

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3534]
### Context
1.10.0 rc 4

### Summary
The Redistribution contract seems to be updated in rc4, but the ABI is not (yet) available at goerli.etherscan.io.?

And my first Claim transaction logged the following:
```
"time"="2022-11-11 12:20:07.983724" "level"="error" "logger"="node/storageincentives" "msg"="claim" "error"="expired batches exist: execution reverted"
```
According to pkg/chain/chain.go, the postage stamp contract address has not changed, but that contract does not seem to have an expiredBatchesExist method which is being called before a claim transaction is even submitted.

### Expected behavior
I thought rc4 would continue to play the Schelling Game successfully.

### Actual behavior
Fails before submitting the claim transaction.

### Steps to reproduce
Fire up a node that thinks it can play the storage incentives Schelling game.  It will commit, reveal, and then fail before claiming.

### Possible solution
Update pkg/chain/chain.go for the new PostageStamp contract and upload the ABI and source to be visible at goerli.etherscan.io.

**Comment by ldeffenb** [comment]
From rc4's pkg/chain/chain.go
Redistribution contract: https://goerli.etherscan.io/address/0x7d5ff32e744340ab26873d05e019a0d27fe4716f
PostageStamp contract: https://goerli.etherscan.io/address/0x7aac0f092f7b961145900839ed6d54b1980f200c

**Comment by swarmHaseeb** [comment]
this issue will be resolved by changing contract addresses and abi in bee, if we are ready to do it. @mrekucci @notanatol , maybe if Esad is ok with changing it.
