### ISSUE TITLE
Add wallet address to the `/wallet` endpoint

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#3569]
Currently the wallet endpoint returns a field called `contractAddress` and that is the address of the chequebook contract. However it is missing the actual wallet address, which is the same as the ethereum address of the node. It would be good to have it as well.

**Comment by istae** [comment]
the wallet endpoint is suffering from misnaming a lot of things
like bzz and xdai fields should be named "bzzBalance" and "nativeTokenBalance", and "chequebookAddress".

Maybe as part of this PR, we can also fix this, and the update documentation.
