### ISSUE TITLE
Postage stamp utilization grows much faster it should

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#3606]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
MacOS, Swarm Desktop 0.16.0, Bee 1.8.1

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1554520/204664158-875c20e7-cc88-4a20-ac4f-41448d15fc29.png">

### Summary
Uploading a relatively small file takes up relatively a lot more postage stamp utilization as it should.

### Expected behavior
Expected that a cca. 67 GB postage would handle roughly that amount of storage.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1554520/204664462-573aa1d3-1e01-4f92-a87b-05628f3bd387.png">

### Actual behavior
Using Swarm Desktop to upload some files, the screenshots will illustrate file sizes and stamp utilization afterwards.

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1554520/204664994-00decce7-67e8-44bc-bcad-9bc6939db192.png">

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/1554520/204665161-9f33d98f-bc56-4264-9253-37469dfb9407.png">

This does not seem to happen with every file, or maybe the stamp info does not get updated immediately. But with a larger amount of files, it is noticable.

In one of the cases, a 67 GB stamp was depleted in trying to upload cca. 400 MB of files (and they did not even finish uploading).

### Steps to reproduce
Use Swarm desktop to upload a number of larger files and monitor stamp usage. Or use a tool such as https://github.com/darkobas2/util_swarmsync to upload several files at once. 

### Possible solution

Have no idea.

**Comment by istae** [comment]
related https://github.com/ethersphere/bee/issues/3122
