### ISSUE TITLE
Enhancing error messages for duplicate data uploads - SOC

### ISSUE THREAD

**Issue by IgorShadurin** [ethersphere/bee#3655]
#### Summary
The issue is about an error that occurs when a user tries to upload data using the SOC feature for the second time. The error indicates that the data has already been uploaded, but it does not provide the reference of the previously uploaded data. This can be problematic for applications that use the bee API and rely on the reference.

#### Motivation
Providing the reference of the previously uploaded data would allow applications that use the bee API to handle this situation more gracefully. Currently, they have to rely on error messages to detect this situation, which can be error-prone and difficult to handle.

#### Implementation
One possible implementation of this feature would be to include the reference of the previously uploaded data in the error message that is returned when the user tries to upload the same data again. This would allow applications that use the bee API to easily identify the data and handle the error in a more graceful manner.

#### Drawbacks
One potential drawback of this feature is that it may require changes to the existing error messages and the way they are generated. This could potentially cause compatibility issues with existing applications that rely on the current error messages. Additionally, it may require additional development and testing effort to implement and maintain this feature.

**Comment by mrekucci** [comment]
This is no longer a problem, and the HTTP POST call to the `/soc` endpoint is idempotent and returns the same reference when the same calls are repeated.
