### ISSUE TITLE
bee-get-addr does not report address

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#3670]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
1.10.0 ubuntu

### Summary
bee-get-addr does not report address

### Expected behavior
should report address

### Actual behavior
does not report address

### Steps to reproduce
run `bee-get-addr` before or after starting Bee

![Screenshot 2022-12-21 at 07 50 10](https://user-images.githubusercontent.com/130104/208850278-3584d411-bdbe-42d8-9876-1a3890da7d71.png)

**Comment by istae** [comment]
Where does this command exist? Can you point to which repo? We are not sure the bee-team owns this.

**Comment by istae** [comment]
The docs for how to runs this cmd https://docs.ethswarm.org/docs/installation/install
the script is inside the packaging directory in bee.

**Comment by aloknerurkar** [comment]
@NoahMaizels We need to change the docs to ask users not to use this command.

**Comment by istae** [comment]
closing since this cmd is no longer documented.
