### ISSUE TITLE
Enable withdrawals to an address which can only be set once for each node/node-wallet.

### ISSUE THREAD

**Issue by m3rlin5ky** [ethersphere/bee#3676]
#### Summary
Enable withdrawals directly from the node wallet

#### Motivation
Exporting the seed phrase and the password and implement it into e. g. MetaMask is still quite risky.
At the moment there is no simple way to withdraw bzz or xdai to an external wallet.
A new solution could also enable a automatic withdrawal mechanism e.g. if a node would be offline for like 6 month.

#### Implementation
Each node-wallet could deploy one withdrawal contract (only should be allowed) where a specific address is defined (recommended is a hardware wallet or a SAFE multisig address), where withdrawals could get received. It could be seen as predefined/whitelisted withdrawal address e.g. keystorefiles of Ethereum/Gnosis validators have such an approach.

#### Drawbacks
Such an embedded address could not be changed unless a new node would be set-up on the machine.

**Comment by istae** [comment]
A reasonable way to whitelist an address is to set it with a config option.

**Comment by ldeffenb** [comment]
I would support the configuration white-list of an address as this is much easier than running an entirely separate contract just to store one piece of information - the withdrawal-target address.
