### ISSUE TITLE
Remove `ReadMsgWithContext` and `WriteMsgWithContext` utilities

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3677]
After working on #3542 it became apparent that these utility functions have issues and that `bee` would be better off without them. This issue will document what are the problems and propose alternative solution.

**Idea behind these utility methods**
These methods create background goroutine in order to read/write data from/to supplied Reader/Writer. They do read/write operation in the background goroutine because they want to abandon this operation when the supplied context is cancelled. 
 
**Problem: goroutine leaks**
In case when context is terminated the method will return error to the caller but goroutine will be left to perform operation until operation is finished. This clearly is causing goroutine leak as these functions should end all goroutines before returning result to the caller.
 
**Problem: data race issues**
In the same case, when context is terminated, these methods could cause data race issues. Let’s consider following scenario:

```
ctx1 := context.WithDeadile(ctx, time.Second)
data1, err := ReadMsgWithContext(ctx1, reader)

ctx2 := context.WithDeadile(ctx, time.Second)
data2, err := ReadMsgWithContext(ctx2, reader)

```

In case when `ctx1` is closed goroutine will keep reading data from form `reader`, which will be a problem because a few lines below new goroutine will be started to read data from the same `reader`. At this point we have data race conditions because two goroutines are reading from the same `reader`.

Looking at both problems stated above it appears that these utilities don't effectively solve the problem they intend to solve. It’s worth mentioning that in a sealed environment these methods may not cause any issues as 1) goroutine will eventually close and 2) data race issues may never happen if there are no use cases which could reproduce it. However since they pose a danger to the system it worth considering better solution.
 
**Potential solution**

In PR #3542 it was attempted to solve all issues by fixing these methods (keeping this approach), but fixes were unnecessarily complicated and the idea that `bee` would be better off without them made more sense.
 
Another solution would be to avoid using these utilities; and instead close Reader/Writer (or entire Stream) in protocol handler logic when the deadline for processing handler request is reached. This would make more sense because 1) it would be possible to stop Read/Write operation as soon as possible and 2) also other side would not waste processing requests which got terminated

**Comment by vladopajic** [comment]
@notanatol, are `libp2p` upgrades touching this part of code? Have these utilities become obsolete by any chance? 

I am guessing, but if these utilities are still used after `libp2p` is upgraded then `bee` could have issues if context is terminated and then the same stream is reused for another handler. This would be very similar to the data race issue explained above, except that this time it could happen in different protocol handlers.

**Comment by notanatol** [comment]
> @notanatol, are `libp2p` upgrades touching this part of code? Have these utilities become obsolete by any chance?
> 
> I am guessing, but if these utilities are still used after `libp2p` is upgraded then `bee` could have issues if context is terminated and then the same stream is reused for another handler. This would be very similar to the data race issue explained above, except that this time it could happen in different protocol handlers.

no, these methods have not been changed in the scope of the libp2p upgrade work.
