### ISSUE TITLE
Detect errors in pusher

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#369]
>  in the future we should detect when there's a significant amount of errors (i.e. a node is not connected, etc), reset the timer and break out of the iterator subscription, allowing it to wait for the next timer interval (which should probably be higher too).

Coming from PR #368

**Comment by Eknir** [comment]
@acud , made this issue based on you PR description

**Comment by acud** [comment]
Thanks @Eknir :pray:

**Comment by Eknir** [comment]
Seeing this issue now. Could this be a useful enhancement, in the light of the recent issues with the pusher?
