### ISSUE TITLE
LiveSyncWorker sync error and some other bugs

### ISSUE THREAD

**Issue by junyan-zg** [ethersphere/bee#3717]
Bee version: bee-1.11.1.x86_64.rpm

System: Centos7.9

When I run bee(full node) a few hours later(first start or restart will be normal), it would report some bugs, **I am not sure whether it is a software problem or a configuration problem.**

1.`Jan 22 22:19:06 swarm bee[4095]: "time"="2023-01-22 22:19:06.026799" "level"="error" "logger"="node/puller" "msg"="liveSyncWorker sync error" "error"="read offer: stream reset" "peer_address"="6a7d587ecb6277f03656dbf1eb9490b11dfd94a5f94aae171565e00414cdf724" "bin"=19 "from"=1195 "topmost"=0`

2.`Jan 22 22:19:31 swarm bee[4095]: "time"="2023-01-22 22:19:31.279918" "level"="warning" "logger"="node/pushsync" "msg"="forwarder, invalid stamp for chunk" "chunk_address"="684b60b84d1d1c7219f5961bda0f8f7da2bb21a629173ff9274ec14beceb6d67"`

3.`Jan 22 22:20:37 swarm bee[4095]: "time"="2023-01-22 22:20:37.629171" "level"="error" "logger"="node/puller" "msg"="histSyncWorker syncing interval failed" "error"="new stream: send headers: read message: context deadline exceeded" "peer_address"="6bc6ca7c5957ac1e1b435504e01360f171c7a0cd1b88537b15bdae675c254b38" "bin"=12 "cursor"=123461 "start"=31422 "topmost"=0`

4.`Jan 22 22:22:29 swarm bee[4095]: "time"="2023-01-22 22:22:29.625128" "level"="error" "logger"="node/puller" "msg"="recalc peers sync failed" "error"="could not get cursors from peer 6e765729b2f53adaa8c8e3c87d71a83554b457c912afb3cfb3bc63959268a851: new stream: send headers: read message: stream reset" "bin"=12 "peer"="6e765729b2f53adaa8c8e3c87d71a83554b457c912afb3cfb3bc63959268a851"`

On `https://api.swarmscan.io/v1/network/nodes/ethereum/{address}` shows
 `"error":"2 errors occurred:\n\t* connect full close stream reset\n\t* connect full close stream reset\n\n"`

I need someone to help me, thank you!

**Comment by istae** [comment]
these puller error are normal - thanks for reporting :)
We will silence these logs in the next release.
