### ISSUE TITLE
Document tracing

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#373]
Document the `tracing` feature

- Add a more descriptive explanation under `--h`
- Describe how to use tracing under the `develop` section of the `bee-docs`
- [optional] Add a tutorial on how to run Bee with tracing under the `tutorial` section of the `bee-docs`

Add @Eknir as reviewer

**Comment by Eknir** [comment]
`tracing` documented in the bee-documentation. Only `--h` must be more descriptive

**Comment by acud** [comment]
I dont think we need to document tracing so much. If people are familiar with it then fine. It is not meant to be used on the public testnet as once your requests go outside the context of nodes that can report to our tracing backend, you lose the meaningfulness of the trace.

**Comment by Eknir** [comment]
I think it would be good to document, even if the purpose is internal-only. This is, to onboard new developers, but also to facilitate people to start their own Swarm networks.

**Comment by Eknir** [comment]
related: https://github.com/ethersphere/bee/issues/1054
