### ISSUE TITLE
nodes should have a minimum balance to cover transaction fees when entering a new storage incentives round

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3742]
Before playing in a new round, the storage incentives agent should check that the wallet of the node has a minimum balance to cover the upcoming transactions.

One approach:
The minimum balance can be calculated as the current gasPrice * avgTransactionGasUsed * minimumTransactionsToCover where

avgTransactionGasUsed is the avg of the gas of claim, commit, and reveal transactions

and minimumTransactionsToCover is the number of transactions the wallet must be able to cover - the default could be 25.

**Comment by ldeffenb** [comment]
And while we're at it, can we have a configurable "maximum gas price" where a node would opt not to play if the gas price at the start of the round (just before committing) is (arbitrarily according to the node operator) too high?

**Comment by swarmHaseeb** [comment]
@ldeffenb Yes we already have a PR in pipeline for that :)
