### ISSUE TITLE
TestNewStreamMulti is flaky

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#375]
```
=== RUN   TestNewStream
--- PASS: TestNewStream (2.06s)
=== RUN   TestNewStreamMulti
##[error]    TestNewStreamMulti: protocols_test.go:86: handler should have been called but wasnt
--- FAIL: TestNewStreamMulti (4.59s)
=== RUN   TestNewStream_errNotSupported
```

**Comment by acud** [comment]
https://github.com/ethersphere/bee/pull/374/checks?check_run_id=807303628

**Comment by acud** [comment]
@pradovic I saw you added a `FullClose` to the test (although i am not sure this is related to the problem). Did you manage to get the test to flake on your machine, and if yes, did the change solve it?

**Comment by pradovic** [comment]
It was failing for me on a CI until I added full close. My rational is that the reason for the failed test was that counter was checked before it was actually incremented. So the solution was either full close in handlers or expext/wait for the counter in tests.  I thought it might be more correct to synchronise with fullclose.

**Comment by pradovic** [comment]
Let's re-open if it appears again, seems to be fixed.
