### ISSUE TITLE
Fix tracing

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#3795]
Tracing needs fixing because at the moment it's not very useful for investigations and insight.

The problem is that in many cases we mishandle and fail to pass down the span ID from the parent context.

We also don't use `opentracing.FollowsFrom` anywhere, even if this is very useful for cases where we spin off goroutines (like pusher) that we would like to report to a parent span.

Additionally, `pusher.chunksWorker` method is due to an overhaul due to mixing of loggers and unorthodox context handling (ctxLogger func)

# Task
1. Find and fix occurrences in the codebase where the tracing span ID is not passed downstream.
3. (Optionally) make the loggers inherit the span ID so it would show in grafana.

## Acceptance criteria
- An upload chunk can be traced from the originator to the final destination, its spans form a clear hierarchy (both ChildOf and FollowsFrom) and in the case of an error it's clear which peer and for what reason rejected the chunk.
All the relevant logs reference a trace id that allows for easy aggregation and allows to easily associate/relate an action (file upload for ex.) to a collection of logs emitted from several peers.
- We no longer have missing parent IDs:
![Screenshot from 2023-08-30 20-08-12](https://github.com/ethersphere/bee/assets/87016465/14d91350-d8be-46fc-9ad6-7cdc6c594261)

Related: #3784

**Comment by nikipapadatou** [comment]
Because of leaves and other unexpected stuff, we are now considering this as a low priority task. Moving this to backlog and catch it up again probably at the end of hardening phase. Work has been done, but need investigation regarding testing and how it performs.

**Comment by istae** [comment]
As a developer, I can track the trace several requests across all involved nodes.
The requests are:

- [ ] Retrieval. The download API endpoints create a tracing span which is then propagated to all downstream peers that serve the retrieval protocol requests.
- [ ] Pusher: The pusher creates a tracing span, all downstream peers that serve the pushsync protocol requests, all report the same trace.
