### ISSUE TITLE
As a node operator, I want to be more resilient to connection errors, such that I become well-connected

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#38]
Upon starting a bee node, it should connect up to a limit of expected peers. First by checking if there are some present in addressbook, and if addressbook is empty, to connect to provided bootnodes, which should provide node addresses to connect to.

At runtime, nodes can disconnect and in that case, new nodes should be picked from addressbook to connect to.

**Comment by Eknir** [comment]
Hi guys, what is the status of this issue? Are we still working on it, is it blocked?

**Comment by janos** [comment]
This is a bit broad epic and @pradovic recently finished PR that is related to this epic, beside other related already merged. I think that this Epic can be closed as bee is now performing what is stated in the description. Limiting the number of peers will come with the current kademlia work.
