### ISSUE TITLE
Claim interface changes: creation of proofs

### ISSUE THREAD

**Issue by ct-ctrl** [ethersphere/bee#3800]
If the node is participating in a round (it has commit/revealed), it checks whether it is the selected winner at the beginning of the claim phase (by the same accessor as before). Overall the claimant must submit evidence which will be verified to show that as a rightful winner it does store all relevant content. Beyond consensus in the Schelling game this provides assurrance that winners do what the network needs them to do even though the claimant may

be the only one to play,
an opportunistic participant, not aspiring to consensus just hoping to get selected as truth
have bribed their neighbours into collusion
Witness chunk and witness segment selection
The winner uses a new accessor function (SSN), which returns the segment selection nonces. These nonces determine which chunks of the reserve sample should be used as witness and which segments of the witness chunks should testify to the integrity of data with the help of inclusion proofs.

The data that is being used to produce these witnesses must be persisted throughout the reveal phase until a potential claim.

Firstly, two random witness chunks are selected from the sample. This boils down to first defining a Segment Selection Nonce for game g and two parameters i and j

SSN(g,i,j) = H(R(g)|BE_8(i)|BE_8(j))

this call is from bee to the cotnrct and takes current nonce/seed and calls contract for validation.

if the last 32byte of the sample chunk is the transformed address of the last element if it’s bigger than the higher value then you cannot testify to this. therefore the claim will be invalid.

Since each chunk in the sample have both their address as well as transformed address (2 segments) within the data of the reserve sample chunk, proving the segment at 2i is needed.
Incidentally the first sister in the proof will be the transformed address of the chunk.

then calculate JK i.e. the 3 indexes for retention proof segment (see solution doc section for this)
https://hackmd.io/C7EvRbghQpWr9UXiGOFgLQ?view

**Comment by nikipapadatou** [comment]
Closing this as part of ph4.
