### ISSUE TITLE
enable paralleltest lint check

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3818]
In the commit af3ba87 `paralleltest` lint check was disabled for entire repository. Instead of disabling it for entire repository it should be disabled only for specific folders.

**Comment by aloknerurkar** [comment]
So this is done on purpose. There is no point maintaining this list of packages to exclude the paralleltest. Instead the check used here is a more lenient one as it only checks for correct usage and doesnt make it compulsory. There are tests in this package which will not be rewritten for parallel test usecase.

**Comment by istae** [comment]
@martinconic parallelized all applicable tests
