### ISSUE TITLE
pushsync - too many "adding peer to skiplist"

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3819]
### Context
bee 1.12.0 mainnet

### Summary
My pusher node seems to be logging a lot of "adding peer to skiplist" from node/pushsync.   These seem to be invalid since there are no subsequent "could not push to peer" messages.

### Expected behavior
If a push is successful, it should not be added to the skiplist.

### Actual behavior
Lots of peers being added to the skiplist, according to the logs.

### Steps to reproduce
Just enable debug logging on a pusher node and watch the logs.

### Possible solution
It seems that the !errors.Is() check at https://github.com/ethersphere/bee/blob/ecfedd4c6275065d4b7016d8cf95613dad1ca984/pkg/pushsync/pushsync.go#L455 should actually be below the result.err == nil.   Nodes are likely being added to the skiplist when they actually succeed in pushing a chunk?

In fact, I suspect the result.err == nil check (https://github.com/ethersphere/bee/blob/ecfedd4c6275065d4b7016d8cf95613dad1ca984/pkg/pushsync/pushsync.go#L461) should be first after the ps.measurePushPeer to save other error checks on a successful push.

**Comment by istae** [comment]
we add the peer to the skiplist even if the push is successful, because the pusher might not be happy with receipt, eg receipt depth is below the storage radius so we retry with a new peer.

ideally, pushsync should detect that the receipt is shallow, so it should just internally retry again

**Comment by ldeffenb** [comment]
So this skiplist is actually by chunk and peer, not just the peer.   On reading the code more closely, I see this.   But I wonder if the log message should clarify if the skiplist addition was for success or for an error?

**Comment by istae** [comment]
Yes, the skiplist is by peer and chunk, and for better log messages, PRs are welcome!
