### ISSUE TITLE
enable paralleltest lint check in `pkg/postage`

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3831]
Currently `pkg/postage` has disabled `paralleltest` lint check (see `golangci.yaml` file). This check should be enabled for this package and tests should be corrected to use `t.Parallel()`.

Acceptance criteria:
- enable `paralleltest` lint check in  `pkg/postage`
  - all tests should use `t.Parallel()`; if tests for some reason could not use `t.Parallel()` then it disabling lint check per tests case should be alright
- all tests should pass 
- there should be no lint errors

**Comment by emekaokoli19** [comment]
@vladopajic From what I understand, the issue here is to add t.parallel() to the test functions in pkg/postage right?
Also, how do I enable paralleltest for pkg/postage? Do I make changes to the golangci.yml file?

**Comment by vladopajic** [comment]
You are right on everything :)
