### ISSUE TITLE
new documentation for how to use the loggers API

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3845]

**Comment by istae** [comment]
related #3784

**Comment by aloknerurkar** [comment]
@NoahMaizels Can you try to add this to bee docs using @mrekucci s help.

**Comment by nikipapadatou** [comment]
cc @NoahMaizels to sync with @mrekucci regarding this.

**Comment by mrekucci** [comment]
The logger API usage section was added to the CODING.md (#4406) and the swarm doc will be updated by @NoahMaizels.
