### ISSUE TITLE
/redistributionstate lastPlayedRound off-by-one

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#3850]
### Context
mainnet 1.12.0+

### Summary
My node won the last round that it played, but the /redistributionstate's lastPlayedRound is one less than the (correct) lastWonRound.

```
  "isFrozen": false,
  "isFullySynced": true,
  "phase": "reveal",
  "round": 175611,
  "lastWonRound": 175369,
  "lastPlayedRound": 175368,
  "lastFrozenRound": 0,
  "block": 26692911,
  "reward": "10246290407424000",
  "fees": "20343529360500000"
```

### Expected behavior
I would expect the lastPlayedRound to always be >= lastWonRound.

### Actual behavior
```
  "isFrozen": false,
  "isFullySynced": true,
  "phase": "reveal",
  "round": 175611,
  "lastWonRound": 175369,
  "lastPlayedRound": 175368,
  "lastFrozenRound": 0,
  "block": 26692911,
  "reward": "10246290407424000",
  "fees": "20343529360500000"
```

### Steps to reproduce
Check the /redistributionstate API output on a node that won the last round played.   Or even notice that the lastPlayedRound is actually one less than the round that the node committed and revealed.

### Possible solution
I'm guessing that the lastPlayedRound is being picked up during the claim phase of the previous round when the node begins calculating the reserve hash (aka "starts playing"), but the actual round number that should be captured is the next round which increments at the end of claim and beginning of commit which is the actual round being played.

**Comment by vladopajic** [comment]
@ldeffenb could you confirm if this is still happening in v1.15.0?

**Comment by ldeffenb** [comment]
Yes, this is still happening on 1.15.   The output just now from one of my staked nodes:
{
  "minimumFunds": "18750000000000000",
  "hasSufficientFunds": true,
  "isFrozen": false,
  "isFullySynced": false,
  "phase": "claim",
  "round": 183317,
  "lastWonRound": 183291,
  "lastPlayedRound": 183290,
  "lastFrozenRound": 182326,
  "block": 27864261,
  "reward": "378811176714240000",
  "fees": "115269532552000000"
}
