### ISSUE TITLE
uploads with mutable batches should only override chunks on index collision if a header is specified

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3889]

**Comment by aloknerurkar** [comment]
We can make the immutable stamps the default purchase. If the user is fine with losing data, they can use mutable flags.

**Comment by nikipapadatou** [comment]
Once it is out, it needs to be communicated to the communicated. It chancges the API in any of the two solutions and the default behaviour.

**Comment by istae** [comment]
default batch type is now immutable.
