### ISSUE TITLE
networkAvailability is "unknown" for all mainnet nodes

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3890]

**Comment by istae** [comment]
"blocklisting peer when network not available" error logs are seen quite often and they stem from networkAvailability being in unknown state

**Comment by notanatol** [comment]
@mrekucci we worked on this module a while ago, let's review it sometime soon?

**Comment by mrekucci** [comment]
> "blocklisting peer when network not available" error logs are seen quite often and they stem from networkAvailability being in unknown state

This error is returned by the `Blocklist` call when a caller tries to blocklist a peer when the network is not available: https://github.com/ethersphere/bee/blob/master/pkg/p2p/libp2p/libp2p.go#L668
