### ISSUE TITLE
Runtime change of welcome message

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#391]
#246 implemented the possibility to set a welcome message for your node. Right now, the welcome message can only be set upon startup, but it must also be possible to set this at run time. The architecture setting a parameter at startup and at run time will be used by other configurations as well.

**Comment by paxthemax** [comment]
@Eknir can we discuss in a bit more detail what does "set at run time" actually entail? My initial understanding is that there would be a debug API call that would be used to set the new value of the welcome message?

Also, there was mention of a countdown style dynamic welcome message that would change based on the number of hits (handshakes)? I assume this task does not require that feature?

**Comment by paxthemax** [comment]
I would propose to create a generic endpoint on the debug API for basic CRUD operations on a KV store. The welcome message would use specified key (`welcome-message` or something similar) to read in this value dynamically.

This way we can have a sort of a multi-purpose dynamic registry on the bee node that we can use in other features as well.

**Comment by Eknir** [comment]
> My initial understanding is that there would be a debug API call that would be used to set the new value of the welcome message?

Exactly.

>  I assume this task does not require that feature?

Indeed. You may forget about this for now :)

Reach out to me if any more questions!

**Comment by Eknir** [comment]
> I would propose to create a generic endpoint on the debug API for basic CRUD operations on a KV store. The welcome message would use specified key (welcome-message or something similar) to read in this value dynamically.

This way we can have a sort of a multi-purpose dynamic registry on the bee node that we can use in other features as well.

Sounds good to me, but I'm not the person for technical details like these. @janos is ;)

**Comment by janos** [comment]
I would like to mention that configuration library that we use https://github.com/spf13/viper, provides another way to update the configuration, by using external configuration managers, like etcd or Consul. It would be nice to consider them in extending the configuration handling at runtime.

Of course, Debug API endpoint would be most direct way to set configuration parameters at runtime and we should have that.

Our components are not made reactive to configuration change, but that is not a problem, it just brings additional complexity that we should handle. Welcome message change is a good for trying out what would be the best approach.
