### ISSUE TITLE
Bootnodes receive unexpected requests

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#3945]
### Context
bee `v1.13.0` although this behaviour has been observed in earlier versions as well. 

### Summary
Bootnodes are receiving requests that they can't satisfy as light nodes. 

```
"time"="2023-03-28 18:45:34.059154" "level"="debug" "logger"="node/libp2p" "msg"="handle protocol failed" "traceID"="613a2cdff3d70430" "protocol"="retrieval" "version"="1.3.0" "stream"="retrieval" "peer"="0b79d15cf889d5fa758e3a3cc665041f0547b97a117fe0d085435f4dd344a60c" "error"="unexpected request while in light mode"
```

### Expected behavior
Bootnodes should NOT be receiving retrieval requests.

**Comment by istae** [comment]
the kademlia peer selection functions like ClosestPeers or the iterator do not care about the type of nodes they return.
the retry mechanism should try another peer so this is ok.
