### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by davidhq** [ethersphere/bee#396]
Simplest possible pull request:

https://github.com/ethersphere/bee/pull/395

But automatic tests don't pass, so something is broken.

```
Run failed for master (81dc9b0)
Repository: ethersphere/bee
Workflow: Coverage
Duration: 1 minute and 48.0 seconds
Finished: 2020-06-29 18:35:13 UTC

View results

Jobs:
coverage failed (1 annotation)
—
You are receiving this because this workflow ran on your branch.
Manage your GitHub Actions notifications here.
```

Links to problem:
https://github.com/ethersphere/bee/runs/819592642
https://github.com/ethersphere/bee/actions/runs/151814431

**Comment by acud** [comment]
Hi, thanks for reporting this. Actually the tests are not broken, its just that our static analysis tool does not work when PRing from private repos.
