### ISSUE TITLE
mechanism for pausing/resuming storage incentives game

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#3960]
**Problem**
Node operators can potentially experience penalties in cases when their node is currently participating in storage incentives game and they are doing maintenance on their infra (bee node upgrades, or anything else causing downtime of bee node).

In order for them to gracefully perform maintenance bee node needs to have mechanism for pausing storage incentives game. Additionally node operator would need to be able to know when game has paused.

**Solution 1** (mechanism just for storage incentives)
- Add API endpoint for pausing and resuming storage incentives
- Extend `GET redistributionstate` endpoint with information about current running status of storage incentives

**Solution 2** (scaled solution for any component of bee)
Assuming that node operators need to gracefully terminate their nodes, it might be worthwhile to implement mechanism which will not only stop storage incentives, but also other components/features of node. Compared to approach in solution 1, this solution should be generalized. 
 
- Add API endpoint for gracefully stop node, this endpoint should stop all components of node
  - endpoint example `/POST /api/node/stop`
  - for beginning this endpoint should only pause storage incentives agent
  - later, this endpoint could be used to gracefully end other components of node:
     - since node is about to be terminated node could be marked as scheduled for termination so other nodes could take up it's spot in the neighborhood?
     - stop serving any new requests for push sync protocol ?
  - possibly terminate node process after everything has stopped? have this feature controlled via request?

**Comment by nikipapadatou** [comment]
@mrekucci 
* Make sure there is sufficient logging about rounds. To be improved if needed.
* Document that upgrading nodes should be outside the reveal phase.

**Comment by istae** [comment]
waiting on noah to finish up the docs before we can close this

**Comment by NoahMaizels** [comment]
Added warnings to docs explaining that nodes should not be shut down during a round the node is playing or else they can get frozen:

https://docs.ethswarm.org/docs/bee/working-with-bee/upgrading-bee
https://docs.ethswarm.org/docs/bee/working-with-bee/staking#check-redistribution-status
