### ISSUE TITLE
node does not shutdown gracefully on ctrl+C

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#3962]
When you hit ctrl c the node does not go through the normal procedure of closing running services. 
It immediately terminates the process.

**Comment by vladopajic** [comment]
This could only be the case when node was not initialized. Because it would not be possible to call .Stop() method on object which was not full created.

**Comment by aloknerurkar** [comment]
This could be specific to windows.

**Comment by nikipapadatou** [comment]
Probably this issue may not be relevant anymore. Checking it on this sprint.

**Comment by nikipapadatou** [comment]
closing this as it is not relevant anymore
