### ISSUE TITLE
Label minimumFunds too abstract

### ISSUE THREAD

**Issue by mfw78** [ethersphere/bee#4003]
**Problem**

The `API` labels should convey enough meaning so that users can infer basic understanding.

**Solution**

Label `minimumFunds` with the _specific_ funds that this is a minimum for. On the basis that this relates to the minimum funds for gas expenses, perhaps: `minimumNativeFunds` or `minimumGasFunds`.

Refer: https://github.com/ethersphere/bee/blob/e1320fa47e9afbed1282cca4cb12828f0289a94d/openapi/SwarmCommon.yaml#L700

**Comment by ldeffenb** [comment]
Just to cast a vote, "minimumGasFunds" is more clear for me!

**Comment by attila-lendvai** [comment]
FWIW, i was also confused by `lastPlayedRound`: i thought it meant last round when the node participated in the redistribution game, as opposed to the round when the node's enighborhood was actually selected.
