### ISSUE TITLE
Add API to retrieve resource info from hash without download it

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#4025]
#### Summary
Add an API that will try to retrieve resource info from an hash, without need to download it.
Something similar to an "HEAD" request (that currently on `/bzz` returns 405 error) but with following information:

- total byte size on disk of it and all its sub-resources if it is a manifest
- resource type: (content or feed-manifest). This helps to understand if it is a dynamic or static content

#### Motivation
Node administration can need information about managed resources, without have to real access them.

#### Implementation
It could be a new dedicated API.

#### Drawbacks
Don't see any.

**Comment by darkobas2** [comment]
I think head request approach mentioned would be a correct way. My use case would be implementing proper server side caching which could check head for etag information for refreshing cache.
