### ISSUE TITLE
docs for pausing/resuming storage incentives game

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#4029]
After #3960 gets implemented docs should be updated to add necessary explanation of how stopping and starting should work.

After docs are created, node operators should be informed with this docs.

**Comment by NoahMaizels** [comment]
Added warnings to docs explaining that nodes should not be shut down during a round the node is playing or else they can get frozen:

https://docs.ethswarm.org/docs/bee/working-with-bee/upgrading-bee
https://docs.ethswarm.org/docs/bee/working-with-bee/staking#check-redistribution-status
