### ISSUE TITLE
Stream closing, synchronisation & handling errors

### ISSUE THREAD

**Issue by pradovic** [ethersphere/bee#403]
Libp2p appears not to clean-up streams unless the stream is closed for both write and read: https://github.com/libp2p/go-libp2p/blob/master/NEWS.md.

We are currently relying on `stream.Close()` to close one side of the stream, but don't check if the other side is closed, always. This can result in a half-closed stream in a case of an error. The quick fix is to use `FullClose()` which will reset the stream on timeout, if other side did not close the stream.

This means that in order for stream to be cleaned up, one of the following must happen:
- Stream must be closed by both sending and receiving side. There is no way to know this unless we wait for other side to close the stream,
- If any error appears the stream should be reset, so it is closed for both writing and reading

In order to achieve this we should reset streams on errors, and this is already part of `helpers.FullClose()`. Taking the example of https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go, we can do the following:
- On the calling side, the one that creates the stream, we can call `FullClose()` in a separate goroutine, possibly hanging until the timeout, and resetting the stream in a case of timeout or error. This is done in a separate goroutine in order to not the block the caller, because maybe we don't actually care if the stream was reset or closed.
- On the handler side, there is not need for a separate gouroutine, as this is already a path that was initiated in the goroutine that initiates the handler

Handling errors:
This way we will reset the stream if the other side does not close the stream, but still we don't have a way to know that the error actually happened. The next step would be to introduce stream.Reset() on errors. 

So, addressing these issues should:
- Improve performance in some cases, where error cases was not handled and the timeout was induced
- Improve correctness, signal errors and synchronize between peers where needed
- Solve zombie thread problem described above

This will be addressed in multiple PRs, going protocol by protocol. The first batch of PRs should use `FullClose()` & `Close()` combinations more properly, and the second batch should introduce usage of `stream.Reset()` if needed.

PRs:
https://github.com/ethersphere/bee/pull/401 - merged
https://github.com/ethersphere/bee/pull/405 - merged
https://github.com/ethersphere/bee/pull/407 - merged
https://github.com/ethersphere/bee/pull/419 - merged
https://github.com/ethersphere/bee/pull/420 - merged
https://github.com/ethersphere/bee/pull/421 - merged
https://github.com/ethersphere/bee/pull/422 - merged
https://github.com/ethersphere/bee/pull/428 - merged
https://github.com/ethersphere/bee/pull/449 - merged

**Comment by Eknir** [comment]
Very well documented issue @pradovic . Thanks!

**Comment by Eknir** [comment]
Closing this issue, as all is merged. Well done guys!
