### ISSUE TITLE
feature request: `bee start` should start a new ultralight node without any further configuration

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#4032]
#### Summary
it would be great for user experience if `bee start` started up an ultralight node without any further config.

this simply the following default options 

```
swap-enable: false
debug-api-enable:true
debug-api-addr: 127.0.0.1:1635
```

the debug api is set to be functioning, but only bound to localhost, preventing outside connections.

**Comment by rampall** [comment]
tangentially related #3756

**Comment by quinton11** [comment]
will love to pick this up if its still open

**Comment by mrekucci** [comment]
Duplicate of #4114
