### ISSUE TITLE
A `report` debug endpoint that collects all key metrics for troubleshooting  / support

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4058]
#### Summary
a special debug endpoint for collecting key metrics for support / troubleshooting

#### Motivation
when node operators face issues, and come to discord for support - we ask them for their setup, os, what A endpoint output is what B endopint output is etc. It would be easier to have a single `report` endpoint where all important troubleshooting data from various other debug endpoints can be pulled and presented to streamline this process.

#### Implementation
some data that is often requested by tech support on discord to identify or troubleshoot issues are:
- `hasSufficientFunds`  
- `isFullySynced`
- `depth`
- `reachability`
- `radius`
- `storageRadius`
... etc
from some of the more common endpoints:
- /health
- /topology
- /status
- /reservestate
- /redistributionstate
etc

config file and data-dir locationd based on the type of setup would be useful too

**Comment by aloknerurkar** [comment]
This can be done externally by writing a script which queries all the endpoints and generates a report. This is already done in the integration tests where we collect all the endpoint data to debug.

Can you share more info on why this is needed?

**Comment by rampall** [comment]
Yeah, a script would work too. 

I have a custom script that does this which i use for troubleshooting - but it pulls just some of the key parameters from some debug api endpoints.  I could turn that into a npx script for this purpose.
