### ISSUE TITLE
Race tests fail in CI

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#406]
WARNING: DATA RACE
Write at 0x00c0001d4870 by goroutine 249:
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*baseFlowController).AddBytesRead()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/flowcontrol/base_flow_controller.go:73 +0xfc
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*streamFlowController).AddBytesRead()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/flowcontrol/stream_flow_controller.go:93 +0x48
  github.com/lucas-clemente/quic-go.(*receiveStream).readImpl()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/receive_stream.go:176 +0x8de
  github.com/lucas-clemente/quic-go.(*receiveStream).Read()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/receive_stream.go:83 +0x79
  github.com/lucas-clemente/quic-go.(*stream).Read()
      <autogenerated>:1 +0x69
  github.com/libp2p/go-libp2p-quic-transport.(*stream).Read()
      <autogenerated>:1 +0x87
  github.com/libp2p/go-libp2p-swarm.(*Stream).Read()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_stream.go:64 +0x92
  github.com/multiformats/go-multistream.(*lazyServerConn).Read()
      /home/runner/go/pkg/mod/github.com/multiformats/go-multistream@v0.1.0/lazyServer.go:32 +0xa7
  github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.5.1/p2p/host/basic/basic_host.go:804 +0x77
  github.com/libp2p/go-libp2p-core/helpers.AwaitEOF()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.3.0/helpers/stream.go:46 +0x125
  github.com/libp2p/go-libp2p-core/helpers.FullClose()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-core@v0.3.0/helpers/stream.go:30 +0xaa
  github.com/ethersphere/bee/pkg/p2p/libp2p.New.func2()
      /home/runner/work/bee/bee/pkg/p2p/libp2p/libp2p.go:231 +0x8e7
  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandlerMatch.func1()
/home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.5.1/p2p/host/basic/basic_host.go:411 +0xb4

Previous read at 0x00c0001d4870 by goroutine 221:
  github.com/lucas-clemente/quic-go/internal/flowcontrol.(*streamFlowController).Abandon()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/internal/flowcontrol/stream_flow_controller.go:99 +0x5d
  github.com/lucas-clemente/quic-go.(*receiveStream).CancelRead()
      /home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.14.1/receive_stream.go:204 +0xb9
  github.com/lucas-clemente/quic-go.(*stream).CancelRead()
      <autogenerated>:1 +0x4d
  github.com/libp2p/go-libp2p-quic-transport.(*stream).Reset()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-quic-transport@v0.2.2/stream.go:16 +0x5d
  github.com/libp2p/go-libp2p-swarm.(*Stream).Reset()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_stream.go:116 +0x54
  github.com/libp2p/go-libp2p-swarm.(*Conn).doClose()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:66 +0x1cc
  github.com/libp2p/go-libp2p-swarm.(*Conn).doClose-fm()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:52 +0x41
  sync.(*Once).doSlow()
      /opt/hostedtoolcache/go/1.14.4/x64/src/sync/once.go:66 +0x103
  sync.(*Once).Do()
      /opt/hostedtoolcache/go/1.14.4/x64/src/sync/once.go:57 +0x68
  github.com/libp2p/go-libp2p-swarm.(*Conn).Close()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:48 +0x65
  github.com/libp2p/go-libp2p-swarm.(*Conn).start.func1()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:100 +0x19b

Goroutine 249 (running) created at:
  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.5.1/p2p/host/basic/basic_host.go:295 +0x86b
  github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler-fm()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p@v0.5.1/p2p/host/basic/basic_host.go:252 +0x55
  github.com/libp2p/go-libp2p-swarm.(*Conn).start.func1.1()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:116 +0x11e

Goroutine 221 (finished) created at:
  github.com/libp2p/go-libp2p-swarm.(*Conn).start()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:93 +0x4c
  github.com/libp2p/go-libp2p-swarm.(*Swarm).addConn()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm.go:237 +0x5c7
  github.com/libp2p/go-libp2p-swarm.(*Swarm).AddListenAddr.func2.2()
      /home/runner/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_listen.go:91 +0xaf

##[error]    TestConnectDisconnectOnAllAddresses: testing.go:906: race detected during execution of test

**Comment by jmozah** [comment]
@pradovic  @janos i found this in CI when i was running CI for my PR. Looks like something related to libp2p.  Please assign to whoever wants to pick it up.

**Comment by pradovic** [comment]
Might be my pr yesterday, I will take   check. Thanks!

**Comment by janos** [comment]
As this is the valid race it happens in the quic transport that we have now disabled by default. @jmozah could you provide more information which version of the code produced this? It looks to me that the PR does not contain recent changes from master, which also updated the quic module.

**Comment by jmozah** [comment]
i am not very sure about the version.... it might be the` fix-tags` branch which is merged with master.

**Comment by janos** [comment]
@jmozah please, provide information in the future for others to try reproduce issues like this. It is only left to do forensics based on the description you provided. And in this case it shows that quic transport is used and caused this, which was disabled on master at the time of this issue report.
