### ISSUE TITLE
`bee` logs warning when `clef` is not enabled

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4074]
If `clef` is not expected/intended to be enabled or running, it might be best to remove this warning (or modified it to sound less alarming from a DX pov).

https://github.com/ethersphere/bee/blob/8292bfc4e174143fab3ad36bccf0719c1bdfc712/cmd/bee/cmd/start.go#L468

![image](https://github.com/ethersphere/bee/assets/520570/2b4b5fcf-7543-49f0-9537-5ec1d4d86e71)

**Comment by istae** [comment]
Related #4100
