### ISSUE TITLE
Add `immutable` to `Access-Control-Allow-Headers` so postage batch mutability can be set

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#4079]
Currently a CORS error:

Request header field immutable is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by mrekucci** [comment]
Have you set `cors-allowed-origins` in the configuration?

**Comment by Cafe137** [comment]
Yes. Other requests work fine.
IMO the `immutable` option has not been added here: https://github.com/ethersphere/bee/blob/8292bfc4e174143fab3ad36bccf0719c1bdfc712/pkg/api/api.go#L650
