### ISSUE TITLE
Beekeeper parallel dynamic retrieval cluster file download check

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#409]
This check is a more complex variant of dynamic retrieval cluster file download check https://github.com/ethersphere/bee/issues/408.

There should be a number (configurable) of goroutines which would upload and download files concurrently and a goroutine that would periodically add, remove or bring back already removed nodes randomly selected within some percentage (configurable) of the total count.

1. start an initial number (configurable) of bee nodes
2. start a number (configurable) of gorutines that would upload and download files
3. start a goroutine that would manage the nodes (add, remove or bring back removed)

Upload/download goroutines:

1. upload a file to one random node
2. check that that file can be downloaded from a number (configurable) of different random nodes
3. wait for some random time up to the certain limit (configurable)
4. go back to step 1.

Node manager goroutine:

1. randomly add, remove or bring back already removed nodes within some percentage (configurable) of total nodes
2. wait for some random time up to the certain limit (configurable)
3. go back to step 1.

One problem is that it may happen that a node may be removed while trying to download from or to upload to it. This case should be handled and not reported as the failure.

There is a complexity maintaining the list of active nodes which should be handled without data races.

I am suggesting these options for this check:

- initial number of nodes
- number of parallel upload/download goroutines
- file size
- number of nodes to download from
- maximal time to wait between upload/download iterations
- maximal time to wait between node manager iterations
- number of total upload/download iterations or to run indefinitely as the long running test

This check should provide metrics (similar to the retrieval metrics):

- time for file to be uploaded
- time for file to be downloaded
- download failure counter

This check should provide metrics (similar to the retrieval metrics):

- time for file to be uploaded
- time for file to be downloaded
- download failure counter

Additionally, an alert for download failures may be added as suggested by @vandot.

This check contains some complexity and its nature is to be closer to the real world situation, so if you find that some adjustments would be beneficial for the reality part or that some technical aspects can be much better, feel free to adjust the check specifications.

**Comment by Eknir** [comment]
Hi guys, this issue is `on hold` for some months now. Is this status still up-to-date?

**Comment by svetomir** [comment]
> Hi guys, this issue is `on hold` for some months now. Is this status still up-to-date?
> @svetomir @janos @vandot 

It is. We'll proceed with it, one k8s api is fully integrated.
