### ISSUE TITLE
unstaked node prints "VM execution error" in the logs

### ISSUE THREAD

**Issue by attila-lendvai** [ethersphere/bee#4099]
### Context
v1.6.0
without Clef
2 recently initialized nodes (about a week ago), in the same environment (on Guix, with my [service code](https://github.com/attila-lendvai/guix-crypto))
only one exhibits the issue

### Summary

i'm getting these in the node's log:

```
2023-05-23 12:24:19 "time"="2023-05-23 12:24:19.643306" "level"="error" "logger"="node/storageincentives" "msg"="phase failed" "error"="IsPlaying: overlay 0x1df20d27685a7ee5b792fd1976681f8d0f91d112d2265473e9ffec69d5c025e8 depth 8: VM execution error." "phase"="sample" "round"=184782
```

```
$ curl -s -X GET http://localhost:1800/redistributionstate | jq
{
  "minimumFunds": "246986249975000000",
  "hasSufficientFunds": true,
  "isFrozen": false,
  "isFullySynced": true,
  "phase": "claim",
  "round": 184888,
  "lastWonRound": 0,
  "lastPlayedRound": 0,
  "lastFrozenRound": 0,
  "block": 28103053,
  "reward": "0",
  "fees": "0"
}
```

i have another node in the very same environment, and that has been playing and even won some rounds:

```
$ curl -s -X GET http://localhost:1801/redistributionstate | jq
{
  "minimumFunds": "258125000000000000",
  "hasSufficientFunds": true,
  "isFrozen": false,
  "isFullySynced": true,
  "phase": "claim",
  "round": 184888,
  "lastWonRound": 184752,
  "lastPlayedRound": 184752,
  "lastFrozenRound": 0,
  "block": 28103055,
  "reward": "61454589886464000",
  "fees": "14220899994500000"
}
```

```
$ grep "VM execution error" /var/log/swarm/mainnet/bee-0.log | wc -l
108
$ grep "VM execution error" /var/log/swarm/mainnet/bee-1.log | wc -l
0
```

### Expected behavior

unstaked nodes should either not print anything, or print something that suggests what the situation is.

"VM execution error" is both alarming, and doesn't give any hint about what the original issue is.

**Comment by attila-lendvai** [comment]
i have just realized that the staking amount for this node was 0 when i reported this issue.

i have staked on it just now.

**Comment by ldeffenb** [comment]
Given that revelation, I'd say this issue is done.   Closing it.

**Comment by attila-lendvai** [comment]
@ldeffenb makes sense, but the fact that this is written in the log does not.

1. why would it attemt to participate if it's not staked?
2. even if it would attempt, it should print a more meaningful message.

**Comment by ldeffenb** [comment]
If your config has storage-incentives-enable: true (which is the default), then your node will attempt to play.  But if it has not been staked, then the attempt to play will fail due to the lack of stake.   As far as I can see, the error logs are appropriate given the lack of stake in a (likely) storage-incentives-enabled node.

Sure, it might be nice if it actually said "insufficient stake" or something like that, but from what I've seen, it seems to be difficult to get clear failure reasons back from the contract methods.

**Comment by ldeffenb** [comment]
If you look at the redistribution contract method linked below, you'll see that it does check the stake and returns a suitable error.  But I suspect this error is turning into a "VM execution error" on its way from the RPC to the bee node code.

https://github.com/ethersphere/storage-incentives/blob/e97ec1033843dbd373857597332e43dfc209806c/src/Redistribution.sol#L502

**Comment by attila-lendvai** [comment]
if it's too much trouble to propagate the proper error message, then maybe we could add a hint to the log message?

**Comment by mrekucci** [comment]
@attila-lendvai is this still relevant, do you see this type of error in the v1.17.3?

**Comment by attila-lendvai** [comment]
@mrekucci yes. just start up a node without staking (and without any xBZZ, although not sure if this matters).

```
2023-09-08 22:14:34 "time"="2023-09-08 22:14:34.535168" "level"="error" "logger"="node/storageincentives" "msg"="phase failed" "error"="IsPlaying: overlay 0x[hash] depth 9: VM execution error." "phase"="sample" "round"=196559
```

**Comment by attila-lendvai** [comment]
@mrekucci you probably need to wait until the node is fully synced and attempts to participate in the game.

**Comment by mrekucci** [comment]
> @mrekucci you probably need to wait until the node is fully synced and attempts to participate in the game.

bee/. (master)  > curl -s -X GET http://localhost:1635/redistributionstate | jq
{
  "minimumGasFunds": "4136250000",
  "hasSufficientFunds": true,
  "isFrozen": false,
  "isFullySynced": true,
  "phase": "claim",
  "round": 63652,
  "lastWonRound": 0,
  "lastPlayedRound": 0,
  "lastFrozenRound": 0,
  "lastSelectedRound": 0,
  "lastSampleDuration": 0,
  "block": 9675214,
  "reward": "0",
  "fees": "0",
  "isHealthy": true
}

**Comment by attila-lendvai** [comment]
i can't easily try master. let's see if the next release gets rid of these.

not sure if this matters, but i also have `swap-initial-deposit 0`.

**Comment by mrekucci** [comment]
@attila-lendvai finally managed to simulate the error. Thanks to some recent fixes and updates of the go-ethereum module, the error message in the log now has more context: `"time"="2023-09-11 19:03:53.546328" "level"="error" "logger"="node/storageincentives" "msg"="phase failed" "error"="IsPlaying: overlay 0x4e49927929cc65e0eca4d159a809784bb0440773f6ec8a09e99d3a2a8e139e5b depth 3: execution reverted: stake amount does not meet minimum" "phase"="sample" "round"=63655` Is that acceptable in order to bring closure to this issue?

**Comment by attila-lendvai** [comment]
@mrekucci that depends what you're aiming for. it's still an `error` log, while it's something that can be safely ignored, i.e. it's not an error, but at most a warning, but probably even lower.

i'm not going to complain if it's closed as it is now, but it's a good example of https://github.com/ethersphere/bee/issues/4122 (confusing log categories).

to be sure, i've copied over this log there as an example, so feel free to close this one.

**Comment by mrekucci** [comment]
> @mrekucci that depends what you're aiming for. it's still an `error` log, while it's something that can be safely ignored, i.e. it's not an error, but at most a warning, but probably even lower.
> 
> i'm not going to complain if it's closed as it is now, but it's a good example of #4122 (confusing log categories).
> 
> closing this one as i've copied over this log to the other issue as an example.

Thanks, the severity will be handled in this PR #4122
