### ISSUE TITLE
Error 500 withdrawing stake

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#4106]
### Context
Bee 1.16.1 running on docker and staking.

### Summary
Trying to withdraw stake I receive `{"code":500,"message":"cannot withdraw stake"}`.

### Expected behavior
It should withdraw as required.

### Actual behavior
Error is returned and operation is not performed.

### Steps to reproduce
Don't sure if is enough, anyway try to stake (currently I'm in with "500000000000000000" PLUR), and after a while try to unstake.

### Possible solution
Don't know.

**Comment by istae** [comment]
stakes are only withdrawable when the contract is paused, generally due to when there is a switch to a new contract (which happens very rarely).

**Comment by tmm360** [comment]
@istae I suppose this is still a missing feature, because it should be possible to unstake at any moment. In my case I has to migrate some nodes, and old addresses are now switch off. I've lost their stakes (not a big issue, small amount, but...)

**Comment by istae** [comment]
not being possible to unstake at any moment is part of the design
maybe @ct-ctrl can have some input here
