### ISSUE TITLE
Stewardship PUT API requires stamp

### ISSUE THREAD

**Issue by aloknerurkar** [ethersphere/bee#4128]
With the new storage layer, the download of chunks no longer retrieves the stamps for the chunks. This is because when downloading content, we dont really care about stamps. The stamps could be expired but the chunks could be part of cache of some nodes.

The only place where we use this is in `PUT /stewardship`. The stewardship PUT is used to reupload content on the network. This is mainly useful if you have pinned content that may not be retrievable for some reason. So now, in order to reupload, user will have to provide a stamp to use. The node remembers stamps now, so if user uses the same stamp and it is valid, all the chunks should be stamped with the same indexes and reuploaded.

The user can also use a different stamp, in which case new indexes will be used for the chunks. This allows more flexibility for users as well.

**Comment by ldeffenb** [comment]
What is the "Reupload API"?  Are you talking about -X PUT /stewardship?   It simply re-pushes the currently stamped content.   And the stamp-owning node can already upload the same content using the same stamp and the stamp is (correctly, IMHO) NOT dinged for the duplicated content, unless, of course, you specify a different stamp.

I don't remember seeing any specific "Reupload" API?

**Comment by aloknerurkar** [comment]
> What is the "Reupload API"? Are you talking about -X PUT /stewardship? It simply re-pushes the currently stamped content. And the stamp-owning node can already upload the same content using the same stamp and the stamp is (correctly, IMHO) NOT dinged for the duplicated content, unless, of course, you specify a different stamp.
> 
> I don't remember seeing any specific "Reupload" API?

I updated the description. Let me know what you think.

**Comment by ldeffenb** [comment]
That helps.   In order to provide backward compatibility with existing -X PUT /stewardship scripts, can it be implemented such that if no stamp is provided on the API, and a stamp is known locally (as in the case of pinned chunks), that it uses the existing stamp?   But if no stamp is provided and no stamp is locally known, the -X PUT /stewardship fails with a suitable error?
