### ISSUE TITLE
Excessive number of chain RPC calls

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#4131]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
After running our of 1M request per 24h we looked into the number of RPC calls bee makes and it turns out that `postage.listener.Listen` is responsible for most of these calls.

### Summary
Bee is issuing a large number of `eth_blockNumber` calls, consuming our quota.

### Expected behavior
Have significantly fewer requests to get the current block number, considering that the vast majority of these requests return the same value, as the block number changes less often.

### Actual behavior

https://monitoring.testnet.ethswarm.org/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bnamespace%3D%5C%22anatol%5C%22,%20container%3D%5C%22bee%5C%22%7D%20%7C%3D%20%5C%22node%2FethBackend%5C%22%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%221686038400000%22,%22to%22:%221686041999000%22%7D%7D

![rpc](https://github.com/ethersphere/bee/assets/87016465/a536d422-c114-42b0-adcc-2653dffb38e0)

### Steps to reproduce
Add these loggers in the code:
```
pkg/storageincentives/agent:183

	phaseCheck := func(ctx context.Context) {
		ctx, cancel := context.WithTimeout(ctx, blockTime*time.Duration(blocksPerRound))
		defer cancel()

		a.metrics.BackendCalls.Inc()
>>>>		a.logger.Debug("ethBackend", "caller", "storageincentives.phaseCheck")
		block, err := a.backend.BlockNumber(ctx)
		if err != nil {
			a.metrics.BackendErrors.Inc()
			a.logger.Error(err, "getting block number")
			return
		}
```

and in `pkg/postage/listener/listener.go:275`
```
			l.metrics.BackendCalls.Inc()
>>>>			l.logger.Debug("ethBackend", "caller", "postage.listener.Listen loop")
			to, err := l.ev.BlockNumber(ctx)
			if err != nil {
				if errors.Is(err, context.Canceled) {
					return nil
				}

				l.metrics.BackendErrors.Inc()
				l.logger.Warning("could not get block number", "error", err)
				lastConfirmedBlock = 0
				continue
			}
```

Also if you run an instance against your own infura account you can check out at the stats.
![signin](https://github.com/ethersphere/bee/assets/87016465/7c2f7c52-2e75-48f4-8d93-85544563e4e7)

### Possible solution
Caching or a less busy loop.

**Comment by notanatol** [comment]
the third caller of the `eth_blockNumber` method is "ChainSyncer.getBlockHeight"

**Comment by notanatol** [comment]
nuking the cluster did not have any impact on the frequency of the chain calls.

**Comment by istae** [comment]
Closed since rpc call volume has not increased between versions.
The excessive calls related to the issue is most likely misconfigured start block values in a testing environment.
