### ISSUE TITLE
Flaky test `TestPushSubscriber` 

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#4142]
Test `TestPushSubscriber` seems to be flaky [CI run](https://github.com/ethersphere/bee/actions/runs/5210532740/jobs/9401723524).

**Comment by acha-bill** [comment]
This doesn't seem flaky after 500 runs
```
➜  bee git:(master) ✗ go test -run TestPushSubscriber ./pkg/storer --count=500
ok      github.com/ethersphere/bee/v2/pkg/storer        142.767s
```

**Comment by vladopajic** [comment]
hey, @acha-bill 

running test in this way is less likely to behave flaky as there is no concurrent environment - there aren't other gorutines running that can compete for processor's time.

**Comment by acha-bill** [comment]
Thanks. 
Tried with 
`seq 50 | xargs -n1 -P10 bash -c 'go test ./pkg/storer/... -count=1'` and all passed
Also tried with 
`seq 10 | xargs -n1 -P10 bash -c 'go test $(go list ./... | grep -v p2p) -count=1 -run="^(Test.*[^_]FLAKY)$"' `
(ignore p2p that's failing locally and known flaky tests)

**Comment by vladopajic** [comment]
yeah that's should be much better, mainly because in this case there many tests that are executed simultaneously  (`go test ./pkg/storer/...` - presumably all tests have `t.Parallel()` enabled) and not just single test (`go test -run TestPushSubscriber`).

sometimes it can also be helpfully to set `export GOMAXPROCS=1` in order to limit total number of os threads to which goroutiens are going to be scheduled (less os threads means same number of goroutines competing for less processor's time, which might make some gorutines to starve and thus cause race conditions).

anyhow, this test is probably not flaky anymore

cheers 🖖
