### ISSUE TITLE
Flaky test `TestUnreserveCap`

### ISSUE THREAD

**Issue by vladopajic** [ethersphere/bee#4143]
Test `TestUnreserveCap` seems to be flaky ([CI run](https://github.com/ethersphere/bee/actions/runs/5210532740/jobs/9401723524)).

**Comment by acha-bill** [comment]
Does not seem flaky to me after 500 runs. 
```
➜  bee git:(master) ✗ go test -run TestUnreserveCap ./pkg/storer --count=500
ok      github.com/ethersphere/bee/v2/pkg/storer        31.359s
```

Closing
