### ISSUE TITLE
Docker :latest tag points to 1.16.0 (while latest version is 1.16.1)

### ISSUE THREAD

**Issue by PabloCastellano** [ethersphere/bee#4162]
### Summary

I have just updated my bee node using the latest docker image and it says version is 1.16.0-239a4fb4

### Expected behavior

Latest release is 1.16.1 so I expect the latest docker image contains also this version.

### Actual behavior

version is 1.16.0-239a4fb4

### Steps to reproduce

```
$ docker pull ethersphere/bee:latest
$ docker run --rm ethersphere/bee:latest version
1.16.0-239a4fb4
```

### Possible solution

Maybe there is an error in CI with github actions somewhere

**Comment by istae** [comment]
closing since current latest points to the most recent (v1.17.1) version.
