### ISSUE TITLE
Single-page website

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#418]
# User story

## Story

As a dapp developer, I want to upload the content (HTML, CSS, Javascript, images/video) of a single-page DAPP to swarm, such that my users can enjoy this content. 

## Acceptance criteria

A user can go to the website and navigate with the address bar to a content address, which server a website, containing an `index.html`, which references a picture `cat.jpg`.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|
| #425: implement manifest data structures | @zelig @mortelli @pradovic | 1 |
| #426: implement manifest API | @mortelli @pradovic | 1 |
| #431: upload directory | @mortelli @pradovic | 1 |
| #433: support relative paths from index.html  | @zbiljic  @pradovic | 1 |

## Technical debt

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|
| #462: decouple api package | - | 0 |
| #463: remove redundant entries in upload/download | - | 0 |
| #476: extract jsonmanifest into manifest repo | @mortelli  | 1 |
| #480: add getter for jsonmanifest Entries | @mortelli | 1 |
| #494: add encoding marshaling to manifest interface | @mortelli | 1 |

## Follow-ups
| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|
| #481: upload empty directory | - | 0 |
| #482: upload encrypted directories | - | 0 |

**Comment by Eknir** [comment]
@mortelli

**Comment by mortelli** [comment]
related epic: #153

**Comment by Eknir** [comment]
Thanks for the great work, documenting this work @mortelli !
For convenience in Zenhub, it would be good to cross-reference (list the mentioned issues under this epic). I will just proceed and do this now.

**Comment by acud** [comment]
outstanding tasks documented in https://github.com/ethersphere/bee/issues/648
