### ISSUE TITLE
Incomplete pullsync error log

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4210]
### Context
bee 2.0.0 rc9

https://github.com/ethersphere/bee/blob/6fb07f335dd02e1118cab5cac40282b5aa5551b4/pkg/pullsync/pullsync.go#L256

### Summary
The error log above is incomplete and potentially misleading.   If you look at it in context, it would be more correct to say:

`invalid cac/soc chunk`

since both validity checks failed before the warning is logged.

### Expected behavior
Clearer logs.

### Actual behavior
The log indicated that the chunk was an invalid soc, when in fact, it was also an invalid cac.

### Steps to reproduce
Have pullsync process an invalid chunk, which seems to have been cleaned up in testnet compare to this morning.

### Possible solution
Update the log text as indicated above.

**Comment by mrekucci** [comment]
Fixed in  #4225
