### ISSUE TITLE
implement manifest data structures

### ISSUE THREAD

**Issue by mortelli** [ethersphere/bee#425]
Implement the data structures for manifests in `bee`, following the Book of Swarm specifications but with the purpose of completing the [Single-page website](https://github.com/ethersphere/bee/issues/418) user story.

This should be done in the [`manifest` repo](https://github.com/ethersphere/manifest).

### References
- [Book of Swarm](https://www.overleaf.com/project/5dd3d7d22c615700012d7189): manifests functionality, page `100`, section `4.1.2`
- [Book of Swarm](https://www.overleaf.com/project/5dd3d7d22c615700012d7189): manifests data type definition, page `187`, section `7.4.2`
- `bee` feature — upload a website: [resources](https://hackmd.io/YklWpLHPRDGWipoZavw50Q)

**Comment by acud** [comment]
this is done AFAIK
