### ISSUE TITLE
implement manifest API

### ISSUE THREAD

**Issue by mortelli** [ethersphere/bee#426]
Implement the API/interface/high level functionalities for manifests in `bee`, following the Book of Swarm specifications but with the purpose of completing the [Single-page website](https://github.com/ethersphere/bee/issues/418) user story.

This should be done in the [`manifest` repo](https://github.com/ethersphere/manifest).

### References
- [Book of Swarm](https://www.overleaf.com/project/5dd3d7d22c615700012d7189): manifest API definition, page `225`, section `10.2.3` onwards
- `bee` feature — upload a website: [resources](https://hackmd.io/YklWpLHPRDGWipoZavw50Q)

**Comment by acud** [comment]
done AFAIK

**Comment by zbiljic** [comment]
@acud I have not closed this issue as I figured it relates to "entire" manifest API, not just part required for website issue. There are few outstanding endpoints for full support.

However if we are looking for website-only, than this can stay closed.
