### ISSUE TITLE
swarm-deferred-upload default value?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4275]
### Location
Everywhere that `swarm-deferred-upload` header is mentioned in the documentation.

### Description
I believe, but I am not certain, that the default value of `swarm-deferred-upload` was changed from true to false in the bee implementation, possibly when the processing of headers was changed in the api handlers.   However, all of the documentation states that the default is true.

It would be good to verify what the default behavior is in a swarm node and update the documentation (if needed) accordingly.   I have searched the bee source code and did not see anywhere that the value would default to `true`, but I may have missed something.

**Comment by istae** [comment]
the default is direct now,
will update the openapi docs
