### ISSUE TITLE
Freshly started node cannot retrieve chunks

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4283]
### Context
bee 1.17.3

### Summary
Trying to retrieve a chunk that I know is in the swarm (but not in the local cache) with /chunks and it fails with `read chunk failed` for some time after the node starts and then miraculously starts working.

### Expected behavior
If the chunk is in the swarm, and some peers are connected, I'd expect the chunk to be retrieved.

### Actual behavior
/chunks and /bytes both fail until after the node has "warmed up" and has "Healthy" peers.

### Steps to reproduce
Start up a fresh 1.17.3 node and try fetching a chunk that is known to be in the swarm, but not in the node's cache.  It will fail until salud starts running and marking peers as "Healthy".

### Possible solution
Possibly retrieval's closestPeer routine should try the "best" peers first, but if none is found, try a "second best" with just reachable and then even fall back to the "worst" with no extra criteria.   Better to retrieve from a slow node than no node at all!

https://github.com/ethersphere/bee/blob/44846bba2287e2ce117baa253454befd6313161f/pkg/retrieval/retrieval.go#L367

**Comment by istae** [comment]
related https://github.com/ethersphere/bee/issues/4379
related https://github.com/ethersphere/bee/issues/4282
