### ISSUE TITLE
-X PUT /stewardship adds to batch utilization

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4286]
### Context
bee 1.17.3

### Summary
When using the new -X PUT /stewardship with the swarm-postage-batch-id header, the specified batch's bucket utilization is being incremented even though the reference being re-pushed was originally stamped by the same batch.

### Expected behavior
Pre 1.17, a -X PUT /stewardship did not increment the batch bucket utilization, but re-pushed the chunks to the swarm using the original stamp.

### Actual behavior
The /batch/{batchID}/buckets output shows that individual buckets are being incremented when the batch is used in a -X PUT /stewardship invocation, even though all chunks being re-pushed were originally uploaded on the same stamp.

### Steps to reproduce
Upload a file on a stamp, pull the /batch/{batchID}/buckets to a file.  Then do a -X PUT /stewardship on the same reference with the same batch.   Pull another copy of /batch/{batchID}/buckets and compare the two.

### Possible solution
If a chunk is being re-pushed to the swarm by -X PUT /stewardship, and the chunk is stamped by the same batch, re-upload the original chunk and stamp (bucket/index) rather than double-dinging the batch for another stamp for a chunk that should already be in the swarm.

After inspecting the source code, I suspect that if "the file was uploaded on the same node before, it will re-use the same batch." (from the API docs), then that batch's buckets will also be re-incremented by the /stewardship call since the whole thing only grabs the batch and not the full stamp (bucket/index) but instead goes back through a stamper/putter/uploader.  I have tried not specifying the header, but all I get are errors even though /debugstore plainly shows millions of uploaded chunks since the migration to 1.17.

**Comment by mrekucci** [comment]
I have not been able to simulate this error. To reproduce it, the following steps were performed:
- A new fresh node was started from the current master `84b6eaad` and funded with 0.5 GETH and 1 GBZZ
- A new stamp was purchased: `curl -XPOST http://localhost:1635/stamps/1000000/30
{"batchID":"c66db1a27e84e3fab4e0d932011d4faf2bfd3450b8199d0c393a92cd4303bff3","txHash":"0x76b6a337e355d8e5ab5c38c24531693c12fd72b74ec31088f31e1813031ca46b"}`
- A ~5MB file was uploaded: `curl -H "Swarm-Postage-Batch-Id: c66db1a27e84e3fab4e0d932011d4faf2bfd3450b8199d0c393a92cd4303bff3" -H "Content-Type: video/mp4" -H "Swarm-Encrypt: false" -H "Swarm-Deferred-Upload: true" -H "Swarm-Pin: true" --data-binary @file.mp4 http://localhost:1633/bzz
{"reference":"23fadbc7be705b79e18c041fd839566747d66fc27215fd40650fed2ad7956aae"}`
- A snapshot of stamp buckets was taken after the successful file upload: `curl http://localhost:1635/stamps/c66db1a27e84e3fab4e0d932011d4faf2bfd3450b8199d0c393a92cd4303bff3/buckets | jq > old`
- Stewardship endpoint was invoked: `curl -XPUT -H "Swarm-Postage-Batch-Id: c66db1a27e84e3fab4e0d932011d4faf2bfd3450b8199d0c393a92cd4303bff3" http://localhost:1633/stewardship/23fadbc7be705b79e18c041fd839566747d66fc27215fd40650fed2ad7956aae
{"code":200,"message":"OK"}`
- A second snapshot of stamp buckets was taken after the successful stewardship invocation: `curl http://localhost:1635/stamps/c66db1a27e84e3fab4e0d932011d4faf2bfd3450b8199d0c393a92cd4303bff3/buckets | jq > new`
- No difference was found by executing: `diff old new`

@ldeffenb if this is still an issue with the latest master `84b6eaad`, can you provide step-by-step instructions (similar to the above) on how to reproduce it?

**Comment by ldeffenb** [comment]
> @ldeffenb if this is still an issue with the latest master `84b6eaad`, can you provide step-by-step instructions (similar to the above) on how to reproduce it?

I'm a bit hesitant to put 1.17.4-rc3 onto my OSM uploader node which is my only node with a stamp to test this.   I can test it with 1.17.3 if you think that would help.

I believe it may only happen for chunks that were stamped and uploaded before the localstore migration.  Chunks uploaded after the migration are recorded in a table that might actually be able to recall the bucket index information from the batch.

I have a /stewarship checker running right now, but unfortunately it is running against the latest OSM upload version which was done after the localstore migration.

**Comment by ldeffenb** [comment]
I would add a log to the stamper/putter that is invoked by -X PUT /stewardship, but I've got 6 or 7 multi-day pinner passes running against this node that I really don't want to have to restart right now.   But I might go ahead and add that hack to my build so that it's ready when I do have an opportunity to put it in place.

**Comment by ldeffenb** [comment]
And it is definitely an ongoing thing with -X PUT /stewardship.   Here's the same stamp's buckets at 10:16.  Even more incremented buckets since 10:10.
[Uploading 20230919-1016-buckets.txt…]()

**Comment by mrekucci** [comment]
> > @ldeffenb if this is still an issue with the latest master `84b6eaad`, can you provide step-by-step instructions (similar to the above) on how to reproduce it?
> 
> I'm a bit hesitant to put 1.17.4-rc3 onto my OSM uploader node which is my only node with a stamp to test this. I can test it with 1.17.3 if you think that would help.
> 
> I believe it may only happen for chunks that were stamped and uploaded before the localstore migration. Chunks uploaded after the migration are recorded in a table that might actually be able to recall the bucket index information from the batch.
> 
> I have a /stewarship checker running right now, but unfortunately it is running against the latest OSM upload version which was done after the localstore migration.

Unfortunately, that's the case for chunks uploaded before the localstore migration. If you want to fix this, you'll have to upload them again. I'm closing this issue for now. Feel free to reopen it if the problems persist after you re-upload the chunks.

**Comment by ldeffenb** [comment]
Or I'll write my own migration for all of the pinned chunks that hopefully still have stamps attached to them somewhere...
