### ISSUE TITLE
Upload errors

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4300]
It seems we occasionally experience errors on uploads. This is not consistent and there may be days in a row that we do not see them at all. Other days they are more frequent. We have not clarified yet what these errors may be connected to, but it seems there is definitely something that triggers them. 

* When are they more often? Can we say they are coming in a pattern (frequency)?
* What are they triggered from?
* How can they be eliminated?

DoD: We expect upload errors (as well as download errors) to be 0 all the time.

**Comment by ldeffenb** [comment]
Are you doing direct or deferred uploads?   What exact upload errors are you seeing?

**Comment by nikipapadatou** [comment]
Next release will include more relevant logging to help the bee team understand where these issues are coming from.

**Comment by istae** [comment]
Observations from the internal smoke test
Notes: smoke data uploads are 5mb files that uses direct uploads

![image](https://github.com/ethersphere/bee/assets/14264581/20663a30-561e-421f-ab6d-f5b9ca7a8472)

Having looked at the past 2 weeks of the (bee-gateway) smoke tests, the ONLY errors encountered are related to deployment of new release (when uploading is not possible cause nodes are down) and batch create errors for reasons like out of fund nodes.

Next, we need to observe the errors rate for the downloads.

**Comment by istae** [comment]
Observations:

https://hackmd.io/BIE--q9-QnepG24S0FvVwg
