### ISSUE TITLE
bee packaging and docker files use deprecated `BEE_SWAP_ENDPOINT` instead of `BEE_BLOCKCHAIN_RPC_ENDPOINT`

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4303]
Deprecated config `BEE_SWAP_ENDPOINT` variable is still used/referenced in several packaging related files.
Needs to be replaced with `BEE_BLOCKCHAIN_RPC_ENDPOINT`

Related Issues:
- https://github.com/ethersphere/swarm-desktop/issues/295
- https://github.com/ethersphere/bee/pull/3345

**Comment by mrekucci** [comment]
> @mrekucci is `swap-endpoint` already deprecated or it can be still used? It is not that easy to deprecate, it's being used in so many places.

It has been deprecated for almost a year now. It is still in the bee codebase for backwards compatibility, but `blockchain-rpc-endpoint` should be used instead.
