### ISSUE TITLE
A debug endpoint that returns the specific bee node's setup and active environment

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4316]
#### Summary
Information that the endpoint could provide:

1. whether bee is running as a systemctl service or cli
2. whether bee is running in a docker env
3. location of the bee log file being used
4. location of the bee node config file being used

This is particularly useful for debugging where multiple bee nodes run on the same machine.

**Comment by istae** [comment]
This information is known at the time of setting up the node so why is it the responsibility of the bee node to return this info?

**Comment by rampall** [comment]
Let's ignore 1 & 2. 
But 3 & 4 depends on 1 & 2.

- This information is known only when set explicitly, otherwise the location of the config & log files changes depending on the bee setup / environment (Systemctl, `bee start`, Swarm Desktop, Docker etc) 
- This information is known only if we assume the person who set up the node is the same person who is interacting with the Debug API endpoint. Why should we assume that? 
- Why shouldn't a bee node report the location where it is reading it's config and logging its messages? 

Even if i personally set up 100s of bee nodes on my machine, it is hard for me to be really sure that i'm editing the right config file and looking at the right log file for a specific bee node that i'm interested in. 

If the bee node i'm interacting with returns this info, i'll know with confidence that the config im editing is the right one, or the logs i'm looking at is the right one and not some other bee node's log.

**Comment by rampall** [comment]
In any case i see the log output can be redirected anywhere and it is not something set in the config file. Closing this for now.
