### ISSUE TITLE
High memory usage during "migration-RefCountSizeInc" on 1.17.4

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#4332]
### Context
I'm migrating my nodes, they have a lot of pinned data, between 250GB and 300GB each one. The process crashes after short time because it used all the memory.
I've created a swap file of 10GB, but it shouldn't be required. An amount of ~11GB of memory is occupied in total.

### Summary
Process allocate too much memory with a large data base.

### Expected behavior
Memory should be better managed.

### Actual behavior
Migration crashes because of out of memory.

### Steps to reproduce
Try to migrate a node pinning a lot of data.

**Comment by istae** [comment]
going forward. for these types of migrations, we need to take these edge cases into consideration.

**Comment by ldeffenb** [comment]
In the meantime, any suggestions on how to migrate these large nodes?   I've looked at the code, and I suspect that if it actually gets into the Delete loop, the database will be completely messed up as some records will have the new larger size and the others will still be 8 bits.

Seems like the migration should have actually changed the keys like most other migrations do it.   Then a) the migration could restart, and b) the actual migration could be broken into smaller chunks that wouldn't exhaust memory.

**Comment by ldeffenb** [comment]
My 193,744,000 chunk node took 7 minutes in the RefCountSizeInc migration and consumed 16GB of my 64GB swap file on a 64GB RAM machine.   But it survived!  Here's the bee_process_virtual_memory_bytes metrics graph.
![image](https://github.com/ethersphere/bee/assets/5175026/22506327-b15f-46a4-a9f8-916f15fa3e0b)

**Comment by istae** [comment]
phew! thanks for the good news.

**Comment by istae** [comment]
@ldeffenb
a suggestion:
instead of generating the `itemsToDelete` list, the `Put` call can be made directly in the iterator call back.

**Comment by istae** [comment]
may I close the issue?

**Comment by ldeffenb** [comment]
> may I close the issue?

If it's ok with you, I'll close it once I get my main node migrated.  My sharky archive failed and was just restarted, so it might be tomorrow before I can actually attempt it.

**Comment by ldeffenb** [comment]
I considered shuffling the update to inside the loop, but wasn't sure a) if the query would continue to execute properly with concurrent updates to the queried items and b) what the recovery effects might be if the node failed during the loop.  But then again, if the node fails during the actual batched update loop, the localstore is hosed anyway since the old records are keyed the same as the new records, but have a different data length.

**Comment by ldeffenb** [comment]
My largest pinning node has now migrated to 1.17.4.  It found 402510135 "itemsToDelete".  It took just under 4 minutes to build the list (I added an additional log) and consume 90% of the RAM in a 64GB machine along with occupying 30G of the 136G swap space.   Actually processing the list took another 52 minutes for a total of 56 minutes.

So the 1.17.4 migration can finish on large nodes, you just have to have enough RAM and swap space and be patient.
