### ISSUE TITLE
allow multiple urls in `blockchain-rpc-endpoint` for failover cases 

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4335]
#### Summary
Allowing multiple urls for the  `blockchain-rpc-endpoint` value would prevent bee nodes from shutting down when one RPC endpoint momentarily fails

#### Motivation
When nethermind (on dappnode) goes down during an automatic upgrade once, all my bee nodes shutdown along with it. Would be better if the bee node could try the other url's in such cases. Similarly when a node operator is using a rate limited service such as getblock and runs out of requests, all bee nodes go down. 

It would be great to automatically switch between RPC urls in case of failure. Sometimes it takes a few days or weeeks for node operators to realize their bees are down.

**Comment by attila-lendvai** [comment]
and while we are at it, don't exit the bee process when the blockchain endpoint(s) are not reachable, but rather keep trying.

**Comment by istae** [comment]
see referenced issue
