### ISSUE TITLE
replace storer transactions with leveldb batches

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4341]
the chunkstore operations do not currently accept the leveldb batches for writes.
this can cause issues especially in areas of the localstore where the chunkstore is used in tandem with other stores that does indeed utilizes batches for write (eg reserve.Put).

the chunkstore transaction implementation is too complex and bug prone.
transactions for sharky especially is not needed, if a db operation fails, the written data and used slot can simply remain as is and do not need to be recovered.
we have `compact` cmd now which can give the used sharky space back to the node.

also the `reverseOP` transaction idea for the indexstore should ideally be completely dropped and all writes must be done using the 'leveldb.batch`.

**Comment by istae** [comment]
The localstore should ideally looks like this.

Parent calls are exported, core functions of the storer pkg, like Reserve.Put.
The parent func initiates a Transaction. 
Any internal storage calls the parent function makes must utilize the batch, and cannot independently make any Writes to the storage. 

The transaction is internally a leveldb.Batch and exposes the storage calls like `Put, Delete, Get, Commit`.
The transaction also exposes the Chunkstore.

Any write ops are accumulated in the batch of the transcation.

Any sharky writes are immediately written to disk.
Sharky releases are kept in memory until the batch is commited.

sharky_write -> write to disk, keep write locations in memory
sharky_release -> keep release location in memory
batch_write -> write to batch
batch_commit -> commit batch to disk, release location in disk
if batch_commit fails, release all sharky_write location, no ops sharky_release

**Comment by istae** [comment]
wrapSync should be removed with a simple mutex in chunkstore

**Comment by nikipapadatou** [comment]
more discussions are needed between bee team engineers to proceed with this.
