### ISSUE TITLE
Enhance bee nodes logging with trx & node address

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4357]
Let's enhance bee node logging with always having trx and node address outputed so we can match it with other trx in a game. 
Also, in the case of a READ with a false output, it will be useful to find out who was calling this, although no trx.

**Comment by istae** [comment]
@mrekucci we already added this, right?

**Comment by mrekucci** [comment]
> @mrekucci we already added this, right?

Not quite sure, maybe a revision would be a good idea.
