### ISSUE TITLE
Expected utilisation percentages

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4359]
The theoretical expected utilisation percentages are described in the swarm specifications:
specifications 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBci91IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c164d94faf3a65a6ba28b9ab5e8697da90bf63ee/Screenshot%202023-09-29%20at%2014.35.17.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0h1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--45270ce2be8aa57b95f49dedaf20436fd02c816a/Screenshot%202023-09-29%20at%2014.35.49.png)

We are called to run some tests in order to find out how close we are to these percentages.

**Comment by nikipapadatou** [comment]
This is expected to be done with benchmarking unit tests. Let's have a table with the expected utilisation (like the above), based on the different depths.

**Comment by istae** [comment]
with this new test ethersphere/bee#4398
it was revelated that depth 22 can consistently provide > 50% utilization

```
go test  -run ^TestUtilization$ github.com/ethersphere/bee/pkg/postage -count=1 -v
=== RUN   TestUtilization
    stampissuer_test.go:236: depth: 17, actual utilization: 0.037651
    stampissuer_test.go:236: depth: 18, actual utilization: 0.102993
    stampissuer_test.go:236: depth: 19, actual utilization: 0.223402
    stampissuer_test.go:236: depth: 20, actual utilization: 0.349894
    stampissuer_test.go:236: depth: 21, actual utilization: 0.491061
    stampissuer_test.go:236: depth: 22, actual utilization: 0.610335
    stampissuer_test.go:236: depth: 23, actual utilization: 0.672418
    stampissuer_test.go:236: depth: 24, actual utilization: 0.757001
```
