### ISSUE TITLE
Dashboard for network doubling

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4361]
We need to have an easy-accessed dashboard that would indicate how close we are to the next doubling of the network. This will allow us time to prepare accordingly before it happens, to avoid surprises.

**Comment by ldeffenb** [comment]
Given how the batch evictions work now (not evicting the entire previous radius chunks), this might be difficult, but then I haven't looked at the new "reserve contents in radius" return value that I believe is in 1.17.4?

**Comment by istae** [comment]
closing https://github.com/ethersphere/bee-backlog/issues/60
