### ISSUE TITLE
trx recipients in bee to catch errors 

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4364]
Atm bee nodes are not catching properly outputs of errors/reverts and although we catch the revert status, we do not catch the reason. (https://github.com/ethersphere/bee/blob/08904602476619187091f826e7b12344ca2e623b/pkg/storageincentives/agent.go#L374)

An example of error on goerli, and we need to see how to do this with the bee nodes as well:
https://goerli.etherscan.io/tx/0x74a2577db1c325c41e38977aa1eb32ab03dfa17cc1fa0649e84f3d8c0f0882ee

Let's proceed with this so that we know why functions are failing.

**Comment by n00b21337** [comment]
I would give more context to this. So this was discussed here
https://github.com/ethersphere/bee/pull/4358

and there is a link to docs about custom errors from solidity with revert statement
https://docs.soliditylang.org/en/latest/control-structures.html#revert

This link also might help as it explains the basics of it.
https://soliditylang.org/blog/2021/04/21/custom-errors/

I couldn't find any golang solutions but there is JS/TS library here https://github.com/superical/ethers-decode-error
that solves this so some logic could be modeled on it.
@mrekucci @acha-bill
