### ISSUE TITLE
Occasionally unreachable nodes list

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4414]
Regarding the issue that has arisen with the unreachable nodes, it would be very useful to increase the observability we have on them. What we need to observe is mostly the nodes that are *occasionally* unreachable, ie. that now can be reachable and in some time from now turn unreachable and so on.

We would like to have the relevant information. This is the following:
* How many unreachable nodes we have at the moment.
* How many unreachable nodes we had during the past 24 hours.
* How many nodes have turned from unreachable to unreachable over the past 24 hours & which are they.
* How many nodes have turned from unreachable to unreachable over the past week & which are they.

For the last two, we need to have the information on time intervals (maybe 1 hour apart). 
We can consider prometheus or even swarmscan as the place to host these info.

**Comment by nikipapadatou** [comment]
It seems only swarmscan has this information, so let's have this integrated in the swarmscan

**Comment by janos** [comment]
SwarmScan have got a new web page https://swarmscan.io/stats/availability that lists requested number of nodes that can be grouped by countries and errors and also filtered by a specific country or error.
