### ISSUE TITLE
Bee should support using multiple RPC endpoints

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4419]
In relevance to the Trusted Operators Program, we are called to be able to support multiple RPC endpoints

**Comment by istae** [comment]
related #4335

**Comment by istae** [comment]
it's best to keep this complexity outside of the bee.
this issue can be tackled by a proxy service that monitors the health of the multiple endpoints and forwards requests coming from bee to the "healthy" endpoint.

**Comment by rampall** [comment]
also related - https://github.com/ethersphere/etherproxy/issues/16

**Comment by istae** [comment]
nice, thanks.
I believe this is the cleanest approach.

**Comment by nikipapadatou** [comment]
Relevant discord discussion between community members: https://discord.com/channels/799027393297514537/811553590170353685/1168318756112568330

**Comment by Cafe137** [comment]
Support for multiple targets and seamless failover has been implemented and released in [etherproxy 1.4.0](https://github.com/ethersphere/etherproxy).

**Comment by istae** [comment]
closing issue, see solution above
