### ISSUE TITLE
Setup cluster for connectivity investigation

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4420]
In regards to the unreachable nodes that we have in our network, we will be trying out a new transport layer in libp2p called QUIC. We have observed that these nodes are in China, so we suspect that the reason behind these connectivity issues is the GFW.

In order to make sure that this is the case, we will need a private testnet cluster. In this we need to setup a new network with nodes running both in china and EU, in order to see how the network behaves.

**Comment by istae** [comment]
for issues regarding internal testing, let's utilize https://github.com/ethersphere/bee-backlog/issues repo instead @nikipapadatou

**Comment by nikipapadatou** [comment]
Closing this because of legal and compliance reasons.
