### ISSUE TITLE
make trojan chunk mining work on bit vectors

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/bee#443]
(issue stemming from unresolved thread in #2148)

trojan chunk mining (i.e. finding a nonce) should work on bit vectors rather than addresses, which are byte arrays.

see [original comment](https://github.com/ethersphere/swarm/pull/2148#discussion_r405590834)

**Comment by Eknir** [comment]
Which phase of global pinning is this? Could you please cross-reference it (also mentioning it in the issue/epic which describes the phase?)

Same for other global-pinning feature which are still in the "New Issues column"

**Comment by Eknir** [comment]
@zelig , could you give me an insight in the priority of this?
