### ISSUE TITLE
Sudden increase of download errors

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4451]
Over the past weeks we have observed a significant increase on the download errors. After some investigation we have correlated them with the connectivity issues we experience at the moment. (Relevant documents are written and explain the issue).

We need to investigate this further, get relevant logs, observe metrics and get to the bottom of it.

**Comment by ldeffenb** [comment]
I've been doing a /stewardship check on the OSM dataset and have observed the following retrieval metrics over the past two days.   Just in case this helps anything.

![image](https://github.com/ethersphere/bee/assets/5175026/aa116eba-22aa-4224-9757-d34df9680eb2)

**Comment by notanatol** [comment]
The results have been shared in the mattermost. I would like to get some inputs on my findings - that would clarify my next steps regarding this task.

**Comment by janos** [comment]
@notanatol thank you for analysis. The results clearly show relevant handshake durations.

**Comment by notanatol** [comment]
I've build this repository to analyze the network dumps:

https://github.com/ethersphere/asa

it has a readme with a step-by-step process that allows to aggregate multiple days of statistics into a single spreadsheet that looks like this:
[availability.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM21tQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7f3c9222dcf385f83e46b90e91b3a5b012d61a2/availability.pdf)
