### ISSUE TITLE
Canceling uploads seems lead to not being able to upload again

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#4460]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context

Bee version: Version: 1.17.5-50fcec7b
Swarm-cli: Swarm CLI 2.6.0
Ubuntu; Bee running as Swarm Desktop

### Summary

Using swarm-cli to upload a large file (10GB+). Quite quickly after starting upload decided to cancel with CTRL-C. Tried to upload same file name shortly after (but slightly larger, as content was added) and the upload fails with error 500. See screenshot.

![image](https://github.com/ethersphere/bee/assets/1554520/b8c59049-565f-4f30-ac18-d362d93430fa)

### Expected behavior

I would expect the uploads to work without error.

### Steps to reproduce

Try to upload a file using swarm-cli, cancel with CTRL-C and try to upload another one (maybe has to be same filename?).

**Comment by acha-bill** [comment]
I cannot reproduce this on `bee 1.17.6` with CLI `2.6.0`
