### ISSUE TITLE
Fix some wrong position on the `swarmscan` map

### ISSUE THREAD

**Issue by junyan-zg** [ethersphere/bee#4463]
@janos Hello! the nodes in China are too concentrated, could you fix it? Thanks!

**Comment by janos** [comment]
Hi @junyan-zg. Thank you for submitting the issue. Currently, the reason for this is the granularity that GeoIP database is providing for these IP addresses. I will see to get more detailed location database.

**Comment by janos** [comment]
SwarmScan now has a better granularity on geolocation data.

**Comment by junyan-zg** [comment]
@janos Efficiently handled! Thanks!
