### ISSUE TITLE
Data Durability dashboards

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4475]
A large file has to be uploaded once to the Mainnet and the list of chunks belonging to file has to be captured. The size of the file should be large enough to cover all neighborhoods and future new neighborhoods in the event of a storage radius increase (eg 10 GB). 

A new beekeeper check needs to created that wakes up every so often and does the following:
* Download the full list of chunks individually via a random gateway nodes(s).
* It’s important the local caching is disabled via the disable cache header.

Capture them metrics below:
* chunk download attempts count, download errors count
* if a single download failure occurs, the download of the file as a whole is marked as a failure.
* If all of the chunks are retrieved, then the download of the file as a whole is marked as a success.
* chunk download duration (success and failure measured separately)

Create the following Grafana Dashboards:
1. All time chunk retrieval rate (% retrievable of all chunks monitored)
2. All time large file retrieval rate

**Comment by istae** [comment]
Tasks
1. Write a new tool (cli command) that will split a file (BMT) and output the chunk addresses.
2. Collect all of the addresses and put them in a file in some format and upload to swarm.
3. Upload the large file to swarm
4. Write a beekeeper check that would download the collection of chunk addresses and does the above (see description)
