### ISSUE TITLE
Write documentation for Encryption

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#448]
# Task
Update the documentation for the using Encryption in bee.

## Acceptance criterea
A new person should be read the doc and do the following
- Upload a file with encryption
- download a file with encryption

**Comment by Eknir** [comment]
Hi @jmozah , thanks a lot for making this issue! The best place to document issues w.r.t. documentation is on our [docs repo](https://github.com/ethersphere/docs.github.io) (so you know next time).

**Comment by Eknir** [comment]
@significance

**Comment by Eknir** [comment]
Done
