### ISSUE TITLE
do rchash in parallel with all available cores

### ISSUE THREAD

**Issue by jpritikin** [ethersphere/bee#4497]
#### Summary
It seems like rchash only uses a single core. This is a problem for old/slow CPUs that cannot complete the hash in time. If bee used all available cores then more old/slow CPUs might be able to participate in the storage game.

#### Motivation
Allow more nodes to participate in the storage game.

**Comment by istae** [comment]
there are currently 6 workers in the `ReserveSample` function so this is a parallelized process.
We can do with more profiling though to see where we can improve
