### ISSUE TITLE
on db nuke also nuke kademlia metrics

### ISSUE THREAD

**Issue by darkobas2** [ethersphere/bee#4502]
### Summary
on a "hot" db nuke (when bee is alive) bee usuallyfails on restart with
```
"time"="2023-12-12 23:36:19.115989" "level"="error" "logger"="node" "msg"="got error, shutting down..." "error"="unable to create kademlia: unable to create metrics storage: database entry point either missing or corrupted"
"time"="2023-12-12 23:36:19.116622" "level"="error" "logger"="node" "msg"="failed to build bee node" "error"="unable to create kademlia: unable to create metrics storage: database entry point either missing or corrupted"
```
I know "hot" nuke is not recommended but it makes life much easier on k8s deployments

### Expected behavior
also nuke kademlia-metrics folder

**Comment by notanatol** [comment]
currently the `kademlia-metric` is removed during nuking. the issue is that during 'hot' db nuke it's impossible to be sure that the running process will not impede the folder from being removed and result in a corrupted database.

we can only insist to not execute the `nuke` command on a running instance.

**Comment by ldeffenb** [comment]
IIRC, a bee node will generate some sort of locking error if it tries to use a data-dir that is in use by another instance.  Any chance that approach could be used on the `db nuke` command?

**Comment by notanatol** [comment]
> IIRC, a bee node will generate some sort of locking error if it tries to use a data-dir that is in use by another instance. Any chance that approach could be used on the `db nuke` command?

So it seems that in the case of the kademlia instance the removal can succeed, it's not deterministic. But when it fails (removes partially) it leaves the database in an inconsistent state. A custom locking mechanism can be implemented but we have to look into the (effort invested)/reward ratio.
