### ISSUE TITLE
create batch: create failed

### ISSUE THREAD

**Issue by sosoxuc** [ethersphere/bee#4505]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
when I try to buy stamps the issue happens

### Summary
when I try to buy stamps the issue happens

### Expected behavior
Should return status 200 and batch id

### Actual behavior
{"code":500,"message":"cannot create batch"}

### Steps to reproduce
Spin up Swarm Bee from docker image
deposit xDAI and BZZ
try buying batch

**Comment by ldeffenb** [comment]
Try running your node with --verbosity 5 and then capture the logs when you attempt to purchase the stamp.   The bee logs go a long way to helping understand failures.

**Comment by acha-bill** [comment]
Also, check if you have any newly created stamps. In case one was actually created.

**Comment by sosoxuc** [comment]
https://github.com/ethersphere/bee/blob/master/pkg/api/postage.go#L123

"time"="2023-12-13 12:59:38.953291" "level"="debug" "logger"="node/api/post_stamp" "msg"="create batch: create failed" "error"="create batch: depth 20 bucketDepth 16 immutable true: Invalid: VM execution error."

**Comment by sosoxuc** [comment]
"logger"="node/transaction" "msg"="estimage gas failed" "sender_address"="0x4645b863faAFDB34be7Ad4a902C2f82a88005Ff0" "error"="Reverted 0xf4d678b8"

**Comment by istae** [comment]
looks like an issue with your rpc provider?

**Comment by sosoxuc** [comment]
> looks like an issue with your rpc provider?

Why that?

I tried two different providers

**Comment by sosoxuc** [comment]
Seems the issue with provider and also amount was small
