### ISSUE TITLE
Upload w/Pinning duplicates RefCnt

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4527]
### Context
1.18.2

### Summary
If a given content is uploaded multiple times with `swarm-pin: true` specified, the resulting refCnt for the involved chunks is left with extra increments based on how many times the content was uploaded with pins.  This will cause the content to never leave the localstore/sharky even after the single actual pin is removed.

### Expected behavior
If data is uploaded and pushed, the resulting refCnt should reflect just the actual single pin (and potential reserve status), not the redundant orphaned pins from the extra uploads.  Then if the pin is deleted, the content would be removed.

### Actual behavior
A new pinning collection is created and completed for each upload with suitable ChunkStore.Put() calls for each involved chunk.
https://github.com/ethersphere/bee/blob/ad2602c31c2b5a479ab8e76e793f3cf2ea548c71/pkg/storer/internal/pinning/pinning.go#L251
But when the collection is closed, the single root reference pinCollectionItem is updated to the new UUID orphaning the original UUID's pinChunkItems such that they will never be deleted causing their refCnt increments to persist forever preventing those chunks from ever leaving the localstore or sharky. 
https://github.com/ethersphere/bee/blob/ad2602c31c2b5a479ab8e76e793f3cf2ea548c71/pkg/storer/internal/pinning/pinning.go#L268
https://github.com/ethersphere/bee/blob/ad2602c31c2b5a479ab8e76e793f3cf2ea548c71/pkg/storer/internal/pinning/pinning.go#L269

Here are the extensive logs that I added to my bee node source to track down this behavior:
```
Original upload creates a new collection AND increments the stamp:

"time"="2023-12-20 13:43:13.786854" "level"="debug" "logger"="node/storer" "msg"="pinning.NewCollection" "UUID"="47ff794c-2b3c-4bf8-b7bd-67e9293f56b3"
"time"="2023-12-20 13:43:13.787038" "level"="debug" "logger"="node/postage" "msg"="StampIssuer.increment" "chunk"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "batch"="b9ca120bc0adc895ab7c9ebaf1288838d5fbe956b3f935812917617869ee39f2" "bucket"=61047 "bCnt"=31 "maxused"=46 "upperbound"=256
"time"="2023-12-20 13:43:13.790376" "level"="debug" "logger"="node/storer" "msg"="chunkTrace: chunkStore.Put new chunk" "why"="Upload(UploadPut(api.Put(ChainWrite)))" "address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "loc"="5:107465(358)" "batch_id"="b9ca120bc0adc895ab7c9ebaf1288838d5fbe956b3f935812917617869ee39f2" "index"="0000ee770000001e"
"time"="2023-12-20 13:43:13.790505" "level"="debug" "logger"="node/storer" "msg"="pinning.Put: new chunk (w/ChunkStore.Put)" "chunk"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="47ff794c-2b3c-4bf8-b7bd-67e9293f56b3"
"time"="2023-12-20 13:43:13.790532" "level"="debug" "logger"="node/storer" "msg"="chunkTrace: chunkStore.Put increment chunk" "why"="Pinning(UploadPin(api.Put(ChainWrite)))" "address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "loc"="5:107465(358)" "refCnt"=2 "batch_id"="b9ca120bc0adc895ab7c9ebaf1288838d5fbe956b3f935812917617869ee39f2" "index"="0000ee770000001e"

The initial Close actually creates a root-keyed pinCollectionItem record with the original UUID.

"time"="2023-12-20 13:43:13.790611" "level"="debug" "logger"="node/storer" "msg"="pinning.Close" "root"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="47ff794c-2b3c-4bf8-b7bd-67e9293f56b3"

The second upload creates a new collection and UUID, and properly doesn't increment the stamp.  But it DOES increment the refCnt for all involved chunks because it doesn't know yet if this is actually a new pin.

"time"="2023-12-20 13:43:13.975410" "level"="debug" "logger"="node/storer" "msg"="pinning.NewCollection" "UUID"="baf57e6f-e6aa-4401-b45a-6b9719029a6e"
"time"="2023-12-20 13:43:13.976285" "level"="debug" "logger"="node/storer" "msg"="pinning.Put: new chunk (w/ChunkStore.Put)" "chunk"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="baf57e6f-e6aa-4401-b45a-6b9719029a6e"
"time"="2023-12-20 13:43:13.976321" "level"="debug" "logger"="node/storer" "msg"="chunkTrace: chunkStore.Put increment chunk" "why"="Pinning(UploadPin(api.Put(ChainWrite)))" "address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "loc"="5:107465(358)" "refCnt"=3 "batch_id"="b9ca120bc0adc895ab7c9ebaf1288838d5fbe956b3f935812917617869ee39f2" "index"="0000ee770000001e"

The second Close updates the root-keyed pinCollectionItem to point to the new UUID.

"time"="2023-12-20 13:43:13.976397" "level"="debug" "logger"="node/storer" "msg"="pinning.Close" "root"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="baf57e6f-e6aa-4401-b45a-6b9719029a6e"

This is just the pusher finally seeing the new chunk to push:

"time"="2023-12-20 13:43:14.344191" "level"="debug" "logger"="node/storer" "msg"="subscribe push: upload.Iterate" "chunk"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7"

A third upload is initiated creating yet another new collection with a 3rd UUID.

"time"="2023-12-20 13:43:14.558114" "level"="debug" "logger"="node/storer" "msg"="pinning.NewCollection" "UUID"="301ba5bb-7386-406b-998c-b9d30c708556"
"time"="2023-12-20 13:43:14.558966" "level"="debug" "logger"="node/storer" "msg"="pinning.Put: new chunk (w/ChunkStore.Put)" "chunk"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="301ba5bb-7386-406b-998c-b9d30c708556"
"time"="2023-12-20 13:43:14.559004" "level"="debug" "logger"="node/storer" "msg"="chunkTrace: chunkStore.Put increment chunk" "why"="Pinning(UploadPin(api.Put(ChainWrite)))" "address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "loc"="5:107465(358)" "refCnt"=4 "batch_id"="b9ca120bc0adc895ab7c9ebaf1288838d5fbe956b3f935812917617869ee39f2" "index"="0000ee770000001e"


The third Close updates the root-keyed pinCollectionItem to point to the new UUID orphaning the original 2 sets of pinChunkItems.

"time"="2023-12-20 13:43:14.559078" "level"="debug" "logger"="node/storer" "msg"="pinning.Close" "root"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "UUID"="301ba5bb-7386-406b-998c-b9d30c708556"

When the pusher finishes, the refCnt is decremented by 1 since the pushItem has been removed, but there's only one active pin (the 3rd one), so the final refCnt should be 1, not 3.  The extra 2 will never go away because the redudant pins have been orphaned.

"time"="2023-12-20 13:43:14.619313" "level"="debug" "logger"="node/pusher" "v"=1 "msg"="chunk pushed" "chunk_address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "peer_address"="f320fb80e8c3872fd7605eb44dba93ae192b23ab0a78d6e8c0523565072e8e18" "proximity_order"=3
"time"="2023-12-20 13:43:14.619442" "level"="debug" "logger"="node/storer" "msg"="chunkTrace: chunkStore.Delete decrement chunk" "why"="Upload.Report" "address"="ee77388fe89615fb7e07b5690a64a3ed8e43d8f206d51e56e4bebde4de9387f7" "loc"="5:107465(358)" "refCnt"=3
```

### Steps to reproduce
Upload some content with a `swarm-pin: true` header.   Note the reference and refCnt (if you can figure out how to get the latter).  Upload the same content again with the same `swarm-pin: true` header.   You'll get the same reference, but now all of the involved chunks will have their refCnt incremented but it will never decrement even after unpinning because the root reference is, in fact, only pinned once.

Manually pinning a reference will not show this behavior unless it is executed concurrently on a single reference.  This is because the manually initiated pin checks to ensure that the reference isn't already pinned before creating a new pinning Collection and traversing the referenced chunks.

### Possible solution
The collectionPutter Close method needs to check if the root reference is already pinned by an earlier UUID and remove the pinChunkItems for the newly redundant UUID with associated ChunkStore.Delete() calls to decrement the refCnts (handled by the deleteCollectionChunks method).  This way only the first upload to complete and close the pin collection will be retained in the localstore and the sharky refCnts.
https://github.com/ethersphere/bee/blob/ad2602c31c2b5a479ab8e76e793f3cf2ea548c71/pkg/storer/internal/pinning/pinning.go#L259
This check and recovery MUST be protected by a mutex because concurrent uploads of a single content is possible, even though the logs above show 3 consecutive, not current, uploads with pins.

**Comment by ldeffenb** [comment]
BTW, this is the image that is being uploaded multiple times to the OSM dataset.  I suppress single color images if the next outer zoom has the same color, but this pattern doesn't fall into that optimization.
![image](https://github.com/ethersphere/bee/assets/5175026/86a473f9-0345-41b7-a0d9-33380bbf0202)

**Comment by istae** [comment]
so the fix looks something like:

1. in `collectionPutter.Close()` check if another `pinCollectionItem` with the root address exists.
2. if it does exist, call `collectionPutter.Close()` to remove the collection (and all of the pinned data).

**Comment by ldeffenb** [comment]
Presuming that 2 is removing the newly creating, and just closed, collection, then yes, I'd concur.

But you probably still need a mutex around it because otherwise if a new reference is uploaded concurrently a bunch of times the FIRST time, then multiple of those completions may detect that there isn't already a pin and they'll all try to store their own still leading to multiple increments.
