### ISSUE TITLE
Global Pinning Integration Test

### ISSUE THREAD

**Issue by santicomp2014** [ethersphere/bee#453]
# Global Pinning Integration in Bee

### Node topology
A ←→ B ←→ C

Node A: consumer (chunk downloader)
Node B: storer   (simulatyes the network)
Node C: pinner   (chunk uploader and pinner)

- a pre-generated chunk must be selected for recovery
- overlay addresses for A and C must not have a matching first byte
- the chunk to be recovered must have an address closest to B

### Tests
 
 1) send a message from node A and receive from node C
    - Register a topic in Node C (topic: "foo")
    - Send a PSS message from Node A destined to topic "foo"
    - Receive the message in Node C
    - Node A should get an delivery Ack
 
 2) Upload and pin chunk from Node C and download in node A (Normal scenario)
    - Upload a chunk from Node C and Pin it
    - Download from Node A (To check if it exists in network)
 
 3) Upload and pin chunk from Node C and download in node A  (Chun repair scenario)
    - Erase the chunk from node B and Node A (trigger GC or use a special chunk delete API)
    - Node C should still have the chunk as it is pinned locally
    - Now Download again from Node A, this time since B does not have the chunk, Node C will trigger a chunk repair
    - After some time, download the same chunk again from Node A,  should be available again in node B
                
          
 Q1) do you need a API (debug) to send and receive PSS messages?
 Q2) do you need a API to delete a chunk in local DB or trigger GC ?
 Q3) Do we also do a full test with more nodes example 30 nodes and try a recovery without special restrictions?
        
### References
Global Pinning Manual Testing [Reference](https://hackmd.io/spqiO42rTt2H2Bb81YQYgQ?view)

- We have to discuss about the PSS API structure...
- Chunk Delete Api for Test and also another GC test for sanity check (#556)

**Comment by Eknir** [comment]
@santicomp2014 , great that you started working on defining this! I assume, however, that it is not complete (yet)? 

Any reason why it was left like this halfway?

It would be great if you could finish this, mention it in the global pinning phase 0 issue, and ask @svetomir if he can already start working on it.

**Comment by Eknir** [comment]
Bump

**Comment by jmozah** [comment]
@Eknir We have not started working on this... Will update once this is in some shape.

**Comment by jmozah** [comment]
https://github.com/ethersphere/beekeeper/pull/40
