### ISSUE TITLE
Remove type specifier for chunk content

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#454]
WTR this exchange: https://github.com/ethersphere/bee/pull/429#discussion_r453443685

**Comment by jmozah** [comment]
When reviewing the trojan PR, it was commented by @nolash that we cleanup the chunks struct inside swarm package and maintain its purity. This PR is a placeholder to take this discussion forward and do the cleanup.  I would also say that we probably move the chunks in to a separate package called chunks.

**Comment by acud** [comment]
solved by @jmozah as part of https://github.com/ethersphere/bee/pull/602
