### ISSUE TITLE
uploadstore fixes

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4541]
* stampindex check can be removed in the `uploadPutter.Put` as the chunks passed to the putter are refreshly uploaded and stamped chunks.
* `uploadPutter.Close` should delete all associated uploadItems and chunk data, see `remove()` (confirm this is currently leaking).
* `Report` should not fetch `uploadItem` for the tagID but can use the tagID directly from the chunk (it must assured that the callers of `Report` has a chunk with a properly set tagID)
* see https://hackmd.io/D3lK13p6S8egANbvkrIYSw#Deferred-Uploads for more description

**Comment by acha-bill** [comment]
> Report should not fetch uploadItem for the tagID but can use the tagID directly from the chunk (it must assured that the callers of Report have a chunk with a properly set tagID)

We still need to fetch `uploadItem` (to update `synced`). So it's better to just use the `tagID` from there.  There's no advantage of getting it from the chunk directly.
