### ISSUE TITLE
Excessive number of stream resets

### ISSUE THREAD

**Issue by notanatol** [ethersphere/bee#4545]
### Context
A random sample off of the `testnet-storage` cluster shows that in a span of 5 minutes there have been 698 log events with category level 'error' - of which 362 are in the form: "error"="SOME ACTION: stream reset"

Sometime the action is multiple errors joined, due to recent enhancements in error handling:

` "error"="new stream: send headers: read message: stream reset"`

Every protocol exhibits these stream resets and some seem to be due to accounting reasons.

### Summary
This ticket keeps track of the efforts to investigate (and fix) the core reason(s) for these stream resets.

**Comment by nikipapadatou** [comment]
old issue and not enough details to investigate
