### ISSUE TITLE
Use NewLegacyKeccak256 instead of LegacyKeccak256 across bee

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#455]
This issue is to have the same hashing algorithm in bee across the system. Some places use LegacyKeccak256 and some places the NewLegacyKeccak256 which is defined in swarm/swarm.go.  

like in this PR https://github.com/ethersphere/bee/pull/347/files#diff-ab87c7a8d2a2740b3c322c1f8d7410a9

this is recommended by @nolash [here](https://github.com/ethersphere/bee/pull/429/files#r453446020)

**Comment by acud** [comment]
golang `sha3` library calls the keccak implementation we use as `legacy`, so closing as there's not much we can do in our codebase.
