### ISSUE TITLE
Periodically write balances to store

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#458]
# Task

Right now balances are persisted on every accounting action. To reduce IO load / overhead this should only happen periodically. One way might be to write into a batch during accounting and commit that later.

## Acceptance criterea

Balances are not persisted on every accounting action but still persisted regularly.

**Comment by acud** [comment]
@ralph-pichler leveldb does not flush to disk on every write and it is very fast. accounting still doesn't fully work on `bee`. why not first focus on correctness and optimize once we see there's a need to do so?

**Comment by Eknir** [comment]
@ralph-pichler , can this issue be closed?
