### ISSUE TITLE
Fix --restricted option on bee API

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4582]
The --restricted option is being used by some calls on both the /bee and /debug APIs with the default value being false.
On the /bee API, when the option is set to false, we get a 404 error, while when it is set to true, we get a 403.
On the /debug API it works as expected. 

We need to fix the functionality of --restricted.

**Comment by notanatol** [comment]
Is there an example of an request that fails? trying to reproduce the bug

**Comment by notanatol** [comment]
currently the implementation of the `restricted` option follows this set of rules: https://docs.ethswarm.org/docs/bee/working-with-bee/security#a-note-on-the-http-endpoints

can someone confirm that any of this functionality needs to be amended or fixed in any specific way?
