### ISSUE TITLE
Delete all pins (20 at a time?)

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#464]
# User story

## Story

As a file host I want to be able to delete ALL current pins as I load a new consistent set of files into the Swarm.

I'm currently doing "Get list of pinned chunks" followed by "Unpin chunk with given address" for each returned address (times the returned pinCounter).  But imagine my surprise when this doesn't delete all the pins?  Another "Get list of pinned chunks" returns still more (and different) pins.

It seems that "Get list of pinned chunks" only returns 20 pins per invocation, but this is not mentioned in the documentation for the Debug API.  There also does not seem to be a way to specify how many pins are desired.

Is there a way to query ALL the pins?  Or is there a context so that different sets of pins can be queried?

## Acceptance criteria

At least document "Get list of pinned chunks" to have a limit of 20 pins.  But hopefully also describe how to query all existing pins.

Or provide an (Debug?) API that deletes all current pins with full understanding of the ramifications of this request.

## Background

I have a script that adds lots (1,000s) of files to the swarm and automatically pins each address while also recording said address externally.  As this file set is refreshed, I want to delete all current pins without consulting the external source and before re-adding the new file set.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by ldeffenb** [comment]
I see now in localstore/pin.go:

const (
	maxChunksToDisplay = 20 // no of items to display per request
)

// PinnedChunks for now returns the first few pinned chunks to display along with their pin counter.
// TODO: have pagination and prefix filter

So this is a known TODO...

**Comment by Eknir** [comment]
Hi,

Thanks for making this issue. We are looking into it now and will prioritize it accordingly.

**Comment by jmozah** [comment]
> I'm currently doing "Get list of pinned chunks" followed by "Unpin chunk with given address" for each returned address (times the returned pinCounter). But imagine my surprise when this doesn't delete all the pins? Another "Get list of pinned chunks" returns still more (and different) pins.

@ldeffenb When you unpin a chunk, what is the pincounter value? only if the pincounter comes to 0 will the chunk not show in "list pinned chunks" API.

**Comment by ldeffenb** [comment]
@jmozah That is correct.  I'm looping on the returned pinCounter and doing an unpin for each count.  When that loop finishes, the pin is actually gone.  Once I've done that for the 20 that came back from the "list pinned chunks", I do another "list" and rinse and repeat.

**Comment by jmozah** [comment]
@ldeffenb Thanks. So the issue is that we return only 20 in the "list pin" API is it? will your problem get resolved if we add pagination?

**Comment by ldeffenb** [comment]
@jmozah Yes, pagination on the "list" API will resolve my problem.
