### ISSUE TITLE
rectify swarm-encrypt returns an error

### ISSUE THREAD

**Issue by significance** [ethersphere/bee#471]
# Task

there is a bug when using the swarm-encrypt header, the command as follows:

`sig :: ~/Desktop » curl -H "swarm-encrypt: true" -F file=@Spinach-and-Chick-Pea-e1434488129314.jpg http://localhost:8081/files`

has response

`{"message":"could not store file data","code":500}`

## Acceptance criterea

a reference should be returned

**Comment by jmozah** [comment]
https://github.com/ethersphere/bee/pull/472

**Comment by j1n6** [comment]
I was testing if the header would encrypt the file, both local and public gateway URL allow seeing the file without decryption. 

@jmozah how would you expect encrypted file to behave when replicated to the public gateway?

**Comment by Eknir** [comment]
@j1n6 , if you use the `swarm-encrypt` header, the data will be encrypted before sent to swarm. You get back a reference which contains the reference to the data + the decryption key. If you pass this reference, indeed, our public gateways will decrypt automatically with the decryption key, as provided. 

Let me know if this answers your question.

**Comment by j1n6** [comment]
@Eknir is there anyway to protect the data only allowing to be decrypted at local node to protect sensitive information? or would you recommend a different/better way to achieve this objective?

**Comment by Eknir** [comment]
@j1n6 , it would be best to continue this conversation at https://beehive.ethswarm.org/ . You can find me there as @Eknir
