### ISSUE TITLE
update ABI version on the bee side and change the staking interaction with the new contract to use eth address instead of overlay.

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4716]
as can be see here https://github.com/ethersphere/storage-incentives/blob/master/src/Staking.sol
The new staking contract now takes in the eth address, in place of the overlay address.

As such, we need to change the existing staking functionality of the bee client to use eth address.

**Comment by ldeffenb** [comment]
Yeah, THIS is going to really easy to merge into a running swarm, right?   NOT!

Looking forward to see how smooth (or rough) this transition is on testnet long before it makes it to the mainnet swarm.

**Comment by istae** [comment]
closed with https://github.com/ethersphere/bee/pull/4718
