### ISSUE TITLE
Standalone flag

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#473]
Introduce a flag that makes the bee node operate standalone. _Very_ useful for local development work, expecially when software still unstable, because:

- currently the workaround is to change the networkid to something (hopefully) unused.
- that workaround creates a lot of chatter in the logs, making it harder to use for debugging.

**Comment by Eknir** [comment]
:thumbsup:

**Comment by acud** [comment]
Using `--bootnode ""` prevents the node from connecting to bootnodes. If the address book is clean then the node won't connect to any other node.

**Comment by nolash** [comment]
@acud doesnt work if the node was already connected at some point?

**Comment by Eknir** [comment]
@nolash , you will need to specify a new (empty) data directory. Otherwise, it will indeed still try to connect to previous connections you made.

**Comment by nolash** [comment]
... and thus it seems to me that the most user-friendly way of implementing this is for the command line switch to decide whether there should be connectivity or not.

**Comment by janos** [comment]
A standalone flag makes sense, I think, as all current options are not clear or reliable enough in all situations. I do not think that it would be much of a problem to add it.

This flag should prevent connecting on start to any peers and also not to connect to any other peers that may be in the addressbook, and also should prevent p2p to listen for new connections by other peers. This is what I would assume that a standalone flag would set. Is this something what would be in line with your proposal @nolash?

**Comment by nolash** [comment]
>  Is this something what would be in line with your proposal @nolash?

you read my mind @janos

**Comment by janos** [comment]
Great, I've just created a task https://github.com/ethersphere/bee/issues/536.

**Comment by acud** [comment]
Done by @metacertain in #597
