### ISSUE TITLE
Add notice that API is not accessible during initialization

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee#4734]
#### Summary

Currently when a new node is initialized, while syncing batch data, the Bee API is not accessible. However, there is no message returned from the API stating that the node is syncing batch data, it simply appears that the API endpoint is not working properly. It would be good if a descriptive message is returned instead that states the node is currently syncing batch data, so that it's clear there is no malfunction. The message could be something like "Currently syncing batch data, API is not available while syncing. Try again in a few minutes."

#### Motivation

Make the user experience easier.

**Comment by nugaon** [comment]
would be better to give back another response for requests than 404. it is more like a 503.

**Comment by NoahMaizels** [comment]
> would be better to give back another response for requests than 404. it is more like a 503.

I think that whatever the response is, it needs to indicate whether the API is not available since the node is in the process of starting up, or whether it is not available due to some other reason / error
