### ISSUE TITLE
append /network/neighbourhoods endpoint to accept a single neighbourhood

### ISSUE THREAD

**Issue by nikipapadatou** [ethersphere/bee#4736]
The /network/neighbourhoods endpoint returns all the neighbourhoods and their population, making it not straighforward to find information for a single neighbourhood. 

We should append the endpoint to accept a neighbourhood as a parameter, and then it should return the relevant response only for this neighbourhood. If the parameter is not provided, it should be returning all the neighbourhoods, as it is at the moment.

**Comment by istae** [comment]
this is a swarm scanner API issue, closing

**Comment by janos** [comment]
SwarmScan API has been extended with the two endpoints that makes easier to get the population of a specific neighbourhood or a neighbourhood of the provided overlay address overlay address for the current or specific depth.

## By neighbourhood

The endpoint that returns the population for the specific neighbourhood is described here https://api.swarmscan.io/#tag/Network/paths/~1v1~1network~1neighborhoods~1%7Bneighborhood%7D/get. Some examples:
- https://api.swarmscan.io/v1/network/neighborhoods/01010010110 for the neighbourhood 01010010110 of depth 11
- https://api.swarmscan.io/v1/network/neighborhoods/010100101101 for the neighbourhood 010100101101 of depth 12
- https://api.swarmscan.io/v1/network/neighborhoods/0 for the first half of the network (if anyone is interested)
- https://api.swarmscan.io/v1/network/neighborhoods/1 for the second half of the network (if anyone is interested)

## By overlay address

The endpoint that returns the de population of the neighbourhood that a some overlay address belongs to is described here https://api.swarmscan.io/#tag/Network/paths/~1v1~1network~1neighborhoods~1address~1%7Boverlay%7D/get. Some examples:
- https://api.swarmscan.io/v1/network/neighborhoods/address/b1928ee318420118c4ec6537bc912cfa25d0a28b87ecaa559d161639e9b21ff0 for the overlay address neighbourhood at the current depth.
- https://api.swarmscan.io/v1/network/neighborhoods/address/b1928ee318420118c4ec6537bc912cfa25d0a28b87ecaa559d161639e9b21ff0/depth/13 for the overlay address neighbourhood at depth 13.
