### ISSUE TITLE
Bee returns 500 error when chunk cannot be found.

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#474]
The 500 code rather suggests that something went wrong with the server software itself, rather than failure due to connectivity and/or request for non-existing chunks. Encourage use of different code.

**Comment by agazso** [comment]
I think this is an error from the Bee side. If I understand the tests correctly the intent is that this should return a `http.StatusNotFound`.

https://github.com/ethersphere/bee/blob/db4a844a3859b029f94f5d4e0d0c1c4ad68688c1/pkg/api/chunk_test.go#L53

**Comment by acud** [comment]
this was addressed with #793
