### ISSUE TITLE
can't connection with other peer

### ISSUE THREAD

**Issue by lvtujingji** [ethersphere/bee#4771]
### Location
I am meeting  this error in aws instance 

### Description

"time"="2024-08-21 08:59:38.763622" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmY7TsbQv5HqrCUDXzbGjj2g6tNFLn2jEo1sVnq1SyrKkN"
"time"="2024-08-21 08:59:38.828489" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmXLzQcPiCtSc8zkJzjckBMksx4SVfRnAbzCYF4DtLoMne"
"time"="2024-08-21 08:59:39.013071" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmXGpbajn6mEEciVfvmYRXbQdZLzGDrJmLLtPCCDwrbfBb"
"time"="2024-08-21 08:59:39.158479" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmTFvk7BFMKHMDeJPh9SDNL3D1dF3KJug98GotT2Tyj9nm"
"time"="2024-08-21 08:59:39.466173" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="Qmc4eReMGzgJwF8kSHmRzV15bvtNoDWXXXkqvyZkHcdGea"
"time"="2024-08-21 08:59:39.501771" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmRqa4MghTpSiH9vtaYSMtddCkL1q2NJF8KaGygqNnLPvs"
"time"="2024-08-21 08:59:39.523656" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmU2wVeuszzPwE5j9zDk4BicGeJoQYVdbXh96DfN4NttKx"
"time"="2024-08-21 08:59:39.604309" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmZPghFC6hM2ahSR5oahC5EfbtQ9bWepF1bpujoPS98Ftz"
"time"="2024-08-21 08:59:39.862911" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmY1CBtYb9zdEMbfDkw36AEV1Go98A33C4okmhfV4GVSCP"
"time"="2024-08-21 08:59:39.869764" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmcVvxZPXAVACYSCpyTK8RGjQwhFqxFZL5YXY95Jm6zECb"
"time"="2024-08-21 08:59:39.902747" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmPhdo3h7mqqdLrVqva4BGsijWBd6sa5AZo49DkuKbbpp3"
"time"="2024-08-21 08:59:39.922975" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="Qmd4cy1YghV59DtVmLf689NQiisiym1W6Ei4KhjfomUhc2"
"time"="2024-08-21 08:59:39.986176" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmYbStennXfjYP2paLpTPxKxiwrGfuPSc37QgD7LkwBWnf"
"time"="2024-08-21 08:59:40.009355" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmWb452BntScFYWKGfczhTpUb57BCfF21HmaM982Qs4cQx"
"time"="2024-08-21 08:59:40.173366" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmeufaXYNzayJihzjEUCPWn7xFLTh4d8WztFPD87kcYCY4"
"time"="2024-08-21 08:59:40.406858" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmVMMJK2vGc1CkYBQ2mCCeKdRCNFvWFaXqQhT6pfBDFWT9"
"time"="2024-08-21 08:59:40.781063" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmXsCX2J9QgjTZWBbY999MLGfeDBKbWnWedLgtXqAByyj3"
"time"="2024-08-21 08:59:40.811338" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmTNCjSp3QzCgELcrR53odpPWzhKng6po6K5CGqaGoSJ9j"
"time"="2024-08-21 08:59:40.841718" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmVuv16pGxi8kvL543CVuh5iCXb3akwrL9HjFi3D7mRuvG"
"time"="2024-08-21 08:59:40.859033" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="Qmej9CJ9Kd3AHK8gofNQZ5rTYRVguydJL3QWAc58PyEdH3"
"time"="2024-08-21 08:59:41.103704" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmV4eszeQqWSKCL2D3gvmgvebbDo9SfrzG1gbR2AQfzdwc"
"time"="2024-08-21 08:59:41.169594" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmQjJSY9riFH8AFnGtQZELr5nMpckbwiTWxEPP8HosanQe"
"time"="2024-08-21 08:59:41.222453" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmaRibJpnZd1Q2ypF5J6P6J2cUUcH5aMPqUhYDkBDm4f7w"
"time"="2024-08-21 08:59:41.301347" "level"="error" "logger"="node/libp2p" "msg"="stream handler: handshake: handle failed" "peer_id"="QmSCg24bTFz7PwVDK6kftCRajUQD6kULUg1tuEkZ4hdP7r"

**Comment by lvtujingji** [comment]
This is my configuration 

root@ip-172-31-45-23:/etc/bee# bee version
2.1.0-de7eccc1

root@ip-172-31-45-23:/etc/bee# cat bee.yaml 
api-addr: 127.0.0.1:1633
full-node: true
swap-enable: true
blockchain-rpc-endpoint: https://rpc.gnosis.gateway.fm
nat-addr: "18.223.119.122:1634"
payment-threshold: "9000000"
swap-initial-deposit: "0"
# target-neighborhood: "10010011011"
password-file: /var/lib/bee/password
config: /etc/bee/bee.yaml
data-dir: /var/lib/bee
  #debug-api-addr: 127.0.0.1:1635
  #debug-api-enable: true
verbosity: 1
welcome-message: "welcome-from-the-hive"
warmup-time: 30s

**Comment by istae** [comment]
make sure that you using the version that mainnet is on, which is v2.1.0

**Comment by cobordism** [comment]
same issue.
Been running for days but no connected peers.

```
$ swarm-cli  status
Bee
API: http://localhost:1633 [OK]
Version: 2.1.0-de7eccc1
Mode: full

Topology
Connected Peers: 0
Population: 9833
Depth: 31

Wallet
xBZZ: 495.0000000000000000
xDAI: 4.999563618211596520

Chequebook
Available xBZZ: 5.0000000000000000
Total xBZZ: 5.0000000000000000

Staking
Staked xBZZ: 0.0000000000000000

Redistribution
Reward: 0.0000000000000000 xBZZ
Has sufficient funds: true
Fully synced: false
Frozen: false
Last selected round: 0
Last played round: 0
Last won round: 0
Minimum gas funds: 0.006000000000000000 xDAI

$ /usr/bin/bee version
2.1.0-de7eccc1


$ apt show bee -a
[...]
Package: bee
Version: 2.1.0
Priority: optional
Maintainer: Swarm Devops <devops@ethswarm.org>
Installed-Size: 46.8 MB
Depends: passwd, ca-certificates
Homepage: https://www.ethswarm.org
Download-Size: 24.9 MB
APT-Manual-Installed: yes
APT-Sources: https://repo.ethswarm.org/apt */* amd64 Packages
Description: Ethereum Swarm node
```

**Comment by ldeffenb** [comment]
Mainnet swarm requires v2.2.0.   You shouldn't get any peers with 2.1.x any more.

**Comment by cobordism** [comment]
ah. ok. works with 220.
It hadn't worked before and then I found this post and downgraded. anyway. works now :)
