### ISSUE TITLE
Change return key from `/stake/withdrawable` from `stakedAmount` to `withdrawableAmount`

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee#4792]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

# Task

Change returned key from `/stake/withdrawable` from `stakedAmount` to `withdrawableAmount` or `withdrawableStake`, since as described in the [openapi specs](https://github.com/ethersphere/bee/blob/dc64bc0faf44127cfa8b75bbcdcee0a57eaab2da/openapi/Swarm.yaml#L2222), This endpoint fetches any amount that is possible to withdraw as surplus."

```bash
noah@NoahM16:~/bee-node-testing-configs/testnet$ curl  http://localhost:1633/stake/withdrawable
{"stakedAmount":"0"}
```

**Comment by istae** [comment]
closed by https://github.com/ethersphere/bee/pull/4796
