### ISSUE TITLE
Remove default options for deprecated feature (clef)

### ISSUE THREAD

**Issue by NoahMaizels** [ethersphere/bee#4793]
⚠️ Requests for support in an issue-format will be closed immediately. For support questions, we welcome you to our [Discord](https://discord.gg/XGNBEKktkD).

# Task

Remove all clef related references from default configurations

Currently in default config:
```bash
# enable clef signer
clef-signer-enable: false
# clef signer endpoint
clef-signer-endpoint: ""
```

**Comment by martinconic** [comment]
fixed by [PR-4812](https://github.com/ethersphere/bee/pull/4812)
