### ISSUE TITLE
Cannot create batch on the testnet

### ISSUE THREAD

**Issue by aranyia** [ethersphere/bee#4809]
### Summary
Not able to create a postage stamp batch on the testnet with a Bee node configured to use the Sepolia network in test mode.
Potential issues with the boot node on Sepolia.

### Expected behavior
Postage batch contract interaction is successful for creating a new postage stamp batch when calling the POST /stamp endpoint with a testnet Bee node.

### Actual behavior
Receiving **HTTP 500** error responses ("cannot create batch") to POST calls made to **/stamps** endpoint, whilte the node is in test mode and configured to be connected to the Sepolia testnet:
> time"="2024-09-09 12:03:50.504538" "level"="info" "logger"="node/api" "msg"="debug api access" "ip"="172.19.76.8" "method"="POST" "host"="int...galaxis.xyz" "uri"="/stamps/5000000000/18" "proto"="HTTP/1.0" "status"=500 "size"=70 "duration"="15.419462096s" "user-agent"="PostmanRuntime/7.40.0" "x-forwarded-for"="2001:861:4b03:7b40:e5fa:fb90:68ee:fc91, 141.101.68.87, 172.19.76.1" "x-real-ip"="172.19.76.1"
"time"="2024-09-09 12:03:57.482351" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/.../tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-09-09 12:03:57.482379" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"

There are also continous failed attempts to connect to the Seploia bootnode previously configured to be "/dnsaddr/sepolia.testnet.ethswarm.org":
> "time"="2024-09-09 12:02:41.543764" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/.../tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-09-09 12:02:41.543797" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"
"time"="2024-09-09 12:02:41.683502" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/.../tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-09-09 12:02:41.683533" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"
"time"="2024-09-09 12:02:56.872640" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/167.235.96.31/tcp/32491/p2p/QmediErcH3owEGGCNmQYXYqxpb2AWEwQqsiG2QSDjpWupH"
"time"="2024-09-09 12:02:56.872672" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"
"time"="2024-09-09 12:03:12.022191" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/167.235.96.31/tcp/32491/p2p/QmediErcH3owEGGCNmQYXYqxpb2AWEwQqsiG2QSDjpWupH"
"time"="2024-09-09 12:03:12.022219" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"
"time"="2024-09-09 12:03:27.160347" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/.../tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-09-09 12:03:27.160373" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"
"time"="2024-09-09 12:03:42.313376" "level"="warning" "logger"="node/kademlia" "msg"="connect to bootnode failed" "bootnode_address"="/ip4/../tcp/32490/p2p/QmZsYCbkUXWpfR34PmUwMJvHwJtGfbcMMoAp1G2EydkpRA"
"time"="2024-09-09 12:03:42.313403" "level"="warning" "logger"="node/kademlia" "msg"="discover to bootnode failed" "bootnode_address"="/dnsaddr/sepolia.testnet.ethswarm.org"

### Steps to reproduce
HTTP POST call to /stamps/5000000000/18 with a testnet Bee node configured to use the Sepolia network.

**Comment by ldeffenb** [comment]
The sepolia testnet swarm is currently on 2.2.0-rc8.   Any node version other than that will likely not work properly due to contract and protocol changes.   You did not mention what version of the bee node you are using.

**Comment by aranyia** [comment]
The issue is no longer reproducible.
