### ISSUE TITLE
upload empty directory

### ISSUE THREAD

**Issue by mortelli** [ethersphere/bee#481]
Extending the work in #447, implement the upload of empty directories.

Original [comment](https://github.com/ethersphere/bee/pull/447#discussion_r460699102) by @acud:
> so this won't support empty directories. would be nice to have the support so we don't lose information when uploading. this was happening in old swarm and i think this is counter-intuitive and an undesired behavior

**Comment by zbiljic** [comment]
This came up during discussion I had with Viktor, and he mentioned that we should not created entries for empty directories, unless there is at least one file in them (@zelig please correct me if I misunderstood). Which means if there is information about directory from TAR archive, entry for that directory should be created, unless directory is empty.

Personally, I do not have any opinions about this (at this time at least), just mentioning for a reference.

**Comment by acud** [comment]
@zbiljic @zelig I personally don't like the idea of omitting information from a given upload. Directory structure is as important as physical files. I object to omitting empty directories, they should be given consideration just as any other file type. This is counter intuitive for users too

**Comment by Eknir** [comment]
I second @acud s opinion. Being able to upload empty directories is important for a user.

**Comment by zelig** [comment]
> This came up during discussion I had with Viktor, and he mentioned that we should not created entries for empty directories, unless there is at least one file in them (@zelig please correct me if I misunderstood). Which means if there is information about directory from TAR archive, entry for that directory should be created, unless directory is empty.
> 
this must have been a misunderstanding. i specifically  want empty dirs to be represented and see it as a shortcoming of the old manifest format not to allow that.

the solution currently in mantaray is not as i designed it and want to change so 

bump this @Eknir @zbiljic

**Comment by Eknir** [comment]
Hi @zelig , I would like to request a meeting on this. As can be seen in this discussion, @acud opposes to omitting empty directories and I also see the value of uploading them. Nevertheless, I assume there are solid reasons for you bumping this issue.
What about upcoming roundtable? If yes, could you put it on the agenda?
