### ISSUE TITLE
go 1.13(.11) cannot run bee

### ISSUE THREAD

**Issue by nolash** [ethersphere/bee#483]
```
$ go run ./cmd/bee start
# github.com/lucas-clemente/quic-go/internal/handshake
../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/go_1-13.go:24:75: cannot use c (type *qtls.ClientHelloInfo) as type *tls.ClientHelloInfo in return argument
```

**Comment by acud** [comment]
i believe go `1.14` is needed for running bee. can you pelase try 1.14 and say if the problem persists? thanks

**Comment by nolash** [comment]
1.14 is fine

**Comment by Eknir** [comment]
Guys, we had a discussion on this in our chat. Can somebody please write the conclusion of this discussion here? Thanks.

**Comment by acud** [comment]
the conclusion is that we do not support go 1.13 right now. that is due some probably hard dependencies to features that are part of go 1.14. we did not define that we should backward-support certain number of minor versions and so this is not supported as of now. if we wish to provide such support then we should do so.

**Comment by nolash** [comment]
> right now.

alpha? beta?
