### ISSUE TITLE
`overlay` null in the `/addresses` endpoint 

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4840]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord]

`/addresses`  endpoint returns `overlay` as null but the logs show the overlay address just fine.

![image](https://github.com/user-attachments/assets/df214e6a-2b37-44c4-9197-d7b5e883f989)
![image](https://github.com/user-attachments/assets/5cc970c6-438f-4023-96c1-651ecaad4e36)

### Possible solution
Maybe cause by renaming `peer` to `overlay`

**Comment by ldeffenb** [comment]
I have seen this behavior when a new node (or a nuked node) is load the stamps the first time.   As soon as the node is fully up and starting to connect to peers, then the overlay shows up properly.

**Comment by rampall** [comment]
You fast :D I just came back here to add that info: 
- Nuked node + Postage Syncing + null `overlay` in the endpoint + 0 peers
Will wait and see once the node is fully synced. Still feels like a bug :)

**Comment by rampall** [comment]
> I have seen this behavior when a new node (or a nuked node) is loading the stamps the first time. As soon as the node is fully up and starting to connect to peers, then the overlay shows up properly.

Indeed. The overlay showed up eventually after the stamps wee loaded.
