### ISSUE TITLE
reserve size doubling tasks

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4842]
[Swip-21](https://github.com/ethersphere/SWIPs/pull/56/files) can actually be tackled by a relatively small number of changes.

- [x] 1) user provides a whole-number radius delta, _d_ through config options (default being 0)
- [x] 2) reserve capacity is now a dynamic value and each increase in _d_ doubles the reserve capacity, eg 2^(22+_d_). When the new capacity is calculated initially, the reserve worker will automatically reduce the current storage radius until the reserve is full.
- [x] 3) in the `ReserveSampler` iterator, the chunks that are considered need to be filtered by checking that their proximity relative to the anchor is greater than equal to the current storage radius +  _d_.
- [x] 4) salud package should no longer punish peers for having "wrong radiuses" relative to the network.
- [x] 5) consider what do to with the db cmds that rely on the reserve size.
- [x] 6) reserve should return the stat (neighborhood adress and size) of each neighborhood.
- [x] 7) new API for the stats above
- [x] 8) ABI changes. If node has been staked before and if there is a delta change then new bzz has to be staked. The node should err out if there is not enough bzz.
- [x] 9) commited depth changes in the redis contract and the agent

**Comment by zelig** [comment]
> 3\. in the `ReserveSampler` iterator, the chunks that are considered need to be filtered by checking that their proximity relative to the anchor is greater than equal to the current storage radius +  _d_.

should be ` - _h_` where _h_ stands for height, ie. the number of doublings

**Comment by zelig** [comment]
In the light of being cautions about supporting anything more than double (due to problems of resource overload in case of height difference in a neighbourhood as well as sampling issues due to lack of proper indexing beyond height 1).
So I recommend 
1. the contract API as well as beewconfig to allow only the operation of 'increase height by one' as a permanent feature and 
2. restrict height to 1 as a temporary feature in bee only.
3. full support for any height in both bee and the contract in the operational logic to keep implementation simple and lasting

**Comment by ldeffenb** [comment]
> 1. the contract API as well as beewconfig to allow only the operation of 'increase height by one' as a permanent feature and

Will a node be allowed to DECREASE the height?   Like go from doubled back down to a single neighborhood?

**Comment by zelig** [comment]
> > 1. the contract API as well as beewconfig to allow only the operation of 'increase height by one' as a permanent feature and
> 
> Will a node be allowed to DECREASE the height? Like go from doubled back down to a single neighborhood?

YES

**Comment by martinconic** [comment]
> > > 1. the contract API as well as beewconfig to allow only the operation of 'increase height by one' as a permanent feature and
> > 
> > 
> > Will a node be allowed to DECREASE the height? Like go from doubled back down to a single neighborhood?
> 
> YES

The height decrease should also be allowed  only -1 at a time?

**Comment by nikipapadatou** [comment]
Apart from the points that  @zelig raised, I would add that we also need a command that will provide this information to the node operator, i.e. what other neighbourhood(s) the node participates to, their depth etc.

**Comment by istae** [comment]
> > 3. in the `ReserveSampler` iterator, the chunks that are considered need to be filtered by checking that their proximity relative to the anchor is greater than equal to the current storage radius +  _d_.
> 
> should be ` - _h_` where _h_ stands for height, ie. the number of doublings

Assuming the radius _r_ passed to the sampler function is the local radius (one that has _h_ subtracted from it), the chunks in the sample should come from the neighborhood whose proximity with the anchor is at least is _r_ + _h_, no ?

**Comment by istae** [comment]
> Apart from the points that @zelig raised, I would add that we also need a command that will provide this information to the node operator, i.e. what other neighbourhood(s) the node participates to, their depth etc.

By increasing the capacity by a factor of _h_, the radius will eventually drop by _h_, so the node's scope of it's neighborhood will expand by the factor. The existing APIs will continue to operate as normal, eg status endpoint, peer's list, etc. What new information do you want to provide to the user?

**Comment by ldeffenb** [comment]
> What new information do you want to provide to the user?

Personally, I'd like to see at least the reserveSizeWithinRadius for each of the individual neighborhoods that are covered.   The total isn't nearly as informative as the individual neighborhood counts.

**Comment by istae** [comment]
> > What new information do you want to provide to the user?
> 
> Personally, I'd like to see at least the reserveSizeWithinRadius for each of the individual neighborhoods that are covered. The total isn't nearly as informative as the individual neighborhood counts.

imo this should be a new endpoint, maybe `/status/neighborhoods`, where we return the reserve size and peer count of each neighborhood?

**Comment by ldeffenb** [comment]
> imo this should be a new endpoint, maybe `/status/neighborhoods`, where we return the reserve size and peer count of each neighborhood?

Works for me.   But what would the current `reserveSizeWithinRadius` be in all of the existing responses?   And especially `/status` which then feeds into `/status/peers`?   Would it be the total of all neighborhoods or what?   It becomes a non-comparable number if some nodes are double (or eventually quadruple or more) of "normal" nodes.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
