### ISSUE TITLE
Move `node/api` access logs from `info` to `debug`

### ISSUE THREAD

**Issue by rampall** [ethersphere/bee#4845]
⚠️ Support requests in an issue-format will be closed immediately. For support, go to Swarm's [Discord](https://discord.gg/XGNBEKktkD).

### Context
I'm running a bee node and a dashboard on a dappnode. 
At the logging `info` level i get valuable info like this:
![image](https://github.com/user-attachments/assets/b95d8a2c-ceeb-497c-8c61-1a9acc9dadab)
But i get also spammed with `node/api` access messages:
![image](https://github.com/user-attachments/assets/0de98316-1fef-449f-89eb-eb475b4f921c)

It might be more useful to move  `node/api` access logs to `debug` imo.

**Comment by martinconic** [comment]
This would be a simple change but as I know API access logs are typically logged at the info level. @istae, @ldeffenb ?

**Comment by ldeffenb** [comment]
I've wanted to do this for a while to clean up my `--verbosity 3` log output, especially when I've got a script running that really beats up the API.   So I've got no issues with changing the default logging level.

But it would be really really nice if there was better documentation on the logging API, like maybe examples of how to use it to individually enable the API logging if a user desires to still see it.

https://docs.ethswarm.org/api/#tag/Logging

**Comment by martinconic** [comment]
> I've wanted to do this for a while to clean up my `--verbosity 3` log output, especially when I've got a script running that really beats up the API. So I've got no issues with changing the default logging level. I can certainly see a node being used by `bee dashboard` (like on DAppNode) would suffer from continuous API logs as well.
> 
> But it would be really really nice if there was better documentation on the logging API, like maybe examples of how to use it to individually enable the API logging if a user desires to still see it.
> 
> https://docs.ethswarm.org/api/#tag/Logging

Thank you for the feedback. Regarding better documentation would be great if you can open a new issue on this aspect. Let me loop in @NoahMaizels also.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
