### ISSUE TITLE
status protocol should return a new `committedDepth` field

### ISSUE THREAD

**Issue by istae** [ethersphere/bee#4890]
The status protocol should report a new field called `committedDepth` which is the sum of the storage radius + capacity doubling.

1. The reserve should ideally export a new function called `CommittedDepth`.
2. The status protocol should report the committedDepth.
3. The status API should return the a committedDepth field.
4. The salud package should use committedDepth instead of storageRadius for health checks.
5. Any package that takes a capacity doubling argument in the constructor that calculates the committed depth manually should ideally just call the reserve.

**Comment by ldeffenb** [comment]
YES!  This will make it possible to compare depths across nodes again, with a level (deepest depth) playing field, regardless of what doubling is in effect.
