### ISSUE TITLE
Non-synced reserve hashed, committed, and revealed (warmup timing issue)

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#4894]
### Context
sepolia testnet bee 2.3.0-rc5 (but I suspect it is in 2.2.0 and previous as well)

### Summary
I updated a node from rc4 to rc5 while it was actively pullsyncing to fill a newly opened multiplier of reserve.   Upon restart, the storage compensation was just at the end of the reveal phase and entered the claim phase.   This node decided that it's neighborhood was chosen and generated a hash.   Upon hash completion, it had only iterated 1,858,396 chunks because the selected neighborhood was still being pulled when the node was shut down.

### Expected behavior
Node should wait to be fully warmed up, allowing the pullsync to commence, before believing that they are ready to participate in the storage compensation round.

### Actual behavior
This node generated a hash, and I suspect it will also commit and reveal and may be frozen because it is definitely operating on a non-fully-synced reserve, which was undetected because pullsync was still warming up.

Here are the storageincentives logs from this node:
```
"time"="2024-11-05 12:23:18.148928" "level"="info" "logger"="node/storageincentives" "msg"="entered new phase" "phase"="reveal" "round"=46172 "block"=7018214
"time"="2024-11-05 12:25:48.154631" "level"="info" "logger"="node/storageincentives" "msg"="entered new phase" "phase"="claim" "round"=46172 "block"=7018225
"time"="2024-11-05 12:25:48.158101" "level"="info" "logger"="node/storageincentives" "msg"="neighbourhood chosen" "round"=46172
"time"="2024-11-05 12:32:35.700922" "level"="info" "logger"="node/storer" "msg"="reserve sampler finished" "duration"="6m47.535404759s" "storage_radius"=3 "consensus_time_ns"=1730824500000000000 "stats"="&{TotalDuration:6m47.535404429s TotalIterated:1858396 IterationDuration:6m47.533445049s SampleInserts:213 NewIgnored:0 InvalidStamp:0 BelowBalanceIgnored:0 TaddrDuration:28m30.877856271s ValidStampDuration:661.179068ms BatchesBelowValueDuration:194.802µs RogueChunk:0 ChunkLoadDuration:16m26.517040139s ChunkLoadFailed:0 StampLoadFailed:0}"
"time"="2024-11-05 12:32:35.701903" "level"="info" "logger"="node/storageincentives" "msg"="produced sample" "hash"="d2a87f958b496d20894b30159e27cfb5cfe81a0d149b8c5785260a0a92411008" "radius"=3 "round"=46172
```
And the output of /status/neighborhoods.   The selected neighborhood was 010 which you can see is not even up to 2^21 (1/2 target size) chunks.
```
  "neighborhoods": [
    {
      "neighborhood": "000",
      "reserveSizeWithinRadius": 2763356,
      "proximity": 3
    },
    {
      "neighborhood": "001",
      "reserveSizeWithinRadius": 2791439,
      "proximity": 2
    },
    {
      "neighborhood": "010",
      "reserveSizeWithinRadius": 1858396,
      "proximity": 1
    },
    {
      "neighborhood": "011",
      "reserveSizeWithinRadius": 1953902,
      "proximity": 1
    }
  ]
```

### Steps to reproduce
1) Have a node actively pullsyncing into a non-fully-synced reserve.  I suspect this can even be a brand new node, it's all about the timing.

2) Shut the node down a few blocks before the start of a claim phase.

3) Restart the node again just before the claim phase starts.   It is important for duplication that the claim phase starts before the node is warmed up which is also before pullsync starts operating again.

4) If you're lucky, (one of) the node's non-synced neighborhoods will be selected and you will have successfully duplicated this issue.

### Possible solution
The storageincentives agent should honor the warmup time period, or at least not start operation until pullsync has cleared the warmup because otherwise the node may appear to be fully synced (zero pullsyncRate), when in fact the selected reserve is woefully incomplete.

It's the 09a04... node that is doing this while trying to build up to a reserve multiplier of 2 which would include the selected 58ea... neighborhood.   It definitely committed according to monSI.
![image](https://github.com/user-attachments/assets/32874da6-8556-4458-9e28-69ce687461a6)

No surprise that the revealed hash doesn't match the other participating nodes.
![image](https://github.com/user-attachments/assets/f9c78522-c27f-4899-8efa-2a34c00007d0)

**Comment by ldeffenb** [comment]
On thinking this through a bit more, maybe the check for a sufficiently full reserve (greater than 1/2 full) is incorrect in the presence of a non-zero multiplier?

The original neighborhood was fully synced and therefore the total reserve chunk count was definitely sufficient.  It was the chunk count in the actual selected neighborhood that is lacking because it is not yet fully synced.

**Comment by istae** [comment]
@martinconic this can tacked by simply by adding a warmup check in this isFullySynced function https://github.com/ethersphere/bee/blob/master/pkg/node/node.go#L1065
