### ISSUE TITLE
Communicate tag before chunking

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#491]
# User story

## Story
As a user of Swarm who uploads a big file, I want to know the status of my upload throughout the whole upload-process, such that I know that my node is working and not crashed

## Acceptance criteria

When I upload a big file, I have the possibility to see at which state of upload my chunk is, and how far the node is already progressed in this state.

## Background

This issue came up while testing out tags. Related issue which came up was https://github.com/ethersphere/bee/pull/490

The problem we encountered was that an auto-generated tag is not communicated to the user before the actual chunking is done. This creates a pretty long time where the user does not know the state of his upload. 

Relevant chat in Mattermost:
![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/0d71b64d-8170-4493-918a-ff5310b0c7df)

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by jmozah** [comment]
#eknir This feature is already there... please see this [link](https://github.com/ethersphere/bee/issues/492#issuecomment-665679930) for some workflow on and examples on how to use it. So please close this.

**Comment by Eknir** [comment]
Duplicate
