### ISSUE TITLE
Communicate tagUID right away

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#492]
# User story

## Story

As a user of Swarm who is uploading a big file, I want to know the status of my file throughout the whole update process, such that I know that my node is working and I wait patiently.

## Acceptance criteria

- User can figure out the state of the upload throughout the whole process. For this to work, he must know the tag immediately after sending the request to upload data.

## Background

This issue came along after trying out to use Swarm for uploading a bigger file. It took some time, so we figured out it might be handy to verify the state of the upload by using tags. The first issue encountered was https://github.com/ethersphere/bee/pull/490, when using explicit tags. When not using explicit tags, Swarm is auto-generating a tag, but this tag is only communicated to the user when chunking is done. Hence, I don't know how the process of chunking is proceeding.

More information in a chat with @acud :
![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/b3f25014-7c08-4873-9f66-5809314fd761)

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by jmozah** [comment]
@Eknir For a large file upload, the user has to create a tag before uploading. The workflow for a large upload will go like this

1) use the POST/tags API to create a tag. The created tag comes in the response as `tagResponse` json struct which has the tagID also.
2) Upload the large file using /file or /bytes and add the header `swarm-tag-uid` with the received tagID
3) When the upload is happening, you can use another terminal to call the GET /tags/{uid} API and supply the original uid to get the splitter status too

**Comment by jmozah** [comment]
https://github.com/ethersphere/bee/pull/493

**Comment by zelig** [comment]
can we close?

**Comment by Eknir** [comment]
This issue can be closed, as there is currently no possibility to communicate tagUID right away.
