### ISSUE TITLE
Cannot resolve feed through `/bzz` endpoint in 2.3.0

### ISSUE THREAD

**Issue by Cafe137** [ethersphere/bee#4925]
### Context
Bee 2.3.0

### Summary
It seems that feeds cannot be accessed in the new version:

```
{"code":500,"message":"mapStructure feed update"}
```

### Expected behavior
E.g. these feeds resolve:
OSM: `2fdac7bd34a7e27e46e3fd2b6c67f13e3f04231ef92226b8d64a5f693ec80cae`
My Etherjot sample blog: `7af986269fefe63b142ae1b7b5c093ef82b129c7eb550a18bb5c1567a7433058`

### Actual behavior
The request fails with HTTP 500

### Steps to reproduce
Please check the hashes in Expected behavior

**Comment by istae** [comment]
extra logs "time"="2024-12-11 02:13:56.376782" "level"="debug" "logger"="node/api/get_bzz_by_path" "msg"="bzz download: mapStructure feed update failed" "traceID"="9152a829e5b694c" "error"="chunk store: failed reading retrievalIndex for address ab470241d73ac7570dbccb9163f1f77efd9e6a570e28623faa85e28894c001ed: storage: not found"
