### ISSUE TITLE
Multi signature support for SOC

### ISSUE THREAD

**Issue by tmm360** [ethersphere/bee#506]
# Epic
SOC are currently enabled for accept simple payload signature, but exists cases where other signing methods need to be accepted. We are proposing here to accept to have different type of signatures, alternative to the original, that however have to be maintained.

## Story
Exists a dapp where users must be able to sign their own SOC for use them with feeds. Feeds are owned by users, that must be able to update them without restrictions and without any third part needed for signature. Users are enabled to use a web3 wallet, for the instance they are using Metamask integrated with the browser, and are not running any node or other signature system on their device. Metamask is also used for authentication, their identities are related to their ether address, and every signature has to be performed with that address.
When in dapp is required to update a feed, it is composed with javascript in page, and a web3 wallet signature request is invoked. At this point metamask will request to user to sign a message, representing SOC payload, and user is able to click on "Sign message" for accept the proposed feed update. Propagation is performed by dapp using an external gateway.

## Background

This story is a real issue that we have encountered in company. Currently we are managing creating an alternative address server side for web3 users as for web2 users and exposing the key by API, but this is not a good solution.

Web3 wallet exposes several types of signing functions. Here [documentation from Metamask](https://docs.metamask.io/guide/signing-data.html). A summary:

* **eth_sign**: https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#sign  
a plain signature system, compatible with Swarm. However its use is discouraged by Metamask for security reasons, and trying to use it rise a warning alert in UI. In fact it can be used also for sign transactions, and is vulnerable to phishing attacks.
* **personal_sign**: https://web3js.readthedocs.io/en/v1.2.7/web3-eth-personal.html#sign  
it add a prefix text to the signed message, making signature unable to sign transactions. It's implementation is so defined: `sign(keccak256("\x19Ethereum Signed Message:\n" + dataToSign.length + dataToSign))`. It's considered a secure and stable signature way, even if not the most recent. personal_sign [announcement from Metamask](https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527). 
* **signTypedData** from v1 to v4: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md  
it's the most recent implementation of data signature, but EIP is not still considered closed and stable. More updates will come, and probably will become the standard when will be completed.

`eth_sign` is currently the only supported signature from Swarm, but at least also `personal_sign` should be, waiting other news.

I've introduced the issue here https://beehive.ethswarm.org/swarm/pl/9s3u3pgi5tfwumoisstgf8q59a, and discussed on roundtable of 30/07/2020.

## Proposed solutions

Assuming that multiple signatures are accepted by Swarm client, the problem is how to verify them.

### Iterative signature check

The simplest solution is to check a signature type after the other, until a valid is found or until signatures are all be tested. Not a very good solution, especially assuming that valid signature methods will increase with time, but is compatible with current SOC composition.

### Use a bit from signature field

Reading from book diagram, currently "signature" field is using 65 bits instead of 64. We could use the additional bit as discriminator for the signature type. It will support only **eth_sign** and **personal_sign**, but also this doesn't change current SOC composition.

### Extract a byte from payload

A byte (or less) can be kept from payload space, and used as discriminator for signature type. A byte is an extremely abundant amount of data, but this can handle also future new signature protocol implementations.

**Comment by Eknir** [comment]
@zelig , could you let you

**Comment by tmm360** [comment]
As context, our last service specification doesn't require this feature anymore. For other reasons (not directly related) we have choose to create a simple manifest on client side (no signing is needed), and a SOC linking the manifest is signed by a service running on server.
However, the feature can still be useful to someone.

**Comment by ralph-pichler** [comment]
SOCs (and all other non-contract related signed data in swarm) now use the scheme described `personal_sign `.

**Comment by zelig** [comment]
i feel there is no need for this.    `personal_sign` is generic and  supported. I close
