### ISSUE TITLE
Document configuration file better

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#508]
# User story

I want to run two bee instances behind a NAT firewall with open incoming ports.  This is easier to maintain if the incoming port(s) match the actual ports on the two different machines.  I know this can be done from the command prompt, but for auto-start reasons, I would like to specify it in a configuration file.  Documentation on the format of this file does not seem to exist.

## Acceptance criteria

The document should provide for developing a completely populated yaml configuration file describing the use, effect, and valid format and values for every available option, including the difference between ":8080" and "127.0.0.1:6060" for a "port" configuration.  I believe I know the difference, but less network-aware folks would likely be clueless.

## Background

Thanks to @nolash I was able to find it hidden inside a tutorial (https://docs.ethswarm.org/bee-docs/tutorial.html), but it really deserves a more complete description including every available option, in a dedicated document.  I mention "every available option" because even in that tutorial, the first config example doesn't mention the "tracing:" option, but the second one does.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by janos** [comment]
Just to mention that there is a section in [Starting your node](https://docs.ethswarm.org/bee-docs/start.html) about the configuration file called _Configuration file_ and bellow the _Config file template_. First containing the general description of the keys in it and the second one providing an example. I agree that some value formats should be explained in more detail.

**Comment by ldeffenb** [comment]
@janos That's a better link, but definitive configuration file documentation is still needed given the statement "Note that the most-recent release of Bee might have different configuration options than the one provided here. Please verify this before using the template." on https://docs.ethswarm.org/bee-docs/start.html

**Comment by janos** [comment]
@ldeffenb Of course, and I believe that there is an ongoing effort to have versionized documentation.

**Comment by Eknir** [comment]
Hi guys,

Thanks for opening this issue.

The current docs represent the state of the latest release. Indeed, there is an ongoing effort to have a versioned docs, which aims to document the latest master (even though we will not give 100% guarantees here that it is up-to-date). 

Our help section is self-evident and we deliberately didn't want to include a reference to an up-to-date yaml file in our docs, as this creates an overhead for changing any config parameter. I still would not like to do this, as it is not needed and with a bit of reading you will figure it out yourself (call `bee start -h` and make the parameters into config parameters, as described in the section `start`).

What we could do instead of documentation is to have an API endpoint which answers a yaml file with your current configuration. This would be more self-contained.

**Comment by Eknir** [comment]
WDYT @janos? @Ideffenb , would this be useful for you?

**Comment by janos** [comment]
@Eknir Would a cli command to print the configuration would be ok?

**Comment by Eknir** [comment]
Good for me.

**Comment by nolash** [comment]
> What we could do instead of documentation is to have an API endpoint which answers a yaml file with your current configuration. This would be more self-contained.

or better yet just a template file in the tree which is a pretty common thing after all.

**Comment by ldeffenb** [comment]
@janos Yes, either a command line way to print the current configuration as a .yaml file or an API to return the same.  If I can also request that comments be included showing the default of each parameter, especially those whose current value is not the default.

@nolash A template file can drift out of data unless it is automatically updated with each new release.  I kind of like better having the running version tell me what it thinks its configuration is and/or should look like.

**Comment by ldeffenb** [comment]
In the meantime, is there any documentation as to the format of the nat-addr parameter?  Even though I have the swarm port open via a NAT rule, I don't seem to be getting many, if any, incoming connections.  I suspect part of this may be due to publishing my internal IP instead of my external which it seems the nat-addr would be good for using.  Especially if I can publish it as my dynamic DNS name that automatically tracks my external IP address.

From https://docs.ethswarm.org/bee-docs/start.html
# NAT exposed address
nat-addr: ""

**Comment by janos** [comment]
@ldeffenb The format of `nat-addr` is in the following format `IP:PORT` where these values are NAT public IP and PORT. Thanks for pointing for missing information, we will improve the docs for the flag.

**Comment by ldeffenb** [comment]
@janos  Thanks for the format.  I'll add that to my config and see if I get any incoming connections.

**Comment by acud** [comment]
@significance can you see if the context of this ticket was resolved by the changes deployed to documentation in the recent release?

**Comment by Eknir** [comment]
Closing this issue, as it was covered.
