### ISSUE TITLE
panic in proximity function

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#515]
After running a bee node built with code state on git commit `6efcbfdfc1f8d0f71b889d5a95a44aa2a773ec8a` as part of the testing session within the small network size, the node eventually got terminated with the panic below. It suggests that the Proximity function received a zero length address as the second argument `other` by the kademlia Disconnect function passed by the peerRegistry. 

```
panic: runtime error: index out of range [0] with length 0

goroutine 3194398 [running]:
github.com/ethersphere/bee/pkg/swarm.Proximity(0xc0000ac6a0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x927749a22a34de01)
	github.com/ethersphere/bee/pkg/swarm/proximity.go:28 +0xc4
github.com/ethersphere/bee/pkg/kademlia.(*Kad).Disconnected(0xc0024c8000, 0x0, 0x0, 0x0)
	github.com/ethersphere/bee/pkg/kademlia/kademlia.go:414 +0x6e
github.com/ethersphere/bee/pkg/p2p/libp2p.(*peerRegistry).Disconnected(0xc000304fc0, 0x2061b60, 0xc000083380, 0x205d420, 0xc001136780)
	github.com/ethersphere/bee/pkg/p2p/libp2p/peer.go:77 +0x3fc
github.com/libp2p/go-libp2p-swarm.(*Conn).doClose.func1.1(0x2055b40, 0xc000304fc0)
	github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm_conn.go:84 +0x5b
github.com/libp2p/go-libp2p-swarm.(*Swarm).notifyAll.func1(0xc0018075e4, 0xc0027491c0, 0x2055b40, 0xc000304fc0)
	github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm.go:493 +0x62
created by github.com/libp2p/go-libp2p-swarm.(*Swarm).notifyAll
	github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm.go:491 +0x118
```

**Comment by janos** [comment]
https://github.com/ethersphere/bee/pull/517 is merged, but it only hardens the Proximity function, does not solve the root cause for this issue, so this issue should stay open to investigate why the nil address was passed to the Proximity function as the second argument.

**Comment by pradovic** [comment]
I inspected this problem a bit more, and managed to reproduce the behavior with one "test": https://gist.github.com/pradovic/0ce78bbd0ce886963a51a7e1f3ecb52f. This prints the nil address in disconnected handler on the old code, but after the peer registry fixes this is solved. Additionally, the check that Janos added is also guarding against this, so I believe that we can close the issue

**Comment by janos** [comment]
Thanks @pradovic.
