### ISSUE TITLE
Validate local pinning

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#520]
# Task
- Verify integration tests of local pinning. There might be some edgecases not covered (based on manual testing of global pinning in Swarm). @mortelli knows.
- Go over the theoretical implementation of local pinning and see if there is a potential for data races. @acud has a look, together with @mortelli .

## Acceptance criterea
If no issues:
- A comment on this issue, explaining steps taken to verify functionality

If issues:
- Relevant PRs

**Comment by Eknir** [comment]
@mortelli , could you link your comment on this issue here and provide a recommendation on how to proceed after your and @acud s findings?

**Comment by Eknir** [comment]
https://github.com/ethersphere/bee/issues/248#issuecomment-671552342

**Comment by acud** [comment]
closing this since there's enough info in #248
