### ISSUE TITLE
Print config CLI command

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#522]
Based on the feedback https://github.com/ethersphere/bee/issues/508, it would be helpful to have a new cli command that would print a bee configuration in yaml format to show available parameters.

This can be achieved with viper AllSettings() method on command.config and marshalling it with yaml encoder just as it is done in viper internally, pretty straightforward.

**Comment by Eknir** [comment]
@metacertain , if you already have a PR for this, could you please link it?
