### ISSUE TITLE
Bootnode flag on windows not interpreted correctly

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#525]
On Windows, passing the `--bootnode /ip4/150.136.63.214/tcp/7070/p2p/16Uiu2HAkuZirDbGvhEVc5TF3QS77rpwx6ryz9pUp7qTEqprD5DLZ` was not interpreted correctly.

This issue was discovered at the [testing session](https://hackmd.io/hVr1MklhSRGcbuM7DgTypQ?view) by @metacertain 
![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/983f344c-11c3-4e78-9645-458bfc88178b)

**Comment by Eknir** [comment]
@metacertain , could you please verify whether this bug still persists? If it persists, it would be nice if you could also fix it. If it doesn't, you may close the issue

**Comment by Eknir** [comment]
@metacertain , could you please look into this, closing it perhaps if not reproducible. Thanks

**Comment by metacertain** [comment]
Yes, I can confirm this is still an issue. However, it can be easily worked around by providing the option via a config file rather than a command parameter. 
Because this is an environment specific issue that can be worked around, I suggest this to be handled with a FAQ item

**Comment by acud** [comment]
This does not look like a bug. Enclosing the bootnode address in quotes should resolve the issue. Closing this
