### ISSUE TITLE
Downloading a file with Russian characters

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#527]
A file was uploaded with Russian characters. This could not be accessed.

This issue was discovered at the [testing session](https://hackmd.io/hVr1MklhSRGcbuM7DgTypQ?view).

![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/18f09007-7635-4f4c-9624-c2f7826bceb5)

I suggest to try and upload a file with Cyrillic characters and see if the problem can be replicated. If not, the issue may be closed.

**Comment by Eknir** [comment]
@mortelli

**Comment by Eknir** [comment]
Related: the path-escaped version of the same file does return "invalid path address":

`50.136.63.214:8080/bzz/2058bf6d8e9d693ec7820fc04a1c700992fb63b9dcd819fbaf0d97ce59a1fb46/Wheel%20of%20Time%20(2003).avi%20BG%20subs%20-%20%D0%9A%D0%BE%D0%BB%D0%B5%D0%BB%D0%BE%D1%82%D0%BE%20%D0%BD%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D1%82%D0%BE-UJZAb830qEc.mp4'`

Probably there are some path-encoding problems.

**Comment by mortelli** [comment]
i have tried out uploading a tar with the following:

- `s p a c e s.txt` (content: `hello`)
- `боре иская.txt` (content: `hello there`)
- `Ї.txt` (content: `Б`)

and i have not been able to reproduce the problem. i am able to access all 3 files through the `bzz` endpoint (through the browser):

- `http://localhost:8080/bzz/<hash>/s p a c e s.txt`
- `http://localhost:8080/bzz/<hash>/боре иская.txt`
- `http://localhost:8080/bzz/<hash>/Ї.txt`

this was done on `master`.

**Comment by Eknir** [comment]
Could you try to make a query like
`/Wheel%20of%20Time%20(2003).avi%20BG%20subs%20-%20%D0%9A%D0%BE%D0%BB%D0%B5%D0%BB%D0%BE%D1%82%D0%BE%20%D0%BD%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D1%82%D0%BE-UJZAb830qEc.mp4'`

from `боре иская.txt` ?

I don't know how to do this, but apparently `%20BG%20subs%20-%20%D0%9A%D0%BE%D0%BB%D0%B5%D0%BB%D0%BE%D1%82%D0%BE%20%D0%BD%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D1%82%D0%BE-UJZAb830qEc` is some encoding of Russian characters (see my first comment)

**Comment by mortelli** [comment]
> Could you try to make a query like
> `/Wheel%20of%20Time%20(2003).avi%20BG%20subs%20-%20%D0%9A%D0%BE%D0%BB%D0%B5%D0%BB%D0%BE%D1%82%D0%BE%20%D0%BD%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D1%82%D0%BE-UJZAb830qEc.mp4'`
> 
> from `боре иская.txt` ?
> 
> I don't know how to do this, but apparently `%20BG%20subs%20-%20%D0%9A%D0%BE%D0%BB%D0%B5%D0%BB%D0%BE%D1%82%D0%BE%20%D0%BD%D0%B0%20%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D1%82%D0%BE-UJZAb830qEc` is some encoding of Russian characters of the initial query (see my first comment)

so in this case `боре иская.txt` is escaped as `%D0%B1%D0%BE%D1%80%D0%B5%20%D0%B8%D1%81%D0%BA%D0%B0%D1%8F.txt`.

both the unicode string as well as the escaped string seem to work in the browser.

however, for the `curl` operation, only the escaped version seems to work.

**Comment by mortelli** [comment]
so analogously to what [@zbiljic pointed out](https://github.com/ethersphere/bee/issues/528#issuecomment-671899165) on issue #528, submitting a `curl` with spaces results in an error on `net/http/server.go`.

for this reason, we can consider this request as invalid and out of scope for `bee`.

as far as i'm concerned, this issue can be closed: cyrillic characters do not appear to be an issue in paths.

**Comment by Eknir** [comment]
Can be closed for me.
