### ISSUE TITLE
Auto-render index.html

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#529]
From the usability perspective for the user story [Single Page Websites](https://github.com/ethersphere/bee/issues/418), it would be good if bee automatically renders `/index.html`, such that you don't have to navigate to `<hash>/index.html` to see the webpage. We briefly spoke about this in the call, but I would like discuss this further. Tagging @acud, @janos and @mortelli .

**Comment by mortelli** [comment]
my 2¢:

a reason not to do this is that we would be potentially contaminating at least _some_ of the download code with things specific to rendering HTML websites, while it would be preferable—in terms of design, i think—to have this code be as agnostic as possible in terms of what we are actually downloading, and leave this to a higher level component (maybe `bzz` protocol?). this would also be checked, in principle, for every single download.

a reason to do this is usability and a better ux. this is quite relevant to the end-user approach we have been trying to take in the last few months.

i'd say we have more reason to do this than not, but if we go along with it, let's try to see what the cleanest way to code this is, other than a simple `if`.

**Comment by acud** [comment]
covered by #658
