### ISSUE TITLE
Set up accounting Grafana dashboards

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#531]
For internal usage, we want to validate the working of accounting/settlement. For this, we need Grafana dashboards to interpret the metrics.

Tagging @svetomir @vandot @ralph-pichler

**Comment by vandot** [comment]
@Eknir do we have those metrics exposed?

**Comment by Eknir** [comment]
@ralph-pichler , could you answer @vandot ?

**Comment by janos** [comment]
These are all metrics with `bee_accounting_` prefix.

**Comment by Eknir** [comment]
@vandot, what is the status? I would be happy we have this in our next release, so we can actually monitor how accounting is playing out. Moving the card to the backlog in our KanBan board

**Comment by vandot** [comment]
As @ralph-pichler said, its done
