### ISSUE TITLE
Upload while uploading

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#532]
# User story

## Story

As a user of Swarm who has just uploaded a big file, I want to be able to do another upload while the big file is still uploading, such that I don't get the feeling that my node is crashed.

## Acceptance criteria

- User uploads big file
- User can upload another file while big file is not yet finished

## Background

This issue came up during the [testing session](https://hackmd.io/hVr1MklhSRGcbuM7DgTypQ), where people had the idea that their node didn't work, whereas in fact their pusher was just pushing other stuff.

A solution could be to implement a FIFI queue for the pusher (now it is LIFO), or somehow being able to stop/pause/continue an existing upload.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by mortelli** [comment]
we can test this through 2 scenarios:

- upload a big file through the api, and while it is being chunked/pushed, repeat the same operation for a smaller file, and then verify which is finished first
- upload a big file through the api, and while iti s being chunked/pushed, stop the node. then, start up the node again and upload the smaller file and verify

**Comment by acud** [comment]
i dont understand this ticket. what is meant by `such that I don't get the feeling that my node is crashed`

**Comment by Eknir** [comment]
This ticket was based on real user feedback. It happened that the user uploaded a big file, didn't have verbosity on 5. Now, it took ages for this file to be push-synced, so the user just had the feeling that the upload crashed. He tried to upload another (smaller file), and uploading this file also didn't work, because the pusher was still pushing the big file.

**Comment by Eknir** [comment]
@zbiljic , are you working on this?

**Comment by Eknir** [comment]
@significance ,

Could you be so kind to do some QA on this issue? Verify that it works for some uploads and comment on the UX?

**Comment by significance** [comment]
@Eknir i would love to!
