### ISSUE TITLE
Level DB crash

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#533]
![image.png](https://images.zenhubusercontent.com/5e7c6d2ce969e644bdebbf30/bad25eb7-7e38-4059-a0cc-e000a685ac5b)

Taggin @janos and @zbiljic

**Comment by Eknir** [comment]
@mortelli , I believe you were working on this, right? What is the status?

**Comment by acud** [comment]
not enough info to reproduce or investigate. closing
