### ISSUE TITLE
pullstorage test erro in CI

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#545]
In chuk-repair branch,  macos, race test 
https://github.com/ethersphere/bee/pull/479/checks?check_run_id=958294738

##[error]    pullstorage_test.go:147: want 2 addrs but got 5

```
=== RUN   TestIntervalChunks_NoChunksLater
Error:     pullstorage_test.go:147: want 2 addrs but got 5
--- FAIL: TestIntervalChunks_NoChunksLater (0.60s)
=== RUN   TestIntervalChunks_Blocking
```

**Comment by acud** [comment]
can't reproduce this locally. @janos maybe you would have more luck than me?

**Comment by Eknir** [comment]
@janos @acud , let's try to reproduce and close if it is not reproducable.

**Comment by Eknir** [comment]
Closing this issue, as it cannot be reproduced. Thanks for attempt @acud !
