### ISSUE TITLE
PSS TestDeliver miner timeout error

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#562]
PSS miner timeout is reached after 5 seconds in CI. This should not related to changes in that PR. It is very likely that this test is very slow with race detector running in CI environment.

```
=== RUN   TestDeliver
##[error]    pss_test.go:120: miner timeout error
--- FAIL: TestDeliver (5.00s)
=== RUN   TestHandler
--- PASS: TestHandler (0.00s)
FAIL
FAIL	github.com/ethersphere/bee/pkg/pss	8.042s
```

https://github.com/ethersphere/bee/runs/977526682#step:10:1477

**Comment by Eknir** [comment]
@janos , is this for the next release? If so, let's move the card in our KanBan Board

**Comment by janos** [comment]
This is of low priority, I did not notice that it was repeated since.

**Comment by jmozah** [comment]
This has happened many times.. The best way to fix this is to have a flag to set the timeout value from command line. SO that we can set a high value in CI and default values in production.

**Comment by janos** [comment]
I think that we can just raise the timeout, there is no particular need to be different in different environments.

**Comment by Eknir** [comment]
@janos , did we implement your suggested solution? 

If not (and low priority), shall we just close this issue for now?

If yes, shall we also close the issue?

**Comment by janos** [comment]
Mining was much improved. Closing this.
