### ISSUE TITLE
Pin in retrospect

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#571]
# User story

## Story
As a user of Swarm, I want to pin a file which is already in the network, such that I can persist this content

## Background

Right now, pinning is architected for upload + pin, but it is expected that users want to pin content which is already in the network (and not necessarily already in their local store).

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by ldeffenb** [comment]
I'll second this request as it will support pinning services to simply request the pin instead of needing to fetch the block and then pin, hoping that the fetched block is actually still local in the cache.

**Comment by zbiljic** [comment]
First PR for this (#1045), main change was that now chunks are actually being fetched through `netstore`, which means we are actually checking network for chunks that are being pinned.

The thing that is not changed, and is still "open issue" is what happens if we cannot fetch some chunk that was found for some "root" hash. This relates to traversed chunks for complex structures we support. Current behavior is that as soon as we reach some chunk that is un-accessible, process is stopped. In that case user is left with not complete data, however trying to fetch other chunks really has little point, if something is missing.

There are multiple possible solutions for solving this problem, some of this @Eknir and myself talked about, but I would like to open this issue for further discussion.

**Comment by Eknir** [comment]
Hi Nemanja,

Thanks for your RFC. Indeed, we spoke about it. Let me outline what I can still remember:

For a user, who wants content to be pinned from the network, it is not great if the upload stops somewhere midway. Ideally, the node should continue pinning the best it can, and only then return, with the information that it only partly succeeded.
Obviously, half-pinned content is not valuable for the user. As a user, you only care about stuff that is fully pinned. That is why we must somehow allow for retrying. Retrying makes sense as the content might be re-uploaded or becomes retrievable again.

We spoke about launching an in-node process that would do this retrying, but as you pointed out, this is opening a box of pandora and will look to obscure to the user. Instead, it would be much better, if we facilitate the primitives inside the bee-node for the user to retry. 
The biggest problem is that pinning something for the second time (retrying) will increase the pin-counter for all chunks. The user does not want this; it merely wants to increment the pincounter once for all the content of the root-hash across different retry sessions.
This, you called "idempotent pinning". As a user-story:
`As a pinner of content content that is already in the network, I want to be able to retry pinning content if it was not available or not reachable, such that I will be able to pin all content under a root hash and afterwards easily unpin it again`

I would be happy to hear the reactions of others on idempotent pinning and hear more details about potential complexities w.r.t. implementation.

**Comment by acud** [comment]
> I want to be able to retry pinning content if it was not available or not reachable

I definitely am not in favor of this, for the same reason that your browser doesn't retry when a server returns an error code of most sorts. Retry logic are cumbersome, have their own complexity and are always controversial. Pinning a content which is unavailable already involves a fair amount of hypothesizing and I would not like to support this use case within the `bee` codebase.

**Comment by Eknir** [comment]
@acud , this is a user story and I would say that, as a user, I definitely want to be able to retry. If you cannot load Github (for instance), you also want to be able to retry, no? It indeed does not mean that Github will automatically start retrying for you. The user story leaves it open whether or not this retrying is done inside bee or outside. This is an engineering decision, which I would like to keep myself out. 
@zbiljic told me that currently, a user can not retry pinning, because the pin counter of successful chunks was already incremented. Thus, the node is in a corrupt state when the remote fetch is partially succesful. The user, however, doesn't want to throw away those chunks that were correctly fetched, as they might belong to valuable content. The most logical action that a user can do, hence, is to be able to retry (and ensure that when 100% succesful the state of the node has no corrupted pincounters).

**Comment by acud** [comment]
@eknir you are confusing a few unrelated things:
- the user _can_ always retry pinning (hit F5 or your favorite last command). i'm not sure if I understand why a user _can't_ (you did mention `can not`) retry an operation, which I believe is a concept which does not exist anywhere in the codebase.
- having a corrupt state of counters of pinned chunks is completely unrelated to that and has to do with error handling and the fact that pinning in retrospect is not transactional (i.e. you cannot roll back an unsuccessful transaction, which in this case might be a large set of overarching network operations). this change might be move involved and complex, but I argue that we might not want to cater this problem right away, as some things might be more urgent than this. also, this problem will exist when you upload and pin, but when the upload is broken/incomplete and you upload again. the counters will already be incremented for the chunks that were already uploaded. please bear in mind that taking care of this stuff could potentially mean significant complexity in the codebase, and so even if as a user story we want this, the cost might be high, and so it should be prioritized accordingly.

**Comment by acud** [comment]
also, the problem of being unable to rollback an unsuccessful transaction is something we have _everywhere_, and I argue that supporting it right now could mean significant complexities and it might as well be that our entire storage abstractions might need to be redesigned and rewritten to support this nicely.

**Comment by Eknir** [comment]
Ok guys, thanks all for your input. As I gather from this feed and other channels, it is not desirable to proceed with implementing the full support for retrospective pinning. The issue of retrospective pinning is that we need an abstraction in our localstore component which we currently don't have. Retrospective pinning misses this, but pin during upload is also not ideal without this abstraction.

The dilemma is currently whether we want to spend time on creating this abstraction (bath insert) or not. 

I would propose the following:
1. This user-story  is complete as is (code-wise). Documentation-wise, we should add to our docs how the user can pin in retrospect and how to minimize the risk of corrupting pin-counters.
2. I will make a user story (issue) which will capture the localstore redesign to support batch operations.
