### ISSUE TITLE
Block peer - disable connections to this peer

### ISSUE THREAD

**Issue by pradovic** [ethersphere/bee#589]
There needs to be a way to block a peeer, thus preventing connections to this peer for specified amount of time. More detailed spec and architecture proposal: https://hackmd.io/fLduHj71RVaPktB-8yc_lQ.

**Comment by Eknir** [comment]
@pradovic , thank you for making this. Given that we are gearing up towards the release, I would propose to put this issue at a lower priority now. Let's first finish all that we plan to release. Thanks for making the architecture proposal.
