### ISSUE TITLE
Get chunk directly when available

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#595]
# User story

## Story
As a user of Swarm, I want to get a chunk immediately after it is known to the network, such that I have the most direct response and I don't get disconnected from the network by sending a lot of requests (polling) for chunks that don't exist (yet)

## Acceptance criteria

- A user can somehow subscribe to get a chunk and get this chunk, immediately after it is delivered.

## Background

BOS mentions:
2.3.1 (timeout vs not found)
```
(...) All in all, as long as delivery has the potential to create earnings for the storer, the
best strategy is to keep a pending request open until it times out and be prepared in
case the chunk should appear.
```
Also, fig 48 mentions this feature.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
I have a couple of questions for this:
- How does a node know what the TTL is?
Viktors answer: we pay more, so the more is paid, the higher the maximum TTL. 
- What about the scenario where you are sending a lot of requests, thereby flooding the node with requests (which he now also must store)
My own, naive suggestion: Each node keeps a maximum of chunks requests and don't allow more than those. When more requests than space, purge the oldest ones. This still makes this feature pretty easy to attack by just continuously sending requests, thereby purging the "honest" requests.
- SWAP is supposed to compensate for bandwidth, but what about the storage of the requests (until TTL)? It surely doesn't compensate for that, so I'm not even sure if a node is ever expected to keep requests until TTL
Viktors answer: we can just send more money via SWAP. 
Rinke answer to that: I don't have the feeling this is so easy, as in SWAP you are paying directly to your peer, and the peer is not necessarily incentived to pass this "excess" value to their peers--up to the storer. I don't know how we would incentivize the closest node for storage of requests.

All in all, it seems to me that this feature still has some details to work out, but I might be wrong @zelig .

**Comment by janos** [comment]
To add to the questions about ttl and flooding by @Eknir, would this be a good attack vector? What would be the mechanism to protect from receiving many long living retrieve requests?

**Comment by zelig** [comment]
Request should not be long term subscriptions, so 
- we could simply put a limit to the TTL (like max 30 seconds) and within that not bother with  differential pricing 
@janos so no long-living requests


There is no need to make any special  guard against  preemptive requests, they  are just requests.

- If there is no resource shortage, accept request with TTL and keep them  till after TTL ends. 
- If  there is resource shortage, recieving nodes should raise their swap price or throttle traffic.
-  Frivolous requests (ones that do not have a chunk response after ttl ) should be limited to a small finite percentage of requests, exceeding that limit  will trigger disconnection/blocklisting
