### ISSUE TITLE
Feedback on configuration

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#600]
# User story

## Story

As a user of Swarm, I would like to get direct feedback when I start up my node on the applied configuration variables, such that I know that Bee has applied my custom configuration and I can explore what other configurations to apply

## Acceptance criteria

- Upon startup, the user gets an overview of all configuration parameters applied (minus the privacy sensitive ones, such as password)
- There is no duplicate information (for example, the data base capacity and p2p address is already logged)

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by acud** [comment]
is this really needed?

**Comment by Eknir** [comment]
I think it would be good from a UX-perspective. We already have it for some config parameters (e.g. db-size), but not for all.

**Comment by ldeffenb** [comment]
Maybe only those configuration parameters whose value is different than the default value?  Otherwise the startup burst will get longer and longer as the configuration parameters increase in number.

**Comment by acud** [comment]
> Maybe only those configuration parameters whose value is different than the default value? Otherwise the startup burst will get longer and longer as the configuration parameters increase in number.

In an ideal world yes, however I'm afraid that adding check for this in the codebase will make the node configuration bootstrapping process very verbose and clunky to maintain, since you'd have not just to define the command line parameters and their default values, but also add checks to record any deviation from default values.

**Comment by Eknir** [comment]
Ok, given that this issue got some resistance, I suggest to close it for now. It is/was anyways not a very high priority.

Thanks for participation, guys.
