### ISSUE TITLE
CI fails in coverage

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#604]
CI fails in `coverage` tests. But other tests pass.
This is in branch "global-pinning-test-fix"
See here https://github.com/ethersphere/bee/pull/602/checks?check_run_id=1020637700

go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading github.com/libp2p/go-libp2p-tls v0.1.3
go: downloading github.com/google/uuid v1.1.1
?   	github.com/ethersphere/bee	[no test files]
?   	github.com/ethersphere/bee/cmd/bee	[no test files]
**panic: qtls.ClientSessionState not compatible with tls.ClientSessionState**

**goroutine 1 [running]:**
**github.com/lucas-clemente/quic-go/internal/handshake.init.2()**
	**/home/runner/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.17.1/internal/handshake/unsafe.go:26 +0x205**
**FAIL	github.com/ethersphere/bee/cmd/bee/cmd	0.010s**
?   	github.com/ethersphere/bee/cmd/bee-file	[no test files]
?   	github.com/ethersphere/bee/cmd/bee-join	[no test files]
?   	github.com/ethersphere/bee/cmd/bee-split	[no test files]
ok  	github.com/ethersphere/bee/cmd/internal/file	0.013s	coverage: 64.2% of statements

**Comment by janos** [comment]
This is not a flaky test, it is very direct failure. This is not happening on the master branch as Go 1.15 is supported. But it seems resolved on global-pinning-test-fix branch on more recent test https://github.com/ethersphere/bee/runs/1020701348, after the branch was updated.
