### ISSUE TITLE
API and Debug API documentation

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#62]
As a user or developer I want to have a documentation on exposed API and Debug API such that I can use it to make correct HTTP requests to them.

In order to have a documentation of exposed HTTP APIs, the best format would be OpenAPI 3.0.

A previous attempt to automate generation of such specification https://github.com/ethersphere/bee/issues/62#issuecomment-614781486 resulted in a conclusion that the tooling is not flexible and mature enough, with the suggestion to manually create and update specifications.

OpenAPI specifications can be put into `docs/api/spec.yaml` and `docs/debugapi/spec.yaml` in the bee repository. Autogenerated swagger files https://github.com/ethersphere/bee/blob/go-swagger/docs/api/swagger.yaml and https://github.com/ethersphere/bee/blob/go-swagger/docs/debugapi/swagger.yaml can be used as starting point, but not required.

Specifications should reflect functionalities implemented in `pkg/api` and `pkg/debugapi` packages with their `router.go` files as starting point. Following their handlers, would reveal request requirements and what responses are providing.

Additionally, a static Redoc can be added to the code for easier reading https://github.com/Redocly/redoc#tldr, alongside the spec.yaml files. Probably avoiding external cdn links for page assets.

**Comment by janos** [comment]
An attempt to use go-swagger spec generation from source is available in `go-swagger` branch https://goswagger.io/use/spec.html. It assumes some code structure in order to correctly read comments that include api definitions out of which the final swagger structure is generated. This required defining httputil.UnmarshalMuxVars and httputil.UnmarshalURLValues functions in order to be able to define path parameters and url query values as structures with typed fields. These functions may be good also to have a unified way to declare and validate input variables from url path and query parameters, but require the usage of reflection.

But, even with these problems solved, go-swagger does not work well with custom types, most notably multiaddr.Multiaddr and fails to generate spec. Beside that, a lot of possibilities from spec format 2.0 are not supported, most notably on the response parameters where the response is not a defined struct by arbitrary byte stream.

API documentation can be generated with code on the `go-swagger` branch with `make swagger-api serve-swagger-api` and debug api documentation with `make swagger-debugapi serve-swagger-debugapi`.

Even my intention was to have spec generated from the code, I do not think that go-swagger is mature enough to allow us to produce a quality swagger spec. I would suggest to write swagger spec manually instead, because of the code expectations of go-swagger, problems with custom third-party types and lack of flexibility in defining spec variables.

**Comment by Eknir** [comment]
@janos , what is the status of this issue? Are you still actively working on it, is it blocked?

**Comment by janos** [comment]
I have updated the description yesterday and @metacertain is working on this task.

**Comment by Eknir** [comment]
@metacertain , do I get that you leave this task, for now? Or is it completed? I would like to see this reflected in the board. If completed (or part of the work done), can you describe this here. If you set it aside for now, could you put it please back in the backlog?

**Comment by metacertain** [comment]
@Eknir Yes, I have put this on hold on my side for a while
