### ISSUE TITLE
Add resolver contract address to ENS resolver client and MultiResolver

### ISSUE THREAD

**Issue by paxthemax** [ethersphere/bee#625]
# Task
Currently, both the ENS resolver client and MultiResolver rely on defaults for the ENS address.
The resolver connection string, however, accepts a contract address parameter.
Pass this parameter to the MultiResolver and ENS resolver client. 

## Acceptance criteria
The ENS resolver connects to an ENS contract suite deployed on a different address.

**Comment by Eknir** [comment]
@paxthemax , is this still open? I'm adding it to the backlog as it should indeed be done. Thanks for making this issue!

**Comment by paxthemax** [comment]
I'm looking into this right now.

Of note is the fact that the ENS suite is currently deployed to a **fixed address** on all chains (using CREATE2 mechanics). 

For reference, see: https://docs.ens.domains/ens-deployments

Older versions of ENS, and RSK (and alternatives) may however still use a different address.

**Comment by Eknir** [comment]
Thanks for your research on this.

First of all, Is ENS deployed on all common testnets?

Secondly, if we would go with non-modification of this parameter, then we should remove the modification option from the CLI. As @janos writes: "The resolver connection string, however, accepts a contract address parameter", but I understand from this issue that this parameter is ignored, as we are using the default only.

Given that the work to remove this is also involved, perhaps the easiest way would be to just use this configuration option if it is passed?

**Comment by paxthemax** [comment]
@Eknir Let me clarify further.

The ENS implementation, as of the last available version, is coded with CREATE2, and set up to deploy to an exact address. That means that the Ethereum mainnet, all testnets that have ENS use this address. It also means that any CUSTOM registry deployment (for example to xDai or POA or another chain that is compatible with ENS contracts) will use the same address.
Further, if we choose to deploy ENS on our own blockchain (for whatever purpose) it will still have the same address.

The only possible reason I would see is if we were to use:
1. A legacy version of ENS (higly unlikely)
2. A different name resolution suite deployed on Ethereum

The second option was relevant for RNS/RSK or other name resolution clients, but it is not necessary for ENS.

**Comment by paxthemax** [comment]
If we can agree, I would close this issue and open a separate one to remove the flag from the resolver.

**Comment by Eknir** [comment]
Thank you for your analysis @paxthemax .

In terms of time consumption, could you give me an estimate for

a) removing
b) adding the configuration

I personally believe that potential support for RSK would warrant leaving the configuration option, given that the time consumption for b is not significantly more than a.

**Comment by paxthemax** [comment]
Related issue: https://github.com/ethersphere/bee/issues/1023

**Comment by paxthemax** [comment]
@Eknir - adding the configuration option is mostly trivial. Removing would take more time, but it results in less code overall (which is good).

In any case, if we do not use the parameter, it's important to document it properly - and deprecate its usage if it's not needed.

I will prepare a PR with the implementation.

**Comment by Eknir** [comment]
Hi @paxthemax ,

Given that the adding the configuration is easiest, I would go with that, with as default value the ENS CREATE2 address.

**Comment by acud** [comment]
@paxthemax what are the repercussions of allowing a custom contract address in terms of security and compatibility? since contracts could also be customized, will this flexibility not produce points where compatibility of the bindings can no longer be ensured?

**Comment by paxthemax** [comment]
@acud This is a valid point. From a strict security perspective, ENS contracts SHOULD NOT be loaded from any other address on the mainnet (or really, any other network that deploys ENS contract suite). A user MAY potentially want to use a different name registry implementation that preserves the ENS contract API (ie. for testing purposes), and she would thus require a different address to interact with that contract.

I believe this functionality was deemed relevant for serving the purpose or RNS, as it may deploy to a different address and still have the same contract API as ENS.

If user security concerns are paramount, my view would be to drop this feature: it enforces a safe default for normal operation, and development/testing can be adapted around a fixed ENS address.

**Comment by acud** [comment]
Thanks @paxthemax. I'm ok with the change, but maybe it would be good that we document this once the feature is merged (just add these notes about inability to ensure binding compatibility if a specific contract address is requested)

**Comment by Eknir** [comment]
Great, so to conclude:

- We offer the configuration
- We include documentation that warns the user of using a non-standard ENS address
- We include a warning to the console if the user uses a non-standard ENS address

@paxthemax , agreed?

**Comment by Eknir** [comment]
Needs documentation. Did you know that you can point your Swarm node to any EVM-chain to resolve human readable names?
