### ISSUE TITLE
Spelling mistake -- line 1 Bee docs

### ISSUE THREAD

**Issue by zach-is-my-name** [ethersphere/bee#633]
https://swarm-gateways.net/bzz:/docs.swarm.eth/bee-docs/introduction.html

-- `Dear user, we are happy that you are here. Welcome to the Swarm! Whether you are **hear**...`

++ `Dear user, we are happy that you are here. Welcome to the Swarm! Whether you are **here**...`

**Comment by zach-is-my-name** [comment]
Also, same page, 

```
-- Migrating data is possible **possible**;
++ Migrating data is possible
```

**Comment by zach-is-my-name** [comment]
Again, same page
 
-- Currently, Bee **Bee** provides the functionality
-- Currently, Bee provides the functionality

**Comment by Eknir** [comment]
Thanks @zach-is-my-name ! @significance, could you please look into this and manage this issue?

**Comment by significance** [comment]
relates to old docs, thanks for the report @zach-is-my-name - new docs can be found at https://docs.ethswarm.org
