### ISSUE TITLE
Printed version doesn't match tag

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#649]
Printed version is 0.1.0, while tagged version is 0.2.0.
[version.go](https://github.com/ethersphere/bee/blob/master/version.go) file needs to be updated to match tag version.

**Comment by zbiljic** [comment]
Did the goreleaser used version from tag?

**Comment by svetomir** [comment]
Yes, that job triggers on tag.

`on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'`

**Comment by acud** [comment]
is this not related to the PR that I merged for the version bump? Should we close this?
