### ISSUE TITLE
PSS public facing API

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#650]
support pss notifications through websockets

**Comment by vandot** [comment]
As we talked on the meeting, you can find more about [Cross-Site WebSocket Hijacking](https://christian-schneider.net/CrossSiteWebSocketHijacking.html), it can be mitigated using `Origin` header and some other ways, but exposing ws to the browser and using static port end-user can be [fingerprinted](https://nullsweep.com/why-is-this-website-port-scanning-me/)

**Comment by zelig** [comment]
vandot
regarding websockets 
https://github.com/ethersphere/bee/issues/650#issuecomment-684753818

**Comment by acud** [comment]
related to #663

**Comment by acud** [comment]
@vandot @zelig @janos I looked at the websocket attack vector and I'm not sure they are relevant for this case.

Let me explain my position here:
- If I'm a client and I register a notification handler for a topic, I get my request upgraded to a websocket
- According to the cross site attack vector, an attacker may query a server with a hijacked cookie and possible token, but I cannot see how an external caller, whoever that may be, can gain access to the underlying connection that was established by the client in the first stage
- We can mitigate this sort of attack vector by allowing for one handler websocket per topic to begin with. 
- Multiple listeners can also be allowed, delegating the responsibility for message encryption to the application layer, which seems to be fine by me (applications can implement own wire security using symmetric/asymmetric encryption).

As of such I see no problem with proceeding with a websocket implementation. Would be happy to hear your thoughts about this.

**Comment by janos** [comment]
In this case, it should be ok to have (POST, DELETE) `/pss/subscribe/{topic}` endpoints in the main api as connection upgraded to websocket, for subscriptions. I have the question. Would there bee a need to change nginx ingress in our infrastructure in order to support this endpoints as websockets, or is it better to have a dedicated listener @svetomir @vandot? It would be great if we could use the same existing api.

**Comment by vandot** [comment]
@acud all this risks can and must be mitigated, I just pointed out possible security issues. second thing is user fingerprinting
@janos we would have to make little research what are our options, if we use infra like it is now all ws traffic would go thru single ingress

**Comment by acud** [comment]
@vandot I think @janos meant whether it would be possible to do the connection upgrade to websockets from bee over the nginx ingress as-it-is (since `bee` needs to initiate a connection upgrade that would need to be propagated to the client that requested the websocket)

**Comment by janos** [comment]
@acud thanks for the clarification. That is exactly what I wanted to ask.

**Comment by vandot** [comment]
@acud thanks for clarification, but I am not sure that I understood correctly, its a standard ws setup, client sends request to `ws://something/ws`?

**Comment by janos** [comment]
@acud maybe the best question would be if there are any blockers in infrastructure to have connection upgrades to websocket connections on the same api proxy?

**Comment by vandot** [comment]
@janos AFAIK currently infra lacks support for ws, we need to add standard nginx support for ws
```
location /ws/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

**Comment by janos** [comment]
@vandot cool, this means that we should be good to go?

**Comment by vandot** [comment]
> @janos we would have to make little research what are our options

as noted above, first hand there are some open issues https://github.com/kubernetes/ingress-nginx/issues/3746
for sure its possible to enable wss just have to research it

**Comment by janos** [comment]
Ok, then this task is blocked until the research on infrastructure level is done. Please share your findings @vandot.

**Comment by vandot** [comment]
@janos @acud infra is ready for ws, we are good to go

**Comment by janos** [comment]
@vandot wonderful, thanks.

**Comment by acud** [comment]
thanks @vandot. Integration is already underway in #686. I'll ping you once there's something to test, then we can see if the ingress works or not. We probably need an integration test here too. Would you be able to assist with this? i.e. register ws handle on one node, send a message from another and assert the message was received on the receiving node?

**Comment by vandot** [comment]
@acud of course, all infra tests are done over debug API, with adequate debug API endpoints we can create such a test
