### ISSUE TITLE
Add SOC semantic API

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#651]
Add API endpoints to interact with SOC, but should work together with the signer in order not to expose node keys through the API.
Needs further investigation.

related to #139

**Comment by Eknir** [comment]
Hi @acud, I don't understand what you mean with this issue by how you describe it. Could you please be a bit more verbose? Thanks :)

**Comment by acud** [comment]
@zelig can you help here please?

**Comment by Eknir** [comment]
@zelig or @acud , could you please provide some more information to this issue. That would greatly help with planning. Thanks

**Comment by Eknir** [comment]
@zelig and @acud will sync

**Comment by Eknir** [comment]
QA: Need to validate if #1143 changes are included in openAPI spec. 
Docs: Need to see if we should document SOC / feeds / etc
