### ISSUE TITLE
Protocol init

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#653]
cc https://github.com/ethersphere/bee/pull/585#issuecomment-682599786

**Comment by janos** [comment]
Yes, @pradovic that was one of the inspiration points for this description. Initially, I thought that only Connect and Disconnect events are enough, but it is better to have more control with their direction.

**Comment by pradovic** [comment]
I believe that current protocols work with single Disconnect call, so that one might be possible. The single Connect call is a bit more tricky as Kademlia has a different use-case and needs to treat them differently.
One more thing, maybe I would rename those to `OnConnectedIn`, `OnDisconnctedIn`,  etc.. Not a requirement, but it might be more obvious that those are event handlers.

**Comment by acud** [comment]
LGTM @janos @pradovic. The only question from my side is that if I understand correctly, this will be called directly from the p2p abstraction, however doesn't this also make the peer notification channel redundant?

Also, one reason why I did not, for example, use such notification when implementing pull syncing (where peer connect/disconnect notifications are needed), is that because IMO topology should reflect the source of truth to consumer APIs (for example, APIs that use `ClosestPeer`, kademlia iterators etc), this potentially introduces data races between p2p abstraction and kademlia, since some disconnections can happen between notifications. Therefore, I chose to implement "dumb" notifications and iterate over the peers, rather than providing an exact overlay (which might not be found when looked for in kademlia due to possible data race).

This is at least my 2 cents from what I've stumbled across. Godspeed

**Comment by janos** [comment]
Pull syncing is a bit different, as it relays on the changes to the topology, not just to call handlers per peer connect. For this purpose topology SubscribePeersChange and NeighborhoodDepth is needed, but here (like for payment threshold protocol) a declarative way to specify events per peer regardless of the topology is needed.

**Comment by acud** [comment]
Cool. Looks good from my side then :+1:

**Comment by pradovic** [comment]
Just an idea of how to solve the sync issue. We consider a peer connected, when it is added to the peer registry, so after the handshake. So one way, to solve this kademlia/peer registry sync, could be to make peer registry pslice based (move this part from kademlia protocol too peer registry), and use it from kademlia as well, so we keep tracj of peers in one place, and after the peer is connected it would be in appropriate bin. In this case, it looks to me, Kademlia would be a driver that would be responsible to decide when to try to connect to more peers, etc.. Simiilar to what it is doing now. Basically, what I am saying, it looks to me like toploogy structure could be extracted from the actual driver, and put in peer registry as the source of truth for all other components of the system. It looks to me that it is important/useful to have peers in appropriate proximity bins, more so than in a map, so we could combine.
It does not have to be defined by the p2p abstraction as well, but it could be injected, ti could just have a same interface and p2p would use it when the connection is finished.
Just a wild idea, feel free to ignore it if it does not makes sense :)

@janos, `SubscribePeersChange and NeighborhoodDepth` looks good 👍

**Comment by acud** [comment]
@pradovic it would definitely be beneficial to have one source of truth for all components, in a way that there is no data race between them. In that case, I am not longer sure though, that it should even be in the p2p layer or in kademlia at all. it might be that we can just manage this data inside the address book.

So for example, address book will maintain a list of the connected peers and known peers, and will toggle connection state flags and other information over those peers, such as internal identifiers used by the p2p abstraction. In this case address book can just be injected to both components as it is now. That being said I think such a change is a big overhaul to all three packages, and must be prioritized accordingly.

**Comment by pradovic** [comment]
@acud exactly, I used kademlia and p2p to illustrate to point, but it could be injected where it is needed
