### ISSUE TITLE
Per peer payment threshold

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#655]
# User story

## Story

As a user I want to be able to use different payment threshold with different peers so I can start with lower payment threshold with less trusted peers and increase it over time.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
This is important, but I suggest to put it on hold for now as there are more important things w.r.t. the chequebook. Related is @metacertain's proposal on [best effort accounting ](https://hackmd.io/ENFsiHxsQxSEzZZhrwlnLA)

**Comment by Eknir** [comment]
@paxthemax , this could be something

**Comment by acud** [comment]
@ralph-pichler @metacertain could you evaluate whether this is still necessary and if not close the issue?

**Comment by metacertain** [comment]
So a progressively growing payment threshold still seems like nice to have to me.
The intention here is, when we have a new connection, we probably want to provide it with a minimum payment threshold to disincentivize bunny-hopping connections. But, having a minimal payment threshold means being able to queue less requests (by reserve limits) which has a throttling effect in itself.
Having a strategy to grow payment thresholds for a p2p connection over time would allow both having minimal initial payment thresholds for safety and being able to undo the effects of this initial request reserve limit throttling on p2p connections persisting on the mid term.

**Comment by Eknir** [comment]
@metacertain, you addressed this issue in one of your recent PRs, right?
