### ISSUE TITLE
Access website on root path (/)

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#658]
As a user I'd like to access a website by writing the swarm reference in the address bar, without specifying a specific file to access (for example `/index.html`)

- [x] #647

**Comment by janos** [comment]
I would like to start a discussion on what functionality this feature should provide.

Possible solutions:

## 1. Define default path for just the root of the collection

Specify which file should be served under `/`. For example `localhost:8080/bzz/swarm.eth` specifying the value for default path `/index.html` would serve `localhost:8080/bzz/swarm.eth/index.html`.

## 2. Define "index" file name for all directories

This is similar like the "index" directive in nginx configuration. Default path would be the filename relative to the current directory in the collection. For example, specifying "index.html" as defaultpath in this case would serve directory roots in with this mapping:

`localhost:8080/bzz/docs.swarm.eth`: `localhost:8080/bzz/docs.swarm.eth/index.html`
`localhost:8080/bzz/docs.swarm.eth/installation`: `localhost:8080/bzz/docs.swarm.eth/installation/index.html`
`localhost:8080/bzz/docs.swarm.eth/quick-start`: `localhost:8080/bzz/docs.swarm.eth/quick-start/index.html`

## 3. Define default path for every directory

Allowing to set a specific file for each and every directory would be the most robust setting, which is also possible with nginx configuration. In this case, every directory would be able to specify its own "index" file within its path.

## My opinions

While 3. gives the most functionality to the user, I would say that it is not so common and that 2. should be the most useful option. Feature 1. is just too restrictive as it does not provide functionality for static websites serving. I would go with feature 2.

This feature is just one of the features that are needed for website hosting. And I think that it should be designed alongside features such are:

- error page: allows custom error page, but more important serving the default path for any path that is not found, to support single page javascript apps with routers
- directory listing: how a user would configure which directory should have a list of its files, or the default path should be served

cc @zelig @Eknir @acud @zbiljic @significance and anyone else who would like to participate

**Comment by acud** [comment]
Great write-up @janos, many thanks for this. I agree that `2` would be the best option and gives at least the minimum set of features we need to deliver here, but the thing which I am only afraid of in this context is that if this setting is written only at the root of the manifest, then we lose the ability to redirect to the error/index page once we do not traverse the manifest from the root. 

Also, since this is a recursive data structure, it is not clear to me if implementing `1` or `3` would actually be any different.

**Comment by janos** [comment]
For 2. the setting would have to be implemented in the root of the manifest, or in order not to traverse from the root, to have it under every branch, which brings the option 3. very doable (as you said), just to figure out what would be the ux to configure such options.

**Comment by Eknir** [comment]
Can this issue be closed?

**Comment by janos** [comment]
I would like to hear if @zbiljic would have to have something to add he does some analysis, as we recently discussed about possible improvements to the pr that got merged.
