### ISSUE TITLE
panic on kademlia disconnect

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#664]
reported by `michelle_plur`:
```
panic: runtime error: index out of range [0] with length 0

goroutine 1492577 [running]:
github.com/ethersphere/bee/pkg/swarm.Proximity(0xc0000374a0, 0x20, 0x20, 0x0, 0x0, 0x0, 0x7e826ca80ae00d01)
    github.com/ethersphere/bee/pkg/swarm/proximity.go:28 +0xc4
github.com/ethersphere/bee/pkg/kademlia.(Kad).Disconnected(0xc00106e000, 0x0, 0x0, 0x0)
    github.com/ethersphere/bee/pkg/kademlia/kademlia.go:414 +0x6e
github.com/ethersphere/bee/pkg/p2p/libp2p.(peerRegistry).Disconnected(0xc0000bc2a0, 0x143d240, 0xc000083380, 0x1438a80, 0xc00140e080)
    github.com/ethersphere/bee/pkg/p2p/libp2p/peer.go:77 +0x3fc
github.com/libp2p/go-libp2p-swarm.(Conn).doClose.func1.1(0x14313a0, 0xc0000bc2a0)
    github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm_conn.go:84 +0x5b
github.com/libp2p/go-libp2p-swarm.(Swarm).notifyAll.func1(0xc002b316b0, 0xc0023f7d50, 0x14313a0, 0xc0000bc2a0)
    github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm.go:493 +0x62
created by github.com/libp2p/go-libp2p-swarm.(*Swarm).notifyAll
    github.com/libp2p/go-libp2p-swarm@v0.2.8/swarm.go:491 +0x118
```

**Comment by janos** [comment]
This trace suggests that the panic occurred on the code before fixes related to the Proximity function and peer registry. Related issue https://github.com/ethersphere/bee/issues/515.

**Comment by acud** [comment]
yeah i thought so too, but documented this nevertheless. it seems there is no command to check the git revision with which the binary was built with. we had this with swarm. should we add this to bee? i get only `0.x.x-dev` when i do `bee version`

**Comment by janos** [comment]
@acud we did have this but it was removed by @svetomir because of warnings printed if there is no .git directory. Maybe it would be useful to have something like this https://github.com/ethersphere/bee/commit/dc1951843baeebbe7dc417216e86cc5ab6cd9fc4#diff-b67911656ef5d18c4ae36cb6741b7965L4 back or handle the warning case somehow differently?

**Comment by acud** [comment]
This is most probably fixed. Closing
