### ISSUE TITLE
Balances integration test

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#671]
P2P message exchange in bee is incentivized within some protocols (retrieval and pushsync). The first step is to have accounting between peers in order to trigger a settlement between each of them. Currently every node holds balances with every node that it exchanged incentivized messages. Debug API contains balances endpoint which provide information that can be used to validate the accounting.

This Beekeeper test should validate the accounting on the high level, checking only the symmetry of balances between all peer pairs. This test does not validate a specific retrieval or pushsync message accounting, or any other protocol message exchange that may be incentivized. Such test may exist, and can be added later, but it would be highly coupled with other protocols. For every incentivized protocol, a separate balances test can be made.

## Scenario

The test should be performed on a clean or a cluster that already has some state. In both cases balances should be symmetric.

Options:
- number of nodes in the cluster
- file size
- number of upload/download iterations to perform

### Steps

1. Upload a file with random data to a randomly selected node in the isolated cluster (trigger pushsync protocol).
2. Validate the balances.
3. Download a file from a randomly selected node (trigger retrieval protocol).
4. Validate the balances.
5. Go to 1. unless the configured number of uploads is reached.

### Balance validation

Balance validation should be done in a loop until it stabilizes as protocols may be still exchanging messages after the upload (pushsync). It is good to validate that the balances are being dynamically updated, instead to use other mechanisms, like tags, to wait for pushsync to finish.

1. Get balances from every node in the network.
2. Validate that there are balances and that they are not equal to 0. If not, wait for a short time and go to 1. until a retry count limit is reached.
3. Compare that every node pair has a symmetric balance (zero sum). If not, wait for a short time and go to 1. until a retry count limit is reached.
4. Compare if all balances are the same as in the previous iteration (they have stabilized) if it is not the first iteration. If they are, exit the loop.
5. Store balances for the stability check in step 3. for the next iteration.
6. Wait for some time (2-3 seconds), go to 1.

**Comment by svetomir** [comment]
Beekeeper v0.2.20 can be used for testing balances: `beekeeper check balances`
Executing it with options `--dry-run` will just validate balances without uploading/downloading a a file.

Right now it seems like there is an issue with cluster balances. After uploading one file to the cluster, balances never reached symmetric state. Here is check printout from the cluster in the namespace **svetomir**:
`./dist/beekeeper check balances --dry-run
Node ef3e7035fca1abe1dfd2a4156b950f914357a4ee84af39f0ced9f12dc126f690 has balance 3870 with peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -3780 with node ef3e7035fca1abe1dfd2a4156b950f914357a4ee84af39f0ced9f12dc126f690
Difference: 90
Node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -5590 with peer 1751cd48bc65c84ddae5f6ad661f1e6edf26a0fb8fc4366c0730e49e454ed343
Peer 1751cd48bc65c84ddae5f6ad661f1e6edf26a0fb8fc4366c0730e49e454ed343 has balance 6150 with node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Difference: 560
Node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -9630 with peer c19d8bcb3402ef4d3a2dcdea9dfd010d9093ca0dc7217a532da56837bdd9e9ab
Peer c19d8bcb3402ef4d3a2dcdea9dfd010d9093ca0dc7217a532da56837bdd9e9ab has balance 10890 with node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Difference: 1260
Node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -3330 with peer e0aa5b66c2352b4697bfa75e0f17fe690f37a2e5bef3d77718e2c33fb2c0c04a
Peer e0aa5b66c2352b4697bfa75e0f17fe690f37a2e5bef3d77718e2c33fb2c0c04a has balance 3470 with node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Difference: 140
Node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -3780 with peer ef3e7035fca1abe1dfd2a4156b950f914357a4ee84af39f0ced9f12dc126f690
Peer ef3e7035fca1abe1dfd2a4156b950f914357a4ee84af39f0ced9f12dc126f690 has balance 3870 with node 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Difference: 90
Node 1751cd48bc65c84ddae5f6ad661f1e6edf26a0fb8fc4366c0730e49e454ed343 has balance 6150 with peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -5590 with node 1751cd48bc65c84ddae5f6ad661f1e6edf26a0fb8fc4366c0730e49e454ed343
Difference: 560
Node c19d8bcb3402ef4d3a2dcdea9dfd010d9093ca0dc7217a532da56837bdd9e9ab has balance 10890 with peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -9630 with node c19d8bcb3402ef4d3a2dcdea9dfd010d9093ca0dc7217a532da56837bdd9e9ab
Difference: 1260
Node e0aa5b66c2352b4697bfa75e0f17fe690f37a2e5bef3d77718e2c33fb2c0c04a has balance 3470 with peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33
Peer 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 has balance -3330 with node e0aa5b66c2352b4697bfa75e0f17fe690f37a2e5bef3d77718e2c33fb2c0c04a
Difference: 140
Error: invalid balances`

**Comment by janos** [comment]
Thanks @svetomir. I assumed that balances should be symmetric between peer pairs on upload or download. In this case only one upload happened, pushsync pushes the chunks and peers balances should be changed symmetrically from the uploader to the peers that is pushed to. In this case the uploader is 0a1641d655548ca9c53d5099c83014f74077a5971bad3b0e279c022623015d33 and all other peers should have a balance with it, as they do, but not symmetrical. Is there something else that we are missing @ralph-pichler?

**Comment by ralph-pichler** [comment]
@svetomir hm, that does not look good. Seems the difference is about 1-3 chunks worth. Not sure what could cause this, will try to replicate and investigate.

**Comment by ralph-pichler** [comment]
ok, I tried this with setting the push sync prices to 0 and it's valid balances, so at least retrieval works and imbalance comes from push sync.

**Comment by ralph-pichler** [comment]
disabling the delivery callback fixes this, so there seems to be some weird effect between the handler not found error from pss and accounting.

**Comment by svetomir** [comment]
Merged
