### ISSUE TITLE
Top up batch of existing content

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#688]
As an end-user I'd like to top-up an _already existing_ upload of mine using the BZZ Token, such that my upload is persisted for a longer period of time.

Scope of work:
- [ ] top up an existing batch on chain
- [ ] implement notifications to NN nodes the update their GC

**Comment by Eknir** [comment]
Hi @acud , seeing this issue now. I have the feeling that for now, having this issue comes too early. We are still at the phase of designing the whole solution. I think we can only start making issues once the common ground is established.

**Comment by Eknir** [comment]
^ if there are more issues like this, then my comment on this issue can be considered for all other issues which are about details for storage incentives.

**Comment by acud** [comment]
a task to tackle this already exists on youtrack
