### ISSUE TITLE
Settlements integration test

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#698]
This beekeeper check should be very similar to the [balances integration test](https://github.com/ethersphere/bee/issues/671) as it should validate only the state in be after balances between two peers reaches the threshold and the settlement happens. Balances and settlements information are available over debugapi endpoint.

Threshold values are important for this test which can be set with cli flags, but default values should be used.

Options:

- number of nodes in the cluster
- file size (default should be a larger in order to reach settlements in less iterations)
- number of settlements to detect

## Steps

1. Keep a global internal balances map for all peer pairs for validation and a map of expected settlement count.
2. Upload a file with random data to a randomly selected node in the isolated cluster (trigger pushsync protocol).
3. Validate the settlements.
4. Download a file from a randomly selected node (trigger retrieval protocol).
5. Validate the settlements.
6. Go to 2. unless the configured number of settlements to be detected is reached.

## Settlements validation

Balances validation is already done in the balances check and no explicit validation is needed here. This check does use information from balances but is testing settlements.

Steps:

1. Get balances from every node in the network.
2. If balances contain values which are greater than threshold values, go to 1. and retry with some shorter sleep period for limited number of times.
3. Get settlements from every node in the network.
4. For every balance against the global internal balances map, check if it has reduced (expecting settlement) and validate that there has been a symmetric settlement between these peers, if does, validation is good.
5. Wait for some time (2-3 seconds), go to 2.

**Comment by svetomir** [comment]
Beekeeper v0.3.0 supports this test
