### ISSUE TITLE
swarm spans are uint64, but io.Writer and Seek methods use int64

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#708]
Swarm spans use `uint64`, but the writers that we use and the native golang interfaces use `int64` for reads and seeks.
It is not entirely clear on how this affect the binary and how seeks and reads will be affected beyond the `int64` upper bound. It might also be a sort of attack vector, but needs further examination.

related to #619

**Comment by Eknir** [comment]
@acud, what is the status of this?
