### ISSUE TITLE
pipeline splitter: add unit tests

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#710]
The current hashtrie writer implementation is covered by the `builder` tests that check that an entire test vector results in a certain root hash.

Since we've broken down the writers into their own packages, making a unit test for the hashtrie writer is necessary.
The scope is to take the existing test vectors of which data chunks' are being deterministically generated, generate the individual bmt hashes which are being written to the hashtrie writer and extract them into a `testdata` file that will contain the fixture of sequenced bmt hashes that need to be written to the hashtrie writer. It would then verify that the correct root hash is generated.

related to #619

**Comment by Eknir** [comment]
This still needs to be done @acud ?

**Comment by acud** [comment]
already done
