### ISSUE TITLE
Allow components to trace

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#724]
Currently our tracing works over p2p streams.
In an attempt to add tracing to pull sync, it has clarified that we cannot add this sort of tracing immediately due to the p2p stream tracing limitation.

The main problem is, that in order to actually see chunk propagation across peers, we need to remember opentracing spans per chunk, i.e. we need to be able to pass opentracing spans per chunk, remembering the context with which a chunk came with, and sending that same context with the chunk whenever it gets synced out again to another peer.

This probably means we should be able to pass a `TraceID` or similar on the protocol level with the actual chunks.

We should be able to allow components to trace somehow using the tracer, this should be generalised not just to cater for this use case obviously, but other use cases should be also thought through.

**Comment by janos** [comment]
The encoded tracing span can be a part of protobuf messages. One most simple approach is just to include the data in pb.Delivery message, and just create a helper functions for common operations. Another approach would be to encapsulate the message, but I think that a simpler approach would be better.

**Comment by acud** [comment]
So if I understand correctly, the second approach would be to have some general `pb.Trace` that would be embedded in the messages we'd like to trace? And the first one would just be to have an optional field on the message that would contain the serialised span data?

**Comment by janos** [comment]
Correct, just a simple proto bytes field.

**Comment by acud** [comment]
Sounds right. Do we actually need to do serialization of the span? Can't we just pass along a unique identifier that identifies the opentracing span and just this as serialization? Or is the data includes more information?

**Comment by janos** [comment]
`opentracing.Tracer.Inject` should be used in order to have all information needed passed. It is already used in `tracing.Tracer.AddContextHeader`.

**Comment by acud** [comment]
Got it. But then we should somehow change the tracer to have its own data type wrapping the data, so that other packages do not use the `p2p.Headers` type for this, right? possibly p2p should also use this data type

**Comment by janos** [comment]
p2p.Headers do not have anything with the tracing, encoded tracing span is just passed using headers. There is no need to complicate things with another data type, opentracing provides just very nice methods to serialize and deserialize to byte slices.

**Comment by acud** [comment]
i mean it in the sense that the tracing package should not have notions of data types from the p2p package, so we can reuse the same functions both for p2p tracing and component level tracing.

**Comment by janos** [comment]
I see, let's then move p2p related functions from tracing to p2p package. Good point.

**Comment by Eknir** [comment]
Hi guys, what is the status of this? 
Can we make a follow-up task from this discussion?

**Comment by janos** [comment]
Passing tracing spans should be trivial to add to protobouf messages in order to connect them, where needed. We should identify which messages should have that field.

**Comment by Eknir** [comment]
Hi @janos , as this is an issue, labeled `question`, could you perhaps close this issue if the question is resolved and add an issue/ issues that would stipulate the task, as identified in this thread?

**Comment by janos** [comment]
I think that we should add more complexity where needed and that currently I do not see the need to change the tracing package. Passing a tracing span with messages should be added where needed only in the messages themselves.

My opinion is that this issue can be closed and reopened when needed by prioritization.

**Comment by Eknir** [comment]
Closing the issue, per your suggestion.
