### ISSUE TITLE
Invalid root chunk 

### ISSUE THREAD

**Issue by svetomir** [ethersphere/bee#730]
I am seeing these errors in the cluster (namespace: svetomir, node bee-4) that runs latest master.
Got the error while running ```beekeeper check balances```

```time="2020-09-22T15:51:07Z" level=trace msg="retrieval: requesting chunk 98935a5f62a91eae6d0571be759ef65d9845c61b7ae8c5d88db73422b4420546 from peer c5b6687625b8d153e7fdad0b0ef01f9a7435c53f3239ca629e7bd9fde953bab8"
time="2020-09-22T15:51:07Z" level=debug msg="retrieval: failed to get chunk 98935a5f62a91eae6d0571be759ef65d9845c61b7ae8c5d88db73422b4420546 from peer c5b6687625b8d153e7fdad0b0ef01f9a7435c53f3239ca629e7bd9fde953bab8: read delivery: stream reset peer c5b6687625b8d153e7fdad0b0ef01f9a7435c53f3239ca629e7bd9fde953bab8" traceid=2abb43848f97e0c3
time="2020-09-22T15:51:07Z" level=debug msg="api download: invalid root chunk 98935a5f62a91eae6d0571be759ef65d9845c61b7ae8c5d88db73422b4420546: failed to retrieve chunk, recovery initiated" traceid=2abb43848f97e0c3
time="2020-09-22T15:51:07Z" level=error msg="api download: invalid root chunk" traceid=2abb43848f97e0c3

**Comment by acud** [comment]
This is in fact not an invalid root chunk but the wrong error returned from `netstore`

**Comment by jmozah** [comment]
This is sighted when the chunk is pushed to network in global pinning too.
level=trace msg="chunk repair: error while sending chunk or receiving receipt: new stream for peer b62672cc3e61f0e7450a4e6b1ca182bbe4451b5afa0269d3368a1526434dc76a: send headers: write message: context canceled"

**Comment by acud** [comment]
looks like different things. one is a stream reset, the second is context cancelled.
