### ISSUE TITLE
Add a way to withdraw eth and bzz from the node

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#768]
# Task

`/chequebook/deposit` and `/chequebook/withdraw` allow moving bzz between chequebook and overlay, but there is no way to get the bzz or eth out of your node again (unless if using clef, then an external tool can be used).

**Comment by Eknir** [comment]
@ralph-pichler , does this issue still makes sense if we would only support CLEF with Bee?

**Comment by ralph-pichler** [comment]
> @ralph-pichler , does this issue still makes sense if we would only support CLEF with Bee?

yes, because even it that case the user should not send other transactions (outside of the bee logic) from the same account.
