### ISSUE TITLE
Add rules or "ui" signer for clef

### ISSUE THREAD

**Issue by ralph-pichler** [ethersphere/bee#769]
# Task

Right now clef integration is only usable with very permissive rules or in `--advanced` mode (basically allowing rejected requests). There should be either 
* a proper ruleset
  * has to be es5 without external dependencies
  * see https://github.com/ethereum/go-ethereum/tree/master/cmd/clef#ui-api for examples
* or a "ui"-signer which wraps around clef and approving via `--stdio-ui` 
  * "ui"-signer starts clef, the communicates over a rpc protocol over stdio with clef
  * advantage is the rules can be written in anything
  * disadvantage is no access to secure storage
  * see https://github.com/ethereum/go-ethereum/tree/master/cmd/clef#ui-api

Either way the bare minimum we should have is this:
* clef automatically exposes at least one account (`ApproveListing`)
* clef automatically allows the following messages in `ApproveSignData`:
  * the public key recovery message (the string `public key recovery message` with eth prefix)
  * signing cheques (eip-712 messages described here: https://github.com/ethersphere/swap-swear-and-swindle#data-formats)
    * if possible check chequebook address
    * max cumulative value might be useful
  * signing the handshake
    * clef must be able to sign the handshake data. right now it can only be identified by its length.
  * signing SOCs
    * this also uses the signer, it is unclear how to recognise this.
* sending transactions
  * don't allow eth value in transactions
  * allow chequebook deployment transactions (`deploySimpleSwap`)
  * allow ERC-20 transfers with bzz token
     * ideally we would auto-allow transfers only to the previously deployed chequebook, but we cannot find out that address on the clef side
     * perhaps the recipient of the first transfer should be stored as the chequebook, this can the be checked when signing cheques
  * allow calling `cashChequeBeneficiary`
     * check recipient is our account  

## Acceptance criterea

Bee works with clef without too permissive rules.

**Comment by Eknir** [comment]
Hi @ralph-pichler,

Given that we have the package bee-clef now, would you change anything to this issue? Could you please tell me what, from a user standpoint, this feature adds on top of what we already have?
Thanks

**Comment by acud** [comment]
@ralph-pichler can we extract the low-hanging fruits here and close the issue?
