### ISSUE TITLE
bee start --help

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#780]
Entering the command "bee start --help" doesn't display the help, but requires a bzzaccount?  This is with a fresh build of 0.3.0-2696c81.

D:\Swarm-Bee>swarm start --help
INFO [09-28|11:56:58] Maximum peer count                       ETH=25 LES=0 total=25
Fatal: bzzaccount option is required but not set; check your config file, command line or environment variables

# Task

## Acceptance criterea
Help should be displayed

**Comment by janos** [comment]
> D:\Swarm-Bee>swarm start --help

Should this be `bee start --help`?

**Comment by ldeffenb** [comment]
Ok, had a memory lapse and ran my ancient swarm client which is somewhere on my path.  Closing now as completely bogus.  Is there a way to delete the entire issue?

**Comment by janos** [comment]
All fine, @ldeffenb. Thanks for reporting, as always. :)
