### ISSUE TITLE
pusher: error while sending chunk, stream reset

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#782]
I've been running the new 0.3.0 bee since the start of the beta kickoff and it was going smoothly, and very quiet with --verbosity 5.  So I took the next step and pushed a few files into the swarm.  The first set of 3 files went without issue, and I watched my peer balances go slightly negative as the pusher pushed out the chunks.  So I added another few files and now my client provides a continuous stream (the same burst every 5 seconds) of the following error messages.

time="2020-09-28T17:43:49-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 75fd033606850daa635c51a2904833556bfc6498f800c99ed2bc6f8a35465483: stream reset"
time="2020-09-28T17:43:49-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 75fd033606850daa635c51a2904833556bfc6498f800c99ed2bc6f8a35465483: stream reset"
time="2020-09-28T17:43:49-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 75fd033606850daa635c51a2904833556bfc6498f800c99ed2bc6f8a35465483: stream reset"
time="2020-09-28T17:43:49-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 75fd033606850daa635c51a2904833556bfc6498f800c99ed2bc6f8a35465483: stream reset"
time="2020-09-28T17:43:49-04:00" level=debug msg="pusher: error while sending chunk or receiving receipt: receive receipt from peer 75fd033606850daa635c51a2904833556bfc6498f800c99ed2bc6f8a35465483: stream reset"

I thought this might be related to #781 but maybe not since that peer has a -5.34k balance which to me would imply that it, or at least I, am tracking a balance on the connection.  Thoughts?

And is there a way I can "red-list" this peer so that I'm not wasting bandwidth trying to push to it?

**Comment by acud** [comment]
@ldeffenb if there's no problem you can pinpoint then we're all good and this issue can be closed. running a node with `--verbosity 5` can yield a lot of output into the terminal and unless the node's performance is impaired in some way which you can somehow describe, logs won't necessarily account for an incorrect behavior. pusher streams can sometimes reset in the network, this is not suggestive of any problem :+1:

**Comment by acud** [comment]
@ralph-pichler is there anything suspicious with the balance that @ldeffenb reported?

**Comment by ldeffenb** [comment]
@acud The only issue I see in this report is the fact that it happens over and over and over again, every 5 seconds.  That seems like something we really don't want the network doing and would seem to indicate some sort of error on either the pusher or the recipient of the push.  Maybe the pusher should give up after some number of retries or something.

I'll try to duplicate this issue and provide better details at some point.

**Comment by ralph-pichler** [comment]
The issue here most likely is that the push fails further downstream. Most likely because some node is pushing to a non-swap node or is stuck in an overdraft mode (due to an issue in accounting that I'm currently fixing). Until this is fixed and we updated prod cluster this push issue will most likely persist.

**Comment by ldeffenb** [comment]
@ralph-pichler Thanks for that heads-up.  With that in mind, I'll go ahead and close this issue.  Once I see notification that the prod cluster has the non-swap node and overdraft fixes, I'll try to duplicate and (re)document any pusher redundancy that I see.
