### ISSUE TITLE
Cheques do not indicate they were cashed out

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#783]
I don't know if #766 will address this but currently there seems to be no indication that a check has been cashed out.  I just did the following sequence:

chequebook/cheque - To see the recent checks from all peers, selected one peer to cash out (ab1bde4b8befa8d744e9285d98ded8ba217abb04af5ae175ba21de64f7ed2c29 with a payout of 450100)

chequebook/cashout was done on that peer - got back a transaction ID

Watched on etherscan for the transaction to complete.

chequebook/cheque and chequebook/cheque/peer both still show the check with no apparent change in status.

chequebook/cashout was done again on the same peer.  got back a new transaction ID.

Watched on etherscan for the transaction to complete.  It succeeded with 0 bzz transferred (but of course, transaction gas paid).

Repeated a third cashout with the same result.

If #766 doesn't plan to address this, then it seems that at least some indication should be flagged on a check that it has, or at least been attempted, to be cached out.

My Goerli Account: 658862e22f50981e4bb37c4f76cfb11a59f72c13
My Chequebook: CFF7CdA70B1e70F8323B4EfB1d7d2AB5437C3C04
Peer Chequebook: f90Ba42843225AA42Ea9F30121ea357f89335924
Transactions: 
250d2179096e2e8aae568ff99acda652efbd7030293f60bbdc153cc75ecba714
6a14ffa4d7e189235db73248193bee9494c731fafd313630bf56826ed2b05a7a
c9eca718edfa901896f763bfaaf7c0a9fd0a308bc257d57daf38c3c58652744d

And the check still looks like:
/chequebook/cheque/ab1bde4b8befa8d744e9285d98ded8ba217abb04af5ae175ba21de64f7ed2c29
{
  "peer": "ab1bde4b8befa8d744e9285d98ded8ba217abb04af5ae175ba21de64f7ed2c29",
  "lastreceived": {
    "beneficiary": "0x658862E22f50981e4Bb37C4F76cFb11a59F72c13",
    "chequebook": "0xf90Ba42843225AA42Ea9F30121ea357f89335924",
    "payout": 450100
  },
  "lastsent": null
}

**Comment by ralph-pichler** [comment]
bee currently does not monitor transactions so it does not really know if a cheque was already cashed out and the cashout endpoint will happily attempt to cash the same cheque twice (with the difference being 0). the only way to query cashout status is to `GET /chequebook/cashout/<peer>`.  the already cashed out amount might be added to `/chequebook/cheque` in the future. `POST /chequebook/cashout/<peer>` will not allow to cash the same thing twice.
