### ISSUE TITLE
PSS integration tests

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#797]
Beekeeper PSS integration tests are necessary to verify that messages are passed correctly between nodes.

The test should be very simple and should be conducted in the following manner:
In a given cluster of `n` nodes, select two random nodes `a` and `b` and establish a websocket message listener node `b`, using the PSS API on topic `t`, which is a known string set up in the test.
Node `a` should then try to send a message to node `b` using the PSS API, given only the first two bytes of `b`'s overlay address.
The test end successfully when the message is then picked up on node `b` with the handler delivering the message to the listener (the beekeeper process).

The test should execute for `n/2` times before completing.

The test should record:
- Time until message sent (time to mine the message), for each individual round
- Time from initial request (before send) until actually receiving the message from the other end

The existing PSS unit tests in the `bee` API can be used as reference.

**Comment by Eknir** [comment]
Hi @zelig , this was an issue from the last sprint, but I assume it is not done? Could you please report on the status and how you think we should best proceed with it?

**Comment by Eknir** [comment]
@svetomir , can I assign this one to you? Meaning, you will stay on top that you get the requirements from the devs who implemented this and/or make the test?

**Comment by Eknir** [comment]
@zelig , this issue needs more detail (from you), so that @svetomir can work on it. @svetomir , can you outline what details you would need to make the integration test for PSS?

**Comment by svetomir** [comment]
@Eknir @zelig we need description of testing scenario with all steps that need to be executed in order to test some feature.
This is an example of a well described test case: https://github.com/ethersphere/bee/issues/79
