### ISSUE TITLE
Run Beekeeper periodically

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#798]
Currently, we are relying on running Beekeeper tests in our CI flow.

There is a need for running the Beekeeper tests periodically on an aws cluster with more (e.g. 30) nodes.

Suggestion is to run it once a day (or once every two days) if there has been a merge to master.

Run on isolated staging cluster and public staging cluster

**Comment by vandot** [comment]
Implemented inside merged PR. Once per day action will be executed that will check if there were any commits to the master, if yes it will spawn cluster of 20 nodes and execute beekeeper test and notification will be sent to [#argocd-notifications](https://beehive.ethswarm.org/swarm/channels/argocd-notifications) channel, when testing is done it will destroy testing cluster and underlying infra
