### ISSUE TITLE
Beekeeper: all tests must be green

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#799]
Currently, not all beekeeper tests are green. 

This issue will be an epic, under which we will list all non-green integration tests, which we can then make green.

**Comment by Eknir** [comment]
@acud, can I assign this one to you? Please adjust the issue body, as you also wanted to focus on the correctness of the tests.

**Comment by Eknir** [comment]
- global pinning, maifests and local pinning failing

**Comment by Eknir** [comment]
@acud @janos , see note which I made during last sprint planning. Could you:

- please assess whether these points are already resolved, 
- make separate issues for those beekeeper tests which are not yet consistently green, 
- assign them to the right people, 
- assign them to the current sprint milestone (if applicable) and 
- close this issue afterwards?

**Comment by janos** [comment]
The current state is that `manifests` check is fixed, and `chunkrepair` is still failing. I believe that @acud is working on new `localpinning` check.

**Comment by Eknir** [comment]
Closed, in favor of more specific issues (#884 #849)
