### ISSUE TITLE
pusher stalls, no timeout reading receipt

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#807]
I've noticed over time that when I add a bunch of stuff to swarm, the pusher in the node I'm adding it to stalls.  Restarting the node seems to restart the pusher.

While testing #791 I decided to see if I could track down what was causing this.  I did notice that disconnecting peers that had reset the stream while being pushed to seemed to break the pusher free, but only for a while, not permanently.

After adding a bunch of trace logs to pushsync's pushChunkToClosest, I determined that lots of chunks (probably up to 20, the value of pusher's concurrentJobs) had written the chunk but had not yet received their receipt.

Then I noticed that pushsync's sendChunkDelivery was using WriteMsgWithTimeout with a timeout of timeToWaitForReceipt (3 seconds).  But that was the only reference to the defined timeout value.  receiveReceipt was using ReadMsg, not ReadMsgWithTimeout.

I changed pushsync's receiveReceipt to use ReadMsgWithTimeout and referencing timeToWaitForReceipt and now my pusher has been running steady for 30+ minutes trying to catch up with the backlog.

pushsync's sendReceipt is invoking WriteMsg (no timeout), but I'm not sure if it should be changed to use the timeout or not.  It seems that if we're timing out on sendChunkDelivery, then sendReceipt should also probably timeout.  If it delays, the pusher will still hang once there are concurrentJobs (20) chunks "inflight".

**Comment by ldeffenb** [comment]
What I have not researched nor can I explain is why the receipt isn't coming back from the peer in a timely fashion (or not at all).

**Comment by janos** [comment]
Very nice findings. We should always have timeouts or context cancelation for message exchange both for reads and writes. Would you like to PR such changes for puhsync? For sendReceipt and receiveReceipt. I would even suggest to try to pass to that functions context, as that would be more correct, of course with adequate cancelation times.

**Comment by ldeffenb** [comment]
@janos Timeouts I can handle, I'm not that familiar with contexts (yet).  Can you point me to an example context with cancellation time that I can learn from?

**Comment by janos** [comment]
I can give an example how it could be handled with both context propagation, which is broken now with this messages and also to add a timeout for the specific context:

```diff
diff --git a/pkg/pushsync/pushsync.go b/pkg/pushsync/pushsync.go
index b0fae811..9d684a13 100644
--- a/pkg/pushsync/pushsync.go
+++ b/pkg/pushsync/pushsync.go
@@ -165,7 +165,7 @@ func (ps *PushSync) handler(ctx context.Context, p p2p.Peer, stream p2p.Stream)
        }
 
        // pass back the received receipt in the previously received stream
-       err = ps.sendReceipt(w, &receipt)
+       err = ps.sendReceipt(ctx, w, &receipt)
        if err != nil {
                return fmt.Errorf("send receipt to peer %s: %w", peer.String(), err)
        }
@@ -188,8 +188,10 @@ func (ps *PushSync) sendChunkDelivery(w protobuf.Writer, chunk swarm.Chunk) (err
        return nil
 }
 
-func (ps *PushSync) sendReceipt(w protobuf.Writer, receipt *pb.Receipt) (err error) {
-       if err := w.WriteMsg(receipt); err != nil {
+func (ps *PushSync) sendReceipt(ctx context.Context, w protobuf.Writer, receipt *pb.Receipt) (err error) {
+       ctx, cancel := context.WithTimeout(ctx, timeToWaitForReceipt)
+       defer cancel()
+       if err := w.WriteMsgWithContext(ctx, receipt); err != nil {
                ps.metrics.SendReceiptErrorCounter.Inc()
                return err
        }
@@ -299,7 +301,7 @@ func (ps *PushSync) handleDeliveryResponse(ctx context.Context, w protobuf.Write
 
        // Send a receipt immediately once the storage of the chunk is successfully
        receipt := &pb.Receipt{Address: chunk.Address().Bytes()}
-       err = ps.sendReceipt(w, receipt)
+       err = ps.sendReceipt(ctx, w, receipt)
        if err != nil {
                return fmt.Errorf("send receipt to peer %s: %w", p.Address.String(), err)
        }
```

Basically, pass the context, through the whole stack and also add WithTimeout before a specific (in sendReceipt) call.

**Comment by janos** [comment]
@ldeffenb I have just made such changes in https://github.com/ethersphere/bee/pull/811.

**Comment by ldeffenb** [comment]
I'll watch for these to merge into master and then update my nodes.  Thanks!
