### ISSUE TITLE
Missing metrics?

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#808]
While researching the pusher and pushsync, I noticed that they have declared metrics.  Having stumbled across the /metrics debugAPI earlier, I wondered why I didn't notice the pusher metrics.  Well, they aren't there!

Tracing back to how items get added to the /metrics display (via prometheus), I found that node.go doesn't add pusher nor pushsync, and it also doesn't add puller nor pullsync.

Is there a reason that these implemented metrics are not included?

**Comment by janos** [comment]
Thanks @ldeffenb, this is clearly missing, we will register these metrics in node.go.

**Comment by janos** [comment]
Actually, @zbiljic already prepared the PR https://github.com/ethersphere/bee/pull/809.

**Comment by zbiljic** [comment]
Just saw this issue. I noticed same thing. Created PR #809.

**Comment by ldeffenb** [comment]
Glad to know I was on the right track.
