### ISSUE TITLE
Integration testing multi version bee node support

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#813]
Supporting bee nodes with different versions in the same cluster is useful for testing backward (in)compatibilities or weaknesses.

Could we have a way to deploy aws clusters with different bee docker images? It would be good to have that for bee-staging install.sh or other scripts.

**Comment by Eknir** [comment]
Hi guys,

I think that this issue should get some more information, mostly about why we need this and what are acceptance criteria (I suggest using the `User Story` template. Then, we can make this into an epic, and put issues under it, which outlines what are the tasks towards completion. Let's discuss, I am happy to help!

**Comment by vandot** [comment]
Blocked by #814

**Comment by svetomir** [comment]
Resolved with the #814
