### ISSUE TITLE
Update libp2p dependencies

### ISSUE THREAD

**Issue by janos** [ethersphere/bee#815]
LibP2P libraries were updated with significant changes and module versions need to be updated.

However, `github.com/libp2p/go-libp2p-core v0.7.0` introduced some breaking changes (such as: `missing CloseRead method` and `undefined: helpers.FullClose`) and other modules need to catchup. New releases are being tagged these days and we should expect for compatibility to be done soon.

**Comment by acud** [comment]
updated in #1095
