### ISSUE TITLE
make lint fails if GOPATH isn't on path

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#816]
When I do a make on the latest version on ubuntu, I get the following error from the lint step.

ldeffenb@osm:~/bee$ make
go build -trimpath -ldflags "-s -w -X github.com/ethersphere/bee.commit=""1d57336""" ./...
which golangci-lint || curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
golangci/golangci-lint info checking GitHub for tag 'v1.30.0'
golangci/golangci-lint info found version: 1.30.0 for v1.30.0/linux/amd64
golangci/golangci-lint info installed /home/ldeffenb/gopath/bin/golangci-lint
golangci-lint run
make: golangci-lint: Command not found
Makefile:30: recipe for target 'lint' failed
make: *** [lint] Error 127

Every time I run the command, it re-installs golangci-lint.  So I checked:

ldeffenb@osm:~/bee$ which golangci-lint
ldeffenb@osm:~/bee$ which go
/usr/local/go/bin/go
ldeffenb@osm:~/bee$ go env GOPATH
/home/ldeffenb/gopath
ldeffenb@osm:~/bee$ echo $GOPATH
/home/ldeffenb/gopath
ldeffenb@osm:~/bee$ ls $GOPATH/bin/golangci-lint -al
-rwxr-xr-x 1 ldeffenb ldeffenb 24219648 Oct  7 10:35 /home/ldeffenb/gopath/bin/golangci-lint

My GOPATH is not on my path so which cannot find golangci-lint causing the re-installation.  But the invocation of golangci-lint is also not found causing the failure.  Should the invocation be qualified with $(go env GOPATH)/bin which is where the installation places it?

But that's not right either because someone might actually have it on their path and NOT in GOPATH/bin in which case the which will find it, but the explicit path will fail. There's a discrepancy between the which test (checking path) and the installation target ($(GOPATH)/bin) and the invocation (back to the path) which I think needs to be resolved.

I worked around the issue by just doing a "make binary" and running directly out of dist.

**Comment by janos** [comment]
The assumption was that users have GOPATH/bin in their PATH env variable. I do not think that there is a complete solution as users environments may have differences as you described. The solution to invoke `golangci-lint` binary with absolute path and to check if that file exists instead to use `which` command, may be good enough.

**Comment by Eknir** [comment]
@ldeffenb, thanks for raising this! If @janos answered your question, could you please close this issue?

**Comment by ldeffenb** [comment]
@Eknir I still think @janos comment below would make sense to implement.  I believe the Makefile should be checking and using the same location that it is installing to.

"The solution to invoke golangci-lint binary with absolute path and to check if that file exists instead to use which command, may be good enough."

**Comment by Eknir** [comment]
Adding it to the backlog.
