### ISSUE TITLE
Global Pinning does not work

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#841]
The existing global pinning stopped working because  of the  forward only chunk forwarding. As of the last testing in cluster, The PushToClosest was resetting the stream and the chunk was not able to repair.

## Acceptance criterea
Missing chunk should be uploaded to network and repaired

**Comment by Eknir** [comment]
Hi @jmozah , can you provide a bit more information? What is ` forward only chunk forwarding`, do you have a PR that introduced this regression? Do you have more information w.r.t the tests?

**Comment by jmozah** [comment]
yes. This  commit https://github.com/ethersphere/bee/commit/2f565f9f4599554535bbf10d9bf3fab450770509
@janos knows about this... This is the right thing to do but it breaks GP.

**Comment by janos** [comment]
Wa actually have chunkrepair integration test passing with this change on ci, and it is failing on real clusters with or without this change.

**Comment by jmozah** [comment]
> we actually have chunkrepair integration test passing with this change on ci,

That is a exception condition not taken care in beekeeper testcase...
but the global pinning fails every single time and i have checked it in the logs every single time...

> it is failing on real clusters with or without this change.

Nope.. It passes every single time in real cluster without this change the last i checked.

**Comment by janos** [comment]
Maybe I did something wrong in my tests on cluster. 

Just to restate my results on running chunkrepair test with https://github.com/ethersphere/bee/commit/2f565f9f4599554535bbf10d9bf3fab450770509 and also with the commit just before that one:

- fails on 3 node bee-staging cluster always
- passes on 3 node ci cluster as it is visible on master beekeeper runs
