### ISSUE TITLE
Tag total counter stays at zero

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#842]
# Task
The total counter in the tag stays zero when splitting is done. Previously, it was set to the value of split when splitting was done.

## Acceptance criterea

- The `tag.total` counter is set to `tag.split` when splitting is done
- Additional tests are created that would have caught this regression

**Comment by acud** [comment]
can't reproduce. created a bug report template. please adhere to the guidelines when opening a bug report
https://github.com/ethersphere/bee/pull/845

**Comment by Eknir** [comment]
This was because I needed to explicitly close the upload
