### ISSUE TITLE
Pair and document/assess: manifest and related API endpoints

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#858]
Pair and document/assess: keystore
 * * [x] planned
* Explainer: @zbiljic  
* Listener: @paxthemax

**Comment by Eknir** [comment]
@zbiljic, @paxthemax . Please your attention on that this is not yet planned. Are we postponing to next sprint?

**Comment by zbiljic** [comment]
@Eknir I communicated with @paxthemax to have meeting today (2020/10/30), which he mentioned on the daily, and which we already had. Some PR related to this should come soon.

**Comment by Eknir** [comment]
Great news! Thanks for the update

**Comment by Eknir** [comment]
Hi @paxthemax ,
Can we expect a PR from you, containing package documentation for this item?

**Comment by Eknir** [comment]
@paxthemax , I put this one in the active sprint again. Please decommission if you don't agree with this.
Do you know what is expected from you here?
