### ISSUE TITLE
too many open files 

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#867]
#### Summary
Failed to insert data using /bytes API

#### Steps to reproduce
Upload lots of chunks and bytes API

```
NFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.002203826 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=127 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000532294 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/debc48be7e8734bfb66a9ebe3c92c16510eecdae095e7dc43bfa871688e544dd user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000929785 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=128 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000478551 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/cca4d354a135f0ed7d1bd218ffdd2ad75e7faae419f24b2f74c1f33aabe243b9 user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000954828 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=128 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000394023 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/6e174e15242b938ec98c2d6573290c17d0a901fef052ed363807b2f05fdbb3fc user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.001828286 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=127 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000387292 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/3bfd5b8be921ba7c20113e2fc17fab52c07c000930362db69e153a21727540e4 user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.00072733 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=128 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000389914 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/19a8eeff2265f8533c91d308e7491f0368e9413ce50209ae274fddbf95dc001d user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000663361 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=127 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-25T05:24:55+05:30] api access                                    duration=0.000452411 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/4a4cafc372789ad45f19944a71e5a2db156f84dcdf6606976063ce6c5fed3565 user-agent=Go-http-client/1.1
ERRO[2020-10-25T05:24:55+05:30] http: Accept error: accept tcp [::]:8080: accept: too many open files; retrying in 5ms 

```

#### Expected behavior
API update works and the bytes gets inserted in Swarm

#### Actual behavior
Application returned an error  " too many open files"

**Comment by janos** [comment]
Hi, could you provide more information about which bee version are you using or the git hash that it is built at? Also the information on which operating system this happens is useful.

I am not able to reproduce the large number of open files by the bee process on macOS while uploading to data to /bytes and /chunks api endpoints.

I am validating the number of open files with `lsof -p 1234 | wc -l` where 1234 is the bee process id. And that number does not go higher than 182, for me.

Could you check what is the number of open files when you get the error and to attach the list to the issue, so that we can investigate further?

**Comment by jmozah** [comment]
@janos Sorry for not providing the context

- Its macOS Catalina 10.15.7
- bee version is 0.3.2-8bd9e28 (i did it in recent version just now)
- ulimit -a shows open file limit as 256 (this might be a issue, i will increase to 65535 and see)
- lsof -a -p $(pidof bee)  | wc -l shows 260

**Comment by janos** [comment]
Thanks @jmozah. We have open files limit for loveldb set to 128, which is not so much, but including network connections and state store open files, it could go to 260. Especially if network connections are left open after every http request to the api. We may want to set IdleTimeout on http.Server to something like 30s, currently it is not set. MaxHeaderTimeout is also good to have it specified, just in case.

**Comment by jmozah** [comment]
ok. I increased the ulimit to 65535.. i was able to do lots of uploads...
but even after the uploads are over.. the fd's are open.. in ESTABLISHED state...

**Comment by jmozah** [comment]
> Especially if network connections are left open after every http request 

I suspect this is happening at my client...  But we should guard bee irrespective of stupidly written clients which can eat up all http connections. Your suggestions are good to implement.

**Comment by janos** [comment]
Cool, I have created a small PR for that https://github.com/ethersphere/bee/pull/869.

**Comment by Eknir** [comment]
@jmozah , could you be so kind to validate whether #869 is a fix for the issue you described?

**Comment by Eknir** [comment]
@jmozah , bump

**Comment by janos** [comment]
I have tested it locally with various ulimit values and extensive uploads. This change reduces the number of open files resulting stability on more restrictive vlues.

**Comment by jmozah** [comment]
@Eknir i could not test this now as i fixed my client to close the connection and not hold the fd. 
It worked fine without the fix if the client behaves well.
