### ISSUE TITLE
Tag already exists

### ISSUE THREAD

**Issue by jmozah** [ethersphere/bee#877]
#### Summary
While uploading lots of file using the /bytes and /chunks API, i get the following error almost always.
```
INFO[2020-10-27T19:38:53+05:30] api access                                    duration=0.000838421 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/0bbbf541813c4a92394a219dc9694f64dcce7609d9e25ddb8cc2c1e0c2b6f498 user-agent=Go-http-client/1.1
INFO[2020-10-27T19:38:53+05:30] api access                                    duration=0.003411815 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=128 status=200 uri=/bytes user-agent=Go-http-client/1.1
INFO[2020-10-27T19:38:53+05:30] api access                                    duration=0.000646409 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=53 status=200 uri=/chunks/465307e0cc6cbbf3668f69031b877dc9db77e90e4af62434b2ed6709b4c6c403 user-agent=Go-http-client/1.1
INFO[2020-10-27T19:38:53+05:30] api access                                    duration=0.004036734 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=127 status=200 uri=/bytes user-agent=Go-http-client/1.1
DEBU[2020-10-27T19:38:53+05:30] chunk upload: get or create tag: cannot create tag: already exists 
ERRO[2020-10-27T19:38:53+05:30] chunk upload: get or create tag              
INFO[2020-10-27T19:38:53+05:30] api access                                    duration=0.000234339 ip=127.0.0.1 method=POST proto=HTTP/1.1 size=75 status=500 uri=/chunks/1dc117d6aa43a7548a69e972e0dba9b7c82c6df7dd2b6a0ad680ff496dd1b29a user-agent=Go-http-client/1.1
```

#### Steps to reproduce
upload many files using /bytes and /chunks API

#### Expected behavior
bee should accept the data and return http 200

#### Actual behavior
i am getting a status 500, with the above log

#### Other Informations

OS: macos catalina  10.15.7
go version go1.14.2 darwin/amd64
bee version: 0.3.2-8bd9e28
API Headers did not contain any tags-id while sending (so it should create a temp tag internally).
/bytes has encryption and pin headers with ~20K size
/chunks has only pin header

Please let me know if you need any other information

**Comment by jmozah** [comment]
Most likely it is a rando number collision `TagUidFunc()`

**Comment by janos** [comment]
This is correct, we do not cleanup tags and the collision probability raises with the number of uploads. We should have greater space for random id generation. To make id a byte slice instead of uint32.

**Comment by jmozah** [comment]
Bump. I am getting this quite often nowadays.

**Comment by Eknir** [comment]
#985 is related

**Comment by Eknir** [comment]
It was decided today to proceed with fixing this bug by not letting the `chunks` endpoint to automatically generate a new tag for each call.
This way, you are less likely to get into collisions. #1084 (point 7) defines also that we implement a GET endpoint on tags, which will help you to delete existing tags in order to create more space.

**Comment by Eknir** [comment]
@jmozah , would be great if you can do some QA on this issue. Is it fixed?

**Comment by Eknir** [comment]
@significance is going to validate if nothing needs to change in our docs. Just to be sure.
