### ISSUE TITLE
Pullsync test fails on infra tests

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#878]
#### Summary
Every execution of infra tests fail with pullsync. Error logs from the [last run](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221603851900000%22,%221603853082000%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22,stream%3D%5C%22stderr%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) 

#### Steps to reproduce
Ping me if you want to test it on infra-tests env

#### Expected behavior
All tests should pass

#### Actual behavior
Test fail with `Error: pull sync` log

**Comment by janos** [comment]
As pull sync logic will change because of the push sync changes, we should not spend time on fixing this check as it is. This should be fixed alongside the changes to syncing strategies changes. We should prioritize improvements to syncing strategies.

**Comment by Eknir** [comment]
Hi @janos , I'm not so sure about your comment here. As far as my understanding goes there are currently no planned change in the pull sync strategy (only #818). 

Could you help me to assign this issue a priority in the bugs board?

**Comment by janos** [comment]
@Eknir if we are not gonna change the syncing strategy, this is a high priority issue.

**Comment by vandot** [comment]
After fixing `pushsync` and `retrieval` test fails we are back to `pullsync` fails.
Last run [logs](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221605664530422%22,%221605665197587%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

**Comment by acud** [comment]
@vandot i think that the last change to the pull sync tests should do the trick. have you seen any failures after we tagged the last version?

**Comment by vandot** [comment]
@acud pullsync still fails but now we have a new typo of error
`Upload node 0. Chunk: 1. Chunk does not have any designated replicators.`
```
	
2020-11-22 03:10:27	
Error: pull sync
	
2020-11-22 03:10:27	
Upload node 0. Chunk: 1. Chunk does not have any designated replicators.
	
2020-11-22 03:10:27	
Upload node 0. Chunk: 1. Closest: 15 64f5a7f3833d4a0574d34d5c7cb56f0405775f282722de3ce1f51a9c35bffd05
	
2020-11-22 03:10:27	
Uploaded chunk 60f9e68a6e9c8226fa905a8c5cd8c18632774d2f2f2446dd7af5211fc4318308
	
2020-11-22 03:10:27	
Chunk replication factor 5
	
2020-11-22 03:10:21	
Chunk should be on 3 nodes. 3 within depth
	
2020-11-22 03:10:21	
Upload node 0. Chunk: 0. Closest: 5 51fc2de2afd0eefb7f0e0da76355f202970105f08fb9eb29ca4e6d7fa7b5e5a6
	
2020-11-22 03:10:21	
Uploaded chunk 5d36c82314d7af8979ae6d37021376e62e22a71db3de708628f482a65ede1391
	
2020-11-22 03:10:21	
Seed: 6379784125030364356
	
2020-11-22 03:10:20	
*** PULLSYNC ***
```
Logs from [last run](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221606010635000%22,%221606011076370%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

**Comment by vandot** [comment]
Again same error -> [logs](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221606183568627%22,%221606183960880%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)
```
Upload node 0. Chunk: 0. Chunk does not have any designated replicators.
Error: pull sync
```

**Comment by vandot** [comment]
Again same errot -> [logs](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221606269969776%22,%221606270455487%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D)

```
Upload node 1. Chunk: 2. Chunk does not have any designated replicators.
Error: pull sync
```

**Comment by acud** [comment]
closing this, as pull sync tests are now disabled
