### ISSUE TITLE
task: improve test time on p2p package

### ISSUE THREAD

**Issue by acud** [ethersphere/bee#88]
# Task
Our `p2p/libp2p` abstraction tests take too long to complete (10-15s locally)
Also, `p2p/protobuf` takes 5 seconds to complete

## Acceptance criteria 
Improved execution time of test suite

**Comment by acud** [comment]
@pradovic i just saw this on some localstore related PR:
```
    --- PASS: TestWriter/NewWriterAndReader (0.00s)
=== RUN   TestWriter_timeout
=== RUN   TestWriter_timeout/NewWriter
=== RUN   TestWriter_timeout/NewWriter/WithContext
=== RUN   TestWriter_timeout/NewWriter/WithTimeout
=== RUN   TestWriter_timeout/NewWriterAndReader
=== RUN   TestWriter_timeout/NewWriterAndReader/WithContext
=== RUN   TestWriter_timeout/NewWriterAndReader/WithTimeout
##[error]    TestWriter_timeout/NewWriterAndReader/WithTimeout: protobuf_test.go:266: timeout
--- FAIL: TestWriter_timeout (2.68s)
    --- PASS: TestWriter_timeout/NewWriter (1.36s)
        --- PASS: TestWriter_timeout/NewWriter/WithContext (0.60s)
```
I don't know if you wanna look into it as part of this PR or should we have a separate issue?

**Comment by pradovic** [comment]
Might be related, I think the place of `time.Sleep()` in protobuf tests was a bit less well placed, so the fix might this as well.
