### ISSUE TITLE
Push sync pushes chunks twice

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#885]
#### Summary

Push sync is seemingly pushing chunks twice without reason

#### Steps to reproduce

This is reproducible when starting 2 fresh nodes locally, connecting them together and uploading some content to one of them 

#### Actual behavior

```
TRAC[2020-10-26T11:52:22+01:00] pusher pushed chunk 03aa8466da882a29ea24e51f3f61183e1f749f4e7376754f86a40f37a9f54e1a 
TRAC[2020-10-26T11:52:22+01:00] pusher pushed chunk 687e89a8d2c9e8b8b299cb7bb5da1bf7f34d14a452546eaa5aa97d625008117d 
TRAC[2020-10-26T11:52:22+01:00] crediting peer 1fa1cb1814b2ad643e5841d6707fcfe11dd240841a493a18969e7eeda9bd32b7 with price 160, new balance is -6400 
DEBU[2020-10-26T11:52:22+01:00] localstore: chunk with address 80353183ad91cb4447b4c29b1bb2cacc55e922a2b1554dcbc337402b103d0b72 not found in push index 
TRAC[2020-10-26T11:52:22+01:00] pusher pushed chunk 80353183ad91cb4447b4c29b1bb2cacc55e922a2b1554dcbc337402b103d0b72 
TRAC[2020-10-26T11:52:22+01:00] crediting peer 1fa1cb1814b2ad643e5841d6707fcfe11dd240841a493a18969e7eeda9bd32b7 with price 130, new balance is -6530 
DEBU[2020-10-26T11:52:22+01:00] localstore: chunk with address 03aa8466da882a29ea24e51f3f61183e1f749f4e7376754f86a40f37a9f54e1a not found in push index 
TRAC[2020-10-26T11:52:22+01:00] pusher pushed chunk 03aa8466da882a29ea24e51f3f61183e1f749f4e7376754f86a40f37a9f54e1a 
```

**Comment by Eknir** [comment]
Steps to fix:
- [ ] Revert #827
- [ ] Beekeeper tests that would have caught this regression
- [ ] re-implement #827,but then without the regression

**Comment by Eknir** [comment]
Hi @zbiljic ,

Could you give me a heads-up on the status of this?

**Comment by zbiljic** [comment]
Sure thing @Eknir. I planned to continue with these steps, however in the period before last release there were too many problems with some Beekeeper tests, especially in regard to this, and I felt it would not be prudent to introduce some changes which might end up causing additional problems, and delaying release any more (than it already was last-minute).
