### ISSUE TITLE
Additional coverage for swap functions

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#889]
For swap, several functions need unit test coverage:

swap/addressbook.go functions
chequebook.LastCheques
chequestore.LastCheques
swap.TotalSent
swap.TotalReceived
swap.SettlementsSent
swap.SettlementsReceived
swapprotocol.init
swapprotocol.EmitCheque

**Comment by Eknir** [comment]
@metacertain , I will move this one to decomissioned.

**Comment by Eknir** [comment]
@metacertain , how are you progressing on this one in this sprint?
