### ISSUE TITLE
Setup ci pipeline for postage smart contract

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#902]
# Task
- Setup ci pipeline for postage smart contract

## Acceptance criterea

- CI pipeline set-up
  - unit tests run on every pr and merge on master
  - coverage run on every pr and merge on master
  - linting run on every pr and merge on master
  - go bindings are generated and pushed on release tags

**Comment by Eknir** [comment]
@ralph-pichler , could you please formulate better acceptance criteria here?

**Comment by ralph-pichler** [comment]
@Eknir done, but this should probably be multiple issues

**Comment by Eknir** [comment]
@paxthemax , I think we concluded together to temporarily de-prioritize this one, right? At least until the whole storage incentive is more stabilized and mature. 

If that is the case, could you please be so kind to move this issue to the Icebox?

**Comment by ralph-pichler** [comment]
At the very least the scripts to generate the bindings should be in the repo before this is ever used on the go side. Ideally though we also generate those already automatically as manually calling them can lead to human error (e.g. running it on wrong branch or with pending changes, this actually happened when we implemented swap and caused quite a few hours of headache).
