### ISSUE TITLE
`init` command

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#910]
# Task
Create `init` command that will generate all keys, write them to disk and exit with 0 if task was successfully executed and with 1 if failed for some reason.
## Acceptance criterea
- run `bee init` with empty data folder and all keys should be generated
- run `bee init` with already generated keys in data folder and `bee` should just exit
- run `bee init` with external signer enabled only `libp2p` key should be generated

**Comment by Eknir** [comment]
Hi @ralph-pichler , is this still on your radar?
