### ISSUE TITLE
Introduce Variable Pricing

### ISSUE THREAD

**Issue by metacertain** [ethersphere/bee#912]
# Epic
## Story
- As a forwarding node, I want that my node chooses economical prices, such that I am making a profit on forwarding and my node is not too expensive, causing it to be avoided by peers.
- As a final consumer of bandwidth, I want that my node chooses decently priced peers to forward my requests to, such that I don't overpay on bandwidth incentives.

## Background
At the moment pricing is inverse linear to proximity order.
This epic changes it to be based on our own supply price and target profit baseline.

**Comment by Eknir** [comment]
Duplicate of #134
