### ISSUE TITLE
Get value of chunks

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#920]
# Story
As a storer node, I want to have an up-to-date representation of the value of all chunks that I store in my _reserve_, such that I can use this information to decide on which chunks to discard and what chunks to keep.

# Background
There exists an architecture proposal https://hackmd.io/o8RGsNwZSN6IE0lkBAZCPw, which most likely will be changed based on changes in the postage stamp smart contract ([see](https://hackmd.io/tvacCgfBSWmeConc3rFOtw)). 

The reserve is the name of storage space dedicated to chunks in the node’s area of responsibity.

# Acceptance criteria
- For all chunks that a node is storing as part of his _reserve_, the node knows the value

**Comment by Eknir** [comment]
@zelig , I am adjusting this epic to be more user-focused, such that it is generic of the particular implementation. Changes in https://hackmd.io/tvacCgfBSWmeConc3rFOtw most likely require also changes in implementation. We would like to discuss this with you on Monday.

**Comment by acud** [comment]
@Eknir can we close this epic? all issues associated with it are closed and I don't see much value in keeping this open
