### ISSUE TITLE
Upload status bar not working as expected with gateway

### ISSUE THREAD

**Issue by crtahlin** [ethersphere/bee#925]
#### Summary
When uploading a large file (2GB +) via the gateway (https://gateway.ethswarm.org/) the "uploadad" status stays at 0% until the file is uploaded, then it jumps to 100%, while still waiting for hash.

#### Steps to reproduce
Download a Linux ISO file, use https://gateway.ethswarm.org/ to upload. Wait and observe ...

#### Expected behavior
I would expect the upload status to change with the progress of the upload continously (least once a couple of seconds). I would also expect the status to rest (or a separate status percentage shown) for the status of the hashing procedure, as it is also quite long.

#### Actual behavior
Status is just binary - either 0% or 100%.

**Comment by Eknir** [comment]
Hi @crtahlin ,

Thank you for reporting this bug. I'm tagging @significance (you know the gateway best of us all). 

Also @agazso, @vojtechsimetka , they are working in the javascript team and they might find this experience of you relevant, when planning an upgrade to the gateway.

Thanks again.

**Comment by Eknir** [comment]
@significance , could you tell me if this bug is reproducible and then assign it a priority (let me know if you need my input here)?

**Comment by Eknir** [comment]
Closing this issue, as we are currently working on revamping the gateway completely.
