### ISSUE TITLE
Chunk traversal

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#927]

**Comment by zbiljic** [comment]
Not sure if this needs to be documented for the users. This is only for some internal process that is responsible for finding addresses for some root chunk. Nothing in the related PR is user-facing.

Of course, if want to have documentation how the bytes/files/collections are stored in Bee, that is nice, however that is not related to this and should be separate issue by itself. At least this is my opinion.

**Comment by Eknir** [comment]
I agree with you @zbiljic . Moving the column to `no documentation needed`
