### ISSUE TITLE
API Documentation not up-to-date with implementation

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#937]
#### Summary

Last weeks, I got two independent complaints that our API documentation is not in line with the implementation. 

@agazso, @vojtechsimetka , please leave a comment to this issue with your specific issue.

I suspect that our API docs are not consistent at other points as well.

Completion of this issue is fixing the issues from @agazso and @vojtechsimetka , and going over our complete API specs, giving it additional love and ensure that it is consistent,

**Comment by agazso** [comment]
At the [Get Referenced File](https://docs.ethswarm.org/api/#tag/File/paths/~1files~1{reference}/get) endpoint the information that the filename is returned in a `content-disposition` header is missing.

**Comment by agazso** [comment]
At the [Upload File](https://docs.ethswarm.org/api/#tag/File/paths/~1files/post) it would be good to mention that the `content-type` header content will be preserved when downloading the referenced file.

**Comment by significance** [comment]
it would be good to complete a full review of this 🏄

**Comment by vojtechsimetka** [comment]
The API documentation for tags is wrong. The parameter name is not required and actually does not work at all.

**Comment by Eknir** [comment]
@metacertain ,
Could you please manage this issue? You can drag it to done in the core: Backlog pipeline if finished. If not finished, it would be good to fix this in the upcoming sprint.
Thanks
