### ISSUE TITLE
content arriving via push/pull sync will not garbage collect

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#949]
#### Summary
https://github.com/ethersphere/bee/pull/908 introduces a bug as a result of which chunks arriving to localstore via push or pullsync wont garbage collect.  

#### Steps to reproduce
???

#### Expected behavior

 chunks arriving to localstore via push or pullsync should be able to garbage collect.
`ModePutSync` should put item in gc index.

#### Actual behavior
`ModeSetSync` and `ModeSetSyncPull` called after a chunk is push synced (https://github.com/ethersphere/bee/blob/master/pkg/pusher/pusher.go#L143, https://github.com/ethersphere/bee/blob/master/pkg/pusher/pusher.go#L202) or pull synced used to correctly put it in the gc.  

`ModePutSync` which is called when   a chunk arrives via push sync (https://github.com/ethersphere/bee/blob/master/pkg/pushsync/pushsync.go#L300) does not.   before this PR such a chunk would still be pull synced and therefore eventually put to gc by `ModeSetSyncPull`, this no longer happens. 

https://github.com/ethersphere/bee/blob/master/pkg/pullsync/pullsync.go#L338

Likewise content arriving via pull sync is not push synced so it will not garbage collect. 
https://github.com/ethersphere/bee/blob/master/pkg/pullsync/pullsync.go#L215
before this PR such a chunk would still be pull synced and therefore eventually put to gc by `ModeSetSyncPull`, this no longer happens. 

the fix can be found here https://github.com/ethersphere/bee/pull/933/files#diff-b7ea289d114aa7c53f783c76af94da3348b5093e10182a57d89826a5ede1d4c3R249

**Comment by janos** [comment]
This is true. It is strange that putSync https://github.com/ethersphere/bee/blob/master/pkg/localstore/mode_put.go#L241 is returning gcSizeChange which suggests that this method may have expected behaviour in the past. Maybe we should bring back putToGCCheck as it was handling these cases.

**Comment by acud** [comment]
We should just add to gc index on `ModePutSync`, if i understand correctly. about the signature, i think that in the past this method was actually putting the chunk into the GC index, but we probably removed this when we figured it possibly undermines replication guarantees on nodes that actively garbage collect

**Comment by Eknir** [comment]
Do we have integration tests that validate this?
