### ISSUE TITLE
Retrieval test fails on infra and github action tests

### ISSUE THREAD

**Issue by vandot** [ethersphere/bee#950]
#### Summary
Retrieval test fails on both [infra](http://kubernetes-grafana.staging.internal/explore?orgId=1&left=%5B%221605578270378%22,%221605578819751%22,%22Loki%22,%7B%22expr%22:%22%7Bnamespace%3D%5C%22infra-test-beekeeper%5C%22%7D%22%7D,%7B%22mode%22:%22Logs%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D) and [github action](https://github.com/ethersphere/bee/runs/1410473366?check_suite_focus=true) tests

#### Steps to reproduce

Ping me if you want to test it on infra-tests env, or rerun [github action workflow](https://github.com/ethersphere/bee/runs/1410473366?check_suite_focus=true)
#### Expected behavior

All tests should pass
#### Actual behavior

Retrieval test fails with message
```
Node 0. Chunk 0 not retrieved successfully. Uploaded size: 548 Downloaded size: 540 Node: ad5c25cbc744735bd778dbf16259f5612a75ba301cad49846eeb7d3eaa93ea6f Chunk: 0c17a2e3c0d5754c271b9d6f5985ba29ac10b798d6788f7716124826389b61f2
Downloaded data is subset of the uploaded data
```

**Comment by acud** [comment]
should be fixed by https://github.com/ethersphere/beekeeper/pull/68

**Comment by vandot** [comment]
It passed for [github actions](https://github.com/ethersphere/bee/runs/1411808667?check_suite_focus=true)
I will run infra tests now

**Comment by vandot** [comment]
Retrieval is passing on infra tests
