### ISSUE TITLE
localstore: spurious key length in pull index

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#952]
Length here reflects an earlier state of the code when hash was part of the key, 41 should be 9 now.
https://github.com/ethersphere/bee/blob/master/pkg/localstore/localstore.go#L268

**Comment by Eknir** [comment]
Hi @janos , I see this is assigned high priority, but it is in the decommissioned pipeline. Could you please have a look? Thanks.

**Comment by janos** [comment]
@Eknir we concluded on code freeze planing that this should not be addressed in this release, as migration would require more time for proper testing. This issue is not a functional one. It just uses longer keys in database than needed, which should be fixed, but is not urgent.
