### ISSUE TITLE
Allow setting changing pin counter of some chunk

### ISSUE THREAD

**Issue by zbiljic** [ethersphere/bee#955]
# Task

Relates to #824 

We should support setting pin counter to 0 for some chunk.

## Acceptance criterea

User should be able to change pin counter for specific chunk.

**Comment by Eknir** [comment]
This needs documentation. The moral of this story is that we allow external processes to manage the pins of the Bee process. Setting the pin counter to 0 is something pretty drastic and should not be done if the user is not absolutely sure that the content of the chunk does not belong to another piece of content that was pinned by the user.

**Comment by jmozah** [comment]
pin counter is something internal and in my opinion should not be exposed to outside world. From the user perspective it should be pin OR unpin...

**Comment by Eknir** [comment]
Issue moved to doesn't need documentation. The API docs are already up-to-date and it doesn't fit well into the narrative of current documentation on pinning to add details w.r.t. the pincounter.

**Comment by Eknir** [comment]
> pin counter is something internal and in my opinion should not be exposed to outside world. From the user perspective it should be pin OR unpin...

We want to allow the user the freedom to individually manage the pin counters.
