### ISSUE TITLE
Packaging CLEF

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#967]
# User story

## Story

- As a user of Bee, I want to run my Bee package with CLEF with minimal effort, such that I can reuse the Ethereum key of my node on mainnet and my keys are secure.

## Acceptance criteria

- Acceptance criteria t.b.d. . At the very minimum, there should be documentation on how to run Bee and manage CLEF yourself. Ideally, CLEF should be released as a package (beeCLEF), which is installed together with the installation of the Bee package.

## Background

As we are moving towards running a real incentivized testnet, we should nudge our users to follow best practices. They keys of our users will soon hold real value, thus must be easily accessible (on Ethereum mainnet) and securely stored.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
@vandot @ralph-pichler @janos, could you please adjust the issue and provide more detail.

Let's decide tomorrow around noon what we will do with this.

**Comment by Eknir** [comment]
@vandot , this one is done? Could you give me the PR that finished this, I'll connect it for you to the issue. Thanks

**Comment by vandot** [comment]
I just merged it into master https://github.com/ethersphere/bee/pull/982
