### ISSUE TITLE
Timeout on insufficient funds

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#970]
# Task
When the Bee node notices that there are insufficient funds, we should not immediately return an error, but instead wait for some time (e.g. 30 seconds). The message to the user (while waiting) should instruct the user to fund his Ethereum address

## Acceptance criterea

- I can run fund my node and immediately afterwards run the node successfully

**Comment by ldeffenb** [comment]
This worked well for me earlier this morning.  I followed the instructions at https://hackmd.io/n-7fTnBnRv6WS5b59ViokA but neglected to do the funding before the start.  Bee just sat there telling me to fund <my address> periodically until I actually did the funding at which point the checkbook contract was created and the node finished it's startup.

Nicely done IMHO!

**Comment by Eknir** [comment]
Perfect @ldeffenb ! @ralph-pichler , since this issue is already finished, could you please attach the PR and move the issue to the respective board? 
Thanks
