### ISSUE TITLE
Cashout of outstanding cheques

### ISSUE THREAD

**Issue by Eknir** [ethersphere/bee#971]
# User story

## Story

As a cheque-recipient, I want to cash out all cheques which I own which are worth more than a certain amount, such that I the money which I earned is available on-chain and I decrease the risk of holding on to uncashed cheques.

## Acceptance criteria

- User can run a command (internally to the Bee or externally) that cashes out all cheques
- The feature is properly documented @significance 

## Background

User will want to do this, once we have an incentivized network. @ralph-pichler suggested that a shell script would probably be best.

## Tasks

| Task | Assignee |  Done (1), or 0 |
| ------ |------------| -----|

**Comment by Eknir** [comment]
Completed per: https://gist.github.com/ralph-pichler/3b5ccd7a5c5cd0500e6428752b37e975

**Comment by Eknir** [comment]
@paxthemax , could you please review this and maybe pair together with @significance , to ensure this gets a place in our docs as well?

**Comment by Eknir** [comment]
@significance , bump :)

**Comment by Eknir** [comment]
Running this command now with @GasperX93 . He encountered a problem that he doesn't have jq. Would it be possible to make this command without jq @ralph-pichler ?

**Comment by Eknir** [comment]
When we run cashout.sh list-uncashed it works as expected 

When we run cashout.sh cashout-all , we see one output (`cashout out cheque for in transaction null`). Afterwards it blocks. @ralph-pichler , any idea what went wrong?

**Comment by Eknir** [comment]
Update. We didn't run `cashout-all`, but `cashout`. Seems to work now. Great!

**Comment by ralph-pichler** [comment]
@Eknir can't do the command without jq as we need to parse the json responses from bee. in `cashout` you probably omitted the peer leading to this. there is very little sanity checking on the user input.

**Comment by Eknir** [comment]
This needs documentation.
The moral of this story is that cashing out cheques is a manual operation. In order to make this easier, we provide a simple [script](https://gist.github.com/ralph-pichler/3b5ccd7a5c5cd0500e6428752b37e975) that makes cashing out many cheques easier.
