### ISSUE TITLE
Create Tag API returns 201 on success

### ISSUE THREAD

**Issue by ldeffenb** [ethersphere/bee#983]
#### Summary
POST /tags returns a 201, not 200 as shown in API documentation from https://docs.ethswarm.org/api/#tag/Tag

#### Steps to reproduce
curl -X POST http://127.0.0.1:8080/tags --verbose

shows HTTP/1.1 201 Created

#### Expected behavior
API documentation implies that 200 is the successful return status

#### Actual behavior
Received a 201 status indicating success

>curl -X POST http://127.0.0.1:8080/tags --verbose
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> POST /tags HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 201 Created
< Cache-Control: no-cache, private, max-age=0
< Content-Type: application/json; charset=utf-8
< Date: Thu, 19 Nov 2020 21:42:03 GMT
< Content-Length: 173
<
{"total":0,"split":0,"seen":0,"stored":0,"sent":0,"synced":0,"uid":3655876072,"name":"unnamed_tag_1605822123","address":"","startedAt":"2020-11-19T16:42:03.2505345-05:00"}

**Comment by Eknir** [comment]
@metacertain , could you please try to reproduce this bug, and manage the bug in our board accordingly? I would say that if this is reproducible, it would be good to fix in the upcoming sprint.

**Comment by metacertain** [comment]
This was addressed in the release of 0.4.0, you can view the current state here
 https://docs.ethswarm.org/api/#tag/Tag
