### ISSUE TITLE
pss tasks [technical debt]

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#996]
remaining pss tasks, to submit independent of #974 

- implemented in #960 :
  - remove context from pss.unwrap - https://github.com/ethersphere/bee/pull/942#discussion_r522792838 
  - introduce cancel for the handler routines conditioned on `pss.Close` (closed quit channel)
- implement proximity check in `pss.TryUnwrap` in alignment with the target length used by send

```go 
if po(baseAddr, chunkAddr) < targetMaxLength*8` { return } 
```
- tests that use shorter target and use TryUnwrap will fail to deliver

**Comment by Eknir** [comment]
@zelig , given that you mentioned in today's sprint planning that you want to tackle #974, I suppose that this one should be tackled as well? Based on what you write in #974

**Comment by Eknir** [comment]
Adding this to the active sprint, based on that. Please decommission if my analysis is incorrect.
