### ISSUE TITLE
ECDH clef support for pss (and ACT)

### ISSUE THREAD

**Issue by zelig** [ethersphere/bee#997]
- [ ] PR ECDH support in clef 
   - https://github.com/nagydani/go-ethereum/commit/6f310757067f354178f8624821585ed11c44dad0
   - https://github.com/nagydani/go-ethereum/commit/b98946623944fedaa61ae83d8695f5e122210292
- [ ] extend signer to accomodate clef ECDH
   -  https://github.com/ethersphere/bee/blob/master/pkg/crypto/clef/clef.go

**Comment by Eknir** [comment]
@zelig , are we supposed to take the commits of @nagydani and complete this?
