### ISSUE TITLE
Uploading a tar file may end up in a redirect loop

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee#999]
#### Summary
I uploaded a tar file and when I tried to access it I ended up with a redirect loop.

#### Steps to reproduce

Here is the tarfile I used
https://bee-0.gateway.ethswarm.org/files/6564a495efaff7ffc1bdf5f4f050458e59c96abf8658ba65afdbc06731a6e588

It has `.DS_Store`, `._.` and `._.DS_Store` files inside that's likely to cause this issue. According to @vandot if you delete these files and upload the resulting tar file, it will work.

Command I used to upload:
```sh
curl \                                                                                                           
    -X POST -v -D - \
    -H "Content-Type: application/x-tar" \
    -H "Swarm-Index-Document: index.html" \
    -H "Swarm-Error-Document: index.html" \
    --data-binary @/Users/attila/Downloads/website.tar https://gateway.staging.ethswarm.org/dirs
```
#### Expected behavior
There shouldn't be a redirect loop when I upload a website. It should be checked on upload and rejected.

**Comment by vojtechsimetka** [comment]
There must be other issues as well. I just prepared a tar file that does not contain any hidden file, yet it causes the redirects.

**Comment by agazso** [comment]
> There must be other issues as well. I just prepared a tar file that does not contain any hidden file, yet it causes the redirects.

@vojtechsimetka Can you upload the file in question so that the issue can be reproduced?

**Comment by vojtechsimetka** [comment]
Yeah even better I know why. The difference is between how the files are tar-ed:

**Causes redirects**
```
tar -cvC folder . >archive.tar
```

**Works just fine**
```
cd folder
tar -cf ../archive.tar *
cd ..
```

Here are are the two archives https://www.dropbox.com/sh/e8unt7kh2qu7b88/AAAuSaUGdg7QcL5EXrjVpr7Da?dl=0

I'm using build in macOS tar in version `bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6`

**Comment by vandot** [comment]
Second file is properly tared, only content from the folder.
First file included folder `.` and all content inside that folder.
You can see that slight diff when you list tar files contents
```
# tar -tvf cases_redirects.tar
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 ./
-rw-r--r--  0 vojtechsimetka staff   32038 Nov 23 22:47 ./favicon.ico
-rw-r--r--  0 vojtechsimetka staff     769 Nov 23 22:47 ./index.html
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 ./css/
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 ./js/
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 ./media/
-rw-r--r--  0 vojtechsimetka staff   34916 Nov 23 22:47 ./media/bzzzzzz.08b5b431.mp3
-rw-r--r--  0 vojtechsimetka staff   16344 Nov 23 22:47 ./media/bzz.cd2b9ec8.mp3
-rw-r--r--  0 vojtechsimetka staff  206108 Nov 23 22:47 ./js/chunk-vendors.49547d05.js
-rw-r--r--  0 vojtechsimetka staff  996904 Nov 23 22:47 ./js/chunk-vendors.49547d05.js.map
-rw-r--r--  0 vojtechsimetka staff   26830 Nov 23 22:47 ./js/app.e22050d2.js.map
-rw-r--r--  0 vojtechsimetka staff    9316 Nov 23 22:47 ./js/app.e22050d2.js
-rw-r--r--  0 vojtechsimetka staff    2157 Nov 23 22:47 ./css/app.a486b3e2.css

# tar -tvf works_fine.tar
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 css/
-rw-r--r--  0 vojtechsimetka staff    2157 Nov 23 22:47 css/app.a486b3e2.css
-rw-r--r--  0 vojtechsimetka staff   32038 Nov 23 22:47 favicon.ico
-rw-r--r--  0 vojtechsimetka staff     769 Nov 23 22:47 index.html
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 js/
-rw-r--r--  0 vojtechsimetka staff  206108 Nov 23 22:47 js/chunk-vendors.49547d05.js
-rw-r--r--  0 vojtechsimetka staff  996904 Nov 23 22:47 js/chunk-vendors.49547d05.js.map
-rw-r--r--  0 vojtechsimetka staff   26830 Nov 23 22:47 js/app.e22050d2.js.map
-rw-r--r--  0 vojtechsimetka staff    9316 Nov 23 22:47 js/app.e22050d2.js
drwxr-xr-x  0 vojtechsimetka staff       0 Nov 23 22:47 media/
-rw-r--r--  0 vojtechsimetka staff   34916 Nov 23 22:47 media/bzzzzzz.08b5b431.mp3
-rw-r--r--  0 vojtechsimetka staff   16344 Nov 23 22:47 media/bzz.cd2b9ec8.mp3
```
I agree that bee should handle that case as well, even by rejecting the illegal file or just mentioning it in the docs unlimited redirects case etc

**Comment by janos** [comment]
This could be handled with https://golang.org/pkg/path/filepath/#Clean on every tar path when read and with a special check on `"./"` and `"."` values.

**Comment by Eknir** [comment]
Hi @agazso @zbiljic 

How does this issue related to #1026 and #1024 and the PR #1027 ?

Generally, it would be great if we could move the respective issues to the correct place in our boards, close duplicates and make conclusions / tangible issues under threats that were posed as a question.

Could the issue authors of above-mentioned issues do this?

Thanks

**Comment by zbiljic** [comment]
Going from this issue, per @janos comment, the `filepath.Clean` was implemented and merged. There is comprehensive comment in the PR ([1027#issuecomment-740502562](https://github.com/ethersphere/bee/pull/1027#issuecomment-740502562)) that covers some details.

However, I think that main discussion should be done on #1024, where we should try to cover all the cases (that we can), and then rest the issue.

**Comment by Eknir** [comment]
Closing this issue
